Repository pharo-project/pharo, pull requests merged in 2019-09, with the labels that each got.

#4421 4419-WeakValueDictionaryrehash-is-breaking-weak-associations
  src/Collections-Tests/WeakValueDictionary.extension.st
  src/Collections-Tests/WeakValueDictionaryTest.class.st
  src/Collections-Weak/WeakValueDictionary.class.st
Labels: tests passed please review!

#4371 4370-Trait-composition-slots-method-contains-duplication
  src/Collections-Sequenceable/OrderedCollection.class.st
  src/Refactoring2-Transformations/OrderedCollection.extension.st
  src/TraitsV2-Tests/T2AbstractTest.class.st
  src/TraitsV2-Tests/T2TraitTest.class.st
  src/TraitsV2/TaSequence.class.st
Labels: tests passed please review!

#4075 2311-Strange-behaviour-in-DebugSessionpcRangeForContext-
  src/Debugger-Model/DebugSession.class.st
Labels: tests passed please review!

#4343 Fonts-should-not-depend-on-deprecated-file-streams
  src/Graphics-Fonts/FontSet.class.st
  src/Graphics-Fonts/StrikeFont.class.st
Labels: stale, tests passed please review!

#4539 2449-Automatic-rewriting-of-deprecated-code-needs-feedback-to-developers-whose-code-is-changed
  src/Kernel/Deprecation.class.st
Labels: tests passed please review!

#4546 4545-fix-callers-of-ObjectlogCr--deprecated
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: tests passed please review!

#4548 4547-CompiledCode-misses-a-subclassResponsibilty-for-methodClass
  src/Kernel/CompiledCode.class.st
Labels: tests passed please review!

#4553 4550-Remove-class-refactoring-should-not-warn-user-if-the-class-reference-itself
  src/Calypso-SystemTools-Core/ClyBrowserMorph.extension.st
Labels: tests passed please review!

#4556 4552-propagateTransformation-should-not-be-subclassResponsibility
  src/Epicea/RBRefactoring.extension.st
Labels: tests passed please review!

#4604 Fixes: #4602 format: examples should be separated
  src/Collections-Strings/String.class.st
Labels: more-information-needed

#4560 4559-visitSlotInitializationNode-should-not-be-subclassResponsibility
  src/ClassParser/RBProgramNodeVisitor.extension.st
Labels: tests passed please review!

#3157 [Partial Fix] Experiment to test FreeType Problem
  src/FreeType-Tests/FreeTypeCacheTest.class.st
  src/FreeType/FreeTypeFont.class.st
Labels: review

#4569 Smalltalk removal in SUnit-core
  src/SUnit-Core/TestCase.class.st
Labels: more-information-needed

#4640 4639-OCVectorTempVariable-should-have-vectorOffset
  src/OpalCompiler-Core/OCVectorTempVariable.class.st
  src/OpalCompiler-Tests/ASTtoIRMappingTests.class.st
Labels: tests passed please review!

#4657 Remove-nil-initialization-from-initialize-methods
  src/AST-Core/RBBlockNode.class.st
  src/AST-Core/RBParseTreeSearcher.class.st
  src/AST-Core/RBPragmaNode.class.st
  src/AST-Core/RBReturnNode.class.st
  src/Athens-Balloon/AthensBalloonImagePaint.class.st
  src/Athens-Cairo/AthensStrikeFontRenderer.class.st
  src/Athens-Examples/AthensSurfaceExamples.class.st
  src/Athens-Morphic/AthensCanvasWrapper.class.st
  src/Athens-Morphic/AthensCompositeStrokePaint.class.st
  src/Athens-Morphic/AthensWrappedWorldDisplay.class.st
  src/Athens-Text/AthensTextLine.class.st
  src/Balloon/BalloonEngine.class.st
  src/CodeImport/MethodChunkCompilerRequestor.class.st
  src/Compression/DeflateStream.class.st
  src/GT-EventRecorder/GTEventDelivery.class.st
  src/GT-Playground/GTPlayPage.class.st
  src/GT-SpotterExtensions-Core/GTSelector.class.st
  src/Glamour-Core/GLMBrowser.class.st
  src/Glamour-Morphic-Widgets/GLMWatcherWindow.class.st
  src/Hiedra/HiSimpleRenderer.class.st
  src/Images-Animated/AnimatedImageFrame.class.st
  src/Morphic-Base/MenuItemMorph.class.st
  src/Morphic-Base/MenuMorph.class.st
  src/Morphic-Base/StringMorph.class.st
  src/Morphic-Core/HandMorph.class.st
  src/Morphic-Core/Morph.class.st
  src/Morphic-Widgets-Basic/SimpleButtonMorph.class.st
  src/Morphic-Widgets-Basic/ThreePhaseButtonMorph.class.st
  src/Morphic-Widgets-Extra/DockingBarMorph.class.st
  src/Morphic-Widgets-Pluggable/LazyListMorph.class.st
  src/Morphic-Widgets-Tabs/TabMorph.class.st
  src/NECompletion/NECContext.class.st
  src/OSWindow-Core/OSWindowAthensRenderer.class.st
  src/OSWindow-Core/OSWindowAttributes.class.st
  src/OSWindow-SDL2/OSSDL2AthensRenderer.class.st
  src/OSWindow-SDL2/OSSDL2ExternalForm.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/Renraku/ReNoNilAssignationInInitializeRule.class.st
  src/Spec-Core/DropListItem.class.st
  src/Spec-Layout/SpecLayoutAdd.class.st
  src/Spec-Layout/SpecSplitterHorizontal.class.st
  src/Spec-Layout/SpecSplitterVertical.class.st
  src/Spec2-Core/SpAbstractWidgetPresenter.class.st
  src/Spec2-Core/SpCodePresenter.class.st
  src/Spec2-Core/SpDropListItem.class.st
  src/Spec2-Core/SpImagePresenter.class.st
  src/Spec2-Core/SpNotebookPresenter.class.st
  src/Spec2-Core/SpPresenter.class.st
  src/Spec2-Core/SpVersatileDialogPresenter.class.st
  src/Spec2-Layout/SpSplitterHorizontal.class.st
  src/Spec2-Layout/SpSplitterVertical.class.st
  src/System-Serial Port/SerialPort.class.st
  src/Tool-Finder/FinderUI.class.st
Labels: tests passed please review!

#4656 Opal-clean-lookUpVar
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCAbstractScope.class.st
  src/OpalCompiler-Core/OCBlockScope.class.st
  src/OpalCompiler-Core/OCClassScope.class.st
  src/OpalCompiler-Core/OCEnvironmentScope.class.st
  src/OpalCompiler-Core/OCExtraBindingScope.class.st
  src/OpalCompiler-Core/OCInstanceScope.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
  src/OpalCompiler-Core/OCTempVariable.class.st
  src/OpalCompiler-Core/OCVectorTempVariable.class.st
Labels: tests passed please review!

#4663 Removed vague and unneceessary relative sentence
  CODE_OF_CONDUCT.md
Labels: more-information-needed

#4678 OpalTempReadSimplify-Step4
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCTempVariable.class.st
  src/OpalCompiler-Core/OCVectorTempVariable.class.st
Labels: tests passed please review!

#4683 4675 doing a pass on refactoring2
  src/AST-Core/RBProgramNode.class.st
  src/Refactoring-Core/RBEntity.class.st
  src/Refactoring-Core/RBMethod.class.st
  src/Refactoring-Core/RBNamespace.class.st
  src/Refactoring2-Core/RBClass2.class.st
  src/Refactoring2-Core/RBNamespace2.class.st
  src/Refactoring2-Transformations-Tests/RBRemoveDirectAccessToVariableTransformationTest.class.st
  src/Refactoring2-Transformations/RBAddClassTransformation.class.st
  src/Refactoring2-Transformations/RBClassTransformation.class.st
  src/Refactoring2-Transformations/RBMethod.extension.st
  src/Refactoring2-Transformations/RBParseTreeSearcher.extension.st
  src/Refactoring2-Transformations/RBProgramNode.extension.st
  src/Refactoring2-Transformations/RBRemoveClassTransformation.class.st
  src/Refactoring2-Transformations/RBRemoveMethodTransformation.class.st
  src/Refactoring2-Transformations/RBRemoveSubtreeTransformation.class.st
  src/Refactoring2-Transformations/RBRemoveTemporaryVariableTransformation.class.st
  src/Refactoring2-Transformations/RBReplaceSubtreeTransformation.class.st
  src/Refactoring2-Transformations/RBTransformation.class.st
Labels: more-information-needed

#4691 Context tempNamed: use Debuggermap directly
  src/Debugging-Core/Context.extension.st
Labels: tests passed please review!

#4688 4677-simplify-lookupSymbol
  src/Debugging-Core/Context.extension.st
Labels: tests passed please review!

#4692 4654-Add-comment-to-RBProgramNodeisFaulty
  src/AST-Core/RBLiteralValueNode.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBVariableNode.class.st
  src/Reflectivity/RFLiteralVariableNode.class.st
Labels: tests passed please review!

#4696 Opal: DefiningContext should be looked up by scope
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCCopyingTempVariable.class.st
  src/OpalCompiler-Core/OCTempVariable.class.st
  src/OpalCompiler-Tests/MethodMapTest.class.st
  src/OpalCompiler-Tests/OCClosureCompilerTest.class.st
Labels: tests passed please review!

#4689 4686-code-completion-not-working-properly-on-inspectors
  src/NECompletion/CompletionContext.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/OpalCompiler-Core/RBProgramNode.extension.st
Labels: tests passed please review!

#4699 2174-withoutDuplicates
  src/Collections-Abstract/Collection.class.st
  src/Collections-Tests/CollectionTest.class.st
Labels: tests passed please review!

#4705 4703-GTInspectorContextNamedTempNode-should-not-use-debuggerMap
  src/GT-Inspector/GTInspectorContextNamedTempNode.class.st
Labels: tests passed please review!

#4708 4706 convenient method to instantiate a form from a base64 encoded string
  src/Graphics-Files/Form.extension.st
  src/Graphics-Tests/ImageReadWriterTest.class.st
Labels: Easy, Enhancement

#4717 Fixed typo in category
  src/SortFunctions-Core/UndefinedSortFunction.class.st
Labels: more-information-needed

#4707 4704-reduce-direct-calls-of-debuggerMap-rangeForPCcontextIsActiveContext
  src/Debugger-Model/DebugSession.class.st
  src/Debugging-Core/CompiledBlock.extension.st
  src/Debugging-Core/CompiledCode.extension.st
  src/Debugging-Core/CompiledMethod.extension.st
  src/Debugging-Core/Context.extension.st
  src/OpalCompiler-Core/DebuggerMethodMapOpal.class.st
  src/OpalCompiler-Tests/MethodMapTest.class.st
  src/SystemCommands-RefactoringSupport/RBPushUpPreview.class.st
  src/Tool-ProcessBrowser/ProcessBrowser.class.st
Labels: tests passed please review!

#4731 OpalSemanticCleanup
  src/OpalCompiler-Core/OCASTClosureAnalyzer.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
Labels: tests passed please review!

#4723 4670-Deprecation-transfrom-make-sure-the-fallback-is-signal
  src/Kernel/Deprecation.class.st
Labels: tests passed please review!

#4729 4718-implement-ContextsourceNode-in-terms-of-sourceNodeExecuted
  src/OpalCompiler-Core/Context.extension.st
Labels: tests passed please review!

#4738 4736-MethodMapExamples-should-not-use-MethodMap-directly
  src/OpalCompiler-Tests/MethodMapExamples.class.st
  src/OpalCompiler-Tests/MethodMapTest.class.st
Labels: tests passed please review!

#4740 4735-Implement-pcRange-on-Context-using-sourceNodeExecuted
  src/Debugger-Model/DebugSession.class.st
  src/Debugger-Tests/IsLatestContextTest.class.st
  src/Debugging-Core/CompiledCode.extension.st
  src/Debugging-Core/Context.extension.st
  src/OpalCompiler-Core/DebuggerMethodMapOpal.class.st
  src/OpalCompiler-Tests/MethodMapTest.class.st
  src/Tool-ProcessBrowser/ProcessBrowser.class.st
Labels: tests passed please review!

#4733 4730-Magnitude-has-no-tests
  src/Kernel-Tests/MagnitudeTest.class.st
Labels: tests passed please review!

#4680 2716-Clean-Editor-method-
  src/Deprecated80/Editor.class.st
  src/EpiceaBrowsers/EpLogBrowserPresenter.class.st
  src/Morphic-Base/Paragraph.class.st
  src/Morphic-Base/TextMorph.class.st
  src/Morphic-Base/WorldMorph.extension.st
  src/Text-Edition/Editor.class.st
  src/Text-Edition/TextEditor.class.st
Labels: tests passed please review!

#4770 4748-remove-slotsDictionary
  src/Glamour-Morphic-Brick/AbstractLayout.extension.st
  src/Glamour-Morphic-Brick/ClassDescription.extension.st
  src/Glamour-Morphic-Brick/LayoutClassScope.extension.st
  src/Glamour-Morphic-Brick/PointerLayout.extension.st
Labels: tests passed please review!

#4772 Add-comment-to-Compiledethod-isRequired
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!
