Repository pharo-project/pharo, pull requests merged in 2019-03, with the labels that each got.

#2364 2363 Add ProperManifestCategorizationTest as new release test
  src/ReleaseTests/ProperManifestCategorizationTest.class.st
Labels: review

#2739 2293-Failing-tests-on-Pharo-8
  src/Graphics-Tests/DisplayScreenTest.class.st
Labels: review

#2738 2492-Typos-in-FileStream-class-comment
  src/DeprecatedFileStream/FileStream.class.st
Labels: review

#2737 2407-Kill-flaky-test-GLMTabulatorMorphicTest
  src/Glamour-Tests-Morphic/GLMTabulatorMorphicTest.class.st
Labels: review

#2721 2587-Cannot-remove-a-Trait
  src/Kernel/Class.class.st
  src/Refactoring-Changes/RBAddTraitChange.class.st
  src/TraitsV2-Tests/T2TraitTest.class.st
Labels: review

#2491 2488-ZipArchive-should-use-FileReferences-and-not-path-strings
  src/Compression-Tests/ZipArchiveTest.class.st
  src/Compression/Archive.class.st
  src/Compression/ZipArchiveMember.class.st
  src/Compression/ZipDirectoryMember.class.st
  src/Compression/ZipNewFileMember.class.st
Labels: Need more work, review

#2730 2728-Rescue-RubCleaning-to-remove-PluggableTextMorph-and-friends
  src/Athens-Morphic/RubPluggableTextFieldMorph.extension.st
  src/Rubric/RubAbstractTextArea.class.st
  src/Rubric/RubDropListButtonRuler.class.st
  src/Rubric/RubFindReplaceDialogWindow.class.st
  src/Rubric/RubGhostTextDisplayer.class.st
  src/Rubric/RubLipsumBasicExample.class.st
  src/Rubric/RubPluggableTextFieldMorph.class.st
  src/Rubric/RubPluggableTextFieldWithFloatConverterExample.class.st
  src/Rubric/RubPluggableTextMorph.class.st
  src/Rubric/RubPluggableTextMorphExample.class.st
  src/Rubric/RubScrolledTextMorph.class.st
  src/Rubric/RubTextFieldArea.class.st
  src/Rubric/RubTextFieldExample.class.st
  src/Rubric/RubTextFieldMorph.class.st
  src/Rubric/RubTextFieldWithEntryCompletionExample.class.st
  src/Rubric/RubTextScrollPane.class.st
  src/Rubric/RubWorkspaceExample.class.st
Labels: review

#2747 2736-Update-Epicea-to-Spec-changes
  src/EpiceaBrowsers/EpLogBrowserPresenter.class.st
Labels: review

#2756 Fix incorrect cascade in DomainError>>signalFrom:to:
  src/Kernel/DomainError.class.st
Labels: Bug, Cleanup, review

#2754 2753-FileReference-version-number-issues
  src/FileSystem-Core/FileReference.class.st
  src/FileSystem-Tests-Core/FileReferenceTest.class.st
Labels: review

#2762 2761-Glamour-Examples-was-removed-from-Pharo-but-not-from-the-repository
  src/Glamour-Examples/GLMBasicExamples.class.st
  src/Glamour-Examples/GLMBrowserWithoutBlocksExample.class.st
  src/Glamour-Examples/GLMExamples.class.st
  src/Glamour-Examples/GLMExamplesBrowser.class.st
  src/Glamour-Examples/package.st
Labels: review

#2743 2742-transformLastToReturn-does-the-same-as-addReturn
  src/AST-Core/RBSequenceNode.class.st
  src/OpalCompiler-Core/RBSequenceNode.extension.st
Labels: Need more work, review

#2767 2766-RubScrolledTextMorphcanDiscardEdits-need-to-use-accessor-as-var-can-be-nil
  src/Rubric/RubScrolledTextMorph.class.st
Labels: review

#2772 2771-Introduce-new-debuggers
  src/Tools/AbstractDebugger.class.st
  src/Tools/InformDebugger.class.st
  src/Tools/LogDebugger.class.st
  src/Tools/NoDebugger.class.st
  src/Tools/TranscriptDebugger.class.st
Labels: review

#2768 2765-Feature-Add-disableDuring-in-Epicea
  src/Epicea-Tests/EpDisabledIntegrationTest.class.st
  src/Epicea/EpMonitor.class.st
Labels: review

#2760 2759-Spec-Deprecated-should-be-removed-from-Pharo-8
  src/BaselineOfSpec/BaselineOfSpec.class.st
  src/Spec-Deprecated/AbstractFormButtonModel.class.st
  src/Spec-Deprecated/AbstractWidgetModel.class.st
  src/Spec-Deprecated/ButtonModel.class.st
  src/Spec-Deprecated/CheckBoxModel.class.st
  src/Spec-Deprecated/ComposableModel.class.st
  src/Spec-Deprecated/ContainerModel.class.st
  src/Spec-Deprecated/DateModel.class.st
  src/Spec-Deprecated/DialogWindowModel.class.st
  src/Spec-Deprecated/DiffModel.class.st
  src/Spec-Deprecated/DropListModel.class.st
  src/Spec-Deprecated/DynamicComposableModel.class.st
  src/Spec-Deprecated/FastTableModel.class.st
  src/Spec-Deprecated/IconListModel.class.st
  src/Spec-Deprecated/ImageModel.class.st
  src/Spec-Deprecated/LabelModel.class.st
  src/Spec-Deprecated/ListModel.class.st
  src/Spec-Deprecated/MenuGroupModel.class.st
  src/Spec-Deprecated/MenuItemModel.class.st
  src/Spec-Deprecated/MenuModel.class.st
  src/Spec-Deprecated/MultiColumnListModel.class.st
  src/Spec-Deprecated/PickListModel.class.st
  src/Spec-Deprecated/RadioButtonGroupModel.class.st
  src/Spec-Deprecated/RadioButtonModel.class.st
  src/Spec-Deprecated/SliderModel.class.st
  src/Spec-Deprecated/TabManagerModel.class.st
  src/Spec-Deprecated/TabModel.class.st
  src/Spec-Deprecated/TableContainerModel.class.st
  src/Spec-Deprecated/TextInputFieldModel.class.st
  src/Spec-Deprecated/TextModel.class.st
  src/Spec-Deprecated/TickingWindowModel.class.st
  src/Spec-Deprecated/TransferModel.class.st
  src/Spec-Deprecated/TreeColumnModel.class.st
  src/Spec-Deprecated/TreeModel.class.st
  src/Spec-Deprecated/TreeNodeModel.class.st
  src/Spec-Deprecated/WindowModel.class.st
  src/Spec-Deprecated/WorldModel.class.st
  src/Spec-Deprecated/package.st
Labels: review

#2711 2708-Deprecate-subscribesendto
  src/Announcements-Core/Announcer.class.st
  src/Announcements-Core/WeakSubscriptionBuilder.class.st
  src/Announcements-Tests-Core/AnnouncerTest.class.st
  src/Announcements-Tests-Core/WeakAnnouncerTest.class.st
  src/Epicea-Tests/EpAnnouncementsTest.class.st
  src/GT-EventRecorder/GTEventRecorder.class.st
  src/GT-Spotter/GTSpotterStep.class.st
  src/Keymapping-Pragmas/KMPragmaKeymapBuilder.class.st
  src/Morphic-Widgets-FastTable/FTFunctionWithField.class.st
  src/NECompletion/NOCCompletionTable.class.st
  src/Ombu-Tests/OmSessionStoreTest.class.st
  src/Reflectivity-Tools/Breakpoint.class.st
  src/SUnit-Core/TestSuite.class.st
  src/SUnit-UI/TestRunner.class.st
Labels: review

#2784 Revert "Adds a new exception for a missing class error (ClassNotUnderstood) and…"
  src/DebuggerActions/DoesNotUnderstandDebugAction.class.st
  src/Kernel-Tests/UndefinedObjectTest.class.st
  src/Kernel/ClassNotUnderstood.class.st
  src/Kernel/UndefinedObject.class.st
Labels: review

#2788 Revert "2759-Spec-Deprecated-should-be-removed-from-Pharo-8"
  src/BaselineOfSpec/BaselineOfSpec.class.st
  src/Spec-Deprecated/AbstractFormButtonModel.class.st
  src/Spec-Deprecated/AbstractWidgetModel.class.st
  src/Spec-Deprecated/ButtonModel.class.st
  src/Spec-Deprecated/CheckBoxModel.class.st
  src/Spec-Deprecated/ComposableModel.class.st
  src/Spec-Deprecated/ContainerModel.class.st
  src/Spec-Deprecated/DateModel.class.st
  src/Spec-Deprecated/DialogWindowModel.class.st
  src/Spec-Deprecated/DiffModel.class.st
  src/Spec-Deprecated/DropListModel.class.st
  src/Spec-Deprecated/DynamicComposableModel.class.st
  src/Spec-Deprecated/FastTableModel.class.st
  src/Spec-Deprecated/IconListModel.class.st
  src/Spec-Deprecated/ImageModel.class.st
  src/Spec-Deprecated/LabelModel.class.st
  src/Spec-Deprecated/ListModel.class.st
  src/Spec-Deprecated/MenuGroupModel.class.st
  src/Spec-Deprecated/MenuItemModel.class.st
  src/Spec-Deprecated/MenuModel.class.st
  src/Spec-Deprecated/MultiColumnListModel.class.st
  src/Spec-Deprecated/PickListModel.class.st
  src/Spec-Deprecated/RadioButtonGroupModel.class.st
  src/Spec-Deprecated/RadioButtonModel.class.st
  src/Spec-Deprecated/SliderModel.class.st
  src/Spec-Deprecated/TabManagerModel.class.st
  src/Spec-Deprecated/TabModel.class.st
  src/Spec-Deprecated/TableContainerModel.class.st
  src/Spec-Deprecated/TextInputFieldModel.class.st
  src/Spec-Deprecated/TextModel.class.st
  src/Spec-Deprecated/TickingWindowModel.class.st
  src/Spec-Deprecated/TransferModel.class.st
  src/Spec-Deprecated/TreeColumnModel.class.st
  src/Spec-Deprecated/TreeModel.class.st
  src/Spec-Deprecated/TreeNodeModel.class.st
  src/Spec-Deprecated/WindowModel.class.st
  src/Spec-Deprecated/WorldModel.class.st
  src/Spec-Deprecated/package.st
Labels: review

#2770 2769-add-Slot-example-write-once-slot
  src/Slot-Examples/WriteOnceSlot.class.st
  src/Slot-Tests/AClassUsingWriteOnceSlot.class.st
  src/Slot-Tests/WriteOnceSlotTest.class.st
Labels: review

#2741 2740-do-not-zap-method-dict-when-making-classes-obsolete
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel/Behavior.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/Metaclass.class.st
  src/TraitsV2-Tests/T2ObsoleteClassTest.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: review

#2778 2777-classbuilder-copyClassSlotsFromExistingClass-needs-to-be-done-by-the-classInstaller-by-default
  src/Hermes/HEInstaller.class.st
  src/Kernel/Class.class.st
  src/Monticello/MCClassDefinition.class.st
  src/SUnit-Core/ClassFactoryWithOrganization.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/Shift-ClassInstaller-Tests/ShClassInstallerTest.class.st
  src/Shift-ClassInstaller/Class.extension.st
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
  src/Slot-Core/Behavior.extension.st
  src/Slot-Tests/SlotClassVariableTest.class.st
  src/TraitsV2/Class.extension.st
  src/TraitsV2/Trait.class.st
Labels: Need more work, review

#2547 2546 Small cleanup UFFI to better distinguish architecture type
  src/UnifiedFFI-Tests/FFIArchitectureTest.class.st
  src/UnifiedFFI/FFIArchitecture.class.st
  src/UnifiedFFI/FFI_x86_64.class.st
Labels: review

#2798 2797-Fix-comment-on-OSWindow--startTextInput
  src/OSWindow-Core/OSWindow.class.st
Labels: review

#2804 2803-parseErrorNode-should-fill-value-for-the-case-of-expecting-a-
  src/AST-Core/RBParser.class.st
  src/AST-Tests-Core/RBFormatterTest.class.st
Labels: review

#2807 2806-test-and-fix-for-PropertySlot-remove-propertySlot-when-instances-are-present
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
  src/Slot-Tests/PropertySlotTest.class.st
Labels: review

#2812 2811-Test-for-metalink-on-slot-that-gets-assigned-
  src/Reflectivity-Tests/ReflectivityControlTest.class.st
Labels: review

#2810 2809-Small-test-cleanup-in-Slots
  src/Slot-Tests/BooleanSlotTest.class.st
  src/Slot-Tests/ClassVariableTest.class.st
  src/Slot-Tests/ExampleClassVariableTest.class.st
  src/Slot-Tests/GlobalVariableTest.class.st
  src/Slot-Tests/PropertySlotTest.class.st
  src/Slot-Tests/RelationSetTest.class.st
  src/Slot-Tests/RelationSlotTest.class.st
  src/Slot-Tests/SlotAnnouncementsTest.class.st
  src/Slot-Tests/SlotBasicTest.class.st
  src/Slot-Tests/SlotClassBuilderTest.class.st
  src/Slot-Tests/SlotClassVariableTest.class.st
  src/Slot-Tests/SlotEnvironmentTest.class.st
  src/Slot-Tests/SlotErrorsTest.class.st
  src/Slot-Tests/SlotExampleMovie.class.st
  src/Slot-Tests/SlotExampleMovieAndPersonTest.class.st
  src/Slot-Tests/SlotExamplePerson.class.st
  src/Slot-Tests/SlotExampleTest.class.st
  src/Slot-Tests/SlotIntegrationTest.class.st
  src/Slot-Tests/SlotLayoutEqualityTest.class.st
  src/Slot-Tests/SlotLayoutExtensionTest.class.st
  src/Slot-Tests/SlotMethodRecompilationTest.class.st
  src/Slot-Tests/SlotMigrationTest.class.st
  src/Slot-Tests/SlotSilentTest.class.st
  src/Slot-Tests/SlotTest.class.st
  src/Slot-Tests/SlotTraitsTest.class.st
  src/Slot-Tests/TOne.trait.st
  src/Slot-Tests/TTwo.trait.st
  src/Slot-Tests/TemporaryVariableTest.class.st
  src/Slot-Tests/TestSharedPool.class.st
  src/Slot-Tests/UnlimitedInstanceVariableSlotTest.class.st
Labels: review

#2816 2802-2801-Refactor-Reflectivity-Tools-
  src/Reflectivity-Tools-Tests/Breakpoint.extension.st
  src/Reflectivity-Tools/CompiledMethod.extension.st
  src/Reflectivity-Tools/RBProgramNode.extension.st
  src/Reflectivity/Break.class.st
  src/Reflectivity/Breakpoint.class.st
  src/Reflectivity/CompiledMethod.extension.st
  src/Reflectivity/ExecutionCounter.class.st
  src/Reflectivity/RBProgramNode.extension.st
  src/Reflectivity/Watchpoint.class.st
Labels: review

#2823 2822-remove-WPDummy
  src/Reflectivity-Tests/ReflectivityExamples.class.st
  src/Reflectivity-Tools-Tests/WPDummy.class.st
  src/Reflectivity-Tools-Tests/WatchpointTests.class.st
Labels: review

#2827 2826-remove-ReDeadMethod-and-Test
  src/Renraku-Test/ReDeadMethodTest.class.st
  src/Renraku/ReDeadMethod.class.st
Labels: review

#2830 2829-RPackagepackageManifestOrNil-should-be-directly-in-RPackage-Core
  src/Manifest-Core/RPackage.extension.st
  src/RPackage-Core/RPackage.class.st
Labels: review

#2835 2834-testExternalMorphicDependencies-failing-on-CI
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: review

#2825 2824-unify-and-cleanup-compactAll-OrderedCollection
  src/Collections-Abstract/HashedCollection.class.st
  src/Collections-Sequenceable/OrderedCollection.class.st
  src/Kernel/Behavior.class.st
  src/Tool-ImageCleaner/ImageCleaner.class.st
Labels: review

#2840 2839-Clean-AthensTest
  src/Athens-Balloon/ImageFillStyle.extension.st
  src/Athens-Examples/AthensTextRenderManualTests.class.st
  src/Athens-Morphic/AthensTextMorph.class.st
Labels: review

#2819 2817-distinguish-between-instance-side-and-class-side-in-method-template
  src/Kernel-Tests/BehaviorTest.class.st
  src/Kernel/Behavior.class.st
  src/Kernel/Metaclass.class.st
  src/OpalCompiler-Core/Behavior.extension.st
  src/OpalCompiler-Tests/OCSourceTemplates.class.st
Labels: review

#2844 2843-Clean-Navigation-code
  src/NodeNavigation-Tests/NNavNavigateTest.class.st
  src/NodeNavigation/NNavDirectionChild.class.st
  src/NodeNavigation/NNavDirectionFirstChild.class.st
  src/NodeNavigation/NNavDirectionParent.class.st
  src/NodeNavigation/NNavDirectionPreviousBrother.class.st
  src/NodeNavigation/NNavDirectionPreviousSelection.class.st
  src/NodeNavigation/NNavDirectionSibling.class.st
  src/NodeNavigation/NNavNavigation.class.st
  src/NodeNavigation/SmalltalkEditor.extension.st
  src/NodeNavigation/Workspace.extension.st
Labels: review

#2859 2858-GRVariableAssignedLiteralRule-raises-exception-on-slots-not-inherited-from-IndexedSlot
  src/GeneralRules/GRVariableAssignedLiteralRule.class.st
Labels: review

#2837 2836-removeUnreferencedKeys-is-only-there-for-the-Undeclared-mechanism-no-need-to-implement-on-other-Disctionaries
  src/Collections-Sequenceable/OrderedDictionary.class.st
  src/Collections-Tests/DictionaryTest.class.st
  src/Collections-Tests/OrderedDictionaryTest.class.st
  src/Collections-Unordered/Dictionary.class.st
  src/Collections-Unordered/SmallDictionary.class.st
Labels: review

#2875 2847-Implement-method-to-remove-class-side-slot
  src/Kernel-Tests-Extended/ClassTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/Metaclass.class.st
  src/Shift-ClassInstaller/Class.extension.st
Labels: review

#2878 2877-whichSelectorsAccess-and-slots
  src/Kernel/Behavior.class.st
  src/Kernel/ClassDescription.class.st
Labels: review

#2857 2852-CodeCompletion-should-not-be-managed-via-common-tools-but-via-a-TextArea-registration
  src/Morphic-Base/TextMorph.class.st
  src/NECompletion/NECController.class.st
  src/Rubric-Tests/RubSmalltalkEditorTest.class.st
  src/Rubric/RubAbstractTextArea.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Rubric/RubTextEditor.class.st
  src/Text-Edition/SmalltalkEditor.class.st
Labels: review

#2894 2891-fix-whichSelectorsRead-and-whichSelectorsStoreInto-for-Slots
  src/Kernel/Behavior.class.st
  src/Kernel/ClassDescription.class.st
Labels: review

#2890 2879-removeInstVarNamed-on-MetaClass-needs-to-use-removeSlot-like-the-implementation-on-Class
  src/Kernel/Class.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/Metaclass.class.st
Labels: review

#2897 2880-speedup-writesSlot-and-readsSlot-for-the-case-of-Ivar
  src/Kernel/CompiledCode.class.st
  src/Slot-Core/Slot.class.st
Labels: review

#2905 2901-ClassBuilder-fillFor-should-not-use-classVariablesString
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
Labels: review

#2892 2889-baselineOfTelePharoSupport
  bootstrap/scripts/03-metacello-bootstrap/01-loadMetacello.st
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfTelePharoSupport/BaselineOfTelePharoSupport.class.st
  src/BaselineOfTelePharoSupport/package.st
Labels: review

#2906 2900-deprecate-whichSelectorsAssign-for-whichSelectorsStoreInto
  src/Kernel-Tests/BehaviorTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Refactoring-Environment/RBVariableEnvironment.class.st
Labels: review

#2919 2918-accessesSlot: should use #isAccessedIn: method
  src/AST-Core/RBProgramNode.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/CompiledCode.class.st
  src/Slot-Core/InstanceVariableSlot.class.st
  src/Slot-Core/Slot.class.st
Labels: review

#2923 2690-22595-Median-is-not-calculated-correctly-for-even-sizes
  src/Collections-Abstract/Collection.class.st
  src/Collections-Sequenceable/SortedCollection.class.st
  src/Collections-Tests/SortedCollectionTest.class.st
Labels: review

#2377 Integrate Clap
  src/BaselineOfClap/BaselineOfClap.class.st
  src/BaselineOfClap/package.st
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/Clap-CommandLine/ClapCommandLineHandler.class.st
  src/Clap-CommandLine/package.st
  src/Clap-Commands-Pharo/ClapCodeEvaluator.class.st
  src/Clap-Commands-Pharo/ClapPharoVersion.class.st
  src/Clap-Commands-Pharo/package.st
  src/Clap-Core/ClapCommand.class.st
  src/Clap-Core/ClapCompositeMatch.class.st
  src/Clap-Core/ClapContext.class.st
  src/Clap-Core/ClapDocumentationFormatter.class.st
  src/Clap-Core/ClapDocumenter.class.st
  src/Clap-Core/ClapExplicit.class.st
  src/Clap-Core/ClapExpression.class.st
  src/Clap-Core/ClapFlag.class.st
  src/Clap-Core/ClapImplicit.class.st
  src/Clap-Core/ClapLeftoversValidation.class.st
  src/Clap-Core/ClapMismatch.class.st
  src/Clap-Core/ClapNamedMatch.class.st
  src/Clap-Core/ClapParameter.class.st
  src/Clap-Core/ClapParameterized.class.st
  src/Clap-Core/ClapPositional.class.st
  src/Clap-Core/ClapRoot.class.st
  src/Clap-Core/ClapSubExpression.class.st
  src/Clap-Core/ClapValidation.class.st
  src/Clap-Core/ClapValidationDiagnostic.class.st
  src/Clap-Core/ClapValidationReport.class.st
  src/Clap-Core/ClapWordMatch.class.st
  src/Clap-Core/ManifestClapCore.class.st
  src/Clap-Core/package.st
  src/Clap-Examples/ClapCommandLineExamples.class.st
  src/Clap-Examples/package.st
  src/Clap-Tests/ClapCommandTest.class.st
  src/Clap-Tests/ClapContextTest.class.st
  src/Clap-Tests/ClapDocumentationTest.class.st
  src/Clap-Tests/ClapFlagTest.class.st
  src/Clap-Tests/ClapHelloWorldTest.class.st
  src/Clap-Tests/ClapMatchesTest.class.st
  src/Clap-Tests/ClapMeaningsTest.class.st
  src/Clap-Tests/ClapParameterTest.class.st
  src/Clap-Tests/ClapParameterizedTest.class.st
  src/Clap-Tests/ClapPositionalTest.class.st
  src/Clap-Tests/package.st
Labels: New Feature, review

#2930 2929-Move-method-comment-parsing-from-Behaviour-to-CompiledMethod
  src/Kernel/Behavior.class.st
  src/Kernel/CompiledMethod.class.st
Labels: review

#2937 2935-Add-test-and-comment-for-RBMethodName
  src/Refactoring-Core/RBCondition.class.st
  src/Refactoring-Core/RBMethodName.class.st
  src/Refactoring-Tests-Core/RBConditionTest.class.st
  src/Refactoring-Tests-Core/RBMethodNameTest.class.st
Labels: review

#2956 2955-speedup-isAccessedIn-in-BooleanSlot-and-PropertySlot
  src/Slot-Examples/BooleanSlot.class.st
  src/Slot-Examples/PropertySlot.class.st
Labels: review

#2973 2972-MailAddressTokenizer-doesnt-handle-non-ascii-characters
  src/Network-Mail/MailAddressTokenizer.class.st
  src/Network-Tests/MailAddressTokenizerTest.class.st
Labels: review

#2985 Update issue URL in build report email
  Jenkinsfile
  README.md
Labels: review

#2988 2987-provide-standard-class-comment-for-tests
  src/Kernel/ClassDescription.class.st
  src/SUnit-Core/TestCase.class.st
Labels: review

#2950 2864-CompiledMethodcommentsIn-should-be-enhanced
  src/AST-Core/CompiledMethod.extension.st
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel/CompiledMethod.class.st
Labels: review

#2994 2993-update-slot-comments
  src/Slot-Core/InstanceVariableSlot.class.st
  src/Slot-Examples/ComputedSlot.class.st
  src/Slot-Examples/ExampleSlotWithState.class.st
Labels: review

#2997 Update Calypso version 0.16.1
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: more-information-needed

#3001 2996-test-failing-on-CI-GTSpotterExtensionsOnClassTesttestBasic
  src/GT-SpotterExtensions-Core/GTSpotterExtensionsOnClassTest.class.st
Labels: review

#3003 2813-Failing-tests-in-MorphicTextInputFieldAdapterTest
  src/Spec-MorphicBackendTests/MorphicTextInputFieldAdapterTest.class.st
Labels: review

#3002 3000-MailAddressParser---extend-to-parse-display-name-as-well-as-address
  src/Network-Mail/MailAddressParser.class.st
  src/Network-Tests/MailAddressParserTest.class.st
Labels: review

#3012 3011-cleanup-delete-unsent-private-method-from-Slots-classes
  src/Slot-Core/BitsLayout.class.st
  src/Slot-Core/ObjectLayout.class.st
  src/Slot-Core/PointerLayout.class.st
  src/Slot-Core/VariableLayout.class.st
Labels: review

#3032 Revert "2813-Failing-tests-in-MorphicTextInputFieldAdapterTest"
  src/Spec-MorphicBackendTests/MorphicTextInputFieldAdapterTest.class.st
Labels: review

#3024 3023-Some-cleanups-in-Slots
  src/Kernel/ClassDescription.class.st
  src/Slot-Core/AbstractLayout.class.st
  src/Slot-Core/BitsLayout.class.st
  src/Slot-Core/ObjectLayout.class.st
  src/Slot-Core/Slot.class.st
  src/Slot-Examples/AccessorInstanceVariableSlot.class.st
  src/Slot-Tests/ExampleClassVariableTest.class.st
  src/Slot-Tests/SlotErrorsTest.class.st
  src/Slot-Tests/SlotExampleTest.class.st
Labels: review

#3045 3044-tests-for-ComputedSlot
  src/Slot-Tests/ComputedSlotTest.class.st
Labels: review

#3071 2141-Spotter-should-use-the-current-theme-instead-of-creating-its-own-theme-classes
  src/GT-Spotter-UI/GTSpotterWidgetDarkThemer.class.st
Labels: review

#3078 Proper name for testisDefinedAsPackageOrSubPackageInMC
  src/Monticello-Tests/RPackageMCSynchronisationTest.class.st
Labels: review

#3076 Lint cleanup / ban for DiskFileSystemTest>>testEqual
  src/FileSystem-Tests-Disk/ManifestFileSystemTestsDisk.class.st
Labels: review

#3063 DiskFileAttributesTests -> DiskFileAttributesTest
  src/FileSystem-Tests-Attributes/DiskFileAttributesTest.class.st
  src/FileSystem-Tests-Attributes/DiskFileAttributesTestsResource.class.st
  src/FileSystem-Tests-Attributes/FileAttributesPluginPrimsTest.class.st
  src/FileSystem-Tests-Attributes/FileReferenceAttributeTest.class.st
Labels: review

#3088 Use <expectedFailure> instead of #expectedFailures.
  src/Glamour-Tests-Core/GLMAnnouncementPropagationTest.class.st
  src/Glamour-Tests-Core/GLMPaneTest.class.st
  src/Glamour-Tests-Core/GLMPresentationTest.class.st
  src/Glamour-Tests-Core/GLMScriptingTest.class.st
  src/Glamour-Tests-Core/GLMTextPresentationTest.class.st
  src/Glamour-Tests-Morphic/GLMActionsToolbarMorphicTest.class.st
  src/Glamour-Tests-Morphic/GLMDynamicMorphicTest.class.st
  src/Glamour-Tests-Morphic/GLMTextMorphicTest.class.st
  src/Glamour-Tests-Morphic/GLMUpdateMorphicTest.class.st
  src/Glamour-Tests-Rubric/GLMRubricTextMorphicTest.class.st
  src/Kernel-Tests-Extended/WriteBarrierTest.class.st
  src/Refactoring-Tests-Core/RBRemoveMethodTest.class.st
  src/Refactoring2-Transformations-Tests/RBRemoveMethodTransformationTest.class.st
  src/SUnit-Tests/SUnitTest.class.st
Labels: review

#3070 assert:equal: cleanups in FileSystem-Tests-Core
  src/FileSystem-Tests-Core/AbstractEnumerationVisitorTest.class.st
  src/FileSystem-Tests-Core/CopyVisitorTest.class.st
  src/FileSystem-Tests-Core/DeleteVisitorTest.class.st
  src/FileSystem-Tests-Core/FileLocatorTest.class.st
  src/FileSystem-Tests-Core/FileReferenceTest.class.st
  src/FileSystem-Tests-Core/FileSystemHandleTest.class.st
  src/FileSystem-Tests-Core/FileSystemResolverTest.class.st
  src/FileSystem-Tests-Core/FileSystemTest.class.st
  src/FileSystem-Tests-Core/GuideTest.class.st
  src/FileSystem-Tests-Core/PathTest.class.st
Labels: review

#3043 3038-Simplify-Slots-that-use-base-slot
  src/Slot-Examples/BooleanSlot.class.st
  src/Slot-Examples/PropertySlot.class.st
  src/Slot-Examples/UnlimitedInstanceVariableSlot.class.st
Labels: review

#3050 2895-remove-SmalltalkEditor
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/Clap-Tests/ClapHelloWorldTest.class.st
  src/Clap-Tests/ClapPositionalTest.class.st
  src/GT-Inspector/GlamourPresentationPresenter.extension.st
  src/GT-Playground/GlamourPresentationPresenter.extension.st
  src/Glamour-Morphic-Renderer/GLMMorphicSmalltalkCodeRenderer.class.st
  src/Glamour-Morphic-Renderer/GLMMorphicTextRenderer.class.st
  src/Glamour-Morphic-Widgets/GLMPluggableTextMorph.class.st
  src/Glamour-Morphic-Widgets/GLMSmalltalkEditor.class.st
  src/Glamour-Morphic-Widgets/GLMTextMorphForEditView.class.st
  src/Glamour-Tests-Morphic/GLMTextMorphicTest.class.st
  src/NodeNavigation/SmalltalkEditor.extension.st
  src/Text-Edition/SmalltalkEditor.class.st
Labels: review

#3102 3091-ExternalDataprintOn-not-as-extension
  src/FFI-Kernel/ExternalData.class.st
  src/UnifiedFFI/ExternalData.extension.st
Labels: review

#3058 3057-Integrated-Iceberg-160
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: review

#3096 2855 autocompletion of a method parameter when typing in a method should be higher
  src/NECompletion/NECModel.class.st
  src/NECompletion/NECUntypedModel.class.st
Labels: review

#3015 3013-RegressionDropListMorph-content-is-now-selectable
  src/Polymorph-Widgets/DropListMorph.class.st
Labels: review

#3103 2980-Rubric-setTextAndAccept-is-missing-to-RubPluggable
  src/Rubric/RubPluggableTextFieldMorph.class.st
Labels: review

#3028 3009-CharacterSetComplement-size-causes-GT-inspector-to-crash
  src/Collections-Support/CharacterSet.class.st
  src/Collections-Support/CharacterSetComplement.class.st
  src/Collections-Support/ManifestCollectionsSupport.class.st
  src/Collections-Tests/CharacterTest.class.st
  src/GT-InspectorExtensions-Core/CharacterSetComplement.extension.st
  src/Kernel/Character.class.st
Labels: review

#3109 3040-Cannot-search-setting-browser-anymore
  src/NECompletion/NECModel.class.st
  src/NECompletion/NECPreferences.class.st
Labels: review

#3087 Abstract collections should redefine #isAbstract
  src/Collections-Abstract/ArrayedCollection.class.st
  src/Collections-Abstract/Collection.class.st
  src/Collections-Abstract/HashedCollection.class.st
  src/Collections-Abstract/SequenceableCollection.class.st
Labels: review

#3034 3033-TextMorphEditView-should-be-packaged-with-PluggableTextMorph
  src/Morphic-Widgets-Pluggable/TextMorphForEditView.class.st
Labels: review
