Repository pharo-project/pharo, pull requests merged in 2019-08, with the labels that each got.

#4158 Fix spelling of programatically to rather be programmatically
  src/Renraku-Test/ReCodeBasedTestCase.class.st
  src/Renraku-Test/ReTestBasedTestCase.class.st
  src/Renraku-Test/ReTestClassNameShouldNotEndWithTestsTest.class.st
Labels: more-information-needed

#4208 Fixing the dependencies again.
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: more-information-needed

#4142 Deprecate-unused-methods-in-obsolete-proctocol
  src/Deprecated80/PluggableListMorph.extension.st
  src/Deprecated80/SimpleHierarchicalListMorph.extension.st
  src/Morphic-Widgets-List/SimpleHierarchicalListMorph.class.st
  src/Morphic-Widgets-Pluggable/PluggableListMorph.class.st
Labels: tests passed please review!

#4279 4017-tryning-to-add-an-ivar-to-UndefinedObject-crashes-the-VM
  src/Shift-ClassBuilder/DangerousClassNotifier.class.st
Labels: tests passed please review!

#4203 4201-Add-isHidden-file-attribute
  src/FileSystem-Core/DiskDirectoryEntry.class.st
  src/FileSystem-Core/FileSystem.class.st
  src/FileSystem-Core/FileSystemDirectoryEntry.class.st
  src/FileSystem-Disk/UnixStore.class.st
  src/FileSystem-Disk/WindowsStore.class.st
  src/FileSystem-Tests-Attributes/DiskFileAttributesTest.class.st
  src/Files/File.class.st
Labels: tests passed please review!

#4274 4204-Should-SystemDictionary-sort-classes-by-name
  src/System-Support/SystemDictionary.class.st
Labels: tests passed please review!

#4277 4275-allInstVarNames-should-call-instVarNames
  src/Kernel/Behavior.class.st
Labels: tests passed please review!

#4205 Do-not-flush-all-caches-when-a-class-is-removed
  src/System-Support/SystemDictionary.class.st
Labels: tests passed please review!

#4285 Update-manually-resolved-dependencies
  src/Collections-Unordered/ManifestCollectionsUnordered.class.st
  src/Kernel/ManifestKernel.class.st
Labels: tests passed please review!

#4199 4194-Missing-refactoring-Abstract-instance-variable
  src/SystemCommands-ClassCommands/SycAbstractAllInstVarAccessorsCommand.class.st
Labels: Need more work

#4313 Test-cases-should-end-with-test
  src/Collections-Arithmetic-Tests/CollectionArithmeticTest.class.st
  src/GT-Tests-Debugger/InfiniteDebuggerTest.class.st
  src/GT-Tests-Debugger/TestClassForTestingDebuggerTest.class.st
  src/GT-Tests-Spotter/GTSpotterA1.class.st
  src/GT-Tests-Spotter/GTSpotterA2.class.st
  src/GT-Tests-Spotter/GTSpotterA3.class.st
  src/Metacello-TestsMC/MetacelloScriptingStdTstHarnessTestCase.class.st
  src/Metacello-TestsMC/MetacelloScriptingTestCase.class.st
  src/OSWindow-Tests/OSWindowBench.class.st
  src/ProfStef-Tests/LessonInstanciationTest.class.st
  src/ProfStef-Tests/PharoTutorialGoOnMockTutorialTest.class.st
  src/ProfStef-Tests/PharoTutorialGoTest.class.st
  src/ProfStef-Tests/PharoTutorialNavigationTest.class.st
  src/ProfStef-Tests/TutorialPlayerTutorialAccessorTest.class.st
  src/ProfStef-Tests/TutorialPlayerWithMockTutorialTest.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/Rubric-Tests/RubScrolledTextMorphTest.class.st
  src/System-Identification-Tests/GlobalIdentifierWithDefaultConfigurationTest.class.st
  src/System-Identification-Tests/GlobalIdentifierWithFuelTest.class.st
  src/System-Identification-Tests/GlobalIdentifierWithStonTest.class.st
  src/Tests/ObjectsAsMethodsTest.class.st
  src/TraitsV2-Tests/T2AbstractTest.class.st
  src/TraitsV2-Tests/T2ObsoleteClassTest.class.st
  src/TraitsV2-Tests/T2OverloadingOfMethodsInTraitedClassTest.class.st
  src/TraitsV2-Tests/T2SubclassingTraitedClassTest.class.st
  src/TraitsV2-Tests/T2TraitAnnouncementsTest.class.st
  src/TraitsV2-Tests/T2TraitInTraitClassTest.class.st
  src/TraitsV2-Tests/T2TraitMCDefinitionsTest.class.st
  src/TraitsV2-Tests/T2TraitPropagatingSlotChangesTest.class.st
  src/TraitsV2-Tests/T2TraitSlotScopeTest.class.st
  src/TraitsV2-Tests/T2TraitTest.class.st
  src/TraitsV2-Tests/T2TraitWithAliasTest.class.st
  src/TraitsV2-Tests/T2TraitWithCategoriesTest.class.st
  src/TraitsV2-Tests/T2TraitWithComplexSlotsTest.class.st
  src/TraitsV2-Tests/T2TraitWithConflictsTest.class.st
  src/TraitsV2-Tests/T2TraitWithPackagesTest.class.st
  src/TraitsV2-Tests/T2TraitWithSlotsTest.class.st
  src/TraitsV2-Tests/T2UsingTraitsWithSlotsTest.class.st
  src/Zinc-Resource-Meta-Tests/ZnFileUrlTest.class.st
  src/Zinc-Zodiac/ZnHTTPSTest.class.st
Labels: tests passed please review!

#4312 2540-self-theme-settings-fadedBackgroundWindows-is-overzealous-violation-of-LOD
  src/Morphic-Base/HaloMorph.class.st
  src/Morphic-Base/MenuItemMorph.class.st
  src/Morphic-Base/SelectionMorph.class.st
  src/Morphic-Widgets-List/SimpleHierarchicalListMorph.class.st
  src/Morphic-Widgets-Pluggable/PluggableListMorph.class.st
  src/Morphic-Widgets-Taskbar/TaskbarMorph.class.st
  src/Morphic-Widgets-Tree/MorphTreeMorph.class.st
  src/Morphic-Widgets-Windows/SystemWindow.class.st
  src/Polymorph-Widgets/AnimationSettings.class.st
  src/Polymorph-Widgets/SystemWindow.extension.st
  src/Polymorph-Widgets/UITheme.class.st
Labels: tests passed please review!

#4163 Adding a variation of trait sequence composition that has preference for one of the members.
  src/TraitsV2-Tests/T2PrecedenceCompositionTest.class.st
  src/TraitsV2/TaPrecedenceComposition.class.st
  src/TraitsV2/TaSequence.class.st
Labels: tests passed please review!

#4360 Fixing change detection of traits
  src/TraitsV2-Tests/T2TraitChangesTest.class.st
  src/TraitsV2/TaAbstractComposition.class.st
  src/TraitsV2/TaAliasMethod.class.st
  src/TraitsV2/Trait.class.st
  src/TraitsV2/TraitBuilderEnhancer.class.st
Labels: tests passed please review!

#4325 4324-activateCursor-method-is-missing-on-WorldMorph
  src/Graphics-Display Objects/Cursor.class.st
  src/Morphic-Core/WorldMorph.class.st
Labels: tests passed please review!

#4359 4306-Add-comment-why-name-cache-in-SystemDictionary-is-sorted
  src/System-Support/SystemDictionary.class.st
Labels: tests passed please review!

#4368 4080-remove-the-class-instance-var-in-NECController
  src/NECompletion/NECController.class.st
Labels: tests passed please review!

#4376 4272 Fix Spelling of Responsability
  src/Debugger-Actions/SubclassResponsibilityDebugAction.class.st
  src/GT-Debugger/SubclassResponsibilityDebugAction.extension.st
  src/Zinc-HTTP/ZnSingleThreadedServer.class.st
Labels: tests passed please review!

#4390 FormCanvas-has-wrong-lazy-initialization
  src/Graphics-Canvas/FormCanvas.class.st
Labels: tests passed please review!

#4366 4365-Reintroduce-separator
  src/Morphic-Core/WorldState.class.st
Labels: tests passed please review!

#4378 4282-Backport-Pharo7-trying-to-add-an-ivar-to-UndefinedObject-crashes-the-VM-4017
  src/Shift-ClassBuilder/DangerousClassNotifier.class.st
Labels: tests passed please review!

#4388 4386-ZeroDivide-in-FTTableMorph
  src/Morphic-Widgets-FastTable/FTTableMorph.class.st
Labels: tests passed please review!

#4310 Use stack instead of recursion in MCScanner>>next
  src/Monticello/MCScanner.class.st
  src/System-Hashing/MD5NonPrimitive.class.st
Labels: tests passed please review!

#4379 Push-down-method-on-right-owner
  src/Morphic-Core/PasteUpMorph.class.st
  src/Morphic-Core/WorldMorph.class.st
Labels: tests passed please review!

#4391 Enable CDClassParser in class definition in Calypso
  src/Calypso-SystemTools-Core/CDSharedVariableNode.extension.st
  src/Calypso-SystemTools-Core/CDSlotNode.extension.st
  src/Calypso-SystemTools-Core/ClyClassDefinitionEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodEditorCommand.class.st
Labels: tests passed please review!

#4381 Add-deny-equivalent-of-assertCollection-hasSameElements
  src/SUnit-Core-Traits/TAssertable.trait.st
  src/SUnit-Core/TestAsserter.class.st
  src/SUnit-Tests/TestAsserterTest.class.st
Labels: tests passed please review!

#4347 Monticello-tests-should-not-depend-on-deprecated-streams
  src/Monticello-Tests/MCFileInTest.class.st
  src/Monticello-Tests/MCSerializationTest.class.st
Labels: tests passed please review!

#4396 Improve-WeakValueDictionary
  src/CodeImport/ChunkFileFormatParser.class.st
  src/Collections-Support/CollectionElement.class.st
  src/Collections-Support/SetElement.class.st
  src/Collections-Tests/WeakValueDictionaryTest.class.st
  src/Collections-Unordered/IdentitySet.class.st
  src/Collections-Unordered/PluggableSet.class.st
  src/Collections-Unordered/Set.class.st
  src/Collections-Weak/WeakSet.class.st
  src/Collections-Weak/WeakValueDictionary.class.st
  src/Deprecated80/CollectionElement.extension.st
  src/Deprecated80/Object.extension.st
  src/Deprecated80/SetElement.class.st
  src/Fuel-Core/Set.extension.st
  src/Fuel-Tests-Core/FLBasicSerializationTest.class.st
  src/Kernel/Object.class.st
  src/Kernel/UndefinedObject.class.st
  src/OpalCompiler-Core/OCKeyedSet.class.st
  src/PharoBootstrap-Initialization/PharoBootstrapInitialization.class.st
Labels: tests passed please review!

#4367 4149-instVarNames-is-not-including-instance-variables-coming-from-Stateful-traits
  src/Kernel/ClassDescription.class.st
  src/Monticello/Class.extension.st
  src/Monticello/Trait.extension.st
  src/TraitsV2-Tests/T2TraitWithSlotsTest.class.st
Labels: tests passed please review!

#4254 Pre-load MCWorkingCopy cache
  src/Monticello/MCWorkingCopy.class.st
Labels: tests passed please review!
