Repository pharo-project/pharo, pull requests merged in 2019-06, with the labels that each got.

#3136 Pharo8.0-ffi
  src/FreeType/FFIExternalStructureReferenceHandle.extension.st
  src/UnifiedFFI-Tests/FFICallbackParametersTests.class.st
  src/UnifiedFFI/ExternalAddress.extension.st
  src/UnifiedFFI/FFICallbackArgumentReader.class.st
  src/UnifiedFFI/FFIExternalStructureReferenceHandle.class.st
Labels: review

#3512 3511-browseAllAccessesTofrom-needs-to-use-slots-to-check-isAccessedIn
  src/Tool-Base/SystemNavigation.extension.st
Labels: tests passed please review!

#3504 3358-Why-do-we-have-RBRefactoryChangeManager-and-RBRefactoringManager
  src/Refactoring-Core/RBRefactoring.class.st
  src/Refactoring-Core/RBRefactoringManager.class.st
  src/Refactoring-Tests-Core/RBRefactoringTest.class.st
  src/Refactoring2-Transformations-Tests/RBMethodProtocolTransformationTest.class.st
  src/Refactoring2-Transformations-Tests/RBRemoveProtocolTransformationTest.class.st
  src/Refactoring2-Transformations-Tests/RBTransformationTest.class.st
  src/Refactoring2-Transformations/RBAddAssignmentTransformation.class.st
  src/Refactoring2-Transformations/RBAddMessageSendTransformation.class.st
  src/Refactoring2-Transformations/RBAddPragmaTransformation.class.st
  src/Refactoring2-Transformations/RBAddReturnStatementTransformation.class.st
  src/Refactoring2-Transformations/RBAddSubtreeTransformation.class.st
  src/Refactoring2-Transformations/RBChangesBrowser.class.st
  src/Refactoring2-Transformations/RBClassTransformation.class.st
  src/Refactoring2-Transformations/RBCustomTransformation.class.st
  src/Refactoring2-Transformations/RBMoveTemporaryVariableDefinitionTransformation.class.st
  src/Refactoring2-Transformations/RBRemoveAssignmentTransformation.class.st
  src/Refactoring2-Transformations/RBRemoveDirectAccessToVariableTransformation.class.st
  src/Refactoring2-Transformations/RBRemovePragmaTransformation.class.st
  src/Refactoring2-Transformations/RBRenameClassTransformation.class.st
  src/Refactoring2-Transformations/RBRenameTemporaryVariableTransformation.class.st
  src/Refactoring2-Transformations/RBReplaceSubtreeTransformation.class.st
  src/Refactoring2-Transformations/RBSplitClassTransformation.class.st
  src/Refactoring2-Transformations/RBTransformation.class.st
Labels: tests passed please review!

#3517 3513-RubSmalltalkEditorrefencesTo-should-no-use-instVarIndexOf-to-check-existence-of-invar
  src/Rubric/RubSmalltalkEditor.class.st
Labels: tests passed please review!

#3516 3515-remove-InstanceVariableSlotusingMethods
  src/Slot-Core/InstanceVariableSlot.class.st
Labels: tests passed please review!

#3454 2332-groupedBy-does-not-work-for-SortedCollection
  src/Collections-Sequenceable/SortedCollection.class.st
  src/Collections-Tests/SortedCollectionTest.class.st
Labels: tests passed please review!

#3521 3514-SystemNavigation-allAccessesTo-instVarName-from-aClass-should-delegate-to-slot-with-allMethodsAccessingSlot
  src/GT-SpotterExtensions-Core/Slot.extension.st
  src/System-Support/SystemNavigation.class.st
  src/Tool-Base/SystemNavigation.extension.st
Labels: tests passed please review!

#3500 3499-remove-literalScannedAsnotifying
  src/Kernel/Behavior.class.st
  src/Kernel/UndefinedObject.class.st
Labels: tests passed please review!

#3548 3547-deprecate-instanceVariables
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#3552 3549-do-we-need-instVarNameForIndex-
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#3288 3287-Redefine isClass in Trait
  src/TraitsV2/Trait.class.st
Labels: tests passed please review!

#3281 3233-Windows-file-references-broken-in-P8
  src/FileSystem-Core/DiskDirectoryEntry.class.st
  src/FileSystem-Core/FileReference.class.st
  src/FileSystem-Disk/DiskStore.class.st
  src/FileSystem-Disk/WindowsStore.class.st
  src/FileSystem-Tests-Core/DirectoryEntryTest.class.st
  src/FileSystem-Tests-Core/FileReferenceTest.class.st
  src/GT-InspectorExtensions-Core/AbstractFileReference.extension.st
Labels: tests passed please review!

#3510 3509-Slots-do-not-use-Association-to-reference-objects-in-compiled-code-but-AdditionalBinding
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Tests/OCBytecodeGeneratorTest.class.st
  src/Reflectivity/RFLiteralVariableNode.class.st
  src/Slot-Core/AdditionalBinding.class.st
  src/Slot-Core/LiteralVariable.class.st
  src/Slot-Core/Slot.class.st
  src/Slot-Examples/RelationSlot.class.st
Labels: tests passed please review!

#3551 3550-updateInstancesFrom-is-now-done-by-the-classbuilder
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#3566 3565-Small-cleanup-on-SystemNavigation-and-SmalltalkImage
  src/Calypso-SystemTools-Core/ClyClassDefinitionEditorToolMorph.class.st
  src/System-Support/SmalltalkImage.class.st
  src/System-Support/SystemDictionary.class.st
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#3579 3578-add-usingMethods-to-SharedPool-class
  src/Calypso-Browser/ClyQueryViewMorph.class.st
  src/Kernel/SharedPool.class.st
Labels: tests passed please review!

#3544 Correctly deprecate RGPackage and introduce Deprecated80 package
  src/BaselineOfPharo/BaselineOfPharo.class.st
  src/Deprecated80/RGPackage.class.st
  src/Deprecated80/package.st
Labels: tests passed please review!

#3581 3580-unify-RGMethodDefinition-creation-in-SystemNavigation-and-methodReference
  src/Ring-Deprecated-Core-Kernel/CompiledMethod.extension.st
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#3562 3561-clean-up-SystemNavigationremoveAllButPackages
  src/System-Support-Tests/SystemNavigationTest.class.st
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#3588 2611-Activating-slots-break-MCSnapshotBrowserTesttestClassSideClassSelected
  src/Monticello-Tests/MCSnapshotBrowserTest.class.st
Labels: tests passed please review!

#3587 Adding many tests for BlueInk.
  src/BlueInk-Tests/BIArrayExpressionTest.class.st
  src/BlueInk-Tests/BIAssignmentExpressionTest.class.st
  src/BlueInk-Tests/BIBlock2ExpressionTest.class.st
  src/BlueInk-Tests/BIBlockExpressionTest.class.st
  src/BlueInk-Tests/BICascadeExpressionTest.class.st
  src/BlueInk-Tests/BILiteralArrayExpressionTest.class.st
  src/BlueInk-Tests/BILiteralValueExpressionTest.class.st
  src/BlueInk-Tests/BIMessageExpressionTest.class.st
  src/BlueInk-Tests/BIMethodeExpressionTest.class.st
  src/BlueInk-Tests/BIParseErrorExpressionTest.class.st
  src/BlueInk-Tests/BIPatternBlockExpressionTest.class.st
  src/BlueInk-Tests/BIPragmaExpressionTest.class.st
  src/BlueInk-Tests/BIReturnExpressionTest.class.st
  src/BlueInk-Tests/BISequenceExpressionTest.class.st
  src/BlueInk-Tests/BISingleExpressionTest.class.st
  src/BlueInk-Tests/BITemporariesExpressionTest.class.st
  src/BlueInk-Tests/BIVariableExpressionTest.class.st
Labels: tests passed please review!

#3586 3584-SystemNavigation-use-methodReference
  src/Deprecated80/SystemNavigation.extension.st
  src/Kernel/Class.class.st
  src/Ring-Deprecated-Core-Kernel/CompiledMethod.extension.st
  src/System-Support/SystemNavigation.class.st
  src/Tool-Base/SystemNavigation.extension.st
Labels: tests passed please review!

#3583 Fix forked processes of TestResource from being terminated between TestCase methods being executed
  src/SUnit-Core/TestResource.class.st
  src/SUnit-Tests/TestResourceWithForkedProcessTestCase.class.st
  src/SUnit-Tests/WithForkedProcessTestResource.class.st
Labels: tests passed please review!

#3595 3505-ClassOrganization-rename-ivar-comment-to-commentRemoteString
  src/Kernel/ClassOrganization.class.st
  src/Shift-ClassBuilder/ClassOrganization.extension.st
Labels: tests passed please review!

#3611 3610-Move-extensions-methods-from-Spec-to-Morphic
  src/Morphic-Widgets-FastTable/FTBasicItem.class.st
  src/Morphic-Widgets-Windows/LayoutFrame.extension.st
  src/Spec-MorphicAdapters/FTBasicItem.extension.st
Labels: tests passed please review!

#3613 3612-add-allMethodsReadingSlot-and-allMethodsWritingSlot-and-tests
  src/Kernel-Tests/BehaviorTest.class.st
  src/Kernel/Behavior.class.st
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#3609 3492-CodeSearchingRule-looks-not-used-
  src/NautilusRefactoring/CodeSearchingRule.class.st
Labels: tests passed please review!

#3618 3616-RF-add-methodToExecute-reifications-for-messageSends
  src/Reflectivity-Examples/SelfPropagatingLinkDemo.class.st
  src/Reflectivity-Tests/ReflectivityReificationTest.class.st
  src/Reflectivity/RFMethodToExecuteReification.class.st
Labels: tests passed please review!

#3623 3622-cleanup-subclassesDo-multiple-identical-implementations
  src/Kernel/Behavior.class.st
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#3620 3619-Simplify-allCallsOn-
  src/Deprecated80/SystemNavigation.extension.st
  src/System-Support-Tests/ClassQueryTest.class.st
  src/System-Support/Behavior.extension.st
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#3590 3589-add-an-OSPlatform-visitor
  src/System-Platforms/MacOSPlatform.class.st
  src/System-Platforms/MacOSXPlatform.class.st
  src/System-Platforms/OSPlatform.class.st
  src/System-Platforms/OSPlatformVisitor.class.st
  src/System-Platforms/Unix32Platform.class.st
  src/System-Platforms/Unix64Platform.class.st
  src/System-Platforms/UnixPlatform.class.st
  src/System-Platforms/Win32Platform.class.st
  src/System-Platforms/Win64Platform.class.st
  src/System-Platforms/WinPlatform.class.st
Labels: tests passed please review!

#3537 Alien: NotFoundError name is too generic, use LibrarySymbolNotFoundError
  src/Alien-Core/Alien.class.st
  src/Alien-Core/LibrarySymbolNotFoundError.class.st
  src/Alien-Core/NotFoundError.class.st
Labels: tests passed please review!

#3629 3628-simplify-withAllSubclassesDo-and-withAllSuperclasses
  src/Kernel/Behavior.class.st
Labels: tests passed please review!

#3632 Fix small typo in bindAndJuggle:
  src/Kernel-BytecodeEncoders/BytecodeEncoder.class.st
Labels: tests passed please review!

#3655 3654-SystemNavigation-browseAllStoresIntofrom-and-cleanup
  src/System-Support-Tests/SystemNavigationTest.class.st
  src/System-Support/SystemNavigation.class.st
  src/Tool-Base/SystemNavigation.extension.st
Labels: tests passed please review!

#3647 3646-simplify-allSelectorsInProtocol
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#3658 3657-add-allClassVariables
  src/Kernel-Tests-Extended/ClassTest.class.st
  src/Kernel/Class.class.st
  src/Kernel/Metaclass.class.st
Labels: tests passed please review!

#3660 3659-add-isUsed-and-slotUsers-for-Slots-
  src/Slot-Core/Slot.class.st
  src/Slot-Tests/SlotTest.class.st
Labels: tests passed please review!

#3651 3650-unify-hasSlotNamed-in-AbractLayout-and-ClassDescription
  src/Kernel/ClassDescription.class.st
  src/Slot-Core/AbstractLayout.class.st
Labels: tests passed please review!

#3605 Fix (P7) forked processes of TestResource from being terminated between TestCase methods being executed
  src/SUnit-Core/TestResource.class.st
  src/SUnit-Tests/TestResourceWithForkedProcessTestCase.class.st
  src/SUnit-Tests/WithForkedProcessTestResource.class.st
Labels: tests passed please review!

#3649 3648-classThatDefinesInstanceVariable-is-taking-names-not-variables
  src/Deprecated80/ClassDescription.extension.st
  src/Kernel-Tests/ClassDescriptionTest.class.st
  src/Kernel/ClassDescription.class.st
  src/NECompletion/NECInstVarTypeGuesser.class.st
Labels: tests passed please review!

#3653 3652-we-have-isReferenced-for-Behavior-add-the-same-to-Variables
  src/Slot-Core/LiteralVariable.class.st
  src/Slot-Core/Slot.class.st
  src/Slot-Tests/LiteralVariableTest.class.st
  src/Slot-Tests/SlotTest.class.st
Labels: tests passed please review!

#3697 fixed a typo "runn" -> "run"
  .github/config.yml
Labels: more-information-needed

#3691 3661-simplify-allUnreferencedClassVariables
  src/Deprecated80/SystemNavigation.extension.st
  src/System-Support/Class.extension.st
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#3694 More improves in the speed of Spotter.
  src/GT-Spotter/GTFilterSubstring.class.st
  src/GT-Spotter/GTLimitArrived.class.st
  src/GT-Spotter/GTNullFilter.class.st
  src/GT-Spotter/GTStringFilter.class.st
  src/GT-Spotter/GTUnorderedFilter.class.st
Labels: tests passed please review!

#3701 3700-simplify-allUnreferencedInstanceVariables
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#3704 3630-small-cleanup-traits-in-Behaviour-isComposedBy-move-to-traits-
  src/Kernel/Behavior.class.st
  src/TraitsV2/Behavior.extension.st
Labels: tests passed please review!
