Repository pharo-project/pharo, pull requests merged in 2019-10, with the labels that each got.

#4771 fix all senders #namedTempAt:
  src/Debugging-Core/Context.extension.st
  src/GT-Inspector/GTInspectorContextNamedTempNode.class.st
  src/OpalCompiler-Tests/OCClosureCompilerTest.class.st
  src/SmartSuggestions/SugsBreakConditionSuggestion.class.st
  src/Spec2-Commander2-Tests/SpCommandTest.class.st
  src/Spec2-Commander2-Tests/SpMenuPresenterBuilderTest.class.st
  src/Spec2-Commander2-Tests/SpRecursiveContextSetterTest.class.st
  src/Spec2-Examples/SpClassMethodBrowser.class.st
  src/Spec2-Examples/SpDropListExample.class.st
  src/Spec2-Examples/SpMethodBrowser.class.st
  src/Spec2-Inspector/ContextTempEyeElement.class.st
Labels: tests passed please review!

#4774 4769-debuggerMap-move-implementation-to-Context
  src/Debugging-Core/Context.extension.st
  src/OpalCompiler-Core/DebuggerMethodMapOpal.class.st
Labels: tests passed please review!

#4783 4782-ContextempNamedput-needs-to-update-the-all-the-copied-temps-up-to-the-definition
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCCopyingTempVariable.class.st
  src/OpalCompiler-Core/OCTempVariable.class.st
  src/OpalCompiler-Tests/MethodMapExamples.class.st
  src/OpalCompiler-Tests/MethodMapTest.class.st
Labels: tests passed please review!

#4785 2201-Metalinks-are-leaving-methods-with-unbound-globals
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#4786 4661-doWithIndex-comment-is-incorrect
  src/Collections-Abstract/SequenceableCollection.class.st
  src/Slot-Core/LayoutClassScope.class.st
Labels: tests passed please review!

#4777 2312-ondo-contexts-added-on-step-through-not-removed
  src/Debugging-Core/Context.extension.st
  src/GT-Debugger/GTGenericStackDebugger.class.st
Labels: tests passed please review!

#4798 4796-remove-GTEventRecorderTest
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/GT-EventRecorder-Tests/GTDummyEvent.class.st
  src/GT-EventRecorder-Tests/GTEventBundleTest.class.st
  src/GT-EventRecorder-Tests/GTEventCollectorTest.class.st
  src/GT-EventRecorder-Tests/GTEventCollectorsTest.class.st
  src/GT-EventRecorder-Tests/GTEventConsolidateTest.class.st
  src/GT-EventRecorder-Tests/GTEventDeliveryTest.class.st
  src/GT-EventRecorder-Tests/GTEventMultiBundleFactoryTest.class.st
  src/GT-EventRecorder-Tests/GTEventMultiBundleTest.class.st
  src/GT-EventRecorder-Tests/GTEventPackingTest.class.st
  src/GT-EventRecorder-Tests/GTEventRecorderTest.class.st
  src/GT-EventRecorder-Tests/GTEventRecorderTestServer.class.st
  src/GT-EventRecorder-Tests/GTEventRegistryTest.class.st
  src/GT-EventRecorder-Tests/GTEventUnpackingTest.class.st
  src/GT-EventRecorder-Tests/GTFuelPackingTest.class.st
  src/GT-EventRecorder-Tests/GTStonPackingTest.class.st
Labels: tests passed please review!

#4793 4575-Completion-is-messing-Transcript
  src/NECompletion/CompletionContext.class.st
Labels: tests passed please review!

#4781 4780-OSWindow-is-not-passing-drop-files-events-to-Morhic
  src/Morphic-Base/DropFilesEvent.class.st
  src/Morphic-Core/PasteUpMorph.class.st
  src/OSWindow-Core/OSWindowMorphicEventHandler.class.st
  src/OSWindow-SDL2/OSSDL2Driver.class.st
Labels: tests passed please review!

#4805 CacheTempOffset
  src/OpalCompiler-Core/OCTempVariable.class.st
Labels: tests passed please review!

#4700 4698 reflectivity object centric features not migrated from p7 to p8
  src/Reflectivity-Tests/LinkInstallerTest.class.st
  src/Reflectivity-Tests/ManifestReflectivityTests.class.st
  src/Reflectivity-Tests/MetaLinkObjectAPITest.class.st
  src/Reflectivity-Tests/MetaLinkTargetResolverTest.class.st
  src/Reflectivity-Tests/ReflectivityExamples.class.st
  src/Reflectivity-Tests/ReflectivityExamples2.class.st
  src/Reflectivity-Tests/ReflectivityExamples2Subclass.class.st
  src/Reflectivity/Class.extension.st
  src/Reflectivity/ClassVariable.extension.st
  src/Reflectivity/GlobalVariable.extension.st
  src/Reflectivity/LiteralVariable.extension.st
  src/Reflectivity/MetaLink.class.st
  src/Reflectivity/MetaLinkAnonymousClassBuilder.class.st
  src/Reflectivity/MetaLinkInstaller.class.st
  src/Reflectivity/MetaLinkNodesMapper.class.st
  src/Reflectivity/MetaLinkRegistry.class.st
  src/Reflectivity/MetalinkChanged.class.st
  src/Reflectivity/MetalinkTargetResolver.class.st
  src/Reflectivity/Object.extension.st
  src/Reflectivity/PermaLink.class.st
  src/Reflectivity/RBProgramNode.extension.st
  src/Reflectivity/RBReturnNode.extension.st
  src/Reflectivity/RFValueReification.class.st
  src/Reflectivity/Slot.extension.st
  src/Reflectivity/TemporaryVariable.extension.st
Labels: tests passed please review!

#4799 4794-Simplify-parsing-in-Syntax-highlighter
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#4787 Speedup #usingMethod for classes and Globals
  src/Kernel/Behavior.class.st
  src/Slot-Core/ClassVariable.class.st
  src/Slot-Core/LiteralVariable.class.st
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#4804 Unify TempVector Read Write
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCVectorTempVariable.class.st
Labels: tests passed please review!

#4844 Document and Improve TempVector Access
  src/OpalCompiler-Core/OCVectorTempVariable.class.st
Labels: tests passed please review!

#4846 Simplify morph creation from Athens surface
  src/Athens-Core/AthensSurface.class.st
  src/Athens-Examples/AthensCairoSurfaceExamples.class.st
  src/Athens-Examples/AthensSurfaceExamples.class.st
  src/Athens-Examples/AthensTextRenderManualTests.class.st
Labels: tests passed please review!

#4853 Opal: remove #variableNamed:
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCAbstractScope.class.st
  src/OpalCompiler-Core/OCClassScope.class.st
  src/OpalCompiler-Core/OCExtraBindingScope.class.st
  src/OpalCompiler-Core/OCInstanceScope.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
Labels: tests passed please review!

#4851 use #lookupVar: instead of #lookupVarForDeclaration:
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCAbstractScope.class.st
  src/OpalCompiler-Core/OCInstanceScope.class.st
  src/Reflectivity/RFSemanticAnalyzer.class.st
Labels: tests passed please review!

#4858 Opal: compiler shoud not copy AST for pluging
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#4682 2874-clampLowHigh
  src/Kernel-Tests/MagnitudeTest.class.st
  src/Kernel/Magnitude.class.st
Labels: Reviewed and Ready to Integrate

#4857 Simplify TempVector Offset from IR
  src/OpalCompiler-Core/IRMethod.class.st
  src/OpalCompiler-Core/IRPushClosureCopy.class.st
  src/OpalCompiler-Core/IRSequence.class.st
  src/OpalCompiler-Core/OCCopyingTempVariable.class.st
Labels: tests passed please review!

#4868 Compiler: Document and simplify #lookupVar:
  src/OpalCompiler-Core/OCAbstractScope.class.st
  src/OpalCompiler-Core/OCExtraBindingScope.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
Labels: tests passed please review!

#4870 Compiler: Clean dead code
  src/OpalCompiler-Core/IRBuilder.class.st
  src/OpalCompiler-Core/IRBytecodeGenerator.class.st
  src/OpalCompiler-Core/IRMethod.class.st
  src/OpalCompiler-Core/IRPushClosureCopy.class.st
  src/OpalCompiler-Core/OCAbstractScope.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
  src/Slot-Core/BlockClosure.extension.st
  src/Slot-Core/CompiledMethod.extension.st
  src/Slot-Core/Context.extension.st
Labels: tests passed please review!

#4885 4883-FileSystemResolver-should-let-the-user-add-its-own-origins
  src/FileSystem-Core/FileSystemResolver.class.st
  src/FileSystem-Core/MacOSResolver.class.st
  src/FileSystem-Core/PlatformResolver.class.st
  src/FileSystem-Core/SystemResolver.class.st
  src/FileSystem-Core/UnixResolver.class.st
  src/FileSystem-Tests-Core/FileSystemResolverTest.class.st
  src/FileSystem-Tests-Core/InteractiveResolverTest.class.st
  src/FileSystem-Tests-Core/PlatformResolverTest.class.st
  src/FileSystem-Tests-Core/SystemResolverTest.class.st
Labels: tests passed please review!

#4889 Improve Comments MustBeBoolean
  src/OpalCompiler-Tests/MustBeBooleanTest.class.st
  src/OpalCompiler-Tests/MyBooleanObject.class.st
Labels: tests passed please review!

#4854 Add new #printOneLineString and related methods
  src/Collections-Streams/FilteringStream.class.st
  src/Collections-Streams/FilteringStreamTest.class.st
  src/Kernel-Tests/ObjectTest.class.st
  src/Kernel/Object.class.st
Labels: Reviewed and Ready to Integrate

#4882 4881-RBImplementedNotSentRule-is-disabled
  src/GeneralRules/RBImplementedNotSentRule.class.st
  src/Renraku/ReRuleManager.class.st
Labels: tests passed please review!

#4893 4843-Semantic-Analysis-add-a-temp-variable-for-the-Temp-Vector-Copied-Var
  src/OpalCompiler-Core/OCASTClosureAnalyzer.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCCopyingTempVariable.class.st
  src/OpalCompiler-Core/OCTempVariable.class.st
  src/OpalCompiler-Core/OCVectorTempVariable.class.st
Labels: tests passed please review!

#4713 Fix Issue 4693
  src/Athens-Cairo/CairoLibrary.class.st
  src/FreeType/FT2FFILibrary.class.st
  src/FreeType/FT2Face.class.st
  src/UnifiedFFI-Legacy/Object.extension.st
  src/UnifiedFFI-Tests/FFICalloutAPITest.class.st
  src/UnifiedFFI-Tests/FFICalloutMethodBuilderTest.class.st
  src/UnifiedFFI/DynamicLoader.class.st
  src/UnifiedFFI/ExternalAddress.extension.st
  src/UnifiedFFI/FFICalloutAPI.class.st
  src/UnifiedFFI/FFICalloutMethodBuilder.class.st
  src/UnifiedFFI/FFICompilerPlugin.class.st
  src/UnifiedFFI/FFILibrary.class.st
  src/UnifiedFFI/FFIUnknownLibrary.class.st
  src/UnifiedFFI/LibC.class.st
  src/UnifiedFFI/MacOSPlatform.extension.st
  src/UnifiedFFI/OSPlatform.extension.st
  src/UnifiedFFI/Object.extension.st
  src/UnifiedFFI/Unix32Platform.extension.st
  src/UnifiedFFI/Unix64Platform.extension.st
  src/UnifiedFFI/UnixPlatform.extension.st
  src/UnifiedFFI/WinPlatform.extension.st
  src/UnifiedFFI/WindowsDynamicLoader.class.st
Labels: Need more work

#4923 Spec Deprecation Rewrites
  src/Spec2-Deprecated/SpDropListButton.class.st
  src/Spec2-Deprecated/SpLabelledDropListButton.class.st
  src/Spec2-Deprecated/SpPickListPresenter.class.st
Labels: tests passed please review!

#4930 4927-Deprecation-a-normal-Deprecation-shows-the-warning-for-rewrite-deprecations
  src/Kernel/Deprecation.class.st
Labels: tests passed please review!

#4929 4926-reduce-references-to-NECController
  src/NECompletion-Tests/CompletionControllerTest.class.st
  src/NECompletion-Tests/NECUntypedModelTest.class.st
  src/NECompletion/CompletionProducerVisitor.class.st
  src/Rubric-Tests/RubSmalltalkEditorTest.class.st
Labels: tests passed please review!

#4933 CompletionCleanup: get class from AST
  src/NECompletion/CompletionContext.class.st
  src/NECompletion/CompletionEntry.class.st
  src/NECompletion/CompletionModel.class.st
  src/NECompletion/CompletionProducerVisitor.class.st
Labels: tests passed please review!

#4934 4863-Completion-in-class-comment-leads-to-DNU
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core/RBParser.class.st
Labels: tests passed please review!

#4936 CompletionOldCompletionRemove
  src/NECompletion/CompletionContext.class.st
  src/NECompletion/CompletionController.class.st
  src/NECompletion/NECClassVarEntry.class.st
  src/NECompletion/NECClassVarTypeGuesser.class.st
  src/NECompletion/NECContext.class.st
  src/NECompletion/NECController.class.st
  src/NECompletion/NECEmptyModel.class.st
  src/NECompletion/NECEntry.class.st
  src/NECompletion/NECGlobalEntry.class.st
  src/NECompletion/NECInstVarEntry.class.st
  src/NECompletion/NECInstVarTypeGuesser.class.st
  src/NECompletion/NECModel.class.st
  src/NECompletion/NECTypeInfo.class.st
  src/NECompletion/NECTypedModel.class.st
  src/NECompletion/NECUntypedModel.class.st
  src/NECompletion/NECVarTypeGuesser.class.st
  src/NECompletion/SHParserST80.class.st
  src/NECompletion/SHRange.class.st
Labels: tests passed please review!

#4942 Cleanup #guessTypeForName:
  src/Calypso-Browser/ClyTextEditorToolMorph.class.st
  src/Glamour-Morphic-Widgets/GLMRubricSmalltalkTextModel.class.st
  src/Glamour-Morphic-Widgets/GLMSmalltalkCodeModel.class.st
  src/NECompletion/AbstractTool.extension.st
  src/NECompletion/FinderUI.extension.st
  src/NECompletion/NECLocalEntry.class.st
  src/NECompletion/NECSelectorEntry.class.st
  src/NECompletion/NECSelfEntry.class.st
  src/NECompletion/NECSuperEntry.class.st
  src/Rubric/RubScrolledTextModel.class.st
  src/Rubric/RubWorkspaceExample.class.st
  src/Spec-MorphicAdapters/MorphicTextAdapter.class.st
  src/Spec2-Adapters-Morphic/SpMorphicCodeAdapter.class.st
  src/Tool-Workspace/Workspace.class.st
Labels: tests passed please review!

#4952 Cleanup #ultimateSourceCodeAt:ifAbsent:
  src/Kernel/Behavior.class.st
  src/Tool-Profilers/TimeProfiler.class.st
Labels: tests passed please review!

#5023 Allow-to-use-boolean-with-sort-functions
  src/SortFunctions-Core/Boolean.extension.st
  src/SortFunctions-Tests/SortFunctionTest.class.st
  src/SortFunctions-Tests/ThreeWayComparisonTest.class.st
Labels: tests passed please review!

#5027 Dictionary #value should use #streamContents:
  src/Collections-Unordered/Dictionary.class.st
  src/Collections-Unordered/SmallDictionary.class.st
Labels: tests passed please review!

#5033 Use NECEntry
  src/NECompletion/CompletionEntry.class.st
  src/NECompletion/CompletionModel.class.st
  src/NECompletion/FinderUI.extension.st
  src/NECompletion/NECEntry.class.st
  src/NECompletion/NECLocalEntry.class.st
  src/NECompletion/NECSelectorEntry.class.st
  src/NECompletion/RBProgramNode.extension.st
  src/NECompletion/TextEditor.extension.st
  src/Tool-Finder/FinderUI.class.st
Labels: tests passed please review!

#5026 4481-Copying-class-does-not-copy-class-comment
  src/Kernel/Class.class.st
Labels: tests passed please review!

#5032 table-headers-should-not-be-rows
  src/Morphic-Widgets-FastTable/FTTableContainerMorph.class.st
  src/Morphic-Widgets-FastTable/FTTableHeaderRowMorph.class.st
Labels: tests passed please review!

#5037 5031-Optimize-newstreamContents
  src/Collections-Abstract/SequenceableCollection.class.st
Labels: tests passed please review!

#5038 Code completion: Remove Producer
  src/NECompletion/CompletionEngine.class.st
  src/NECompletion/CompletionModel.class.st
  src/NECompletion/CompletionProducerVisitor.class.st
  src/NECompletion/NECEntryDescription.class.st
  src/NECompletion/RBLiteralValueNode.extension.st
  src/NECompletion/RBMessageNode.extension.st
  src/NECompletion/RBMethodNode.extension.st
  src/NECompletion/RBPragmaNode.extension.st
  src/NECompletion/RBProgramNode.extension.st
  src/NECompletion/RBVariableNode.extension.st
Labels: tests passed please review!

#5034 5029-ChunkWriteStreamnextPut-contains-a-very-inefficient-loop
  src/CodeExport/ChunkWriteStream.class.st
  src/CodeExport/WriteStream.extension.st
  src/System-Sources/SourceFile.class.st
  src/System-Sources/SourceFileCharacterReadWriteStream.class.st
Labels: tests passed please review!
