Repository pharo-project/pharo, pull requests merged in 2020-11, with the labels that each got.

#7637 Fixed #7187. Removed SystemReporter and SizeReporter. They were replaced with Spec-based StSystemReporter and StSizeReporter
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/NewTools-SystemReporter/StSizeReporter.class.st
  src/Tool-SystemReporter/AbstractReporter.class.st
  src/Tool-SystemReporter/SizeReporter.class.st
  src/Tool-SystemReporter/SystemReporter.class.st
  src/Tool-SystemReporter/package.st
Labels: Need more work

#7633 7585-Fix-dependency-to-get-a-green-bar-again
  src/Kernel-Tests-Extended/SharedPoolTest.extension.st
  src/Kernel-Tests/ExampleForTestWithSharedPool.class.st
  src/Kernel-Tests/FluidClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/OldPharoClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2CommonClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2FluidClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2OldPharoClassDefinitionPrinterTest.class.st
Labels: tests passed please review!

#7629 Fixed #7487. Added protocol column to ClyQueryBrowser
  src/Calypso-SystemQueries/ClyMethodDefinitionProperty.class.st
  src/Calypso-SystemTools-QueryBrowser/ClyQueryBrowser.class.st
Labels: tests passed please review!

#7649 7648-Fluid-rescue-test-for-compactClassDefinition-and-compactTraitDefinition
  src/Kernel-Tests/FluidClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/MockWithComplexSlot.class.st
  src/Kernel/OldPharoClassDefinitionPrinter.class.st
  src/TraitsV2-Tests/T2FluidClassDefinitionPrinterTest.class.st
Labels: tests passed please review!

#7654 7652-What-is-the-purpose-of-testObjectFormatInstSize
  src/Kernel-Tests/ClassHierarchyTest.class.st
Labels: tests passed please review!

#7641 6731 use announcements instead of ad hoc observer in breakpoints
  src/Calypso-SystemPlugins-Reflectivity-Queries/BreakpointAnnouncement.extension.st
  src/Reflectivity-Tools-Tests/BreakpointObserverTest.class.st
  src/Reflectivity-Tools-Tests/BreakpointTest.class.st
  src/Reflectivity/Breakpoint.class.st
  src/Reflectivity/BreakpointActivationNotification.class.st
  src/Reflectivity/BreakpointAdded.class.st
  src/Reflectivity/BreakpointAddedNotification.class.st
  src/Reflectivity/BreakpointAnnouncement.class.st
  src/Reflectivity/BreakpointHit.class.st
  src/Reflectivity/BreakpointHitNotification.class.st
  src/Reflectivity/BreakpointNotification.class.st
  src/Reflectivity/BreakpointRemoved.class.st
  src/Reflectivity/BreakpointRemovedNotification.class.st
  src/Reflectivity/ExecutionCounter.class.st
  src/Reflectivity/VariableBreakpoint.class.st
Labels: tests passed please review!

#7618 Cleanups in Fonts-Infrastructure and Fonts-Infrastructure-Tests-Logical
  src/Fonts-Infrastructure-Tests/LogicalFontManager.extension.st
  src/Fonts-Infrastructure-Tests/LogicalFontManagerTest.class.st
  src/Fonts-Infrastructure/AbstractFontFamily.class.st
  src/Fonts-Infrastructure/AbstractFontFamilyMember.class.st
  src/Fonts-Infrastructure/AbstractFontProvider.class.st
  src/Fonts-Infrastructure/LogicalFont.class.st
  src/Fonts-Infrastructure/LogicalFontManager.class.st
  src/Fonts-Infrastructure/TextStyleAsFontFamily.class.st
  src/Fonts-Infrastructure/TextStyleAsFontFamilyMember.class.st
Labels: tests passed please review!

#7664 add deprecated #isSpecial
  src/Ring-Core/RGVariable.class.st
Labels: tests passed please review!

#7657 7584-Fluid-Complex-slot-should-force-display-of-fluid-class-definition
  Jenkinsfile
  bootstrap/src/Pharo30Bootstrap/PBBootstrap.class.st
  src/BaselineOfTraits/BaselineOfTraits.class.st
  src/Calypso-SystemTools-Core/ClyClassDefinitionEditorToolMorph.class.st
  src/ClassParser-Tests/CDClassParserSelectionTest.class.st
  src/ClassParser/CDFluidClassDefinitionParser.class.st
  src/ClassParser/ClassDescription.extension.st
  src/Kernel-Tests/FluidClassDefinitionPrinterTest.class.st
  src/Kernel/ClassDefinitionPrinter.class.st
  src/Kernel/FluidClassDefinitionPrinter.class.st
  src/Kernel/OldPharoClassDefinitionPrinter.class.st
  src/TraitsV2-Tests/T2AbstractTest.class.st
  src/TraitsV2-Tests/T2CommonClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2FluidClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2ObsoleteClassTest.class.st
  src/TraitsV2-Tests/T2OldPharoClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2OverloadingOfMethodsInTraitedClassTest.class.st
  src/TraitsV2-Tests/T2PrecedenceCompositionTest.class.st
  src/TraitsV2-Tests/T2SubclassingTraitedClassTest.class.st
  src/TraitsV2-Tests/T2TraitAnnouncementsTest.class.st
  src/TraitsV2-Tests/T2TraitChangesTest.class.st
  src/TraitsV2-Tests/T2TraitInTraitClassTest.class.st
  src/TraitsV2-Tests/T2TraitMCDefinitionsTest.class.st
  src/TraitsV2-Tests/T2TraitPropagatingSlotChangesTest.class.st
  src/TraitsV2-Tests/T2TraitSlotScopeTest.class.st
  src/TraitsV2-Tests/T2TraitTest.class.st
  src/TraitsV2-Tests/T2TraitWithAliasTest.class.st
  src/TraitsV2-Tests/T2TraitWithCategoriesTest.class.st
  src/TraitsV2-Tests/T2TraitWithComplexSlotsTest.class.st
  src/TraitsV2-Tests/T2TraitWithConflictsTest.class.st
  src/TraitsV2-Tests/T2TraitWithPackagesTest.class.st
  src/TraitsV2-Tests/T2TraitWithSlotsTest.class.st
  src/TraitsV2-Tests/T2UsingTraitsWithSlotsTest.class.st
  src/TraitsV2-Tests/TMockWithComplexSlot.trait.st
Labels: tests passed please review!

#7663 Updating Image to support correctly TFFI
  src/Athens-Cairo/AthensCairoCanvas.class.st
  src/Athens-Cairo/AthensCairoExportSurface.class.st
  src/Athens-Cairo/AthensCairoGradientPaint.class.st
  src/Athens-Cairo/AthensCairoMatrix.class.st
  src/Athens-Cairo/AthensCairoPathBuilder.class.st
  src/Athens-Cairo/AthensCairoStrokePaint.class.st
  src/Athens-Cairo/AthensCairoSurface.class.st
  src/Athens-Cairo/AthensCairoTransform.class.st
  src/Athens-Cairo/SQSurfaceDispatch.class.st
  src/OSWindow-SDL2/SDL2.class.st
  src/OSWindow-SDL2/SDLOSXPlatformInitializer.class.st
  src/UnifiedFFI-Tests/FFICallbackParametersTest.class.st
  src/UnifiedFFI-Tests/FFITestStructureSmallIntFloatStructure.class.st
  src/UnifiedFFI/FFIAlienCallback.class.st
  src/UnifiedFFI/FFICallback.class.st
  src/UnifiedFFI/FFICallbackFunctionResolution.class.st
  src/UnifiedFFI/FFIExternalStructureType.class.st
  src/UnifiedFFI/FFIStructure.class.st
  src/UnifiedFFI/LibC.class.st
Labels: tests passed please review!

#7671 enable-testInsteadVariableReadTemp
  src/Reflectivity-Tests/ReflectivityControlTest.class.st
Labels: tests passed please review!

#7667 ReClassVariableNeitherReadNorWrittenRule
  src/GeneralRules-Tests/ReAbstractRuleTestCase.class.st
  src/GeneralRules-Tests/ReClassVariableNeitherReadNorWrittenRuleTest.class.st
  src/GeneralRules/ReClassVariableNeitherReadNorWrittenRule.class.st
  src/GeneralRules/ReIvarNeitherReadNorWrittenRule.class.st
Labels: tests passed please review!

#7672 VariableBreakpoint-fix-BrowserUpdate
  src/Reflectivity/Breakpoint.class.st
  src/Reflectivity/BreakpointAddedNotification.class.st
  src/Reflectivity/BreakpointHitNotification.class.st
  src/Reflectivity/BreakpointNotification.class.st
  src/Reflectivity/BreakpointRemovedNotification.class.st
  src/Reflectivity/VariableBreakpoint.class.st
Labels: tests passed please review!

#7660 Enhancements to Selector Extractor
  src/AST-Core-Tests/RBErrorNodeParserTest.class.st
  src/AST-Core/ManifestASTCore.class.st
  src/AST-Core/RBInvalidCascadeErrorNode.class.st
  src/AST-Core/RBMissingOpenerErrorNode.class.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBProgramNode.class.st
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
  src/Tools-CodeNavigation-Tests/CNSelectorExtractionOnPositionTest.class.st
  src/Tools-CodeNavigation-Tests/CNSelectorExtractionOnSelectionTest.class.st
  src/Tools-CodeNavigation-Tests/package.st
  src/Tools-CodeNavigation/CNSelectorExtractor.class.st
  src/Tools-CodeNavigation/package.st
Labels: tests passed please review!

#7676 MetaLink-DoNotAnnounceByDefault
  src/Reflectivity/Breakpoint.class.st
  src/Reflectivity/CompiledMethod.extension.st
  src/Reflectivity/ExecutionCounter.class.st
  src/Reflectivity/MetaLink.class.st
  src/Reflectivity/RBProgramNode.extension.st
  src/Reflectivity/ReflectiveMethod.class.st
  src/Reflectivity/Watch.class.st
Labels: tests passed please review!

#7673 left-option-key-in-mac-should-allow-to-enter-special-characters
  src/OSWindow-SDL2/OSSDL2BackendWindow.class.st
Labels: tests passed please review!

#7670 identityIncludesFontProvider: should be test extension
  src/Fonts-Infrastructure-Tests/LogicalFontManager.extension.st
  src/Fonts-Infrastructure/LogicalFontManager.class.st
Labels: tests passed please review!

#7680 add-asForm-transform-to-morph
  src/Morphic-Core/Morph.class.st
  src/Morphic-Widgets-Taskbar/Morph.extension.st
Labels: tests passed please review!

#7686 7522--Fluid--Adding-Setting-for-fluid-Syntax
  src/Kernel/ClassDefinitionPrinter.class.st
  src/Kernel/Slot.class.st
  src/Ring-Core/RGMetaclassStrategy.class.st
  src/Ring-Core/RGMetaclassTraitV2Strategy.class.st
Labels: tests passed please review!

#7691 7690-fluid-printer-has-some-duplicated-logic-
  src/Kernel/FluidClassDefinitionPrinter.class.st
Labels: tests passed please review!

#7669 Simplify-MetaLinkInstaller
  src/Reflectivity/MetaLink.class.st
  src/Reflectivity/MetaLinkInstaller.class.st
  src/Reflectivity/Object.extension.st
  src/Reflectivity/PermaLink.class.st
Labels: tests passed please review!

#7683 7682-ClassHierarchyPrinter-on-steroid-should-be-back-
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/Kernel-ExtraUtils/ClassHierarchyPrinter.class.st
  src/Kernel-ExtraUtils/ClassHierarchyPrinterTest.class.st
  src/Kernel-ExtraUtils/package.st
Labels: tests passed please review!

#7689 7687-Cannot-remove-a-Trait-written-with-the-fluid-syntax
  src/Refactoring-Changes/RBAddClassTraitChange.class.st
  src/Refactoring-Changes/RBAddMetaclassChange.class.st
  src/Refactoring-Changes/RBAddTraitChange.class.st
Labels: tests passed please review!

#7712 Cleanup Files-Tests package
  src/Files-Tests/BinaryFileStreamTest.class.st
  src/Files-Tests/FileRegistryTest.class.st
  src/Files-Tests/FileTest.class.st
  src/Files-Tests/StdioStreamTest.class.st
  src/Files-Tests/StdioStreamTestResource.class.st
Labels: tests passed please review!

#7666 CleanBlockChecker-Cleanup
  src/Debugging-Core/CleanBlockChecker.class.st
  src/Debugging-Core/CompiledCode.extension.st
  src/Debugging-Core/InstVarRefLocator.class.st
  src/Kernel/BlockClosure.class.st
Labels: tests passed please review!

#7709 EmbeddedFreeTypeFontFontDescription should be EmbeddedFreeTypeFontDescription - SECOND ATTEMPT
  src/Deprecated90/EmbeddedFreeTypeFontFontDescription.class.st
  src/EmbeddedFreeType/EmbeddedFreeTypeFontDescription.class.st
  src/EmbeddedFreeType/EmbeddedFreeTypeFontInstaller.class.st
  src/EmbeddedFreeType/LucidaGrandeRegular.class.st
  src/EmbeddedFreeType/SourceCodeProRegular.class.st
  src/EmbeddedFreeType/SourceSansProRegular.class.st
Labels: tests passed please review!

#7714 Added <debuggerCompleteToSender> pragma to user-level object error-handling protocol methods
  src/Kernel/Object.class.st
Labels: Enhancement, easyReview, tests passed please review!

#7704 Unify-OCInstanceScope-Behavior
  src/Kernel/Class.class.st
  src/Kernel/ReservedVariable.class.st
  src/Kernel/SelfVariable.class.st
  src/Kernel/SuperVariable.class.st
  src/Kernel/ThisContextVariable.class.st
  src/OpalCompiler-Core/Behavior.extension.st
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/IRTranslator.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCAbstractScope.class.st
  src/OpalCompiler-Core/OCExtraBindingScope.class.st
  src/OpalCompiler-Core/OCInstanceScope.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
  src/OpalCompiler-Tests/OCASTCheckerTest.class.st
  src/OpalCompiler-Tools/OCInstanceScope.extension.st
  src/Reflectivity/RFSemanticAnalyzer.class.st
  src/Slot-Core/SystemDictionary.extension.st
  src/System-Support/SystemDictionary.class.st
Labels: tests passed please review!

#7719 Introduce package Collections-Sequenceable-Tests
  src/BaselineOfKernelTests/BaselineOfKernelTests.class.st
  src/Collections-Sequenceable-Tests/Array2DTest.class.st
  src/Collections-Sequenceable-Tests/HeapTest.class.st
  src/Collections-Sequenceable-Tests/IntervalTest.class.st
  src/Collections-Sequenceable-Tests/LinkedListTest.class.st
  src/Collections-Sequenceable-Tests/OrderedCollectionTest.class.st
  src/Collections-Sequenceable-Tests/OrderedDictionaryTest.class.st
  src/Collections-Sequenceable-Tests/OrderedIdentityDictionaryTest.class.st
  src/Collections-Sequenceable-Tests/SharedQueueTest.class.st
  src/Collections-Sequenceable-Tests/SortedCollectionTest.class.st
  src/Collections-Sequenceable-Tests/package.st
Labels: tests passed please review!

#7723 NautilusRefactoring-DeadcodeClean
  src/NautilusRefactoring/ClassVariable.extension.st
  src/NautilusRefactoring/GlobalVariable.extension.st
  src/NautilusRefactoring/LocalVariable.extension.st
  src/NautilusRefactoring/NautilusRefactoring.class.st
  src/NautilusRefactoring/RBMessageNode.extension.st
  src/NautilusRefactoring/RBMethodNode.extension.st
  src/NautilusRefactoring/RBProgramNode.extension.st
  src/NautilusRefactoring/RBVariableNode.extension.st
  src/NautilusRefactoring/Slot.extension.st
Labels: tests passed please review!

#7710 DoItVariable instead of ForeignVariable and tests
  src/Kernel/DoItVariable.class.st
  src/Kernel/ForeignVariable.class.st
  src/Kernel/Variable.class.st
  src/Slot-Tests/DoItVariableTest.class.st
Labels: tests passed please review!

#7715 Compute and use the screen scale factor in OSWorldRenderer
  src/OSWindow-Core/OSWorldRenderer.class.st
  src/OSWindow-SDL2/OSSDL2AthensRenderer.class.st
  src/OSWindow-SDL2/OSSDL2BackendWindow.class.st
  src/OSWindow-SDL2/SDL2.class.st
  src/OSWindow-SDL2/SDL2ConstantsHint.class.st
Labels: tests passed please review!

#7739 BaseStreamTest had just one subclass. Move the tests there and remove…
  src/Monticello-Tests/MCDataStreamTest.class.st
  src/Tests/BaseStreamTest.class.st
Labels: tests passed please review!

#7729 Cleanup System-Support-Tests
  src/System-Support-Tests/AuthorTest.class.st
  src/System-Support-Tests/ClassQueryTest.class.st
  src/System-Support-Tests/ManifestSystemSupportTests.class.st
  src/System-Support-Tests/MethodQueryTest.class.st
  src/System-Support-Tests/SmalltalkImageTest.class.st
  src/System-Support-Tests/SystemDictionaryTest.class.st
  src/System-Support-Tests/SystemNavigationTest.class.st
  src/System-Support-Tests/SystemOrganizerTest.class.st
  src/System-Support-Tests/SystemVersionTest.class.st
Labels: tests passed please review!

#7736 Another cleanup pass on DoubleLinkedList package
  src/Collections-DoubleLinkedList/DoubleLinkedList.class.st
  src/Collections-DoubleLinkedList/ManifestCollectionsDoubleLinkedList.class.st
Labels: tests passed please review!

#7745 7731-OCUndeclaredVariableWarning-isUninitialized-with-NonInteractiveUIManager
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
Labels: tests passed please review!

#7746 Cleanup-SystemDictionary-varlookup
  src/System-Support/SystemDictionary.class.st
Labels: tests passed please review!

#7744 7740-CI-32bit-testIsImmediateObject
  src/Kernel-Tests/ProtoObjectTest.class.st
Labels: tests passed please review!

#7747 Disable the dpi based computation screen scale factor computation in OS X
  src/Morphic-Core/WorldMorph.class.st
  src/OSWindow-SDL2/OSSDL2BackendWindow.class.st
Labels: tests passed please review!

#7750 Add support for creating OpenGL ES contexts
  src/OSWindow-Core/OSWindowGLAttributes.class.st
  src/OSWindow-SDL2/OSSDL2Driver.class.st
Labels: tests passed please review!

#7726 FFICompilerPlugin-Simpler
  src/UnifiedFFI/FFICompilerPlugin.class.st
Labels: tests passed please review!

#7738 Allow catalog json to be served from GitHub and other
  src/Tool-Catalog/CatalogProvider.class.st
Labels: tests passed please review!

#7734 DeadCode-Cleanup-Finder
  src/Tool-Finder/DialogItemsChooser.class.st
  src/Tool-Finder/DialogItemsChooserUI.class.st
  src/Tool-Finder/Finder.class.st
  src/Tool-Finder/FinderPragmaNode.class.st
  src/Tool-Finder/FinderUI.class.st
  src/Tool-Finder/Object.extension.st
Labels: tests passed please review!

#7631 Compiler-compile-all-Literals-readOnly
  src/Kernel/Character.class.st
  src/OpalCompiler-Core/IRTranslator.class.st
Labels: tests passed please review!

#7766 Typo
  src/Hermes/ManifestHermes.class.st
Labels: tests passed please review!

#7767 #isReadOnlyLiteral is not needed anymore
  src/Collections-Native/ByteArray.class.st
  src/Collections-Sequenceable/Array.class.st
  src/Collections-Strings/String.class.st
  src/Kernel/Float.class.st
  src/Kernel/Integer.class.st
  src/Kernel/Object.class.st
  src/Kernel/ScaledDecimal.class.st
  src/Kernel/SmallFloat64.class.st
  src/Kernel/SmallInteger.class.st
  src/Tool-ImageCleaner/ImageCleaner.class.st
Labels: tests passed please review!

#7765 Move-isHaltNode-to-AST
  src/AST-Core/RBMessageNode.class.st
  src/AST-Core/RBProgramNode.class.st
  src/NewTools-Debugger-Extensions/RBMessageNode.extension.st
  src/NewTools-Debugger-Extensions/RBProgramNode.extension.st
Labels: tests passed please review!

#7762 ObjectsAsMethodsTest-move-to-Kernel-Tests
  src/Kernel-Tests/AbstractObjectsAsMethod.class.st
  src/Kernel-Tests/ObjectsAsMethodsExample.class.st
  src/Kernel-Tests/ObjectsAsMethodsTest.class.st
Labels: tests passed please review!

#7749 Variables defined with #primitive:error: are shown as undefined, fixes 7748
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/PrimitiveErrorVariable.class.st
  src/OpalCompiler-Core/RBPragmaNode.extension.st
  src/OpalCompiler-Core/TemporaryVariable.class.st
  src/OpalCompiler-Tests/OCASTCheckerTest.class.st
Labels: tests passed please review!

#7773 5457-environmentKeyNotFound-looks-deadcode
  src/Kernel/Process.class.st
Labels: tests passed please review!

#7732 Merge Iceberg v1.6.10 in Pharo 8
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: tests passed please review!

#7754 ReLiteralArrayContainsCommaRule should ignore all UFFI selectors
  src/GeneralRules/ReLiteralArrayContainsCommaRule.class.st
Labels: tests passed please review!

#7759 Move ReAsClassRule to GeneralRules
  src/BaselineOfRefactoring/BaselineOfRefactoring.class.st
  src/GeneralRules/ReAsClassRule.class.st
  src/System-Support-Rules/package.st
Labels: tests passed please review!

#7742 MetaLinks-Cleanup-Variables2
  src/Kernel/CompiledMethod.class.st
  src/Reflectivity-Tests/LinkInstallerTest.class.st
  src/Reflectivity/Behavior.extension.st
  src/Reflectivity/Class.extension.st
  src/Reflectivity/CompiledMethod.extension.st
  src/Reflectivity/MetaLink.class.st
  src/Reflectivity/Object.extension.st
Labels: tests passed please review!

#7757 7755 re excessive arguments rule should exclude ffi callouts
  src/GeneralRules-Tests/ReExcessiveArgumentsRuleTest.class.st
  src/GeneralRules/ReExcessiveArgumentsRule.class.st
Labels: tests passed please review!

#7780 Cleanup-Unused-Ivars
  src/Beacon-Core-Tests/MemoryLoggerTest.class.st
  src/GT-Spotter/GTSpotter.class.st
  src/Morphic-Widgets-Windows/SystemWindow.class.st
  src/Reflectivity-Tools-Tests/BreakpointTest.class.st
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
  src/Rubric/DummyFindReplaceService.class.st
  src/Tools-CodeNavigation-Tests/CNSelectorExtractionOnPositionTest.class.st
  src/Tools-CodeNavigation-Tests/CNSelectorExtractionOnSelectionTest.class.st
Labels: tests passed please review!

#7776 Rule based cleanup for RBCompositeRefactoryChange
  src/NautilusRefactoring/NautilusRefactoring.class.st
  src/Refactoring-Changes/RBCompositeRefactoryChange.class.st
  src/Refactoring-Changes/RBRenameClassChange.class.st
  src/Refactoring-Changes/RBRenameVariableChange.class.st
Labels: tests passed please review!

#7784 add testNoUnusedClassVariablesLeft (skipped for now)
  src/Growl/GrowlMorph.class.st
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
Labels: tests passed please review!

#7799 Remove unused var in SycMethodNameEditorTest
  src/SystemCommands-RefactoringSupport-Tests/SycMethodNameEditorTest.class.st
Labels: tests passed please review!

#7791 Var cleanup in DependencyAnalyser
  src/Tool-DependencyAnalyser-Tests/DAPackageRelationGraphTest.class.st
  src/Tool-DependencyAnalyser/DAPoolDictionaryDependency.class.st
Labels: tests passed please review!

#7789 Simplify ReExcessiveArgumentsRule>>#basicCheck:
  src/GeneralRules/ReExcessiveArgumentsRule.class.st
Labels: tests passed please review!

#7785 7777-Could-we-have-isTestMethod-on-Symbol-too
  src/Ring-Definitions-Core/RGMethodDefinition.class.st
  src/SUnit-Core/CompiledMethod.extension.st
  src/SUnit-Core/Symbol.extension.st
Labels: tests passed please review!

#7786 Add the missing implementation of OSSDL2GLRenderer >> #pixelExtent
  src/OSWindow-Core/OSWindowGenericRenderer.class.st
  src/OSWindow-Core/OSWindowRenderer.class.st
  src/OSWindow-SDL2/OSSDL2GLRenderer.class.st
  src/OSWindow-SDL2/SDL_Window.class.st
Labels: tests passed please review!

#7801 remove-halt-visitEnglobingErrorNode
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/Reflectivity-Tools/ErrorNodeStyler.class.st
Labels: tests passed please review!

#7805 Fulfil ClassTestCase>>#classToBeTested subclass reponsibility
  src/Collections-Sequenceable-Tests/HeapTest.class.st
  src/Collections-Sequenceable-Tests/IntervalTest.class.st
  src/Collections-Sequenceable-Tests/OrderedCollectionTest.class.st
  src/Collections-Sequenceable-Tests/SortedCollectionTest.class.st
  src/Collections-Strings-Tests/ByteSymbolTest.class.st
  src/Collections-Strings-Tests/SymbolTest.class.st
  src/Collections-Strings-Tests/WideStringTest.class.st
  src/Collections-Support-Tests/AssociationTest.class.st
  src/Collections-Tests/ArrayTest.class.st
  src/Collections-Tests/FloatArrayTest.class.st
  src/Collections-Unordered-Tests/BagTest.class.st
  src/Collections-Weak-Tests/WeakRegistryTest.class.st
  src/Graphics-Tests/PointTest.class.st
  src/Kernel-Tests-Extended/ClassTest.class.st
  src/Kernel-Tests/BehaviorTest.class.st
  src/Kernel-Tests/BooleanTest.class.st
  src/Kernel-Tests/ClassDescriptionTest.class.st
  src/Kernel-Tests/FalseTest.class.st
  src/Kernel-Tests/FractionTest.class.st
  src/Kernel-Tests/LargeNegativeIntegerTest.class.st
  src/Kernel-Tests/LargePositiveIntegerTest.class.st
  src/Kernel-Tests/NumberTest.class.st
  src/Kernel-Tests/ObjectTest.class.st
  src/Kernel-Tests/ProtoObjectTest.class.st
  src/Kernel-Tests/ScaledDecimalTest.class.st
  src/Kernel-Tests/SemaphoreTest.class.st
  src/Kernel-Tests/SmallIntegerTest.class.st
  src/Kernel-Tests/TrueTest.class.st
  src/Kernel-Tests/UndefinedObjectTest.class.st
  src/Kernel-Tests/WeakMessageSendTest.class.st
  src/Morphic-Tests/TextMorphTest.class.st
  src/Network-Tests/SocketStreamTest.class.st
  src/Random-Tests/RandomTest.class.st
  src/System-Hashing-Tests/MD5Test.class.st
  src/System-Hashing-Tests/SHA1Test.class.st
  src/System-Hashing-Tests/SHA256Test.class.st
  src/System-Object Events-Tests/EventManagerTest.class.st
Labels: tests passed please review!

#7811 Care on unused ivars in Renraku
  src/GeneralRules-Tests/ReTempVarOverridesInstVarRuleTest.class.st
  src/GeneralRules-Tests/ReTestCaseShouldNotUseInitializeRuleTest.class.st
  src/Renraku/ReRemoveMethodCritique.class.st
Labels: tests passed please review!

#7809 Unused ivar MorphicTabManagerAdapter
  src/Spec-MorphicAdapters/MorphicTabManagerAdapter.class.st
Labels: tests passed please review!

#7807 Cleanup and extend Dr. Test
  src/DrTests/DTBrowseSelectedItem.class.st
  src/DrTests/DTCommand.class.st
  src/DrTests/DTFilterableListPresenter.class.st
  src/DrTests/DTLeafResultCommand.class.st
  src/DrTests/DTMiddleListCommand.class.st
  src/DrTests/DTPackagesCommand.class.st
  src/DrTests/DTPackagesSelectAllCommand.class.st
  src/DrTests/DTPackagesSelectNoneCommand.class.st
  src/DrTests/DTResultBrowseCommand.class.st
  src/DrTests/DTResultCommand.class.st
  src/DrTests/DTStatusUpdate.class.st
  src/DrTests/DrTests.class.st
  src/DrTests/MiniDrTests.class.st
Labels: tests passed please review!

#7795 Remove FFITutorial
  src/UnifiedFFI/FFITutorial.class.st
Labels: tests passed please review!

#7781 PharoDocComment : remove a direct reference to RBParser
  src/PharoDocComment-Tests/PharoDocCommentExtensionsTest.class.st
  src/PharoDocComment-Tests/PharoDocCommentNodeTest.class.st
  src/PharoDocComment-Tests/PharoDocCommentTest.class.st
  src/PharoDocComment/DocCommentIconStyler.class.st
  src/PharoDocComment/PharoDocCommentExpression.class.st
Labels: tests passed please review!

#7814 Care on unsued ivars in Calypso
  src/Calypso-Browser/ClyNotebookPageMorph.class.st
  src/Calypso-NavigationModel-Tests/ClyBrowserQueryResultTestCase.class.st
  src/Calypso-SystemPlugins-Critic-Browser/ClyCriticContext.class.st
  src/Calypso-SystemPlugins-Critic-Queries-Tests/ClyGroupedCritiquesTest.class.st
  src/Calypso-SystemQueries-Tests-P1WithHierarchy/ClyClass1FromP1.class.st
  src/Calypso-SystemQueries-Tests-P1WithHierarchy/ClyClass2FromP1.class.st
  src/Calypso-SystemQueries-Tests-P1WithHierarchy/ClySubclassN1OfClass1FromP1.class.st
  src/Calypso-SystemQueries-Tests-P1WithHierarchy/ClySubclassN2OfClass1FromP1.class.st
  src/Calypso-SystemQueries-Tests/ClyAllMethodsQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyHierarchicalSystemItemsTest.class.st
  src/Calypso-SystemQueries-Tests/ClyVariableReadersQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyVariableWritersQueryTest.class.st
  src/Calypso-SystemQueries/ClyProjectManager.class.st
Labels: tests passed please review!

#7775 Merge-MethodNameEditor-RBMethodNameEditor
  src/NautilusRefactoring/MethodNameEditor.class.st
  src/Refactoring2-Transformations/RBMethodNameEditor.class.st
Labels: tests passed please review!

#7824 Unused ivar in Reflectivity-Tools-Tests
  src/Reflectivity-Tools-Tests/BreakpointObserverTest.class.st
Labels: tests passed please review!

#7822 Unused ivar in Clap
  src/Clap-Core/ClapDocumentationFormatter.class.st
Labels: tests passed please review!

#7793 Cleanup UnifiedFFI packages
  src/UnifiedFFI-Tests/FFIExternalObjectForTest.class.st
  src/UnifiedFFI-Tests/FFITestObject.class.st
  src/UnifiedFFI-Tests/FFITestStructure2DoubleStructure.class.st
  src/UnifiedFFI-Tests/FFITestStructure2Int64Structure.class.st
  src/UnifiedFFI-Tests/FFITestStructure4Int64Structure.class.st
  src/UnifiedFFI-Tests/FFITestStructureDoubleStructure.class.st
  src/UnifiedFFI-Tests/FFITestStructureIntStructure.class.st
  src/UnifiedFFI-Tests/FFITestType.class.st
  src/UnifiedFFI/FFIAlienCallback.class.st
  src/UnifiedFFI/FFICallout.class.st
  src/UnifiedFFI/FFIExternalStructureType.class.st
Labels: tests passed please review!

#7815 Fix side-effect in MCOrganizationDefinition
  src/Monticello/MCOrganizationDefinition.class.st
Labels: tests passed please review!

#7829 PharoDoc-pass2
  src/Collections-Sequenceable/OrderedDictionary.class.st
  src/Colors/Color.class.st
  src/Kernel/AsciiCharset.class.st
  src/PharoDocComment/CompiledMethod.extension.st
  src/PharoDocComment/PharoDocCommentExpression.class.st
  src/PharoDocComment/PharoDocCommentNode.class.st
Labels: tests passed please review!

#7819 Cleanup DrTest - pass #2
  src/DrTests/AbstractDrTestsUI.class.st
  src/DrTests/ClassDescription.extension.st
  src/DrTests/CompiledMethod.extension.st
  src/DrTests/DTFilterableListPresenter.class.st
  src/DrTests/DTLeavesCollector.class.st
  src/DrTests/DrTests.class.st
  src/DrTests/MiniDrTests.class.st
  src/GT-Playground/GTPlayground.class.st
  src/SUnit-UI/TestRunner.class.st
Labels: tests passed please review!

#7661 7347 improve exception description api
  src/Kernel-Tests/ExceptionTest.class.st
  src/Kernel-Tests/MessageNotUnderstoodTest.class.st
  src/Kernel-Tests/MyVariableNotDeclaredDummyClassForTest.class.st
  src/Kernel-Tests/VariableNotDeclaredTest.class.st
  src/Kernel/Exception.class.st
  src/Kernel/MessageNotUnderstood.class.st
  src/Kernel/VariableNotDeclared.class.st
Labels: tests passed please review!

#7828 7820 class description contains dead code related to slots printing
  src/Kernel/Class.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/Metaclass.class.st
  src/MonticelloGUI-Tests/MCSnapshotBrowserTest.class.st
  src/Spec2-Examples/SpTransmissionExample.class.st
Labels: tests passed please review!

#7833 `#ensureCreateDirectory` Shouldn't Resolve
  src/FileSystem-Core/AbstractFileReference.class.st
Labels: tests passed please review!

#7837 Trait was missing the #named:package: instance creation method
  src/TraitsV2/Trait.class.st
Labels: tests passed please review!

#7835 [Code cleaning] Replaced 'Character tab asString' to 'String tab'
  src/GT-Debugger/GTDebugActionButton.class.st
  src/Glamour-Morphic-Renderer/GLMMorphicActionRenderer.class.st
  src/System-Clipboard/Clipboard.class.st
  src/Zinc-Character-Encoding-Tests/ZnPercentEncoderTest.class.st
Labels: tests passed please review!

#7797 Remove unused trait users
  src/TraitsV2/Trait.class.st
Labels: tests passed please review!

#7844 SemanticAnalysis-Args-are-read
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Tests/OCASTClosureAnalyzerTest.class.st
  src/Slot-Tests/ArgumentVariableTest.class.st
Labels: tests passed please review!

#7845 Origin/7770 cleaning old definition printer
  src/Kernel/OldPharoClassDefinitionPrinter.class.st
  src/Refactoring-Changes/RBAddTraitChange.class.st
  src/Refactoring-Changes/RBRefactoryDefinitionChange.class.st
  src/TraitsV2-Tests/T2OldPharoClassDefinitionPrinterTest.class.st
Labels: tests passed please review!

#7836 Clean the OSWindowGenericRenderer texture APIs for properly implementing a text renderer
  src/OSWindow-Core/OSWindowGenericRenderer.class.st
  src/OSWindow-Core/OSWindowNullGenericRenderer.class.st
  src/OSWindow-Core/OSWindowRendererTexture.class.st
  src/OSWindow-SDL2/AbstractFont.extension.st
  src/OSWindow-SDL2/LogicalFont.extension.st
  src/OSWindow-SDL2/OSSDL2GenericRenderer.class.st
  src/OSWindow-SDL2/OSSDL2TextureAtlasEntry.class.st
  src/OSWindow-SDL2/OSSDL2TextureAtlasFontCache.class.st
  src/OSWindow-SDL2/OSSDL2WindowRendererTexture.class.st
  src/OSWindow-SDL2/SDL_Renderer.class.st
Labels: tests passed please review!

#7853 Accessor generator should create formatted version
  src/Refactoring-Core/RBCreateAccessorsForVariableRefactoring.class.st
  src/Refactoring2-Transformations/RBAddVariableAccessorTransformation.class.st
Labels: tests passed please review!

#7803 Add additional linux platform checking
  src/System-Platforms/UnixPlatform.class.st
Labels: tests passed please review!

#7779 Compilerbased-meta-data-tagging
  src/Debugging-Utils-Tests/HaltTest.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/CompiledMethod.class.st
  src/OpalCompiler-Core/OCASTMethodMetadataAnalyser.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
Labels: tests passed please review!

#7854 CompiledMethod-hasProperty-use-includesProperty
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#7783 reduce-ASTCache-reset
  src/Manifest-Tests/SmalllintManifestCheckerTest.class.st
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
Labels: tests passed please review!

#7847 Ban rule "class not referenced" for WebBrowser subclasses
  src/WebBrowser-Core/WebBrowser.class.st
Labels: tests passed please review!

#7834 Extracting FFI backend
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfPharoBootstrap/BaselineOfPharoBootstrap.class.st
  src/FFI-Kernel/ByteArray.extension.st
  src/FFI-Kernel/ExternalAddress.class.st
  src/FFI-Kernel/FFIBackend.class.st
  src/FFI-Kernel/NullFFIBackend.class.st
  src/FFI-OldFFIBackend/ByteArray.extension.st
  src/FFI-OldFFIBackend/ExternalAddress.extension.st
  src/FFI-OldFFIBackend/ExternalFunction.class.st
  src/FFI-OldFFIBackend/ExternalLibrary.class.st
  src/FFI-OldFFIBackend/ExternalLibraryFunction.class.st
  src/FFI-OldFFIBackend/Object.extension.st
  src/FFI-OldFFIBackend/OldFFIBackend.class.st
  src/FFI-OldFFIBackend/package.st
  src/InitializePackagesCommandLineHandler/InitializePackagesCommandLineHandler.class.st
  src/Kernel/BlockClosure.class.st
  src/Kernel/CleanBlockClosure.class.st
  src/Kernel/ManifestKernel.class.st
  src/Kernel/UndefinedObject.class.st
  src/OSWindow-SDL2/OSSDL2ExternalForm.class.st
  src/System-Platforms/MacOSPlatform.class.st
  src/System-Platforms/UnixPlatform.class.st
  src/System-Platforms/WinPlatform.class.st
  src/System-SessionManager/SessionManager.class.st
  src/UnifiedFFI-Tests/FFICallbackParametersTest.class.st
  src/UnifiedFFI-Tests/FFICallbackTest.class.st
  src/UnifiedFFI-Tests/FFICalloutAPITest.class.st
  src/UnifiedFFI-Tests/FFICalloutMethodBuilderTestContext.class.st
  src/UnifiedFFI-Tests/FFICompilerPluginTest.class.st
  src/UnifiedFFI-Tests/FFIConstantHandleTest.class.st
  src/UnifiedFFI-Tests/FFIExternalEnumerationTest.class.st
  src/UnifiedFFI-Tests/FFIMockCalloutMethodBuilder.class.st
  src/UnifiedFFI-Tests/FFITestObject.class.st
  src/UnifiedFFI/ExternalAddress.extension.st
  src/UnifiedFFI/FFIBackend.extension.st
  src/UnifiedFFI/FFICallback.class.st
  src/UnifiedFFI/FFICalloutAPI.class.st
  src/UnifiedFFI/FFICalloutMethodBuilder.class.st
  src/UnifiedFFI/FFILibrary.class.st
  src/UnifiedFFI/False.extension.st
  src/UnifiedFFI/Object.extension.st
  src/UnifiedFFI/True.extension.st
Labels: Need more work

#7864 7862-Cleaning-finder-code-glicthes
  src/Math-Operations-Extensions/Integer.extension.st
  src/Tool-Finder/ClassDescription.extension.st
  src/Tool-Finder/Integer.extension.st
  src/Tool-Finder/MethodFinder.class.st
  src/Tool-Finder/MethodFinderSend.class.st
Labels: tests passed please review!

#7873 shouldDisplayOnTopContext-seems-to-be-not-needed
  src/Debugger-Model/DebugSession.class.st
Labels: tests passed please review!

#7866 Deprecated Behavior methods should go to Deprecated Behavior methods …
  src/Deprecated90/Behavior.extension.st
  src/Kernel/Behavior.class.st
Labels: tests passed please review!

#7868 No "inconsistent method classification" for methods in deprecated method category
  src/GeneralRules/ReInconsistentMethodClassificationRule.class.st
Labels: tests passed please review!

#7727 Add ExternalAddress class>>#allocate:bytesDuring:
  src/FFI-Kernel/ExternalAddress.class.st
  src/OSWindow-SDL2/OSSDL2AthensRenderer.class.st
  src/OSWindow-SDL2/OSSDL2FormRenderer.class.st
  src/OSWindow-SDL2/OSSDL2GenericRenderer.class.st
  src/OSWindow-SDL2/SDL2.class.st
  src/OSWindow-SDL2/SDL_Renderer.class.st
Labels: tests passed please review!

#7880 Fixed #7840. Deprecating hasPropertyNamed:
  src/Ring-Core/RGObject.class.st
  src/Ring-Tests-Core/RGObjectTest.class.st
Labels: tests passed please review!

#7903 Cleanup code for Morph properties
  src/Morphic-Core/Morph.class.st
  src/Morphic-Core/MorphExtension.class.st
Labels: tests passed please review!

#7875 Fixed #7841 . Implementing hasProperty in Behavior and RPackage.
  src/Kernel-Tests/BehaviorTest.class.st
  src/Kernel/Behavior.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Tests/RPackageTest.class.st
Labels: tests passed please review!

#7902 Fix infinite recursion upon send of not-understood message to nil
  src/Kernel/UndefinedObject.class.st
Labels: tests passed please review!

#7885 Remove DeprecatedFileStream package
  bootstrap/scripts/4-build.sh
  src/BaselineOfPharoBootstrap/BaselineOfPharoBootstrap.class.st
  src/DeprecatedFileStream/FileExistsException.class.st
  src/DeprecatedFileStream/FileStream.class.st
  src/DeprecatedFileStream/LimitingLineStreamWrapper.class.st
  src/DeprecatedFileStream/ManifestDeprecatedFileStream.class.st
  src/DeprecatedFileStream/MultiByteBinaryOrTextStream.class.st
  src/DeprecatedFileStream/MultiByteFileStream.class.st
  src/DeprecatedFileStream/PositionableStream.extension.st
  src/DeprecatedFileStream/RWBinaryOrTextStream.class.st
  src/DeprecatedFileStream/StandardFileStream.class.st
  src/DeprecatedFileStream/package.st
  src/Fuel-Core/StandardFileStream.extension.st
  src/Fuel-Core/ZnBufferedReadStream.extension.st
  src/Fuel-Tests-Core/FLBinaryFileStreamSerializationTest.class.st
  src/Fuel-Tests-Core/FLBinaryFileStreamStrategy.class.st
  src/Fuel-Tests-Core/FLFileStreamStrategy.class.st
  src/Fuel-Tests-Core/FLMultiByteStreamStrategy.class.st
  src/Fuel-Tests-Core/FLSerializationTest.class.st
  src/Fuel-Tests-Core/FLStandardFileStreamSerializationTest.class.st
  src/Graphics-Primitives/StandardFileStream.extension.st
  src/Metacello-PharoCommonPlatform/MetacelloPharoCommonPlatform.class.st
  src/Monticello-Tests/MCDataStreamTest.class.st
  src/Monticello/MCDataStream.class.st
  src/Monticello/MCVersionReader.class.st
  src/MonticelloConfigurations/MCPseudoFileStream.class.st
  src/MonticelloGUI/MCWorkingCopyBrowser.class.st
  src/Multilingual-Tests/ByteTextConverterTest.class.st
  src/Network-MIME/MIMEDocument.class.st
  src/Network-Mail/MIMEDocument.extension.st
  src/Network-Mail/MailMessage.class.st
  src/Network-Protocols/FTPClient.class.st
  src/PharoBootstrap-Initialization/PharoBootstrapInitialization.class.st
  src/System-Changes-FileServices/ChangeSet.extension.st
  src/System-Changes/ChangeSet.class.st
  src/System-Installers-Tests/MCMczInstallerTest.class.st
  src/System-SessionManager/SessionManager.class.st
  src/Tests/FileStreamTest.class.st
  src/Tests/TraitFileOutTest.class.st
  src/Tool-ExternalBrowser/ExternalChangesBrowser.class.st
  src/Tool-FileList/FileList.class.st
  src/Tool-FileList/FileStream.extension.st
  src/Zinc-Resource-Meta-Core/FileStream.extension.st
  src/Zinc-Zodiac/ZnHTTPSTest.class.st
Labels: tests passed please review!

#7917 optimize-hasDropShadow
  src/Morphic-Core/Morph.class.st
Labels: tests passed please review!
