Repository pharo-project/pharo, pull requests merged in 2020-03, with the labels that each got.

#5780 Using Image relative font files can not work
  src/FreeType/FreeTypeFontProvider.class.st
Labels: tests passed please review!

#5825 5824-remove-class-var-that-is-still-referenced-change-is-not-saved
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
Labels: tests passed please review!

#5835 5830-speed-up-NoUnusedTemporaryVariablesLeftTest
  src/ReleaseTests/NoUnusedTemporaryVariablesLeftTest.class.st
Labels: tests passed please review!

#5797 5791-AbstractEnvironmentTestCase-logic-is-bogus
  src/OpalCompiler-Tests/OCBytecodeDecompilerTest.class.st
  src/SUnit-Core/AbstractEnvironmentTestCase.class.st
Labels: tests passed please review!

#5732 Renaming packages leads to out of synch manifest names
  src/Manifest-Core/TheManifestBuilder.class.st
  src/ReleaseTests/ReleaseTest.class.st
Labels: tests passed please review!

#5718 Fix: exporting only non empty RGPackages to Tonel
  src/Ring-Monticello/RGEnvironment.extension.st
Labels: tests passed please review!

#5833 ifNil isnteado of == nil ifTrue #5832
  src/Metacello-Core/MetacelloAbstractPackageSpec.class.st
Labels: tests passed please review!

#5831 ReadStream optimization for #upToAll:
  src/Collections-Streams/PositionableStream.class.st
  src/Collections-Streams/ReadStream.class.st
Labels: tests passed please review!

#5857 isLiteralMethod-should-work-on-sista
  src/Calypso-SystemQueries/CompiledMethod.extension.st
  src/Kernel-BytecodeEncoders/BytecodeEncoder.class.st
  src/Kernel-BytecodeEncoders/EncoderForSistaV1.class.st
  src/Kernel-BytecodeEncoders/EncoderForV3.class.st
Labels: tests passed please review!

#5789 Possible-to-duplicate-of-Instance-variable-through-a-bug
  src/Shift-ClassBuilder/ShLayoutDefinition.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/Shift-ClassInstaller-Tests/ShClassInstallerTest.class.st
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
  src/TraitsV2-Tests/T2TraitSlotScopeTest.class.st
Labels: tests passed please review!

#5858 shout-make-configurable-the-formatIncompleteIdentifiers
  src/Shout-Tests/SHRBTextStylerTest.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#5839 5524-SequenceableCollection-select-should-use-species-instead-of-class
  src/Collections-Abstract/SequenceableCollection.class.st
Labels: tests passed please review!

#5844 Fix Alien libcName
  src/Alien-Core/Alien.class.st
Labels: tests passed please review!

#5848 UnsafeAlien is missing nonPointerObject: implementation
  src/Alien-Core/UnsafeAlien.class.st
Labels: tests passed please review!

#5880 Bug in the comparison of CompiledMethods
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel/CompiledCode.class.st
Labels: tests passed please review!

#5806 Add executable comments in SequenceableCollection - conevrting protocol
  src/Collections-Sequenceable/OrderedCollection.class.st
Labels: Need more work

#5770 Revert "5724-Improve-AdditionalMethodStaterefersToLiteral"
  src/Collections-Support/LookupKey.class.st
  src/Kernel/AdditionalMethodState.class.st
Labels: tests passed please review!

#5890 Cleanup world
  src/BaselineOfMorphicCore/BaselineOfMorphicCore.class.st
  src/FormCanvas-Core/FormCanvas.class.st
  src/Morphic-Core/AbstractWorldRenderer.class.st
  src/Morphic-Core/NullWorldRenderer.class.st
  src/Morphic-Core/PasteUpMorph.class.st
  src/Morphic-Core/VMDisplayDeferredUpdateMode.class.st
  src/Morphic-Core/VMDisplayDirectUpdateMode.class.st
  src/Morphic-Core/VMWorldRenderer.class.st
  src/Morphic-Core/WorldMorph.class.st
  src/Morphic-Core/WorldState.class.st
  src/OSWindow-Core/ComposablePresenter.extension.st
  src/OSWindow-Core/OSWindowFormRenderer.class.st
  src/OSWindow-Core/OSWindowWorldMorphAdapter.class.st
  src/OSWindow-Core/OSWindowWorldMorphModel.class.st
  src/OSWindow-Core/OSWorldRenderer.class.st
Labels: tests passed please review!

#5886 Pharo8 Backport - Fixing problem with class trait compositions with parens.
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/ClassParser/CDTraitCompositionSequenceNode.class.st
  src/ClassParser/CDTraitPrecedenceCompositionNode.class.st
  src/Monticello/MCTraitDefinition.class.st
  src/Monticello/Trait.extension.st
  src/Ring-Definitions-Monticello/MCTraitDefinition.extension.st
  src/TraitsV2/TaPrecedenceComposition.class.st
Labels: tests passed please review!

#5105 5104-The-Through-button-in-the-debugger-should-be-named-Step
  src/Debugger-Actions/StepIntoDebugAction.class.st
  src/Debugger-Actions/StepOverDebugAction.class.st
  src/Debugger-Actions/StepThroughDebugAction.class.st
Labels: more-information-needed

#5761 Update Clap
  src/BaselineOfClap/BaselineOfClap.class.st
  src/Clap-CommandLine/ClapCommandLineHandler.class.st
  src/Clap-Commands-Pharo/ClapCodeEvaluator.class.st
  src/Clap-Commands-Pharo/ClapImage.class.st
  src/Clap-Commands-Pharo/ClapMetacello.class.st
  src/Clap-Commands-Pharo/ClapPharoApplication.class.st
  src/Clap-Commands-Pharo/ClapPharoVersion.class.st
  src/Clap-Commands-Pharo/ClapTestRunner.class.st
  src/Clap-Core/ClapApplication.class.st
  src/Clap-Core/ClapCommand.class.st
  src/Clap-Core/ClapCompositeMatch.class.st
  src/Clap-Core/ClapContext.class.st
  src/Clap-Core/ClapExpression.class.st
  src/Clap-Core/ClapFlag.class.st
  src/Clap-Core/ClapMismatch.class.st
  src/Clap-Core/ClapParameter.class.st
  src/Clap-Core/ClapParameterized.class.st
  src/Clap-Core/ClapPluggableStdio.class.st
  src/Clap-Core/Symbol.extension.st
  src/Clap-Examples/ClapCommandLineExamples.class.st
  src/Clap-Tests/ClapCodeEvaluatorTest.class.st
  src/Clap-Tests/ClapCommandTest.class.st
  src/Clap-Tests/ClapContextTest.class.st
  src/Clap-Tests/ClapDocumentationTest.class.st
  src/Clap-Tests/ClapFlagTest.class.st
  src/Clap-Tests/ClapHelloTest.class.st
  src/Clap-Tests/ClapHelloWorldTest.class.st
  src/Clap-Tests/ClapMatchesTest.class.st
  src/Clap-Tests/ClapMeaningsTest.class.st
  src/Clap-Tests/ClapParameterTest.class.st
  src/Clap-Tests/ClapParameterizedTest.class.st
  src/Clap-Tests/ClapPharoCommandsTest.class.st
  src/Clap-Tests/ClapPharoVersionTest.class.st
  src/Clap-Tests/ClapPositionalTest.class.st
  src/Clap-Tests/ClapTestRunnerTest.class.st
Labels: Need more work

#5616 [feedback needed] attempt to improve class comment for RemoteString
  src/System-Sources/RemoteString.class.st
Labels: tests passed please review!

#5866 Adding a name cache to the Package organizer.
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: Large Images

#5931 Fix #5930: Write the error name and description in the body of the error too
  src/JenkinsTools-Core/HDTestReport.class.st
Labels: Easy, Misc

#5916 Remove ActiveHand and ActiveEvent
  src/Athens-Morphic/MenuMorph.extension.st
  src/BaselineOfDisplay/BaselineOfDisplay.class.st
  src/BaselineOfMorphicCore/BaselineOfMorphicCore.class.st
  src/Calypso-Browser/ClyBrowserToolMorph.class.st
  src/Commander-Activators-Mouse/CmdMouseCommandActivation.class.st
  src/EpiceaBrowsers/EpLogBrowserToolbarPresenter.class.st
  src/GT-Spotter-UI/GTSpotterContentsBrick.class.st
  src/GT-Spotter-UI/GTSpotterDropDownMorph.class.st
  src/GT-Spotter-UI/GTSpotterGlobalShortcut.class.st
  src/GT-Spotter-UI/GTSpotterHeaderBrick.class.st
  src/GT-Spotter-UI/GTSpotterMorph.class.st
  src/GT-Spotter-UI/GTSpotterPaneBrick.class.st
  src/Glamour-Morphic-Brick/GLMScrollPaneBrick.class.st
  src/Glamour-Morphic-Widgets/GLMPopper.class.st
  src/Glamour-Morphic-Widgets/GLMPrintPopper.class.st
  src/Glamour-Tests-Morphic/GLMPharoScriptMorphicTest.class.st
  src/Glamour-Tests-Morphic/GLMTextMorphicTest.class.st
  src/Glamour-Tests-Rubric/GLMRubricTextMorphicTest.class.st
  src/Graphics-Display Objects/Cursor.class.st
  src/Growl/GrowlMorph.class.st
  src/Morphic-Base/MenuMorph.class.st
  src/Morphic-Base/Object.extension.st
  src/Morphic-Base/Paragraph.class.st
  src/Morphic-Base/Rectangle.extension.st
  src/Morphic-Base/SelectionMorph.class.st
  src/Morphic-Base/TransferMorph.class.st
  src/Morphic-Base/WorldMorph.extension.st
  src/Morphic-Core/HandMorph.class.st
  src/Morphic-Core/Morph.class.st
  src/Morphic-Core/PasteUpMorph.class.st
  src/Morphic-Core/WorldMorph.class.st
  src/Morphic-Core/WorldState.class.st
  src/Morphic-Widgets-Pluggable/PluggableListMorph.class.st
  src/Morphic-Widgets-Tabs/TabBarMorph.class.st
  src/Morphic-Widgets-Windows/CollapsedMorph.class.st
  src/Morphic-Widgets-Windows/GroupWindowMorph.class.st
  src/Morphic-Widgets-Windows/ProportionalSplitterMorph.class.st
  src/Morphic-Widgets-Windows/SystemWindow.class.st
  src/NECompletion-Morphic/NECMenuMorph.class.st
  src/OSWindow-SDL2/OSSDL2WindowHandle.class.st
  src/OSWindow-VM/OSVMWindowHandle.class.st
  src/Polymorph-Widgets/Morph.extension.st
  src/Polymorph-Widgets/MorphicUIManager.class.st
  src/Rubric/RubAbstractTextArea.class.st
  src/Rubric/RubFloatingEditorBuilder.class.st
  src/Rubric/RubParagraph.class.st
  src/Rubric/RubTextEditor.class.st
  src/SUnit-Support-UITesting-Tests/SimulateKeystrokesTest.class.st
  src/SUnit-Support-UITesting/TestCase.extension.st
  src/Spec-MorphicAdapters/SpecTransferMorph.class.st
  src/Spec2-Adapters-Morphic/SpMorphicButtonAdapter.class.st
  src/Spec2-Adapters-Morphic/SpTransferMorph.class.st
  src/Spec2-Backend-Tests/SpMockMenu.class.st
  src/Text-Edition/StrikeFont.extension.st
  src/Text-Edition/TextEditor.class.st
Labels: Graphics

#5946 Add issue templates to the repository
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: more-information-needed

#5933 Fix and small enhance of ExternalAddress>>readArrayOf:until:
  src/UnifiedFFI-Tests/FFIExternalArrayTest.class.st
  src/UnifiedFFI/ExternalAddress.extension.st
Labels: more-information-needed

#5967 Fix #5947
  src/System-Settings-Core/PickOneSettingDeclaration.class.st
Labels: Bug, Graphics

#5964 Handle normal mouse events before artificial click
  src/Morphic-Base/MouseClickState.class.st
Labels: Bug, Graphics

#5979 Make Glamour Bricks implement morphic event interface
  src/Glamour-Morphic-Brick/GLMEmptyPopupBrick.class.st
  src/Glamour-Morphic-Brick/GLMPopupBrickListener.class.st
  src/Glamour-Morphic-Brick/GLMPopupBrickOutisideClickPredicate.class.st
  src/Glamour-Morphic-Brick/GLMPopupBrickPredicate.class.st
  src/Glamour-Morphic-Brick/GLMPopupBrickUnhoverPredicate.class.st
Labels: Bug, Graphics

#5984 Increase hiedra test time limit
  src/Hiedra-Tests/HiExamplesTest.class.st
Labels: Bug, Fleaky-test

#5982 Restore deferredUpdateMode in case of nested render loops
  src/Morphic-Core/VMWorldRenderer.class.st
Labels: Bug, Graphics

#5987 Remove extra templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/pharo-9-0-bug-report.md
Labels: more-information-needed

#5981 Menu morph should open on the active hand of the opening world
  src/Morphic-Base/MenuMorph.class.st
Labels: Bug, Graphics

#5863 windowMenuCleanup
  src/MenuRegistration/BlockMenuBuilder.class.st
  src/Morphic-Base/Form.extension.st
  src/Morphic-Base/MenuRegistration.extension.st
  src/Morphic-Core/Morph.class.st
  src/Morphic-Widgets-Windows/SystemWindow.class.st
Labels: Need more work

#5871 Loaded Fuel 3.0.2
  src/BaselineOfFuel/BaselineOfFuel.class.st
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/BaselineOfUI/BaselineOfUI.class.st
  src/Fuel-Core/ExternalAddress.extension.st
  src/Fuel-Core/FLDecoder.class.st
  src/Fuel-Core/FLEncoder.class.st
  src/Fuel-Core/FLExternalAddressCluster.class.st
  src/Fuel-Core/FLIndexStream.class.st
  src/Fuel-Core/FLLightGeneralMapper.class.st
  src/Fuel-Core/ManifestFuelCore.class.st
  src/Fuel-Core/ZnBufferedReadStream.extension.st
  src/Fuel-Core/ZnBufferedWriteStream.extension.st
  src/Fuel-Platform-Core/FLPlatform.class.st
  src/Fuel-Platform-Pharo-Core/ExternalAddress.extension.st
  src/Fuel-Platform-Pharo-Core/FLPharoPlatform.class.st
  src/Fuel-Tests-Core/FLBasicSerializationTest.class.st
  src/Fuel-Tests-Core/FLBinaryFileStreamBasicSerializationTest.class.st
  src/Fuel-Tests-Core/FLBinaryFileStreamSerializationTest.class.st
  src/Fuel-Tests-Core/FLBinaryFileStreamStrategy.class.st
  src/Fuel-Tests-Core/FLByteArrayBasicSerializationTest.class.st
  src/Fuel-Tests-Core/FLFileReferenceStreamBasicSerializationTest.class.st
  src/Fuel-Tests-Core/FLFileReferenceStreamStrategy.class.st
  src/Fuel-Tests-Core/FLFileStreamStrategy.class.st
  src/Fuel-Tests-Core/FLGZippedBasicSerializationTest.class.st
  src/Fuel-Tests-Core/FLHookedSubstitutionTest.class.st
  src/Fuel-Tests-Core/FLInMemoryBasicSerializationTest.class.st
  src/Fuel-Tests-Core/FLMultiByteStreamStrategy.class.st
  src/Fuel-Tests-Core/FLProcessBasicSerializationTest.class.st
  src/Fuel-Tests-Core/FLSerializationTest.class.st
  src/Fuel-Tests-Core/FLUserGuidesTest.class.st
  src/Fuel-Tools-Pharo/FLMaterializer.extension.st
  src/Fuel-Tools-Pharo/Object.extension.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: Need more work

#6013 [fix] separation between isTemp from the compiler/AST pov
  src/OpalCompiler-Core/OCASTClosureAnalyzer.class.st
  src/OpalCompiler-Core/RBVariableNode.extension.st
  src/Reflectivity/RFOperationReification.class.st
Labels: tests passed please review!

#6026 6002-Generate-accessors-on-inst-var-does-not-work
  src/SystemCommands-RefactoringSupport/SycRefactoringPreview.class.st
Labels: Need more work

#6018 Release test for proper tag casing
  src/ReleaseTests/ProperClassCategorizationTest.class.st
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
Labels: tests passed please review!

#6014 5991-In-place-edition-of-inspector-fails
  src/NECompletion/CompletionEngine.class.st
Labels: tests passed please review!

#6030 [easy][cleanup] removes a duplicated method
  src/OpalCompiler-Core/RBVariableNode.extension.st
Labels: tests passed please review!

#6039 Queue pending mouse events
  src/Morphic-Base/Form.extension.st
  src/Morphic-Base/MouseClickState.class.st
  src/Morphic-Core/HandMorph.class.st
Labels: Bug, Graphics

#6017 6012-Click-outside-of-completion-pop-up-should-close-it
  src/Morphic-Core/MorphClosePopups.class.st
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/Rubric/RubAbstractTextArea.class.st
Labels: tests passed please review!

#6051 ReflectivityExamples: do not do compileTemporaryMethods in #initialize
  src/Reflectivity-Tests/ReflectivityExamples.class.st
Labels: tests passed please review!

#6057 Fix minimal Pharo on Window
  src/System-Platforms-Tests/Win32WideStringTest.class.st
  src/System-Platforms/WinPlatform.class.st
Labels: tests passed please review!
