Repository pharo-project/pharo, pull requests merged in 2020-06, with the labels that each got.

#6461 6412-RBComment-should-have-parent-pointer-to-node
  src/AST-Core/RBComment.class.st
  src/AST-Core/RBParser.class.st
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
Labels: tests passed please review!

#6432 [fix] remove usage of reflectivity to get ast methods by default.
  bootstrap/scripts/03-metacello-bootstrap/01-loadMetacello.st
  bootstrap/scripts/4-build.sh
  src/AST-Core/ASTCache.class.st
  src/AST-Core/ASTCacheMissStrategy.class.st
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfMetacello/BaselineOfMetacello.class.st
  src/BaselineOfQA/BaselineOfQA.class.st
  src/BaselineOfReflectivity/BaselineOfReflectivity.class.st
  src/Reflectivity/RFReflectivityASTCacheStrategy.class.st
Labels: tests passed please review!

#6468 Fixes changes file flushing issue
  src/System-Sources/SourceFileBufferedReadWriteStream.class.st
Labels: tests passed please review!

#6427 6420-Backport-5482-to-Pharo8
  src/NECompletion/NECSpecialVariableEntry.class.st
  src/NECompletion/RBVariableNode.extension.st
Labels: tests passed please review!

#6304 Rules checking Tests should be in package SUnit-Rules
  src/ReleaseTests/ProperlyImplementedSUnitClassesTest.class.st
  src/SUnit-Rules-Tests/ReTestBasedTestCase.class.st
  src/SUnit-Rules-Tests/ReTestClassNameShouldEndWithTestTest.class.st
  src/SUnit-Rules-Tests/ReTestClassNameShouldNotEndWithTestsTest.class.st
  src/SUnit-Rules-Tests/ReTestClassNotInPackageWithTestEndingNameTest.class.st
  src/SUnit-Rules-Tests/package.st
  src/SUnit-Rules/ReAssertEqualSignIntoAssertEqualsRule.class.st
  src/SUnit-Rules/ReShouldSendSuperSetUpAsFirstMessage.class.st
  src/SUnit-Rules/ReShouldSendSuperTearDownAsLastMessage.class.st
  src/SUnit-Rules/ReShouldTransformedIntoAssertRule.class.st
  src/SUnit-Rules/ReTSUnitGroupedRule.trait.st
  src/SUnit-Rules/ReTestClassNameShouldEndWithTestRule.class.st
  src/SUnit-Rules/ReTestClassNameShouldNotEndWithTests.class.st
  src/SUnit-Rules/ReTestClassNotInPackageWithTestEndingNameRule.class.st
Labels: tests passed please review!

#6467 Fixes changes file flushing issue
  src/System-Sources/SourceFileBufferedReadWriteStream.class.st
Labels: tests passed please review!

#6483 simplify-firstPrecodeComment
  src/AST-Core/RBMethodNode.class.st
  src/Kernel/Behavior.class.st
  src/Kernel/CompiledCode.class.st
Labels: tests passed please review!

#6484 6415-RBMethodNode-should-have-allComments #6415
  src/AST-Core-Tests/RBProgramNodeTest.class.st
  src/AST-Core/RBProgramNode.class.st
Labels: tests passed please review!

#6455 Fix https://github.com/pharo-vcs/iceberg/issues/1331
  src/Calypso-SystemPlugins-Monticello-Browser/ClyCommitMCPackageCommand.class.st
Labels: tests passed please review!

#6477 emitStore-do-not-use-Object-new
  src/Slot-Core/GlobalVariable.class.st
  src/Slot-Core/LiteralVariable.class.st
  src/VariablesLibrary/ObservableSlot.class.st
  src/VariablesLibrary/WeakClassVariable.class.st
Labels: tests passed please review!

#6482 6049-It-should-not-be-possible-to-use-super-as-something-else-than-the-receiver-of-a-message
  src/GeneralRules-Tests/ReSuperWithoutSendTest.class.st
  src/GeneralRules/ReSuperWithoutSend.class.st
Labels: tests passed please review!

#6486 deprecate-parseCompiledMethod
  src/AST-Core/RBParser.class.st
  src/Deprecated90/RBParser.extension.st
Labels: tests passed please review!

#6485 RPackage-AllUnsentMessages-Shouldbe-Set
  src/RPackage-Tests/RPackageTest.class.st
  src/System-Support/RPackage.extension.st
Labels: tests passed please review!

#6488 6487-RBMethodNode-primitiveSources-is-strange
  src/AST-Core/RBMethodNode.class.st
  src/Deprecated90/RBMethodNode.extension.st
Labels: tests passed please review!

#6492 Created a simple and a complex test for the changes file flushing issue
  src/Tests/SourceFileBufferedReadWriteStreamTest.class.st
Labels: tests passed please review!

#6478 pushOuterVectors-use-tempVectorVarNames
  src/OpalCompiler-Core/IRTranslator.class.st
  src/OpalCompiler-Core/RBPragmaNode.extension.st
Labels: tests passed please review!

#6429 6418-Backport-5643-into-Pharo8
  src/Kernel-Tests-Extended/ClassTest.class.st
  src/Kernel/Class.class.st
  src/Kernel/UndefinedObject.class.st
Labels: tests passed please review!

#6494 Use iceberg 1.8.2
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: tests passed please review!

#6497 [Disable Flaky Tests] Disable two Zinc flaky tests
  src/Zinc-Tests/ZnEasyTest.class.st
  src/Zinc-Tests/ZnImageExampleDelegateTest.class.st
Labels: tests passed please review!

#6522 Unify Slots and LiteralVariable in single hierarchy
  src/Calypso-SystemQueries/ClyClassBindings.class.st
  src/Calypso-SystemQueries/LiteralVariable.extension.st
  src/Debugging-Core/SymbolicBytecodeBuilder.class.st
  src/OpalCompiler-Core/IRBytecodeGenerator.class.st
  src/Slot-Core/LiteralVariable.class.st
  src/Slot-Core/Slot.class.st
  src/Slot-Core/TemporaryVariable.class.st
  src/Slot-Core/Variable.class.st
  src/Slot-Tests/LiteralVariableTest.class.st
Labels: tests passed please review!

#6547 6125-Fleaky-NECompletion-test
  src/NECompletion-Tests/CompletionContextTest.class.st
Labels: tests passed please review!

#6550 remove-necompletion-morphic-dependency
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/HeuristicCompletion-Model/CoCompletionContext.class.st
  src/NECompletion-Preferences/NECPreferences.class.st
  src/NECompletion-Preferences/package.st
  src/NECompletion/ManifestNECompletion.class.st
  src/NECompletion/NECEntry.class.st
Labels: tests passed please review!

#6546 add-Slot-and-Variable-tooDangerousClasses
  src/Shift-ClassBuilder/DangerousClassNotifier.class.st
Labels: tests passed please review!

#6554 dumpTallyOnTranscript sends missing message #processBrowser
  src/Tool-ProcessBrowser/CPUWatcher.class.st
Labels: tests passed please review!

#6552 Move-Layouts-to-Kernel
  src/Kernel/AbstractLayout.class.st
  src/Kernel/BitsLayout.class.st
  src/Kernel/ByteLayout.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/CompiledMethodLayout.class.st
  src/Kernel/Context.class.st
  src/Kernel/DoubleByteLayout.class.st
  src/Kernel/DoubleWordLayout.class.st
  src/Kernel/EmptyLayout.class.st
  src/Kernel/EphemeronLayout.class.st
  src/Kernel/FixedLayout.class.st
  src/Kernel/ImmediateLayout.class.st
  src/Kernel/LayoutAbstractScope.class.st
  src/Kernel/LayoutClassScope.class.st
  src/Kernel/LayoutEmptyScope.class.st
  src/Kernel/ObjectLayout.class.st
  src/Kernel/PointerLayout.class.st
  src/Kernel/VariableLayout.class.st
  src/Kernel/WeakLayout.class.st
  src/Kernel/WordLayout.class.st
  src/Slot-Core/ClassDescription.extension.st
  src/Slot-Core/Context.extension.st
Labels: tests passed please review!

#6565 skip-testNodeForBCOffsetTest-on32bit
  src/OpalCompiler-Tests/OCBytecodeToASTCacheTest.class.st
Labels: tests passed please review!

#6563 Extract TextDiffBuilderTest into Text-Diff-Tests (second PR)
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/Text-Diff-Tests/TextDiffBuilderTest.class.st
  src/Text-Diff-Tests/package.st
Labels: tests passed please review!

#6569 Variable breakpoint: added API in object
  src/Reflectivity-VariableBreakpoint/Object.extension.st
  src/Reflectivity-VariableBreakpoint/VariableBreakpointTest.class.st
Labels: tests passed please review!

#6576 add-convenience-method-to-FFILibraryFinder
  src/UnifiedFFI/FFILibraryFinder.class.st
Labels: tests passed please review!

#6578 fix known paths for linux 64bit
  src/UnifiedFFI/FFILibraryFinder.class.st
  src/UnifiedFFI/FFIMacLibraryFinder.class.st
  src/UnifiedFFI/FFIUnix64LibraryFinder.class.st
  src/UnifiedFFI/FFIWindowsLibraryFinder.class.st
Labels: tests passed please review!

#6562 Move #isLinux to platform classes
  src/System-Platforms/OSPlatform.class.st
  src/System-Platforms/UnixPlatform.class.st
  src/Tests/OSPlatformTest.class.st
  src/Tool-SystemReporter/SystemReporter.class.st
Labels: tests passed please review!

#6573 Cleanup duplicated metalinks (reflectivity) protocol in variables
  src/Calypso-SystemQueries/ClyCompositeScope.extension.st
  src/Kernel/Slot.class.st
  src/Kernel/TemporaryVariable.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Tools/LiteralVariable.extension.st
  src/OpalCompiler-Tools/Variable.extension.st
  src/Reflectivity/ClassVariable.extension.st
  src/Reflectivity/GlobalVariable.extension.st
  src/Reflectivity/LiteralVariable.extension.st
  src/Reflectivity/TemporaryVariable.extension.st
  src/Reflectivity/Variable.extension.st
Labels: tests passed please review!

#6493 Calypso: Class Tree Pane Should Be Collapsible
  src/Calypso-Browser/ClyQueryViewMorph.class.st
  src/Calypso-NavigationModel/ClyNavigationEnvironment.class.st
  src/Calypso-SystemQueries/ClyLocalClassScope.class.st
  src/Calypso-SystemQueries/ClyMethodGroup.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowser.class.st
Labels: tests passed please review!

#6539 2873-Critiques---Temporaries-read-before-written-versus-nil-checking-messages
  src/AST-Core/RBReadBeforeWrittenTester.class.st
Labels: tests passed please review!

#6582 Introduce-isValidSelector
  src/AST-Core/RBLiteralToken.class.st
  src/AST-Core/RBLiteralValueNode.class.st
  src/AST-Core/RBScanner.class.st
  src/AST-Core/String.extension.st
  src/Collections-Tests/StringTest.class.st
  src/Refactoring-Core/RBCondition.class.st
  src/Refactoring-Core/RBMethod.class.st
  src/Refactoring-Core/RBMethodName.class.st
  src/Refactoring2-Transformations/RBExtractMethodTransformation.class.st
Labels: tests passed please review!

#6584 Move Workspace tests in own tool test package
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/Tool-Workspace-Tests/WorkspaceTest.class.st
  src/Tool-Workspace-Tests/package.st
Labels: tests passed please review!

#6536 6503-senders-of-copyAt-smells-like-dead-code
  src/Tool-FileList/FileList.class.st
Labels: tests passed please review!

#6548 CompiledMethod-hasComment
  src/AST-Core-Tests/RBMethodNodeTest.class.st
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel/CompiledMethod.class.st
  src/System-Changes/ChangeSet.class.st
Labels: tests passed please review!

#6605 Introduce a Tool-Profilers-Tests package
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/Tool-Profilers-Tests/AndreasSystemProfilerTest.class.st
  src/Tool-Profilers-Tests/MessageTallyTest.class.st
  src/Tool-Profilers-Tests/SpaceTallyTest.class.st
  src/Tool-Profilers-Tests/package.st
Labels: tests passed please review!

#6607 RBRenameClassTransformationTest-defaultTimeLimit
  src/Refactoring2-Transformations-Tests/RBRenameClassTransformationTest.class.st
Labels: tests passed please review!

#6537 CompiledMethod-comments-simpler
  src/AST-Core/CompiledMethod.extension.st
Labels: easyReview, tests passed please review!

#6626 6046-Fleaky-RBBrowserEnvironmentTest-test
  src/Refactoring-Tests-Environment/RBBrowserEnvironmentTest.class.st
Labels: easyReview, tests passed please review!

#6627 Deprecate SmalltalkEditingState
  src/Deprecated90/SmalltalkEditingState.class.st
Labels: tests passed please review!

#6602 #copyFrom: in ClassOrganization should not be extension method
  src/Kernel/ClassOrganization.class.st
  src/Shift-ClassBuilder/ClassOrganization.extension.st
Labels: easyReview, tests passed please review!

#6579 Deprecate-firstPrecodeCommentFor
  src/Deprecated90/Behavior.extension.st
  src/Kernel/Behavior.class.st
Labels: tests passed please review!

#6636 6634-testNoUnusedTemporaryVariablesLeft-is-failing-in-Pharo9
  src/NECompletion-Morphic/CompletionEngine.class.st
Labels: easyReview, tests passed please review!

#6628 Load iceberg 1.8.3
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: tests passed please review!

#6551 6506-Behavior--methodsInProtocol-invokes-subclass-only-defined-method
  src/Ring-Definitions-Core/Behavior.extension.st
  src/Ring-Definitions-Core/ClassDescription.extension.st
  src/Ring-Definitions-Core/RGBehaviorDefinition.class.st
  src/Ring-Definitions-Core/RGClassDescriptionDefinition.class.st
Labels: easyReview, tests passed please review!

#6638 Use Variable's directly instead of OCVariable wrappers
  src/Calypso-Ring/RGMethod.extension.st
  src/Calypso-Ring/RGSlot.extension.st
  src/Calypso-SystemTools-Core/LiteralVariable.extension.st
  src/Calypso-SystemTools-Core/Slot.extension.st
  src/Calypso-SystemTools-Core/UndeclaredVariable.extension.st
  src/ClassParser-Tests/CDExistingClassDefinitionTest.class.st
  src/ClassParser/CDClassNameNode.class.st
  src/Hermes/HEGlobalVariable.class.st
  src/Kernel/LiteralVariable.class.st
  src/Kernel/Slot.class.st
  src/Kernel/UndeclaredVariable.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/LiteralVariable.extension.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCAbstractLocalVariable.class.st
  src/OpalCompiler-Core/OCAbstractVariable.class.st
  src/OpalCompiler-Core/OCClassScope.class.st
  src/OpalCompiler-Core/OCEnvironmentScope.class.st
  src/OpalCompiler-Core/OCExtraBindingScope.class.st
  src/OpalCompiler-Core/OCInstanceScope.class.st
  src/OpalCompiler-Core/OCLiteralVariable.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
  src/OpalCompiler-Core/OCSlotVariable.class.st
  src/OpalCompiler-Core/OCUndeclaredVariable.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
  src/OpalCompiler-Core/Slot.extension.st
  src/OpalCompiler-Core/UndeclaredVariable.extension.st
  src/OpalCompiler-Core/Variable.extension.st
  src/OpalCompiler-Tests/OCCompiledMethodIntegrityTest.class.st
  src/OpalCompiler-Tests/OCEnvironmentScopeTest.class.st
  src/Reflectivity/RFIndexReification.class.st
  src/Reflectivity/RFOperationReification.class.st
  src/Ring-Core/RGClassVariable.class.st
  src/Ring-Core/RGSlot.class.st
  src/Ring-Core/RGVariable.class.st
Labels: tests passed please review!

#6538 scanTokens-can-call-scanTokensObjects
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBScanner.class.st
  src/Refactoring2-Transformations/RBParser.extension.st
Labels: tests passed please review!

#6606 DeprecatedSlot-fixEmptyMessage
  src/VariablesLibrary/SlotDeprecation.class.st
Labels: tests passed please review!

#6656 Revert "6595-SpDemoTest-should-close-the-open-windows"
  src/Spec2-Tests/SpTest.class.st
Labels: easyReview

#6640 Object centric halt on call breakpoint
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnAccessCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnReadCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVarAccessCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVarReadsCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVarWritesCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnWriteCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/SycVariableAccessBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/SycVariableReadBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/SycVariableWriteBreakpointCommand.class.st
  src/Reflectivity-Tools-Tests/BreakpointTest.class.st
  src/Reflectivity-VariableBreakpoint/VariableBreakpoint.class.st
  src/Reflectivity-VariableBreakpoint/VariableBreakpointTest.class.st
  src/Reflectivity/Breakpoint.class.st
  src/Reflectivity/Object.extension.st
Labels: tests passed please review!

#6652 Compiler-Scopes-remove-children
  src/OpalCompiler-Core/OCAbstractScope.class.st
  src/OpalCompiler-Tools/GTOpalScopeBrowser.class.st
  src/OpalCompiler-Tools/RBProgramNode.extension.st
Labels: tests passed please review!

#6647 Introduce #readFromContext: for all variables
  src/Debugging-Core/Context.extension.st
  src/Deprecated90/DebuggerMethodMapOpal.extension.st
  src/HeuristicCompletion-Model/CoVariableValueMessageHeuristic.class.st
  src/Kernel-Tests-WithCompiler/ContextTest.extension.st
  src/Kernel/LiteralVariable.class.st
  src/Kernel/Slot.class.st
  src/Kernel/TemporaryVariable.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/OCSelfVariable.class.st
  src/OpalCompiler-Core/OCSpecialVariable.class.st
  src/OpalCompiler-Core/OCSuperVariable.class.st
  src/OpalCompiler-Core/OCTempVariable.class.st
  src/OpalCompiler-Core/OCThisContextVariable.class.st
  src/Reflectivity/RFTempWrite.class.st
  src/Slot-Tests/ClassVariableTest.class.st
  src/Slot-Tests/SlotTest.class.st
Labels: Need more work

#6642 TemporaryVariable-Cleanup-saveTemp
  src/Kernel/TemporaryVariable.class.st
  src/Slot-Core/CompiledBlock.extension.st
  src/Slot-Core/CompiledMethod.extension.st
  src/Slot-Tests/TemporaryVariableTest.class.st
Labels: tests passed please review!

#6661 fix-6504: slotNames is defined in ClassDescription but invoked from Behavior
  src/Kernel/Behavior.class.st
  src/Kernel/Class.class.st
  src/Kernel/ClassDescription.class.st
  src/Slot-Core/Behavior.extension.st
Labels: tests passed please review!

#6662 CleanupIsPseudoVariable
  src/Kernel/Slot.class.st
  src/Slot-Core/Symbol.extension.st
Labels: easyReview, tests passed please review!

#6658 PoolVariable-merge-in-ClassVariable
  src/Kernel/ClassVariable.class.st
  src/Kernel/PoolVariable.class.st
Labels: tests passed please review!

#6665 Introduce Collections-Atomic-Tests
  src/BaselineOfKernelTests/BaselineOfKernelTests.class.st
  src/Collections-Atomic-Tests/FIFOQueueTest.class.st
  src/Collections-Atomic-Tests/LIFOQueueTest.class.st
  src/Collections-Atomic-Tests/WaitfreeQueueTest.class.st
  src/Collections-Atomic-Tests/package.st
Labels: tests passed please review!

#6668 Cleanup Debugger-Filters package
  src/Debugger-Filters/BlockFilter.class.st
  src/Debugger-Filters/BooleanFilter.class.st
  src/Debugger-Filters/KernelClassesFilter.class.st
  src/Debugger-Filters/ManifestDebuggerFilters.class.st
  src/Debugger-Filters/SelectorFilter.class.st
  src/Debugger-Filters/StackFilter.class.st
Labels: tests passed please review!

#6671 ReservedVariable-usingMethods-isReferenced
  src/Kernel/Slot.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/ReservedVariable.class.st
Labels: tests passed please review!

#6632 use-OCBytecodeToASTCache-instead-of-fullBlockInstructionForPC
  src/AST-Core/RBBlockNode.class.st
  src/OpalCompiler-Core/IRMethod.class.st
  src/OpalCompiler-Core/OCBytecodeToASTCache.class.st
  src/OpalCompiler-Core/RBBlockNode.extension.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/OpalCompiler-Tests/MethodMapExamples.class.st
  src/OpalCompiler-Tests/OCBytecodeToASTCacheTest.class.st
Labels: tests passed please review!

#6673 Object centric installer reflective view on objects
  src/Reflectivity-Tests/LinkInstallerTest.class.st
  src/Reflectivity-Tests/MetaLinkAnonymousClassBuilder.extension.st
  src/Reflectivity-Tests/MetaLinkAnonymousClassBuilderTest.class.st
  src/Reflectivity/MetaLinkAnonymousClassBuilder.class.st
  src/Reflectivity/MetaLinkInstaller.class.st
  src/Reflectivity/MetaLinkRegistry.class.st
Labels: tests passed please review!

#6676 Introduce Collections-Stack-Tests
  src/BaselineOfKernelTests/BaselineOfKernelTests.class.st
  src/Collections-Stack-Tests/StackTest.class.st
  src/Collections-Stack-Tests/package.st
Labels: tests passed please review!

#6669 6532-Incomplete-state-of-method-AST
  src/AST-Core/CompiledMethod.extension.st
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/Reflectivity/ReflectiveMethod.class.st
Labels: tests passed please review!

#6328 Refactor monstrous Process>>#terminate method
  src/Kernel/Context.class.st
  src/Kernel/Process.class.st
Labels: tests passed please review!

#6633 6544-ReImplementedNotSentRule-has-false-positives
  src/Calypso-SystemPlugins-Critic-Queries-Tests/ClyClassWithProblemMethods.class.st
  src/GeneralRules/ReImplementedNotSentRule.class.st
Labels: tests passed please review!

#6683 StackTest: Accessors should be in accessing
  src/Collections-Stack-Tests/StackTest.class.st
Labels: tests passed please review!

#6686 6549-Better-comment-for-WordArray-and-friends
  src/Collections-Native/ByteArray.class.st
  src/Collections-Native/DoubleByteArray.class.st
  src/Collections-Native/DoubleWordArray.class.st
  src/Collections-Native/FloatArray.class.st
  src/Collections-Native/IntegerArray.class.st
  src/Collections-Native/WordArray.class.st
Labels: tests passed please review!

#6685 ByteArray asWideString should be in conversion
  src/Collections-Native/ByteArray.class.st
Labels: tests passed please review!

#6701 6520-Progress-bar-should-not-happen-below-the-toolbar
  src/Morphic-Base/Form.extension.st
  src/Morphic-Base/SystemProgressMorph.class.st
Labels: tests passed please review!

#6694 Symbol>>#asIcon should be in Deprecated90
  src/Deprecated90/Symbol.extension.st
Labels: tests passed please review!

#6703 ReImplementedNotSentRule-Disable
  src/Renraku/ReRuleManager.class.st
Labels: tests passed please review!

#6689 Lint cleanup Collections-Abstract-Traits
  src/Collections-Abstract-Traits/ManifestCollectionsAbstractTraits.class.st
  src/Collections-Abstract-Traits/TSortable.trait.st
  src/Ring-Definitions-Tests-Monticello/RGTraitDefinitionTest.extension.st
Labels: tests passed please review!

#6706 TemporaryVariable-cleanup
  src/Deprecated90/OCAbstractLocalVariable.class.st
  src/OpalCompiler-Core/OCAbstractLocalVariableTOMERGE.class.st
  src/OpalCompiler-Core/OCTempVariable.class.st
Labels: tests passed please review!

#6717 Better setUp tab in the browser
  src/Calypso-SystemPlugins-SUnit-Browser/ClyTestSetUpEditorTool.class.st
Labels: tests passed please review!

#6716 Fix updating tabs in Calypso broken by new notebook widget
  src/Calypso-Browser/ClyNotebookManager.class.st
  src/Calypso-Browser/ClyNotebookMorph.class.st
  src/Morphic-Widgets-PolyTabs/TabGroupMorph.class.st
  src/Morphic-Widgets-PolyTabs/TabSelectorMorph.class.st
  src/Spec2-Adapters-Morphic/SpNotebookMorph.class.st
  src/Spec2-Adapters-Morphic/SpNotebookTabSelectorMorph.class.st
  src/Spec2-Backend-Tests/SpNotebookAdapterTest.class.st
Labels: tests passed please review!

#6718 Use-globals-for-OCEnvironmentScope
  src/Deprecated90/OCEnvironmentScope.class.st
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Tests/OCEnvironmentScopeTest.class.st
  src/Slot-Core/Dictionary.extension.st
Labels: tests passed please review!

#6735 Dictionary-no-hasTempVector
  src/OpalCompiler-Core/IRTranslator.class.st
  src/Slot-Core/Dictionary.extension.st
Labels: tests passed please review!

#6734 ScopeLevel-only-MethodScope
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCAbstractScope.class.st
  src/OpalCompiler-Core/OCInstanceScope.class.st
Labels: tests passed please review!

#6726 Introduce Collections-Unordered-Tests and tag SortedCollectionTest correctly
  src/BaselineOfKernelTests/BaselineOfKernelTests.class.st
  src/Collections-Tests/SortedCollectionTest.class.st
  src/Collections-Unordered-Tests/BagTest.class.st
  src/Collections-Unordered-Tests/DictionaryTest.class.st
  src/Collections-Unordered-Tests/HashTableSizesTest.class.st
  src/Collections-Unordered-Tests/IdentityBagTest.class.st
  src/Collections-Unordered-Tests/IdentityDictionaryTest.class.st
  src/Collections-Unordered-Tests/IdentitySetTest.class.st
  src/Collections-Unordered-Tests/KeyedTreeTest.class.st
  src/Collections-Unordered-Tests/MethodDictionaryTest.class.st
  src/Collections-Unordered-Tests/NestedDictionaryTest.class.st
  src/Collections-Unordered-Tests/PluggableDictionaryTest.class.st
  src/Collections-Unordered-Tests/PluggableSetTest.class.st
  src/Collections-Unordered-Tests/SetTest.class.st
  src/Collections-Unordered-Tests/SmallDictionaryTest.class.st
  src/Collections-Unordered-Tests/SmallIdentityDictionaryTest.class.st
  src/Collections-Unordered-Tests/TDictionaryAddingTest.trait.st
  src/Collections-Unordered-Tests/TDictionaryAssociationAccessTest.trait.st
  src/Collections-Unordered-Tests/TDictionaryComparingTest.trait.st
  src/Collections-Unordered-Tests/TDictionaryCopyingTest.trait.st
  src/Collections-Unordered-Tests/TDictionaryEnumeratingTest.trait.st
  src/Collections-Unordered-Tests/TDictionaryImplementationTest.trait.st
  src/Collections-Unordered-Tests/TDictionaryIncludesTest.trait.st
  src/Collections-Unordered-Tests/TDictionaryIncludesWithIdentityCheckTest.trait.st
  src/Collections-Unordered-Tests/TDictionaryKeyAccessTest.trait.st
  src/Collections-Unordered-Tests/TDictionaryKeysValuesAssociationsAccess.trait.st
  src/Collections-Unordered-Tests/TDictionaryPrintingTest.trait.st
  src/Collections-Unordered-Tests/TDictionaryRemovingTest.trait.st
  src/Collections-Unordered-Tests/TDictionaryValueAccessTest.trait.st
  src/Collections-Unordered-Tests/package.st
Labels: tests passed please review!

#6730 Allow-Compiling-Syntax-Errors-NonInteractively
  src/AST-Core/RBParseErrorNode.class.st
  src/Kernel/RuntimeSyntaxError.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/MethodPragmaTest.class.st
  src/OpalCompiler-Tests/OCCompileWithFailureTest.class.st
Labels: tests passed please review!

#6740 LiteralVariable-methodNode-remove
  src/Reflectivity/LiteralVariable.extension.st
Labels: tests passed please review!

#6738 Change superclass of OCTempVariable
  src/OpalCompiler-Core/OCTempVariable.class.st
Labels: tests passed please review!

#6457 6431-Remove-BlueInk-from-P9
  src/AST-Core-Tests/RBMethodNodeTest.class.st
  src/AST-Core-Tests/RBProgramNodeTest.class.st
  src/AST-Core/RBArrayNode.class.st
  src/AST-Core/RBBlockNode.class.st
  src/AST-Core/RBMethodNode.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBSequenceNode.class.st
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/EnlumineurFormatter-Tests/RBMethodNodeTest.extension.st
  src/EnlumineurFormatter-Tests/RBProgramNodeTest.extension.st
  src/EnlumineurFormatter/EFContext.class.st
  src/EnlumineurFormatter/EFFormatter.class.st
  src/EnlumineurFormatter/RBArrayNode.extension.st
  src/EnlumineurFormatter/RBBlockNode.extension.st
  src/EnlumineurFormatter/RBMethodNode.extension.st
  src/EnlumineurFormatter/RBProgramNode.extension.st
  src/EnlumineurFormatter/RBSequenceNode.extension.st
  src/Formatter-Settings/RBProgramNode.extension.st
Labels: tests passed please review!

#6743 ReMethodHasSyntaxErrorRule
  src/GeneralRules/ReMethodHasSyntaxErrorRule.class.st
Labels: tests passed please review!
