Repository pharo-project/pharo, pull requests merged in 2020-05, with the labels that each got.

#6270 tinyCleanupTextTest
  src/Metacello-Core/MetacelloVersionValidator.class.st
  src/Text-Tests/TextTest.class.st
Labels: tests passed please review!

#6255 remove OCKeyedSet
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCBlockScope.class.st
  src/OpalCompiler-Core/OCKeyedSet.class.st
Labels: tests passed please review!

#6289 Move deprecated HistoryCollection to Deprecated90 package
  src/Deprecated90/HistoryCollection.class.st
Labels: tests passed please review!

#6298 CoTypeInferencerLogging
  src/HeuristicCompletion-Model/CoTypeInferencer.class.st
Labels: tests passed please review!

#6142 do-not-generate-initialize-method-for-slots-if-it-already-call-super
  src/Slot-Core/Slot.class.st
  src/Slot-Tests/SlotClassVariableTest.class.st
Labels: tests passed please review!

#6300 remove-RBRuleIfNotEmptyDo
  src/GeneralRules/ReIfNotEmptyDoRule.class.st
Labels: tests passed please review!

#6314 optionalFindThePig
  src/Debugging-Settings/DebugSystemSettings.class.st
  src/Tool-ProcessBrowser/CPUWatcher.class.st
Labels: tests passed please review!

#6198 IRBuilder-fill-TempOffsets
  src/OpalCompiler-Core/IRBuilder.class.st
  src/OpalCompiler-Core/IRMethod.class.st
  src/OpalCompiler-Core/IRPushClosureCopy.class.st
  src/OpalCompiler-Core/IRSequence.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCClassScope.class.st
  src/OpalCompiler-Core/OCCopyingTempVariable.class.st
  src/OpalCompiler-Core/OCEnvironmentScope.class.st
  src/OpalCompiler-Core/OCTempVariable.class.st
  src/OpalCompiler-Core/OCVectorTempVariable.class.st
  src/Reflectivity/RFASTTranslator.class.st
Labels: tests passed please review!

#6305 fix-keyUp-keyDown-eventHandler
  src/Morphic-Core/Morph.class.st
  src/Morphic-Tests/MorphicEventHandlerTest.class.st
Labels: tests passed please review!

#6348 DeprecateObject-notify-at
  src/Deprecated90/Object.extension.st
  src/Kernel/Object.class.st
Labels: tests passed please review!

#6352 6351-SyntaxErrorDebugger-messes-up-display-state-when-closed
  src/Tools/SyntaxErrorDebugger.class.st
Labels: tests passed please review!

#6345 toolsMenu
  src/Morphic-Base/WorldState.extension.st
  src/Tool-ProcessBrowser/ProcessBrowser.class.st
  src/Tool-Profilers/TimeProfiler.class.st
Labels: tests passed please review!

#6347 Compiler: #notify:at: Cleanup
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OCReadOnlyVMWarning.class.st
  src/OpalCompiler-Core/OCSemanticError.class.st
  src/OpalCompiler-Core/OCSemanticWarning.class.st
Labels: tests passed please review!

#6357 SyntaxErrorDebuggerDepentsClean
  src/Tools/SyntaxErrorDebugger.class.st
Labels: tests passed please review!

#6358 FixCompilerSettings
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#6354 Variable breakpoints: break on variable (inst/temps/args) accesses (read/write/both)
  src/BaselineOfReflectivity/BaselineOfReflectivity.class.st
  src/BaselineOfUnifiedFFI/BaselineOfUnifiedFFI.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnAccessCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnReadCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVarAccessCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVarReadsCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVarWritesCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVariableCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnWriteCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyVariableBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/SycVariableAccessBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/SycVariableBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/SycVariableReadBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/SycVariableWriteBreakpointCommand.class.st
  src/Reflectivity-Tests/LinkInstallerTest.class.st
  src/Reflectivity-Tools-Tests/BreakpointObserverTest.class.st
  src/Reflectivity-Tools-Tests/BreakpointTest.class.st
  src/Reflectivity-Tools-Tests/DummyBreakpointObserver.class.st
  src/Reflectivity-VariableBreakpoint/Breakpoint.extension.st
  src/Reflectivity-VariableBreakpoint/Class.extension.st
  src/Reflectivity-VariableBreakpoint/CompiledMethod.extension.st
  src/Reflectivity-VariableBreakpoint/RBAssignmentNode.extension.st
  src/Reflectivity-VariableBreakpoint/RBInstanceVariableNode.extension.st
  src/Reflectivity-VariableBreakpoint/RBProgramNode.extension.st
  src/Reflectivity-VariableBreakpoint/RBVariableNode.extension.st
  src/Reflectivity-VariableBreakpoint/VariableBreakpoint.class.st
  src/Reflectivity-VariableBreakpoint/VariableBreakpointMockClass.class.st
  src/Reflectivity-VariableBreakpoint/VariableBreakpointMockSubclass.class.st
  src/Reflectivity-VariableBreakpoint/VariableBreakpointTest.class.st
  src/Reflectivity-VariableBreakpoint/package.st
  src/Reflectivity/Break.class.st
  src/Reflectivity/Breakpoint.class.st
  src/Reflectivity/BreakpointActivationNotification.class.st
  src/Reflectivity/BreakpointAddedNotification.class.st
  src/Reflectivity/BreakpointHitNotification.class.st
  src/Reflectivity/BreakpointNotification.class.st
  src/Reflectivity/BreakpointRemovedNotification.class.st
  src/Reflectivity/MetaLinkRegistry.class.st
  src/Reflectivity/MetalinkTargetResolver.class.st
Labels: Need more work

#6370 Removing slice and issue support
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/IssueTracking-Tests/ManifestIssueTrackingTests.class.st
  src/IssueTracking-Tests/PharoIssueTest.class.st
  src/IssueTracking-Tests/package.st
  src/IssueTracking/ManifestIssueTracking.class.st
  src/IssueTracking/NullPharoIssue.class.st
  src/IssueTracking/PharoIssue.class.st
  src/IssueTracking/package.st
  src/MonticelloGUI/MCSliceInfo.class.st
  src/MonticelloGUI/MCSliceMaker.class.st
  src/MonticelloGUI/MCWorkingCopyBrowser.class.st
Labels: tests passed please review!

#6336 SimplifyOCASTTranslater-by-tempVarNamesWithoutArguments
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/Reflectivity/RFASTTranslator.class.st
Labels: tests passed please review!

#6371 CleanupOCKeyedSet2
  src/OpalCompiler-Core/OCKeyedSet.class.st
  src/OpalCompiler-Core/OCSelfVariable.class.st
  src/OpalCompiler-Core/OCSpecialVariable.class.st
  src/OpalCompiler-Core/OCSuperVariable.class.st
Labels: tests passed please review!

#6372 Improve Compiler Overlay
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#6359 asDoitShouldStoreFormattedSource
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/OpalCompiler-Core/RBProgramNode.extension.st
Labels: tests passed please review!

#6401 RequestorScopeHardenNonStringVarname
  src/OpalCompiler-Core/OCRequestorScope.class.st
Labels: tests passed please review!

#6395 6278-RBProgramNodeparents-is-messy
  src/AST-Core-Tests/RBMethodNodeTest.class.st
  src/AST-Core-Tests/RBProgramNodeTest.class.st
  src/AST-Core/RBProgramNode.class.st
  src/GT-InspectorExtensions-Core/RBProgramNode.extension.st
  src/GT-SpotterExtensions-Core/RBProgramNode.extension.st
Labels: tests passed please review!

#6447 Fixing #5451
  src/AST-Core/RBScanner.class.st
Labels: more-information-needed

#6451 Fixing #6379
  src/Kernel/ClassDescription.class.st
Labels: more-information-needed

#6446 4002-Temporaries-read-before-written-Rule--potentially-Add-explanation
  src/GeneralRules/ReTempsReadBeforeWrittenRule.class.st
Labels: tests passed please review!

#6416 6320-RBExtraBlockRule-does-not-check-for-cull--co
  src/GeneralRules/ReExtraBlockRule.class.st
Labels: tests passed please review!
