Repository pharo-project/pharo, pull requests merged in 2020-10, with the labels that each got.

#7406 7405-Debug-It-is-broken
  src/Monticello-Tests/MCStWriterTest.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#7407 7365-DictionaryValueHold-removeKey-calls-a-non-existing-method
  src/NewValueHolder-Core/DictionaryValueHolder.class.st
Labels: tests passed please review!

#7403 Name Analysis: Lookup Slots In Class
  src/Kernel/Class.class.st
  src/Kernel/LayoutClassScope.class.st
  src/Kernel/LayoutEmptyScope.class.st
  src/Kernel/PointerLayout.class.st
  src/Kernel/Slot.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/Behavior.extension.st
  src/OpalCompiler-Core/OCInstanceScope.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
  src/OpalCompiler-Core/ReservedVariable.class.st
  src/Ring-Core/RGBehavior.class.st
  src/Ring-Core/RGLayout.class.st
  src/Ring-Core/RGPointerLayout.class.st
Labels: tests passed please review!

#7402 reduce-sends-doSemanticAnalysis
  src/HeuristicCompletion-Model/CoASTResultSetBuilder.class.st
  src/HeuristicCompletion-Model/CoGlobalSorterResultSetBuilder.class.st
  src/OpalCompiler-Tests/OCASTCheckerTest.class.st
  src/OpalCompiler-Tests/OCASTClosureAnalyzerTest.class.st
Labels: tests passed please review!

#7393 Enable-ReadOnly-Literals
  src/OpalCompiler-Core/CompilationContext.class.st
Labels: tests passed please review!

#7424 7364-RBSelectorNode-has-unclassified-methods
  src/AST-Core/RBSelectorNode.class.st
Labels: easyReview, tests passed please review!

#7427 Fixed #7420. Added transformation rules to some non-transforming deprecations that were identified as automatable in the Deprewriter paper
  src/Glamour-Rubric-Presentations/GLMCompositePresentation.extension.st
  src/Metacello-Core/MetacelloGenericProjectSpec.class.st
  src/Metacello-Core/MetacelloMethodSection.class.st
  src/Metacello-Core/MetacelloPlatform.class.st
  src/Metacello-MC/MetacelloAbstractPackageSpec.extension.st
  src/Metacello-MC/MetacelloPackageSpec.class.st
  src/Metacello-ToolBox/MetacelloToolBox.class.st
  src/UnifiedFFI-Legacy/Object.extension.st
  src/UnifiedFFI/ExternalAddress.extension.st
  src/UnifiedFFI/FFIExternalReference.class.st
  src/UnifiedFFI/FFIStructure.class.st
Labels: tests passed please review!

#7426 7367-pragmas-not-needed-textEditorShiftedMenu-fileListContentMenu
  src/Text-Edition/TextEditor.class.st
  src/Tool-FileList/FileList.class.st
Labels: tests passed please review!

#7417 Exposing signalContext in Exception
  src/Kernel-Tests-Extended/ProcessTest.class.st
  src/Kernel/Exception.class.st
  src/Kernel/Process.class.st
  src/NewTools-Debugger-Tests/StDebuggerTest.class.st
Labels: tests passed please review!

#7425 7414-division-of-number-by-array-fails-with-doesNotUnderstand-isZero
  src/Collections-Arithmetic-Tests/CollectionArithmeticTest.class.st
  src/Collections-Arithmetic/Collection.extension.st
Labels: easyReview, tests passed please review!

#7337 Background failures log in CI
  src/JenkinsTools-Core/Error.extension.st
  src/JenkinsTools-Core/Exception.extension.st
  src/JenkinsTools-Core/HDTestReport.class.st
  src/JenkinsTools-Core/Halt.extension.st
  src/JenkinsTools-Core/TestFailedByForkedProcess.extension.st
  src/JenkinsTools-Core/TestFailure.extension.st
  src/JenkinsTools-Core/TestSkip.extension.st
  src/JenkinsTools-Core/UnhandledError.extension.st
  src/SUnit-Core/ProcessMonitorTestService.class.st
  src/SUnit-Core/TestExecutionEnvironment.class.st
  src/SUnit-Tests/ProcessMonitorTestServiceTest.class.st
  src/SUnit-UI/CommandLineTestRunner.class.st
  src/SUnit-UI/VTermTestRunner.class.st
Labels: tests passed please review!

#7328 Added a closeAllDebugger method to trait TDebugger class, that users …
  src/Debugger-Model-Tests/TDebuggerTest.class.st
  src/Debugger-Model/TDebugger.trait.st
  src/EmergencyDebugger/EDEmergencyDebugger.class.st
Labels: tests passed please review!

#7436 Cleaning integer division
  src/Collections-Arithmetic/Collection.extension.st
  src/Kernel/SmallInteger.class.st
Labels: tests passed please review!

#7433 7431-preparing-fluid-class-Part-1
  src/ClassParser/CDAbstractClassDefinitionParser.class.st
  src/ClassParser/CDClassSideTraitDefinitionNode.class.st
  src/ClassParser/CDClassTagNode.class.st
  src/ClassParser/CDPackageNode.class.st
  src/ClassParser/CDTraitDefinitionNode.class.st
Labels: tests passed please review!

#7432 betterName-isSharedLiteral
  src/Collections-Native/ByteArray.class.st
  src/Collections-Sequenceable/Array.class.st
  src/Collections-Strings/String.class.st
  src/Kernel/Object.class.st
  src/OpalCompiler-Core/IRTranslator.class.st
  src/Tool-ImageCleaner/ImageCleaner.class.st
Labels: tests passed please review!

#7434 7412-preparing-the-integration-of-fluid-class-part-2
  src/Kernel/AbstractLayout.class.st
  src/Kernel/ByteLayout.class.st
  src/Kernel/CompiledMethodLayout.class.st
  src/Kernel/DoubleByteLayout.class.st
  src/Kernel/DoubleWordLayout.class.st
  src/Kernel/EmptyLayout.class.st
  src/Kernel/EphemeronLayout.class.st
  src/Kernel/FixedLayout.class.st
  src/Kernel/ImmediateLayout.class.st
  src/Kernel/VariableLayout.class.st
  src/Kernel/WeakLayout.class.st
  src/Kernel/WordLayout.class.st
Labels: tests passed please review!

#7430 7362-Package-Debugger-Filters-is-not-used-and-can-be-removed
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/BaselineOfUI/BaselineOfUI.class.st
  src/Debugger-Filters-Tests/FilterTest.class.st
  src/Debugger-Filters/BlockClosure.extension.st
  src/Debugger-Filters/BlockFilter.class.st
  src/Debugger-Filters/BooleanFilter.class.st
  src/Debugger-Filters/KernelClassesFilter.class.st
  src/Debugger-Filters/ManifestDebuggerFilters.class.st
  src/Debugger-Filters/SelectorFilter.class.st
  src/Debugger-Filters/StackFilter.class.st
  src/Graphics-Tests/PointTest.class.st
Labels: tests passed please review!

#7408 Debugger-should-show-Workspace-bindings
  src/AST-Core/RBMethodNode.class.st
  src/AST-Core/RBProgramNode.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#7404 5956-Wrong-format-of-DoubleWordArray
  src/Collections-Native/DoubleByteArray.class.st
  src/Collections-Tests/NativeArrayTest.class.st
  src/Kernel/AbstractLayout.class.st
  src/Kernel/Class.class.st
  src/Monticello/MCClassDefinition.class.st
Labels: tests passed please review!

#7435 Variable-scope-addTests
  src/Kernel/Slot.class.st
  src/Slot-Tests/ClassVariableTest.class.st
  src/Slot-Tests/GlobalVariableTest.class.st
  src/Slot-Tests/SlotTest.class.st
  src/Slot-Tests/TemporaryVariableTest.class.st
Labels: tests passed please review!

#7418 SourceFileBufferedReadWriteStreamTest-readOnlyLiteral
  src/Tests/SourceFileBufferedReadWriteStreamTest.class.st
Labels: tests passed please review!

#7441 7416-Fileout-a-protocol-raises-a-DNU
  src/Calypso-SystemPlugins-FileOut-Queries/ClyMethodGroup.extension.st
  src/CodeExport/ClassDescription.extension.st
Labels: tests passed please review!

#7438 7437-prepare-fluid-class-integration-part-3
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
  src/ClassParser/CDBehaviorDefinitionNode.class.st
  src/ClassParser/CDClassDefinitionNode.class.st
  src/ClassParser/CDClassTraitNode.class.st
  src/ClassParser/CDMetaclassDefinitionNode.class.st
Labels: tests passed please review!

#7447 7042-Better-comment-for-CompiledBlock-and-FullBlock
  src/Kernel/CleanBlockClosure.class.st
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#7419 Playground-Self-Bindings
  src/HeuristicCompletion-Model/CoVariableValueMessageHeuristic.class.st
Labels: tests passed please review!

#7442 Skip-HiExamplesTest-testAllExamples
  src/Hiedra-Tests/HiExamplesTest.class.st
Labels: tests passed please review!

#7492 7423-Breakpoint-on-while-nodes-do-not-work
  src/Reflectivity-Tests/ReflectivityControlTest.class.st
  src/Reflectivity-Tests/ReflectivityExamples.class.st
  src/Reflectivity/RFASTTranslator.class.st
Labels: tests passed please review!

#7494 Cleanup-NautilusRefactoring-Shortcuts
  src/NautilusRefactoring/NautilusRefactoring.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
  src/Tool-Finder/FinderUI.class.st
  src/Tool-ProcessBrowser/ProcessBrowser.class.st
Labels: tests passed please review!

#7506 improvement of the travis help
  src/Pharo-Help/TravisIntegrationHelp.class.st
Labels: tests passed please review!

#7501 7500-Remove-argument-refactoring-from-Calypso-hangs-forever
  src/SystemCommands-MessageCommands/SycMessageDescription.class.st
  src/SystemCommands-MessageCommands/SycMessageOriginHack.class.st
  src/SystemCommands-RefactoringSupport-Tests/SycRefactoringStoreOnTest.class.st
Labels: tests passed please review!

#7502 Add backwards compatibility Pharo9 to Pharo8
  src/OSWindow-Core/OSWindowHandle.class.st
  src/OpalCompiler-Core/IRBytecodeGenerator.class.st
  src/System-Platforms/Key.class.st
Labels: tests passed please review!

#7509 Fix #7507: Methods comments in Collection
  src/Collections-Sequenceable/OrderedCollection.class.st
Labels: tests passed please review!

#7511 Doit-RequestorScope
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#7512 DoIt-access-with-ReadVariable
  src/OpalCompiler-Core/RBMethodNode.extension.st
Labels: tests passed please review!

#7513 CompilerBackend-pushThisProcess
  src/Kernel-BytecodeEncoders/BytecodeEncoder.class.st
  src/Kernel-BytecodeEncoders/EncoderForSistaV1.class.st
  src/OpalCompiler-Core/IRBuilder.class.st
  src/OpalCompiler-Core/IRBytecodeGenerator.class.st
  src/OpalCompiler-Core/IRInstruction.class.st
  src/OpalCompiler-Core/IRPrinter.class.st
  src/OpalCompiler-Core/IRPushThisProcess.class.st
  src/OpalCompiler-Core/IRTranslator.class.st
  src/OpalCompiler-Core/IRVisitor.class.st
  src/OpalCompiler-Tests/IRBuilderTest.class.st
Labels: tests passed please review!

#7491 7490-definition-on-classDescription-can-be-simplified
  src/Kernel-Tests/OldPharoClassDefinitionPrinterTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/Metaclass.class.st
  src/Kernel/OldPharoClassDefinitionPrinter.class.st
  src/Manifest-Core/RGClassDescriptionDefinition.extension.st
  src/Monticello/Class.extension.st
  src/Monticello/MCClassDefinition.class.st
  src/Monticello/MCTraitDefinition.class.st
  src/Monticello/Trait.extension.st
  src/Refactoring-Changes/RBAddClassTraitChange.class.st
  src/Refactoring-Tests-Changes/RBRefactoringChangeTest.class.st
  src/Ring-Definitions-Monticello/MCTraitDefinition.extension.st
  src/Ring-Definitions-Tests-Core/RGClassDefinitionTest.class.st
  src/System-Support-Tests/ClassQueryTest.class.st
  src/Tests/TraitTest.class.st
  src/TraitsV2-Tests/T2PrecedenceCompositionTest.class.st
  src/TraitsV2-Tests/T2TraitMCDefinitionsTest.class.st
  src/TraitsV2/MetaclassForTraits.class.st
  src/TraitsV2/Trait.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: Need more work

#7518 Cleanup-headerFlagForEncoder
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#7524 Variables-isTempVariable
  src/AST-Core-Tests/RBVariableNodeTest.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBVariableNode.class.st
  src/Calypso-SystemTools-Core/ClySourceCodeContext.class.st
  src/ClassParser-Tests/CDExistingClassDefinitionTest.class.st
  src/ClassParser/CDClassNameNode.class.st
  src/ClassParser/CDSlotNode.class.st
  src/Deprecated90/RBProgramNode.extension.st
  src/Deprecated90/Variable.extension.st
  src/GeneralRules/ReTemporaryNeitherReadNorWrittenRule.class.st
  src/Kernel/Variable.class.st
  src/NECompletion/TypingVisitor.class.st
  src/OpalCompiler-Core/TemporaryVariable.class.st
  src/OpalCompiler-Tests/OCASTCheckerTest.class.st
  src/Reflectivity-Tests/LinkInstallerTest.class.st
  src/Reflectivity/RFVariableReification.class.st
  src/Ring-Core/RGVariable.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#7508 Introduce symbolic platform independent name to the morphic keyDown and keyUp events
  src/Morphic-Core/KeyboardEvent.class.st
  src/OSWindow-Core/OSKeySymbols.class.st
  src/OSWindow-Core/OSWindowMorphicEventHandler.class.st
  src/System-Platforms/KeyboardKey.class.st
Labels: tests passed please review!

#7526 Replace Character cr asString to String cr
  src/EmergencyDebugger/EDDebuggingAPI.class.st
  src/EnlumineurFormatter-Tests/EFInternalTest.class.st
  src/GT-SUnitDebugger/Collection.extension.st
  src/Refactoring-Core/RBRemoveClassRefactoring.class.st
  src/Refactoring2-Transformations/RBRemoveClassTransformation.class.st
  src/Rubric/RubTextAreaExamples.class.st
  src/System-Clipboard/Clipboard.class.st
Labels: tests passed please review!

#7528 MetaLinkResolver-simplify
  src/Reflectivity-Tests/MetaLinkTargetResolverTest.class.st
  src/Reflectivity/Class.extension.st
  src/Reflectivity/MetaLinkInstaller.class.st
  src/Reflectivity/Metaclass.extension.st
  src/Reflectivity/MetalinkTargetResolver.class.st
  src/Reflectivity/Object.extension.st
  src/Reflectivity/PermaLink.class.st
  src/Reflectivity/ProtoObject.extension.st
  src/Reflectivity/Trait.extension.st
Labels: tests passed please review!

#7530 7529-ImageReadWriter-should-raise-a-specialised-exception-and-not-Error
  src/Graphics-Files/ImageReadWriter.class.st
  src/Graphics-Files/LzwGifDecoder.class.st
  src/Graphics-Files/UnrecognizedImageFormatError.class.st
Labels: tests passed please review!

#7517 CaseOf-Remove-BackendError
  src/Kernel-Tests/ObjectTest.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/RBMessageNode.extension.st
  src/OpalCompiler-Tests/OCCaseOfTest.class.st
Labels: tests passed please review!

#7531 7421-Variable-breakpoints-do-not-work-on-class-variables
  src/Reflectivity-VariableBreakpoint/Class.extension.st
  src/Reflectivity-VariableBreakpoint/VariableBreakpointMockClass.class.st
  src/Reflectivity-VariableBreakpoint/VariableBreakpointTest.class.st
  src/Reflectivity/MetaLink.class.st
  src/Reflectivity/MetaLinkInstaller.class.st
Labels: tests passed please review!

#7534 ScaledDecimal-readOnlyLiteral
  src/Kernel/ScaledDecimal.class.st
Labels: tests passed please review!

#7542 VariableBreakPoint-package-merge
  src/BaselineOfReflectivity/BaselineOfReflectivity.class.st
  src/Reflectivity-Tests/VariableBreakpointMockClass.class.st
  src/Reflectivity-Tests/VariableBreakpointMockSubclass.class.st
  src/Reflectivity-Tests/VariableBreakpointTest.class.st
  src/Reflectivity-VariableBreakpoint/Breakpoint.extension.st
  src/Reflectivity-VariableBreakpoint/Class.extension.st
  src/Reflectivity-VariableBreakpoint/CompiledMethod.extension.st
  src/Reflectivity-VariableBreakpoint/Object.extension.st
  src/Reflectivity-VariableBreakpoint/RBProgramNode.extension.st
  src/Reflectivity/Breakpoint.class.st
  src/Reflectivity/Class.extension.st
  src/Reflectivity/CompiledMethod.extension.st
  src/Reflectivity/Object.extension.st
  src/Reflectivity/RBAssignmentNode.extension.st
  src/Reflectivity/RBProgramNode.extension.st
  src/Reflectivity/RBVariableNode.extension.st
  src/Reflectivity/VariableBreakpoint.class.st
Labels: tests passed please review!

#7541 Cleanup-referredInstVars
  src/Kernel/CompiledCode.class.st
Labels: tests passed please review!

#7555 Cleanup Fonts-Abstract package
  src/Athens-Text/AbstractFont.extension.st
  src/Fonts-Abstract/AbstractFont.class.st
  src/Fonts-Abstract/ManifestFontsAbstract.class.st
  src/Fonts-Abstract/StubFixedFont.class.st
Labels: tests passed please review!

#7575 Use ifNil: in BitBlt>>#fillColor:
  src/Graphics-Primitives/BitBlt.class.st
Labels: tests passed please review!

#7540 isClean-using-CleanBlockChecker
  src/Debugging-Core/CleanBlockChecker.class.st
  src/Kernel-Tests/BlockClosureTest.class.st
  src/Kernel/BlockClosure.class.st
  src/OpalCompiler-Tests/OCClosureTest.class.st
Labels: tests passed please review!

#7551 7535-Variable-Breakpoints-Wrong-Icon-in-gutter
  src/Reflectivity-Tools/MetaLinkIconStyler.class.st
  src/Reflectivity/Breakpoint.class.st
  src/Reflectivity/ExecutionCounter.class.st
  src/Reflectivity/MetaLink.class.st
  src/Reflectivity/Watch.class.st
Labels: tests passed please review!

#7543 Fix crashes and memory leaks in OSSDL2AthensRenderer
  src/OSWindow-Core/OSWindow.class.st
  src/OSWindow-Core/OSWindowEventVisitor.class.st
  src/OSWindow-SDL2/AthensCairoSDLSurface.class.st
  src/OSWindow-SDL2/OSSDL2AthensRenderer.class.st
  src/OSWindow-SDL2/SDL_Surface.class.st
Labels: tests passed please review!

#7552 DNU in RubCurrentLineBarDecorator for #compose
  src/FreeType/FreeTypeFont.class.st
Labels: tests passed please review!

#7571 Simplify Form>>#bitsSize
  src/Graphics-Display Objects/Form.class.st
Labels: tests passed please review!

#7561 Cleanup FreeTypeCache
  src/FreeType-Tests/FreeTypeCacheTest.class.st
  src/FreeType/FreeTypeCache.class.st
Labels: tests passed please review!

#7569 Cleanup ExternalType>>#cleanupUnusedTypes
  src/FFI-Kernel/ExternalType.class.st
Labels: tests passed please review!

#7553 isReadOnlyLiteral-Float-Integer
  src/Kernel/Float.class.st
  src/Kernel/Integer.class.st
  src/Kernel/SmallFloat64.class.st
  src/Kernel/SmallInteger.class.st
Labels: tests passed please review!

#7590 7589-isReadOnlyObject-and-beReadOnlyObject-are-not-consistent-wrt-immediate-objects
  src/Kernel-Tests-Extended/WriteBarrierTest.class.st
  src/Kernel/Object.class.st
Labels: tests passed please review!

#7586 6001-isTemp-might-fail-on-Pharo-AST
  src/AST-Core/RBVariableNode.class.st
  src/OpalCompiler-Core/OCASTSemanticCleaner.class.st
  src/OpalCompiler-Core/RBVariableNode.extension.st
  src/OpalCompiler-Core/UnresolvedVariable.class.st
Labels: tests passed please review!

#7546 Add support for mesh gradients to Athens
  src/Athens-Cairo/AthensAbstractMeshPaintPatch.extension.st
  src/Athens-Cairo/AthensCairoMeshGradientPaint.class.st
  src/Athens-Cairo/AthensCairoSurface.class.st
  src/Athens-Cairo/CoonsPaintPatch.extension.st
  src/Athens-Cairo/GenericPaintPatch.extension.st
  src/Athens-Cairo/TrianglePaintPatch.extension.st
  src/Athens-Core/AthensAbstractMeshPaintPatch.class.st
  src/Athens-Core/AthensSurface.class.st
  src/Athens-Core/CoonsPaintPatch.class.st
  src/Athens-Core/GenericPaintPatch.class.st
  src/Athens-Core/MeshGradientPaint.class.st
  src/Athens-Core/TrianglePaintPatch.class.st
  src/Athens-Examples/AthensSurfaceExamples.class.st
Labels: tests passed please review!

#7596 Merge-MetaLinkStyler
  src/Reflectivity-Examples/CoverageRubricStyler.class.st
  src/Reflectivity-Examples/MetalinkIconStyler.class.st
Labels: tests passed please review!

#7594 7591-We-have-isImmediateClass-add-isImmediateObject
  src/Kernel-Tests/ProtoObjectTest.class.st
  src/Kernel/Object.class.st
  src/Kernel/ProtoObject.class.st
  src/Kernel/SmallFloat64.class.st
  src/Kernel/SmallInteger.class.st
Labels: tests passed please review!

#7593 7592-add-beRecursivelyReadOnlyObject
  src/Kernel-Tests/ObjectTest.class.st
  src/Kernel/Object.class.st
Labels: tests passed please review!

#7605 FontFamilyAbstract should be renamed to AbstractFontFamily
  src/Deprecated90/FontFamilyAbstract.class.st
  src/Fonts-Infrastructure-Tests/AbstractFontFamilyTest.class.st
  src/Fonts-Infrastructure/AbstractFontFamily.class.st
  src/Fonts-Infrastructure/TextStyleAsFontFamily.class.st
  src/FreeType/FreeTypeFontFamily.class.st
Labels: tests passed please review!

#7538 Move SystemAnnouncement extensions from Calypso
  src/Calypso-SystemPlugins-Reflectivity-Queries/MetalinkChanged.extension.st
  src/Calypso-SystemQueries/Announcement.extension.st
  src/Calypso-SystemQueries/ClassAnnouncement.extension.st
  src/Calypso-SystemQueries/ClassModificationApplied.extension.st
  src/Calypso-SystemQueries/ClassRemoved.extension.st
  src/Calypso-SystemQueries/ClassRenamed.extension.st
  src/Calypso-SystemQueries/ClassRepackaged.extension.st
  src/Calypso-SystemQueries/ClassTagAnnouncement.extension.st
  src/Calypso-SystemQueries/MethodAnnouncement.extension.st
  src/Calypso-SystemQueries/MethodModified.extension.st
  src/Calypso-SystemQueries/MethodRecategorized.extension.st
  src/Calypso-SystemQueries/MethodRemoved.extension.st
  src/Calypso-SystemQueries/MethodRepackaged.extension.st
  src/Calypso-SystemQueries/ProtocolAnnouncement.extension.st
  src/Calypso-SystemQueries/RPackage.extension.st
  src/Calypso-SystemQueries/RPackageAnnouncement.extension.st
  src/Calypso-SystemQueries/RPackageRenamed.extension.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageAnnouncement.class.st
  src/RPackage-Core/RPackageRenamed.class.st
  src/Reflectivity/MetalinkChanged.class.st
  src/System-Announcements/Announcement.extension.st
  src/System-Announcements/ClassAnnouncement.class.st
  src/System-Announcements/ClassRemoved.class.st
  src/System-Announcements/ClassRenamed.class.st
  src/System-Announcements/ClassRepackaged.class.st
  src/System-Announcements/ClassTagAnnouncement.class.st
  src/System-Announcements/MethodAnnouncement.class.st
  src/System-Announcements/MethodModified.class.st
  src/System-Announcements/MethodRecategorized.class.st
  src/System-Announcements/MethodRemoved.class.st
  src/System-Announcements/MethodRepackaged.class.st
  src/System-Announcements/ProtocolAnnouncement.class.st
Labels: tests passed please review!

#7597 Variables-use-pushLiteral
  src/AST-Core-Traits/TRBProgramNodeVisitor.trait.st
  src/EnlumineurFormatter/EFFormatter.class.st
  src/Kernel/AdditionalBinding.class.st
  src/Kernel/ClassVariable.class.st
  src/Kernel/GlobalVariable.class.st
  src/Kernel/LiteralVariable.class.st
  src/Kernel/Slot.class.st
  src/Kernel/WorkspaceVariable.class.st
  src/Reflectivity-Tools-Tests/MethodConstantTest.class.st
  src/Reflectivity/HookGenerator.class.st
  src/Reflectivity/RBProgramNodeVisitor.extension.st
  src/Reflectivity/RBSimpleFormatter.extension.st
  src/Reflectivity/RFASTTranslator.class.st
  src/Reflectivity/RFEntityReification.class.st
  src/Reflectivity/RFLinkReification.class.st
  src/Reflectivity/RFLiteralVariableNode.class.st
  src/Reflectivity/RFMethodReification.class.st
  src/Reflectivity/RFNodeReification.class.st
  src/Reflectivity/RFOperationReification.class.st
  src/Reflectivity/RFOriginalMethodReification.class.st
  src/Reflectivity/RFValueReification.class.st
  src/Reflectivity/RFVariableReification.class.st
  src/Reflectivity/ReflectiveMethod.class.st
Labels: tests passed please review!

#7620 newtools-0.4.5 remove remaining halt
  src/NewTools-Debugger/StDebugger.class.st
Labels: tests passed please review!

#7626 Tests of VariableBreakpointTests now check that the Break exception has been raised, instead of checking the Halt exception
  src/Reflectivity-Tests/VariableBreakpointTest.class.st
Labels: tests passed please review!

#7483 [DrTests] Other test hierarchies than TestAssertable are not handled by DrTest
  src/DrTests-TestsRunner/DTTestsRunner.class.st
  src/DrTests/DTFilterableListPresenter.class.st
  src/DrTests/DrTests.class.st
  src/DrTests/DrTestsPlugin.class.st
  src/SUnit-Core/TestResult.class.st
Labels: tests passed please review!

#7635 Fixed #7627. Changing canonicalClassName of True and False to Boolean
  src/Debugger-Model-Tests/DynamicMessageImplementorTest.class.st
  src/Tools/Boolean.extension.st
Labels: tests passed please review!

#7630 7366-Small-Cleanup-SystemOrganizer
  src/System-Support/SystemOrganizer.class.st
Labels: tests passed please review!

#7621 Deprecated withSqueakLineEndings. Fixed #7446
  src/Collections-Strings/String.class.st
  src/Text-Core/Text.class.st
Labels: tests passed please review!

#7619 [improvement] change name of 'paste...' command to be clearer
  src/Rubric/RubPlainTextMode.class.st
  src/Rubric/RubSmalltalkCodeMode.class.st
  src/Text-Edition/TextEditor.class.st
  src/Tool-FileList/FileList.class.st
Labels: tests passed please review!

#7632 ClyQuery-supportsWriteBarrier-cleanup
  src/Calypso-NavigationModel/ClyQuery.class.st
Labels: tests passed please review!

#7623 7613-Settings-not-storing-correct-values
  src/System-Settings-Core/AbstractStoredSetting.class.st
  src/System-Settings-Core/SettingsStonWriter.class.st
  src/System-Settings-Core/StoredSettingsFactory.class.st
  src/System-Settings-Tests/MockSettings.class.st
  src/System-Settings-Tests/SystemSettingsPersistenceTest.class.st
Labels: tests passed please review!

#7636 MetaLinkInstaller-do-not-rely-on-MetaLinkChanged
  src/Reflectivity/MetaLinkInstaller.class.st
  src/Reflectivity/MetalinkChanged.class.st
  src/Reflectivity/RBProgramNode.extension.st
Labels: tests passed please review!
