Repository pharo-project/pharo, pull requests merged in 2020-12, with the labels that each got.

#7919 Improve-isHaltNode
  src/AST-Core/RBMessageNode.class.st
  src/Debugging-Utils-Tests/HaltTest.class.st
Labels: tests passed please review!

#7891 7830-DummyFindReplaceService-not-documented-not-used-Can-be-removed
  src/Rubric/DummyFindReplaceService.class.st
Labels: tests passed please review!

#7910 Tag classes in DrTests-TestsRunner
  src/DrTests-TestsRunner/DTDebugTestCommand.class.st
  src/DrTests-TestsRunner/DTError.class.st
  src/DrTests-TestsRunner/DTFail.class.st
  src/DrTests-TestsRunner/DTPass.class.st
  src/DrTests-TestsRunner/DTRerunCommand.class.st
  src/DrTests-TestsRunner/DTSkipped.class.st
  src/DrTests-TestsRunner/DTTestLeaf.class.st
  src/DrTests-TestsRunner/DTTestResultType.class.st
  src/DrTests-TestsRunner/DTTestsRunner.class.st
  src/DrTests-TestsRunner/DTTestsRunnerConfiguration.class.st
  src/DrTests-TestsRunner/DTTestsRunnerResult.class.st
Labels: tests passed please review!

#7931 7927-halt-left-in-OmBlockrefreshIfNeededStartingAtsince
  src/Ombu/OmBlock.class.st
Labels: tests passed please review!

#7926 tag more tests with <haltOrBreakpointForTesting>
  src/Calypso-SystemPlugins-Critic-Queries-Tests/ClyClassWithProblemMethods.class.st
  src/Calypso-SystemPlugins-Reflectivity-Queries-Tests/ClyActiveBreakpointsQueryTest.class.st
  src/Calypso-SystemPlugins-Reflectivity-Queries-Tests/ClyClassWithHalts.class.st
  src/Debugger-Model-Tests/StepOverTest.class.st
  src/Refactoring-Tests-Critics/RBSmalllintTestObject.class.st
  src/System-SessionManager-Tests/SessionErrorHandlingTest.class.st
Labels: tests passed please review!

#7940 Remove unused environment ivar from BuilderManifestTest
  src/Manifest-Tests/BuilderManifestTest.class.st
Labels: tests passed please review!

#7944 Care on unreferenced variables in OpalCompiler packages
  src/OpalCompiler-Tests/OCMockCompilationClass.class.st
  src/OpalCompiler-Tests/OCScopeTest.class.st
  src/OpalCompiler-Tests/OCSourceCode2BytecodeTest.class.st
Labels: tests passed please review!

#7933 Cleanup tests and mock package of DrTest (Second attempt)
  src/BaselineOfDrTests/BaselineOfDrTests.class.st
  src/DrTests-TestCoverage-MocksForTests/MockForCoverage.class.st
  src/DrTests-TestCoverage-MocksForTests/package.st
  src/DrTests-TestCoverage-Tests-Mocks/DTCoverageMockTest.class.st
  src/DrTests-TestCoverage-Tests-Mocks/MockForCoverage.class.st
  src/DrTests-TestCoverage-Tests-Mocks/package.st
  src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
  src/DrTests-Tests/DrTestsTestRunnerTest.class.st
  src/DrTests-TestsProfiling-Tests/DTTestProfilingTest.class.st
Labels: tests passed please review!

#7943 Remove unused ivars from HeuristicCompletion packages
  src/HeuristicCompletion-Tests/CoBasicCompletionTest.class.st
  src/HeuristicCompletion-Tests/CoMockClass.class.st
Labels: tests passed please review!

#7950 RBPragmaNode-accessor-simpler
  src/AST-Core/RBPragmaNode.class.st
Labels: tests passed please review!

#7962 TRBProgramNodeVisitor-methods-missing
  src/AST-Core-Traits/TRBProgramNodeVisitor.trait.st
Labels: tests passed please review!

#7969 "Browse Breakpoints" should not show implementation methods
  src/Calypso-SystemPlugins-Reflectivity-Queries/ClyActiveBreakpointsQuery.class.st
Labels: tests passed please review!

#7970 7928-halt-left-in-FBDDecompilerpushFullClosurenumCopiedreceiverOnStackignoreOuterContext
  src/Flashback-Decompiler/FBDDecompiler.class.st
Labels: tests passed please review!

#7932 7925-halt-left-in-FFIFunctionParsersetOn
  src/UnifiedFFI/FFIFunctionParser.class.st
Labels: tests passed please review!

#7976 7953 huge debugger st pharo application memory leak
  src/Debugger-Model-Tests/DebuggerModelTest.class.st
  src/Debugger-Model/DebugSession.class.st
  src/NewTools-Debugger/StDebuggerActionModel.class.st
Labels: tests passed please review!

#7972 Cleanup-EncoderForV3PlusClosures
  src/Kernel-BytecodeEncoders/BytecodeEncoder.class.st
  src/Kernel-BytecodeEncoders/EncoderForSistaV1.class.st
  src/Kernel-BytecodeEncoders/EncoderForV3.class.st
  src/Kernel-BytecodeEncoders/EncoderForV3PlusClosures.class.st
  src/Kernel-Tests/FluidClassDefinitionPrinterTest.class.st
  src/OpalCompiler-Core/ManifestOpalCompilerCore.class.st
Labels: tests passed please review!

#7958 7956-Completion-broken-in-Transcript
  src/HeuristicCompletion-Morphic/CoCompletionEngine.class.st
  src/Transcript-Core/ThreadSafeTranscript.class.st
Labels: tests passed please review!

#7946 Remove unused lastKeyboardFocus ivare from OSSDL2BackendWindow
  src/OSWindow-SDL2/OSSDL2BackendWindow.class.st
Labels: tests passed please review!

#7977 7975-ReleaseTesttestMethodsContainNoHalt
  src/ReleaseTests/ReleaseTest.class.st
Labels: tests passed please review!

#7938 Fixed #7937. Implemented Random>>nextBetween:and:, nextIntBetween:and:, and wrote tests for them
  src/Random-Core/Random.class.st
  src/Random-Tests/RandomTest.class.st
Labels: tests passed please review!

#7839 Simplify-ReUnaryAccessingMethodWithoutReturnRule
  src/GeneralRules/ReUnaryAccessingMethodWithoutReturnRule.class.st
Labels: tests passed please review!

#7929 AST-add-more-Variable-visit-methods
  src/AST-Core-Traits/TRBProgramNodeVisitor.trait.st
  src/AST-Core/RBProgramNodeVisitor.class.st
  src/ClassParser/CDTraitCompositionBuilder.class.st
  src/HeuristicCompletion-Model/CoASTResultSetBuilder.class.st
  src/Kernel/ClassVariable.class.st
  src/Kernel/GlobalVariable.class.st
  src/Kernel/LiteralVariable.class.st
  src/OpalCompiler-Core/ArgumentVariable.class.st
  src/OpalCompiler-Core/LocalVariable.class.st
  src/OpalCompiler-Core/PrimitiveErrorVariable.class.st
  src/OpalCompiler-Core/TemporaryVariable.class.st
  src/Ring-Core/RGSlot.class.st
Labels: tests passed please review!

#7982 7980-fix-checkClassRebuild
  src/Epicea/Class.extension.st
  src/Epicea/Metaclass.extension.st
  src/Kernel/UndefinedSlot.class.st
Labels: tests passed please review!

#7622 Fixed #7612. The bug that happened when an IntegerArray was added to a FloatArray
  src/Collections-Abstract/Collection.class.st
  src/Collections-Arithmetic/FloatArray.extension.st
  src/Collections-Native/FloatArray.class.st
  src/Collections-Tests/FloatArrayTest.class.st
  src/Kernel/Number.class.st
Labels: tests passed please review!

#7981 add Trait>>#isUsed.
  src/TraitsV2/Trait.class.st
Labels: tests passed please review!

#7986 Only concrete Font descriptions should be installable
  src/EmbeddedFreeType/EmbeddedFreeTypeFontDescription.class.st
Labels: tests passed please review!

#7983 7966-Temporary-Variables-Cannot-be-used-in-loops-in-a-playground
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
Labels: tests passed please review!

#7988 fixes #7924: Enhance CodeImporter with better comment
  src/CodeImport/CodeImporter.class.st
Labels: tests passed please review!

#7998 7993-Completion-broken-while-editing
  src/HeuristicCompletion-Model/CoASTResultSetBuilder.class.st
  src/HeuristicCompletion-Tests/CoASTResultSetBuilderTest.class.st
Labels: tests passed please review!

#7778 Fix win32 library name for freetype
  src/FreeType/FT2FFILibrary.class.st
Labels: Need more work

#8022 ReSearchStringSourceAnchor>>#interval should not use deprecated #definition
  src/Renraku/ReSearchStringSourceAnchor.class.st
Labels: tests passed please review!

#8021 Fixed #8014. Renamed Random >> nextInt: and nextIntBetween:and: to nextInteger: and nextIntegerBetween:and:
  src/AST-Core-Tests/NumberParserTest.class.st
  src/Collections-Abstract/SequenceableCollection.class.st
  src/Files/Stdio.class.st
  src/Hiedra-Examples/HiExampleCommit.class.st
  src/Kernel-Tests-Extended/FloatTest.extension.st
  src/Kernel-Tests/DelayBenchmark.class.st
  src/Kernel-Tests/LargePositiveIntegerTest.class.st
  src/Network-UUID/UUIDGenerator.class.st
  src/Random-Core/Bag.extension.st
  src/Random-Core/Collection.extension.st
  src/Random-Core/Integer.extension.st
  src/Random-Core/OrderedDictionary.extension.st
  src/Random-Core/Random.class.st
  src/Random-Core/SequenceableCollection.extension.st
  src/Random-Core/Set.extension.st
  src/Random-Core/SharedRandom.class.st
  src/Random-Tests/RandomTest.class.st
  src/Spec-Tests/RGBSlidersTest.class.st
  src/Spec2-Morphic-Tests/SpRGBSlidersTest.class.st
Labels: more-information-needed

#8027 Gofer-UI package should be removed in Pharo 9
  src/BaselineOfPharo/BaselineOfPharo.class.st
  src/Gofer-UI/GoferBrowseLocalChanges.class.st
  src/Gofer-UI/GoferBrowseRemoteChanges.class.st
  src/Gofer-UI/ManifestGoferUI.class.st
  src/Gofer-UI/package.st
Labels: easyReview, tests passed please review!

#7951 AST-Cleanup-visitUnreachableStatement
  src/AST-Core/RBCommentNodeVisitor.class.st
  src/AST-Core/RBGenericNodeVisitor.class.st
  src/AST-Core/RBParseErrorNodeVisitor.class.st
  src/Reflectivity-Tools/ErrorNodeStyler.class.st
Labels: tests passed please review!

#8063 Clean selector casing in Renraku
  src/Renraku/ReAbstractCritique.class.st
  src/Renraku/ReFeedbacker.class.st
Labels: tests passed please review!

#8057 Cleanup ReAbstractRule
  src/Renraku/ReAbstractRule.class.st
Labels: tests passed please review!

#8029 Mark abstract test classes in Renraku-Tests
  src/Renraku-Tests/ReCodeBasedTestCase.class.st
  src/Renraku-Tests/ReExceptionStrategyBaseTest.class.st
  src/Renraku-Tests/RenrakuBaseTestCase.class.st
Labels: tests passed please review!

#8067 RBGenericNodeVisitor-tests
  src/AST-Core-Tests/RBCommentNodeVisitorTest.class.st
  src/AST-Core-Tests/RBGenericNodeVisitorTest.class.st
  src/AST-Core/RBAbstractBlockVisitor.class.st
Labels: tests passed please review!

#7995 Move ArrayTest to Collections-Sequenceable-Tests
  src/Collections-Sequenceable-Tests/ArrayTest.class.st
Labels: tests passed please review!

#8104 8086-RSLabelTest-Could-not-find-accessor-for-variable-named-anUTF8EncodedString
  src/Athens-Cairo/AthensCairoCanvas.class.st
Labels: tests passed please review!

#8110 RBProgramNode>>#doSemanticAnalysis should be correctly packaged
  src/OpalCompiler-Core/RBProgramNode.extension.st
Labels: tests passed please review!

#8121 ClassParser-reduce-NewUndeclaredWarning
  src/ClassParser/CDAbstractClassDefinitionParser.class.st
Labels: tests passed please review!

#8118 8117-RBMethodNode>>methodClass-should-gard-for-nil
  src/AST-Core-Tests/RBMethodNodeTest.class.st
  src/AST-Core/RBMethodNode.class.st
Labels: tests passed please review!

#8105 SlotScope-DeadCode-Clean
  src/Kernel/LayoutAbstractScope.class.st
  src/Kernel/LayoutClassScope.class.st
  src/Kernel/LayoutEmptyScope.class.st
Labels: tests passed please review!

#8116 Correctly decode file names from SDL2, at SDL2
  src/FileSystem-Core/FileReference.class.st
  src/Morphic-Base/DropFilesEvent.class.st
  src/Morphic-Base/Form.extension.st
  src/OSWindow-SDL2/OSSDL2Driver.class.st
Labels: tests passed please review!

#8126 Cleanup-ClassOrganization-listAtCategoryNumber
  src/Kernel/ClassOrganization.class.st
Labels: tests passed please review!

#8045 Fix class variable entanglement issue
  src/Kernel-Tests-Extended/ClassTest.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
Labels: tests passed please review!

#8141 Debugger fuel out stack command
  src/BaselineOfFuel/BaselineOfFuel.class.st
  src/BaselineOfNewTools/BaselineOfNewTools.class.st
  src/Fuel-Tools-Pharo-Tests/FLDebuggerStackSerializerTest.class.st
  src/Fuel-Tools-Pharo-Tests/package.st
  src/Fuel-Tools-Pharo/FLDebuggerStackMaterialization.class.st
  src/Fuel-Tools-Pharo/FLDebuggerStackSerializer.class.st
  src/Fuel-Tools-Pharo/FuelOutStackDebugAction.class.st
  src/JenkinsTools-Core/HDTestReport.class.st
  src/NewTools-Debugger-Fuel/StDebugger.extension.st
  src/NewTools-Debugger-Fuel/StFuelOutStackCommand.class.st
  src/NewTools-Debugger-Fuel/package.st
Labels: tests passed please review!

#8136 8135-When-executing-a-doit-against-a-context-the-class-is-not-correct
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OCDoitTest.class.st
Labels: tests passed please review!

#8159 8158-ContextquickStep-is-unused-and-strange
  src/Debugging-Core/Context.extension.st
  src/Kernel/Context.class.st
Labels: tests passed please review!

#8033 Add a lint rule for classes to have no "Uncategorized" classes in the package
  src/GeneralRules/ReClassNotCategorizedRule.class.st
Labels: tests passed please review!

#7990 DelayBasicScheduler had debug code left from review
  src/Kernel-Tests/DelayBasicSchedulerMicrosecondTickerTest.class.st
  src/Kernel/DelayBasicScheduler.class.st
Labels: tests passed please review!

#7979 RBMethodNode #pragmas is the only instance variable for AST children that has an accessor checking for nil
  src/AST-Core/RBMethodNode.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
Labels: tests passed please review!

#6700 [fix] remove itemFilterName for the spotter, as it seems to be unused…
  src/GT-Spotter/GTSpotterCandidatesListProcessor.class.st
  src/GT-SpotterExtensions-Core/Collection.extension.st
  src/GT-SpotterExtensions-Core/HelpTopic.extension.st
Labels: tests passed please review!

#6995 Fixes #6993 against P9: Incorrect error message on failed parsing of a number with high radix
  src/NumberParser/NumberParser.class.st
Labels: tests passed please review!

#6994 Fixes #6993 against P8: Incorrect error message on failed parsing of a number with high radix
  src/NumberParser/NumberParser.class.st
Labels: Pharo8, tests passed please review!

#6154 backportIfErrorDo
  src/Kernel/BlockClosure.class.st
Labels: Pharo8

#7959 Do not add DoIts to the cache for now. fixes #7955
  src/AST-Core/ASTCache.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#8165 Fix testCreationByUnnamed
  src/Ring-Tests-Core/RGClassDescripitonStrategyTest.class.st
Labels: tests passed please review!
