Repository pharo-project/pharo, pull requests merged in 2020-02, with the labels that each got.

#5632 5443-redo-readExponent
  src/Kernel-Tests/FloatTest.class.st
  src/NumberParser/NumberParser.class.st
Labels: tests passed please review!

#5613 5154-Improve-CompiledCodehasLiteralThorough-literal
  src/Collections-Sequenceable/Array.class.st
  src/Kernel-Tests-Extended/BehaviorTest.extension.st
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/Kernel/AdditionalMethodState.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/Object.class.st
Labels: Cleanup, tests passed please review!

#5637 5635-remove-RPackagemethodReferences
  src/Ring-Definitions-Core/RPackage.extension.st
Labels: tests passed please review!

#5636 5633-Speedup-implementors-and-senders-do-not-wrap-in-Ring1-entity
  src/Kernel-Tests-Extended/BehaviorTest.extension.st
  src/Kernel-Tests-Extended/SharedPoolTest.extension.st
  src/System-Support-Tests/SystemNavigationTest.class.st
  src/System-Support/SystemNavigation.class.st
  src/Tool-Base/SystemNavigation.extension.st
Labels: tests passed please review!

#5647 fixing ring version in PharoBootstrapProcess
  bootstrap/src/BaselineOfPharoBootstrapProcess/BaselineOfPharoBootstrapProcess.class.st
Labels: more-information-needed

#5659 5650-Make-unclosable-in-SystemWindow-does-not-work-revert-PR-5552
  src/Morphic-Widgets-Windows/SystemWindow.class.st
Labels: tests passed please review!

#5660 redo-5464-Bug-Slot-template-add-variable-without-hash-Crash-on-accept
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
Labels: tests passed please review!

#5643 5615-Completion-Engine-throw-error-in-some-specific-real-cases-
  src/Kernel-Tests-Extended/ClassTest.class.st
  src/Kernel/Class.class.st
  src/Kernel/UndefinedObject.class.st
Labels: tests passed please review!

#5639 CleanupWhichCategoryIncludesSelector
  src/Kernel-Tests/ClassDescriptionTest.class.st
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#5657 5401-AST-tests-should-not-depend-on-the-formatter
  src/AST-Core-Tests/RBProgramNodeTest.class.st
Labels: tests passed please review!

#5661 Slots: Unify Api Layout and Scope
  src/Slot-Core/LayoutAbstractScope.class.st
  src/Slot-Core/PointerLayout.class.st
Labels: tests passed please review!

#5658 CompiledCode #sourcePointer
  src/Kernel/CompiledBlock.class.st
Labels: tests passed please review!

#5640 5478-Inspector-on-a-ByteSymbol-should-get-the-senders-of-this-symbol-on-a-lazy-way
  src/GT-InspectorExtensions-Core/Symbol.extension.st
Labels: tests passed please review!

#5663 5631-Improve-atRandom-
  src/Random-Core/Bag.extension.st
  src/Random-Core/Collection.extension.st
Labels: tests passed please review!

#5664 system-windows-should-not-use-pragmas-for-menus
  src/Morphic-Base/Form.extension.st
  src/Morphic-Base/MenuMorph.class.st
  src/Morphic-Widgets-Windows/SystemWindow.class.st
  src/Polymorph-Widgets/SystemWindow.extension.st
Labels: Large Images, tests passed please review!

#5662 removing-pragma-collector-for-process-browser
  src/Tool-ProcessBrowser/ProcessBrowser.class.st
Labels: Large Images, tests passed please review!

#5666 whichCategoryIncludesSelectorNoCheckNeeded
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#5672 Compiler: CleanUp #sourceNodeExecutedForPC:
  src/Kernel/CompiledCode.class.st
  src/OpalCompiler-Core/CompiledBlock.extension.st
  src/OpalCompiler-Core/CompiledMethod.extension.st
  src/OpalCompiler-Core/Context.extension.st
  src/OpalCompiler-Core/IRInstruction.class.st
  src/OpalCompiler-Core/IRMethod.class.st
  src/OpalCompiler-Core/IRPushClosureCopy.class.st
  src/OpalCompiler-Core/RBBlockNode.extension.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
Labels: tests passed please review!

#5673 Context: Cleanup #sourceNodeExecuted
  src/Debugging-Core/Context.extension.st
Labels: tests passed please review!

#5668 5574-There-is-a-whichSelectorsRead-but-not-whichSelectorsWrite
  src/Kernel-Tests-Extended/ExceptionTest.extension.st
  src/Kernel-Tests/BehaviorTest.class.st
  src/Kernel-Tests/ClassDescriptionTest.class.st
  src/Kernel-Tests/ExceptionTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Refactoring-Environment/RBVariableEnvironment.class.st
Labels: tests passed please review!

#5665 #sharedPoolNames : move to Class
  src/Kernel/Behavior.class.st
  src/Kernel/Class.class.st
  src/Kernel/Metaclass.class.st
Labels: tests passed please review!

#5670 unify implementation of #doWithIndex: and withIndexDo
  src/Collections-Abstract/Collection.class.st
  src/Collections-Abstract/HashedCollection.class.st
  src/Collections-Abstract/SequenceableCollection.class.st
Labels: tests passed please review!

#5688 Adopt WelcomeHelp size to show all text
  src/Pharo-WelcomeHelp/WelcomeHelp.class.st
Labels: tests passed please review!

#5703 Compiler: Small dead code cleanup
  src/Debugging-Core/Context.extension.st
  src/OpalCompiler-Core/BytecodeEncoder.extension.st
Labels: tests passed please review!

#5702 testWhichSelectorsAccess small cleanup
  src/Kernel-Tests-Extended/BehaviorTest.extension.st
  src/Kernel-Tests/ClassDescriptionTest.class.st
Labels: tests passed please review!

#5700 5684-CollectionatRandom-can-use-withIndexDo
  src/Random-Core/Collection.extension.st
  src/Random-Core/OrderedDictionary.extension.st
Labels: tests passed please review!

#5706 Contex #sourceNode Comment and simpify
  src/OpalCompiler-Core/Context.extension.st
Labels: tests passed please review!

#5709 5704-rescue-tests-for-Float-Array
  src/Collections-Tests/FloatArrayTest.class.st
Labels: tests passed please review!

#5712 Float: add two missing subclassResponsibility methods
  src/Kernel/Float.class.st
Labels: tests passed please review!

#5710 Context: #sourceNode simplify by introducing #scope
  src/Debugging-Core/Context.extension.st
  src/Kernel-Tests-WithCompiler/ContextTest.extension.st
  src/OpalCompiler-Core/Context.extension.st
  src/OpalCompiler-Tests/MethodMapTest.class.st
Labels: tests passed please review!

#5711 #5693 use printString to simplify drTestName
  src/DrTests-TestCoverage/CompiledMethod.extension.st
Labels: tests passed please review!

#5716 Cleanup-enclosingMethodOrBlockNode
  src/OpalCompiler-Core/RBBlockNode.extension.st
  src/OpalCompiler-Core/RBProgramNode.extension.st
Labels: tests passed please review!

#5546 Fix issue #5542: Unnecessary double checks of infinity
  src/Kernel/Float.class.st
Labels: tests passed please review!

#5729 ManifestSpec2CommanderTests should be ManifestSpec2Commander2Tests
  src/Spec2-Commander2-Tests/ManifestSpec2Commander2Tests.class.st
Labels: tests passed please review!

#5740 Compiler: Remove AbstractCompiler
  src/GT-SpotterExtensions-Core/AbstractCompiler.extension.st
  src/GT-SpotterExtensions-Core/OpalCompiler.extension.st
  src/OpalCompiler-Core/AbstractCompiler.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#5742 Compiler: remove old deprecated Compiler API
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#5731 5724-Improve-AdditionalMethodStaterefersToLiteral
  src/Collections-Support/LookupKey.class.st
  src/Kernel/AdditionalMethodState.class.st
Labels: tests passed please review!

#5757 5723-Improve-comment-float-printing
  src/Kernel/Float.class.st
Labels: tests passed please review!

#5749 Categorize SourceFileBufferedReadWriteStreamTest
  src/Tests/SourceFileBufferedReadWriteStreamTest.class.st
Labels: tests passed please review!

#5713 Context: simplify #executedPC
  src/Debugging-Core/Context.extension.st
  src/OpalCompiler-Core/Context.extension.st
Labels: tests passed please review!

#5736 ManifestSpecTools should be ManifestSpec2Tools
  src/Spec2-Tools/ManifestSpec2Tools.class.st
Labels: tests passed please review!

#5751 Cleanup Shift-ClassBuilder-Tests
  src/Shift-ClassBuilder-Tests/ShAbstractClassBuilderTest.class.st
  src/Shift-ClassBuilder-Tests/ShCreateClassTest.class.st
  src/Shift-ClassBuilder-Tests/ShModifyClassTest.class.st
Labels: tests passed please review!

#5753 Categorize classes in Rubric-Tests
  src/Rubric-Tests/RubAbstractTextAreaTest.class.st
  src/Rubric-Tests/RubEditingAreaTest.class.st
  src/Rubric-Tests/RubFindReplaceServiceTest.class.st
  src/Rubric-Tests/RubScrolledTextMorphTest.class.st
  src/Rubric-Tests/RubSmalltalkEditorTest.class.st
Labels: tests passed please review!

#5755 [ENH] Release test for proper manifest classes
  src/ReleaseTests/ReleaseTest.class.st
Labels: tests passed please review!

#5747 Categorize classes in TraitsV2-Tests
  src/TraitsV2-Tests/T2AbstractTest.class.st
  src/TraitsV2-Tests/T2ObsoleteClassTest.class.st
  src/TraitsV2-Tests/T2OverloadingOfMethodsInTraitedClassTest.class.st
  src/TraitsV2-Tests/T2SubclassingTraitedClassTest.class.st
  src/TraitsV2-Tests/T2TraitAnnouncementsTest.class.st
  src/TraitsV2-Tests/T2TraitInTraitClassTest.class.st
  src/TraitsV2-Tests/T2TraitMCDefinitionsTest.class.st
  src/TraitsV2-Tests/T2TraitPropagatingSlotChangesTest.class.st
  src/TraitsV2-Tests/T2TraitSlotScopeTest.class.st
  src/TraitsV2-Tests/T2TraitTest.class.st
  src/TraitsV2-Tests/T2TraitWithAliasTest.class.st
  src/TraitsV2-Tests/T2TraitWithCategoriesTest.class.st
  src/TraitsV2-Tests/T2TraitWithComplexSlotsTest.class.st
  src/TraitsV2-Tests/T2TraitWithConflictsTest.class.st
  src/TraitsV2-Tests/T2TraitWithPackagesTest.class.st
  src/TraitsV2-Tests/T2TraitWithSlotsTest.class.st
  src/TraitsV2-Tests/T2UsingTraitsWithSlotsTest.class.st
Labels: tests passed please review!

#5730 2560-CairoFreetypeFontRenderer-ivar-cache-is-initialized---but-nowhere-used
  src/Athens-Cairo/CairoFreetypeFontRenderer.class.st
Labels: tests passed please review!

#5764 introduce literal method concept and use it to skip some tiime-consum…
  src/Calypso-SystemPlugins-Critic-Browser/ClyCriticDecorator.class.st
  src/Calypso-SystemQueries/CompiledMethod.extension.st
  src/Calypso-SystemTools-Core/ClyMethodCodeEditorToolMorph.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowser.class.st
Labels: tests passed please review!

#5777 Change rubMayActOnEvent to call super
  src/Rubric/TextMethodLink.extension.st
Labels: tests passed please review!

#5781 5771-Weird-black-highlighting-after-executing-commands-in-Playground
  src/FormCanvas-Core/FormCanvas.class.st
Labels: tests passed please review!

#5788 5722-LRUCache-should-have-an-explanation-of-the-API-in-the-class-comment
  src/System-Caching/LRUCache.class.st
Labels: tests passed please review!

#5784 SequenceableCollection accessing protocol - Add executable comments
  src/Collections-Abstract/SequenceableCollection.class.st
Labels: tests passed please review!

#5785 Refactoring - Add remove class keeping subclasses
  src/Calypso-SystemTools-Core/ClyBrowserMorph.extension.st
  src/Calypso-SystemTools-Core/ClySystemBrowserContext.class.st
  src/Refactoring-Core/RBNamespace.class.st
  src/Refactoring-Core/RBRemoveClassKeepingSubclassesRefactoring.class.st
  src/Refactoring-Tests-Core/RBRemoveClassKeepingSubclassesTest.class.st
  src/Refactoring-Tests-Core/RBRemoveClassTest.class.st
  src/Refactoring-Tests-Core/RBTransformationRuleTestData1.class.st
  src/Refactoring-Tests-Core/RBTransformationRuleTestData2.class.st
  src/SystemCommands-ClassCommands/SycRemoveClassKeepingSubclassesCommand.class.st
Labels: tests passed please review!

#5802 5604-improvement-fix-5603-overlayCompilerbug
  src/OpalCompiler-Core/OCExtraBindingScope.class.st
Labels: tests passed please review!

#5803 Removing-Deprecated80
  src/BaselineOfPharo/BaselineOfPharo.class.st
  src/DrTests/DrTestsPlugin.class.st
  src/Morphic-Widgets-Pluggable/ManifestMorphicWidgetsPluggable.class.st
  src/Refactoring-Environment/RBNotEnvironment.class.st
  src/Ring-Core/RGMethod.class.st
  src/Rubric/RubTextFieldArea.class.st
  src/Rubric/RubTextFieldMorph.class.st
  src/Spec-Core/TextInputFieldPresenter.class.st
  src/Spec-MorphicAdapters/MorphicTextInputFieldAdapter.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: tests passed please review!

#5773 5560-string-scanning-optimization
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core/RBScanner.class.st
Labels: tests passed please review!
