Repository pharo-project/pharo, pull requests merged in 2020-07, with the labels that each got.

#6746 delete-OCAbstractLocalVariableTOMERGE
  src/OpalCompiler-Core/OCAbstractLocalVariableTOMERGE.class.st
Labels: tests passed please review!

#6747 use-OrderedDictionary-for-copiedVars
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
Labels: tests passed please review!

#6733 Fix #6721: Do not take the completion token from the AST
  src/HeuristicCompletion-Model/CoASTHeuristicsResultSetBuilder.class.st
  src/HeuristicCompletion-Model/CoASTResultSetBuilder.class.st
  src/HeuristicCompletion-Model/CoCompletionContext.class.st
  src/HeuristicCompletion-Model/CoGlobalSorterResultSetBuilder.class.st
  src/HeuristicCompletion-Tests/CoASTResultSetBuilderTest.class.st
  src/HeuristicCompletion-Tests/CoMockEngine.class.st
  src/NECompletion-Morphic/CompletionEngine.class.st
Labels: tests passed please review!

#6749 Add variable ivar to RBVariableNode
  src/AST-Core/RBVariableNode.class.st
Labels: tests passed please review!

#6750 Speedup-RelationSlot-write
  src/Slot-Examples/RelationSlot.class.st
  src/Slot-Examples/ToOneRelationSlot.class.st
Labels: tests passed please review!

#6753 RBVariableNode-use-iVar-for-binding
  src/OpalCompiler-Core/OCASTSemanticCleaner.class.st
  src/OpalCompiler-Core/RBVariableNode.extension.st
Labels: tests passed please review!

#6756 Dictionary-move-scope-methods
  src/OpalCompiler-Tests/OCASTTranslatorTest.class.st
  src/Slot-Core/Dictionary.extension.st
  src/Slot-Core/SystemDictionary.extension.st
Labels: tests passed please review!

#6681 Introduce Collections-Weak-Tests
  src/BaselineOfKernelTests/BaselineOfKernelTests.class.st
  src/Collections-Weak-Tests/MockExceptionWithPassAction.class.st
  src/Collections-Weak-Tests/MockFinalizerAction.class.st
  src/Collections-Weak-Tests/VileFinalizer.class.st
  src/Collections-Weak-Tests/WeakIdentityKeyDictionaryTest.class.st
  src/Collections-Weak-Tests/WeakIdentitySetTest.class.st
  src/Collections-Weak-Tests/WeakIdentityValueDictionaryTest.class.st
  src/Collections-Weak-Tests/WeakKeyDictionaryTest.class.st
  src/Collections-Weak-Tests/WeakKeyToCollectionDictionaryTest.class.st
  src/Collections-Weak-Tests/WeakOrderedCollectionTest.class.st
  src/Collections-Weak-Tests/WeakRegistryTest.class.st
  src/Collections-Weak-Tests/WeakSetTest.class.st
  src/Collections-Weak-Tests/WeakValueDictionaryTest.class.st
  src/Collections-Weak-Tests/package.st
Labels: tests passed please review!

#6766 remove-unused-temporaries-in-packages-starting-with-A
  src/AST-Core-Tests/RBCommentNodeVisitorTest.class.st
  src/AST-Core-Tests/RBProgramNodeTest.class.st
  src/AST-Core/RBAbstractBlockVisitor.class.st
  src/Alien-Core/AlienWeakTable.class.st
  src/Athens-Morphic/AthensCanvasWrapper.class.st
  src/Athens-Morphic/MulticolumnLazyListMorph.extension.st
  src/Athens-Text/AthensTextRenderer.class.st
Labels: tests passed please review!

#6760 cleanup #asClassVariable on String + small cleanups
  src/ClassParser-Tests/ASTClassBuilderTest.class.st
  src/ClassParser/CDSlotNode.class.st
  src/Epicea-Tests/EpCodeChangeIntegrationTest.class.st
  src/Kernel/TemporaryVariable.class.st
  src/Reflectivity/TemporaryVariable.extension.st
  src/Slot-Core/String.extension.st
  src/Slot-Core/Symbol.extension.st
Labels: tests passed please review!

#6764 6763-ProgressBar-should-be-shifted
  src/Morphic-Base/Form.extension.st
  src/Morphic-Base/SystemProgressMorph.class.st
Labels: tests passed please review!

#6762 Fixing-Cairo-FontMetrics
  src/Athens-Cairo/CairoFontFace.class.st
  src/Athens-Cairo/CairoScaledFont.class.st
  src/FreeType/FreeTypeFace.class.st
Labels: tests passed please review!

#6739 offsetIsComment-easy-check-if-inside-comment
  src/AST-Core-Tests/RBMethodNodeTest.class.st
  src/AST-Core/RBMethodNode.class.st
Labels: tests passed please review!

#6769 remove-unused-temporaries-in-packages-starting-with-B
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
Labels: tests passed please review!

#6774 6759-Remove-Really-Old-Primitives
  src/System-Support/SmalltalkImage.class.st
  src/System-Support/VirtualMachine.class.st
Labels: tests passed please review!

#6779 6758-OrderedCollectionremoveDuplicates-is-really-long
  src/Collections-Sequenceable/OrderedCollection.class.st
  src/Collections-Tests/OrderedCollectionTest.class.st
Labels: tests passed please review!

#6715 Reduce-Interaction-Define-Method
  src/Debugger-Actions/DoesNotUnderstandDebugAction.class.st
  src/Tool-Base/AbstractTool.class.st
Labels: tests passed please review!

#6748 Expand OSWindow with additional bindings for the generic renderer
  src/Fonts-Abstract/AbstractFont.class.st
  src/Fonts-Infrastructure/LogicalFont.class.st
  src/FreeType/FreeTypeFont.class.st
  src/FreeType/GlyphForm.class.st
  src/Graphics-Display Objects/Form.class.st
  src/OSWindow-Core/OSWindowGenericRenderer.class.st
  src/OSWindow-Core/OSWindowGenericRendererScene.class.st
  src/OSWindow-Core/OSWindowNullGenericRenderer.class.st
  src/OSWindow-Core/OSWindowRendererTexture.class.st
  src/OSWindow-SDL2/AbstractFont.extension.st
  src/OSWindow-SDL2/LogicalFont.extension.st
  src/OSWindow-SDL2/OSSDL2AthensRenderer.class.st
  src/OSWindow-SDL2/OSSDL2GenericRenderer.class.st
  src/OSWindow-SDL2/OSSDL2TextureAtlasEntry.class.st
  src/OSWindow-SDL2/OSSDL2TextureAtlasFontCache.class.st
  src/OSWindow-SDL2/OSSDL2WindowRendererTexture.class.st
  src/OSWindow-SDL2/SDL2.class.st
  src/OSWindow-SDL2/SDL2Constants.class.st
  src/OSWindow-SDL2/SDL2Types.class.st
  src/OSWindow-SDL2/SDL_Renderer.class.st
  src/OSWindow-SDL2/SDL_Texture.class.st
  src/OSWindow-SDL2/SDL_Window.class.st
Labels: tests passed please review!

#6776 remove-unused-temporaries-in-packages-starting-with-K
  src/Kernel-Tests-Extended/MutexTest.class.st
  src/Kernel-Tests-Extended/ProcessTest.class.st
  src/Kernel-Tests/BlockClosureTest.class.st
  src/Kernel-Tests/DateTest.class.st
  src/Kernel-Tests/ProcessTerminateBugTest.class.st
  src/Kernel-Tests/TimespanTest.class.st
  src/Kernel/BlockClosure.class.st
Labels: tests passed please review!

#6741 Added Rewrite Basic Editor.
  src/BaselineOfRewriteTool/BaselineOfRewriteTool.class.st
  src/BaselineOfRewriteTool/package.st
  src/RewriteRule-Tests/BasicEditorTest.class.st
  src/RewriteRule-Tests/package.st
  src/RewriteRuleEditor/LoadRewriteRulePresenter.class.st
  src/RewriteRuleEditor/RewriteBasicEditorPresenter.class.st
  src/RewriteRuleEditor/RewriteRuleApplierPresenter.class.st
  src/RewriteRuleEditor/package.st
  src/RewriteRulesCreator/CustomRuleGenerator.class.st
  src/RewriteRulesCreator/DefaultRule.class.st
  src/RewriteRulesCreator/DemoRule1.class.st
  src/RewriteRulesCreator/DemoRule2.class.st
  src/RewriteRulesCreator/DemoRule3.class.st
  src/RewriteRulesCreator/ManifestRewriteToolCustomRules.class.st
  src/RewriteRulesCreator/RBCustomTransformationRule.class.st
  src/RewriteRulesCreator/package.st
Labels: tests passed please review!

#6783 TrivialClean-RBParser-use-cascade
  src/AST-Core/RBParser.class.st
Labels: tests passed please review!

#6785 Introduce-LocalVariable
  src/Debugging-Core/Context.extension.st
  src/Deprecated90/OCArgumentVariable.class.st
  src/Deprecated90/OCTempVariable.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/Slot.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/ArgumentVariable.class.st
  src/OpalCompiler-Core/LocalVariable.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCCopyingTempVariable.class.st
  src/OpalCompiler-Core/OCVectorTempVariable.class.st
  src/OpalCompiler-Core/RBVariableNode.extension.st
  src/OpalCompiler-Core/TemporaryVariable.class.st
  src/Ring-Core/RGVariable.class.st
  src/Shift-ClassBuilder/ShLayoutDefinition.class.st
  src/Slot-Tests/TemporaryVariableTest.class.st
Labels: tests passed please review!

#6782 6778-ShiftClassBuilder-does-not-recompile-SharedPool-users-when-it-changes
  src/Commander2/CmCommandGroup.class.st
  src/Shift-ClassInstaller-Tests/ShClassInstallerTest.class.st
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
Labels: tests passed please review!

#6789 Reflectivity-LiteralVariable-Cleanup
  src/Calypso-SystemPlugins-Undeclared-Queries/ClyUndeclaredEnvironmentPlugin.class.st
  src/Calypso-SystemPlugins-Undeclared-Queries/ClyUndeclaredMethodsQuery.class.st
  src/Calypso-SystemPlugins-Undeclared-Queries/CompiledMethod.extension.st
  src/Reflectivity-Tests/LinkInstallerTest.class.st
  src/Reflectivity-Tests/MetaLinkObjectAPITest.class.st
  src/Reflectivity/RFASTTranslator.class.st
  src/Reflectivity/RFClassReification.class.st
  src/Reflectivity/RFEntityReification.class.st
  src/Reflectivity/RFLinkReification.class.st
  src/Reflectivity/RFNameReification.class.st
  src/Reflectivity/RFObjectReification.class.st
  src/Reflectivity/RFThisContextReification.class.st
  src/Reflectivity/RFValueReification.class.st
  src/Reflectivity/RFVariableReification.class.st
Labels: tests passed please review!

#6781 UndefinedSlot
  src/Kernel/UndefinedSlot.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/Slot-Core/Symbol.extension.st
  src/Slot-Tests/SlotErrorsTest.class.st
  src/Slot-Tests/SlotTest.class.st
Labels: tests passed please review!

#6777 ClassVariable with #definingClass and related cleanup and refactoring
  bootstrap/src/Pharo30Bootstrap/PBClassLoader.class.st
  src/Deprecated90/Slot.extension.st
  src/Kernel/Class.class.st
  src/Kernel/ClassVariable.class.st
  src/Kernel/DuplicatedVariableError.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/Ring-Core/ClassVariable.extension.st
  src/Shift-ClassBuilder-Tests/ShAbstractClassBuilderTest.class.st
  src/Shift-ClassBuilder/ShLayoutDefinition.class.st
  src/Shift-ClassInstaller-Tests/ShClassInstallerTest.class.st
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
  src/Slot-Core/Dictionary.extension.st
  src/Slot-Examples/ExampleClassVariableWithState.class.st
  src/Slot-Tests/ExampleClassVariableTest.class.st
  src/UnifiedFFI/FFIEnumeration.class.st
  src/VariablesLibrary/AbstractInitializedClassVariable.class.st
  src/VariablesLibrary/WeakClassVariable.class.st
Labels: tests passed please review!

#6793 Removing old completion Morphs
  src/Deprecated90/SmalltalkEditingState.class.st
  src/Rubric/RubSelectorChooserMorph.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Text-Edition/SelectorChooserMorph.class.st
Labels: tests passed please review!

#6795 Update download_vm.sh: Use Pharo9 VM
  bootstrap/scripts/download_vm.sh
Labels: tests passed please review!

#6796 Update runTests.sh to use Pharo 9 vm
  bootstrap/scripts/runTests.sh
Labels: tests passed please review!

#6806 FFI-use-new-propertyAPI
  src/UnifiedFFI/CompiledMethod.extension.st
  src/UnifiedFFI/FFICalloutAPI.class.st
  src/UnifiedFFI/FFIMethodRegistry.class.st
Labels: tests passed please review!

#6767 [Disable Flaky Tests] Disable continuation flaky test
  src/Kernel-Tests/ContinuationTest.class.st
Labels: tests passed please review!

#6815 6008-Two-methods-to-test-if-a-node-is-an-argument
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyVariableBreakpointCommand.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/ArgumentVariable.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/RBVariableNode.extension.st
  src/OpalCompiler-Tests/OCASTClosureAnalyzerTest.class.st
  src/Ring-Core/RGVariable.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#6813 6811-Block-arguments-and-local-should-be-used-to-solve-unresolved-variables
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
Labels: tests passed please review!

#6809 cleanup-OldSendsDeprecatedMethodToGlobalRule
  src/Kernel-Rules/OldSendsDeprecatedMethodToGlobalRule.class.st
  src/Refactoring-Critics/PharoCriticRules.class.st
Labels: tests passed please review!

#6816 Speedup-class-removal
  src/GeneralRules/ReGlobalVariablesUsageRule.class.st
  src/Kernel/Class.class.st
  src/Kernel/LiteralVariable.class.st
  src/System-Support/SmalltalkImage.class.st
Labels: tests passed please review!

#6804 Compiler-DeadCode-Clean
  src/OpalCompiler-Core/OCLiteralList.class.st
  src/OpalCompiler-Core/SequenceableCollection.extension.st
  src/OpalCompiler-Core/Symbol.extension.st
  src/OpalCompiler-Core/UndefinedObject.extension.st
Labels: tests passed please review!

#6819 Monticello-support-UndefinedSlot
  src/Monticello/MCClassDefinition.class.st
Labels: tests passed please review!

#6814 AST-deprecate-methodComments
  src/AST-Core/RBMethodNode.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBSequenceNode.class.st
  src/Deprecated90/RBMethodNode.extension.st
  src/Deprecated90/RBProgramNode.extension.st
  src/Deprecated90/RBSequenceNode.extension.st
Labels: tests passed please review!

#6805 Variables-isGlobal-Cleanup
  src/Kernel/GlobalVariable.class.st
  src/Kernel/LiteralVariable.class.st
  src/Kernel/UndeclaredVariable.class.st
  src/OpalCompiler-Core/RBVariableNode.extension.st
  src/Reflectivity/RFOperationReification.class.st
  src/Reflectivity/RFValueReification.class.st
Labels: tests passed please review!

#6823 Fix-LocalVariable-astNodes
  src/OpalCompiler-Core/LocalVariable.class.st
Labels: tests passed please review!

#6798 Improve-MetaLinks-onVariables
  src/Reflectivity-Tests/ReflectivityControlTest.class.st
  src/Reflectivity-Tests/ReflectivityReificationTest.class.st
  src/Reflectivity/RFASTTranslator.class.st
  src/Reflectivity/RFSemanticAnalyzer.class.st
  src/Reflectivity/Variable.extension.st
Labels: tests passed please review!

#6810 FixFailingDocComments
  src/Collections-Strings/ByteString.class.st
  src/Collections-Strings/ByteSymbol.class.st
  src/Collections-Strings/String.class.st
  src/Kernel/Object.class.st
  src/PharoDocComment/RBMethodNode.extension.st
Labels: tests passed please review!

#6799 6092-Fleaky-Reflectivity-test
  src/AST-Core/RBMethodNode.class.st
Labels: tests passed please review!

#6807 3072-ComputedSlots-break-accessor-generation
  src/SystemCommands-VariableCommands/InstanceVariableSlot.extension.st
  src/SystemCommands-VariableCommands/Slot.extension.st
Labels: tests passed please review!

#6833 Speedup-pharoDocCommentNodes
  src/AST-Core/RBComment.class.st
  src/PharoDocComment/DocCommentIconStyler.class.st
  src/PharoDocComment/RBComment.extension.st
Labels: tests passed please review!

#6837 6835-Remove-printHierarchy-methods
  src/Kernel-Tests/ClassDescriptionTest.class.st
  src/Kernel/Behavior.class.st
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#6848 3236-isInstance-is-not-consistent-with-isClassVariable
  src/AST-Core/RBInstanceVariableNode.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBVariableNode.class.st
  src/Calypso-Ring/RGMethod.extension.st
  src/Calypso-SystemTools-Core/ClySourceCodeContext.class.st
  src/ClassParser-Tests/CDExistingClassDefinitionTest.class.st
  src/ClassParser/CDSharedVariableNode.class.st
  src/ClassParser/CDSlotNode.class.st
  src/GeneralRules/ReTestCaseShouldNotUseInitializeRule.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/RBVariableNode.extension.st
  src/OpalCompiler-Tests/OCASTCheckerTest.class.st
  src/Reflectivity/RFOperationReification.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#6831 MoreSmallRulesCleanups
  src/GT-Inspector/ClassDescription.extension.st
  src/GT-Inspector/ReAbstractCritique.extension.st
  src/GT-Inspector/ReIntervalSourceAnchor.extension.st
  src/GT-Inspector/ReProperty.extension.st
  src/GT-Inspector/ReSearchStringSourceAnchor.extension.st
  src/GT-Inspector/ReSourceAnchor.extension.st
  src/GT-Spotter/GTSpotterExtensionSettings.class.st
  src/GT-Spotter/Object.extension.st
  src/GeneralRules-Tests/ReSmalllintTest.class.st
  src/GeneralRules/ReAnySatisfyRule.class.st
  src/GeneralRules/ReMissingSubclassResponsibilityRule.class.st
  src/GeneralRules/ReNoClassCommentRule.class.st
  src/GeneralRules/ReSendsMethodDictRule.class.st
  src/GeneralRules/ReSuperSendsNewRule.class.st
  src/GeneralRules/ReTemporaryVariableCapitalizationRule.class.st
  src/GeneralRules/ReUncommonMessageSendRule.class.st
  src/GeneralRules/ReUsesTrueRule.class.st
  src/GeneralRules/ReUtilityMethodsRule.class.st
  src/Kernel-Tests-Rules/SendsDeprecatedMethodToGlobalRuleTest.class.st
  src/Refactoring-Tests-Critics/RBSmalllintTestObject.class.st
  src/Renraku/ClassDescription.extension.st
  src/Renraku/CompiledMethod.extension.st
  src/Renraku/ManifestRenraku.class.st
  src/Renraku/Object.extension.st
  src/Renraku/RBProgramNode.extension.st
  src/Renraku/RGMethodDefinition.extension.st
  src/Renraku/RPackage.extension.st
  src/Renraku/ReSettings.class.st
Labels: tests passed please review!

#6825 Simplify-MetalinkTargetResolver-resolvingBlocForOption
  src/Reflectivity/MetaLinkInstaller.class.st
  src/Reflectivity/MetalinkTargetResolver.class.st
  src/Reflectivity/Variable.extension.st
Labels: tests passed please review!

#6869 remove-PharoCriticRules
  src/Refactoring-Critics/PharoCriticRules.class.st
  src/Tool-CriticBrowser/SelectRuleBrowser.class.st
Labels: tests passed please review!

#6868 speedup-ReVariableReferencedOnceRule
  src/GeneralRules/ReVariableReferencedOnceRule.class.st
Labels: tests passed please review!

#6867 simplify-ReTemporaryNeitherReadNorWrittenRule
  src/GeneralRules/ReTemporaryNeitherReadNorWrittenRule.class.st
Labels: tests passed please review!

#6866 simplify-ReIvarNeitherReadNorWrittenRule
  src/GeneralRules/ReIvarNeitherReadNorWrittenRule.class.st
Labels: tests passed please review!

#6865 AST-cleanup-isArgument
  src/AST-Core/RBArgumentNode.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBVariableNode.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVarAccessCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVarWritesCommand.class.st
  src/Calypso-SystemTools-Core/ClySourceCodeContext.class.st
  src/NECompletion/RBVariableNode.extension.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/RBVariableNode.extension.st
  src/OpalCompiler-Tests/OCASTClosureAnalyzerTest.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#6870 Rulescleanup-asRBRule
  src/Refactoring-Critics/RBLintRule.class.st
  src/Refactoring-Critics/RBRenrakuWrapperLintRule.class.st
  src/Renraku/ReAbstractRule.class.st
Labels: tests passed please review!

#6856 6817-testUnixRandomGeneratorSeed-run-on-Linux-CI-takes-nearly-3-minutes
  src/Random-Tests/RandomTest.class.st
Labels: tests passed please review!

#6861 Add "Open in native file browser" also to inspectors for file references
  src/GT-InspectorExtensions-Core/AbstractFileReference.extension.st
  src/Glamour-Morphic-Theme/GLMUIThemeExtraIcons.class.st
Labels: tests passed please review!

#6857 6836-DefinitionForNautilus-is-deprecated-so-we-should-remove-it-
  src/Kernel/Class.class.st
  src/Kernel/ClassDescription.class.st
  src/Ring-Core/RGBehavior.class.st
  src/Ring-Tests-Core/RGClassStrategyTest.class.st
Labels: tests passed please review!

#6875 ReTemporaryVariableCapitalizationRule-check-Args
  src/GeneralRules/ReTemporaryVariableCapitalizationRule.class.st
Labels: tests passed please review!

#6854 Daily-Trivials-2020-07-15
  src/Athens-Morphic/AthensTextMorph.class.st
  src/Kernel-Tests-Extended/ClassTest.class.st
  src/Kernel/Behavior.class.st
  src/Ring-Definitions-Core/RPackage.extension.st
  src/Ring-Definitions-Core/RPackageSet.extension.st
  src/TraitsV2/Behavior.extension.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: tests passed please review!

#6864 Introduce Collections-Streams-Tests
  src/BaselineOfKernelTests/BaselineOfKernelTests.class.st
  src/Collections-Streams-Tests/GeneratorTest.class.st
  src/Collections-Streams-Tests/LimitedWriteStreamTest.class.st
  src/Collections-Streams-Tests/NullStreamTest.class.st
  src/Collections-Streams-Tests/ReadStreamTest.class.st
  src/Collections-Streams-Tests/ReadWriteStreamTest.class.st
  src/Collections-Streams-Tests/StreamBugsTest.class.st
  src/Collections-Streams-Tests/WriteStreamTest.class.st
  src/Collections-Streams-Tests/package.st
Labels: tests passed please review!

#6844 6838-Reduce-Squeak-mentions
  src/Athens-Cairo/AthensCairoSurface.class.st
  src/Collections-Atomic-Tests/FIFOQueueTest.class.st
  src/Collections-Atomic-Tests/LIFOQueueTest.class.st
  src/Collections-Tests/SharedQueueTest.class.st
  src/Collections-Unordered-Tests/DictionaryTest.class.st
  src/Compression/CompiledMethodTrailer.extension.st
  src/Compression/GZipReadStream.class.st
  src/Compression/ZipFileMember.class.st
  src/FileSystem-Disk/DiskStore.class.st
  src/Files/AsyncFile.class.st
  src/Fuel-Tests-Core/FLHashedCollectionSerializationTest.class.st
  src/GeneralRules-Tests/ReSmalllintTest.class.st
  src/Glamour-Helpers/BlockClosure.extension.st
  src/Glamour-Helpers/MessageSend.extension.st
  src/Graphics-Display Objects/Form.class.st
  src/HelpSystem-Core/HelpHowToHelpTopics.class.st
  src/Kernel-Chronology-Extras/DateAndTime.extension.st
  src/Kernel-Chronology-Extras/Integer.extension.st
  src/Kernel-Tests-Extended/DelayTest.extension.st
  src/Kernel-Tests-Extended/FloatTest.extension.st
  src/Kernel-Tests/FloatTest.class.st
  src/Kernel/DateAndTime.class.st
  src/Kernel/DelayMicrosecondTicker.class.st
  src/Kernel/Float.class.st
  src/Kernel/Time.class.st
  src/Kernel/Timespan.class.st
  src/Metacello-Base/Metacello.class.st
  src/Metacello-ProfStef/MetacelloConfigurationTutorialPart1.class.st
  src/MonticelloRemoteRepositories/MCFtpRepository.class.st
  src/MonticelloRemoteRepositories/MCGemstoneRepository.class.st
  src/MonticelloRemoteRepositories/MCSmalltalkhubRepository.class.st
  src/MonticelloRemoteRepositories/MCSqueaksourceRepository.class.st
  src/Morphic-Core/WorldState.class.st
  src/Morphic-Tests/PolygonMorphTest.class.st
  src/Morphic-Widgets-Basic/PluggableButtonMorph.class.st
  src/Network-Kernel/NetNameResolver.class.st
  src/Refactoring2-Transformations-Tests/RBBasicDummyLintRuleTest.class.st
  src/Ring-Core/RGStampParser.class.st
  src/Ring-Definitions-Core/RGElementDefinition.class.st
  src/Rubric/RubTextStopConditions.class.st
  src/System-Support/SmalltalkImage.class.st
  src/System-Support/VirtualMachine.class.st
Labels: tests passed please review!

#6871 CompiledCode-useLiteralAt
  src/Kernel/CompiledCode.class.st
Labels: tests passed please review!

#6873 Variables-SmallCleanups
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBVariableNode.class.st
  src/Calypso-Ring/RGMethod.extension.st
  src/Calypso-SystemTools-Core/ClySourceCodeContext.class.st
  src/GeneralRules-Tests/ReSuperWithoutSendTest.class.st
  src/Kernel/Behavior.class.st
  src/Kernel/Slot.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/ArgumentVariable.class.st
  src/OpalCompiler-Core/LocalVariable.class.st
  src/OpalCompiler-Core/RBVariableNode.extension.st
  src/OpalCompiler-Core/TemporaryVariable.class.st
  src/Slot-Tests/ArgumentVariableTest.class.st
  src/Slot-Tests/TemporaryVariableTest.class.st
  src/System-Support/Class.extension.st
  src/VariablesLibrary/ObservableSlot.class.st
  src/VariablesLibrary/Slot.extension.st
  src/VariablesLibrary/TObservable.trait.st
Labels: tests passed please review!

#6880 reduce-usage-RBVariableNode-subclasses
  src/AST-Core-Tests/RBDumpVisitorTest.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser-Tests/ClyInstallMetaLinkPresenterTest.class.st
  src/OpalCompiler-Tests/OCVariableSpecialisationTest.class.st
  src/Reflectivity/RFArgumentsReification.class.st
  src/Reflectivity/RFMethodToExecuteReification.class.st
  src/Reflectivity/RFNewValueReification.class.st
  src/Reflectivity/RFOperationReification.class.st
  src/Reflectivity/RFReceiverReification.class.st
  src/Reflectivity/RFValueReification.class.st
Labels: tests passed please review!

#6874 ReRuleManager-cleanups-related-to-enabled
  src/Refactoring-Critics/RBLintRule.class.st
  src/Renraku/ReImageRuleBaner.class.st
  src/Renraku/ReRuleManager.class.st
Labels: tests passed please review!

#6876 ReReferencesObsoleteClassRule
  src/GeneralRules/ReGlobalVariablesUsageRule.class.st
  src/GeneralRules/ReReferencesObsoleteClassRule.class.st
  src/Kernel/LiteralVariable.class.st
Labels: tests passed please review!

#6765 willCreateBlock-support-fullBlock
  src/Debugger-Tests/AssignmentAndLiteralDebuggerTest.class.st
  src/Debugger-Tests/DebuggerTest.class.st
  src/Debugging-Core/InstructionStream.extension.st
  src/Kernel-BytecodeEncoders/EncoderForSistaV1.class.st
  src/Kernel-BytecodeEncoders/EncoderForV3PlusClosures.class.st
Labels: tests passed please review!

#6887 Variables-CopiedArgs
  src/OpalCompiler-Core/ArgumentVariable.class.st
  src/OpalCompiler-Core/LocalVariable.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCCopyingArgumentVariable.class.st
  src/OpalCompiler-Core/TemporaryVariable.class.st
Labels: tests passed please review!

#6889 Rules-Cleanup-excludedRuleNames
  src/GeneralRules/ReImplementedNotSentRule.class.st
  src/Renraku/ReRuleManager.class.st
Labels: tests passed please review!

#6894 6890-Variablevariable-is-deprecated
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel/Class.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/InstanceVariableSlot.class.st
  src/Kernel/Slot.class.st
  src/Kernel/UndefinedObject.class.st
  src/OpalCompiler-Core/OCCopyingArgumentVariable.class.st
  src/OpalCompiler-Core/OCCopyingTempVariable.class.st
  src/OpalCompiler-Core/TemporaryVariable.class.st
  src/OpalCompiler-Tests/OCVariableSpecialisationTest.class.st
  src/Slot-Tests/ArgumentVariableTest.class.st
  src/Slot-Tests/TemporaryVariableTest.class.st
Labels: tests passed please review!

#6882 unify-isAccessedIn-isReferencedIn
  src/Calypso-SystemQueries/ClyVariable.class.st
  src/Calypso-SystemQueries/ClyVariableReferencesQuery.class.st
  src/Kernel/LiteralVariable.class.st
  src/Ring-Core/RGBehavior.class.st
Labels: tests passed please review!

#6900 Introduce Collections-Support-Tests
  src/BaselineOfKernelTests/BaselineOfKernelTests.class.st
  src/Collections-Support-Tests/AssociationTest.class.st
  src/Collections-Support-Tests/CharacterSetTest.class.st
  src/Collections-Support-Tests/CollectionTest.class.st
  src/Collections-Support-Tests/WideCharacterSetTest.class.st
  src/Collections-Support-Tests/package.st
Labels: tests passed please review!

#6917 Simplify initializeCommandLineHandlerAndErrorHandling for default UI …
  src/PharoBootstrap-Initialization/PharoBootstrapInitialization.class.st
Labels: tests passed please review!

#6913 if we implement enabeld: in ReImplementedNotSentRule, we can now even…
  src/GeneralRules/ReImplementedNotSentRule.class.st
Labels: tests passed please review!

#6922 Variables-deprecate-isGlobal
  src/AST-Core-Tests/RBDumpVisitorTest.class.st
  src/AST-Core/RBGlobalNode.class.st
  src/AST-Core/RBVariableNode.class.st
  src/ClassParser/CDClassDefinitionParser.class.st
  src/Deprecated90/RBVariableNode.extension.st
  src/GeneralRules/ReReferencesObsoleteClassRule.class.st
  src/GeneralRules/ReRefersToClassRule.class.st
  src/GeneralRules/ReUsesTrueRule.class.st
  src/GeneralRules/ReUsesWorldGlobalRule.class.st
  src/Kernel-Rules/FloatReferencesRule.class.st
  src/OpalCompiler-Core/LocalVariable.class.st
  src/OpalCompiler-Core/RBVariableNode.extension.st
  src/Refactoring-Core/RBCondition.class.st
  src/Reflectivity/Variable.extension.st
  src/Ring-Core/RGBehavior.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#6927 Global-and-Class-Var-add-scope
  src/Kernel/GlobalVariable.class.st
  src/Kernel/LiteralVariable.class.st
  src/Slot-Tests/ClassVariableTest.class.st
  src/Slot-Tests/GlobalVariableTest.class.st
  src/Slot-Tests/TemporaryVariableTest.class.st
Labels: tests passed please review!

#6925 Variable-accessesRef-cleanup
  src/Calypso-SystemQueries/ClyVariable.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/LiteralVariable.class.st
Labels: tests passed please review!

#6923 merge-numberOfReservedLiterals-literalsToSkip
  src/Kernel/CompiledBlock.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#6912 Supervar-use-sendsToSuper
  src/Kernel/Behavior.class.st
  src/OpalCompiler-Core/SuperVariable.class.st
Labels: tests passed please review!

#6924 simplify-hasReportableSlip
  src/System-Changes/ChangeSet.class.st
Labels: tests passed please review!

#6901 Improving debugger infrastructure step 1: a Trait to unify the debugger API used by the system to open debuggers
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/Debugger-Filters-Tests/FilterTest.class.st
  src/Debugger-Filters-Tests/package.st
  src/Debugger-Model-Tests/AssignmentAndLiteralDebuggerTest.class.st
  src/Debugger-Model-Tests/DebugSessionContexts2Test.class.st
  src/Debugger-Model-Tests/DebugSessionContextsTest.class.st
  src/Debugger-Model-Tests/DebuggerModelTest.class.st
  src/Debugger-Model-Tests/DebuggerTest.class.st
  src/Debugger-Model-Tests/DynamicMessageImplementorTest.class.st
  src/Debugger-Model-Tests/ErrorWasInUIProcessTest.class.st
  src/Debugger-Model-Tests/IsContextPostMortemTest.class.st
  src/Debugger-Model-Tests/MyHalt.class.st
  src/Debugger-Model-Tests/RestartTest.class.st
  src/Debugger-Model-Tests/StepIntoTest.class.st
  src/Debugger-Model-Tests/StepOverTest.class.st
  src/Debugger-Model-Tests/StepThroughTest.class.st
  src/Debugger-Model-Tests/TDebuggerTest.class.st
  src/Debugger-Model-Tests/package.st
  src/Debugger-Model/DebugContext.class.st
  src/Debugger-Model/DebugSession.class.st
  src/Debugger-Model/DebuggerSettings.class.st
  src/Debugger-Model/TDebugger.trait.st
  src/Debugger-Tests/package.st
Labels: debugger, tests passed please review!

#6911 Proper initialization of TraceEvents in OSWindow
  src/OSWindow-Core/OSWindow.class.st
  src/OSWindow-Tests/OSWindowTest.class.st
Labels: tests passed please review!

#6916 Cleanups in OSSDL2BackendWindow
  src/OSWindow-SDL2/ManifestOSWindowSDL2.class.st
  src/OSWindow-SDL2/OSSDL2BackendWindow.class.st
Labels: tests passed please review!

#6931 executeRenameRefactoringBy-move-to-Variable
  src/NautilusRefactoring/ClassVariable.extension.st
  src/NautilusRefactoring/GlobalVariable.extension.st
  src/NautilusRefactoring/LocalVariable.extension.st
  src/NautilusRefactoring/RBArgumentNode.extension.st
  src/NautilusRefactoring/RBGlobalNode.extension.st
  src/NautilusRefactoring/RBInstanceVariableNode.extension.st
  src/NautilusRefactoring/RBTemporaryNode.extension.st
  src/NautilusRefactoring/RBVariableNode.extension.st
  src/NautilusRefactoring/Slot.extension.st
Labels: tests passed please review!

#6930 Variable-isSelf-isSuper-deprecation
  src/Deprecated90/OCSelfVariable.class.st
  src/Deprecated90/OCSuperVariable.class.st
  src/Deprecated90/Variable.extension.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/SelfVariable.class.st
  src/OpalCompiler-Core/SuperVariable.class.st
  src/OpalCompiler-Tests/OCASTCheckerTest.class.st
Labels: tests passed please review!

#6926 Variables-isBlockVar-via-Variable
  src/AST-Core/RBArgumentNode.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBTemporaryNode.class.st
  src/AST-Core/RBVariableNode.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#6934 Make RBComment a subclass of RBProgramNode
  src/AST-Core/RBComment.class.st
Labels: tests passed please review!

#6935 Variables-isReferenced-cleanup
  src/Kernel/Behavior.class.st
  src/Kernel/ClassVariable.class.st
  src/Kernel/LiteralVariable.class.st
  src/Kernel/Metaclass.class.st
  src/Kernel/Slot.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/LocalVariable.class.st
Labels: tests passed please review!

#6936 ReImplementedNotSentRule-tellmeMore
  src/GeneralRules/ReInconsistentMethodClassificationRule.class.st
Labels: tests passed please review!

#6942 Compiler-OCAbstractMethodScope-push-node-down
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCAbstractScope.class.st
Labels: tests passed please review!

#6947 6943-Syntax-highlighter-doesnt-like-blocks-with-arguments
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#6948 RBComment-cleanup
  src/AST-Core/RBComment.class.st
Labels: tests passed please review!

#6955 6953-Contextual-menu-on-a-class-Variable-in-the-browser-is-bugged
  src/Calypso-SystemTools-Core/ClySourceCodeContext.class.st
Labels: tests passed please review!

#6950 SyntaxHighLight-test-argstyling
  src/Shout-Tests/SHRBTextStylerTest.class.st
Labels: tests passed please review!

#6929 CompiledCode-refersToLiteral
  src/Kernel/CompiledBlock.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#6888 simplify-ReVariableAssignedLiteralRule
  src/GeneralRules/ReVariableAssignedLiteralRule.class.st
Labels: tests passed please review!

#6933 Variables Refactoring: isSelfVariable-Part2
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core/RBMessageNode.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBThisContextNode.class.st
  src/AST-Core/RBVariableNode.class.st
  src/Debugger-Model-Tests/StepOverTest.class.st
  src/Debugger-Model-Tests/StepThroughTest.class.st
  src/Deprecated90/OCThisContextVariable.class.st
  src/Deprecated90/RBProgramNode.extension.st
  src/Deprecated90/Variable.extension.st
  src/GeneralRules/ReCollectionMessagesToExternalObjectRule.class.st
  src/GeneralRules/ReReturnsBooleanAndOtherRule.class.st
  src/GeneralRules/ReSuperWithoutSend.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/ThisContextVariable.class.st
  src/OpalCompiler-Tests/OCASTCheckerTest.class.st
  src/Refactoring-Core/RBInlineMethodRefactoring.class.st
  src/Reflectivity/MetaLinkInstaller.class.st
Labels: tests passed please review!

#6921 simplify-ReAddRemoveDependentsRule
  src/GeneralRules/ReAddRemoveDependentsRule.class.st
Labels: tests passed please review!

#6971 Fix-Failing-ReSmalllintTest
  src/GeneralRules/ReAddRemoveDependentsRule.class.st
Labels: tests passed please review!

#6969 accessesRef-test-andspeedup
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/Kernel/CompiledCode.class.st
Labels: tests passed please review!

#6941 6821-BlockClosureTest-should-not-compare-string-but-use-the-dumpVisitor
  src/Kernel-Tests/BlockClosureTest.class.st
Labels: tests passed please review!

#6966 6965-speedup-senders-of-hasSelectorspecialSelectorIndex-check-too-much
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/Kernel/CompiledCode.class.st
Labels: tests passed please review!

#6982 Use #do: in testCollectCreatesANewMatrix
  src/Collections-Tests/Array2DTest.class.st
Labels: tests passed please review!

#6983 6905-Can-we-merge-System-Hashing-Tests-and-System-Hashing-Testing
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/System-Hashing-Testing/DigitalSignatureAlgorithm.extension.st
  src/System-Hashing-Testing/ManifestSystemHashingTesting.class.st
  src/System-Hashing/DigitalSignatureAlgorithm.class.st
Labels: tests passed please review!

#6988 ThisContextVariable-fast-usingMethods
  src/Kernel-BytecodeEncoders/EncoderForSistaV1.class.st
  src/Kernel-BytecodeEncoders/EncoderForV3PlusClosures.class.st
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/CompiledMethod.class.st
  src/OpalCompiler-Core/SelfVariable.class.st
  src/OpalCompiler-Core/SuperVariable.class.st
  src/OpalCompiler-Core/ThisContextVariable.class.st
Labels: tests passed please review!

#6980 Athens Cleanups
  src/Athens-Core/AthensAbstractShape.class.st
  src/Athens-Core/AthensAffineTransform.class.st
  src/Athens-Core/AthensBezier3Scene.class.st
  src/Athens-Core/AthensBezierConverter.class.st
  src/Athens-Core/AthensCanvas.class.st
  src/Athens-Core/AthensCubicBezier.class.st
  src/Athens-Core/AthensCubicSegment.class.st
  src/Athens-Core/AthensPaintMode.class.st
  src/Athens-Core/AthensPathBuilder.class.st
  src/Athens-Core/AthensPathSegment.class.st
  src/Athens-Core/AthensShadowPaint.class.st
  src/Athens-Core/AthensSimplePathBuilder.class.st
  src/Athens-Core/AthensStrokePaint.class.st
  src/Athens-Core/AthensTransform.class.st
  src/Athens-Core/GradientPaint.class.st
  src/Athens-Core/LinearGradientPaint.class.st
  src/Athens-Morphic/AthensCanvas.extension.st
Labels: tests passed please review!

#6989 Tests-hasLiteral-hasLiteralSuchThat
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#6990 Reduce-References-RBVariableNode-subclasses2
  src/AST-Core/RBSequenceNode.class.st
  src/AST-Core/RBVariableNode.class.st
  src/Flashback-Decompiler/FBDASTBuilder.class.st
  src/Flashback-Decompiler/FBDDecompiler.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/Reflectivity/RFThisContextReification.class.st
  src/Reflectivity/ReflectiveMethod.class.st
Labels: tests passed please review!

#7000 RBLintRule-enabledSettingID
  src/Refactoring-Critics/RBLintRule.class.st
Labels: tests passed please review!

#7002 merge-spec2-0.7.2
  src/Spec2-Adapters-Morphic/SpDialogWindow.class.st
  src/Spec2-Adapters-Morphic/SpMorphicBoxAdapter.class.st
  src/Spec2-Adapters-Morphic/SpMorphicDialogWindowAdapter.class.st
  src/Spec2-Adapters-Morphic/SpMorphicLayoutAdapter.class.st
  src/Spec2-Adapters-Morphic/SpMorphicMillerAdapter.class.st
  src/Spec2-Adapters-Morphic/SpMorphicTableCellBuilder.class.st
  src/Spec2-Adapters-Morphic/SpMorphicTableColumn.class.st
  src/Spec2-Adapters-Morphic/SpMorphicTableDataSource.class.st
  src/Spec2-Adapters-Morphic/SpMorphicTextAdapter.class.st
  src/Spec2-Adapters-Morphic/SpMorphicWindowAdapter.class.st
  src/Spec2-Adapters-Morphic/SpTMorphicTableDataSourceCommons.trait.st
  src/Spec2-Backend-Tests/SpBoxLayoutAdapterTest.class.st
  src/Spec2-Code/SpCodePopoverErrorPresenter.class.st
  src/Spec2-Code/SpCodePopoverPrintPresenter.class.st
  src/Spec2-Core/OrderedDictionary.extension.st
  src/Spec2-Core/SpApplication.class.st
  src/Spec2-Core/SpApplicationBackend.class.st
  src/Spec2-Core/SpDialogWindowPresenter.class.st
  src/Spec2-Core/SpDynamicPresenter.class.st
  src/Spec2-Core/SpRichTextPresenter.class.st
  src/Spec2-Core/SpTextPresenter.class.st
  src/Spec2-Core/SpWindowPresenter.class.st
  src/Spec2-Examples/SpBoxLayoutReplacePresenterExample.class.st
  src/Spec2-Layout/SpBoxLayout.class.st
  src/Spec2-Layout/SpExecutableLayout.class.st
  src/Spec2-Tests/SpBoxLayoutTest.class.st
Labels: tests passed please review!

#6967 ReUtilityMethodsRule-speedup-and-test
  src/GeneralRules-Tests/ReUtilityMethodsRuleTest.class.st
  src/GeneralRules/ReUtilityMethodsRule.class.st
Labels: tests passed please review!

#7007 Cleanup-kindOfSubclassDefinitionString
  src/Calypso-Ring/RGByteLayout.extension.st
  src/Calypso-Ring/RGCompiledMethodLayout.extension.st
  src/Calypso-Ring/RGEphemeronLayout.extension.st
  src/Calypso-Ring/RGFixedLayout.extension.st
  src/Calypso-Ring/RGImmediateLayout.extension.st
  src/Calypso-Ring/RGVariableLayout.extension.st
  src/Calypso-Ring/RGWeakLayout.extension.st
  src/Calypso-Ring/RGWordLayout.extension.st
Labels: tests passed please review!

#7010 Improving Taskit Execution time
  src/TaskIt-Tests/TKTTestCase.class.st
Labels: tests passed please review!

#7009 6751-Syntactically-wrong-code-can-be-compiled-without-Error
  src/Kernel/RuntimeSyntaxError.class.st
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/Tool-Finder/Finder.class.st
Labels: tests passed please review!

#7006 Variables-definedVariables-tests
  src/Debugging-Core/Context.extension.st
  src/Kernel-Tests/BehaviorTest.class.st
  src/Kernel/Behavior.class.st
  src/Manifest-Core/TheManifestBuilder.class.st
  src/Slot-Examples/DerivedSlot.class.st
Labels: tests passed please review!

#7005 PDF and SVG cairo exporters: do not require garbage collection to flush the file
  src/Athens-Cairo-Tests/AthensCairoExportSurfaceTest.class.st
  src/Athens-Cairo-Tests/AthensCairoPDFSurfaceExportTest.class.st
  src/Athens-Cairo-Tests/AthensCairoPDFSurfaceTest.class.st
  src/Athens-Cairo-Tests/AthensCairoSVGSurfaceExportTest.class.st
  src/Athens-Cairo-Tests/AthensCairoSVGSurfaceTest.class.st
  src/Athens-Cairo/AthensCairoExportSurface.class.st
  src/Athens-Cairo/AthensCairoPDFSurface.class.st
  src/Athens-Cairo/AthensCairoSVGSurface.class.st
  src/Athens-Cairo/AthensCairoSurface.class.st
Labels: tests passed please review!

#7011 Merge NewTools v0.4.2.1 with debugger fixes
  src/NewTools-Core/StPharoSettings.class.st
  src/NewTools-Debugger-Breakpoints-Tools/StHaltAndBreakpointControlTest.class.st
  src/NewTools-Debugger-Breakpoints-Tools/StHaltCache.class.st
  src/NewTools-Debugger-Breakpoints-Tools/StHaltCacheTest.class.st
  src/NewTools-Debugger-Tests/StDebuggerTest.class.st
  src/NewTools-Debugger/StDebugger.class.st
  src/NewTools-Debugger/StDebuggerActionModel.class.st
  src/NewTools-Inspector/StMetaBrowser.class.st
  src/NewTools-Inspector/StRawInspection.class.st
  src/NewTools-Playground/StPlayground.class.st
Labels: tests passed please review!

#6999 Ring2-Compatibility-isVariable
  src/Ring-Core/RGInstanceVariableSlot.class.st
  src/Ring-Core/RGSlot.class.st
  src/Ring-Core/RGVariable.class.st
Labels: tests passed please review!

#6978 ReInconsistentMethodClassificationRule-add-repair
  src/GeneralRules/ReInconsistentMethodClassificationRule.class.st
  src/Refactoring2-Transformations/RBTransformation.class.st
Labels: tests passed please review!

#6975 Introduce Collections-Strings-Tests
  src/BaselineOfKernelTests/BaselineOfKernelTests.class.st
  src/Collections-Strings-Tests/ByteSymbolTest.class.st
  src/Collections-Strings-Tests/CharacterTest.class.st
  src/Collections-Strings-Tests/StringInitializationTest.class.st
  src/Collections-Strings-Tests/StringLineEndingsTest.class.st
  src/Collections-Strings-Tests/StringTest.class.st
  src/Collections-Strings-Tests/SymbolTest.class.st
  src/Collections-Strings-Tests/WideStringTest.class.st
  src/Collections-Strings-Tests/package.st
Labels: tests passed please review!

#7019 Changing defaults to retain blanks
  src/AST-Core-Tests/RBDumpVisitorTest.class.st
  src/EnlumineurFormatter/EFContext.class.st
  src/EnlumineurFormatter/EFFormatter.class.st
Labels: tests passed please review!

#7024 Fix #7023
  src/Debugging-Core/Context.extension.st
  src/Kernel-Tests-WithCompiler/ContextTest.extension.st
Labels: tests passed please review!

#7016 ReservedVariable-nameIsReserved-and-Test
  src/OpalCompiler-Core/ReservedVariable.class.st
  src/Slot-Tests/ReservedVariableTest.class.st
Labels: easyReview, tests passed please review!

#7014 isFaulty-useBlocksWithAnySatisFy
  src/AST-Core/RBArrayNode.class.st
  src/AST-Core/RBBlockNode.class.st
  src/AST-Core/RBCascadeNode.class.st
  src/AST-Core/RBLiteralArrayNode.class.st
  src/AST-Core/RBMessageNode.class.st
  src/AST-Core/RBMethodNode.class.st
  src/AST-Core/RBPragmaNode.class.st
  src/AST-Core/RBSequenceNode.class.st
Labels: easyReview, tests passed please review!

#7026 6952 debugger line location is uncorrect when using a breakonce
  src/NewTools-Debugger-Breakpoints-Tools/StHaltAndBreakpointController.class.st
  src/Reflectivity-Tests/MetaLinkTest.class.st
  src/Reflectivity-Tests/ReflectivityControlTest.class.st
  src/Reflectivity-Tools-Tests/BreakpointTest.class.st
  src/Reflectivity-Tools/BreakpointIconStyler.class.st
  src/Reflectivity-Tools/MetaLinkIconStyler.class.st
  src/Reflectivity-VariableBreakpoint/RBVariableNode.extension.st
  src/Reflectivity-VariableBreakpoint/VariableBreakpoint.class.st
  src/Reflectivity-VariableBreakpoint/VariableBreakpointTest.class.st
  src/Reflectivity/Break.class.st
  src/Reflectivity/Breakpoint.class.st
  src/Reflectivity/HookGenerator.class.st
  src/Reflectivity/RBProgramNode.extension.st
Labels: tests passed please review!
