Repository pharo-project/pharo, pull requests merged in 2020-04, with the labels that each got.

#5974 OrderedDictionary >> at:ifPresent:ifAbsentPut: doesn't touch the ordered keys array
  src/Collections-Sequenceable/OrderedDictionary.class.st
  src/Collections-Tests/OrderedDictionaryTest.class.st
Labels: Bug, System

#6090 Only modal lock/unlock system windows
  src/Spec-MorphicAdapters/Morph.extension.st
Labels: Graphics

#6089 Cleanups and renames in OSWindow terminology
  src/OSWindow-Core/OSBackendWindow.class.st
  src/OSWindow-Core/OSNullBackendWindow.class.st
  src/OSWindow-Core/OSNullWindowDriver.class.st
  src/OSWindow-Core/OSWindow.class.st
  src/OSWindow-Core/OSWindowGLRenderer.class.st
  src/OSWindow-Core/OSWindowRenderer.class.st
  src/OSWindow-SDL2/OSSDL2AthensRenderer.class.st
  src/OSWindow-SDL2/OSSDL2BackendWindow.class.st
  src/OSWindow-SDL2/OSSDL2Driver.class.st
  src/OSWindow-SDL2/OSSDL2FormRenderer.class.st
  src/OSWindow-SDL2/OSSDL2GLRenderer.class.st
  src/OSWindow-SDL2/OSSDL2GenericRenderer.class.st
  src/OSWindow-VM/OSVMBackendWindow.class.st
  src/OSWindow-VM/VMWindowDriver.class.st
Labels: Cleanup, Tools

#6107 Quote URL interpolated into xdg-open command string
  src/WebBrowser-Core/WBUnixWebBrowser.class.st
Labels: tests passed please review!

#6096 Codegeneration: generate code for Blocks for effect
  src/OpalCompiler-Core/OCASTTranslatorForEffect.class.st
  src/Reflectivity/RFASTTranslatorForEffect.class.st
Labels: tests passed please review!

#6129 6091-Fleaky-Spotter-tests
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/GT-Tests-Spotter-Processors/MockCatalogProvider.class.st
  src/GT-Tests-Spotter-Processors/SptCatalogProjectsProcessorTest.class.st
Labels: Fleaky-test

#6135 Compiler: Use better names for syntetic temps
  src/OpalCompiler-Core/OCASTTranslator.class.st
Labels: tests passed please review!

#6134 Cleanup: #vectorOffset
  src/OpalCompiler-Core/OCVectorTempVariable.class.st
  src/OpalCompiler-Tests/ASTtoIRMappingTest.class.st
Labels: tests passed please review!

#6132 Fix a couple of completion glitches
  src/HeuristicCompletion-Model/CoASTResultSetBuilder.class.st
  src/HeuristicCompletion-Model/CompletionEngine.extension.st
  src/HeuristicCompletion-Morphic/CoCompletionEngine.class.st
  src/HeuristicCompletion-Morphic/RubScrolledTextModel.extension.st
  src/HeuristicCompletion-Morphic/Workspace.extension.st
  src/HeuristicCompletion-Tests/CoASTResultSetBuilderTest.class.st
  src/HeuristicCompletion-Tests/CoMockASTResultSetBuilder.class.st
Labels: Bug, Tools

#6149 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/cleanup-report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/pharo-dev-branch-bug-report.md
Labels: Enhancement

#6153 ReflectivityAfterOptimizedBlocks
  src/Reflectivity-Tests/GlobalForTesting.class.st
  src/Reflectivity-Tests/ReflectivityControlTest.class.st
  src/Reflectivity-Tests/ReflectivityExamples.class.st
  src/Reflectivity-Tests/ReflectivityExamples2.class.st
  src/Reflectivity-Tests/ReflectivityExamples2Subclass.class.st
  src/Reflectivity/RFASTTranslator.class.st
Labels: tests passed please review!

#6159 OCASTTranslator: simplify #addTemps: callers
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCBlockScope.class.st
  src/Reflectivity/RFASTTranslator.class.st
Labels: tests passed please review!

#6178 Fix 6160 Cleanup two tests in BlockClosureTest
  src/Kernel-Tests/BlockClosureTest.class.st
Labels: more-information-needed

#6177 Improve Spacetally perfs and clean code
  src/Tool-Profilers/SmalltalkImage.extension.st
  src/Tool-Profilers/SpaceTally.class.st
  src/Tool-Profilers/SpaceTallyResult.class.st
  src/Tools-Test/SpaceTallyTest.class.st
Labels: Enhancement, Large Images

#6148 IRBuilder-addTempSimpler
  src/OpalCompiler-Core/IRBuilder.class.st
Labels: tests passed please review!

#6150 IRV2 cleanup
  src/OpalCompiler-Core/IRInstruction.class.st
  src/OpalCompiler-Core/IRMethod.class.st
  src/OpalCompiler-Core/IRPrinter.class.st
  src/OpalCompiler-Core/IRSequence.class.st
  src/OpalCompiler-Core/IRTranslator.class.st
Labels: tests passed please review!

#6141 2679-Fix-RxmBranch-to-do-greedy-matching-instead-of-first-match-passes
  src/Regex-Core-Tests/RxMatcherTest.class.st
  src/Regex-Core/RxMatcher.class.st
  src/Regex-Core/RxmBranch.class.st
Labels: tests passed please review!

#6168 CompilerCleanup-hasIncompleteIdentifier
  src/AST-Core/RBVariableNode.class.st
  src/Calypso-Browser/ClyTextEditorToolMorph.class.st
  src/Glamour-Morphic-Widgets/GLMRubricSmalltalkTextModel.class.st
  src/Glamour-Morphic-Widgets/GLMSmalltalkCodeModel.class.st
  src/Kernel-Tests-Extended/ClassTest.class.st
  src/Kernel/Class.class.st
  src/Kernel/SharedPool.class.st
  src/OpalCompiler-Core/ClassDescription.extension.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCAbstractScope.class.st
  src/OpalCompiler-Core/OCClassScope.class.st
  src/OpalCompiler-Core/OCEnvironmentScope.class.st
  src/OpalCompiler-Core/OCExtraBindingScope.class.st
  src/OpalCompiler-Core/OCInstanceScope.class.st
  src/OpalCompiler-Core/OCKeyedSet.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
  src/OpalCompiler-Tests/OCEnvironmentScopeTest.class.st
  src/OpalCompiler-Tests/OCScopeTest.class.st
  src/ProfStef-Core/LessonView.class.st
  src/Rubric/RubScrolledTextModel.class.st
  src/Rubric/RubSmalltalkCodeMode.class.st
  src/Rubric/RubTextAreaExamples.class.st
  src/Rubric/RubWorkspaceExample.class.st
  src/System-Support-Tests/SystemDictionaryTest.class.st
  src/System-Support/SmalltalkImage.class.st
  src/Tool-Workspace/Workspace.class.st
Labels: tests passed please review!

#6210 SemanticAnalysisSmallCleanup
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCAbstractVariable.class.st
  src/OpalCompiler-Core/OCClassScope.class.st
  src/OpalCompiler-Core/OCInstanceScope.class.st
  src/OpalCompiler-Core/OCSpecialVariable.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/OpalCompiler-Tests/ASTtoIRMappingTest.class.st
Labels: tests passed please review!

#6216 Fix #5854. SycMethodNameEditor fails with DNU in some cases
  src/SystemCommands-RefactoringSupport-Tests/MethodNameEditorTest.class.st
  src/SystemCommands-RefactoringSupport-Tests/SycMethodNameEditorTest.class.st
  src/SystemCommands-RefactoringSupport/SycMethodNameEditor.class.st
Labels: Refactorings

#6209 ReNodeRewriteRule subclasses might change the AST
  src/Renraku/ReAbstractRule.class.st
  src/Renraku/ReCriticEngine.class.st
  src/Renraku/ReNodeRewriteRule.class.st
Labels: tests passed please review!

#6158 ifErrorDo: should be onErrorDo: and deprecate with transform
  src/Calypso-NavigationModel-Tests/ClyCompositeScopeTest.class.st
  src/Calypso-NavigationModel-Tests/ClyTypedQueryTestCase.class.st
  src/Calypso-NavigationModel-Tests/ClyUnionQueryTest.class.st
  src/Calypso-SystemQueries/ClyQueryBrowserFilter.class.st
  src/ClassAnnotation-Tests/QueryAnnotationsFromClassTest.class.st
  src/Debugger-Model/DebugSession.class.st
  src/Deprecated90/BlockClosure.extension.st
  src/DeprecatedFileStream/FileStream.class.st
  src/EmergencyEvaluator/Transcripter.class.st
  src/JenkinsTools-Core/HDTestReport.class.st
  src/Kernel-Tests-Extended/MutexTest.class.st
  src/Kernel-Tests/BlockClosureTest.class.st
  src/Kernel-Tests/SemaphoreTest.class.st
  src/Kernel/BlockClosure.class.st
  src/Kernel/Context.class.st
  src/Kernel/Semaphore.class.st
  src/Math-Operations-Extensions/Float.extension.st
  src/Math-Operations-Extensions/Number.extension.st
  src/Monticello/MCWorkingCopy.class.st
  src/Morphic-Base/PolygonMorph.class.st
  src/Morphic-Core/PasteUpMorph.class.st
  src/Morphic-Core/WorldState.class.st
  src/Multilingual-Tests/MultiFontTest.extension.st
  src/Network-Mail/MailMessage.class.st
  src/OSWindow-SDL2/SDL2.class.st
  src/System-Sources/PharoFilesOpener.class.st
  src/System-Support/SmalltalkImage.class.st
  src/Tool-Finder/MethodFinderSend.class.st
  src/Tool-Finder/Object.extension.st
  src/Tool-ProcessBrowser/ProcessBrowser.class.st
Labels: Enhancement, Need more work

#6234 FixBlockBytecodePrinting
  src/Debugging-Core/SymbolicBytecodeBuilder.class.st
Labels: tests passed please review!

#6242 Improve Tests OCBytecodeToASTCache
  src/OpalCompiler-Tests/OCBytecodeToASTCacheTest.class.st
Labels: tests passed please review!

#6241 6082-Some-variables-seem-shadowed-and-reported-as-such-in-the-build-report-
  src/Athens-Examples/VGTigerDemo.class.st
  src/DrTests-Tests/DrTestsTestRunnerTest.class.st
  src/DrTests/DTPluginConfiguration.class.st
  src/Graphics-Files/PNGReadWriter.class.st
  src/MonticelloFileTree-Core/MCFileTreeStCypressWriter.class.st
  src/OpalCompiler-Tests/OCASTTranslatorTest.class.st
  src/OpalCompiler-Tests/OCASTVariableTranslatorTest.class.st
  src/Rubric-Tests/RubSmalltalkEditorTest.class.st
  src/Text-Tests/TextTest.class.st
Labels: tests passed please review!

#6245 Make all users of manifests use #uniqueIdentifierName to construct selectors
  src/Renraku/TheManifestBuilder.extension.st
Labels: tests passed please review!

#6235 ReAssignmentOnBlockArgumentRule-Remove
  src/GeneralRules-Tests/ReAssignmentOnBlockArgumentRuleTest.class.st
  src/GeneralRules/ReAssignmentOnBlockArgumentRule.class.st
Labels: tests passed please review!

#6207 refactor-spanNewSessionFrom
  src/Debugger-Model/DebugSession.class.st
  src/GT-Debugger/GTMoldableDebugger.class.st
Labels: tests passed please review!

#6251 6250-Transcript-shows-error-MessageNotUnderstood-Metaclass-hasBindingThatBeginsWith
  src/Kernel-Tests/MetaClassTest.class.st
  src/Kernel/Metaclass.class.st
Labels: tests passed please review!

#6252 Semantic Analysis: put Escape Analysis In one place
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
Labels: tests passed please review!

#6236 ReExcessiveVariablesRule: disable for SharedPools
  src/GeneralRules/ReExcessiveVariablesRule.class.st
Labels: tests passed please review!

#6249 SemanticAnalysis-PrimitiveErrorInvisitPragmaNode
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
Labels: tests passed please review!
