Repository pharo-project/pharo, pull requests merged in 2020-01, with the labels that each got.

#5456 Improving metalink printing and visualization in Calypso
  src/Reflectivity-Tools/MetaLinkIconStyler.class.st
  src/Reflectivity/MetaLink.class.st
Labels: Enhancement

#5455 Made metalinks installable on ast nodes by selecting code when browsing methods in Calypso
  src/Calypso-SystemPlugins-Reflectivity-Browser-Tests/ClyInstallMetaLinkPresenterTest.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddExecutionCounterCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddWatchpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyDebuggingCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyDebuggingMenuGroup.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyInstallMetaLinkCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyMetaLinkInstallationPresenter.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyMetalinkCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyRemoveBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyRemoveDebuggingCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyRemoveExecutionCounterCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyRemoveWatchpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyUninstallMetaLinkCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ManifestCalypsoSystemPluginsReflectivityBrowser.class.st
  src/Calypso-SystemTools-Core/SycOpenDebuggingMenuCommand.extension.st
  src/SystemCommands-SourceCodeCommands/SycDebuggingMenuActivation.class.st
  src/SystemCommands-SourceCodeCommands/SycOpenDebuggingMenuCommand.class.st
Labels: Cleanup, Enhancement

#5569 5562-Executing-All-Instances-in-the-startup-affects-loading-times
  src/FFI-Kernel/ExternalAddress.class.st
  src/Hiedra/HiColumnController.class.st
  src/Ombu/OmSessionStore.class.st
Labels: Large Images

#5594 5587-RBSimpleFormatter-should-not-use-start-and-stop-to-print-comments
  src/AST-Core/RBSimpleFormatter.class.st
Labels: tests passed please review!

#5598 5597-EFFormatter-should-not-use-start-and-stop-to-print-comments
  src/EnlumineurFormatter/EFFormatter.class.st
Labels: tests passed please review!

#5596 5595-BIConfigurableFormatter-should-not-use-start-and-stop-to-print-comments
  src/BlueInk-Core/BIConfigurableFormatter.class.st
Labels: tests passed please review!

#5593 CompletionEngine-and-Monticello-backport
  src/MonticelloGUI/MCSaveVersionDialog.class.st
Labels: tests passed please review!
