Repository pharo-project/pharo, pull requests merged in 2021-08, with the labels that each got.

#9657 Fixes: #9656 unload GT
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: Need more work

#9745 Fixes: #9744. Remove Glamour! Finally.
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: more-information-needed

#9747 Fixes: #9746 harvest two methods from Glamour extension.
  src/Collections-Abstract/ArrayedCollection.class.st
  src/Colors/Color.class.st
Labels: more-information-needed

#9663 8944-Remove-Unused-Alien-Core-Methods
  src/Alien-Core/Alien.class.st
  src/Alien-Core/ByteArray.extension.st
Labels: tests passed please review!

#9627 Better IPv6 String Support (Issue 9626)
  src/Network-Kernel/NetNameResolver.class.st
  src/Network-Tests/NetworkIPv6StringTest.class.st
Labels: tests passed please review!

#9755 Fix: #9754 gtCollectionSizeThreshold
  src/Collections-Abstract/Collection.class.st
Labels: more-information-needed

#9098 Fix for #9096 string >>> as time is very permissive
  src/Fuel-Tests-Core/FLBasicSerializationTest.class.st
  src/Kernel-Chronology-Extras/Time.extension.st
  src/Kernel-Tests/FluidClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/LegacyClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/OldClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/TimeTest.class.st
  src/Kernel/ChronologyConstants.class.st
Labels: tests passed please review!

#9764 fix navigator in spec
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: more-information-needed

#9775 Fixes: #9774 no more TestCase only Test + fixing typo.
  src/Calypso-NavigationModel-Tests/ClyAbstractNavigationEnvironmentTest.class.st
  src/Calypso-NavigationModel-Tests/ClyAsyncQueryResultTest.class.st
  src/Calypso-NavigationModel-Tests/ClyBrowserQueryCursorTest.class.st
  src/Calypso-NavigationModel-Tests/ClyBrowserQueryResultTest.class.st
  src/Calypso-NavigationModel-Tests/ClyItemGroupProviderTest.class.st
  src/Calypso-NavigationModel-Tests/ClyNavigationEnvironmentTest.class.st
  src/Calypso-NavigationModel-Tests/ClyQueryNavigationResultTest.class.st
  src/Calypso-NavigationModel-Tests/ClyQueryTest.class.st
  src/Calypso-NavigationModel-Tests/ClyRawQueryResultTest.class.st
  src/Calypso-NavigationModel-Tests/ClyScopeTest.class.st
  src/Calypso-NavigationModel-Tests/ClySortedQueryResultTest.class.st
  src/Calypso-SystemPlugins-Critic-Queries-Tests/ClyAllProblemMethodsTest.class.st
  src/Calypso-SystemPlugins-Critic-Queries-Tests/ClyGroupedCritiquesTest.class.st
  src/Calypso-SystemPlugins-Deprecation-Queries-Tests/ClyDeprecatedMethodsQueryTest.class.st
  src/Calypso-SystemPlugins-FFI-Queries-Tests/ClyFFIMethodsTest.class.st
  src/Calypso-SystemPlugins-Flags-Queries-Tests/ClyFlaggingMethodsQueryTest.class.st
  src/Calypso-SystemPlugins-InheritanceAnalysis-Queries-Tests/ClyAbstractMethodsQueryTest.class.st
  src/Calypso-SystemPlugins-InheritanceAnalysis-Queries-Tests/ClyOverriddenMethodsQueryTest.class.st
  src/Calypso-SystemPlugins-InheritanceAnalysis-Queries-Tests/ClyOverridingMethodsQueryTest.class.st
  src/Calypso-SystemPlugins-InheritanceAnalysis-Queries-Tests/ClyUnimplementedMethodsQueryTest.class.st
  src/Calypso-SystemPlugins-Reflectivity-Queries-Tests/ClyActiveBreakpointsQueryTest.class.st
  src/Calypso-SystemPlugins-Reflectivity-Queries-Tests/ClyMethodCallCountersQueryTest.class.st
  src/Calypso-SystemPlugins-Reflectivity-Queries-Tests/ClyMethodWatchQueryTest.class.st
  src/Calypso-SystemPlugins-SUnit-Queries-Tests/ClyExpectedFailedTestMethodsQueryTest.class.st
  src/Calypso-SystemPlugins-SUnit-Queries-Tests/ClyTestedEnvironmentPluginTest.class.st
  src/Calypso-SystemPlugins-Traits-Queries-Tests/ClyLocalClassScopeTest.extension.st
  src/Calypso-SystemPlugins-Undeclared-Queries-Tests/ClyUndeclaredMethodsQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyAllExtensionMethodsQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyAllMethodsQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyBothMetaLevelClassScopeTest.class.st
  src/Calypso-SystemQueries-Tests/ClyClassBindingsTest.class.st
  src/Calypso-SystemQueries-Tests/ClyClassExternalReferencesQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyClassReferencesQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyClassScopeTest.class.st
  src/Calypso-SystemQueries-Tests/ClyClassSideScopeTest.class.st
  src/Calypso-SystemQueries-Tests/ClyConstantMethodQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyGroupedExtendingPackagesTest.class.st
  src/Calypso-SystemQueries-Tests/ClyInstanceSideScopeTest.class.st
  src/Calypso-SystemQueries-Tests/ClyLocalClassScopeTest.class.st
  src/Calypso-SystemQueries-Tests/ClyMessageImplementorsQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyMessageSendersQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyMethodGroupTest.class.st
  src/Calypso-SystemQueries-Tests/ClyMethodQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyMethodSourcesQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyPackageExtensionMethodsQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyTaggedMethodsQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyUnclassifiedMethodsQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyVariableReferencesTest.class.st
Labels: more-information-needed

#9797 9795-Failing-on-CI-ReleaseTesttestNoEquivalentSuperclassMethods
  src/Collections-Unordered-Tests/SmallDictionaryTest.class.st
  src/EnlumineurFormatter-Tests/EFBlockExpressionTest.class.st
  src/Epicea/EpUnknownRefactoring.class.st
  src/Metacello-Core/MetacelloVersionNumber.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/System-Model/DisplayableObject.class.st
  src/Tool-Finder-Tests/MethodFinderBottomClass.class.st
Labels: tests passed please review!

#9805 Use Protocol unclassified whenever possible
  src/Kernel/Categorizer.class.st
  src/Ring-Core/RGBehavior.class.st
  src/Ring-Core/RGObject.class.st
  src/System-Changes/ChangeSet.class.st
Labels: tests passed please review!

#9802 Skip-testModifiedReturn
  src/OpalCompiler-Tests/OCTargetCompilerTest.class.st
Labels: tests passed please review!

#9793 ReadOnlyLiterals-Remove-Preference
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/IRTranslator.class.st
Labels: tests passed please review!

#9821 Adding doc
  doc/Epicea/1-Epicea.md
  doc/SUnit/1-SUnit.md
  doc/SUnit/2-running_tests.md
  doc/SUnit/3-links.md
  doc/SUnit/4-tutorial.md
  doc/Welcome/1-Welcome.md
  doc/Welcome/2-ChangeLog.md
  doc/Welcome/3-Documentation.md
  doc/Welcome/4-ToContribute.md
Labels: Need more work

#9817 Refactoring2-Deprecation-Clean
  src/Refactoring2-Transformations/RBMoveInstanceVariableToClassTransformation.class.st
  src/Refactoring2-Transformations/RBRenameVariableTransformation.class.st
Labels: tests passed please review!

#9816 DeadCode-Cleanup-08-24
  src/Calypso-Browser/ClyDataSource.class.st
  src/Calypso-NavigationModel/ClyItemGroup.class.st
  src/Calypso-SystemPlugins-SUnit-Browser/ClyTestSetUpEditorToolMorph.class.st
  src/Calypso-SystemPlugins-SUnit-Queries/ClySUnitEnvironmentPlugin.class.st
  src/Calypso-SystemQueries/ClyManagedProject.class.st
  src/Calypso-SystemTools-Core/ClySystemBrowserContext.class.st
  src/Deprecated90/AbstractCompiler.class.st
  src/Deprecated90/LocalVariable.extension.st
  src/Deprecated90/OCAbstractLocalVariable.class.st
  src/Deprecated90/OCAbstractVariable.class.st
  src/Deprecated90/OCArgumentVariable.class.st
  src/Deprecated90/OCEnvironmentScope.class.st
  src/Deprecated90/OCLiteralVariable.class.st
  src/Deprecated90/OCSelfVariable.class.st
  src/Deprecated90/OCSlotVariable.class.st
  src/Deprecated90/OCSpecialVariable.class.st
  src/Deprecated90/OCStoreIntoSpecialVariableError.class.st
  src/Deprecated90/OCSuperVariable.class.st
  src/Deprecated90/OCTempVariable.class.st
  src/Deprecated90/OCThisContextVariable.class.st
  src/Deprecated90/OCUndeclaredVariable.class.st
  src/Deprecated90/RBArgumentNode.class.st
  src/Deprecated90/RBGlobalNode.class.st
  src/Deprecated90/RBInstanceVariableNode.class.st
  src/Deprecated90/RBMethodNode.extension.st
  src/Deprecated90/RBProgramNode.extension.st
  src/Deprecated90/RBSelfNode.class.st
  src/Deprecated90/RBSequenceNode.extension.st
  src/Deprecated90/RBSuperNode.class.st
  src/Deprecated90/RBTemporaryNode.class.st
  src/Deprecated90/RBThisContextNode.class.st
  src/Deprecated90/RBVariableNode.extension.st
  src/Deprecated90/Slot.extension.st
  src/Deprecated90/Variable.extension.st
  src/Kernel-ExtraUtils/ClassHierarchyPrinterTest.class.st
  src/Kernel/LiteralVariable.class.st
  src/OpalCompiler-Core/ManifestOpalCompilerCore.class.st
  src/Reflectivity-Tools/FlagIconStyler.class.st
Labels: tests passed please review!

#9815 RecurseReadOnly-LiteralArray
  src/Collections-Sequenceable-Tests/ArrayTest.class.st
  src/Collections-Sequenceable/Array.class.st
  src/Kernel-Tests/ObjectTest.class.st
  src/Kernel/Object.class.st
  src/OpalCompiler-Core/IRTranslator.class.st
Labels: tests passed please review!

#9819 Unify #layoutForType: with the #kind methods.
  src/ClassParser-Tests/CDFluidClassParserTest.class.st
  src/Kernel/AbstractLayout.class.st
  src/Kernel/ByteLayout.class.st
  src/Kernel/DoubleByteLayout.class.st
  src/Kernel/DoubleWordLayout.class.st
  src/Kernel/EmptyLayout.class.st
  src/Kernel/ImmediateLayout.class.st
  src/Kernel/ObjectLayout.class.st
  src/Kernel/WordLayout.class.st
Labels: tests passed please review!

#9852 9731-Ph9-Spec2-List-items-cannot-be-selected-when-medium-font-is-used
  src/Settings-Graphics/GraphicFontSettings.class.st
Labels: tests passed please review!

#9853 Backport Issue 9731: Ph9-Spec2-List-items-cannot-be-selected-when-medium-font-is-used
  src/Settings-Graphics/GraphicFontSettings.class.st
Labels: tests passed please review!

#9834 Expand Dictionary documentation
  src/Collections-Unordered/Dictionary.class.st
Labels: tests passed please review!

#9862 remove-deprecated-code-08-30
  src/Deprecated90/AbstractFont.extension.st
  src/Deprecated90/BlockClosure.extension.st
  src/Deprecated90/ByteString.extension.st
  src/Deprecated90/CharacterScanner.extension.st
  src/Deprecated90/CompiledMethod.extension.st
  src/Deprecated90/CompositionScanner.extension.st
  src/Deprecated90/Context.extension.st
  src/Deprecated90/GIFReadWriter.extension.st
  src/Deprecated90/HTTPEncodingTest.extension.st
  src/Deprecated90/JapaneseEnvironment.class.st
  src/Deprecated90/LanguageEnvironment.class.st
  src/Deprecated90/Locale.extension.st
  src/Deprecated90/MultiFontTest.extension.st
  src/Deprecated90/OSEnvironment.extension.st
  src/Deprecated90/OSSDL2BackendWindow.extension.st
  src/Deprecated90/Pragma.extension.st
  src/Deprecated90/PragmaCollector.extension.st
  src/Deprecated90/RBParser.extension.st
  src/Deprecated90/RubCharacterScanner.extension.st
  src/Deprecated90/RubCompositionScanner.extension.st
  src/Deprecated90/String.extension.st
  src/Deprecated90/StringTest.extension.st
  src/Deprecated90/Symbol.extension.st
  src/Deprecated90/SystemNavigation.extension.st
  src/Deprecated90/Text.extension.st
  src/Deprecated90/TextConverter.class.st
  src/Deprecated90/TextStyleAsFontFamilyMember.extension.st
  src/Deprecated90/Unicode.extension.st
  src/Deprecated90/WideString.extension.st
  src/Deprecated90/WideSymbol.extension.st
  src/Network-Tests/HTTPEncodingTest.class.st
Labels: tests passed please review!
