Repository pharo-project/pharo, pull requests merged in 2021-12, with the labels that each got.

#10526 fixes 10525 - extract Keymapping packages to its own baseline
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfKeymapping/BaselineOfKeymapping.class.st
  src/BaselineOfKeymapping/package.st
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/BaselineOfUI/BaselineOfUI.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: Need more work

#10550 Cleanup newlines and blanks in "Metacello" packages
  src/Metacello-Base/BaselineOf.class.st
  src/Metacello-Core/MCRepository.extension.st
  src/Metacello-Core/MetacelloMemberListSpec.class.st
  src/Metacello-Core/MetacelloOldSemanticVersionNumber.class.st
  src/Metacello-Core/MetacelloPlatform.class.st
  src/Metacello-Core/MetacelloProject.class.st
  src/Metacello-Core/MetacelloScriptEngine.class.st
  src/Metacello-Core/MetacelloSemanticVersionNumber.class.st
  src/Metacello-Core/MetacelloToolBoxConstructor.class.st
  src/Metacello-Core/MetacelloVersionSpec.class.st
  src/Metacello-Cypress/MetacelloCypressPackageSpec.class.st
  src/Metacello-GitBasedRepository/MCGitBasedNetworkRepository.class.st
  src/Metacello-GitHub/MCGitHubRepository.class.st
  src/Metacello-MC/MetacelloMCProjectSpec.class.st
  src/Metacello-MC/MetacelloMCVersion.class.st
  src/Metacello-MC/MetacelloMCVersionValidator.class.st
  src/Metacello-MC/MetacelloPackageSpec.class.st
  src/Metacello-PharoCommonPlatform/MetacelloPharoCommonPlatform.class.st
  src/Metacello-PharoExtensions/BaselineOf.extension.st
  src/Metacello-Platform/MetacelloPharoPlatform.class.st
  src/Metacello-Reference/MetacelloReferenceConfig.class.st
  src/Metacello-TestsCommonMC/MetacelloTestsMCPackage.extension.st
  src/Metacello-TestsCore/MetacelloCommonVersionNumberTestCase.class.st
  src/Metacello-TestsCore/MetacelloStackCacheTestCase.class.st
  src/Metacello-TestsCore/MetacelloVersionNumberTestCase.class.st
  src/Metacello-TestsMC/MetacelloDictionaryRepositoryTest.class.st
  src/Metacello-TestsMC/MetacelloScriptingStdTstHarnessTestCase.class.st
  src/Metacello-TestsMCCore/MetacelloPlatformTestCase.class.st
  src/Metacello-TestsMCResources/MetacelloAtomicConfigurationResource.class.st
  src/Metacello-TestsMCResources/MetacelloAtomicMonticelloResource.class.st
  src/Metacello-TestsMCResources/MetacelloConfigurationResource.class.st
  src/Metacello-TestsMCResources/MetacelloExampleProjectConfig.class.st
  src/Metacello-TestsMCResources/MetacelloIssue108Resource.class.st
  src/Metacello-TestsMCResources/MetacelloMCTestsAbstractConfig.class.st
  src/Metacello-TestsPlatform/MetacelloRepositorySqueakCommonTestCase.class.st
  src/Metacello-ToolBox/MetacelloToolBox.class.st
  src/Metacello-Tutorial/MetacelloProjectRefTutorialConfig.class.st
  src/Metacello-Tutorial/MetacelloTutorialConfig.class.st
Labels: tests passed please review!

#10560 in fact, Keymapping-Pragmas package needs to be in UI group
  src/BaselineOfKeymapping/BaselineOfKeymapping.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: tests passed please review!

#10614 Beacon "instance" class variable not capitalized
  src/Beacon-Core/Beacon.class.st
Labels: tests passed please review!

#10604 Cleanup newlines and blanks in "PragmaCollector" packages
  src/PragmaCollector/PragmaCollector.class.st
Labels: tests passed please review!

#10617 Fixing the category of QuotedPrintableMimeConverter>>#newline
  src/Network-MIME/QuotedPrintableMimeConverter.class.st
Labels: tests passed please review!

#10388 Fix for Issue #10269 Replaced RBExtractToTemporaryRefactoring with RBExtractToTemporaryTra…
  src/Refactoring-Help/RBBrowserSourceRefactoringHelp.class.st
  src/Refactoring2-Transformations/RBExtractToTemporaryTransformation.class.st
  src/SystemCommands-SourceCodeCommands/SycExtractTempCommand.class.st
Labels: tests passed please review!

#10514 Fix stability of SUnitTest's related to the process monitoring
  src/SUnit-Tests/SUnitTest.class.st
Labels: tests passed please review!

#10618 Cleanup newlines and blanks in "OpalCompiler" packages
  src/OpalCompiler-Core/Behavior.extension.st
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/IRBlockReturnTop.class.st
  src/OpalCompiler-Core/IRBuilder.class.st
  src/OpalCompiler-Core/IRBytecodeDecompiler.class.st
  src/OpalCompiler-Core/IRBytecodeGenerator.class.st
  src/OpalCompiler-Core/IRFix.class.st
  src/OpalCompiler-Core/IRInstruction.class.st
  src/OpalCompiler-Core/IRJump.class.st
  src/OpalCompiler-Core/IRMethod.class.st
  src/OpalCompiler-Core/IRPrimitive.class.st
  src/OpalCompiler-Core/IRPrinter.class.st
  src/OpalCompiler-Core/IRPushArray.class.st
  src/OpalCompiler-Core/IRPushFullClosure.class.st
  src/OpalCompiler-Core/IRPushReceiver.class.st
  src/OpalCompiler-Core/IRReconstructor.class.st
  src/OpalCompiler-Core/IRSend.class.st
  src/OpalCompiler-Core/IRSequence.class.st
  src/OpalCompiler-Core/IRStackCount.class.st
  src/OpalCompiler-Core/IRTempVector.class.st
  src/OpalCompiler-Core/IRTranslator.class.st
  src/OpalCompiler-Core/IRVisitor.class.st
  src/OpalCompiler-Core/LocalVariable.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCASTSemanticCleaner.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/OCASTTranslatorForEffect.class.st
  src/OpalCompiler-Core/OCASTTranslatorForValue.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCLiteralList.class.st
  src/OpalCompiler-Core/OCSemanticWarning.class.st
  src/OpalCompiler-Core/OCShadowVariableWarning.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Core/RBBlockNode.extension.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/OpalCompiler-Core/RBProgramNode.extension.st
  src/OpalCompiler-Tests/IRBuilderTest.class.st
  src/OpalCompiler-Tests/MethodMapTest.class.st
  src/OpalCompiler-Tests/MethodPragmaTest.class.st
  src/OpalCompiler-Tests/MockSourceEditor.class.st
  src/OpalCompiler-Tests/OCASTCheckerTest.class.st
  src/OpalCompiler-Tests/OCASTClosureAnalyzerTest.class.st
  src/OpalCompiler-Tests/OCASTDoubleBranchConditionalTranslatorTest.class.st
  src/OpalCompiler-Tests/OCASTSpecialLiteralTranslatorTest.class.st
  src/OpalCompiler-Tests/OCASTTranslatorTest.class.st
  src/OpalCompiler-Tests/OCASTVariableTranslatorTest.class.st
  src/OpalCompiler-Tests/OCArrayLiteralTest.class.st
  src/OpalCompiler-Tests/OCBytecodeToASTCacheTest.class.st
  src/OpalCompiler-Tests/OCCleanBlockTest.class.st
  src/OpalCompiler-Tests/OCClosureTest.class.st
  src/OpalCompiler-Tests/OCCompilerExceptionsTest.class.st
  src/OpalCompiler-Tests/OCCompilerNotifyingTest.class.st
  src/OpalCompiler-Tests/OCCompilerTest.class.st
  src/OpalCompiler-Tests/OCOpalExamples.class.st
  src/OpalCompiler-Tests/OCPerformTest.class.st
  src/OpalCompiler-Tests/OCSourceCode2BytecodeTest.class.st
  src/OpalCompiler-Tests/OCTargetCompilerParser.class.st
  src/OpalCompiler-Tests/OCTargetCompilerSample.class.st
  src/OpalCompiler-Tests/OCTargetCompilerTest.class.st
Labels: tests passed please review!

#10641 Extract freetype to its own baseline (2nd pass)
  src/BaselineOfFreeType/BaselineOfFreeType.class.st
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/FreeType-Graphics/BitBlt.extension.st
  src/FreeType-Graphics/Form.extension.st
  src/FreeType-Graphics/FreeTypeFont.extension.st
  src/FreeType-Graphics/FreeTypeGlyphRenderer.class.st
  src/FreeType-Graphics/FreeTypeSettings.extension.st
  src/FreeType-Graphics/FreeTypeSubPixelAntiAliasedGlyphRenderer.class.st
  src/FreeType-Graphics/FreeTypeSystemSettings.extension.st
  src/FreeType-Graphics/GlyphForm.class.st
  src/FreeType-Graphics/GrafPort.extension.st
  src/FreeType-Graphics/package.st
  src/FreeType-Morphic/TextStyle.extension.st
  src/FreeType/FreeTypeCache.class.st
  src/FreeType/FreeTypeFont.class.st
  src/FreeType/FreeTypeSettings.class.st
  src/FreeType/FreeTypeSystemSettings.class.st
  src/FreeType/Object.extension.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: tests passed please review!

#10643 Fixing selector type: RBAddMethodChange>>#class:source:contoller:
  src/Refactoring-Changes/RBAddMethodChange.class.st
Labels: tests passed please review!

#10626 Migrating RBAbstractVariables and RBMoveMethod
  src/Refactoring2-Transformations-Tests/RBMoveMethodParametrizedTest.class.st
  src/Refactoring2-Transformations/RBAbstractVariablesTransformation.class.st
  src/Refactoring2-Transformations/RBMoveMethodTransformation.class.st
Labels: tests passed please review!

#10649 Categorize-More-Uncategorized
  src/HelpSystem-Core/HelpExporter.class.st
  src/OSWindow-SDL2/SDL2WindowsMessages.class.st
  src/Ring-Core/RGEnvironmentQueryInterface.class.st
  src/Tool-Diff/MergeJoinSection.class.st
Labels: tests passed please review!, easyReview

#10660 Unused method in FFI
  src/UnifiedFFI/FFICallout.class.st
Labels: tests passed please review!

#10624 Cleanup-Spec-Deprecated
  src/BaselineOfSpec/BaselineOfSpec.class.st
  src/Spec-Deprecated/ComposablePresenter.extension.st
Labels: tests passed please review!

#10652 10651-Resuming-a-exception-that-has-been-signalled-twice-does-not-return-correctly
  src/Kernel-Tests/ExceptionTest.class.st
  src/Kernel/Context.class.st
Labels: tests passed please review!

#10654 Cleanup-DuplcatedMethods-12-13
  src/Refactoring-Core/RBMoveMethodToClassSideRefactoring.class.st
  src/Rubric-SpecFindReplaceDialog/SpRubFindReplaceService.class.st
  src/Spec-Core/ComposablePresenter.class.st
  src/SystemCommands-ClassCommands/SycCMakeAbstractCommand.class.st
  src/SystemCommands-RefactoringSupport/SycMethodNameEditorPresenter.class.st
  src/UnifiedFFI/FFIExternalValueHolderType.class.st
Labels: tests passed please review!, easyReview

#10662 fix a couple of regressions
  src/Keymapping-Pragmas/PragmaMenuAndShortcutRegistration.extension.st
  src/ThreadedFFI/Bitmap.extension.st
Labels: tests passed please review!

#10653 Register bootstrapped projects
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: tests passed please review!

#10648 10294-undefinedIdentifier-is-missing-in-SHRBTextStyler
  src/Shout-Tests/SHRBTextStylerTest.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#10633 Fix metacello lock
  src/Metacello-Base/Metacello.class.st
  src/Metacello-Core/MetacelloGenericProjectSpec.class.st
  src/Metacello-Core/MetacelloProjectSpec.class.st
  src/Metacello-Core/MetacelloProjectSpecForLoad.class.st
  src/Metacello-Core/MetacelloScriptEngine.class.st
  src/Metacello-MC/MetacelloMCProjectSpec.class.st
  src/Metacello-MC/MetacelloPackageSpec.class.st
  src/Metacello-TestsCore/BaselineOfTestToLock1.class.st
  src/Metacello-TestsCore/BaselineOfTestToLock2.class.st
  src/Metacello-TestsCore/MetacelloLockTest.class.st
Labels: tests passed please review!
