Repository pharo-project/pharo, pull requests merged in 2021-07, with the labels that each got.

#9492 RB - Fix extract method refactoring
  src/AST-Core/RBPatternVariableNode.class.st
  src/Refactoring-Core/RBExtractMethodRefactoring.class.st
  src/Refactoring-Core/RBInlineMethodRefactoring.class.st
  src/Refactoring-Core/RBRefactoring.class.st
  src/Refactoring-Tests-Core/RBExtractMethodAndOccurrencesTest.class.st
  src/Refactoring-Tests-Core/RBRefactoringTest.class.st
  src/SystemCommands-MessageCommands/SycFindAndReplaceMethodCommand.class.st
Labels: tests passed please review!

#9537 Add release test - no "utlils" method categorization, use "utilities" instead
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
Labels: tests passed please review!

#9550 9543-Executing-an-expression-with-an-unknow-class-raises-an-error-on-rub
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
Labels: tests passed please review!

#9556 9548-Menus-shortcut-rendering-broken
  src/Morphic-Base/ShortcutReminder.class.st
Labels: tests passed please review!

#9557 fixing-pointer-explorer-open-break
  src/EyeInspector/EyePointerExplorer.class.st
  src/EyeInspector/EyeTreeInspector.class.st
Labels: tests passed please review!

#9549 9488-ReConsistencyCheckRule-description-is-not-fully-correct
  src/GeneralRules/ReConsistencyCheckRule.class.st
Labels: tests passed please review!

#9554 Fixes: #9552 and #9553
  src/Calypso-SystemPlugins-MethodDiffTool/ClyMethodDiffToolMorph.class.st
  src/Calypso-SystemPlugins-SUnit-Browser/ClyTestSetUpEditorToolMorph.class.st
  src/Calypso-SystemQueries-Tests/ClyExtensionLastSortedClassesTest.class.st
  src/Calypso-SystemQueries/ClyExtensionLastSortedClassResult.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserMorph.class.st
Labels: Pharo10

#9544 Fixed the Undo and Redo in the RubTextEditor
  src/Rubric/RubTextEditor.class.st
Labels: tests passed please review!

#9569 9555-Disable-deprecate-menuItem
  src/SystemCommands-ClassCommands/SycDeprecateClassCommand.class.st
Labels: tests passed please review!

#9568 9567-Traits-Super-sends-in-blocks-lead-to-VM-crash
  src/TraitsV2/TaCompositionElement.class.st
Labels: tests passed please review!

#9563 Improve the workaround to not show the undeclared fix menu when in c…
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
Labels: tests passed please review!

#9559 updating-changelog-to-p9
  src/HelpSystem-Core/CustomHelp.class.st
  src/Pharo-WelcomeHelp/WelcomeHelp.class.st
Labels: tests passed please review!

#9578 Fix #9577: Typing in the help browser DNU
  src/HelpSystem-Core/HelpBrowser.class.st
Labels: tests passed please review!

#9572 9571-Using-Clipboard-Tools-does-not-work-aka-Virtual-Paste
  src/OSWindow-SDL2/OSSDL2Driver.class.st
  src/OSWindow-SDL2/OSSDLPasteEventFilter.class.st
  src/OSWindow-SDL2/SDL2MappedEvent.class.st
  src/OSWindow-SDL2/SDL_ClipboardUpdateEvent.class.st
  src/OSWindow-SDL2/SDL_CommonEvent.class.st
  src/OSWindow-SDL2/SDL_Event.class.st
  src/OSWindow-SDL2/SDL_KeyDownEvent.class.st
  src/OSWindow-SDL2/SDL_KeyUpEvent.class.st
  src/OSWindow-SDL2/SDL_KeyboardEvent.class.st
  src/OSWindow-SDL2/SDL_Keysym.class.st
Labels: tests passed please review!

#9585 fix getting help page
  src/Pharo-WelcomeHelp/WelcomeHelp.class.st
Labels: tests passed please review!

#9602 use spec 1.0.1
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: tests passed please review!

#9593 Fixing UML tab to not be generated on each click
  src/Calypso-Browser/ClyNotebookManager.class.st
Labels: tests passed please review!

#9606 9603 changes in pharo 9 in welcome window points to version 8 instead of 9
  src/Pharo-WelcomeHelp/WelcomeHelp.class.st
Labels: tests passed please review!

#9608 9564-CriticsCache-is-not-referenced
  src/Renraku/ReCriticsCache.class.st
  src/Tool-CriticBrowser/CriticBrowser.class.st
  src/Tool-CriticBrowser/CriticsCache.class.st
Labels: easyReview, tests passed please review!

#9605 Fit column width to content on double clicking a MorphTreeResizerMorph
  src/Morphic-Base/Morph.extension.st
  src/Morphic-Widgets-Tree/MorphTreeResizerMorph.class.st
Labels: tests passed please review!

#9221 add upperbound on seed in random
  src/Random-Core/Random.class.st
Labels: tests passed please review!

#9635 Fix 9631 (Sources should not contain NULL character) for Pharo 9
  src/GeneralRules/ReClassNameInSelectorRule.class.st
  src/OSWindow-Core/OSWindowMorphicEventHandler.class.st
Labels: tests passed please review!

#9651 CommandLineUIManager should setup stdout transcript
  src/UIManager/CommandLineUIManager.class.st
Labels: tests passed please review!

#9623 RB - Migrate refactorings
  src/Refactoring-Core/RBAbstractClass.class.st
  src/Refactoring-Core/RBClass.class.st
  src/Refactoring-Core/RBCondition.class.st
  src/Refactoring-Core/RBMetaclass.class.st
  src/Refactoring-Core/RBNamespace.class.st
  src/Refactoring-Core/RBRenameInstanceVariableRefactoring.class.st
  src/Refactoring2-Core/RBAbstractClass2.class.st
  src/Refactoring2-Core/RBClass2.class.st
  src/Refactoring2-Core/RBMetaclass2.class.st
  src/Refactoring2-Core/RBNamespace.extension.st
  src/Refactoring2-Core/RBNamespace2.class.st
  src/Refactoring2-Transformations-Tests/RBAddInstanceVariableParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBExtractMethodTransformationTest.class.st
  src/Refactoring2-Transformations-Tests/RBExtractToTemporaryParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBInlineTemporaryParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBMergeInstanceVariableIntoAnotherParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBPullUpMethodParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBPushDownMethodParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBRenameTemporaryParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBTransformationTest.class.st
  src/Refactoring2-Transformations-Tests/RBTransformationsTest.class.st
  src/Refactoring2-Transformations-Tests/TModelBuilder.trait.st
  src/Refactoring2-Transformations/RBCompositeTransformation.class.st
  src/Refactoring2-Transformations/RBExpandReferencedPoolsTransformation.class.st
  src/Refactoring2-Transformations/RBExtractToTemporaryTransformation.class.st
  src/Refactoring2-Transformations/RBInlineTemporaryTransformation.class.st
  src/Refactoring2-Transformations/RBMergeInstanceVariableIntoAnotherTransformation.class.st
  src/Refactoring2-Transformations/RBPullUpMethodTransformation.class.st
  src/Refactoring2-Transformations/RBPushDownMethodTransformation.class.st
  src/Refactoring2-Transformations/RBRenameVariableTransformation.class.st
  src/Refactoring2-Transformations/RBTransformation.class.st
Labels: tests passed please review!

#9652 Fix #9471: roundDownTo: Turn comments into executable comments
  src/Kernel/Number.class.st
Labels: tests passed please review!

#9660 ReleaseTest to check that sources should not contain NUL character
  src/ReleaseTests/ReleaseTest.class.st
Labels: tests passed please review!

#9662 Fix EmbeddedFreeTypeFontDescription class>>#isAbstract
  src/EmbeddedFreeType/EmbeddedFreeTypeFontDescription.class.st
Labels: tests passed please review!

#9667 Mark AbstractDelayTicker as abstract
  src/Kernel/AbstractDelayTicker.class.st
Labels: tests passed please review!

#9669 Fix typos in AnnouncementLogger class comments
  src/System-Announcements/AnnouncementLogger.class.st
Labels: tests passed please review!

#9674 ManifestDeprecated10 needs to inherit from PackageManifest
  src/Deprecated10/ManifestDeprecated10.class.st
Labels: tests passed please review!

#9672 9620-changes-in-pharo-10-in-welcome-window-points-to-version-8-instead-of-10
  src/Pharo-WelcomeHelp/WelcomeHelp.class.st
Labels: tests passed please review!

#9680 Adjust sizes in ProperMethodCategorizationTest
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
Labels: tests passed please review!

#9678 Checksum is abstract
  src/System-Hashing/Checksum.class.st
Labels: tests passed please review!

#9642 9590-asRingMinimalDefinitionIn-not-defined-in-AbstractLayout-hierarchy
  src/Kernel/AbstractLayout.class.st
  src/Kernel/BitsLayout.class.st
  src/Kernel/CompiledMethodLayout.class.st
  src/Kernel/ImmediateLayout.class.st
  src/Kernel/LayoutAbstractScope.class.st
  src/Kernel/ObjectLayout.class.st
  src/Kernel/PointerLayout.class.st
  src/Ring-Core/BitsLayout.extension.st
  src/Ring-Core/DoubleByteLayout.extension.st
  src/Ring-Core/DoubleWordLayout.extension.st
  src/Ring-Core/ObjectLayout.extension.st
  src/Ring-Core/PointerLayout.extension.st
  src/Ring-Core/RGDoubleByteLayout.class.st
  src/Ring-Core/RGDoubleWordLayout.class.st
  src/Ring-Monticello/RGDoubleByteLayout.extension.st
  src/Ring-Monticello/RGDoubleWordLayout.extension.st
Labels: tests passed please review!

#9687 Rename LayoutAbstractScope into AbstractLayoutScope and define as abstract
  src/Kernel/AbstractLayoutScope.class.st
  src/Kernel/LayoutClassScope.class.st
  src/Kernel/LayoutEmptyScope.class.st
Labels: tests passed please review!

#9698 update spec version to v1.0.2
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: tests passed please review!

#9699 use newtools 0.6.9
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: tests passed please review!

#9695 9694 cleanup gofer packages
  src/Gofer-Core/Gofer.class.st
  src/Gofer-Core/GoferChanges.class.st
  src/Gofer-Core/GoferCleanup.class.st
  src/Gofer-Core/GoferCommit.class.st
  src/Gofer-Core/GoferConfigurationReference.class.st
  src/Gofer-Core/GoferConstraintReference.class.st
  src/Gofer-Core/GoferLocalChanges.class.st
  src/Gofer-Core/GoferMerge.class.st
  src/Gofer-Core/GoferOperation.class.st
  src/Gofer-Core/GoferPackageReference.class.st
  src/Gofer-Core/GoferPush.class.st
  src/Gofer-Core/GoferRecompile.class.st
  src/Gofer-Core/GoferReference.class.st
  src/Gofer-Core/GoferReinitialize.class.st
  src/Gofer-Core/GoferRemoteChanges.class.st
  src/Gofer-Core/GoferRepositoryError.class.st
  src/Gofer-Core/GoferResolvedReference.class.st
  src/Gofer-Core/GoferRevert.class.st
  src/Gofer-Core/GoferSynchronize.class.st
  src/Gofer-Core/GoferUnload.class.st
  src/Gofer-Core/GoferUpdate.class.st
  src/Gofer-Core/GoferVersionReference.class.st
  src/Gofer-Core/GoferWorking.class.st
  src/Gofer-Core/ManifestGoferCore.class.st
  src/Gofer-Tests/GoferApiTest.class.st
  src/Gofer-Tests/GoferOperationTest.class.st
  src/Gofer-Tests/GoferReferenceTest.class.st
  src/Gofer-Tests/GoferResource.class.st
  src/Gofer-Tests/GoferTest.class.st
  src/Metacello-MC/GoferPackageReference.extension.st
Labels: tests passed please review!

#9685 Deprecated unused AssemblyManifest and related methods (SECOND ATTEMPT)
  src/Deprecated10/AssemblyManifest.class.st
  src/Deprecated10/CollectionsAssembly.class.st
  src/Deprecated10/DAPackageUnderAnalysisNode.extension.st
  src/Deprecated10/PharoBootstrapRule.extension.st
  src/Deprecated10/PharoKernelAssembly.class.st
  src/Kernel-Rules/PharoBootstrapRule.class.st
  src/Tool-DependencyAnalyser-UI/AssemblyManifest.extension.st
  src/Tool-DependencyAnalyser-UI/DAPackageUnderAnalysisNode.class.st
Labels: tests passed please review!

#9648 add /usr/lib/x86_64-linux-gnu/ to the FFIUnix64LibraryFinder
  src/UnifiedFFI/FFIUnix64LibraryFinder.class.st
Labels: tests passed please review!

#9655 ReleaseTest-testNoEquivalentSuperclassMethods
  src/ReleaseTests/ReleaseTest.class.st
Labels: easyReview, tests passed please review!

#9702 Cleanup-DuplicatedMethods-ClassParser
  src/ClassParser-Tests/CDPointClassParserTest.class.st
  src/ClassParser/CDAbstractTraitCompositionNode.class.st
  src/ClassParser/CDBehaviorDefinitionNode.class.st
  src/ClassParser/CDClassDefinitionNode.class.st
  src/ClassParser/CDClassDefinitionParser.class.st
  src/ClassParser/CDFluidClassDefinitionParser.class.st
Labels: easyReview, tests passed please review!

#9696 Ring2-Layouts-simpler-layoutName
  src/Ring-Core/RGBitsLayout.class.st
  src/Ring-Core/RGByteLayout.class.st
  src/Ring-Core/RGCompiledMethodLayout.class.st
  src/Ring-Core/RGDoubleByteLayout.class.st
  src/Ring-Core/RGDoubleWordLayout.class.st
  src/Ring-Core/RGEmptyLayout.class.st
  src/Ring-Core/RGEphemeronLayout.class.st
  src/Ring-Core/RGFixedLayout.class.st
  src/Ring-Core/RGImmediateLayout.class.st
  src/Ring-Core/RGLayout.class.st
  src/Ring-Core/RGObjectLayout.class.st
  src/Ring-Core/RGPointerLayout.class.st
  src/Ring-Core/RGVariableLayout.class.st
  src/Ring-Core/RGWeakLayout.class.st
  src/Ring-Core/RGWordLayout.class.st
Labels: tests passed please review!

#9650 9649-unload-Commander2-Deprecations-in-Pharo10
  src/BaselineOfCommander2/BaselineOfCommander2.class.st
  src/Commander2-Deprecations/CmCommandDecorator.extension.st
  src/Commander2-Deprecations/CmCommandGroupDecorator.extension.st
  src/Commander2-Deprecations/CmTWithBasicNameAndDescription.extension.st
Labels: tests passed please review!

#9689 Remove some Pharo5 deprecations (UFFI)
  src/UnifiedFFI/ExternalAddress.extension.st
  src/UnifiedFFI/FFIExternalReference.class.st
  src/UnifiedFFI/FFIStructure.class.st
Labels: tests passed please review!

#9645 9612-CleanBlockChecker-looks-to-be-used-before-it-is-loaded
  src/Kernel/CleanBlockChecker.class.st
  src/Kernel/InstructionClient.class.st
Labels: tests passed please review!
