Repository pharo-project/pharo, pull requests merged in 2021-02, with the labels that each got.

#8449 Fix copy-paste to take into account real AST node
  src/Rubric/RubSmalltalkEditor.class.st
  src/Rubric/RubTextEditor.class.st
Labels: tests passed please review!

#8466 RB - Introduce Extract setUp refactoring
  src/Refactoring-Core/RBExtractSetUpMethodRefactoring.class.st
  src/Refactoring-Tests-Core/RBDataTest.class.st
  src/Refactoring-Tests-Core/RBExtractSetUpMethodTest.class.st
Labels: tests passed please review!

#8448 8370 metalinks cannot be reinstalled if the image was saved while they were uninstalled
  src/Reflectivity-Tests/ReflectivityTest.class.st
  src/Reflectivity/MetaLink.class.st
  src/Reflectivity/RFCondition.class.st
Labels: tests passed please review!

#8457 Clean the log file created on the disk by the test
  src/System-Support-Tests/SmalltalkImageTest.class.st
Labels: tests passed please review!

#8470 7638-withSqueakLineEnding-should-be-moved-to-deprecated-package
  src/Collections-Strings/String.class.st
  src/Deprecated90/String.extension.st
  src/Deprecated90/Text.extension.st
  src/Text-Core/Text.class.st
Labels: easyReview, tests passed please review!

#8472 RB - Expose variable refactoring commands in source context
  src/Calypso-SystemTools-Core/SycRenameVariableCommand.extension.st
  src/SystemCommands-VariableCommands/SycProtectVariableCommand.class.st
  src/SystemCommands-VariableCommands/SycRemoveVariableCommand.class.st
Labels: tests passed please review!

#8456 2681 debugger step into does not go into accessors or methods with primitives
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/Kernel-Tests/ContextTest.class.st
  src/Kernel-Tests/SimulationMock.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/CompiledMethod.class.st
  src/Kernel/Context.class.st
Labels: debugger, tests passed please review!

#8487 Classify one unclassified method in Trait
  src/TraitsV2/Trait.class.st
Labels: easyReview, tests passed please review!

#8495 Adding deprecations that were recommended by DepMiner (accepted by 3 reviewers)
  src/ClassParser/CDClassDefinitionParser.class.st
  src/ClassParser/CDSharedVariableNode.class.st
  src/ClassParser/CDSlotNode.class.st
  src/Ring-Core/RGSlot.class.st
  src/Ring-Core/RGVariable.class.st
Labels: tests passed please review!

#8492 7692-Deprecation-exception-when-use-Open-Directory-Chooser-button-dialog-of-Iceberg-Settings-UI
  src/System-Settings-Core/PragmaSetting.class.st
Labels: tests passed please review!

#8488 DiskDirectoryEntry-remove-unused-classVar
  src/FileSystem-Core/DiskDirectoryEntry.class.st
Labels: easyReview, tests passed please review!

#8486 Changeset-fileout-DNU
  src/System-Changes/ChangeSet.class.st
Labels: easyReview, tests passed please review!

#8484 TaRenameSlot-TestAndFix
  src/ClassParser/CDAbstractTraitCompositionNode.class.st
  src/ClassParser/CDTraitSlotRenameNode.class.st
  src/TraitsV2-Tests/T2TraitWithAliasTest.class.st
  src/TraitsV2/TaAbstractComposition.class.st
  src/TraitsV2/TaEmptyComposition.class.st
  src/TraitsV2/TaRemoveSlot.class.st
  src/TraitsV2/TaRenameSlot.class.st
  src/TraitsV2/Trait.class.st
Labels: tests passed please review!

#8493 7879-Clunky-interactive-but-bad-flow-for-fileIntoNewChangeSet
  src/Compression/GZipReadStream.class.st
  src/System-Changes-FileServices/ChangeSet.extension.st
Labels: easyReview, tests passed please review!

#8510 Adding transformation rules for two deprecated methods of Context. One of them was recommended by DepMiner but had to be modified
  src/Debugging-Core/Context.extension.st
Labels: tests passed please review!

#8507 Adding deprecations for Opal Compiler that were recommended by DepMiner and accepted by Pablo
  src/Deprecated90/OCAbstractVariable.class.st
  src/Deprecated90/OCLiteralVariable.class.st
  src/Deprecated90/OCSelfVariable.class.st
  src/Deprecated90/OCSlotVariable.class.st
  src/Deprecated90/OCSuperVariable.class.st
  src/Deprecated90/OCUndeclaredVariable.class.st
Labels: tests passed please review!

#8501 Testing and adding debugger inspector maximize assertion failure diff pane
  src/NewTools-Debugger-Tests/StDebuggerInspectorTest.class.st
  src/NewTools-Debugger-Tests/StDebuggerTest.class.st
  src/NewTools-Debugger/StDebuggerInspector.class.st
Labels: debugger, easyReview, tests passed please review!

#8516 8473-whenGotForcus-method-in-RubScrolledTextMorph-class
  src/Rubric/RubScrolledTextMorph.class.st
Labels: tests passed please review!

#8527 ReflectivityTest>>#setUp copies the ASTCache
  src/Reflectivity-Tests/ReflectivityTest.class.st
Labels: tests passed please review!

#8518 6757-Remove-references-to-the-class-Interpreter
  src/OpalCompiler-Core/IRPrimitive.class.st
Labels: tests passed please review!

#8517 Cleanup-Compiler-Backend-DeadCode
  src/OpalCompiler-Core/IRMethod.class.st
  src/OpalCompiler-Core/IRSequence.class.st
Labels: tests passed please review!

#8496 Adding deprecations that were recommended by DepMiner (accepted by 2 reviewers)
  src/AST-Core/RBVariableNode.class.st
  src/ClassParser/CDClassNameNode.class.st
  src/ClassParser/CDSlotNode.class.st
  src/Deprecated90/RBArgumentNode.class.st
  src/Deprecated90/RBGlobalNode.class.st
  src/Deprecated90/RBInstanceVariableNode.class.st
  src/Deprecated90/RBSelfNode.class.st
  src/Deprecated90/RBSuperNode.class.st
  src/Kernel/Metaclass.class.st
  src/Rubric-Tests/RubSmalltalkEditorTest.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Spec2-Core/SpAbstractListPresenter.class.st
  src/Spec2-Core/SpCheckBoxTableColumn.class.st
  src/Spec2-Core/SpListPresenter.class.st
  src/Spec2-Morphic-Examples/SpMethodBrowser.class.st
  src/Text-Edition/TextEditor.class.st
  src/TraitsV2/MetaclassForTraits.class.st
  src/TraitsV2/Trait.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: tests passed please review!

#8497 fixes #4856 - print on methods should avoid calling blindly print string on their elements
  src/Clap-Core/ClapValidationReport.class.st
  src/ClassParser/RBSlotInitializationNode.class.st
  src/Collections-Sequenceable/Array2D.class.st
  src/FileSystem-Core/FileSystemDirectoryEntry.class.st
  src/Glamour-Announcements/GLMContextChanged.class.st
  src/Glamour-Announcements/GLMMatchingPresentationsChanged.class.st
  src/Glamour-Announcements/GLMPresentationsChanged.class.st
  src/Glamour-Core/GLMPane.class.st
  src/Glamour-Core/GLMPanePort.class.st
  src/Glamour-Core/GLMPort.class.st
  src/Glamour-Core/GLMPortEvent.class.st
  src/Glamour-Core/GLMPortReference.class.st
  src/Glamour-Core/GLMTransmission.class.st
  src/Glamour-Morphic-Widgets/GLMTreeMorphNodeModel.class.st
  src/Hermes/HEMethod.class.st
  src/Kernel-Chronology-Extras/Month.class.st
  src/Kernel/DelayBasicScheduler.class.st
  src/Kernel/Duration.class.st
  src/Keymapping-Core/KMCategoryBinding.class.st
  src/Keymapping-Core/KMCategoryTarget.class.st
  src/Keymapping-Core/KMKeymap.class.st
  src/Manifest-Core/TheManifestBuilder.class.st
  src/Metacello-Core/MetacelloVersionDiffReport.class.st
  src/Monticello/MCVersion.class.st
  src/Morphic-Core/DropEvent.class.st
  src/Morphic-Core/MorphExtension.class.st
  src/Morphic-Core/MouseEvent.class.st
  src/Morphic-Core/MouseMoveEvent.class.st
  src/Morphic-Core/MouseWheelEvent.class.st
  src/Morphic-Core/TransformationMorph.class.st
  src/OSWindow-Core/OSEvent.class.st
  src/Pillar-Core/PRCascadingCounter.class.st
  src/SUnit-Core/TestCase.class.st
  src/SUnit-Core/TestResource.class.st
  src/Shout/SHStyleElement.class.st
  src/Spec2-Morphic-Tests/SpRGBSlidersTest.class.st
  src/System-Changes/ChangeRecord.class.st
  src/System-Localization/Locale.class.st
  src/ThreadedFFI/TFPool.class.st
  src/Tools-Test/OpenToolTest.class.st
  src/UnifiedFFI/FFIEnumeration.class.st
  src/VariablesLibrary/ComputedSlot.class.st
Labels: tests passed please review!

#8519 7662-Must-be-boolean-deoptimization-targeting-wrong-or-block
  src/OpalCompiler-Core/ProtoObject.extension.st
  src/OpalCompiler-Tests/MustBeBooleanTest.class.st
Labels: tests passed please review!

#8523 8520-TwoWay-Become-should-not-loop-infinite-when-out-of-space
  src/Collections-Sequenceable/Array.class.st
Labels: tests passed please review!

#8462 Fixes issue #7616 implementors and senders browsing broken in the debugger
  src/Spec2-Code/SpCodePresenter.class.st
  src/Spec2-Tests/SpCodePresenterTest.class.st
  src/Tools-CodeNavigation-Tests/CNSelectorExtractorTest.class.st
  src/Tools-CodeNavigation/CNSelectorExtractor.class.st
Labels: Need more work, debugger

#8461 Move to Iceberg v2
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/Calypso-SystemPlugins-Monticello-Browser/ClyBrowseIcebergCommitCommand.class.st
  src/Calypso-SystemPlugins-Monticello-Browser/ClyBrowseIcebergPackageCommand.class.st
  src/Calypso-SystemPlugins-Monticello-Browser/ClyBrowseIcebergRepositoryCommand.class.st
  src/Calypso-SystemPlugins-Monticello-Browser/ClyIcebergShowMethodVersionCommand.class.st
  src/Calypso-SystemPlugins-Monticello-Browser/IceTipHiedraHistoryBrowser.extension.st
  src/Calypso-SystemPlugins-Monticello-Browser/IceTipRepositoriesBrowser.extension.st
  src/Calypso-SystemPlugins-Monticello-Browser/IceTipWorkingCopyBrowser.extension.st
Labels: tests passed please review!

#8535 8353-startStepping-is-calling-an-undefined-method
  src/Morphic-Core/PasteUpMorph.class.st
  src/Morphic-Core/WorldMorph.class.st
Labels: tests passed please review!

#8552 8551-Error-when-doing-implementors-of-of-non-string-literals
  src/Tool-Base/SystemNavigation.extension.st
Labels: tests passed please review!

#8543 8042 deprecate and remove pointdist because there is pointdistance to with exactly the same implementation
  src/Athens-Morphic/PolygonMorph.extension.st
  src/Graphics-Canvas/Canvas.class.st
  src/Graphics-Tests/PointTest.class.st
  src/Math-Operations-Extensions/Point.extension.st
Labels: tests passed please review!

#8545 Fixes #4011 Character nextObject crashes Pharo too
  src/Kernel-Tests/ProtoObjectTest.class.st
  src/Kernel/Character.class.st
  src/Kernel/SmallFloat64.class.st
Labels: tests passed please review!

#8541 8540-TFFI-should-support-passing-a-ByteArray-in-a-char-parameter-a-TFStringType
  src/ThreadedFFI-UFFI-Tests/TFUFFIDerivedTypeMarshallingTest.class.st
  src/ThreadedFFI/TFStringType.class.st
Labels: tests passed please review!

#8539 8503-Slot-remove-in-Stateful-Traits
  src/ClassParser/CDAbstractTraitCompositionNode.class.st
  src/ClassParser/CDTraitCompositionBuilder.class.st
  src/ClassParser/CDTraitSlotRemoveNode.class.st
  src/ClassParser/CDTraitSlotRenameNode.class.st
  src/TraitsV2-Tests/T2TraitWithAliasTest.class.st
  src/TraitsV2/TaAbstractComposition.class.st
  src/TraitsV2/TaRemoveSlot.class.st
  src/TraitsV2/Trait.class.st
Labels: tests passed please review!

#8560 fixes #8308: Can't close tabs in System Browser when code has been modified
  src/Calypso-Browser/ClyNotebookPageHeaderPresenter.class.st
Labels: tests passed please review!

#8542 6812-When-executing-a-method-should-not-get-a-IRPopIntoTemp-did-not-undersand-nextByteCideOffsetAfterJump
  src/OpalCompiler-Core/IRJump.class.st
  src/OpalCompiler-Core/IRPopIntoTemp.class.st
  src/OpalCompiler-Core/ProtoObject.extension.st
  src/OpalCompiler-Tests/MustBeBooleanTest.class.st
Labels: tests passed please review!

#8417 remove #defaultWorldMenu and the registration in WorldMorph>>#initialize
  src/Morphic-Core/WorldMorph.class.st
  src/Morphic-Core/WorldState.class.st
Labels: tests passed please review!

#8533 RB - Add rename package refactoring
  src/Refactoring-Changes/RBRefactoryChangeFactory.class.st
  src/Refactoring-Changes/RBRefactoryPackageChange.class.st
  src/Refactoring-Changes/RBRenamePackageChange.class.st
  src/Refactoring-Core/RBClassModelFactory.class.st
  src/Refactoring-Core/RBNamespace.class.st
  src/Refactoring-Core/RBPackage.class.st
  src/Refactoring-Core/RBPackageRefactoring.class.st
  src/Refactoring-Core/RBRenamePackageRefactoring.class.st
  src/Refactoring-Tests-Core/RBRenamePackageTest.class.st
  src/Refactoring2-Transformations-Tests/RBRemoveDirectAccessToVariableTransformationTest.class.st
  src/SystemCommands-PackageCommands/SycRenamePackageCommand.class.st
Labels: tests passed please review!

#8506 Adding deprecations that were recommended by DepMiner (accepted by 1 reviewer)
  src/Clap-Core/ClapCommand.class.st
  src/Collections-Support/LookupKey.class.st
  src/Collections-Support/WeakKeyAssociation.class.st
  src/Deprecated90/RBTemporaryNode.class.st
  src/Kernel/AdditionalMethodState.class.st
  src/Kernel/LiteralVariable.class.st
  src/OSWindow-Core/OSWindowMorphicEventHandler.class.st
  src/OSWindow-Core/OSWindowRenderer.class.st
  src/Rubric/RubTextEditor.class.st
  src/Spec2-Core/SpAbstractTextPresenter.class.st
  src/Spec2-Core/SpLabelledTextInput.class.st
Labels: tests passed please review!

#8563 Cleanup-Deprecated-Tests
  src/Deprecated90/ByteTextConverterTest.class.st
  src/Deprecated90/EUCTextConverterTest.class.st
  src/Deprecated90/Latin1CharsetTest.class.st
  src/Deprecated90/UTF16TextConverterTest.class.st
  src/Deprecated90/UTF8TextConverterTest.class.st
Labels: tests passed please review!

#8538 8451-Wrong-over-optimization-of-mustBeBoolean-magic
  src/OpalCompiler-Core/OCASTTranslatorForEffect.class.st
  src/OpalCompiler-Tests/MustBeBooleanTest.class.st
Labels: tests passed please review!

#8576 MetaLink-LiteralArray-Fix
  src/Reflectivity-Tests/ReflectivityReificationTest.class.st
  src/Reflectivity/RFReification.class.st
Labels: tests passed please review!

#8580 8566-CtrlShiftEnd-runs-Debug-it-keybinding-instead-of-selecting-text
  src/Rubric/RubSmalltalkEditor.class.st
Labels: tests passed please review!

#8579 8554-P9---Problem-with-copy-and-paste-from-Windows-to-ClassBrowser-method-panel-
  src/OSWindow-Core/OSWindowClipboard.class.st
Labels: easyReview, tests passed please review!

#8559 TaRenameSlot-Use-TaRenamedSlotWrapper
  src/TraitsV2/TaAbstractComposition.class.st
  src/TraitsV2/TaRenameSlot.class.st
  src/TraitsV2/TaRenamedSlotWrapper.class.st
Labels: tests passed please review!

#8574 remove-unused-ClassVar-FFICallbackParametersTest
  src/UnifiedFFI-Tests/FFICallbackParametersTest.class.st
Labels: easyReview, tests passed please review!

#8553 RB - Add preview to generate accessors refactoring
  src/Refactoring-Core/RBPushDownMethodRefactoring.class.st
  src/SystemCommands-ClassCommands/SycAbstractAllInstVarAccessorsCommand.class.st
  src/SystemCommands-MethodCommands/SycPushDownMethodCommand.class.st
  src/SystemCommands-MethodCommands/SycPushUpMethodCommand.class.st
  src/SystemCommands-RefactoringSupport/RBAbstractSelectionPresenter.class.st
  src/SystemCommands-RefactoringSupport/RBItemsSelectionPresenter.class.st
  src/SystemCommands-RefactoringSupport/RBMethodsSelectionPresenter.class.st
  src/SystemCommands-RefactoringSupport/RBPushDownPreviewPresenter.class.st
  src/SystemCommands-RefactoringSupport/RBPushUpPreviewPresenter.class.st
  src/SystemCommands-RefactoringSupport/RBSelectClassAndMethodsPresenter.class.st
  src/SystemCommands-RefactoringSupport/RBVariablesSelectionPresenter.class.st
  src/SystemCommands-RefactoringSupport/SycRefactoringPreviewPresenter.class.st
  src/SystemCommands-VariableCommands/Slot.extension.st
Labels: Need more work

#8570 RB - New move to class side method refactoring
  src/Refactoring-Core/RBAbstractClass.class.st
  src/Refactoring-Core/RBMoveMethodToClassSideRefactoring.class.st
  src/Refactoring-Tests-Core/RBMoveMethodToClassSideTest.class.st
  src/SystemCommands-MethodCommands/SycMoveMethodsToClassCommand.class.st
Labels: Need more work

#8531 RB - Improve messages push up method refactoring
  src/Refactoring-Core/RBPullUpMethodRefactoring.class.st
  src/Refactoring-Tests-Core/RBPullUpMethodTest.class.st
Labels: Need more work, tests passed please review!

#8583 Cleanup-ClassVars-Metacello
  src/Metacello-MC/MetacelloConfigTemplate.class.st
  src/Metacello-MC/MetacelloConfigTemplateExample.class.st
Labels: easyReview, tests passed please review!

#8582 Remove-unused-Classvar-GTGenericStackDebugger
  src/GT-Debugger/GTGenericStackDebugger.class.st
Labels: easyReview, tests passed please review!

#8581 6842-May-be-we-can-drop-the-old-squeakform-format-check-in-fromBinaryStream
  src/Graphics-Display Objects/Form.class.st
  src/Graphics-Files/Form.extension.st
Labels: easyReview, tests passed please review!

#8408 upgrading Pharo 9 with Roassal 0.9.6
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: tests passed please review!

#8590 Cleanup-unused-classVar-FFIStringCalloutTest
  src/UnifiedFFI-Tests/FFIStringCalloutTest.class.st
Labels: easyReview, tests passed please review!

#8596 RB - Improve extract set up method refactoring
  src/Refactoring-Core/RBExtractMethodRefactoring.class.st
  src/Refactoring-Core/RBExtractSetUpMethodRefactoring.class.st
  src/Refactoring-Tests-Core/RBDataTest.class.st
  src/Refactoring-Tests-Core/RBExtractSetUpMethodTest.class.st
Labels: tests passed please review!

#8597 RB - Rename method only in specific packages
  src/Calypso-SystemTools-Core/ClySystemBrowserContext.class.st
  src/Refactoring-Core/RBBrowserEnvironment.extension.st
  src/Refactoring-Core/RBChangeMethodNameRefactoring.class.st
  src/Refactoring-Core/RBNamespace.class.st
  src/Refactoring-Core/RBRefactoring.class.st
  src/Refactoring-Tests-Core/RBRenameMethodTest.class.st
  src/SystemCommands-MessageCommands/SycRenameMessageInSomePackagesCommand.class.st
Labels: tests passed please review!

#8598 RB - Improve some warning messages
  src/Refactoring-Core/RBAbstractVariablesRefactoring.class.st
  src/Refactoring-Core/RBChangeMethodNameRefactoring.class.st
  src/Refactoring-Core/RBExpandReferencedPoolsRefactoring.class.st
  src/Refactoring-Core/RBExtractMethodAndOccurrences.class.st
  src/Refactoring-Core/RBPullUpInstanceVariableRefactoring.class.st
  src/Refactoring-Core/RBPullUpMethodRefactoring.class.st
  src/Refactoring-Core/RBRemoveMethodRefactoring.class.st
  src/Refactoring-Core/RBReplaceMethodRefactoring.class.st
Labels: easyReview, tests passed please review!

#8604 Cleanup-unused-classvars-Locale
  src/System-Localization/Locale.class.st
Labels: tests passed please review!

#8605 Cleanup-unused-ivar-RBItemsSelectionPresenter
  src/SystemCommands-RefactoringSupport/RBItemsSelectionPresenter.class.st
Labels: easyReview, tests passed please review!

#8607 Fix-unused-classvars-CDClassWithFullDefinitionExample
  src/ClassParser-Tests/CDClassWithFullDefinitionExample.class.st
Labels: easyReview, tests passed please review!

#8611 cleanup-unused-ClassVar-ISO88597TextConverter
  src/Deprecated90/ISO88597TextConverter.class.st
Labels: tests passed please review!

#8616 Rule for setUp and tearDown should be applied for TestResource too
  src/SUnit-Rules/ReShouldSendSuperSetUpAsFirstMessage.class.st
  src/SUnit-Rules/ReShouldSendSuperTearDownAsLastMessage.class.st
Labels: tests passed please review!

#8620 8613-Unused-class-Variable-in-ZnConstants
  src/Zinc-HTTP/ZnConstants.class.st
Labels: tests passed please review!

#8603 Cleanup-unused-classvars-WindowsStore
  src/FileSystem-Disk/WindowsStore.class.st
Labels: easyReview, tests passed please review!

#8628 fix column width calculous
  src/Morphic-Widgets-FastTable/FTTableContainerMorph.class.st
Labels: tests passed please review!

#8626 6438-TextEditorpluggableYellowButtonActivity-call-dead-code
  src/Text-Edition/TextEditor.class.st
Labels: easyReview, tests passed please review!

#8622 Fix #8621: Improve the help of the new spec-based inspector
  src/Spec2-Help/SpHelpTopics.class.st
Labels: tests passed please review!

#8618 Icon for abstract classes
  src/Kernel/Behavior.class.st
  src/Polymorph-Widgets/Behavior.extension.st
Labels: tests passed please review!

#8624 testNoUnusedClassVariablesLeft-improve
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
Labels: tests passed please review!

#8609 RB - Improve convert temporary to instance variable refactoring
  src/Refactoring-Core/RBTemporaryToInstanceVariableRefactoring.class.st
  src/Refactoring-Tests-Core/RBTemporaryToInstanceVariableTest.class.st
Labels: tests passed please review!

#8619 RB - Refactor methods to use Factory class instead of RB*Change classes directly
  src/Refactoring-Changes/RBRefactoryPackageChange.class.st
  src/Refactoring-Changes/RBRenameClassVariableChange.class.st
  src/Refactoring-Changes/RBRenameInstanceVariableChange.class.st
  src/Refactoring-Changes/RBRenamePackageChange.class.st
  src/Refactoring2-Core/RBAbstractClass2.class.st
  src/Renraku/ReMissingMethodCritique.class.st
  src/Renraku/ReRemoveMethodCritique.class.st
  src/Renraku/ReReplaceNodeCritique.class.st
  src/Renraku/ReTransformationCritique.class.st
Labels: tests passed please review!

#8601 Cleanup-unused-classvars-FTSizeRec
  src/FreeType/FTSizeRec.class.st
Labels: easyReview, tests passed please review!

#8637 Inconsistent casing in Debug menu item
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddConditionalBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddExecutionCounterCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddOnceBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddStaticBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddWatchCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBrowseBreakpointsCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Queries/ClyActiveBreakpointsQuery.class.st
  src/Calypso-SystemPlugins-Reflectivity-Queries/ClyMethodWatchQuery.class.st
  src/Reflectivity/Watch.class.st
Labels: tests passed please review!

#8600 Cleanup-unused-classvars-FT2Handle
  src/FreeType/FT2Handle.class.st
Labels: easyReview, tests passed please review!

#8647 cleanup-ununsed-classvar-LiteralVariableTest
  src/Slot-Tests/LiteralVariableTest.class.st
Labels: tests passed please review!

#8649 cleanup-unused-classVar-ClySubclassLOfClass2FromP1
  src/Calypso-SystemQueries-Tests-P1WithHierarchy/ClySubclassLOfClass2FromP1.class.st
Labels: tests passed please review!

#8645 cleanup-unused-classvar-RBTransformationRuleTestData1
  src/Refactoring-Tests-Core/RBTransformationRuleTestData1.class.st
Labels: tests passed please review!

#8646 cleanup-unused-classvar-ClyClass2FromP1
  src/Calypso-SystemQueries-Tests-P1WithHierarchy/ClyClass2FromP1.class.st
Labels: tests passed please review!

#8650 Fix issue 8642: ClassTrait instance variable vanishing when defining new instance variable
  src/TraitsV2/Trait.class.st
Labels: tests passed please review!

#8648 8644-Rubric-Field-should-not-lose-the-password-state-when-a-font-is-applied
  src/Rubric/RubTextFieldMorph.class.st
Labels: tests passed please review!

#8651 8595 enhance debugger to show the dnu call in the stack
  src/NewTools-Debugger-Extensions/Exception.extension.st
  src/NewTools-Debugger-Extensions/MessageNotUnderstood.extension.st
  src/NewTools-Debugger-Extensions/OupsNullException.extension.st
  src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
  src/NewTools-Debugger-Tests/StDebuggerContextTest.class.st
  src/NewTools-Debugger-Tests/StDebuggerTest.class.st
  src/NewTools-Debugger/StDebugger.class.st
  src/NewTools-Debugger/StDebuggerActionModel.class.st
  src/NewTools-Debugger/StDebuggerContext.class.st
  src/NewTools-Debugger/StDebuggerContextPredicate.class.st
  src/NewTools-Debugger/StDebuggerErrorContextPredicate.class.st
Labels: debugger, tests passed please review!

#8653 Fixing how undefined objects test for undefined variable
  src/Kernel/UndefinedObject.class.st
  src/NewTools-Debugger/StDebuggerErrorContextPredicate.class.st
Labels: debugger, tests passed please review!

#8629 Decompiler-test-and-fix-super-inBlock-classSide
  src/Flashback-Decompiler-Tests/FBDDecompilerTest.class.st
  src/Flashback-Decompiler-Tests/FBDExamples.class.st
  src/Flashback-Decompiler/FBDASTBuilder.class.st
Labels: tests passed please review!
