Repository pharo-project/pharo, pull requests merged in 2021-03, with the labels that each got.

#8614 increasing-number-of-initial-stack-pages
  bootstrap/scripts/4-build.sh
Labels: tests passed please review!

#8675 8544 new debugger impossible to step into debugger complete to sender methods
  src/NewTools-Debugger-Commands/StDebuggerToggleFilterStackCommand.class.st
  src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
  src/NewTools-Debugger-Tests/StMockDebuggerActionModel.class.st
  src/NewTools-Debugger/StDebugger.class.st
  src/NewTools-Debugger/StDebuggerActionModel.class.st
Labels: debugger, tests passed please review!

#8640 Uncommenting to lines in ClyTextEditor so that Cmd-n and Cmd-m in the…
  src/Calypso-SystemTools-QueryBrowser/ClyTextEditor.extension.st
Labels: tests passed please review!

#8686 RB - Remove unnecessary initialization
  src/Refactoring-Changes/RBRemoveClassChange.class.st
Labels: tests passed please review!

#8696 8641-valueWithExit-should-answer-the-result-of-value
  src/Kernel-Tests/BlockClosureTest.class.st
  src/Kernel/BlockClosure.class.st
Labels: tests passed please review!

#8699 8698-Failing-on-CI-ReleaseTesttestThatAllMethodsArePackaged
  src/TraitsV2-Tests/T2TraitTest.class.st
  src/TraitsV2/TraitedClass.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: tests passed please review!

#8660 RB - Add support for traits in RBNamespace
  src/Refactoring-Core/RBAbstractClass.class.st
  src/Refactoring-Core/RBClass.class.st
  src/Refactoring-Core/RBClassModelFactory.class.st
  src/Refactoring-Core/RBCondition.class.st
  src/Refactoring-Core/RBMethod.class.st
  src/Refactoring-Core/RBNamespace.class.st
  src/Refactoring-Core/RBTrait.class.st
  src/Refactoring-Core/RBTraitedMetaclass.class.st
  src/Refactoring-Tests-Core/RBClassToRename.class.st
  src/Refactoring-Tests-Core/RBClassUsingSharedPoolForTestData.class.st
  src/Refactoring-Tests-Core/RBDummy.trait.st
  src/Refactoring-Tests-Core/RBExtractMethodAndOccurrencesTest.class.st
  src/Refactoring-Tests-Core/RBFindAndReplaceTest.class.st
  src/Refactoring-Tests-Core/RBRenameClassTest.class.st
  src/Refactoring-Tests-Core/RBRenameMethodTest.class.st
Labels: tests passed please review!

#8685 RB - Improve messages of remove class command
  src/Calypso-SystemTools-Core/ClyBrowserMorph.extension.st
  src/SystemCommands-ClassCommands/SycRemoveClassCommand.class.st
  src/SystemCommands-RefactoringSupport/RBFindAndReplacePreviewPresenter.class.st
  src/SystemCommands-RefactoringSupport/SycMethodNameEditorPresenter.class.st
  src/SystemCommands-RefactoringSupport/SycRefactoringPreviewPresenter.class.st
Labels: tests passed please review!

#8714 AbstractSessionHandler should be abstract
  src/System-SessionManager/AbstractSessionHandler.class.st
Labels: tests passed please review!

#8707 8678-Clean-unused-Class-Vars-so-we-can-un-skip-testNoUnusedClassVariablesLeft
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
Labels: tests passed please review!

#8716 ReAbstractRuleTestCase should be abstract
  src/GeneralRules-Tests/ReAbstractRuleTestCase.class.st
Labels: tests passed please review!

#8719 8189-testNoUnusedInstanceVariablesLeft-is-skipped
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
Labels: tests passed please review!

#8721 8720-RBTraitedMetaclass-has-unused-ivar
  src/Refactoring-Core/RBTraitedMetaclass.class.st
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
Labels: easyReview, tests passed please review!

#8731 Is ReNodeRewriteRule an abstract class?
  src/Renraku/ReNodeRewriteRule.class.st
Labels: tests passed please review!

#8737 TaAbstractComposition should implement #isAbstract
  src/TraitsV2/TaAbstractComposition.class.st
Labels: tests passed please review!

#8741 Cleanup method categories in TKTAbstractExecutor
  src/TaskIt/TKTAbstractExecutor.class.st
  src/TaskIt/TTaskExecutor.trait.st
Labels: tests passed please review!

#8745 T2AbstractTest should be abstract
  src/TraitsV2-Tests/T2AbstractTest.class.st
Labels: tests passed please review!

#8752 Extract example in FontChooser
  src/Fonts-Chooser/FontChooser.class.st
Labels: tests passed please review!

#8748 Abstract classes in Font packages
  src/Fonts-Abstract/AbstractFont.class.st
  src/Fonts-Chooser/AbstractFontSelectorDialogWindow.class.st
  src/System-Settings-Core/AbstractFontStoredSetting.class.st
Labels: tests passed please review!

#8764 Fixing packages for extension packages in the debugger stack
  src/NewTools-Debugger-Tests/StDebuggerTest.class.st
  src/NewTools-Debugger/StDebugger.class.st
Labels: tests passed please review!

#8768 8502 cannot proceed in debugger when loading fuel and bytecodes have changed
  src/Fuel-Core/FLError.class.st
  src/NewTools-Debugger/StDebuggerErrorContextPredicate.class.st
Labels: tests passed please review!

#8754 Deprecate JapaneseEnvironment leftover methods
  src/Deprecated90/AbstractFont.extension.st
  src/Deprecated90/CharacterScanner.extension.st
  src/Fonts-Abstract/AbstractFont.class.st
  src/Text-Scanning/CharacterScanner.class.st
Labels: tests passed please review!

#8743 Proper method category names in TKTRunner and subclasses
  src/TaskIt/TKTAbstractExecutor.class.st
  src/TaskIt/TKTLocalProcessTaskRunner.class.st
  src/TaskIt/TKTNewProcessTaskRunner.class.st
  src/TaskIt/TKTUIProcessTaskRunner.class.st
Labels: tests passed please review!

#8708 RB - Introduce new refactoring "Merge inst var x in y"
  src/Calypso-SystemTools-Core/ClySystemBrowserContext.class.st
  src/Calypso-SystemTools-Core/SycMergeVariableCommand.extension.st
  src/Calypso-SystemTools-FullBrowser/SycMergeVariableCommand.extension.st
  src/Refactoring-Changes/RBRenameInstanceVariableChange.class.st
  src/Refactoring-Core/RBMergeInstanceVariableIntoAnother.class.st
  src/Refactoring-Core/RBRenameInstanceVariableRefactoring.class.st
  src/Refactoring-Tests-Core/RBMergeInstanceVariableIntoAnotherTest.class.st
  src/SystemCommands-VariableCommands/SycMergeVariableCommand.class.st
  src/SystemCommands-VariableCommands/SycProtectVariableCommand.class.st
  src/SystemCommands-VariableCommands/SycRenameVariableCommand.class.st
Labels: tests passed please review!

#8739 TaskIt: TKTRunner and TKTAbstractExecutor should be abstract
  src/TaskIt/TKTAbstractExecutor.class.st
  src/TaskIt/TKTRunner.class.st
Labels: tests passed please review!

#8724 Package level comments
  src/Manifest-Core/TheManifestBuilder.class.st
Labels: tests passed please review!

#8770 8659 expression leading to error is not highlighted anymore
  src/NewTools-Debugger/StDebugger.class.st
Labels: tests passed please review!

#8780 8185-When-fluid-class-RGClassDefinitionTest-has-one-test-failing
  src/Ring-Definitions-Tests-Core/RGClassDefinitionTest.class.st
Labels: tests passed please review!

#8769 Fixes: #7963 - does not use broken primitives.
  src/NewTools-SystemReporter/StSystemReporter.class.st
Labels: easyReview, tests passed please review!

#8779 Changed ClyOldMessageBrowserAdapter>>open to using realParent to handle cases where parent is nil
  src/Calypso-SystemTools-OldToolCompatibillity/ClyOldMessageBrowserAdapter.class.st
Labels: tests passed please review!

#8773 Added the possibility to create a new method in the class definition tab
  src/Calypso-SystemTools-Core/ClyClassDefinitionEditorToolMorph.class.st
Labels: tests passed please review!

#8783 Update misleading comments in the LibC class
  src/UnifiedFFI/LibC.class.st
Labels: easyReview, tests passed please review!

#8706 Fix #8656 Process class >> #forContext:priority: potentially crashing an image
  src/Kernel/Process.class.st
Labels: tests passed please review!

#8788 RB - Improve refactoring comments
  src/Refactoring-Core/RBCreateAccessorsWithLazyInitializationForVariableRefactoring.class.st
  src/Refactoring-Core/RBMergeInstanceVariableIntoAnother.class.st
  src/Refactoring-Core/RBMoveMethodToClassSideRefactoring.class.st
  src/Refactoring-Core/RBRemoveClassKeepingSubclassesRefactoring.class.st
  src/Refactoring-Core/RBRemoveHierarchyMethodRefactoring.class.st
  src/Refactoring-Core/RBRenameMethodRefactoring.class.st
  src/Refactoring-Core/RBRenamePackageRefactoring.class.st
  src/Refactoring-Core/RBReplaceMethodRefactoring.class.st
  src/Refactoring-Help/RBBrowserClassRefactoringHelp.class.st
  src/Refactoring-Help/RBBrowserMethodRefactoringHelp.class.st
  src/Refactoring-Help/RBBrowserPackageRefactoringHelp.class.st
  src/Refactoring-Help/RBBrowserSupportHelp.class.st
  src/Refactoring-Help/RBBrowserVariableRefactoringHelp.class.st
  src/Refactoring-Tests-Core/RBRemoveClassKeepingSubclassesTest.class.st
Labels: tests passed please review!

#8763 Configuring the spec debugger to force contexts stepping into quick methods
  src/Kernel-Tests/ContextTest.class.st
  src/Kernel/Context.class.st
  src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
  src/NewTools-Debugger/StDebuggerActionModel.class.st
Labels: tests passed please review!

#8610 validate callback failure on exit
  src/ThreadedFFI/FFICallback.extension.st
  src/ThreadedFFI/TFCallback.class.st
  src/ThreadedFFI/TFCallbackInvocation.class.st
Labels: tests passed please review!

#8777 8775-Press-red-exclamation-mark-on-the-middle--raises-an-error
  src/SystemCommands-ClassCommands/SycOpenClassMenuCommand.class.st
Labels: tests passed please review!

#8787 Compiler-Cleanup-OCAbortCompilation
  src/OpalCompiler-Core/OCAbortCompilation.class.st
  src/OpalCompiler-Core/SyntaxErrorNotification.class.st
Labels: tests passed please review!

#8772 Update UnhandledError to reflect the ability for the underlying Exception to resume.
  src/Kernel-Tests/ExceptionTest.class.st
  src/Kernel/Exception.class.st
  src/Kernel/UnhandledError.class.st
Labels: tests passed please review!

#8798 upgrading Pharo 9 with Roassal 0.9.7b
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: tests passed please review!

#8806 8761-Add-a-release-test-for-unclassified-methods
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
Labels: tests passed please review!

#8805 8195-Moving-message-refactoring-is-broken-in-the-implementors-browser
  src/Calypso-Browser/ClyBrowserContext.class.st
Labels: tests passed please review!

#8802 8701-Class-references-show-incorrect-results-when-there-are-super-sends-in-blocks
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/OpalCompiler-Core/IRBytecodeGenerator.class.st
Labels: tests passed please review!

#8801 8695-FTSizeRec-declares-class-variables-without-referencing
  src/FreeType/FTSizeRec.class.st
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
Labels: tests passed please review!

#8804 8655-SurfacePluginDLL-is-crashing-with-the-headless-VM-at-restart
  src/Athens-Cairo/AthensCairoSurface.class.st
  src/Deprecated90/AthensCairoSurface.extension.st
Labels: tests passed please review!

#8674 Fluid class should propose trait: + trait: TEmpty as a default
  src/Calypso-SystemPlugins-Traits-Browser/ClyCreateTraitCommand.class.st
  src/ClassParser/CDFluidClassDefinitionParser.class.st
  src/ClassParser/CDTraitCompositionBuilder.class.st
  src/FluidClassBuilder-Tests/FluidClassBuilderTest.class.st
  src/FluidClassBuilder-Tests/FluidTraitBuilderTest.class.st
  src/FluidClassBuilder/FluidClassBuilder.class.st
  src/FluidClassBuilder/FluidTraitBuilder.class.st
  src/Hermes/HEInstaller.class.st
  src/Kernel-Traits/TEmpty.trait.st
  src/Kernel-Traits/Trait.extension.st
  src/Kernel/FluidClassDefinitionPrinter.class.st
  src/TraitsV2-Tests/T2AbstractTest.class.st
  src/TraitsV2-Tests/T2FluidClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2TraitAnnouncementsTest.class.st
  src/TraitsV2-Tests/T2TraitChangesTest.class.st
  src/TraitsV2-Tests/T2TraitMCDefinitionsTest.class.st
  src/TraitsV2-Tests/T2TraitTest.class.st
  src/TraitsV2/Metaclass.extension.st
  src/TraitsV2/Trait.class.st
Labels: Need more work

#8849 Update-ReleaseTests
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
Labels: tests passed please review!

#8857 RB - Add comments to RBRemoveAllSendersRefactoring
  src/Refactoring-Core/RBRemoveAllSendersRefactoring.class.st
  src/Refactoring-Help/RBBrowserMethodRefactoringHelp.class.st
Labels: tests passed please review!

#8856 Fix 8855: Paste shortcut (cmd/ctrl+V) conflicts with new calypso shortcut
  src/Calypso-SystemTools-Core/SycMergeVariableCommand.extension.st
  src/Calypso-SystemTools-FullBrowser/SycMergeVariableCommand.extension.st
  src/Keymapping-KeyCombinations/KMKeyCombination.class.st
  src/Keymapping-Tests/KMShortcutTest.class.st
Labels: tests passed please review!

#8800 8762-Compiler-Evaluating-an-expression-with-error-with-a-requestor-leads-to-primitive-fail
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OCDoitTest.class.st
Labels: tests passed please review!

#8841 6526-RGTraitDescriptionStrategy-invoke-methods-that-do-not-exist-announcer
  src/Ring-Core/RGTraitDescriptionStrategy.class.st
Labels: tests passed please review!

#8863 Simplify SystemVersion class>>#current
  src/System-Support/SystemVersion.class.st
Labels: tests passed please review!

#8874 ReVariableReferencedOnceRule-show-varname
  src/GeneralRules/ReVariableReferencedOnceRule.class.st
Labels: tests passed please review!

#8877 RB - Improve extract setUp Refactoring
  src/Refactoring-Core/RBExtractMethodAndOccurrences.class.st
  src/Refactoring-Core/RBExtractMethodRefactoring.class.st
  src/Refactoring-Core/RBExtractSetUpMethodAndOccurrences.class.st
  src/Refactoring-Core/RBExtractSetUpMethodRefactoring.class.st
  src/Refactoring-Core/RBFindAndReplaceRefactoring.class.st
  src/Refactoring-Core/RBFindAndReplaceSetUpRefactoring.class.st
  src/Refactoring-Tests-Core/RBDataTest.class.st
  src/Refactoring-Tests-Core/RBExtractSetUpMethodAndOccurrencesTest.class.st
  src/Refactoring-Tests-Core/RBExtractSetUpMethodTest.class.st
  src/Refactoring-Tests-Core/RBFindAndReplaceSetUpTest.class.st
  src/Refactoring-Tests-Core/RBFindAndReplaceTest.class.st
  src/Refactoring-Tests-Core/RBRefactoringTest.class.st
  src/Refactoring-Tests-Core/RBTest.class.st
  src/SystemCommands-MessageCommands/SycFindAndReplaceMethodCommand.class.st
  src/SystemCommands-MethodCommands/SycFindAndReplaceSetUpCommand.class.st
  src/SystemCommands-MethodCommands/SycNewMoveToClassSideCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycExtractSetUpRefactoring.class.st
Labels: tests passed please review!

#8885 8793-some-settings-for-code-completion-are-not-working
  src/HeuristicCompletion-Model/CoASTResultSetBuilder.class.st
  src/HeuristicCompletion-Model/CoGlobalVariablesHeuristic.class.st
  src/HeuristicCompletion-Model/CoResultSet.class.st
  src/HeuristicCompletion-Tests/CoResultSetTest.class.st
  src/Morphic-Core/HandMorph.class.st
  src/Morphic-Core/KeyboardEvent.class.st
  src/NECompletion-Morphic/CompletionEngine.class.st
Labels: tests passed please review!

#8882 ReVariableAssignedLiteralRule-Skip-PoolVars
  src/GeneralRules/ReVariableAssignedLiteralRule.class.st
  src/Kernel/ClassVariable.class.st
  src/Kernel/Variable.class.st
  src/Slot-Tests/ClassVariableTest.class.st
Labels: tests passed please review!

#8884 [fix] fixes #8878: Fluid class and more got broken by recent calypso...
  src/BaselineOfCalypso/BaselineOfCalypso.class.st
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
  src/Calypso-SystemTools-Core-Tests/ClyClassDefinitionEditorToolMorphTest.class.st
  src/Calypso-SystemTools-Core-Tests/ClyFullBrowserBlockingUI.class.st
  src/Calypso-SystemTools-Core-Tests/MockClyContainerTab.class.st
  src/Calypso-SystemTools-Core-Tests/MockClyFullBrowserClassContext.class.st
  src/Calypso-SystemTools-Core-Tests/MockMethodGroupQuery.class.st
  src/Calypso-SystemTools-Core-Tests/package.st
  src/Calypso-SystemTools-Core/ClyClassDefinitionEditorToolMorph.class.st
  src/FluidClassBuilder/FluidClassBuilder.class.st
  src/FluidClassBuilder/FluidTraitBuilder.class.st
Labels: tests passed please review!

#8898 RB - Add preview when use "extract method refactoring"
  src/NautilusRefactoring/NautilusRefactoring.class.st
  src/Refactoring-Core/RBExtractMethodAndOccurrences.class.st
  src/Refactoring-Core/RBExtractMethodRefactoring.class.st
  src/Refactoring-Core/RBRefactoring.class.st
  src/Refactoring-Tests-Core/RBRefactoringTest.class.st
  src/SystemCommands-SourceCodeCommands/SycExtractMethodCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycExtractSetUpRefactoring.class.st
Labels: tests passed please review!

#8909 Variable-model-Shadowing
  src/GeneralRules/ReTempVarOverridesInstVarRule.class.st
  src/Kernel/Character.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCShadowVariableWarning.class.st
Labels: tests passed please review!

#8913 fixes #8904 Better class comment for some SUnit classes
  src/ParametrizedTests/PaSelectedCasesExampleTest.class.st
  src/ParametrizedTests/PaSimpleMatrixExampleTest.class.st
  src/ParametrizedTests/ParametrizedTestCase.class.st
  src/ParametrizedTests/ParametrizedTestMatrix.class.st
  src/SUnit-Core/TestAsserter.class.st
  src/SUnit-Core/TestCase.class.st
  src/SUnit-Core/TestResource.class.st
  src/SUnit-Core/TestSuite.class.st
Labels: tests passed please review!

#8917 8009-Rule-required-for-shadowed-variables
  src/AST-Core/RBProgramNode.class.st
  src/GeneralRules-Tests/ReTempVarOverridesInstVarRuleTest.class.st
  src/GeneralRules/ReTempVarOverridesInstVarRule.class.st
Labels: tests passed please review!

#8915 testNoUnusedInstanceVariablesLeft-down-to-19
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
Labels: tests passed please review!

#8911 8525-Errors--Insufficient-buffer-size-to-read-current-working-directory-at-the-launch-of-a-new-image-with-not-supported-yet-and-ever-StrikeFont-error
  src/System-Platforms/WinPlatform.class.st
  src/ThreadedFFI/TFFIBackend.class.st
Labels: tests passed please review!

#8842 6970-win32ModuleName-not-implemented
  src/UnifiedFFI/FFILibrary.class.st
Labels: tests passed please review!

#8928 Speedup-reflective-read-IndexedSlot
  src/Kernel/IndexedSlot.class.st
Labels: tests passed please review!

#8919 8194-Enhance-Welcome-with-Build-Date
  src/Pharo-WelcomeHelp/WelcomeHelp.class.st
Labels: tests passed please review!
