Repository pharo-project/pharo, pull requests merged in 2021-01, with the labels that each got.

#8225 Remove unused ivars in TaskIt
  src/TaskIt/TKTLocalProcessTaskRunner.class.st
  src/TaskIt/TKTPromise.class.st
  src/TaskIt/TKTTaskExecution.class.st
  src/TaskIt/TKTUIProcessTaskRunner.class.st
  src/TaskIt/TKTWorkerPool.class.st
Labels: tests passed please review!

#8247 Remove unused class FT2BitmapSize
  src/FreeType/FT2BitmapSize.class.st
Labels: tests passed please review!

#8230 Remove unused ivars in ClassParser package
  src/ClassParser-Tests/CDClassWithFullDefinitionExample.class.st
  src/ClassParser-Tests/CDFluidClassParserTest.class.st
  src/ClassParser/CDClassDefinitionNode.class.st
  src/ClassParser/CDClassDefinitionParser.class.st
  src/ClassParser/CDFluidClassDefinitionParser.class.st
  src/ClassParser/CodeParser.class.st
Labels: tests passed please review!

#8238 Cleanup unused ivars in ExampleForTestWithSharedPool
  src/Kernel-Tests/ExampleForTestWithSharedPool.class.st
  src/Kernel-Tests/FluidClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/LegacyClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/OldClassDefinitionPrinterTest.class.st
Labels: tests passed please review!

#8251 Remove unused vars in HandMorph
  src/Morphic-Core/HandMorph.class.st
Labels: tests passed please review!

#8278 Care on unused ivars in StepThroughTest
  src/Debugger-Model-Tests/StepThroughTest.class.st
Labels: tests passed please review!

#8245 Cleanup unused ivar in FLDebuggerStackMaterialization
  src/Fuel-Tools-Pharo/FLDebuggerStackMaterialization.class.st
Labels: tests passed please review!

#8263 Unused ivars in FluidClassBuilder
  src/FluidClassBuilder/FluidClassBuilder.class.st
Labels: tests passed please review!

#8279 8241-Warning-PotentialOutDatedDependencyWarning-Kernel-FFI-Kernel-dependency-declared-in-the-package-Manifest-as-manuallyResolvedDependencies-not-detected-as-a-dependency
  src/Collections-Tests/ManifestCollectionsTests.class.st
  src/Kernel/ManifestKernel.class.st
Labels: tests passed please review!

#8281 8280-From-Twitter-There-is-an-error-in-the-image-tutorial-related-to-read-only-literals
  src/ProfStef-Core/PharoSyntaxTutorial.class.st
Labels: tests passed please review!

#8255 improving-TFFI-semaphore-pool
  Jenkinsfile
  src/ThreadedFFI-Tests/TFPoolTest.class.st
  src/ThreadedFFI-Tests/TFStructTest.class.st
  src/ThreadedFFI-UFFI-Tests/TFUFFIBasicTypeMarshallingTest.class.st
  src/ThreadedFFI/TFCharType.class.st
  src/ThreadedFFI/TFDoubleType.class.st
  src/ThreadedFFI/TFExternalSemaphore.class.st
  src/ThreadedFFI/TFFIBackend.class.st
  src/ThreadedFFI/TFFloatType.class.st
  src/ThreadedFFI/TFPool.class.st
  src/ThreadedFFI/TFPooledExternalAsyncCall.class.st
  src/ThreadedFFI/TFRunner.class.st
  src/ThreadedFFI/TFWorker.class.st
  src/UnifiedFFI-Tests/FFICalloutAPITest.class.st
Labels: tests passed please review!

#8276 Care on unused ivars in ThreadedFFI
  src/ThreadedFFI/TFExternalAsyncCall.class.st
Labels: tests passed please review!

#8285 Unused ivars in Kernel slot classes
  src/Kernel/Slot.class.st
  src/Kernel/UndefinedSlot.class.st
Labels: tests passed please review!

#8290 Cleanup MockForCompilation
  src/OpalCompiler-Tests/MockForCompilation.class.st
Labels: tests passed please review!

#8292 RubTextEditor has unused ivar
  src/Rubric/RubTextEditor.class.st
Labels: tests passed please review!

#8296 Cleanups in package 'TraitsV2-Tests'
  src/TraitsV2-Tests/T2FluidClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2OldPharoClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/TMockWithComplexSlot.trait.st
  src/TraitsV2-Tests/TMockWithUseAndSlot.trait.st
Labels: tests passed please review!

#8301 8283-ClassDescriptiondefinition-called-from-GTSpotterExtensionsOnClassTesttestBasic-has-been-deprecated
  src/GT-SpotterExtensions-Core/GTSpotterExtensionsOnClassTest.class.st
Labels: tests passed please review!

#8206 8169 - Compiled code 'literals' do not behave the same that compiled code 'hasLiteral'
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/Kernel/CompiledCode.class.st
Labels: tests passed please review!

#8227 Small cleanup OCASTSemanticAnalyzer: #declareVariableNode:
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/Reflectivity/RFSemanticAnalyzer.class.st
Labels: tests passed please review!

#8294 Unused ivars in Rubric Spec2 dialogs
  src/Rubric-SpecFindReplaceDialog/SpRubFindReplaceDialog.class.st
  src/Rubric-SpecFindReplaceDialog/SpRubFindReplaceService.class.st
Labels: tests passed please review!

#8302 merge newtools 0.5.1
  src/NewTools-ChangeSorter/SpChangeSorterPresenter.class.st
  src/NewTools-Debugger-Breakpoints-Tools/StHaltCache.class.st
  src/NewTools-Debugger-Extensions/RBProgramNode.extension.st
  src/NewTools-Debugger/ArgumentVariable.extension.st
  src/NewTools-Debugger/SpCodePresenter.extension.st
  src/NewTools-Debugger/StDebugger.class.st
  src/NewTools-Debugger/StDebuggerActionModel.class.st
  src/NewTools-Debugger/StDebuggerContext.class.st
  src/NewTools-Debugger/StDebuggerContextInteractionModel.class.st
  src/NewTools-Debugger/StDebuggerContextReceiverInteractionModel.class.st
  src/NewTools-Debugger/StDebuggerErrorContextPredicate.class.st
  src/NewTools-Debugger/StDebuggerInspector.class.st
  src/NewTools-Debugger/StDebuggerInspectorModel.class.st
  src/NewTools-Debugger/StDebuggerInspectorTempNode.class.st
  src/NewTools-Debugger/TemporaryVariable.extension.st
  src/NewTools-Inspector-Extensions/Class.extension.st
  src/NewTools-Inspector-Extensions/Collection.extension.st
  src/NewTools-Inspector-Extensions/Dictionary.extension.st
  src/NewTools-Inspector-Extensions/RBProgramNode.extension.st
  src/NewTools-Inspector-Extensions/Variable.extension.st
  src/NewTools-Inspector/StInspectionContext.class.st
  src/NewTools-Inspector/StInspector.class.st
  src/NewTools-Inspector/StInspectorContextNamedTempNode.class.st
  src/NewTools-Inspector/StInspectorProtoObjectNode.class.st
  src/NewTools-Inspector/StInspectorRefreshService.class.st
  src/NewTools-Inspector/StInspectorSlotNode.class.st
  src/NewTools-Inspector/StInspectorTempNode.class.st
  src/NewTools-Inspector/StNodeCollector.class.st
  src/NewTools-Inspector/StObjectContextPresenter.class.st
  src/NewTools-Inspector/StObjectInspectorPresenter.class.st
  src/NewTools-Inspector/StRawInspection.class.st
  src/NewTools-Morphic/StPharoMorphicConfiguration.class.st
  src/NewTools-Playground/StPlayground.class.st
  src/NewTools-Sindarin-Commands/SindarinSkipThroughSelectionCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinSkipUpToSelectionCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToNextCallCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToNextCallInClassCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToNextCallInObjectCommand.class.st
Labels: tests passed please review!

#8303 New tools v0.5.1.1 advanced steps
  src/BaselineOfNewTools/BaselineOfNewTools.class.st
  src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
  src/NewTools-Debugger-Tests/StDebuggerCodeCommandTreeBuilderTest.class.st
  src/NewTools-Debugger-Tests/StDebuggerContextTest.class.st
  src/NewTools-Debugger-Tests/StDebuggerInspectorTest.class.st
  src/NewTools-Debugger-Tests/StDebuggerObjectForTests.class.st
  src/NewTools-Debugger-Tests/StDebuggerStackCommandTreeBuilderTest.class.st
  src/NewTools-Debugger-Tests/StDebuggerTest.class.st
  src/NewTools-Debugger-Tests/StTestDebuggerProvider.class.st
  src/NewTools-Debugger/StDebugger.class.st
  src/NewTools-Debugger/StDebuggerCodeCommandTreeBuilder.class.st
  src/NewTools-Sindarin-Commands-Tests/SindarinCommandsTest.class.st
  src/NewTools-Sindarin-Commands-Tests/SindarinTestCommandDebugger.class.st
  src/NewTools-Sindarin-Commands-Tests/SindarinTestObjectToVisit.class.st
  src/NewTools-Sindarin-Commands-Tests/SindarinTestVisitor.class.st
  src/NewTools-Sindarin-Commands-Tests/package.st
  src/NewTools-Sindarin-Commands/SindarinCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToMethodEntryCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToNextCallInClassCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToNextCallInObjectCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToNextInstanceCreation.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToReturnCommand.class.st
  src/NewTools-Sindarin-Commands/StDebugger.extension.st
  src/Sindarin-Tests/SindarinBytecodeToASTCacheTest.class.st
  src/Sindarin-Tests/SindarinDebugSessionMock.class.st
  src/Sindarin-Tests/SindarinDebuggerTest.class.st
  src/Sindarin/Context.extension.st
  src/Sindarin/SindarinBytecodeToASTCache.class.st
  src/Sindarin/SindarinDebugSession.class.st
  src/Sindarin/SindarinDebugger.class.st
  src/Sindarin/SindarinScript.class.st
  src/Sindarin/StepToNextDoIterationDbgScript.class.st
  src/Sindarin/StepUntilAboutToSignalExceptionDbgScript.class.st
Labels: tests passed please review!

#8331 8216-FluidClass-API-for-traits-
  src/FluidClassBuilder-Tests/FluidClassBuilderTest.class.st
  src/FluidClassBuilder-Tests/TViewModelMock2.trait.st
  src/TraitsV2/MetaclassForTraits.class.st
  src/TraitsV2/Trait.class.st
Labels: need help

#8314 RB - Fix issue replace message send by another message send
  src/Refactoring-Core/RBChangeMethodNameRefactoring.class.st
  src/Refactoring-Core/RBNamespace.class.st
  src/Refactoring-Core/RBRefactoring.class.st
  src/Refactoring-Core/RBReplaceMethodRefactoring.class.st
  src/Refactoring-Tests-Core/RBReplaceMethodTest.class.st
  src/Refactoring-Tests-Core/RBSplitCascadeRefactoringTest.class.st
  src/System-Support/SystemNavigation.class.st
  src/SystemCommands-MessageCommands/SycRemoveMessageArgumentCommand.class.st
  src/SystemCommands-MessageCommands/SycReplaceMessageCommand.class.st
Labels: tests passed please review!

#8306 Add literalsEvenTheOnesInTheInnerBlocks to the CleanBlockClosure
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/Kernel/CleanBlockClosure.class.st
  src/OpalCompiler-Tests/OpalCompilerTest.class.st
Labels: tests passed please review!

#8347 8174 st peel to first command looks wrong
  src/NewTools-Debugger-Commands/StPeelToFirstCommand.class.st
  src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
  src/NewTools-Debugger-Tests/StDebuggerCommandTest.class.st
  src/NewTools-Debugger-Tests/StDummyDebuggerPresenter.class.st
  src/NewTools-Debugger-Tests/StTestDebuggerProvider.class.st
  src/NewTools-Debugger/StDebugger.class.st
  src/NewTools-Debugger/StDebuggerActionModel.class.st
Labels: debugger

#8221 Refactor ChangeSetClassChangesTest to use ClassFactoryForTestCase.
  src/SUnit-Core/ClassFactoryForTestCase.class.st
  src/Tests/ChangeSet.extension.st
  src/Tests/ChangeSetClassChangesTest.class.st
  src/Tool-Finder/FinderUI.class.st
Labels: tests passed please review!

#8350 Fix enclosing and adding comment to KeyboardKey
  src/Rubric/RubTextEditor.class.st
  src/System-Platforms/KeyboardKey.class.st
Labels: tests passed please review!

#8351 Smalltalk-restartMethods
  src/Kernel/Behavior.class.st
  src/Morphic-Core/MorphicCoreUIManager.class.st
  src/Polymorph-Widgets/MorphicUIManager.class.st
  src/System-Support/SmalltalkImage.class.st
  src/Tool-ImageCleaner/ImageCleaner.class.st
Labels: tests passed please review!

#8356 Unused ivars in ListPresenter
  src/Spec-Core/ListPresenter.class.st
Labels: tests passed please review!

#8359 Using rub text decorators to show the next instruction to execute
  src/NewTools-Debugger-Tests/StDebuggerTest.class.st
  src/NewTools-Debugger/StDebugger.class.st
Labels: Reviewed and Ready to Integrate

#8372 Fixing assertion layout in the debugger inspector when we encounter a shouldnt:raise: failure
  src/NewTools-Debugger-Tests/StDebuggerInspectorTest.class.st
  src/NewTools-Debugger-Tests/StTestDebuggerProvider.class.st
  src/NewTools-Debugger/StDebuggerInspector.class.st
Labels: tests passed please review!

#8360 PRRichTextComposer-resetStylers
  src/Pillar-ExporterRichText/PRRichTextComposer.class.st
Labels: tests passed please review!

#8362 add WriteBarrierTest class>>#restartMethods
  src/Kernel-Tests-Extended/WriteBarrierTest.class.st
Labels: tests passed please review!

#8373 5427 debugger into on dead process hangs image
  src/NewTools-Debugger-Commands/StReturnValueCommand.class.st
  src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
  src/NewTools-Debugger-Tests/StDebuggerCommandTest.class.st
  src/NewTools-Debugger-Tests/StDebuggerContextPredicateTest.class.st
  src/NewTools-Debugger/StDebugger.class.st
  src/NewTools-Debugger/StDebuggerActionModel.class.st
  src/NewTools-Debugger/StDebuggerContextPredicate.class.st
  src/NewTools-Sindarin-Tools/StSindarinBytecodeDebuggerPresenter.class.st
Labels: tests passed please review!

#8339 improve-win32-platform-specific-implementations
  src/FFI-Kernel/ExternalAddress.class.st
  src/FFI-Kernel/ExternalData.class.st
  src/FFI-Kernel/ExternalObject.class.st
  src/SUnit-Core/TestSuite.class.st
  src/SUnit-Tests/RPackage.extension.st
  src/System-Platforms/Win32WideString.class.st
  src/System-Platforms/WinPlatform.class.st
Labels: tests passed please review!

#8365 hasBindingThatBeginsWith-Layouts
  src/Kernel-Tests-Extended/ClassTest.class.st
  src/Kernel/AbstractLayout.class.st
Labels: tests passed please review!

#8364 clean the class variables in RubTextSelectionColor
  src/Rubric/RubTextSelectionColor.class.st
Labels: tests passed please review!

#8380 RB - Add message to kwon how many occurrences were replaced
  src/Refactoring-Core/RBExtractMethodAndOccurrences.class.st
  src/Refactoring-Core/RBFindAndReplaceRefactoring.class.st
  src/SystemCommands-MessageCommands/SycFindAndReplaceMethodCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycExtractMethodCommand.class.st
Labels: Need more work

#8419 8354-SycRemoveMessageArgumentCommand-with-unused-ivar
  src/SystemCommands-MessageCommands/SycRemoveMessageArgumentCommand.class.st
Labels: tests passed please review!

#8240 8168-CompiledMethodreferencedClasses-should-not-take-class-variables-into-account
  src/Kernel-Tests-Extended/ClassTest.class.st
  src/System-Support/Behavior.extension.st
  src/System-Support/CompiledMethod.extension.st
Labels: tests passed please review!

#8425 RBExtractMethodAndOccurrences-unused-ivar
  src/Refactoring-Core/RBExtractMethodAndOccurrences.class.st
Labels: tests passed please review!

#8422 Remove-unused-vars-RB
  src/Refactoring-Changes/RBRefactoryChange.class.st
  src/Refactoring-Tests-Core/RBRefactoringTest.class.st
  src/Refactoring2-Transformations-Tests/RBTransformationTest.class.st
Labels: tests passed please review!

#8427 7763-Does-BlockClosurecull-need-the-pragma-debuggerCompleteToSender
  src/Kernel/BlockClosure.class.st
Labels: tests passed please review!

#8428 Added empty selection interval to force SpCodePresenter to auto-scroll.
  src/NewTools-Debugger/StDebugger.class.st
Labels: easyReview, tests passed please review!

#8432 remove two unused ivars in GT-Tests
  src/GT-Tests-Spotter-Processors/SptCatalogProjectsProcessorTest.class.st
  src/GT-Tests-Spotter-Processors/SptHelpProcessorTest.class.st
Labels: tests passed please review!

#8431 spec1-clean-ivars
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
  src/Spec-Core/SpecLayoutFrame.class.st
  src/Spec-Core/SpecPragmaCollector.class.st
  src/Spec-Layout/SpecTableLayoutAddSpacer.class.st
Labels: tests passed please review!

#8437 OCDoitTest-testDoItContextReadIvar
  src/OpalCompiler-Tests/OCDoitTest.class.st
Labels: tests passed please review!

#8433 remove some unused class variables 1
  src/Athens-Core/AthensCurveFlattener.class.st
  src/Morphic-Base/BalloonMorph.class.st
  src/Morphic-Base/JobProgressMorph.class.st
  src/Morphic-Base/MenuItemMorph.class.st
  src/Polymorph-Widgets/TextEditorDialogWindow.class.st
  src/Settings-System/SystemSystemSettings.class.st
  src/Tool-FileList/FileList.class.st
Labels: easyReview, tests passed please review!

#8447 7889-GZipReadStream--fileIntoNewChangeSet-fullFileName
  src/Compression/GZipReadStream.class.st
  src/System-FileRegistry/GZipReadStream.extension.st
Labels: tests passed please review!

#8426 8379-Debugger-Contextat-infinite-loop-when-pressing-Through-in-a-test-case-condition
  src/Debugging-Core/Context.extension.st
  src/Kernel-Tests-Extended/ClassUsedInInstructionStreamTest.class.st
  src/Kernel-Tests-Extended/InstructionStreamTest.class.st
  src/Kernel/Context.class.st
  src/Kernel/Process.class.st
  src/ReleaseTests/ObsoleteTest.class.st
Labels: tests passed please review!

#8430 Removing suspicious update code in the debugger inspector, and fixing variable update problem with recursive call
  src/NewTools-Debugger-Tests/StDebuggerInspectorTest.class.st
  src/NewTools-Debugger/StDebuggerInspector.class.st
Labels: tests passed please review!

#8438 Move-ArgumentNamesTest-to-Debugger-Model-Tests-Core
  src/Debugger-Model-Tests/ArgumentNamesTest.class.st
  src/Debugger-Model/Boolean.extension.st
  src/Debugger-Model/Collection.extension.st
  src/Debugger-Model/Integer.extension.st
  src/Debugger-Model/Metaclass.extension.st
  src/Debugger-Model/MetaclassForTraits.extension.st
  src/Debugger-Model/Number.extension.st
  src/Debugger-Model/Object.extension.st
  src/Debugger-Model/String.extension.st
  src/Tools/Object.extension.st
Labels: easyReview, tests passed please review!

#8452 7987-Class-definition-should-not-be-evaluated-if-it-contains-a-syntax-error
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
Labels: tests passed please review!

#8455 8454-Removing-more-users-of-oldDefinition
  src/NewTools-Inspector-Extensions/Class.extension.st
  src/System-Changes/ChangeSet.class.st
  src/System-Changes/ClassChangeRecord.class.st
  src/Tests/ChangeSetClassChangesTest.class.st
Labels: tests passed please review!
