Repository pharo-project/pharo, pull requests merged in 2021-10, with the labels that each got.

#10091 Fix failing tests in CI
  src/Zinc-Zodiac/ZnHTTPSTest.class.st
Labels: easyReview

#9982 Fix #9907: improes DoesNotUnderstand exception's messageText
  src/Kernel-Tests/MessageNotUnderstoodTest.class.st
  src/Kernel/MessageNotUnderstood.class.st
Labels: tests passed please review!

#10101 Small cleanups: ByteString
  src/Collections-Strings/ByteString.class.st
Labels: tests passed please review!

#10103 Cleanup Changeset class
  src/System-Changes/ChangeSet.class.st
  src/System-Changes/ManifestSystemChanges.class.st
Labels: tests passed please review!

#10087 10025-ObjectLayout-classlayoutForType-should-be-moved-to-the-Monticello-package
  src/Kernel/ObjectLayout.class.st
  src/Monticello/ObjectLayout.extension.st
Labels: tests passed please review!, easyReview

#10120 9927-Check-Pharo9-Defining-variables-in-the-debugger-DNU-isForScripting-9925
  src/Rubric/RubAbstractSmalltalkMode.class.st
Labels: tests passed please review!, easyReview
