Repository pharo-project/pharo, pull requests merged in 2021-09, with the labels that each got.

#9876 Cleanup-Deprecated-Code-09-01
  src/Deprecated90/AthensCairoPatternSurfacePaint.extension.st
  src/Deprecated90/AthensCanvasWrapper.extension.st
  src/Deprecated90/Behavior.extension.st
  src/Deprecated90/CompiledCode.extension.st
  src/Deprecated90/EmbeddedFreeTypeFontFontDescription.class.st
  src/Deprecated90/FontFamilyAbstract.class.st
  src/Deprecated90/FontFamilyMemberAbstract.class.st
  src/Deprecated90/FontProviderAbstract.class.st
  src/Deprecated90/FreeTypeFontFamilyMember.extension.st
  src/Deprecated90/FuzzyMatcher.extension.st
  src/Deprecated90/HistoryCollection.class.st
  src/Deprecated90/IconicListItem.class.st
  src/Deprecated90/MultiByteFileStreamFileOutTestClass.class.st
  src/Deprecated90/Object.extension.st
  src/Deprecated90/SmalltalkEditingState.class.st
  src/Deprecated90/TabLabelItem.class.st
  src/Deprecated90/UITestCase.class.st
Labels: tests passed please review!

#9875 Remove UnixEnvironment>>#unsetEnv:
  src/System-OSEnvironments/UnixEnvironment.class.st
Labels: tests passed please review!

#9799 Cleaning up `ValueLink` objects
  src/Collections-Sequenceable-Tests/LinkedListTest.class.st
  src/Collections-Support-Tests/ValueLinkForTesting.class.st
  src/Collections-Support-Tests/ValueLinkTest.class.st
  src/Collections-Support/Link.class.st
  src/Collections-Support/ValueLink.class.st
  src/Kernel/Object.class.st
  src/Kernel/UndefinedObject.class.st
Labels: tests passed please review!

#9881 categorize-more-09-01
  src/AST-Core/RBParseErrorNode.class.st
  src/Calypso-Ring/RGClassDefinitionCompiler.class.st
  src/Metacello-MC/MetacelloMCBaselineProject.class.st
  src/Metacello-MC/MetacelloMCProject.class.st
  src/Morphic-Widgets-Pluggable/MulticolumnLazyListMorph.class.st
  src/Network-Tests/NetworkIPv6StringTest.class.st
  src/Refactoring-Core/RBCopyPackageRefactoring.class.st
  src/Ring-Core/RGReadOnlyBackend.class.st
  src/Ring-Tests-Core/RGBackendTest.class.st
  src/Ring-Tests-Core/RGEnvironmentBackendTest.class.st
  src/Spec-MorphicAdapters/MorphicFastTableAdapter.class.st
Labels: tests passed please review!

#9880 Cleanup-Deprecated-DisplayMedium
  src/Graphics-Display Objects/DisplayMedium.class.st
  src/Graphics-Display Objects/Form.class.st
Labels: tests passed please review!

#9849 9848-Allow-reflective-execution-if-CompiledMethod-without-sending-to-the-receiver
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#9873 Cleanup FileSystemDirectoryEntry
  src/FileSystem-Core/FileSystemDirectoryEntry.class.st
Labels: tests passed please review!

#9886 Cleanup-Deprecated-09-02
  src/AST-Core/RBComment.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBVariableNode.class.st
  src/Announcements-Core/Announcer.class.st
  src/Announcements-Core/WeakSubscriptionBuilder.class.st
  src/BaselineOfParametrizedTests/BaselineOfParametrizedTests.class.st
  src/Beacon-Core/SignalLogger.class.st
  src/Beacon-Core/StringSignal.class.st
  src/Beacon-Core/WrapperSignal.class.st
  src/ClassParser/CDClassDefinitionParser.class.st
  src/ClassParser/CDClassNameNode.class.st
  src/ClassParser/CDSlotNode.class.st
  src/Collections-Abstract/Collection.class.st
  src/Collections-Streams/Stream.class.st
  src/Collections-Strings-Tests/StringTest.class.st
  src/Collections-Strings/String.class.st
  src/Collections-Support/LookupKey.class.st
  src/Collections-Support/WeakKeyAssociation.class.st
  src/Debugging-Core/Context.extension.st
  src/Deprecated10/SystemWindow.extension.st
  src/Deprecated90/Character.extension.st
  src/Deprecated90/CompiledMethod.extension.st
  src/Deprecated90/String.extension.st
  src/FreeType/FreeTypeCache.class.st
  src/FreeType/FreeTypeFont.class.st
  src/Kernel-Chronology-Extras/Timespan.extension.st
  src/Kernel/AdditionalMethodState.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/Metaclass.class.st
  src/Kernel/Slot.class.st
  src/Math-Operations-Extensions/Integer.extension.st
  src/Metacello-Core/MetacelloGenericProjectSpec.class.st
  src/Metacello-Core/MetacelloMethodSection.class.st
  src/Metacello-Core/MetacelloPlatform.class.st
  src/Metacello-MC/MetacelloAbstractPackageSpec.extension.st
  src/Metacello-MC/MetacelloPackageSpec.class.st
  src/Metacello-ToolBox/MetacelloToolBox.class.st
  src/OSWindow-Core/OSWindowMorphicEventHandler.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/Random-Core/Random.class.st
  src/Refactoring-Critics/RBLintRule.class.st
  src/Refactoring2-Transformations/RBProgramNode.extension.st
  src/Reflectivity/ReflectiveMethod.class.st
  src/Ring-Core/RGBehavior.class.st
  src/Ring-Core/RGInstanceVariableSlot.class.st
  src/Ring-Core/RGObject.class.st
  src/Ring-Core/RGSlot.class.st
  src/Ring-Core/RGVariable.class.st
  src/Rubric-Tests/RubSmalltalkEditorTest.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Rubric/RubTextEditor.class.st
  src/SUnit-Core/TestSuite.class.st
  src/Text-Edition/TextEditor.class.st
  src/Tool-Base/Object.extension.st
  src/TraitsV2/MetaclassForTraits.class.st
  src/TraitsV2/Trait.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: tests passed please review!

#9887 Remove-Deprecated-09-03
  src/Clap-Commands-Pharo/ClapPharoApplication.class.st
  src/Clap-Core/ClapCommand.class.st
  src/Clap-Core/ClapCompositeMatch.class.st
  src/Clap-Core/ClapParameterized.class.st
  src/Morphic-Examples/WidgetExample.class.st
  src/Polymorph-Widgets/TEasilyThemed.trait.st
  src/System-Support/VirtualMachine.class.st
Labels: tests passed please review!

#9910 Cleanup-Compiler-remove-tests-optionFullBlockClosure
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Tests/OCASTTranslatorMappingForFullBlockClosuresTest.class.st
  src/OpalCompiler-Tests/OCASTTranslatorTest.class.st
  src/OpalCompiler-Tests/OCBytecodeDecompilerTest.class.st
  src/OpalCompiler-Tests/OCCompiledMethodIntegrityTest.class.st
  src/OpalCompiler-Tests/OCNewCompilerWithChangesFunctionalTest.class.st
  src/OpalCompiler-Tests/OCSourceCode2BytecodeTest.class.st
  src/OpalCompiler-Tests/OpalCompilerTest.class.st
Labels: tests passed please review!

#9900 Expand String class comment.
  src/Collections-Strings/String.class.st
Labels: tests passed please review!

#9902 9879-AthensCairoSurface-deprecated-methods-still-have-senders
  src/Athens-Cairo/AthensCairoSurface.class.st
  src/Deprecated90/AthensCairoSurface.extension.st
Labels: tests passed please review!

#9908 9901-Fluid-Class-Parser-gets-wrong-symbols-from-the-layout-kind
  src/ClassParser-Tests/CDExistingClassDefinitionTest.class.st
  src/ClassParser-Tests/CDFluidClassParserTest.class.st
  src/ClassParser/CDFluidClassDefinitionParser.class.st
  src/Kernel/AbstractLayout.class.st
  src/Kernel/ByteLayout.class.st
  src/Kernel/CompiledMethodLayout.class.st
  src/Kernel/DoubleByteLayout.class.st
  src/Kernel/DoubleWordLayout.class.st
  src/Kernel/EmptyLayout.class.st
  src/Kernel/EphemeronLayout.class.st
  src/Kernel/FixedLayout.class.st
  src/Kernel/ImmediateLayout.class.st
  src/Kernel/ObjectLayout.class.st
  src/Kernel/VariableLayout.class.st
  src/Kernel/WeakLayout.class.st
  src/Kernel/WordLayout.class.st
Labels: tests passed please review!

#9903 9888-FFI-remove-gcpointer
  src/UnifiedFFI/ExternalAddress.extension.st
  src/UnifiedFFI/FFIExternalArray.class.st
Labels: tests passed please review!, easyReview

#9917 9038-Windows-edges-grabbing-for-resizing-not-optimal
  src/Morphic-Base/HaloMorph.class.st
  src/Morphic-Core/HandMorph.class.st
  src/OSWindow-SDL2/SDLWindowsPlatform.class.st
  src/OSWindow-SDL2/WinPlatform.extension.st
Labels: tests passed please review!

#9920 Pharo10 - 9038-windows edges grabbing for resizing not optimal
  src/Morphic-Base/HaloMorph.class.st
  src/Morphic-Core/HandMorph.class.st
  src/OSWindow-SDL2/SDLWindowsPlatform.class.st
  src/OSWindow-SDL2/WinPlatform.extension.st
Labels: tests passed please review!

#9277 Rewrote and improved String >> skipAnySubstring:startingAt:
  src/Collections-Abstract-Tests/TAsStringCommaAndDelimiterTest.trait.st
  src/Collections-Strings-Tests/StringTest.class.st
  src/Collections-Strings/String.class.st
Labels: tests passed please review!

#9426 9308 code critics improving critic description api change api hints architectural
  src/Renraku/ReSmalllintChecker.class.st
  src/Renraku/ReThemeAccessRule.class.st
  src/System-Settings-Rules/SettingDontTranslateDescriptionRule.class.st
Labels: tests passed please review!

#9937 enhance code changes browser a little bit
  src/EpiceaBrowsers/EpFileLogNode.class.st
  src/EpiceaBrowsers/EpLogNode.class.st
  src/EpiceaBrowsers/EpLogNodeGraphPresenter.class.st
  src/EpiceaBrowsers/EpMonitorLogNode.class.st
  src/EpiceaBrowsers/EpUnifiedBrowserPresenter.class.st
Labels: tests passed please review!

#9529 Reenable FFICallbackTest on Windows
  src/UnifiedFFI-Tests/FFICallbackTest.class.st
Labels: tests passed please review!, Pharo10

#9942 9928-Do-not-use-optionFullBlockClosure-in-OCASTTranslatorvisitBlockNode
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
Labels: tests passed please review!

#9949 CDSlotNode-NoIndex
  src/ClassParser/CDSlotNode.class.st
Labels: tests passed please review!

#9923 9909-Deprecate-typeOfClass-and-kind-and-add-mcType-instead
  src/Deprecated10/Behavior.extension.st
  src/Deprecated10/ObjectLayout.extension.st
  src/Deprecated10/UndefinedObject.extension.st
  src/Kernel/Behavior.class.st
  src/Kernel/ByteLayout.class.st
  src/Kernel/CompiledMethodLayout.class.st
  src/Kernel/EphemeronLayout.class.st
  src/Kernel/FixedLayout.class.st
  src/Kernel/ImmediateLayout.class.st
  src/Kernel/ObjectLayout.class.st
  src/Kernel/UndefinedObject.class.st
  src/Kernel/VariableLayout.class.st
  src/Kernel/WeakLayout.class.st
  src/Kernel/WordLayout.class.st
  src/Monticello/Class.extension.st
Labels: tests passed please review!

#9952 9948-OCRequestorScope-does-not-like-empty-variable-names
  src/OpalCompiler-Core/OCRequestorScope.class.st
  src/OpalCompiler-Tests/OCCompileWithFailureTest.class.st
Labels: tests passed please review!

#9941 NoSymbolCreation-hasPackageMatchingExtensionName
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: tests passed please review!

#9958 Cleanup-Duplicated-Methods-09-14
  src/Fonts-Abstract/StubFixedFont.class.st
  src/HelpSystem-Core/Trait.extension.st
  src/Renraku/ReNodeBasedRule.class.st
  src/Ring-Core/RGBehaviorStrategy.class.st
  src/Ring-Core/RGObject.class.st
  src/Ring-Core/RGReadOnlyBackend.class.st
  src/Ring-Core/RGReadOnlyImageBackend.class.st
  src/Ring-Core/RGSlot.class.st
  src/Ring-Core/RGTraitV2Strategy.class.st
  src/Rubric/RubAnnotationDisplayer.class.st
  src/Rubric/RubFindReplaceDialogWindow.class.st
  src/Rubric/RubScrolledTextExtraSurface.class.st
  src/System-SessionManager/StartupUIManager.class.st
  src/TaskIt/TKTLocalProcessTaskRunner.class.st
  src/Tool-Workspace/RubWorkspaceBarRuler.class.st
  src/TraitsV2/TraitBuilderEnhancer.class.st
Labels: tests passed please review!, easyReview

#9957 Cleanup-deprecated-09-14
  src/Kernel/CompiledCode.class.st
  src/OSWindow-Core/OSWindowRenderer.class.st
  src/OSWindow-SDL2/OSSDL2WindowHandle.class.st
  src/Polymorph-Widgets/MorphicUIManager.class.st
  src/Polymorph-Widgets/UITheme.class.st
  src/Ring-Core/RGVariable.class.st
Labels: tests passed please review!

#9967 Cleanup-Deprecated-09-15
  src/Clap-Core/ClapParameter.class.st
  src/Deprecated10/Point.extension.st
  src/FileSystem-Path/Path.class.st
  src/Kernel/ClassDescription.class.st
  src/Math-Operations-Extensions/Point.extension.st
  src/Morphic-Widgets-FastTable/FTSelectionChanged.class.st
  src/Morphic-Widgets-FastTable/FTSelectionStrategy.class.st
  src/Morphic-Widgets-FastTable/FTStrongSelectionChanged.class.st
  src/Morphic-Widgets-FastTable/FTTableMorph.class.st
  src/Spec-Deprecated/ComposablePresenter.extension.st
  src/UnifiedFFI-Legacy/Object.extension.st
Labels: tests passed please review!

#9930 Cleanup-tests-fullblocks
  src/OpalCompiler-Tests/IRBuilderTest.class.st
  src/OpalCompiler-Tests/IRPrinterTest.class.st
  src/OpalCompiler-Tests/IRVisitorTest.class.st
  src/OpalCompiler-Tests/OCBytecodeDecompilerTest.class.st
  src/OpalCompiler-Tests/OCBytecodeGeneratorTest.class.st
  src/OpalCompiler-Tests/OCNewCompilerWithChangesFunctionalTest.class.st
Labels: tests passed please review!

#9926 9925-Defining-variables-in-the-debugger-DNU-isForScripting
  src/Rubric/RubAbstractSmalltalkMode.class.st
Labels: tests passed please review!

#9978 Cleanup-Duplicated-Methods-09-17
  src/Morphic-Base/Form.extension.st
  src/Morphic-Base/TextAnchor.class.st
  src/Morphic-Widgets-Windows/SystemWindow.class.st
  src/SystemCommands-MessageCommands/SycFindAndReplaceMethodCommand.class.st
  src/SystemCommands-MessageCommands/SycReplaceMessageCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycSourceCodeCommand.class.st
  src/TaskIt/TKTUIProcessTaskRunner.class.st
  src/ThreadedFFI-UFFI-Tests/BenchTFFIWorker.class.st
  src/ThreadedFFI-UFFI-Tests/TFTestLibraryUsingSameThreadRunner.class.st
  src/ThreadedFFI/TFOOPType.class.st
  src/ThreadedFFI/TFStringType.class.st
  src/TraitsV2/Trait.class.st
  src/TraitsV2/TraitedMetaclass.class.st
  src/UnifiedFFI/FFIExternalString.class.st
Labels: tests passed please review!

#9981 9933-isDeprecated-should-not-check-for-the-category
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel-Tests-Extended/DeprecatedClassForTest.class.st
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#9939 9936-MCClassDefinitionkindOfSubclass-wrong-for-user-defined-layouts
  src/Monticello-Tests/MCClassDefinitionTest.class.st
  src/Monticello/MCClassDefinition.class.st
Labels: tests passed please review!

#9988 do not re-parse in ReShouldSendSuperSetUpAsFirstMessage and ReShouldSendSuperTearDownAsLastMessage
  src/SUnit-Rules/ReShouldSendSuperSetUpAsFirstMessage.class.st
  src/SUnit-Rules/ReShouldSendSuperTearDownAsLastMessage.class.st
Labels: tests passed please review!

#9969 9965-CI-ZipArchiveTesttestArchiveWithThousandFilesShouldWork-sometimes-times-out
  src/Compression-Tests/ZipArchiveTest.class.st
Labels: tests passed please review!

#9983 9955-add-comments-to-mcType-subclassDefiningSymbol-kindOfSubclass
  src/Kernel/Behavior.class.st
  src/Kernel/ByteLayout.class.st
  src/Kernel/CompiledMethodLayout.class.st
  src/Kernel/DoubleByteLayout.class.st
  src/Kernel/DoubleWordLayout.class.st
  src/Kernel/EphemeronLayout.class.st
  src/Kernel/FixedLayout.class.st
  src/Kernel/ImmediateLayout.class.st
  src/Kernel/ObjectLayout.class.st
  src/Kernel/UndefinedObject.class.st
  src/Kernel/VariableLayout.class.st
  src/Kernel/WeakLayout.class.st
  src/Kernel/WordLayout.class.st
  src/Monticello/Behavior.extension.st
  src/Monticello/ByteLayout.extension.st
  src/Monticello/CompiledMethodLayout.extension.st
  src/Monticello/EphemeronLayout.extension.st
  src/Monticello/FixedLayout.extension.st
  src/Monticello/ImmediateLayout.extension.st
  src/Monticello/ObjectLayout.extension.st
  src/Monticello/UndefinedObject.extension.st
  src/Monticello/VariableLayout.extension.st
  src/Monticello/WeakLayout.extension.st
  src/Monticello/WordLayout.extension.st
  src/Ring-Core/RGBehaviorStrategy.class.st
  src/Ring-Core/RGBehaviorStrategyUser.class.st
  src/Ring-Core/RGClassDescriptionStrategy.class.st
  src/Ring-Core/RGTraitV2DescriptionStrategy.class.st
Labels: tests passed please review!

#6768 [Enable Flaky Tests] Enable continuation flaky test
  src/Kernel-Tests/ContinuationTest.class.st
Labels: Pharo10

#9989 Cleanup-Duplicated-Methods-09-18
  src/AST-Core-Tests/RBMethodNodeTest.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyQueryBrowserMorph.extension.st
  src/DrTests-Tests/DTMockPlugin.class.st
  src/Graphics-Primitives/ManifestGraphicsPrimitives.class.st
  src/Kernel-Chronology-Extras/Month.class.st
  src/Metacello-Core/MetacelloProjectSpecLoadError.class.st
  src/Metacello-Cypress/MetacelloCypressBaselineProject.class.st
  src/Metacello-MC/MetacelloNullRecordingMCSpecLoader.class.st
  src/Monticello/MCDirectoryRepository.class.st
  src/MonticelloGUI/MCTool.class.st
  src/Morphic-Core/Morph.class.st
  src/Morphic-Core/NullWorldRenderer.class.st
  src/OSWindow-SDL2/OSSDL2BackendWindow.class.st
  src/Polymorph-Widgets/SystemWindow.extension.st
  src/Refactoring-Core/RBAbstractClass.class.st
  src/Refactoring-Core/RBMoveMethodToClassSideRefactoring.class.st
  src/Refactoring-Environment/RBPragmaEnvironment.class.st
  src/Refactoring2-Transformations-Tests/RBBasicDummyLintRuleTest.class.st
  src/Refactoring2-Transformations/RBClassTransformation.class.st
  src/Ring-Core/RGBehaviorStrategy.class.st
  src/Ring-Core/RGElement.class.st
  src/Ring-Core/RGMetaclassStrategy.class.st
  src/Ring-Core/RGMetaclassTraitV2Strategy.class.st
  src/Ring-Tests-Core/RGEnvironmentBackendTest.class.st
  src/Slot-Core/ManifestSlotCore.class.st
  src/System-Model/Model.class.st
  src/System-OSEnvironments/PlatformIndependentEnvironment.class.st
  src/SystemCommands-SourceCodeCommands/SycExtractSetUpRefactoring.class.st
  src/Transcript-Tool/ManifestTranscriptTool.class.st
Labels: tests passed please review!, easyReview

#10000 9946-CI-Flaky-test-ProcessSpecificTesttestDynamicVariable
  src/Kernel-Tests/ProcessSpecificTest.class.st
Labels: tests passed please review!

#9897 Release test for #basicNew categorization
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
Labels: tests passed please review!

#9944 Migrated RBTemporaryToInstanceVariableRefactoring to RBTemporaryToIns…
  src/Refactoring2-Transformations-Tests/RBTemporaryToInstanceVariableParametrizedTest.class.st
  src/Refactoring2-Transformations/RBTemporaryToInstanceVariableTransformation.class.st
Labels: tests passed please review!

#9998 9970-ReConsistencyCheckRule-is-a-very-bad-name
  src/GeneralRules/ReUseIsEmptyNotSizeRule.class.st
Labels: tests passed please review!, easyReview

#9945 Migrating RBMoveMethodToClassRefactoring to RBMoveMethodToClassTransformation
  src/Refactoring2-Transformations-Tests/RBMoveMethodToClassParametrizedTest.class.st
  src/Refactoring2-Transformations/RBMoveMethodToClassTransformation.class.st
Labels: tests passed please review!

#10009 Fix: #7974 deprecate openAndTruncateForWriteFile:
  src/Deprecated10/File.extension.st
  src/Files/File.class.st
Labels: tests passed please review!

#10003 BACKPORT-6311-Enhance-Completion-to-be-more-fluid-in-large-images
  src/HeuristicCompletion-Model/CoASTResultSetBuilder.class.st
  src/HeuristicCompletion-Model/CoFetcher.class.st
  src/HeuristicCompletion-Model/CoNarrowHistoryFetcher.class.st
  src/HeuristicCompletion-Model/CoNarrowHistoryItem.class.st
  src/HeuristicCompletion-Model/CoResultSet.class.st
  src/HeuristicCompletion-Tests/CoNarrowHistoryFetcherTest.class.st
  src/HeuristicCompletion-Tests/CoRepeatedHierarchyImplementedSelectorsFetcherTest.class.st
  src/NECompletion/NECEntry.class.st
Labels: tests passed please review!

#9974 update Spec version to v1.0.3 and NewTools to v0.6.10
  src/BaselineOfPharo/BaselineOfPharo.class.st
  src/GT-SpotterExtensions-Core/HelpTopic.extension.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: Need more work

#10039 Fixed #9964. Refactored the hardcoded Ring method #kindOfSubclass using dispatch and moved it to the superclass
  src/Ring-Core/RGBehaviorStrategy.class.st
  src/Ring-Core/RGBitsLayout.class.st
  src/Ring-Core/RGByteLayout.class.st
  src/Ring-Core/RGClassDescriptionStrategy.class.st
  src/Ring-Core/RGEphemeronLayout.class.st
  src/Ring-Core/RGImmediateLayout.class.st
  src/Ring-Core/RGLayout.class.st
  src/Ring-Core/RGTraitDescriptionStrategy.class.st
  src/Ring-Core/RGTraitV2DescriptionStrategy.class.st
  src/Ring-Core/RGVariableLayout.class.st
  src/Ring-Core/RGWeakLayout.class.st
Labels: tests passed please review!

#10064 Integrate Roassal3 v0.9.9c
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: tests passed please review!

#10040 Keep isQuick checks to the single place it matters
  src/Debugger-Model/DebugSession.class.st
  src/Kernel/Process.class.st
Labels: tests passed please review!

#10049 Markdown documentation for regex
  doc/Regex/1-Introduction.md
  doc/Regex/2-WhatsNew.md
  doc/Regex/3-Syntax.md
  doc/Regex/4-Usage.md
  doc/Regex/5-ImplementationNotes.md
  doc/Regex/6-License.md
  src/Collections-Strings/String.class.st
Labels: tests passed please review!

#10048 Fixes #10042 enhance help system to be microdown based
  doc/gen_announcementsframework.md
  doc/gen_contributetobasecode.md
  doc/gen_epicea.md
  doc/gen_freetypefonts.md
  doc/gen_helponhelp.md
  doc/gen_importingresources.md
  doc/gen_pharoenvironmenthelp.md
  doc/gen_pharotutorial.md
  doc/gen_refactoringframework.md
  doc/gen_regularexpressionsframework.md
  doc/gen_renrakuqualityrules.md
  doc/gen_rpackage.md
  doc/gen_spec.md
  doc/gen_sunitframework.md
  doc/gen_thesettingbrowser.md
  doc/gen_welcome.md
  doc/gen_worldmenuitems.md
  doc/gen_writedocumentationwithwikilikesyntax.md
  src/HelpSystem-Core/CustomHelp.class.st
  src/HelpSystem-Core/CustomHelpMicrodownFormatter.class.st
  src/HelpSystem-Core/CustomHelpTextFormatter.class.st
  src/HelpSystem-Core/HelpExporter.class.st
  src/HelpSystem-Core/HelpTopic.class.st
Labels: tests passed please review!

#10084 Small cleanups - Breakpoint
  src/Reflectivity/Breakpoint.class.st
Labels: tests passed please review!

#10074 10073-Cleanup-class-parser-support-for-slots-in-old-style-class-def-not-needed
  src/ClassParser-Tests/ASTClassBuilderTest.class.st
  src/ClassParser-Tests/CDSlotParserArgumentingSlotTest.class.st
  src/ClassParser-Tests/CDSlotParserSimpleExplicitSlotTest.class.st
  src/ClassParser-Tests/CDSlotParserSimpleInstanceVariableTest.class.st
  src/ClassParser/CDClassDefinitionParser.class.st
Labels: tests passed please review!
