Repository pharo-project/pharo, pull requests merged in 2022-09, with the labels that each got.

#11624 Cleanup: remove Point3 class
  src/FluidClassBuilder/Point3.class.st
Labels: tests passed please review!

#11604 11597-RPackagetoTagName-possibly-creates-an-extra-symbol
  src/RPackage-Core/RPackage.class.st
Labels: tests passed please review!

#11637 11635-Compiler-eval-an-expression-with-halt-and-bindings-opens-Emergency-Evaluator
  src/OpalCompiler-Core/OCExtraBindingScope.class.st
  src/OpalCompiler-Tests/OCDoitTest.class.st
Labels: tests passed please review!

#11614 adding entries in the debug world menu to enable / disable all breakpoints in the image
  src/Reflectivity/Breakpoint.class.st
Labels: tests passed please review!

#11583 Attempt to fix scrolling behavior in RubAbstractTextArea & friends
  src/Rubric/RubAbstractTextArea.class.st
  src/Rubric/RubScrolledTextMorph.class.st
Labels: tests passed please review!

#11638 backportPharo10-11635-Compiler-eval-an-expression
  src/OpalCompiler-Core/OCExtraBindingScope.class.st
Labels: tests passed please review!

#11608 Fix leaking subscriptions in SpRubFindReplaceService
  src/Rubric-SpecFindReplaceDialog/SpRubFindReplaceService.class.st
Labels: tests passed please review!

#11600 Fix behavior of sum: on collections of doubles
  src/Collections-Abstract/Collection.class.st
  src/Collections-Abstract/SequenceableCollection.class.st
  src/Collections-Arithmetic-Tests/CollectionArithmeticTest.class.st
Labels: tests passed please review!

#11644 FTTableMorph: Allow expansion/collapse of nodes using arrow keys
  src/Calypso-Browser/ClyCollapsedDataSource.class.st
  src/Calypso-Browser/ClyNoChildrenError.class.st
  src/Calypso-Browser/ClyQueryViewMorph.class.st
  src/Morphic-Widgets-FastTable/FTSelectionRejected.class.st
  src/Morphic-Widgets-FastTable/FTTableMorph.class.st
Labels: tests passed please review!

#11487 [Quick review] fix #11265: Underscore in class name breaks text completion
  src/NECompletion-Tests/CompletionEngineTest.class.st
  src/NECompletion/Character.extension.st
Labels: tests passed please review!

#11647 FTTableMorph: Pass some keyboard events to the filter field if it is focused
  src/Calypso-Browser/FTTableMorph.extension.st
  src/Morphic-Widgets-FastTable/FTTableMorph.class.st
  src/Rubric/RubScrolledTextMorph.class.st
Labels: tests passed please review!

#11493 [improvement] add microsecond to API
  src/Kernel-Tests/DurationTest.class.st
  src/Kernel-Tests/FluidClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/LegacyClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/OldClassDefinitionPrinterTest.class.st
  src/Kernel/ChronologyConstants.class.st
  src/Kernel/Duration.class.st
Labels: tests passed please review!

#11663 Improve FileReference>>=
  src/FileSystem-Core/FileReference.class.st
  src/FileSystem-Tests-Core/FileReferenceTest.class.st
Labels: tests passed please review!

#11667 Expand Heap, Interval, LinkedList class comments
  src/Collections-Sequenceable/Heap.class.st
  src/Collections-Sequenceable/Interval.class.st
  src/Collections-Sequenceable/LinkedList.class.st
Labels: tests passed please review!

#11673 Creating a user interface for Time Profiler and Andreas Profiler
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfProfilerUI/BaselineOfProfilerUI.class.st
  src/BaselineOfProfilerUI/package.st
  src/ProfilerUI/AndreasSystemProfiler.extension.st
  src/ProfilerUI/FTTreeItem.extension.st
  src/ProfilerUI/ManifestProfilerUI.class.st
  src/ProfilerUI/MessageTally.extension.st
  src/ProfilerUI/ProfilerCodePresenter.class.st
  src/ProfilerUI/ProfilerInputPresenter.class.st
  src/ProfilerUI/ProfilerModel.class.st
  src/ProfilerUI/ProfilerNumberInput.class.st
  src/ProfilerUI/ProfilerPresenter.class.st
  src/ProfilerUI/ProfilerResultsPresenter.class.st
  src/ProfilerUI/ProfilerResultsTreeRootChangedAnnouncement.class.st
  src/ProfilerUI/ProfilerToolbarButtonPresenter.class.st
  src/ProfilerUI/ProfilerToolbarPresenter.class.st
  src/ProfilerUI/ProfilerTreeTablePresenter.class.st
  src/ProfilerUI/ProfilingFinishedAnnouncement.class.st
  src/ProfilerUI/ProfilingResultsDisplayedAnnouncement.class.st
  src/ProfilerUI/ProfilingStartedAnnouncement.class.st
  src/ProfilerUI/QSystemTally.extension.st
  src/ProfilerUI/SpMorphicProfilerTreeTableAdapter.class.st
  src/ProfilerUI/TallyModel.class.st
  src/ProfilerUI/TallyModelAndreas.class.st
  src/ProfilerUI/TallyModelTime.class.st
  src/ProfilerUI/TimeProfiler.extension.st
  src/ProfilerUI/package.st
Labels: more-information-needed

#11666 Adds executable comments to False and True classes
  src/Kernel/False.class.st
  src/Kernel/True.class.st
  src/UnifiedFFI/False.extension.st
  src/UnifiedFFI/True.extension.st
Labels: tests passed please review!

#11564 Fix case insensitive auto-completion setting
  src/HeuristicCompletion-Model/CoCompletionContext.class.st
  src/HeuristicCompletion-Model/CoGlobalVariableFetcher.class.st
  src/HeuristicCompletion-Tests/CoMockSystemNavigation.class.st
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#11664 SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0 on Linux
  src/OSWindow-SDL2/SDL2ConstantsHint.class.st
  src/OSWindow-SDL2/SDLUnixPlatform.class.st
  src/OSWindow-SDL2/Unix64Platform.extension.st
Labels: tests passed please review!

#11662 Cleaning CharacterSet class >> #allCharacters
  src/Collections-Support/CharacterSet.class.st
Labels: tests passed please review!

#11660 Deprecated method Character class >> #allCharacters and replaced its references
  src/AST-Core/RBScanner.class.st
  src/Collections-Strings-Tests/CharacterTest.class.st
  src/Fuel-Tests-Core/FLBasicSerializationTest.class.st
  src/Kernel/Character.class.st
Labels: tests passed please review!

#11689 DrTest see extension classes
  src/DrTests-CommentsToTests/DTCommentTestConfiguration.class.st
  src/DrTests-CommentsToTests/DTCommentToTestPlugin.class.st
  src/DrTests/DTDefaultPluginPresenter.class.st
  src/DrTests/DTFilterableListPresenter.class.st
  src/RPackage-Core/RPackage.class.st
Labels: tests passed please review!

#11695 deprecate taskbarIcon and systemIcon
  src/Calypso-SystemTools-Core/ClyClassIconTableDecorator.class.st
  src/Commander2-UI/CmUICommandGroup.class.st
  src/DrTests/DrTests.class.st
  src/EpiceaBrowsers/EpUnifiedBrowserPresenter.class.st
  src/HelpSystem-Core/CustomHelp.class.st
  src/HelpSystem-Core/CustomHelp2.class.st
  src/MenuRegistration/MenuRegistrationExample.class.st
  src/MonticelloGUI/MCWorkingCopyBrowser.class.st
  src/Morphic-Base/Object.extension.st
  src/Morphic-Core/WorldMorph.class.st
  src/Morphic-Widgets-FastTable/FTBasicTreeListDataSource.class.st
  src/Morphic-Widgets-FastTable/FTExampleClassInfoTableDataSource.class.st
  src/Morphic-Widgets-FastTable/FTExampleDataSource.class.st
  src/Morphic-Widgets-Taskbar/SystemWindow.extension.st
  src/Morphic-Widgets-Taskbar/TShowInTaskbar.trait.st
  src/Morphic-Widgets-Taskbar/TaskbarItemMorph.class.st
  src/Morphic-Widgets-Taskbar/UITheme.extension.st
  src/Morphic-Widgets-Windows/SystemWindow.class.st
  src/Polymorph-Widgets/Object.extension.st
  src/SUnit-UI/TestRunner.class.st
  src/SystemCommands-RefactoringSupport/RBAbstractSelectionPresenter.class.st
  src/Text-Edition/EditorFindReplaceDialogWindow.class.st
  src/Tool-FileList/FileList.class.st
  src/Tool-ProcessBrowser/ProcessBrowser.class.st
  src/Tool-Profilers/TimeProfiler.class.st
  src/Transcript-Tool/ThreadSafeTranscript.extension.st
Labels: tests passed please review!

#11668 clean String reading from FFI to return bytes to allow decoding with any decoder.
  src/FFI-Kernel/ExternalAddress.class.st
  src/FFI-Kernel/ExternalData.class.st
  src/FreeType/FT2Face.class.st
  src/OSWindow-SDL2/OSSDL2Driver.class.st
  src/System-OSEnvironments/Win32Environment.class.st
  src/ThreadedFFI-UFFI-Tests/TFUFFIDerivedTypeMarshallingTest.class.st
  src/ThreadedFFI/TFStringType.class.st
  src/UnifiedFFI/ByteArray.extension.st
  src/UnifiedFFI/ExternalData.extension.st
Labels: tests passed please review!

#11701 11613-Review-RBLiteralNode-classvalue
  src/AST-Core/RBLiteralNode.class.st
Labels: tests passed please review!

#11711 Integrate Roassal3 v0.9.9i2
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: tests passed please review!

#11708 Pharo11: Bug fix + code cleanup for issue #11705: Error: Instances of RBProtocolEnvironment are not indexable
  src/Refactoring-Environment/RBBrowserEnvironmentWrapper.class.st
Labels: tests passed please review!

#11690 11631-Clarify-if-TViewModelMock3-is-in-correct-package
  src/ClassParser-Tests/CDFluidClassParserTest.class.st
  src/ClassParser-Tests/TViewModelMock3.trait.st
Labels: tests passed please review!

#11714 Moving Deferred messages to instance side
  src/Morphic-Core/MorphicRenderLoop.class.st
  src/Morphic-Core/WorldMorph.class.st
  src/Morphic-Core/WorldState.class.st
  src/Polymorph-Widgets/MorphicUIManager.class.st
  src/TaskIt/TKTUIProcessTaskRunner.class.st
  src/Tool-ProcessBrowser/ProcessBrowser.class.st
Labels: tests passed please review!

#11722 11720-Improve-ReUtilityMethodsRule
  src/GeneralRules/ReUtilityMethodsRule.class.st
Labels: tests passed please review!

#11706 Pharo10: Bug fix + code cleanup for issue #11705: Error: Instances of RBProtocolEnvironment are not indexable
  src/Refactoring-Environment/RBBrowserEnvironmentWrapper.class.st
Labels: tests passed please review!, Pharo10

#11721 Add Point>>#isInRectangle
  src/Graphics-Tests/PointTest.class.st
  src/Kernel/Point.class.st
  src/Kernel/Rectangle.class.st
Labels: tests passed please review!

#11719 Make title bar layout dependent on new settings option and OS
  src/Polymorph-Widgets/ThemeSettings.class.st
  src/Polymorph-Widgets/UITheme.class.st
  src/Settings-Polymorph/PolymorphSystemSettings.class.st
Labels: tests passed please review!

#11716 Faster Array>>asX and Array>>as:
  src/Collections-Abstract/ArrayedCollection.class.st
  src/Collections-Abstract/Collection.class.st
  src/Collections-Sequenceable/Array.class.st
  src/Collections-Sequenceable/Interval.class.st
  src/Collections-Sequenceable/OrderedCollection.class.st
  src/Collections-Sequenceable/SortedCollection.class.st
  src/Kernel/Object.class.st
  src/Text-Core/RunArray.class.st
Labels: tests passed please review!

#11728 Integrate Roassal3 v0.9.9j
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: tests passed please review!

#11698 Prevent BlockClosure>>benchFor: to loop infinitely
  src/Kernel-Chronology-Extras/BlockClosure.extension.st
  src/Kernel-Tests-Extended/BlockClosureTest.extension.st
Labels: tests passed please review!

#11737 Class definition popup uses the default class syntax (fluid with the new default)
  src/Kernel/ClassDefinitionPrinter.class.st
  src/Kernel/FluidClassDefinitionPrinter.class.st
  src/Kernel/LegacyClassDefinitionPrinter.class.st
  src/Kernel/OldPharoClassDefinitionPrinter.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
Labels: tests passed please review!

#11699 Add executable comments on Collection for do: and stream related
  src/Collections-Abstract/Collection.class.st
Labels: tests passed please review!
