Repository pharo-project/pharo, pull requests merged in 2022-11, with the labels that each got.

#11795 Fix #11794: Enhance CI to use the right VM version
  bootstrap/scripts/envversion.sh
  bootstrap/scripts/runKernelTests.sh
  bootstrap/scripts/runTests.sh
Labels: tests passed please review!

#11855 Fix: #11854 removing useless code and obsolete pragmas!
  src/Metacello-Bitbucket/MCBitbucketRepository.class.st
  src/Metacello-GitHub/MCGitHubRepository.class.st
  src/Metacello-Gitlab/MCGitlabRepository.class.st
Labels: tests passed please review!

#11857 Fix #11843 renaming a manifest breaks.
  src/Refactoring-Core/RBRenamePackageRefactoring.class.st
  src/Refactoring2-Transformations/RBRenamePackageTransformation.class.st
Labels: tests passed please review!

#11837 [improvement] backport of #11487
  src/NECompletion-Tests/CompletionEngineTest.class.st
  src/NECompletion/Character.extension.st
Labels: tests passed please review!

#11864 11842-Context-menu-on-class-variables-opens-debug-menu
  src/ClassParser/CDSharedVariableNode.class.st
Labels: tests passed please review!

#11849 Fixes the problem related to backwards selection. Closes #11848
  src/Rubric-Tests/RubEditingStateTest.class.st
  src/Rubric/RubEditingState.class.st
  src/Rubric/RubTextEditor.class.st
Labels: tests passed please review!

#11860 #instVarNamed: does not need to send #asSymbol to the name
  src/Kernel/AbstractLayoutScope.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/Object.class.st
  src/Ring-Core/RGPointerLayout.class.st
Labels: tests passed please review!

#11830 Package 'Coverage' as a higher level API for code coverage
  src/BaselineOfCoverage/BaselineOfCoverage.class.st
  src/BaselineOfCoverage/package.st
  src/BaselineOfDrTests/BaselineOfDrTests.class.st
  src/BaselineOfSUnit/BaselineOfSUnit.class.st
  src/Coverage/CoverageCollector.class.st
  src/Coverage/CoverageCollectorTest.class.st
  src/Coverage/CoverageResult.class.st
  src/Coverage/Crown.class.st
  src/Coverage/ManifestCoverage.class.st
  src/Coverage/package.st
  src/DrTests-TestCoverage/DTTestCoveragePlugin.class.st
  src/SUnit-UI/TestRunner.class.st
Labels: tests passed please review!

#11851 Transition deprecate method refactoring to use driver
  src/Refactoring-Core/RBApplicabilityChecksFailedError.class.st
  src/Refactoring-Core/RBBreakingChangeChecksFailedWarning.class.st
  src/Refactoring-Core/RBDeprecateMethodDriver.class.st
  src/Refactoring-Core/RBDeprecateMethodRefactoring.class.st
  src/Refactoring-Core/RBDriver.class.st
  src/Refactoring-Core/RBMoveMethodToClassSideRefactoring.class.st
  src/Refactoring-Core/RBMoveMethodsToClassSideDriver.class.st
  src/SystemCommands-MessageCommands/SycDeprecateMessageCommand.class.st
Labels: tests passed please review!

#11878 fix #11877
  src/Calypso-SystemTools-Core/SycReplaceMessageCommand.extension.st
  src/Refactoring-Core/RBConjunctiveCondition.class.st
  src/Refactoring-Core/RBReplaceMessageSendTransformation.class.st
  src/Refactoring-Tests-Core/RBConditionTest.class.st
  src/Refactoring2-Transformations-Tests/RBReplaceSendersMethodParametrizedTest.class.st
  src/SystemCommands-MessageCommands/SycReplaceMessageCommand.class.st
Labels: Refactorings

#11879 Clean blocks simpler checks
  src/Coverage/CoverageCollectorTest.class.st
  src/Kernel/CleanBlockClosure.class.st
  src/Refactoring2-Transformations-Tests/RBMoveMethodParametrizedTest.class.st
Labels: tests passed please review!

#11882 AST: add a recursive #hasNonLocalReturn and #isConstant
  src/AST-Core-Tests/RBBlockNodeTest.class.st
  src/AST-Core/RBBlockNode.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBSequenceNode.class.st
Labels: tests passed please review!

#11884 CleanBlock-no-receiver
  src/Kernel/CleanBlockClosure.class.st
Labels: tests passed please review!

#11861 Introducing new icons pack
  src/Polymorph-Widgets/ThemeIcons.class.st
Labels: Need more work

#11890 11881-RBBlockNodeisClean-takes-every-optimized-block-to-be-not-clean
  src/AST-Core-Tests/RBBlockNodeTest.class.st
  src/Kernel-Tests/BlockClosureTest.class.st
  src/Kernel/BlockClosure.class.st
  src/OpalCompiler-Core/RBBlockNode.extension.st
  src/OpalCompiler-Tests/OCCleanBlockTest.class.st
Labels: tests passed please review!

#11900 11883-CleanBlockChecker-does-not-recurse-into-the-blocks
  src/Kernel/CleanBlockChecker.class.st
Labels: tests passed please review!

#11898 Implement #asSlot to return a correct Slot instances for complex slots
  src/ClassParser/CDSlotNode.class.st
  src/ClassParser/ShiftClassBuilder.extension.st
Labels: tests passed please review!

#11891 Fixes #11802 - Adds full consistency checks to class Time
  src/Kernel-Chronology-Extras/Time.extension.st
  src/Kernel-Tests/TimeTest.class.st
  src/Kernel/Time.class.st
  src/Kernel/TimeError.class.st
Labels: tests passed please review!

#11902 add #numArgs to RBBlockNode
  src/AST-Core-Tests/RBBlockNodeTest.class.st
  src/AST-Core/RBBlockNode.class.st
Labels: tests passed please review!, easyReview

#11811 11810-FT2Handle-classstartUp-compiled-code-on-image-startup
  src/FreeType/FT2Handle.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/System-SessionManager/SessionManager.class.st
Labels: tests passed please review!

#11905 IRBuilder: add support for outerContext flag for Closure creation
  src/OpalCompiler-Core/IRBuilder.class.st
  src/OpalCompiler-Core/IRBytecodeGenerator.class.st
  src/OpalCompiler-Core/IRInstruction.class.st
  src/OpalCompiler-Core/IRPushFullClosure.class.st
Labels: tests passed please review!

#11894 ConstantBlockClosure: active when compiling with clean blocks enabled
  src/Debugging-Core/CompiledBlock.extension.st
  src/Fuel-Tests-Core/FLBlockClosureSerializationTest.class.st
  src/Fuel-Tests-Core/FLFullBlockClosureSerializationTest.class.st
  src/Fuel-Tests-Core/FLGlobalEnvironmentTest.class.st
  src/Kernel-Tests-Extended/ProcessTest.class.st
  src/Kernel/CleanBlockClosure.class.st
  src/Kernel/ConstantBlockClosure.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
Labels: tests passed please review!

#11897 Fixing to correctly get the VM for running the tests
  bootstrap/scripts/runTests.sh
Labels: tests passed please review!

#11907 CompiledBlocks: compile quick returns
  src/Kernel/CompiledBlock.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/CompiledMethod.class.st
  src/OpalCompiler-Core/IRBytecodeGenerator.class.st
Labels: tests passed please review!

#11917 11911-Compiler-add-compiler-option-for-outerContextNeeded
  src/Collections-Unordered/Dictionary.class.st
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
Labels: tests passed please review!

#11919 11901-ConstantBlockClosure-raise-error-if-called-with-wrong-number-of-args
  src/Kernel/ConstantBlockClosure.class.st
  src/Kernel/ConstantBlockClosure1Arg.class.st
  src/Kernel/ConstantBlockClosure2Arg.class.st
  src/Kernel/ConstantBlockClosure3Arg.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
Labels: tests passed please review!

#11899 Sync #basicInspect and inspect
  src/Tool-Base/Object.extension.st
  src/Tools/Object.extension.st
Labels: tests passed please review!

#11922 Context-print-no-isClean-check
  src/Kernel/Context.class.st
Labels: tests passed please review!

#11929 Fixes #11925, ExternalBrowser does not show class definition from ST files Bug
  src/Ring-OldChunkImporter/RingChunkImporter.class.st
Labels: tests passed please review!

#11509 Cleanup on The package TestRunner
  src/TestRunner-Core/AbstractExecutionMode.class.st
  src/TestRunner-Core/AbstractReporter.class.st
  src/TestRunner-Core/AbstractSuitePreparator.class.st
  src/TestRunner-Core/NewCommandLineRunner.class.st
  src/TestRunner-Core/NewTestRunner.class.st
  src/TestRunner-Core/SequenceableCollection.extension.st
  src/TestRunner-Tests/AllTestFailTest.class.st
  src/TestRunner-Tests/DependencyTest.class.st
  src/TestRunner-Tests/FailThenPass.class.st
  src/TestRunner-Tests/GreenTest.class.st
  src/TestRunner-Tests/MockTest.class.st
  src/TestRunner-Tests/MyClassCovered100Test.class.st
  src/TestRunner-Tests/MyClassCovered50Test.class.st
  src/TestRunner-Tests/NewCommandLineRunnerTest.class.st
  src/TestRunner-Tests/RedTest.class.st
  src/TestRunner-Tests/YellowTest.class.st
Labels: tests passed please review!

#11824 Improve bootstrap.sh
  bootstrap/scripts/bootstrap.sh
Labels: tests passed please review!

#11659 RubTextEditor: Bind the MENU key to open the context menu
  src/OSWindow-Core/OSKeySymbols.class.st
  src/Rubric/RubAbstractTextArea.class.st
  src/Rubric/RubTextEditor.class.st
  src/System-Platforms/KeyboardKey.class.st
Labels: tests passed please review!

#11936 Some smaller fixes/cleanups related to Blocks
  src/AST-Core-Tests/RBBlockNodeTest.class.st
  src/Kernel/CompiledCode.class.st
  src/OpalCompiler-Core/CompiledCode.extension.st
  src/OpalCompiler-Core/CompiledMethod.extension.st
Labels: tests passed please review!

#11932 ReNotOptimizedIfNilRule
  src/GeneralRules/ReNotOptimizedIfNilRule.class.st
Labels: tests passed please review!

#11942 EpHasImpactVisitor>>visitProtocolRemoval: handle protocols that only contain trait methods.
  src/EpiceaBrowsers-Tests/EpHasImpactFilterTest.class.st
  src/EpiceaBrowsers/EpHasImpactVisitor.class.st
Labels: tests passed please review!

#11945 Remove old comment editors
  src/Calypso-Browser/ClyTabManager.class.st
  src/Calypso-SystemTools-Core/ClyClassCommentEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyPackageCommentEditorToolMorph.class.st
Labels: Cleanup, easyReview, pharo11

#11952 do not rebuild all Calypso tools at each selection change
  src/Calypso-Browser-Tests/ClyBrowserContextAbstractTest.class.st
  src/Calypso-Browser-Tests/ClyBrowserToolValidityTest.class.st
  src/Calypso-Browser-Tests/ClyNotebookPageRecyclerTest.class.st
  src/Calypso-Browser-Tests/package.st
  src/Calypso-Browser/ClyBrowserMorph.class.st
  src/Calypso-Browser/ClyBrowserToolMorph.class.st
  src/Calypso-Browser/ClyNotebookManager.class.st
  src/Calypso-Browser/ClyNotebookPageRecycler.class.st
  src/Calypso-Browser/ClyTargetTool.class.st
  src/Calypso-SystemPlugins-SUnit-Browser/ClyTestSetUpEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyClassCreationToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyClassEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodCodeEditorToolMorph.class.st
  src/Tool-DependencyAnalyser-UI-Tab/DABrowserToolMorph.class.st
Labels: tests passed please review!

#11831 fix OSWIndowDriver shutdown while saving
  src/Morphic-Core/AbstractWorldRenderer.class.st
  src/OSWindow-Core/OSWindowDriver.class.st
  src/OSWindow-Core/OSWorldRenderer.class.st
  src/OSWindow-SDL2/OSSDL2Driver.class.st
Labels: tests passed please review!

#11951 Blocks: pcInOuter-not-Debugging
  src/Debugging-Core/CompiledBlock.extension.st
  src/Kernel/CompiledBlock.class.st
  src/Kernel/CompiledCode.class.st
  src/OpalCompiler-Core/CompiledCode.extension.st
  src/OpalCompiler-Core/CompiledMethod.extension.st
Labels: tests passed please review!

#11950 Fix #11949 less help class
  src/Announcements-Help/AnnouncementsAPIDocumentation.class.st
  src/Announcements-Help/AnnouncementsHelp.class.st
  src/Announcements-Help/AnnouncementsTutorial.class.st
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/BaselineOfGeneralHelp/BaselineOfGeneralHelp.class.st
  src/BaselineOfQualityAssistant/BaselineOfQualityAssistant.class.st
  src/ProfStef-Help/PharoTutorialAPIHelp.class.st
  src/ProfStef-Help/PharoTutorialHelp.class.st
  src/ProfStef-Help/PharoTutorialsHelp.class.st
  src/ProfStef-Tests/PharoTutorialHelpTest.class.st
  src/ProfStef-Tests/PharoTutorialHelpTutorialBuilderTest.class.st
  src/Renraku-Help/RenrakuCritiqueDesignHelp.class.st
  src/Renraku-Help/RenrakuCritiqueExamplesHelp.class.st
  src/Renraku-Help/RenrakuCritiqueHelp.class.st
  src/Renraku-Help/RenrakuHelp.class.st
  src/Renraku-Help/RenrakuMigrationHelp.class.st
  src/Renraku-Help/RenrakuRuleCreationHelp.class.st
  src/Renraku-Help/RenrakuRuleHelp.class.st
  src/Renraku-Help/RenrakuSpecialRulesHelp.class.st
Labels: tests passed please review!, easyReview

#11887 New refactoring changes preview presenter
  src/Refactoring-Core/RBDeprecateMethodDriver.class.st
  src/Refactoring-Core/RBRefactoringPreviewPresenter.class.st
  src/SystemCommands-MessageCommands/SycChangeMessageSignatureCommand.class.st
  src/SystemCommands-MessageCommands/SycDeprecateMessageCommand.class.st
Labels: tests passed please review!

#11982 11844-Renaming-a-package-loses-all-the-package-extensions
  src/RPackage-Tests/RPackageRenameTest.class.st
Labels: tests passed please review!

#11987 Support #isReturnSpecial on CompiledBlock
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#11947 [Compiler] fix code generation when compiling syntax errors: EnglobingError
  src/AST-Core/RBParseErrorNode.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Tests/OCCompileWithFailureTest.class.st
Labels: tests passed please review!

#11921 11544 enhance socket to show meaningful errors
  src/Network-Kernel/Socket.class.st
  src/Network-Kernel/SocketError.class.st
  src/System-Platforms/MacOSXPlatform.class.st
  src/System-Platforms/UnixPlatform.class.st
  src/System-Platforms/WinPlatform.class.st
Labels: tests passed please review!

#12001 Removing help support
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/BaselineOfFreeType/BaselineOfFreeType.class.st
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfSUnit/BaselineOfSUnit.class.st
  src/BaselineOfUI/BaselineOfUI.class.st
  src/Metacello-ToolBox/MetacelloToolBox.class.st
  src/RPackage-Core/RPackage.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: Need more work

#12000 11966-Implement-BlockClosurehomeMethod-without-using-home
  src/Kernel-Tests/BlockClosureTest.class.st
  src/Kernel-Tests/ContextTest.class.st
  src/Kernel/BlockClosure.class.st
  src/Kernel/Context.class.st
Labels: tests passed please review!

#12012 Integrate Roassal3 v0.9.9k
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: tests passed please review!

#11991 Fix slow execution time when using CharacterSet or CharacterSetComple…
  src/Collections-Strings-Tests/StringTest.class.st
  src/Collections-Strings/String.class.st
Labels: Enhancement, tests passed please review!

#11916 Fix print on recursive array
  src/Collections-Sequenceable-Tests/ArrayTest.class.st
  src/Collections-Sequenceable/Array.class.st
  src/Kernel/Object.class.st
Labels: tests passed please review!

#12015 Tests for clean and constant blocks
  src/OpalCompiler-Tests/OCClosureTest.class.st
Labels: tests passed please review!

#12016 11937-Cycling-of-Halos-does-not-work-anymore
  src/BaselineOfMorphicCore/BaselineOfMorphicCore.class.st
  src/Morphic-Base/HaloMorph.class.st
  src/Morphic-Base/Object.extension.st
  src/Morphic-Core/Morph.class.st
  src/Morphic-Core/MouseButtonEvent.class.st
  src/Morphic-Core/UserInputEvent.class.st
  src/Morphic-Tests/HaloMorphTest.class.st
  src/Morphic-Tests/MorphicEventHandlerTest.class.st
  src/OSWindow-Core/OSWindowMorphicEventHandler.class.st
Labels: tests passed please review!
