Repository pharo-project/pharo, pull requests merged in 2022-04, with the labels that each got.

#11095 fixes checkForNewScreenSize
  src/OSWindow-Core/OSWorldRenderer.class.st
Labels: tests passed please review!

#11094 Specify the mouse over color in the theme rather than hardcode it.
  src/Morphic-Widgets-FastTable/FTSelectableMorph.class.st
  src/Polymorph-Widgets/PharoDarkTheme.class.st
  src/Polymorph-Widgets/UITheme.class.st
Labels: tests passed please review!

#11097 Merging latest changes in P10 to P11
  src/BaselineOfPharo/BaselineOfPharo.class.st
  src/Morphic-Widgets-FastTable/FTSelectableMorph.class.st
  src/OSWindow-Core/OSWorldRenderer.class.st
  src/Polymorph-Widgets/PharoDarkTheme.class.st
  src/Polymorph-Widgets/UITheme.class.st
Labels: tests passed please review!

#11086 Fix for issue 11070: Interval>>= and Interval>>hash do not match
  src/Collections-Sequenceable-Tests/IntervalTest.class.st
  src/Collections-Sequenceable/Interval.class.st
Labels: tests passed please review!

#11116 Allow to serialize Memory File Systems
  src/STON-Core/FileReference.extension.st
  src/STON-Core/Object.extension.st
  src/STON-Tests/STONWriteReadTest.class.st
Labels: tests passed please review!, Pharo10

#11110 Fix #11109: Feature Envy on startSteppingSubmorphsOf:
  src/Morphic-Base/MenuMorph.class.st
  src/Morphic-Base/TextMorph.class.st
  src/Morphic-Core/Morph.class.st
  src/Morphic-Core/PasteUpMorph.class.st
  src/Morphic-Core/TransformationMorph.class.st
  src/Morphic-Core/WorldMorph.class.st
  src/Morphic-Widgets-Windows/CollapsedMorph.class.st
  src/Morphic-Widgets-Windows/SystemWindow.class.st
Labels: tests passed please review!

#11120 add accessor to AbstractInitializedSlot
  src/VariablesLibrary/AbstractInitializedSlot.class.st
Labels: tests passed please review!

#11132 fix comments mentioning compact classes.
  src/Kernel/Object.class.st
  src/Kernel/ProtoObject.class.st
Labels: tests passed please review!, easyReview

#11160 11159-Complete-the-set-of-methods-to-access-keys
  src/System-Platforms/KeyboardKey.class.st
Labels: tests passed please review!

#11156 11063-ExternalChangesBrowserbuildMenu-should-use-selectedItemsSorted
  src/Tool-ExternalBrowser/ExternalChangesBrowser.class.st
Labels: tests passed please review!

#11168 Fixing RBChildrenToSiblingsRefactoring to handle Classes that use Traits
  src/Refactoring-Core/RBChildrenToSiblingsRefactoring.class.st
Labels: tests passed please review!

#11148 10963-Memory-AllProtocol-uses-a-lot-of-memory
  src/Kernel/AbstractProtocol.class.st
  src/Kernel/AllProtocol.class.st
  src/Kernel/Protocol.class.st
  src/Ring-Core/AbstractProtocol.extension.st
  src/SystemCommands-RefactoringSupport/RBAbstractSelectionPresenter.class.st
Labels: tests passed please review!
