Repository pharo-project/pharo, pull requests merged in 2022-05, with the labels that each got.

#11175 11172-ClassclassPool-empty-dictionary-for-all-classes-but-not-many-define-class-vars
  src/Kernel/Class.class.st
Labels: tests passed please review!

#11188 Rename BlockClosure startpc to compiledBlock
  src/Kernel/BlockClosure.class.st
Labels: tests passed please review!

#10436 Reflectivity-AddPragmaSupport
  src/Reflectivity-Tests/ReflectiveMethodTest.class.st
  src/Reflectivity-Tests/ReflectivityExamples.class.st
  src/Reflectivity/RFASTTranslator.class.st
  src/Reflectivity/RFReification.class.st
Labels: tests passed please review!

#11192 Start to remove code from Deprecated10 package.
  src/Deprecated10/Behavior.extension.st
  src/Deprecated10/CompiledCode.extension.st
  src/Deprecated10/DAPackageUnderAnalysisNode.extension.st
  src/Deprecated10/DebuggerMethodMapOpal.class.st
  src/Deprecated10/InstructionStream.extension.st
  src/Deprecated10/JobProgressBarMorph.extension.st
  src/Deprecated10/OpalCompiler.extension.st
  src/Deprecated10/ProtocolRemovalException.class.st
  src/Deprecated10/UndefinedObject.extension.st
Labels: tests passed please review!

#11189 11144-LocaleAnnouncementTest-seems-to-be-unused
  src/System-Localization-Tests/LocaleAnnouncementTest.class.st
Labels: tests passed please review!, easyReview

#11200 11198-Pharo10-Reflectivity-do-not-add-temp-for-value-if-not-generating-the-primtive-Wrapper
  src/Reflectivity/RFSemanticAnalyzer.class.st
Labels: tests passed please review!

#11197 Making completion support $_ in class and method names
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion/Character.extension.st
  src/Rubric/RubSmalltalkEditor.class.st
Labels: tests passed please review!

#11117 Fix for the issue #11115: Feature Envy clipRect on AthensCairoCanvas
  src/Athens-Cairo/AthensCairoCanvas.class.st
Labels: tests passed please review!

#11202 Remembering scroll position when collapsing and expanding tree table items
  src/Morphic-Widgets-FastTable/FTBasicItem.class.st
  src/Morphic-Widgets-FastTable/FTTreeDataSource.class.st
Labels: tests passed please review!

#11173 Fixes #11165 begins with and ends with should return true on empty string
  src/Collections-Abstract-Tests/TBeginsEndsWith.trait.st
  src/Collections-Abstract/SequenceableCollection.class.st
  src/Collections-Sequenceable-Tests/OrderedCollectionTest.class.st
  src/Collections-Strings-Tests/StringTest.class.st
  src/Collections-Strings/String.class.st
  src/HeuristicCompletion-Model/CoCaseInsensitiveBeginsWithFilter.class.st
  src/HeuristicCompletion-Model/CoCaseSensitiveBeginsWithFilter.class.st
  src/HeuristicCompletion-Tests/CoMockSystemNavigation.class.st
Labels: tests passed please review!

#10951 FIX issue #10933: Scaled decimals comparison result depends on the number creation method
  src/Kernel-Tests/ScaledDecimalTest.class.st
  src/Kernel/ScaledDecimal.class.st
Labels: tests passed please review!, pharo11

#11205 6323-RubSmalltalkEditor-meta-j-shortcut-not-working
  src/Rubric/RubSmalltalkEditor.class.st
Labels: easyReview

#11164 11162-Check-ReToDoRule
  src/GeneralRules-Tests/ReSmalllintTest.class.st
  src/GeneralRules/ReToDoRule.class.st
  src/Refactoring-Tests-Critics/RBSmalllintTestObject.class.st
Labels: tests passed please review!

#11176 6720-Dictionary--newFrom-logic-can-be-improved-
  src/Collections-Unordered/Dictionary.class.st
  src/Tests/TraitCompositionTest.class.st
Labels: tests passed please review!

#11224 11216-categorize-ZnStaticFileDecoratorDelegate-classdecorateservingFilesFrom
  src/Zinc-HTTP-Examples/ZnStaticFileDecoratorDelegate.class.st
Labels: easyReview

#11215 Fix an issue where streaming client usage failed when the server set a connection close.
  src/Zinc-Character-Encoding-Core/ZnBufferedReadStream.class.st
  src/Zinc-Character-Encoding-Tests/ZnBufferedReadStreamTest.class.st
  src/Zinc-HTTP-Examples/ZnStaticFileServerDelegate.class.st
  src/Zinc-HTTP-Examples/ZnStaticFileServerDelegateTest.class.st
  src/Zinc-HTTP/ZnClient.class.st
  src/Zinc-Resource-Meta-Core/ZnUrl.class.st
  src/Zinc-Tests/ZnClientTest.class.st
Labels: tests passed please review!, pharo11

#11214 Fix an issue where streaming client usage failed when the server set a connection close.
  src/Zinc-Character-Encoding-Core/ZnBufferedReadStream.class.st
  src/Zinc-Character-Encoding-Tests/ZnBufferedReadStreamTest.class.st
  src/Zinc-HTTP-Examples/ZnStaticFileServerDelegate.class.st
  src/Zinc-HTTP-Examples/ZnStaticFileServerDelegateTest.class.st
  src/Zinc-HTTP/ZnClient.class.st
  src/Zinc-Resource-Meta-Core/ZnUrl.class.st
  src/Zinc-Tests/ZnClientTest.class.st
Labels: Pharo10

#11228 Revert "FIX issue #10933: Scaled decimals comparison result depends on the number creation method"
  src/Kernel-Tests/ScaledDecimalTest.class.st
  src/Kernel/ScaledDecimal.class.st
Labels: tests passed please review!

#11229 11218-CleanBlocks-Compiler-should-not-change-the-outerCode-for-all-blocks-in-the-literals
  src/Kernel/CleanBlockClosure.class.st
  src/OpalCompiler-Core/IRBytecodeGenerator.class.st
Labels: tests passed please review!

#11225 CleanBlock-Hierachy-Cleanup
  src/Kernel/BlockClosure.class.st
  src/Kernel/CleanBlockClosure.class.st
  src/Kernel/FullBlockClosure.class.st
Labels: tests passed please review!

#11231 11230-ClassParser-Improve-Hierarchy-CDSharedVariableNodeCDSlotNode
  src/ClassParser/CDSharedVariableNode.class.st
  src/ClassParser/CDSlotNode.class.st
  src/ClassParser/CDVariableNode.class.st
  src/ClassParser/ShiftClassBuilder.extension.st
Labels: tests passed please review!

#11241 Cleanup: OneCharacterSymbols: Symbol allSymbols contains one-character symbols twice
  src/Collections-Strings/String.class.st
  src/Collections-Strings/Symbol.class.st
  src/Kernel/Character.class.st
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
Labels: tests passed please review!

#11247 remove OneCharacterSymbols from Symbol
  src/Collections-Strings/Symbol.class.st
Labels: tests passed please review!

#11250 Cleanup-DeadCode-05-20
  src/MonticelloFileTree-Core/MCFileTreeRepository.class.st
  src/Polymorph-Widgets/SoundTheme.class.st
  src/Tool-DependencyAnalyser-UI/DADependentPackageNode.class.st
  src/Tool-DependencyAnalyser-UI/DAExtensionDependencyNode.class.st
Labels: tests passed please review!

#11239 Pharo11-UFT8-Monticello
  src/Monticello/MCVersionInfoWriter.class.st
Labels: tests passed please review!

#11256 11255-OrderedCollection-adding-methods-remove-a-poppushTemp
  src/Collections-Sequenceable/OrderedCollection.class.st
Labels: tests passed please review!

#11244 11243-Symbol-classrebuildSelectorTable-hould-not-use-allInstancesDo
  src/Collections-Strings/Symbol.class.st
Labels: tests passed please review!

#11249 11245-Trivial-FinderUI-classsearchedTextListMaxSize-can-be-removed
  src/Tool-Finder/FinderUI.class.st
Labels: tests passed please review!

#11281 Symbol-simpler-findInternedSelector
  src/Collections-Strings-Tests/SymbolTest.class.st
  src/Collections-Strings/Symbol.class.st
Labels: tests passed please review!

#11261 Add rules for simplification of isNotNil ifTrue:, notNil ifTrue:ifFalse
  src/GeneralRules/ReIsNotNilAndConditionalRule.class.st
Labels: tests passed please review!

#11302 ReleaseTest-Symbol-unused-classvar
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
Labels: tests passed please review!

#11291 Simpler (and slightly faster) Symbol>>#intern:
  src/Collections-Strings/ByteString.class.st
  src/Collections-Strings/Symbol.class.st
  src/Collections-Strings/WideString.class.st
Labels: tests passed please review!

#11311 11248-Check-CanSelectorTable-use-WeakIndentitySet
  src/Collections-Strings-Tests/SymbolTest.class.st
  src/Collections-Strings/Symbol.class.st
Labels: tests passed please review!

#11303 fix-ReMissingSubclassResponsibilityRule
  src/Renraku/ReMissingMethodCritique.class.st
Labels: tests passed please review!

#11187 11186-Clean-Blocks-fix-to-make-debugger-work
  src/Debugger-Model-Tests/DebugSessionContexts2Test.class.st
  src/Debugger-Model-Tests/StepOverTest.class.st
  src/Kernel/Context.class.st
Labels: tests passed please review!

#7018 ReNotOptimizedIfRule
  src/GeneralRules-Tests/ReSmalllintTest.class.st
  src/GeneralRules/ReNotOptimizedIfRule.class.st
  src/Refactoring-Tests-Critics/RBSmalllintTestObject.class.st
Labels: tests passed please review!
