Repository pharo-project/pharo, pull requests merged in 2022-07, with the labels that each got.

#11436 reduce-asSymbol-in-tools
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserMorph.class.st
  src/Morphic-Base/ShortcutReminder.class.st
  src/Renraku/ReProperMethodProtocolNameForAccessingRule.class.st
  src/Renraku/ReProperMethodProtocolNameForAddingRemovingRule.class.st
  src/Renraku/ReProperMethodProtocolNameForConvertingRule.class.st
  src/Renraku/ReProperMethodProtocolNameForFileInOutRule.class.st
  src/Renraku/ReProperMethodProtocolNameForInstanceCreationRule.class.st
  src/Renraku/ReProperMethodProtocolNameForRemovalRule.class.st
  src/Renraku/ReProperMethodProtocolNameForUtilitiesRule.class.st
  src/Renraku/ReProperMethodProtocolNameRule.class.st
Labels: tests passed please review!

#11431 Cleanup: Deprecate FFIExternalReference>>#handle: and FFIExternalReference>>#handle
  src/UnifiedFFI-Legacy/FFIExternalReference.extension.st
Labels: tests passed please review!

#11437 Allow creating Pharo methods using the Bytecode IR
  src/AST-Core-Tests/RBMethodNodeTest.class.st
  src/AST-Core-Tests/RBParseTreeSearcherTest.class.st
  src/AST-Core/RBMethodNode.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
Labels: tests passed please review!

#11440 Cleanup-asRingMinimalDefinitionIn-Parent
  src/Ring-Core/AbstractProtocol.extension.st
  src/Ring-Core/Slot.extension.st
  src/Ring-TraitsV2Support/TaAliasMethod.extension.st
Labels: tests passed please review!

#11326 Add commentSourcePointer to ClassDescription
  src/Kernel/ClassDescription.class.st
Labels: Need more work

#11421 Cleanup-M1-Variadic-FFI-Tests
  src/ThreadedFFI-Tests/TFFunctionCallTest.class.st
  src/ThreadedFFI-Tests/TestCase.extension.st
  src/UnifiedFFI-Tests/FFICalloutAPITest.class.st
  src/UnifiedFFI-Tests/FFIExternalEnumerationTest.class.st
Labels: tests passed please review!

#11452 code critique cleanup of some methods related to #category
  src/Kernel/ClassOrganization.class.st
Labels: tests passed please review!

#11462 Revert "9828-Inspector-columns-cannot-be-resized "
  src/Morphic-Widgets-FastTable/FTColumnResizerMorph.class.st
Labels: tests passed please review!

#11471 Integer: add missing #subclassResponsibility
  src/Kernel/Integer.class.st
  src/Kernel/LargeInteger.class.st
Labels: tests passed please review!, easyReview

#11463 DoIts without method header and reformatting
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core-Tests/RBProgramNodeTest.class.st
  src/AST-Core/ASTCacheMissStrategy.class.st
  src/AST-Core/CompiledMethod.extension.st
  src/AST-Core/RBDoItMethodNode.class.st
  src/AST-Core/RBMethodNode.class.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBReturnNode.class.st
  src/AST-Core/RBSequenceNode.class.st
  src/Calypso-Browser/ClyTextEditingMode.class.st
  src/DrTests-CommentsToTests-Tests/CommentsToTestsTest.class.st
  src/Kernel-ExtraUtils/ClassHierarchyPrinterTest.class.st
  src/Kernel-Tests-Extended/CompiledMethodTrailerTest.extension.st
  src/Kernel/CompiledMethodTrailer.class.st
  src/OpalCompiler-Core/OCContextualDoItSemanticScope.class.st
  src/OpalCompiler-Core/OCDoItSemanticScope.class.st
  src/OpalCompiler-Core/OCReceiverDoItSemanticScope.class.st
  src/OpalCompiler-Core/OCSemanticScope.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OCASTTranslatorTest.class.st
  src/OpalCompiler-Tests/OCCompileWithFailureTest.class.st
  src/Reflectivity/RFReflectivityASTCacheStrategy.class.st
  src/Rubric/RubScrolledTextModel.class.st
  src/Shout/SHRBTextStyler.class.st
  src/Tools-CodeNavigation-Tests/CNSelectorExtractionOnPositionTest.class.st
  src/Tools-CodeNavigation/CNSelectorExtractor.class.st
Labels: tests passed please review!

#11472 tag AbstractBinaryFileStream as abstract
  src/Files/AbstractBinaryFileStream.class.st
Labels: tests passed please review!

#11349 Fixes: #11342 added some tests to cover to methods that were not called.
  src/Refactoring-Changes/RBAddClassChange.class.st
  src/Refactoring-Core/RBClass.class.st
  src/Refactoring-Tests-Core/RBSharedPoolTest.class.st
Labels: Bug, Fix proposed

#11408 CloseAllWindows
  src/Morphic-Core/PasteUpMorph.class.st
  src/Morphic-Widgets-Taskbar/SystemWindow.extension.st
Labels: tests passed please review!

#11466 10774-FTP-clientgetDataInto-lost-returned-information
  src/Network-Protocols/FTPClient.class.st
Labels: tests passed please review!

#11478 Adding comments to SUnit classes
  src/SUnit-Core/BadEqualer.class.st
  src/SUnit-Core/TestAsserter.class.st
  src/SUnit-Core/TestCase.class.st
  src/SUnit-Core/TestResult.class.st
Labels: more-information-needed
