Repository pharo-project/pharo, pull requests merged in 2022-02, with the labels that each got.

#10833 Cleanup-unsent-Deprecated90
  src/Deprecated90/MacRomanTextConverter.class.st
  src/Deprecated90/TextConverter.class.st
  src/Deprecated90/UTF8TextConverter.class.st
Labels: tests passed please review!

#10820 fix-users-canBeGlobalVarInitial
  src/Kernel/Class.class.st
  src/Morphic-Examples/WidgetExample.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
  src/Polymorph-Widgets/EntryCompletion.class.st
  src/Rubric/RubMethodEditingExample.class.st
Labels: tests passed please review!

#10826 Cleanup : remove Class>>isValidTraitName. No more sender of it in the…
  src/Kernel/Class.class.st
Labels: tests passed please review!

#10839 Replace Moose algos graphs by AI graphs algorithms
  src/BaselineOfDependencyAnalyzer/BaselineOfDependencyAnalyzer.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
  src/Tool-DependencyAnalyser-Tests/DATarjanAlgorithmTest.class.st
  src/Tool-DependencyAnalyser/AITarjan.extension.st
  src/Tool-DependencyAnalyser/DADependencyChecker.class.st
  src/Tool-DependencyAnalyser/DAPackageCycleDetector.class.st
Labels: tests passed please review!

#10832 Add back beautifulcomments
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: tests passed please review!

#10848 10847-Deprecate-canBeGlobalVarInitial-and-canBeNonGlobalVarInitial
  src/Deprecated10/AsciiCharset.extension.st
  src/Deprecated10/Character.extension.st
  src/Deprecated10/EncodedCharSet.extension.st
  src/Kernel/AsciiCharset.class.st
  src/Kernel/Character.class.st
  src/Multilingual-Encodings/EncodedCharSet.class.st
Labels: tests passed please review!

#10835 9777-SystemNavigation-default-allUnimplementedCalls-size---DNU
  src/Debugging-Core/InstructionStream.extension.st
  src/Graphics-Canvas/InterpolatedGradientFillStyle.class.st
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#10863 5879-Printing-an-exception-should-not-rely-on-the-AST
  src/Kernel/BlockClosure.class.st
Labels: tests passed please review!

#10873 cleanup: rewrite users of unicodeToMacRoman to use Zn encoders
  src/FreeType-Graphics/FreeTypeGlyphRenderer.class.st
  src/FreeType-Graphics/FreeTypeSubPixelAntiAliasedGlyphRenderer.class.st
  src/FreeType/FreeTypeFont.class.st
Labels: tests passed please review!

#10874 cleanup: rewrite users of leadingChar
  src/Collections-Strings/String.class.st
  src/Deprecated10/EncodedCharSet.extension.st
  src/Deprecated10/GB2312.class.st
  src/System-Changes/PositionableStream.extension.st
  src/System-Sources/ChunkReadStream.class.st
Labels: tests passed please review!

#10865 10864-deprecate-unused-class-ProtocolRemovalException
  src/Deprecated10/ProtocolRemovalException.class.st
Labels: tests passed please review!

#10868 Bugfix in RBSelectorEnvironment
  src/Refactoring-Environment/RBSelectorEnvironment.class.st
  src/Refactoring-Tests-Environment/RBBrowserEnvironmentTest.class.st
Labels: tests passed please review!

#10866 testNoUncategorizedMethods-lowerbound
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
Labels: tests passed please review!

#10852 Cleanup-CDAbstractClassDefinitionParser
  src/ClassParser/CDAbstractClassDefinitionParser.class.st
  src/ClassParser/CDClassDefinitionParser.class.st
  src/ClassParser/CDFluidClassDefinitionParser.class.st
Labels: tests passed please review!

#10876 Deprecate KMCategoryTarget
  src/Deprecated10/KMCategoryTarget.class.st
Labels: tests passed please review!

#10882 Epicea-Fluid-fixes
  src/Epicea-Tests/EpCodeChangeIntegrationTest.class.st
  src/EpiceaBrowsers/EpApplyVisitor.class.st
  src/FluidClassBuilder/Behavior.extension.st
  src/FluidClassBuilder/FluidBuilder.class.st
Labels: tests passed please review!

#10875 9963-MCStReadertypeOfSubclass-hard-codes-mcType-and-subclassDefiningSymbol
  src/Monticello/MCStReader.class.st
Labels: tests passed please review!

#10886 Just less newHorizontal
  src/DrTests/DTDefaultPluginPresenter.class.st
Labels: tests passed please review!

#10870 10854-Cmd-t-stopped-working
  src/Calypso-SystemTools-Core/SycOpenReflectivityMenuCommand.extension.st
  src/SystemCommands-SourceCodeCommands/SycOpenReflectivityMenuCommand.class.st
Labels: tests passed please review!

#10885 just adding two little tests for fraction accessing.
  src/Kernel-Tests/FractionTest.class.st
Labels: tests passed please review!

#10891 10889-equal-CompiledBlocks-in-the-literal-frame-stored-only-once
  src/Kernel-Tests/BlockClosureTest.class.st
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/Kernel/CompiledBlock.class.st
Labels: tests passed please review!

#10932 Simplify-allUnimplementedCalls
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#10819 New try at removing Pharo 9 metacello attributes
  src/System-Support/SmalltalkImage.class.st
Labels: tests passed please review!, Pharo10

#10893 10860-Debugger-hightlights-the-wrong-line-in-test-for-asserts-inside-two-identical-blocks
  src/Kernel-BytecodeEncoders/EncoderForSistaV1.class.st
  src/Kernel-Tests/CompiledBlockTest.class.st
  src/Kernel-Tests/CompiledCodeTest.class.st
Labels: tests passed please review!, Pharo10

#10941 Cleanup newlines and blanks in "Baseline" packages
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/BaselineOfBeacon/BaselineOfBeacon.class.st
  src/BaselineOfCalypso/BaselineOfCalypso.class.st
  src/BaselineOfDependencyAnalyzer/BaselineOfDependencyAnalyzer.class.st
  src/BaselineOfDisplay/BaselineOfDisplay.class.st
  src/BaselineOfFuel/BaselineOfFuel.class.st
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfMenuRegistration/BaselineOfMenuRegistration.class.st
  src/BaselineOfMetacello/BaselineOfMetacello.class.st
  src/BaselineOfMonticello/BaselineOfMonticello.class.st
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/BaselineOfParametrizedTests/BaselineOfParametrizedTests.class.st
  src/BaselineOfPharoBootstrap/BaselineOfPharoBootstrap.class.st
  src/BaselineOfReflectivity/BaselineOfReflectivity.class.st
  src/BaselineOfTaskIt/BaselineOfTaskIt.class.st
  src/BaselineOfTraits/BaselineOfTraits.class.st
  src/BaselineOfUnifiedFFI/BaselineOfUnifiedFFI.class.st
Labels: tests passed please review!

#10888 Full block cleanup: #sourceNodeForPC: RBBlockNode
  src/OpalCompiler-Core/RBBlockNode.extension.st
  src/OpalCompiler-Tests/OCBytecodeToASTCacheTest.class.st
Labels: tests passed please review!

#10953 Fix issue 10949 by checking correctly windows platform
  src/FreeType/FreeTypeFontProvider.class.st
Labels: more-information-needed
