Repository pharo-project/pharo, pull requests merged in 2022-01, with the labels that each got.

#10630 9697-FTExamplesexampleTree1-menu-item-Expand-All-freezes-image
  src/Morphic-Widgets-FastTable/FTExamples.class.st
Labels: tests passed please review!

#10668 Add TFProcessLocalWorker
  src/ThreadedFFI/TFProcessLocalWorker.class.st
Labels: tests passed please review!

#10683 add-SystemDictionary-loopUpVarDeclare
  src/System-Support/SystemDictionary.class.st
Labels: tests passed please review!

#10686 Fixes #10263 Setting minimum size for browser window
  src/Calypso-Browser/ClyBrowserMorph.class.st
Labels: more-information-needed

#10697 align commit of external projects with its merged version
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfPharo/BaselineOfPharo.class.st
  src/BaselineOfPharo/PharoExternalProject.class.st
Labels: tests passed please review!

#9792 use DoubleByteLayout and DoubleWordLayout
  bootstrap/src/Pharo30Bootstrap/MCClassDefinition.extension.st
  src/Collections-Native/DoubleByteArray.class.st
  src/Collections-Native/DoubleWordArray.class.st
Labels: tests passed please review!

#10682 Fixes #10673 by adding missing method method to display a MessageTally identified
  src/Tool-Profilers/MessageTally.class.st
Labels: tests passed please review!

#10707 10678-Step-Over-fails-for-leaving-simple-accessors
  src/Debugger-Model/DebugSession.class.st
Labels: tests passed please review!

#10705 10703-Collectionflattened-changed-semantics
  src/Collections-Abstract-Tests/TEnumeratingTest.trait.st
  src/Collections-Strings/String.class.st
  src/Kernel/CompiledCode.class.st
Labels: tests passed please review!

#10706 10331-No-need-to-refer-to-transcript-in-executable-comments
  src/Collections-Abstract/SequenceableCollection.class.st
  src/DrTests/DrTests.class.st
Labels: tests passed please review!

#10711 Fix-deprecated-hostWindowTitle
  src/Spec-MorphicAdapters/WorldPresenter.class.st
Labels: tests passed please review!

#10713 Fixes #10702 Printing method selector in windows title only if the selector is not nil
  src/SystemCommands-RefactoringSupport/SycMethodNameEditorPresenter.class.st
Labels: tests passed please review!

#10734 Remove temporarily documentation reader
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: more-information-needed

#10717 Fixes #10253 adding new fetcher for selectors.
  src/HeuristicCompletion-Model/CoGlobalSelectorFetcher.class.st
  src/HeuristicCompletion-Model/CoUnknownMessageHeuristic.class.st
  src/HeuristicCompletion-Tests/CoGlobalSelectorFetcherTest.class.st
  src/HeuristicCompletion-Tests/CoMockSystemNavigation.class.st
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#10759 Enh/better expansion for non fluid
  src/Kernel-Tests/FluidClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/OldClassDefinitionPrinterTest.class.st
  src/Kernel/Class.class.st
  src/Kernel/FluidClassDefinitionPrinter.class.st
  src/Kernel/OldPharoClassDefinitionPrinter.class.st
  src/TraitsV2-Tests/T2FluidClassDefinitionPrinterTest.class.st
Labels: tests passed please review!

#10762 10719-Porting-TestReviver-to-Spec2-and-remove-Spec1-version
  src/SUnit-UI/TestReviver.class.st
Labels: tests passed please review!

#10738 TFFI not compatible to UFFI - missing #tfPointerAddress on Integer
  src/ThreadedFFI/Integer.extension.st
Labels: tests passed please review!

#10761 10720-Porting-WatchesWindow-to-Spec2-and-remove-Spec1-version
  src/Reflectivity-Tools/WatchIconStyler.class.st
  src/Reflectivity-Tools/WatchesWindow.class.st
  src/Reflectivity-Tools/WatchesWindowPresenter.class.st
Labels: tests passed please review!

#10709 Move FontChooser to NewTools
  src/BaselineOfUI/BaselineOfUI.class.st
  src/Fonts-Chooser/AbstractFontSelectorDialogWindow.class.st
  src/Fonts-Chooser/FontChooser.class.st
  src/Fonts-Chooser/FontChooserMorph.class.st
  src/Fonts-Chooser/FreeTypeFontSelectorDialogWindow.class.st
  src/Fonts-Chooser/StandardFonts.extension.st
  src/Fonts-Chooser/package.st
  src/FreeType-Morphic/PluggableListMorph.extension.st
  src/FreeType-Morphic/StringMorph.extension.st
  src/Morphic-Widgets-Pluggable/PluggableListMorph.class.st
  src/Polymorph-Widgets/UITheme.class.st
  src/Rubric/RubTextEditor.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
  src/System-Settings-Core/PragmaSetting.class.st
Labels: tests passed please review!

#10770 CmdCommand-isAbstract-check
  src/Commander-Core/CmdCommand.class.st
  src/Tool-Registry/PharoCommonTools.class.st
Labels: tests passed please review!

#10776 10721-Porting-ExternalBrowser-to-Spec2-and-remove-Spec1-version
  src/Tool-ExternalBrowser/ExternalBrowser.class.st
  src/Tool-ExternalBrowser/ExternalChangesBrowser.class.st
Labels: tests passed please review!

#10775 10695-CmdBrowse-raise-a-DNU
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
Labels: tests passed please review!

#10791 spec2 auto-rewrites
  src/Calypso-Browser/ClyNotebookPageHeaderPresenter.class.st
  src/Calypso-SystemPlugins-Monticello-Browser/ClyCommitMCPackageCommand.class.st
  src/DrTests/DTDefaultPluginPresenter.class.st
  src/DrTests/DTFilterableListPresenter.class.st
  src/DrTests/DrTests.class.st
  src/DrTests/MiniDrTests.class.st
  src/EpiceaBrowsers/EpLogBrowserPresenter.class.st
  src/EpiceaBrowsers/EpLogBrowserToolbarPresenter.class.st
  src/NautilusRefactoring/RewriteRuleEditor.class.st
  src/Rubric-SpecFindReplaceDialog/SpRubFindReplaceDialog.class.st
  src/SystemCommands-RefactoringSupport/SycMethodNameEditorPresenter.class.st
  src/SystemCommands-RefactoringSupport/SycRefactoringPreviewPresenter.class.st
Labels: more-information-needed

#10792 commit spec rewrites 2
  src/Tool-ExternalBrowser/ExternalBrowser.class.st
  src/Tool-ExternalBrowser/ExternalChangesBrowser.class.st
Labels: more-information-needed

#10796 Remove abbreviation that is not needed to make it more explicit
  src/Calypso-SystemQueries/ClyAbstractClassScope.class.st
Labels: tests passed please review!

#10793 Rename defaultSpec to defaultLayout
  src/Athens-Examples/AthensDemoPresenter.class.st
  src/Athens-Examples/AthensTextRenderSpecExamples.class.st
  src/Calypso-SystemPlugins-Monticello-Browser/ClyCommitMCPackageCommand.class.st
  src/Calypso-SystemPlugins-Monticello-Browser/ClyIcebergShowMethodVersionCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyMetaLinkInstallationPresenter.class.st
  src/EpiceaBrowsers/EpDashboardPresenter.class.st
  src/EpiceaBrowsers/EpLog.extension.st
  src/EpiceaBrowsers/EpLogNodeGraphPresenter.class.st
  src/EpiceaBrowsers/EpLostChangesDetector.class.st
  src/EpiceaBrowsers/EpUnifiedBrowserPresenter.class.st
  src/Hiedra-Tests/HiRulerBuilderTest.class.st
  src/Keymapping-Tools-Spec/KMDescriptionPresenter.class.st
  src/NautilusRefactoring/ChangesBrowser.class.st
  src/NautilusRefactoring/RewriteRuleChangesBrowser.class.st
  src/ProfStef-Core/ProfStef.class.st
  src/Refactoring-Core/RBReplacePreview.class.st
  src/Reflectivity-Examples/CoverageDemo.class.st
  src/Reflectivity-Tools/WatchesWindowPresenter.class.st
  src/Renraku/ReAbstractCritique.class.st
  src/SystemCommands-RefactoringSupport/RBAbstractSelectionPresenter.class.st
  src/SystemCommands-RefactoringSupport/RBEnvironmentsPresenter.class.st
  src/SystemCommands-RefactoringSupport/RBFindAndReplacePreviewPresenter.class.st
  src/SystemCommands-RefactoringSupport/RBItemsSelectionPresenter.class.st
  src/SystemCommands-RefactoringSupport/SycMethodNameEditorPresenter.class.st
  src/Tool-ExternalBrowser/ExternalChangesBrowser.class.st
Labels: tests passed please review!

#10799 chore: Define baseline of TaskIt for Pharo 10
  src/BaselineOfTaskIt/BaselineOfTaskIt.class.st
Labels: tests passed please review!

#10622 Using "adding-removing" instead of "adding/removing"
  src/AST-Core/RBAssignmentNode.class.st
  src/AST-Core/RBBlockNode.class.st
  src/AST-Core/RBCascadeNode.class.st
  src/AST-Core/RBMessageNode.class.st
  src/AST-Core/RBMethodNode.class.st
  src/AST-Core/RBReturnNode.class.st
  src/Kernel/Behavior.class.st
  src/Manifest-Core/TheManifestBuilder.class.st
  src/Refactoring-Critics/RBCompositeLintRule.class.st
  src/ReleaseTests/ProtocolConventionsTest.class.st
  src/Renraku/ReProperMethodProtocolNameForAddingRemovingRule.class.st
  src/Ring-Definitions-Containers/RGAbstractContainer.class.st
  src/Ring-Definitions-Containers/RGContainer.class.st
  src/Ring-Definitions-Containers/RGPackageDefinition.class.st
  src/Ring-Definitions-Containers/RGSlice.class.st
  src/Ring-Definitions-Core/RGBehaviorDefinition.class.st
  src/Ring-Definitions-Core/RGTraitDescriptionDefinition.class.st
  src/Slot-Tests/SlotExampleMovie.class.st
Labels: tests passed please review!

#10784 Cleanup-canBeExecutedInContext
  src/Calypso-SystemPlugins-Critic-Browser/ClyFixCritiqueCommand.class.st
  src/Calypso-SystemPlugins-Critic-Browser/ClyShowDependencyCritiqueCommand.class.st
  src/Calypso-SystemPlugins-Monticello-Browser/ClyIcebergShowMethodVersionCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddExecutionCounterCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddWatchCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVariableCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyRemoveBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyRemoveExecutionCounterCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyRemoveWatchCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyVariableBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/SycVariableBreakpointCommand.class.st
  src/SystemCommands-ClassCommands/SycSingleClassCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycConvertTempToInstVarCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycExtractMethodCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycExtractSetUpRefactoring.class.st
  src/SystemCommands-SourceCodeCommands/SycExtractTempCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycInlineMethodCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycInlineTempCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycRenameArgOrTempCommand.class.st
  src/SystemCommands-VariableCommands/SycGenerateVariableAccessorsWithLazyInitializationCommand.class.st
Labels: tests passed please review!

#10763 NewValueHolder extracted to its own baseline
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/BaselineOfNewValueHolder/BaselineOfNewValueHolder.class.st
  src/BaselineOfNewValueHolder/package.st
  src/Monticello/MCPackageLoader.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: tests passed please review!

#10806 Fix #10698: Misleading Calypso warning when defining new instance variables
  src/Calypso-SystemPlugins-Traits-Queries/ClySystemEnvironment.extension.st
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
Labels: tests passed please review!

#10807 Fix #7952: Decompiler raises Error For methods from Traits on class side
  src/Flashback-Decompiler/FBDASTBuilder.class.st
Labels: tests passed please review!

#10809 Cleanup-gtInspectorAllVariablesIn
  src/FileSystem-Core/DiskDirectoryEntry.class.st
  src/FreeType-Morphic/FreeTypeFont.extension.st
  src/HeuristicCompletion-Model/CoStaticBenchmarks.class.st
  src/HeuristicCompletion-Model/ManifestHeuristicCompletionModel.class.st
  src/Kernel/LiteralVariable.class.st
  src/Refactoring2-Transformations-Tests/RBAddPragmaTransformationTest.class.st
  src/Refactoring2-Transformations-Tests/RBRemovePragmaTransformationTest.class.st
  src/Refactoring2-Transformations/RBAddPragmaTransformation.class.st
  src/Refactoring2-Transformations/RBRemovePragmaTransformation.class.st
  src/Reflectivity/ReflectiveMethod.class.st
Labels: tests passed please review!

#10808 Fix 10741: Adding an unknown SharedPool and canceling the proposed choice brings a debugger
  src/Kernel/Class.class.st
Labels: tests passed please review!

#10636 10214 improving comments and adding tests to tree searcher
  src/AST-Core-Tests/RBParseTreeSearcherTest.class.st
  src/AST-Core-Tests/RBPatternParserTest.class.st
  src/AST-Core/RBParseTreeSearcher.class.st
  src/AST-Core/RBPatternVariableNode.class.st
Labels: Need more work

#10812 Breakpoint position from cursor
  src/AST-Core-Tests/RBMessageNodeTest.class.st
  src/AST-Core-Tests/RBProgramNodeTest.class.st
  src/AST-Core/RBSequenceNode.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddConditionalBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddExecutionCounterCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddOnceBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddStaticBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAddWatchCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAdvancedDebuggingCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyAdvancedDebuggingMenuGroup.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVarAccessCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVarReadsCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyBreakOnVarWritesCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyDebuggingCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyDebuggingMenuGroup.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyInstallMetaLinkCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyMetaLinkInstallationPresenter.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyReflectivityCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyReflectivityMenuGroup.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyRemoveBreakpointCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyRemoveExecutionCounterCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyRemoveWatchCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClySourceCodeCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyUninstallMetaLinkCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyVariableBreakpointCommand.class.st
  src/Calypso-SystemTools-Core/SycOpenAdvancedDebuggingMenuCommand.extension.st
  src/SystemCommands-SourceCodeCommands/RBAssignmentNode.extension.st
  src/SystemCommands-SourceCodeCommands/RBBlockNode.extension.st
  src/SystemCommands-SourceCodeCommands/RBLiteralArrayNode.extension.st
  src/SystemCommands-SourceCodeCommands/RBMessageNode.extension.st
  src/SystemCommands-SourceCodeCommands/RBMethodNode.extension.st
  src/SystemCommands-SourceCodeCommands/RBProgramNode.extension.st
  src/SystemCommands-SourceCodeCommands/RBReturnNode.extension.st
  src/SystemCommands-SourceCodeCommands/SycAdvancedDebuggingMenuActivation.class.st
  src/SystemCommands-SourceCodeCommands/SycOpenAdvancedDebuggingMenuCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycOpenDebuggingMenuCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycOpenReflectivityMenuCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycReflectivityMenuActivation.class.st
Labels: Need more work

#10825 Remove Class>>isAbstract as it actually call the super class method
  src/Kernel/Class.class.st
Labels: tests passed please review!

#10816 Remove Spec1 Critic Browser
  src/BaselineOfQualityAssistant/BaselineOfQualityAssistant.class.st
  src/Calypso-SystemPlugins-Critic-Browser/ClyOpenCriticBrowserCommand.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: tests passed please review!
