Repository pharo-project/pharo, pull requests merged in 2023-04, with the labels that each got.

#13226 Finder: Ignoring combinations selector for collections
  src/Tool-Finder/Collection.extension.st
  src/Tool-Finder/Symbol.extension.st
Labels: tests passed please review!, pharo12

#13228 Socket error handling can get in a loop
  src/Network-Kernel/Socket.class.st
Labels: tests passed please review!

#13243 Faulty code: inspect notice
  src/AST-Core/RBNotice.class.st
  src/AST-Core/RBParseErrorNode.class.st
  src/AST-Core/RBSyntaxErrorNotice.class.st
Labels: tests passed please review!

#13248 Faulty code: various undeclared cleanups
  bootstrap/scripts/02-monticello-bootstrap/03-bootstrapMonticelloRemote.st
  bootstrap/scripts/03-metacello-bootstrap/01-loadMetacello.st
  src/AST-Core/RBNotice.class.st
  src/GeneralRules-Tests/ReGlobalVariablesUsageRuleTest.class.st
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/OpalCompiler-Tests/OCCodeReparatorTest.class.st
  src/OpalCompiler-Tests/OCCompiledMethodIntegrityTest.class.st
  src/OpalCompiler-Tests/OCCompilerTest.class.st
  src/OpalCompiler-Tests/OCDoitTest.class.st
  src/OpalCompiler-Tests/OCEnvironmentScopeTest.class.st
Labels: tests passed please review!

#13187 Inline protocol organizer
  src/CodeImport/ClassOrganization.extension.st
  src/Kernel/AllProtocol.class.st
  src/Kernel/ClassOrganization.class.st
  src/Kernel/ProtocolOrganizer.class.st
  src/TraitsV2/TaAbstractComposition.class.st
Labels: tests passed please review!

#13245 RPackageOrganizer should not call system organizer global but keep a reference
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: tests passed please review!

#13258 Make RPackageOrganizer polymorphic with SystemOrganizer
  src/CodeExport/RPackageOrganizer.extension.st
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: Reviewed and Ready to Integrate

#13231 Added new text selection for pharo
  src/Rubric-Tests/RubTextSegmentMorphTest.class.st
  src/Rubric/RubTextSegmentMorph.class.st
Labels: tests passed please review!

#13259 Remove references to SystemOrganizer
  src/Fuel-Platform-Core/FLPlatform.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/System-Support/SmalltalkImage.class.st
Labels: tests passed please review!

#13257 Rename #methodsInProtocolNamed: into #methodSelectorsInProtocol:
  src/CodeExport/ClassDescription.extension.st
  src/Deprecated12/ClassDescription.extension.st
  src/Deprecated12/ClassOrganization.extension.st
  src/Gofer-Core/GoferCleanup.class.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/OpalCompiler-Tests/MethodPragmaTest.class.st
  src/RPackage-Core/RPackage.class.st
  src/Refactoring-Environment/RBBrowserEnvironment.class.st
Labels: tests passed please review!

#13266 deprecate classesThatImplementAllOf: method. fix: #12832
  src/Deprecated12/ClassDescription.extension.st
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#13263 Snippets: split badExpressions into 3 methods
  src/AST-Core-Tests/RBCodeSnippet.class.st
Labels: Reviewed and Ready to Integrate

#13247 Protocols: Allow to compile a method with a real protocol
  src/CodeExport/ClassDescription.extension.st
  src/Fuel-Platform-Pharo-Core/FLPharoPlatform.class.st
  src/Kernel-Tests/ClassDescriptionTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/Monticello/MethodAddition.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OpalCompilerTest.class.st
  src/System-Sources/ClassDescription.extension.st
  src/System-Sources/CompiledMethod.extension.st
  src/TraitsV2/TraitedClass.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: Reviewed and Ready to Integrate

#13212 Move weak dictionaries to new finalization
  src/Announcements-Core/WeakAnnouncementSubscription.class.st
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/Collections-Support/WeakKeyAssociation.class.st
  src/Collections-Unordered-Tests/DictionaryTest.class.st
  src/Collections-Unordered-Tests/TDictionaryKeyAccessTest.trait.st
  src/Collections-Unordered-Tests/TDictionaryValueAccessTest.trait.st
  src/Collections-Weak-Tests/WeakIdentityKeyDictionaryTest.class.st
  src/Collections-Weak-Tests/WeakKeyDictionaryTest.class.st
  src/Collections-Weak-Tests/WeakKeyToCollectionDictionaryTest.class.st
  src/Collections-Weak/WeakIdentityKeyDictionary.class.st
  src/Collections-Weak/WeakKeyAssociation.class.st
  src/Collections-Weak/WeakKeyDictionary.class.st
  src/Collections-Weak/WeakKeyToCollectionDictionary.class.st
  src/Collections-Weak/WeakRegistry.class.st
  src/Fuel-Tests-Core/FLWeakObjectsTest.class.st
  src/Kernel-Tests-Extended/ClassTest.class.st
  src/Kernel/Behavior.class.st
  src/Kernel/Object.class.st
  src/Monticello/MCPackageLoader.class.st
  src/Reflectivity-Tests/LinkInstallerTest.class.st
  src/Reflectivity/MetaLinkRegistry.class.st
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
  src/System-Finalization-Tests/MockFinalizerAction.class.st
  src/System-Finalization/WeakFinalizationList.class.st
  src/System-Finalization/WeakFinalizerItem.class.st
  src/System-Object Events/EventManager.class.st
  src/System-SessionManager/SessionManager.class.st
  src/System-Support/SmalltalkImage.class.st
Labels: Need more work

#13261 Faulty Code: compiler honor failBlock
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/RBCodeSnippetScriptingTest.extension.st
  src/OpalCompiler-Tests/RBCodeSnippetTest.extension.st
Labels: tests passed please review!

#13281 hotfix ClassTest>>#testCommentSourcePointer
  src/Kernel-Tests-Extended/ClassTest.class.st
Labels: tests passed please review!

#13275 Remove ClassOrganization>>allProtocol
  src/Kernel/ClassOrganization.class.st
Labels: tests passed please review!

#13277 Faulty code: move code reparator to RBNotice
  src/OpalCompiler-Core/OCUndeclaredVariableNotice.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Core/RBNotice.extension.st
  src/OpalCompiler-Tests/OCCodeReparatorTest.class.st
  src/OpalCompiler-Tests/RBCodeSnippetTest.extension.st
Labels: tests passed please review!

#13268 do not compute message sends dependencies in browser dependencies tool
  src/Tool-DependencyAnalyser-UI-Tab/DABrowserToolMorph.class.st
  src/Tool-DependencyAnalyser/DADependencyChecker.class.st
  src/Tool-DependencyAnalyser/DAPackageRelationGraph.class.st
Labels: tests passed please review!

#13280 Faulty code: add permitUndeclared
  src/AST-Core/RBNotice.class.st
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableNotice.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/MockForCompilation.class.st
Labels: tests passed please review!

#13242 StFilterFuzzy>>#applyFilterWithQuery send missing #takeFirst:
  src/Collections-Abstract-Tests/TSubCollectionAccess.trait.st
  src/Collections-Abstract/SequenceableCollection.class.st
Labels: tests passed please review!

#13279 Bootstrap: allow to authetificate github requests during the bootstrap
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: tests passed please review!

#13289 Remove class AllProtocol
  src/Kernel/AbstractProtocol.class.st
  src/Kernel/AllProtocol.class.st
  src/Kernel/ClassOrganization.class.st
  src/Kernel/Protocol.class.st
Labels: tests passed please review!

#13290 Remove PBOldExtendedBootstrap
  src/Pharo30Bootstrap/PBOldExtendedBootstrap.class.st
Labels: Reviewed and Ready to Integrate

#13294 Remove dependency of Collections-Abstract/Sequenceable over Random-Core
  src/Collections-Abstract/SequenceableCollection.class.st
  src/Collections-Sequenceable-Tests/Heap.extension.st
  src/Collections-Sequenceable/Array2D.class.st
  src/Collections-Sequenceable/Heap.class.st
  src/Collections-Sequenceable/Interval.class.st
  src/Random-Core/Array2D.extension.st
  src/Random-Core/Interval.extension.st
  src/Random-Core/SequenceableCollection.extension.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: Reviewed and Ready to Integrate

#13302 Some compiler cleanup
  src/Deprecated12/SyntaxErrorNotification.class.st
  src/OpalCompiler-Core/Behavior.extension.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
  src/OpalCompiler-Core/OCSemanticScope.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
Labels: Reviewed and Ready to Integrate

#13300 Faulty parser: better faulty literal (byte) arrays
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core/RBParser.class.st
Labels: tests passed please review!

#13292 enable Fluid Class Definition by default
  src/Kernel/ClassDefinitionPrinter.class.st
Labels: tests passed please review!

#13298 Do not disable system announcements during rpackage tests
  src/Monticello-Tests/RPackageClassesSynchronisationTest.class.st
  src/Monticello-Tests/RPackageMCSynchronisationTest.class.st
  src/RPackage-Tests/RPackageObsoleteTest.class.st
  src/RPackage-Tests/RPackageTest.class.st
  src/RPackage-Tests/RPackageTestCase.class.st
Labels: Reviewed and Ready to Integrate

#13216 Refactor: insert new class refactoring
  src/Refactoring-Core/RBChildrenToSiblingsRefactoring.class.st
  src/Refactoring-Core/RBCopyClassRefactoring.class.st
  src/Refactoring-Core/RBInsertNewClassRefactoring.class.st
  src/Refactoring-Core/RBSplitClassRefactoring.class.st
  src/Refactoring2-Transformations-Tests/RBCopyPackageParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBInsertClassParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBRenameClassParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBTransformationsTest.class.st
  src/Refactoring2-Transformations/RBInsertNewClassTransformation.class.st
  src/Refactoring2-Transformations/RBRenameAndDeprecateClassTransformation.class.st
  src/Refactoring2-Transformations/RBSplitClassTransformation.class.st
  src/SystemCommands-ClassCommands/SycCmAddSubclassCommand.class.st
  src/SystemCommands-ClassCommands/SycCmInsertSubclassCommand.class.st
  src/SystemCommands-ClassCommands/SycCmInsertSuperclassCommand.class.st
Labels: tests passed please review!

#13317 Clean ChangeSetClassChangesTest
  src/System-Changes-Tests/ChangeSetClassChangesTest.class.st
Labels: easyReview

#13306 Remove SystemOrganisation global
  src/Pharo30Bootstrap/PBImageBuilder50.class.st
Labels: tests passed please review!

#13325 Remove deprecated modelwants steps in in p12
  src/System-Model/Model.class.st
Labels: pharo12

#13333 Remove nullProtocolName
  src/Deprecated12/ClassDescription.extension.st
  src/Kernel/Protocol.class.st
  src/Tool-Base/AbstractTool.class.st
Labels: tests passed please review!, easyReview

#13331 Use Protocol>>#unclassified instead of #defaultName
  src/Kernel/Protocol.class.st
  src/Monticello-Tests/RPackageExtensionMethodsSynchronisationTest.class.st
  src/RPackage-Core/RPackage.class.st
Labels: tests passed please review!

#13238 Faulty code: forbid read of undeclared variables
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel/LiteralVariable.class.st
  src/Kernel/UndeclaredVariable.class.st
  src/Kernel/UndeclaredVariableRead.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Tests/OCCompilerTest.class.st
  src/OpalCompiler-Tests/OCEnvironmentScopeTest.class.st
Labels: Reviewed and Ready to Integrate

#13343 extract return and use and: expression. add some tests
  src/Graphics-Tests/RectangleTest.class.st
  src/Kernel/Rectangle.class.st
Labels: Reviewed and Ready to Integrate

#13339 Remove general help package from the repo
  src/BaselineOfGeneralHelp/BaselineOfGeneralHelp.class.st
  src/BaselineOfGeneralHelp/package.st
  src/HelpSystem-Core/CustomHelp.class.st
  src/HelpSystem-Core/CustomHelpHelpBuilder.class.st
  src/HelpSystem-Core/CustomHelpTextFormatter.class.st
  src/HelpSystem-Core/HelpBrowser.class.st
  src/HelpSystem-Core/HelpBuilder.class.st
  src/HelpSystem-Core/HelpTopic.class.st
  src/HelpSystem-Core/HelpTopicListItemWrapper.class.st
  src/HelpSystem-Core/SystemHelp.class.st
  src/HelpSystem-Core/package.st
  src/HelpSystem-Tests/AdvancedHelpBrowserDummy.class.st
  src/HelpSystem-Tests/ClassAPIHelpBuilderTest.class.st
  src/HelpSystem-Tests/CustomHelpTest.class.st
  src/HelpSystem-Tests/HelpBrowserTest.class.st
  src/HelpSystem-Tests/HelpTopicListItemWrapperTest.class.st
  src/HelpSystem-Tests/HelpTopicTest.class.st
  src/HelpSystem-Tests/WikiStyleHelpBuilderTest.class.st
  src/HelpSystem-Tests/WikiStyleHelpTest.class.st
  src/HelpSystem-Tests/package.st
  src/Regex-Help/RegexAPIDocumentation.class.st
  src/Regex-Help/RegexHelp.class.st
  src/Regex-Help/package.st
  src/SUnit-Help/SUnitAPIDocumentation.class.st
  src/SUnit-Help/SUnitHelp.class.st
  src/SUnit-Help/SUnitTutorial.class.st
  src/SUnit-Help/package.st
Labels: tests passed please review!

#13340 Fix and load SystemCommands tests
  src/BaselineOfSystemCommands/BaselineOfSystemCommands.class.st
  src/Calypso-SystemTools-Core/ClySourceCodeContext.class.st
  src/SystemCommands-MethodCommands-Tests/SycConvertTempToinstVarCommandTest.class.st
  src/SystemCommands-MethodCommands-Tests/SycInlineTempCommandTest.class.st
  src/SystemCommands-MethodCommands-Tests/SycRenameArgOrTempCommandTest.class.st
Labels: tests passed please review!

#13336 Cleanup: Move as "Arrayed" tagged test classes from generic "Collections-Tests" package to specific "Collections-Native-Tests" package
  src/BaselineOfKernelTests/BaselineOfKernelTests.class.st
  src/Collections-Native-Tests/ByteArrayTest.class.st
  src/Collections-Native-Tests/Float32ArrayTest.class.st
  src/Collections-Native-Tests/Float64ArrayTest.class.st
  src/Collections-Native-Tests/IntegerArrayTest.class.st
  src/Collections-Native-Tests/NativeArrayTest.class.st
  src/Collections-Native-Tests/package.st
Labels: Reviewed and Ready to Integrate

#13320 Deprecate OneShotArmed / doOnlyOnce: mechanism in ProtoObject (P12)
  src/Deprecated12/ProtoObject.extension.st
  src/GeneralRules-Tests/ReSmalllintTest.class.st
  src/Kernel/ProtoObject.class.st
  src/Refactoring-Tests-Critics/RBSmalllintTestObject.class.st
  src/Reflectivity-Tools/DoOnlyOnceIconStyler.class.st
Labels: Reviewed and Ready to Integrate, pharo12

#13344 RBNotice: add isSyntaxError and make it easier to sort them
  src/AST-Core/RBNotice.class.st
  src/AST-Core/RBSyntaxErrorNotice.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OCCompilerTest.class.st
Labels: tests passed please review!

#13327 Cleanup small cleanups in baseline of base libraries package
  src/BaselineOfBaseLibraries/BaselineOfBaseLibraries.class.st
  src/BaselineOfBaseLibraries/ManifestBaselineOfBaseLibraries.class.st
Labels: Reviewed and Ready to Integrate, pharo12

#13311 Remove usage of Protocol>>#canBeRemoved
  src/Kernel/ClassOrganization.class.st
  src/Kernel/Protocol.class.st
  src/Refactoring2-Transformations/RBRemoveProtocolTransformation.class.st
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
Labels: tests passed please review!

#13332 4969-Epicea-Reverting-a-class-remove-looses-class-comment
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers/EpApplyVisitor.class.st
Labels: Reviewed and Ready to Integrate

#13031 Update find sdl2
  src/OSWindow-SDL2/SDL2.class.st
  src/UnifiedFFI/FFIMacLibraryFinder.class.st
Labels: Reviewed and Ready to Integrate

#13314 Remove the need to give a SystemOrganizer to SystemDictionary
  src/Pharo30Bootstrap/PBBootstrap30.class.st
  src/Pharo30Bootstrap/PBImageBuilder50.class.st
  src/SUnit-Tests/ClassFactoryWithOrganizationTest.class.st
  src/System-Support-Tests/SystemDictionaryTest.class.st
  src/System-Support/SystemDictionary.class.st
Labels: tests passed please review!

#13346 Remove ClassOrganization>>hasOrganizedClass
  src/Deprecated12/ClassOrganization.extension.st
  src/Kernel/ClassOrganization.class.st
Labels: tests passed please review!

#13334 Simplify protocol removals
  src/Deprecated12/ClassOrganization.extension.st
  src/Gofer-Core/GoferCleanup.class.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/OpalCompiler-Tests/MethodPragmaTest.class.st
  src/Refactoring-Changes/RBRemoveProtocolChange.class.st
Labels: Reviewed and Ready to Integrate

#13358 Always announce creation of new protocols
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
Labels: tests passed please review!

#13362 use and: expression instead of ifTrue:ifFalse: expression
  src/Kernel/CompiledMethod.class.st
  src/Kernel/Duration.class.st
  src/Kernel/Integer.class.st
  src/Kernel/Point.class.st
  src/TraitsV2/Behavior.extension.st
Labels: Reviewed and Ready to Integrate

#13356 Make protocols an array in ClassOrganization
  src/CodeExport/ClassOrganization.extension.st
  src/Kernel/ClassOrganization.class.st
Labels: Reviewed and Ready to Integrate

#13369 Rename Protocol class>>#ambiguous into #traitConflictName
  src/Kernel/Protocol.class.st
  src/TraitsV2-Compatibility/TraitMethodDescription.class.st
  src/TraitsV2-Tests/TraitMethodDescriptionTest.class.st
  src/TraitsV2/Protocol.extension.st
  src/TraitsV2/TaAbstractComposition.class.st
  src/TraitsV2/TaSequence.class.st
Labels: Reviewed and Ready to Integrate

#13329 Cleanup: Better ratio of commented classes
  src/ReleaseTests/ReleaseTest.class.st
Labels: Reviewed and Ready to Integrate

#13360 Clean ClassRenameFixTest
  src/System-Changes-Tests/ClassRenameFixTest.class.st
Labels: tests passed please review!

#13375 rename truncation and roundoff to truncation and round off protocol in Rectangle
  src/Kernel/Rectangle.class.st
Labels: Reviewed and Ready to Integrate

#13378 refactor ASTCache
  src/AST-Core/ASTCache.class.st
Labels: Reviewed and Ready to Integrate

#13379 ASTCache: use a double weak dictionary
  src/AST-Core/ASTCache.class.st
Labels: Reviewed and Ready to Integrate

#13392 OpalCompiler restore undeclared menu on the playground
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#13408 ASTCache>>#at:put: prevent TOCTOU when cleaning the cache
  src/AST-Core/ASTCache.class.st
Labels: tests passed please review!

#13400 extract return from Float>>#asApproximateFractionAtOrder:
  src/Kernel/Float.class.st
Labels: Reviewed and Ready to Integrate

#13396 ClyJumpToTestMethodCommand>>#generateTestMethodNamed:in: use good protocol
  src/Calypso-SystemPlugins-SUnit-Browser/ClyJumpToTestMethodCommand.class.st
Labels: Reviewed and Ready to Integrate

#13397 Faulty code importers: use new compiler API
  src/CodeImport/MethodChunk.class.st
  src/Monticello/MCMethodDefinition.class.st
Labels: Reviewed and Ready to Integrate

#13402 Completion can extends keyword messages
  src/AST-Core/RBMessageNode.class.st
  src/AST-Core/RBPragmaNode.class.st
  src/HeuristicCompletion-Model/CoGlobalSelectorFetcher.class.st
Labels: tests passed please review!

#13350 AST: fix node positions, and test them systematically
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBCodeSnippetTest.class.st
  src/AST-Core/RBParseErrorNode.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBVariableNode.class.st
Labels: Reviewed and Ready to Integrate

#13404 FluidClassBuilder tests should clean the system
  src/FluidClassBuilder-Tests/FluidClassBuilderTest.class.st
Labels: tests passed please review!

#13319 Fix bug in syntaxt highlighting of comments
  src/PharoDocComment/SHRBTextStyler.extension.st
  src/Shout-Tests/SHRBStyleAttributionTest.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#13410 provide compatibility with old finalisation mechanism
  src/Collections-Weak/WeakRegistry.class.st
Labels: pharo11

#13383 Remove #protocolsOfSelector: and implement #protocolOfSelector:
  src/Kernel/ClassOrganization.class.st
Labels: Reviewed and Ready to Integrate

#13411 Refactoring rotten green test on Context
  src/Kernel-Tests/ContextTest.class.st
Labels: Reviewed and Ready to Integrate

#13393 Try to move workspace variables further (lite)
  src/Debugging-Core/Context.extension.st
  src/OpalCompiler-Core/Behavior.extension.st
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Core/OCAbstractScope.class.st
  src/OpalCompiler-Core/OCContextualDoItSemanticScope.class.st
  src/OpalCompiler-Core/OCExtraBindingScope.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
  src/OpalCompiler-Core/OCSemanticScope.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/Reflectivity/RFSemanticAnalyzer.class.st
  src/Ring-Core/RGBehavior.class.st
Labels: tests passed please review!

#13407 Fix dependies of RPackage-Core
  src/RPackage-Core/ManifestRPackageCore.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: tests passed please review!

#13251 12885-Objectassert-fails-with-non-booleans-contradicting-its-own-comment
  src/Kernel-Tests/ObjectTest.class.st
  src/Kernel/Object.class.st
Labels: Reviewed and Ready to Integrate

#13405 Remove ClassFactoryForTestCaseTest>>#testDuplicateClassWithNewName
  src/SUnit-Core/ClassFactoryForTestCase.class.st
  src/SUnit-Tests/ClassFactoryForTestCaseTest.class.st
Labels: tests passed please review!

#13426 Make protocol of super method a priority in MethodClassifier
  src/Tool-Base/MethodClassifier.class.st
  src/Tools-Tests/MethodClassifierMock.class.st
  src/Tools-Tests/MethodClassifierMockSuperclass.class.st
  src/Tools-Tests/MethodClassifierTest.class.st
Labels: Reviewed and Ready to Integrate

#13415 Change Protocol to use an array for methodSelectors directly
  src/Kernel/ClassOrganization.class.st
  src/Kernel/Protocol.class.st
Labels: Reviewed and Ready to Integrate

#13412 use fixed NewTools version
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: Reviewed and Ready to Integrate

#13418 Calypso: check if node is nil before calling isCommentNode and cie
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyDebuggingCommand.class.st
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyReflectivityCommand.class.st
Labels: tests passed please review!

#13438 CompiledCodeTest>>#testMessages should not assume order of elements
  src/Kernel-Tests/CompiledCodeTest.class.st
Labels: Reviewed and Ready to Integrate

#13435 Remove dead code in Bootstrap
  src/Pharo30Bootstrap/PBBootstrap30.class.st
  src/Pharo30Bootstrap/PBDefinitionFetcher.class.st
Labels: Reviewed and Ready to Integrate

#13341 Striked through symbols who are names of a deprecated global
  src/Deprecated12/ManifestDeprecated12.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#13421 AST: starting visiting comments
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBCodeSnippetTest.class.st
  src/AST-Core-Traits/TRBProgramNodeVisitor.trait.st
  src/AST-Core/RBComment.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBProgramNodeVisitor.class.st
  src/HeuristicCompletion-Model/CoASTResultSetBuilder.class.st
Labels: tests passed please review!

#13445 Use fixed spec version for Pharo 11
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: Reviewed and Ready to Integrate

#13446 Fix typo introduced in merge
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!, IMPORTANT ISSUE

#13431 Cut dependency from CommandLine to UIManager
  src/System-CommandLineHandler/PharoCommandLineHandler.class.st
  src/UIManager/PharoCommandLineHandler.extension.st
Labels: tests passed please review!, easyReview

#13443 Keep pushing protocols usage
  src/Deprecated12/ClassOrganization.extension.st
  src/Epicea-Tests/EpCodeChangeIntegrationTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyPreviewerTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers-Tests/EpRevertTest.class.st
  src/EpiceaBrowsers/EpApplyPreviewer.class.st
  src/EpiceaBrowsers/EpApplyVisitor.class.st
  src/EpiceaBrowsers/EpHasImpactVisitor.class.st
  src/Gofer-Tests/GoferOperationTest.class.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/Monticello-Tests/MCPackageTest.class.st
  src/Monticello-Tests/RPackageClassesSynchronisationTest.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
  src/Refactoring-Changes/RBAddProtocolChange.class.st
  src/Refactoring2-Transformations-Tests/RBMethodProtocolTransformationTest.class.st
  src/System-Announcements-Tests/SystemAnnouncerTest.class.st
Labels: tests passed please review!

#13432 Backport #13426
  src/Tool-Base/MethodClassifier.class.st
  src/Tools-Tests/MethodClassifierMock.class.st
  src/Tools-Tests/MethodClassifierMockSuperclass.class.st
  src/Tools-Tests/MethodClassifierTest.class.st
Labels: tests passed please review!

#13450 Rubric editors (thus calypso) execute doit actions in faulty mode
  src/Rubric-Tests/RubSmalltalkEditorTest.class.st
  src/Rubric/RubSmalltalkEditor.class.st
Labels: tests passed please review!

#13459 Refactoring BlockClosureTest >> testCannotReturn
  src/Kernel-Tests-Extended/BlockClosureTest.extension.st
Labels: Reviewed and Ready to Integrate

#13460 Use Pharo12 branch of Spec and NewTools
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: tests passed please review!

#13453 Improve ClassOrganization copy
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassOrganization.class.st
Labels: Reviewed and Ready to Integrate

#13458 Remove ClassOrganization>>#silentlyRenameProtocolNamed:toBe: in favor of always announcing the rename
  src/Deprecated12/ClassOrganization.extension.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/Gofer-Tests/GoferOperationTest.class.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassOrganization.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
  src/TraitsV2-Tests/TraitMethodDescriptionTest.class.st
Labels: Reviewed and Ready to Integrate

#13422 faulty code: test runtimeSyntaxError
  src/Kernel-Tests-WithCompiler/RuntimeSyntaxErrorTest.class.st
  src/Kernel/Context.class.st
  src/Kernel/RuntimeSyntaxError.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
Labels: Reviewed and Ready to Integrate

#13398 Compiler: simplify DoIt
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core-Tests/RBProgramNodeTest.class.st
  src/AST-Core/RBDoItMethodNode.class.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBProgramNode.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/RBProgramNode.extension.st
Labels: Reviewed and Ready to Integrate

#13423 Cleanup OpalCompiler & CompilationContext
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/IRMethod.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/Reflectivity/RFSemanticAnalyzer.class.st
Labels: Reviewed and Ready to Integrate

#13467 Fix bug in parenthesis highlight
  src/Shout-Tests/SHRBStyleAttributionTest.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#13469 Debug can recompile doit and uninstalled method
  src/Debugger-Model-Tests/RecompileTest.class.st
  src/Debugger-Model-Tests/StepIntoTest.class.st
  src/Debugger-Model/DebugContext.class.st
  src/Debugger-Model/DebugSession.class.st
Labels: tests passed please review!

#13471 Kill VariableNotDeclared
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/Kernel/UndefinedObject.class.st
  src/Kernel/VariableNotDeclared.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
Labels: tests passed please review!

#13472 Compiler: explicit the need of requestor scope
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
  src/OpalCompiler-Tests/OCDoitTest.class.st
Labels: tests passed please review!

#13479 Compiler: remove #optionEmbeddSources
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/OpalCompiler-Tests/OpalCompilerTest.class.st
  src/Slot-Tests/DoItVariableTest.class.st
  src/TraitsV2-Compatibility/TraitMethodDescription.class.st
Labels: tests passed please review!

#13481 remove-embeddSourceInTrailer
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#13480 Make #renameProtocolNamed:toBe: manage nils
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassOrganization.class.st
Labels: tests passed please review!

#13484 Directly update source pointer without creating an additional compiled method
  src/Kernel/CompiledMethod.class.st
  src/Kernel/CompiledMethodTrailer.class.st
Labels: Reviewed and Ready to Integrate

#13473 Completion menu: some love on the detail window
  src/HeuristicCompletion-Model/CoGlobalSelectorFetcher.class.st
  src/HeuristicCompletion-Tests/CoCompletionEngineTest.class.st
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion-Morphic/NECMenuMorph.class.st
  src/NECompletion/NECSelectorEntry.class.st
  src/NECompletion/NECSymbolEntry.class.st
Labels: Reviewed and Ready to Integrate

#13486 Faulty code: improve highlight and icons
  src/Reflectivity-Tools/ErrorNodeStyler.class.st
  src/Rubric/RubUnderlinedSegmentMorph.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#13489 add SHRBStyleAttributionTest>>#testErrorStyle
  src/Shout-Tests/SHRBStyleAttributionTest.class.st
Labels: Reviewed and Ready to Integrate

#13492 Rename #removeMethodTag: into #removeProtocolIfEmpty:
  src/Calypso-SystemQueries/ClyTaggedMethodGroup.class.st
  src/Deprecated12/ClassDescription.extension.st
  src/Kernel/ClassDescription.class.st
  src/SystemCommands-MethodCommands/SycSilentlyRemoveMethodStrategy.class.st
Labels: tests passed please review!

#13449 Introduce annotations
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Traits/TRBProgramNodeVisitor.trait.st
  src/AST-Core/RBAnnotationMarkNode.class.st
  src/AST-Core/RBBinarySelectorToken.class.st
  src/AST-Core/RBDumpVisitor.class.st
  src/AST-Core/RBMessageNode.class.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBProgramNodeVisitor.class.st
  src/AST-Core/RBSimpleFormatter.class.st
  src/AST-Core/RBToken.class.st
  src/EnlumineurFormatter/EFFormatter.class.st
  src/Kernel-ExtraUtils/ClassHierarchyPrinterTest.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/RBAnnotationMarkNode.extension.st
  src/OpalCompiler-Tests/OCAnnotationTest.class.st
Labels: tests passed please review!

#13348 Add support to deprecate globals
  src/Kernel/GlobalVariable.class.st
  src/Shout-Tests/SHRBDeprecatedClassMock.class.st
  src/Shout-Tests/SHRBStyleAttributionTest.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: Reviewed and Ready to Integrate

#13301 Vocabulary: propose "script" in compiler
  src/Debugger-Model-Tests/StepIntoTest.class.st
  src/Debugger-Model/DebugContext.class.st
  src/HeuristicCompletion-Model/CoASTResultSetBuilder.class.st
  src/Monticello-Tests/MCStWriterTest.class.st
  src/NECompletion/CompletionContext.class.st
  src/OpalCompiler-Core/Context.extension.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OCCompileWithFailureTest.class.st
  src/OpalCompiler-Tests/OCDoitTest.class.st
  src/OpalCompiler-Tests/RBCodeSnippet.extension.st
  src/OpalCompiler-Tests/RBCodeSnippetTest.extension.st
  src/ProfilerUI/ProfilerModel.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Shout-Tests/SHRBStyleAttributionTest.class.st
  src/Shout-Tests/SHRBTextStylerTest.class.st
  src/Shout/SHRBTextStyler.class.st
  src/Slot-Tests/DoItVariableTest.class.st
  src/Tool-Profilers/TimeProfiler.class.st
Labels: tests passed please review!

#13500 Snippet: test more comments and fix some
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/OpalCompiler-Core/ArgumentVariable.class.st
  src/OpalCompiler-Core/TemporaryVariable.class.st
  src/Shout/ArgumentVariable.extension.st
  src/Shout/SHRBTextStyler.class.st
Labels: Reviewed and Ready to Integrate

#13501 SHRBTextStyler class>>#blueStyleTable distinguish some variables
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#13496 Synch bug in RPackage removal
  src/FluidClassBuilder-Tests/FluidClassBuilderTest.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Tests/RPackageOrganizerAndSystemOrganizeSynchTest.class.st
  src/System-Support/SystemOrganizer.class.st
Labels: tests passed please review!

#13502 Style literal arrays
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core/RBLiteralArrayNode.class.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBScanner.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#13506 Make Protocol announcements use real protocols
  src/Calypso-SystemQueries/ClassDescription.extension.st
  src/Calypso-SystemQueries/TraitedMetaclass.extension.st
  src/Deprecated12/ClassOrganization.extension.st
  src/Deprecated12/ProtocolRenamed.extension.st
  src/Epicea/EpMonitor.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/Kernel/Protocol.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/SUnit-Core/ClassTestCase.class.st
  src/System-Announcements-Tests/SystemAnnouncerTest.class.st
  src/System-Announcements/ProtocolAdded.class.st
  src/System-Announcements/ProtocolAnnouncement.class.st
  src/System-Announcements/ProtocolRemoved.class.st
  src/System-Announcements/ProtocolRenamed.class.st
Labels: tests passed please review!

#13514 AST: cleanup extension methods from OpalCompiler
  src/AST-Core/CompiledMethod.extension.st
  src/AST-Core/RBMethodNode.class.st
  src/AST-Core/RBValueNode.class.st
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/OpalCompiler-Tests/OCBytecodeDecompilerExamplesTest.class.st
  src/Reflectivity-Tests/ReflectivityReificationTest.class.st
  src/Reflectivity/Breakpoint.class.st
  src/Reflectivity/RFOperationReification.class.st
  src/Reflectivity/ReflectiveMethod.class.st
Labels: tests passed please review!

#13517 Compiler: doSemanticAnalysis yourself
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/OpalCompiler-Tests/OCASTCheckerTest.class.st
  src/Reflectivity/RFSemanticAnalyzer.class.st
Labels: Reviewed and Ready to Integrate

#13519 Clean info of MethodChangeRecord
  src/System-Changes/ChangeSet.class.st
  src/System-Changes/ClassChangeRecord.class.st
  src/System-Changes/MethodChangeRecord.class.st
Labels: tests passed please review!

#13511 Detach compilationContext a little
  src/NECompletion/RBVariableNode.extension.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/Reflectivity/RFASTTranslator.class.st
Labels: Reviewed and Ready to Integrate

#13544 Reflectivity: make tests more reliable (and fix a bug)
  src/Reflectivity-Tests/LinkInstallerTest.class.st
  src/Reflectivity-Tests/MetaLinkObjectAPITest.class.st
  src/Reflectivity-Tests/MetaLinkRegistryTest.class.st
  src/Reflectivity-Tests/MetaLinkTest.class.st
  src/Reflectivity-Tests/ReflectiveMethodTest.class.st
  src/Reflectivity-Tests/ReflectivityControlTest.class.st
  src/Reflectivity-Tests/ReflectivityReificationTest.class.st
  src/Reflectivity-Tests/ReflectivityTest.class.st
  src/Reflectivity-Tests/ReflectivityTestCase.class.st
  src/Reflectivity/RFASTTranslator.class.st
  src/Reflectivity/ReflectiveMethod.class.st
Labels: Reviewed and Ready to Integrate

#13527 CompiledMethodTrailer: use 4 bytes as sourcePointer
  src/Kernel/CompiledMethodTrailer.class.st
Labels: Reviewed and Ready to Integrate

#13536 Make sure class parser tests clean the system
  src/ClassParser-Tests/ASTClassBuilderTest.class.st
Labels: tests passed please review!

#13539 Classify method before installing them
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
Labels: tests passed please review!

#13540 Scope: generalize target class
  src/AST-Core/RBMethodNode.class.st
  src/ClassParser/CDClassNameNode.class.st
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCAbstractScope.class.st
  src/OpalCompiler-Core/OCSemanticScope.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: Reviewed and Ready to Integrate

#13546 CompiledMethodTrailer: more cleanup, do not use it for #endPC
  src/Fuel-Tests-Core/FLCompiledMethodSerializationTest.class.st
  src/Kernel/CompiledMethod.class.st
  src/Kernel/CompiledMethodTrailer.class.st
  src/OpalCompiler-Tests/OpalCompilerTest.class.st
Labels: tests passed please review!

#13550 CompiledMethodTrailer-Cleanup-even-more
  src/Flashback-Decompiler/FBDDecompiler.class.st
  src/Fuel-Tests-Core/FLCompiledMethodSerializationTest.class.st
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel/Behavior.class.st
  src/Kernel/CompiledMethod.class.st
  src/Kernel/CompiledMethodTrailer.class.st
  src/OpalCompiler-Core/Behavior.extension.st
  src/TraitsV2/TaAbstractComposition.class.st
  src/UnifiedFFI/FFICalloutMethodBuilder.class.st
Labels: Reviewed and Ready to Integrate

#13554 AST: kill multiple keyword token
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBScannerTest.class.st
  src/AST-Core/RBLiteralToken.class.st
  src/AST-Core/RBMultiKeywordLiteralToken.class.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBScanner.class.st
  src/AST-Core/RBToken.class.st
Labels: tests passed please review!

#13553 add new test RBCodeSnippet class>>#badScanner with special scanner hacks
  src/AST-Core-Tests/RBCodeSnippet.class.st
Labels: tests passed please review!

#13530 Simplify ClassOrganization>>removeElement: and remove protocol if empty
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassOrganization.class.st
Labels: tests passed please review!

#13538 Ensure ThreadedFFI tests terminate all launched processes
  src/ThreadedFFI-Tests/TFCallbacksTest.class.st
Labels: tests passed please review!

#13558 Do not use #trailer to read the sourcePointer
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#13560 Cleanup: Fuel does not need to use #copyWithTrailerBytes:
  src/Fuel-Core/FLCompiledMethodCluster.class.st
  src/Fuel-Tests-Core/CompiledMethod.extension.st
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#13562 AST: cleanup scanner
  src/AST-Core/RBScanner.class.st
Labels: tests passed please review!

#13551 Factorize some code in recompilation management
  src/TraitsV2/TraitedClass.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: tests passed please review!

#13521 Compiler get more scope responsibilities
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OCASTTranslatorTest.class.st
Labels: Reviewed and Ready to Integrate

#13564 Cleanup: do not reference CompiledMethodTrailer in ReflectiveMethod
  src/Kernel/CompiledBlock.class.st
  src/Kernel/CompiledMethod.class.st
  src/Reflectivity/ReflectiveMethod.class.st
Labels: tests passed please review!

#13570 Make shift tests more robust
  src/Shift-ClassInstaller-Tests/ShClassInstallerTest.class.st
Labels: tests passed please review!

#13533 Improve ClassDescription>>#addAndClassifySelector:withMethod:inProtocol:
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#13575 Compiler: Cleanup trailer for the frontend
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/IRMethod.class.st
  src/OpalCompiler-Core/IRTranslator.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/Slot-Tests/DoItVariableTest.class.st
Labels: Reviewed and Ready to Integrate

#13457 Use #protocolOfSelector: in CompiledMethod>>#category
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#13569 Add compiler option to not optimise special sends
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/IRBytecodeGenerator.class.st
  src/OpalCompiler-Tests/OCASTTranslatorTest.class.st
  src/OpalCompiler-Tests/OCBytecodeGeneratorTest.class.st
  src/OpalCompiler-Tests/OCCalledMethodProxy.class.st
  src/OpalCompiler-Tests/OCOpalExamples.class.st
  src/OpalCompiler-Tests/OCSpecialSelectorTest.class.st
Labels: tests passed please review!

#13577 Fix wrong double click
  src/Morphic-Base/MouseClickState.class.st
  src/Morphic-Tests/MouseClickStateTest.class.st
Labels: tests passed please review!

#13548 Autocompletion must replace from start of the word if case-insensitiv…
  src/NECompletion-Morphic/CompletionEngine.class.st
Labels: tests passed please review!

#13578 this PR introduces CompiledMethod>>#clearSourcePointer and #sourcePointer:
  src/Fuel-Core/FLCompiledMethodCluster.class.st
  src/Fuel-Tests-Core/CompiledMethod.extension.st
  src/Kernel/CompiledMethod.class.st
  src/OpalCompiler-Core/Behavior.extension.st
  src/OpalCompiler-Tests/MethodMapTest.class.st
  src/Reflectivity/ReflectiveMethod.class.st
  src/System-Sources/CompiledMethod.extension.st
  src/TraitsV2/TaAbstractComposition.class.st
  src/UnifiedFFI/FFICalloutMethodBuilder.class.st
Labels: Reviewed and Ready to Integrate

#13582 Do not rely on #protocolNameOfElement: in Traits
  src/TraitsV2-Tests/ClassTraitTest.class.st
  src/TraitsV2-Tests/T2TraitWithPackagesTest.class.st
  src/TraitsV2-Tests/TraitMethodDescriptionTest.class.st
  src/TraitsV2-Tests/TraitPureBehaviorTest.class.st
  src/TraitsV2/TaAbstractComposition.class.st
Labels: tests passed please review!

#13466 Improve #renameProtocolNamed:toBe:
  src/Deprecated12/ClassOrganization.extension.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassOrganization.class.st
  src/Monticello-Tests/RPackageClassesSynchronisationTest.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/TraitsV2-Tests/T2TraitWithCategoriesTest.class.st
Labels: tests passed please review!

#13096 rubric: doit actions on empty selection selects the current expression
  src/Rubric-Tests/RubSmalltalkEditorTest.class.st
  src/Rubric/RubSmalltalkEditor.class.st
Labels: tests passed please review!
