Repository pharo-project/pharo, pull requests merged in 2023-01, with the labels that each got.

#12160 Cleanup: fix lints for morphic classes on class side #initialize (SECOND ATTEMPT)
  src/Calypso-NavigationModel/ClyEnvironmentPlugin.class.st
  src/Commander-Activators-WorldMenu/CmdWorldMenuRegistration.class.st
  src/FreeType/FreeTypeCache.class.st
  src/Graphics-Canvas/CornerRounder.class.st
  src/Graphics-Canvas/GradientFillStyle.class.st
  src/Graphics-Display Objects/Cursor.class.st
  src/Graphics-Display Objects/DisplayScreen.class.st
  src/Graphics-Display Objects/Form.class.st
  src/Graphics-Files/GIFReadWriter.class.st
  src/Graphics-Files/JPEGHuffmanTable.class.st
  src/Graphics-Files/JPEGReadWriter.class.st
  src/Keymapping-Pragmas/KMPragmaKeymapBuilder.class.st
  src/Morphic-Base/ImageMorph.class.st
  src/Morphic-Base/MenuItemMorph.class.st
  src/Morphic-Base/MenuMorph.class.st
  src/Morphic-Core/Clipboard.class.st
  src/Morphic-Core/DefaultExternalDropHandler.class.st
  src/Morphic-Core/ExternalDropHandler.class.st
  src/Morphic-Core/UserInputEvent.class.st
  src/Morphic-Widgets-Menubar/MenubarMorph.class.st
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
  src/System-Installers/MczInstaller.class.st
  src/System-Localization/Locale.class.st
  src/System-Object Events/EventManager.class.st
  src/Text-Edition/EditorFindReplaceDialogWindow.class.st
Labels: tests passed please review!

#12144 Move SearchFacade to MonticelloGUI
  src/MonticelloGUI/MCSearchFacade.class.st
  src/MonticelloGUI/MCWorkingCopyBrowser.class.st
Labels: tests passed please review!

#12192 12191-RBAddMethodChange-moves-all-uncategorized-to-accessing
  src/Refactoring-Changes/RBAddMethodChange.class.st
  src/Refactoring-Tests-Changes/RBRefactoringChangeTest.class.st
Labels: tests passed please review!

#12194 Cleanup: Condense Beacon- packages
  src/Beacon-Core-Tests/MemoryLoggerTest.class.st
  src/Beacon-Core-Tests/SignalLoggerTest.class.st
  src/Beacon-Core-Tests/SignalTest.class.st
  src/Beacon-Core-Tests/WrapperSignalTest.class.st
  src/Beacon-Core/Announcement.extension.st
  src/Beacon-Core/Beacon.class.st
  src/Beacon-Core/CircularMemoryLogger.class.st
  src/Beacon-Core/MemoryLogger.class.st
  src/Beacon-Core/SignalLogger.class.st
  src/Beacon-Core/StringSignal.class.st
  src/Beacon-Core/WrapperSignal.class.st
Labels: tests passed please review!

#12103 11634-Unimplemented-message-send-in-FT2FaceemboldenOutline
  src/FreeType/FT2Face.class.st
Labels: tests passed please review!

#12117 Introduce release test to check that "selectors send but not implemented" cases do not grow
  src/ReleaseTests/ReleaseTest.class.st
Labels: tests passed please review!

#12209 RBMakeClassAbstractTransformation-no-whitespace
  src/Refactoring-Core/RBMakeClassAbstractTransformation.class.st
Labels: tests passed please review!

#12216 Cleanup: Condense ClassParser- packages
  src/ClassParser-Tests/ASTClassBuilderTest.class.st
  src/ClassParser-Tests/CDBehaviorParserTest.class.st
  src/ClassParser-Tests/CDClassDefinitionParserTest.class.st
  src/ClassParser-Tests/CDClassParserSelectionTest.class.st
  src/ClassParser-Tests/CDClassWithPoolDictionaryParserTest.class.st
  src/ClassParser-Tests/CDClassWithTraitAliasParserTest.class.st
  src/ClassParser-Tests/CDDoubleByteClassParserTest.class.st
  src/ClassParser-Tests/CDDoubleWordClassParserTest.class.st
  src/ClassParser-Tests/CDEphemeronClassParserTest.class.st
  src/ClassParser-Tests/CDExistingClassDefinitionTest.class.st
  src/ClassParser-Tests/CDExistingClassSideDefinitionTest.class.st
  src/ClassParser-Tests/CDFluidClassParserTest.class.st
  src/ClassParser-Tests/CDImmediateClassParserTest.class.st
  src/ClassParser-Tests/CDMetaclassParserTest.class.st
  src/ClassParser-Tests/CDMetaclassWithTraitParserTest.class.st
  src/ClassParser-Tests/CDNormalClassCategoryParserTest.class.st
  src/ClassParser-Tests/CDNormalClassParserTest.class.st
  src/ClassParser-Tests/CDNormalMetaclassParserTest.class.st
  src/ClassParser-Tests/CDPointClassParserTest.class.st
  src/ClassParser-Tests/CDTraitCompositionClassParserTest.class.st
  src/ClassParser-Tests/CDTraitParserTest.class.st
  src/ClassParser-Tests/CDVariableByteClassParserTest.class.st
  src/ClassParser-Tests/CDVariableClassParserTest.class.st
  src/ClassParser-Tests/CDVariableWordClassParserTest.class.st
  src/ClassParser-Tests/CDWeakClassParserTest.class.st
  src/ClassParser/CDAbstractClassDefinitionParser.class.st
  src/ClassParser/CDAbstractTraitCompositionNode.class.st
  src/ClassParser/CDBehaviorDefinitionNode.class.st
  src/ClassParser/CDClassDefinitionNode.class.st
  src/ClassParser/CDClassDefinitionParser.class.st
  src/ClassParser/CDClassNameNode.class.st
  src/ClassParser/CDClassTagNode.class.st
  src/ClassParser/CDClassTraitNode.class.st
  src/ClassParser/CDFluidClassDefinitionParser.class.st
  src/ClassParser/CDMetaclassDefinitionNode.class.st
  src/ClassParser/CDNode.class.st
  src/ClassParser/CDPackageNode.class.st
  src/ClassParser/CDSharedPoolNode.class.st
  src/ClassParser/CDSharedVariableNode.class.st
  src/ClassParser/CDSlotNode.class.st
  src/ClassParser/CDTraitAliasNode.class.st
  src/ClassParser/CDTraitCompositionBuilder.class.st
  src/ClassParser/CDTraitCompositionNode.class.st
  src/ClassParser/CDTraitCompositionSequenceNode.class.st
  src/ClassParser/CDTraitDefinitionNode.class.st
  src/ClassParser/CDTraitExclusionNode.class.st
  src/ClassParser/CDTraitNode.class.st
  src/ClassParser/CDTraitSlotRemoveNode.class.st
  src/ClassParser/CDTraitSlotRenameNode.class.st
  src/ClassParser/CDUnrecognizedClassPart.class.st
  src/ClassParser/CDVariableNode.class.st
  src/ClassParser/ClassDescription.extension.st
  src/ClassParser/Collection.extension.st
  src/ClassParser/RBSlotInitializationNode.class.st
  src/ClassParser/ShiftClassBuilder.extension.st
Labels: tests passed please review!

#12214 Cleanup: Condense ClassAnnotation- packages
  src/ClassAnnotation-Tests/ActiveClassAnnotationsTest.class.st
  src/ClassAnnotation-Tests/AnnotationUserExample.class.st
  src/ClassAnnotation-Tests/ClassAnnotationTest.class.st
  src/ClassAnnotation-Tests/ClassWithAnnotationDefinedForUserSuperclass.class.st
  src/ClassAnnotation-Tests/ClassWithAnnotationsDefinedForUserClass.class.st
  src/ClassAnnotation-Tests/ClassWithBadAnnotatingMethod.class.st
  src/ClassAnnotation-Tests/ClassWithBrokenAnnotatingMethod.class.st
  src/ClassAnnotation-Tests/ClassWithForbiddenAnnotationExample.class.st
  src/ClassAnnotation-Tests/ClassWithPrioritizedAnnotations.class.st
  src/ClassAnnotation-Tests/ClassWithSingleAnnotation.class.st
  src/ClassAnnotation-Tests/ClassWithThreeAnnotations.class.st
  src/ClassAnnotation-Tests/CompositeAnnotationContextTest.class.st
  src/ClassAnnotation-Tests/QueryAnnotationsFromClassTest.class.st
  src/ClassAnnotation-Tests/RegisteredClassAnnotationsTest.class.st
  src/ClassAnnotation-Tests/SubclassWithOverridenAnnotation.class.st
  src/ClassAnnotation-Tests/VisibleClassAnnotationsTest.class.st
  src/ClassAnnotation/BrokenClassAnnotation.class.st
  src/ClassAnnotation/Class.extension.st
  src/ClassAnnotation/ClassAnnotation.class.st
  src/ClassAnnotation/ClassAnnotationRegistry.class.st
  src/ClassAnnotation/CompositeAnnotationContext.class.st
  src/ClassAnnotation/ForbiddenClassAnnotation.class.st
  src/ClassAnnotation/SimpleAnnotationContext.class.st
Labels: tests passed please review!

#12202 ReCompactSourceCodeCritic should change origin method - not methodClass
  src/Renraku/ReCompactSourceCodeCritic.class.st
Labels: tests passed please review!

#12212 Cleanup: Condense Clap- packages
  src/Clap-Commands-Pharo/ClapCodeEvaluator.class.st
  src/Clap-Commands-Pharo/ClapImage.class.st
  src/Clap-Commands-Pharo/ClapMetacello.class.st
  src/Clap-Commands-Pharo/ClapPharoApplication.class.st
  src/Clap-Commands-Pharo/ClapPharoVersion.class.st
  src/Clap-Commands-Pharo/ClapTestRunner.class.st
  src/Clap-Core/ClapCommand.class.st
  src/Clap-Core/ClapContext.class.st
  src/Clap-Core/ClapDocumentationFormatter.class.st
  src/Clap-Core/ClapDocumenter.class.st
  src/Clap-Core/ClapExpression.class.st
  src/Clap-Core/ClapFlag.class.st
  src/Clap-Core/ClapMismatch.class.st
  src/Clap-Core/ClapValidationReport.class.st
  src/Clap-Core/ClapWordMatch.class.st
  src/Clap-Examples/ClapCommandLineExamples.class.st
  src/Clap-Tests/ClapCodeEvaluatorTest.class.st
  src/Clap-Tests/ClapCommandTest.class.st
  src/Clap-Tests/ClapContextTest.class.st
  src/Clap-Tests/ClapDocumentationTest.class.st
  src/Clap-Tests/ClapFlagTest.class.st
  src/Clap-Tests/ClapHelloTest.class.st
  src/Clap-Tests/ClapMatchesTest.class.st
  src/Clap-Tests/ClapMeaningsTest.class.st
  src/Clap-Tests/ClapParameterTest.class.st
  src/Clap-Tests/ClapParameterizedTest.class.st
  src/Clap-Tests/ClapPharoVersionTest.class.st
  src/Clap-Tests/ClapPositionalTest.class.st
Labels: tests passed please review!

#12113 Slots: For experiments, add Setting for unrestricted definitions
  src/ClassParser-Tests/CDFluidClassParserTest.class.st
  src/ClassParser/CDFluidClassDefinitionParser.class.st
Labels: tests passed please review!

#12224 Cleanup: Condense AI-Algorithms-Graph packages
  src/BaselineOfDependencyAnalyzer/BaselineOfDependencyAnalyzer.class.st
Labels: tests passed please review!

#12096 RubTextEditor/TextEditor: Make ctrl+backspace delete the previous word
  src/Rubric/RubTextEditor.class.st
  src/Text-Edition/TextEditor.class.st
  src/Tool-Base/PharoShortcuts.class.st
Labels: tests passed please review!

#12225 remove ByteLayout from FFIBackend and children
  src/FFI-Kernel/FFIBackend.class.st
  src/FFI-Kernel/NullFFIBackend.class.st
  src/ThreadedFFI/TFFIBackend.class.st
Labels: tests passed please review!

#12260 Fix: #12259 add also two nice examples
  src/Morphic-Base/LayoutFrame.class.st
Labels: more-information-needed

#12151 Cleaning RB issues
  src/FileSystem-Core/AbstractFileReference.class.st
  src/NautilusRefactoring/RBReplacePreview.class.st
  src/Refactoring-Core/RBCopyPackageRefactoring.class.st
  src/Refactoring-Core/RBNamespace.class.st
  src/Refactoring-Core/RBPackageRefactoring.class.st
  src/Refactoring2-Transformations-Tests/RBCopyPackageParametrizedTest.class.st
  src/SystemCommands-PackageCommands/SycCopyPackageCommand.class.st
  src/SystemCommands-RefactoringSupport/SycCopyClassUsingPatternPresenter.class.st
Labels: tests passed please review!

#12305 Fix hasSelector:specialSelectorIndex: on FFI methods that are compiled
  src/UnifiedFFI-Tests/FFICompilerPluginTest.class.st
  src/UnifiedFFI/CompiledMethod.extension.st
Labels: tests passed please review!

#12311 Cleanup: Condense DrTest packages
  src/DrTests-CommentsToTests-Tests/CommentsToTestsTest.class.st
  src/DrTests-CommentsToTests/DTCommentTestConfiguration.class.st
  src/DrTests-CommentsToTests/DTCommentToTestPlugin.class.st
  src/DrTests-CommentsToTests/DTCommentToTestResult.class.st
  src/DrTests-RottenGreenTestsFinder/DTRFTPlugin.class.st
  src/DrTests-TestCoverage-Tests-Mocks/DTCoverageMockTest.class.st
  src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
  src/DrTests-TestCoverage/DTTestCoverageConfiguration.class.st
  src/DrTests-TestCoverage/DTTestCoveragePlugin.class.st
  src/DrTests-TestCoverage/DTTestCoverageResult.class.st
  src/DrTests-Tests/DTFilterableListPresenterTest.class.st
  src/DrTests-Tests/DTMockPlugin.class.st
  src/DrTests-Tests/DTMockPluginTest.class.st
  src/DrTests-Tests/DrTestsTestRunnerUITest.class.st
  src/DrTests-Tests/DrTestsUITest.class.st
  src/DrTests-TestsProfiling/DTTestsProfilingResult.class.st
  src/DrTests-TestsRunner/DTDebugTestCommand.class.st
  src/DrTests-TestsRunner/DTTestsRunnerPlugin.class.st
  src/DrTests-TestsRunner/DTTestsRunnerResult.class.st
  src/DrTests-TestsRunner/TestCase.extension.st
  src/DrTests/AbstractDrTestsPresenter.class.st
  src/DrTests/DTBrowseSelectedItemCommand.class.st
  src/DrTests/DTCommand.class.st
  src/DrTests/DTDefaultPluginPresenter.class.st
  src/DrTests/DTFilterableListPresenter.class.st
  src/DrTests/DTLeafResultCommand.class.st
  src/DrTests/DTLeavesCollector.class.st
  src/DrTests/DTMiddleListCommand.class.st
  src/DrTests/DTPackagesCommand.class.st
  src/DrTests/DTPluginConfiguration.class.st
  src/DrTests/DTPluginResult.class.st
  src/DrTests/DTResultCommand.class.st
  src/DrTests/DTResultTreeView.class.st
  src/DrTests/DTStyleContributor.class.st
  src/DrTests/DTTreeLeafNode.class.st
  src/DrTests/DTTreeNode.class.st
  src/DrTests/DrTests.class.st
  src/DrTests/DrTestsPlugin.class.st
  src/DrTests/MiniDrTests.class.st
Labels: tests passed please review!

#12367 Cleanup: Condense Images packages
  src/Images-Animated/AnimatedImageFrame.class.st
  src/Images-Animated/AnimatedImageMorph.class.st
Labels: tests passed please review!

#12359 Cleanup: Condense Growl packages
  src/Growl/GrowlMorph.class.st
Labels: tests passed please review!

#12350 Cleanup: Condense FuzzyMatcher packages
  src/FuzzyMatcher-Tests/FuzzyMatcherExample.class.st
  src/FuzzyMatcher-Tests/FuzzyMatcherTest.class.st
  src/FuzzyMatcher/FuzzyMatcher.class.st
Labels: tests passed please review!

#12342 Cleanup: Condense Fonts packages
  src/Fonts-Abstract/AbstractFont.class.st
  src/Fonts-Abstract/StubFixedFont.class.st
  src/Fonts-Infrastructure-Tests/AbstractFontFamilyMemberTest.class.st
  src/Fonts-Infrastructure-Tests/AbstractFontFamilyTest.class.st
  src/Fonts-Infrastructure-Tests/AbstractFontProviderTest.class.st
  src/Fonts-Infrastructure-Tests/LogicalFontManager.extension.st
  src/Fonts-Infrastructure/AbstractFontFamily.class.st
  src/Fonts-Infrastructure/AbstractFontFamilyMember.class.st
  src/Fonts-Infrastructure/LogicalFont.class.st
  src/Fonts-Infrastructure/LogicalFontManager.class.st
  src/Fonts-Infrastructure/TextStyleAsFontFamily.class.st
  src/Fonts-Infrastructure/TextStyleAsFontFamilyMember.class.st
Labels: tests passed please review!

#12365 Cleanup: Condense Hiedra packages
  src/Hiedra-Examples/HiExampleCommit.class.st
  src/Hiedra-Examples/HiFastTableExample.class.st
  src/Hiedra-Examples/HiSpecExample.class.st
  src/Hiedra-Tests/HiExamplesTest.class.st
  src/Hiedra-Tests/HiRulerBuilderTest.class.st
  src/Hiedra-Tests/HiRulerTest.class.st
  src/Hiedra/HiAbstractRenderer.class.st
  src/Hiedra/HiBranchMapping.class.st
  src/Hiedra/HiColumnController.class.st
  src/Hiedra/HiLink.class.st
  src/Hiedra/HiNode.class.st
  src/Hiedra/HiRuler.class.st
  src/Hiedra/HiRulerBuilder.class.st
  src/Hiedra/HiSimpleRenderer.class.st
  src/Hiedra/HiWheelColorStrategy.class.st
Labels: tests passed please review!

#12177 extract return from ifTrue:ifFalse: expression
  src/Kernel-Traits/TComparable.trait.st
  src/Kernel/Magnitude.class.st
Labels: Need more work

#12338 Cleanup: Condense Flashback packages
  src/Flashback-Decompiler-Tests/FBDDecompilerTest.class.st
  src/Flashback-Decompiler-Tests/FBDExamples.class.st
  src/Flashback-Decompiler/FBDASTBuilder.class.st
  src/Flashback-Decompiler/FBDDecompiler.class.st
  src/Flashback-Decompiler/FBDLoopScanner.class.st
  src/Flashback-Decompiler/FBDOptimizedMessagesRewriter.class.st
Labels: tests passed please review!

#12411 12410-Minimal-Image-does-not-open-ChangesFile-correctly
  src/System-Sources/SourceFileArray.class.st
Labels: tests passed please review!

#12423 Fix for "Browse this version in Calypso" Error after clicking an unloaded package
  src/Tool-DependencyAnalyser-Tests/DAMessageSendAnalyzerTest.class.st
  src/Tool-DependencyAnalyser/DAMessageSendAnalyzer.class.st
Labels: tests passed please review!

#12388 Move #asNumber from AST-Core to Kernel (where it is also already tested)
  src/AST-Core/String.extension.st
  src/Collections-Strings/String.class.st
Labels: tests passed please review!

#12272 Cleanup: Condense Color packages
  src/Colors/Color.class.st
  src/Colors/ColorMap.class.st
Labels: tests passed please review!

#12336 Cleanup: Condense Files packages
  src/Files-Prompt/MorphicUIManager.extension.st
  src/Files-Tests/BinaryFileStreamTest.class.st
  src/Files-Tests/FileRegistryTest.class.st
  src/Files-Tests/FileTest.class.st
  src/Files-Tests/StdioStreamTest.class.st
  src/Files-Tests/StdioStreamTestResource.class.st
  src/Files/AbstractBinaryFileStream.class.st
  src/Files/AsyncFile.class.st
  src/Files/File.class.st
  src/Files/FileAlreadyExistsException.class.st
  src/Files/FileException.class.st
  src/Files/Stdio.class.st
  src/Files/StdioStream.class.st
  src/Files/String.extension.st
Labels: tests passed please review!

#12405 FIX CI issues - FFIExternalString>>#basicHandle:at: calls deprecated message
  src/UnifiedFFI/FFIExternalString.class.st
Labels: tests passed please review!

#12346 Cleanup: Condense FreeType packages
  src/FreeType-Graphics/BitBlt.extension.st
  src/FreeType-Graphics/FreeTypeFont.extension.st
  src/FreeType-Graphics/FreeTypeGlyphRenderer.class.st
  src/FreeType-Graphics/FreeTypeSettings.extension.st
  src/FreeType-Graphics/FreeTypeSubPixelAntiAliasedGlyphRenderer.class.st
  src/FreeType-Graphics/FreeTypeSystemSettings.extension.st
  src/FreeType-Graphics/GlyphForm.class.st
  src/FreeType-Morphic/TextStyle.extension.st
  src/FreeType-Morphic/TransformMorph.extension.st
  src/FreeType-Tests/FreeTypeCacheTest.class.st
  src/FreeType-Tests/FreeTypeFontFamilyMemberTest.class.st
  src/FreeType/AbstractFont.extension.st
  src/FreeType/AbstractFreeTypeFileInfo.class.st
  src/FreeType/FT2Constants.class.st
  src/FreeType/FT2Error.class.st
  src/FreeType/FT2FFILibrary.class.st
  src/FreeType/FT2Face.class.st
  src/FreeType/FT2GlyphSlot.class.st
  src/FreeType/FT2Handle.class.st
  src/FreeType/FT2Library.class.st
  src/FreeType/FT2Outline.class.st
  src/FreeType/FT2Types.class.st
  src/FreeType/FT2Version.class.st
  src/FreeType/FTBBox.class.st
  src/FreeType/FTBitmap.class.st
  src/FreeType/FTBitmapSize.class.st
  src/FreeType/FTCharMapRec.class.st
  src/FreeType/FTFaceRec.class.st
  src/FreeType/FTGeneric.class.st
  src/FreeType/FTGlyphMetrics.class.st
  src/FreeType/FTGlyphSlotRec.class.st
  src/FreeType/FTListRec.class.st
  src/FreeType/FTMatrix.class.st
  src/FreeType/FTOutline.class.st
  src/FreeType/FTSizeMetrics.class.st
  src/FreeType/FTSizeRec.class.st
  src/FreeType/FTVector.class.st
  src/FreeType/FreeTypeCache.class.st
  src/FreeType/FreeTypeCacheConstants.class.st
  src/FreeType/FreeTypeCacheEntry.class.st
  src/FreeType/FreeTypeCacheLinkedList.class.st
  src/FreeType/FreeTypeExternalMemory.class.st
  src/FreeType/FreeTypeFace.class.st
  src/FreeType/FreeTypeFileInfo.class.st
  src/FreeType/FreeTypeFont.class.st
  src/FreeType/FreeTypeFontFamily.class.st
  src/FreeType/FreeTypeFontFamilyMember.class.st
  src/FreeType/FreeTypeFontProvider.class.st
  src/FreeType/FreeTypeNameParser.class.st
  src/FreeType/FreeTypeSettings.class.st
  src/FreeType/FreeTypeSystemSettings.class.st
Labels: tests passed please review!

#12375 Fix for multiple Epicea issues
  src/Epicea/EpCategoryRegistration.class.st
  src/Epicea/EpMonitor.class.st
  src/Epicea/EpTCodeChangeVisitor.trait.st
  src/EpiceaBrowsers-Tests/EpLostChangesDetectorTest.class.st
  src/EpiceaBrowsers/EpApplyPreviewer.class.st
  src/EpiceaBrowsers/EpApplyVisitor.class.st
  src/EpiceaBrowsers/EpHasImpactVisitor.class.st
  src/EpiceaBrowsers/EpIconVisitor.class.st
  src/EpiceaBrowsers/EpInverseVisitor.class.st
  src/EpiceaBrowsers/EpMorphVisitor.class.st
  src/EpiceaBrowsers/EpNewStateVisitor.class.st
Labels: tests passed please review!

#12197 checkIfMustRefresh in OmBlockFileStore>>blockForLocalNameAsInteger:
  src/Ombu-Tests/OmBlockFileStoreTest.class.st
  src/Ombu/OmBlockFileStore.class.st
  src/Ombu/OmFileStore.class.st
Labels: tests passed please review!

#12361 Cleanup: Condense Hermes packages
  src/Hermes-Extensions/HEDuplicationModeStrategy.class.st
  src/Hermes-Extensions/HEExtendedInstaller.class.st
  src/Hermes/HEAdditionalMethodState.class.st
  src/Hermes/HEArray.class.st
  src/Hermes/HEAssociation.class.st
  src/Hermes/HEBinaryReader.class.st
  src/Hermes/HEByteArray.class.st
  src/Hermes/HEByteString.class.st
  src/Hermes/HECharacter.class.st
  src/Hermes/HEClass.class.st
  src/Hermes/HEClassTrait.class.st
  src/Hermes/HEClassVariable.class.st
  src/Hermes/HECompiledBlock.class.st
  src/Hermes/HEConstantBlock.class.st
  src/Hermes/HEExportedLiteral.class.st
  src/Hermes/HEExportedMetaclass.class.st
  src/Hermes/HEFloat.class.st
  src/Hermes/HEFraction.class.st
  src/Hermes/HEGlobalVariable.class.st
  src/Hermes/HEInstaller.class.st
  src/Hermes/HEMethod.class.st
  src/Hermes/HEMethodLiteral.class.st
  src/Hermes/HEPackage.class.st
  src/Hermes/HEPragma.class.st
  src/Hermes/HEScaledDecimal.class.st
  src/Hermes/HESendMessage.class.st
  src/Hermes/HESymbol.class.st
  src/Hermes/HETrait.class.st
  src/Hermes/HETraitLiteral.class.st
  src/Hermes/HEWideString.class.st
  src/Hermes/HermesCommandLineHandler.class.st
Labels: tests passed please review!

#12381 Cleanup: Condense Keymapping packages
  src/Keymapping-Core/KMBuffer.class.st
  src/Keymapping-Core/KMCategory.class.st
  src/Keymapping-Core/KMCategoryBinding.class.st
  src/Keymapping-Core/KMDispatchChain.class.st
  src/Keymapping-Core/KMDispatcher.class.st
  src/Keymapping-Core/KMGlobalDispatcher.class.st
  src/Keymapping-Core/KMKeymap.class.st
  src/Keymapping-Core/KMLog.class.st
  src/Keymapping-Core/KMOSXShortcutPrinter.class.st
  src/Keymapping-Core/KMRepository.class.st
  src/Keymapping-Core/KMShortcutPrinter.class.st
  src/Keymapping-Core/KMStorage.class.st
  src/Keymapping-Core/KMTarget.class.st
  src/Keymapping-Core/MacOSPlatform.extension.st
  src/Keymapping-KeyCombinations/ByteString.extension.st
  src/Keymapping-KeyCombinations/Character.extension.st
  src/Keymapping-KeyCombinations/Collection.extension.st
  src/Keymapping-KeyCombinations/KMAltModifier.class.st
  src/Keymapping-KeyCombinations/KMComposedModifier.class.st
  src/Keymapping-KeyCombinations/KMCtrlModifier.class.st
  src/Keymapping-KeyCombinations/KMKeyCombination.class.st
  src/Keymapping-KeyCombinations/KMKeyCombinationChoice.class.st
  src/Keymapping-KeyCombinations/KMKeyCombinationSequence.class.st
  src/Keymapping-KeyCombinations/KMKeymap.extension.st
  src/Keymapping-KeyCombinations/KMMetaModifier.class.st
  src/Keymapping-KeyCombinations/KMModifiedKeyCombination.class.st
  src/Keymapping-KeyCombinations/KMModifier.class.st
  src/Keymapping-KeyCombinations/KMNamedCharKeyCombination.class.st
  src/Keymapping-KeyCombinations/KMNoModifier.class.st
  src/Keymapping-KeyCombinations/KMPlatformSpecificKeyCombination.class.st
  src/Keymapping-KeyCombinations/KMShiftModifier.class.st
  src/Keymapping-KeyCombinations/KMSingleKeyCombination.class.st
  src/Keymapping-KeyCombinations/KMUntypeableSingleKeyCombination.class.st
  src/Keymapping-Pragmas/KMBuilder.class.st
  src/Keymapping-Pragmas/KMKeymapBuilder.class.st
  src/Keymapping-Pragmas/KMPragmaKeymapBuilder.class.st
  src/Keymapping-Pragmas/PragmaMenuAndShortcutRegistration.extension.st
  src/Keymapping-Settings/KMCatcherMorph.class.st
  src/Keymapping-Settings/KMShortcutDeclaration.class.st
  src/Keymapping-Settings/KMShortcutSetting.class.st
  src/Keymapping-Settings/SettingNodeBuilder.extension.st
  src/Keymapping-Settings/SettingTreeBuilder.extension.st
  src/Keymapping-Tests/AbstractKeymappingTest.class.st
  src/Keymapping-Tests/CharacterKeyCombinationTest.class.st
  src/Keymapping-Tests/KMCategoryTest.class.st
  src/Keymapping-Tests/KMCombinationTest.class.st
  src/Keymapping-Tests/KMDispatcherTest.class.st
  src/Keymapping-Tests/KMKeymapBuilderTest.class.st
  src/Keymapping-Tests/KMKeymapTest.class.st
  src/Keymapping-Tests/KMShortcutPrinterTest.class.st
  src/Keymapping-Tests/KMShortcutTest.class.st
Labels: tests passed please review!

#12249 Cleanup: Condense Collections-Support packages
  src/Collections-Support-Tests/AssociationTest.class.st
  src/Collections-Support-Tests/CharacterSetTest.class.st
  src/Collections-Support-Tests/CollectionTest.class.st
  src/Collections-Support-Tests/WideCharacterSetTest.class.st
  src/Collections-Support/Association.class.st
  src/Collections-Support/CharacterSet.class.st
  src/Collections-Support/CharacterSetComplement.class.st
  src/Collections-Support/CollectionElement.class.st
  src/Collections-Support/Link.class.st
  src/Collections-Support/LookupKey.class.st
  src/Collections-Support/ValueLink.class.st
  src/Collections-Support/WeakKeyAssociation.class.st
  src/Collections-Support/WeakValueAssociation.class.st
  src/Collections-Support/WideCharacterSet.class.st
Labels: tests passed please review!

#12386 Re-introduce list morph shortcuts using keydown
  src/Morphic-Widgets-List/SimpleHierarchicalListMorph.class.st
  src/Tool-Diff/PSMCPatchMorph.class.st
Labels: tests passed please review!

#12258 convert numpad keys with NumLock turned off
  src/OSWindow-SDL2/OSSDL2BackendWindow.class.st
Labels: tests passed please review!

#12205 12128-Poor-performance-with-large-WriteStreams
  src/Collections-Streams/WriteStream.class.st
Labels: Discussion

#12085 Clean some duplication logic by extracting Smalltalk tools into a sep…
  src/Keymapping-Core/KMCategory.class.st
  src/Reflectivity-Tools/WatchesWindowPresenter.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Rubric/RubTextEditor.class.st
  src/Tool-Base/RGBehaviorDefinition.extension.st
  src/Tool-Base/RGDefinition.extension.st
  src/Tool-Base/RGElementDefinition.extension.st
  src/Tool-Base/RGMethodDefinition.extension.st
  src/Tool-Base/SystemNavigation.extension.st
  src/Tool-Base/ToolShortcutsCategory.class.st
  src/Tool-ProcessBrowser/ProcessBrowser.class.st
Labels: tests passed please review!

#12055 11968-Clean-Blocks-Jobowner-assumes-valid-outerContext
  src/Jobs/BlockClosure.extension.st
  src/Jobs/Job.class.st
Labels: tests passed please review!

#11918 Complete symbols
  src/HeuristicCompletion-Model/CoASTHeuristicsResultSetBuilder.class.st
  src/HeuristicCompletion-Model/CoGlobalFetcher.class.st
  src/HeuristicCompletion-Model/CoGlobalSelectorFetcher.class.st
  src/HeuristicCompletion-Model/CoGlobalSymbolFetcher.class.st
  src/HeuristicCompletion-Model/CoGlobalVariableFetcher.class.st
  src/HeuristicCompletion-Model/CoLiteralSymbolHeuristic.class.st
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#11554 Review if #scanToken: in RBScanner is still needed
  src/AST-Core-Tests/RBScannerTest.class.st
  src/AST-Core/RBScanner.class.st
  src/BaselineOfPharo/BaselineOfPharo.class.st
  src/Deprecated11/MCScanner.extension.st
  src/Deprecated11/RBScanner.extension.st
  src/Deprecated11/package.st
  src/Monticello/MCScanner.class.st
Labels: tests passed please review!

#11254 Extracting the logic of screenshot and selection
  src/Graphics-Canvas/BitmapFillStyle.class.st
  src/Graphics-Display Objects/Form.class.st
  src/Graphics-Files/GIFReadWriter.class.st
  src/Morphic-Base/BitmapFillStyle.extension.st
  src/Morphic-Base/ImageMorph.class.st
  src/Morphic-Base/PasteUpMorph.extension.st
  src/Morphic-Base/Rectangle.extension.st
  src/Morphic-Core/Screenshot.class.st
  src/Morphic-Core/WorldMorph.class.st
  src/Morphic-Core/WorldState.class.st
  src/OSWindow-Core/OSWorldRenderer.class.st
Labels: Need more work

#11053 [improvement] better default hierarchy display
  src/Calypso-SystemQueries/ClySubclassHierarchy.class.st
  src/System-Settings-Tests/SystemSettingsPersistenceTest.class.st
Labels: tests passed please review!

#12438 Improving the ChangesBrowser presenter
  src/NautilusRefactoring/ChangesBrowser.class.st
Labels: tests passed please review!

#12439 fix issue #12434, pair programming with Valentin
  src/Morphic-Widgets-FastTable/FTSearchFunction.class.st
  src/Morphic-Widgets-FastTable/FTTableMorph.class.st
Labels: tests passed please review!

#12446 Fix #12287 adding group model to parent window
  src/Calypso-Browser/ClyBrowserMorph.class.st
Labels: tests passed please review!
