Repository pharo-project/pharo, pull requests merged in 2023-07, with the labels that each got.

#14159 fix-deprecated-send-testCreateGroupsForEveryMethodTag
  src/Calypso-SystemQueries-Tests/ClyAllClassGroupsQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyClassScopeTest.class.st
  src/Calypso-SystemQueries-Tests/ClyPackageScopeTest.class.st
  src/Calypso-SystemQueries-Tests/ClyTaggedMethodGroupProviderTest.class.st
Labels: tests passed please review!

#14182 changebrowser -> stChangeBrowserPresenter
  src/Calypso-SystemPlugins-Critic-Browser/ClyFixCritiqueCommand.class.st
  src/Epicea-Tests/EpTriggeringIntegrationTest.class.st
  src/Epicea/StChangesBrowserPresenter.extension.st
  src/Hiedra-Examples/HiSpecExamplePresenter.class.st
  src/Hiedra-Tests/HiSpecExampleTest.class.st
  src/NautilusRefactoring-Tests/ChangesBrowserTest.class.st
  src/NautilusRefactoring/ChangesBrowser.class.st
  src/NautilusRefactoring/RewriteRuleChangesBrowser.class.st
  src/NautilusRefactoring/StChangesBrowserPresenter.class.st
  src/NautilusRefactoring/StRewriteRuleChangesBrowserPresenter.class.st
  src/Reflectivity-Examples/CoverageDemoPresenter.class.st
  src/Renraku/ReAbstractCritique.class.st
Labels: more-information-needed

#14189 Remove references to #allManagers in RPackage
  src/Monticello-Tests/RPackageMCSynchronisationTest.class.st
  src/Monticello-Tests/RPackageMonticelloSynchronisationTest.class.st
  src/Monticello/MCWorkingCopy.class.st
  src/Monticello/RPackageOrganizer.extension.st
  src/RPackage-Tests/RPackageIncrementalTest.class.st
  src/RPackage-Tests/RPackageTestCase.class.st
Labels: tests passed please review!

#14180 Some users of inform: that could simply use the inform: from Object.
  src/Calypso-SystemPlugins-Monticello-Browser/ClyIcebergShowMethodVersionCommand.class.st
  src/Calypso-SystemTools-FullBrowser/ClyRemoveClassGroupCommand.class.st
  src/Calypso-SystemTools-FullBrowser/ClyRemoveMethodGroupCommand.class.st
  src/OSWindow-SDL2/UserInterruptHandler.class.st
  src/SUnit-UI/TestRunner.class.st
  src/System-SessionManager/StartupUIManager.class.st
  src/Text-Edition/TextPrintIt.extension.st
  src/Tool-Base/ToolShortcutsCategory.class.st
  src/Tool-Workspace/Workspace.class.st
Labels: tests passed please review!, easyReview

#14194 14164--ChunkImportTestCasetestImportAMethodWithSpacesInItsCategory--calls-category
  src/CodeImport-Tests/ChunkImportTestCase.class.st
Labels: tests passed please review!

#14187 Keep pushing for rpackage knowing their organizer
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: tests passed please review!

#14188 Rename ClyTaggedMethodsQuery into ClyMethodsInProtocolQuery
  src/Calypso-SystemQueries-Tests/ClyMethodsInProtocolGroupProviderTest.class.st
  src/Calypso-SystemQueries-Tests/ClyMethodsInProtocolQueryTest.class.st
  src/Calypso-SystemQueries/ClyMethodsInProtocolGroup.class.st
  src/Calypso-SystemQueries/ClyMethodsInProtocolQuery.class.st
  src/Calypso-SystemQueries/ClyTaggedMethodsQuery.class.st
  src/Deprecated12/ClyMethodsInProtocolQuery.extension.st
Labels: tests passed please review!

#14193 SmalltalkImage>>garbageCollect : correct method comment
  src/System-Support/SmalltalkImage.class.st
Labels: tests passed please review!

#14214 14162-UUIDGenerator-uses-of-deprecated-method-in-tests
  src/FileSystem-Tests-Attributes/DiskFileAttributesTest.class.st
  src/FileSystem-Tests-Attributes/DiskFileAttributesTestsResource.class.st
  src/Tool-FileList-Tests/FileDialogWindowTest.class.st
Labels: Reviewed and Ready to Integrate

#14222 Add test on installing a class in a non default environment
  src/Shift-ClassInstaller-Tests/ShClassInstallerTest.class.st
Labels: Reviewed and Ready to Integrate

#14220 Add tests for primitive adoptInstance and the sibling primitiveChangeClassTo
  src/Kernel-Tests/ObjectTest.class.st
Labels: Low-level, Reviewed and Ready to Integrate

#14223 Simplification of the package validation
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: tests passed please review!

#14217 Rename #allManagers into #allWorkingCopies
  src/Deprecated12/MCWorkingCopy.extension.st
  src/Deprecated12/RGContainer.extension.st
  src/Gofer-Core/GoferReference.class.st
  src/Gofer-Core/GoferUnload.class.st
  src/Gofer-Tests/GoferOperationTest.class.st
  src/Metacello-Base/ConfigurationOf.class.st
  src/Metacello-Cypress/MetacelloCypressPackageSpec.class.st
  src/Metacello-MC/MetacelloCachingGoferResolvedReference.class.st
  src/Metacello-MC/MetacelloGoferPackage.class.st
  src/Metacello-TestsMC/MetacelloDictionaryRepositoryTest.class.st
  src/Metacello-TestsMC/MetacelloIssueTestCase.class.st
  src/Metacello-TestsMC/MetacelloScriptingStdTstHarnessTestCase.class.st
  src/Monticello/MCWorkingCopy.class.st
  src/MonticelloGUI/MCConfigurationBrowser.class.st
  src/MonticelloGUI/MCTool.class.st
  src/Ring-Definitions-Containers/RGContainer.class.st
  src/TraitsV2-Tests/TimeMeasuringTest.class.st
Labels: tests passed please review!

#14219 Clean #affectsMethodsTaggedWith:
  src/Calypso-SystemPlugins-InheritanceAnalysis-Queries/ClyOverriddenSuperclassesChanged.class.st
  src/Calypso-SystemPlugins-InheritanceAnalysis-Queries/ClyOverridingMethodsChanged.class.st
  src/Calypso-SystemPlugins-InheritanceAnalysis-Queries/ClyOverridingSubclassesChanged.class.st
  src/Calypso-SystemPlugins-SUnit-Queries/ClyTestCaseRan.class.st
  src/Calypso-SystemQueries/ClyMethodsInProtocolQuery.class.st
  src/Deprecated12/Announcement.extension.st
  src/System-Announcements/Announcement.extension.st
  src/System-Announcements/ClassRemoved.class.st
  src/System-Announcements/ClassRenamed.class.st
  src/System-Announcements/ClassRepackaged.class.st
  src/System-Announcements/MethodAnnouncement.class.st
  src/System-Announcements/MethodModified.class.st
  src/System-Announcements/MethodRecategorized.class.st
  src/System-Announcements/MethodRemoved.class.st
Labels: tests passed please review!

#14208 SmalltalkImage>>#newSpecialObjectsArray remove elements not used by the VM
  src/System-Support/SmalltalkImage.class.st
Labels: Low-level, tests passed please review!

#14134 Composing and reusing add method refactoring/transformation
  src/Refactoring-Core/RBAddMethodRefactoring.class.st
  src/Refactoring-Core/RBAddMethodTransformRefactoring.class.st
  src/Refactoring-Core/RBCreateAccessorsForVariableTransformation.class.st
  src/Refactoring-Core/RBCreateLazyAccessorsForVariableTransformation.class.st
  src/Refactoring-Core/RBMakeClassAbstractTransformation.class.st
  src/Refactoring2-Transformations-Tests/RBAddMethodTransformRefactoringTest.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: Reviewed and Ready to Integrate

#14232 Introduce RPackageOrganizer#hasPackage:
  src/Monticello-Tests/RPackageCategorySynchronisationTest.class.st
  src/Monticello-Tests/RPackageClassesSynchronisationTest.class.st
  src/Monticello-Tests/RPackageExtensionMethodsSynchronisationTest.class.st
  src/Monticello-Tests/RPackageMonticelloSynchronisationTest.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
  src/RPackage-Tests/RPackageRenameTest.class.st
  src/RPackage-Tests/RPackageTest.class.st
Labels: tests passed please review!

#14243 Deprecated CompiledMethod tag API
  src/Calypso-SystemQueries-Tests/ClyAllMethodGroupsQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyClassScopeTest.class.st
  src/Calypso-SystemQueries-Tests/ClyMethodsInProtocolGroupProviderTest.class.st
  src/Deprecated12/ClassDescription.extension.st
  src/Deprecated12/CompiledMethod.extension.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/CompiledMethod.class.st
  src/Ring-Tests-Core/RGClassTest.class.st
  src/TraitsV2/TraitedClass.class.st
Labels: tests passed please review!

#14229 fix calculous of layout when morph is not visible
  src/Morphic-Base/TableLayout.class.st
  src/Morphic-Tests/TableLayoutTest.class.st
Labels: Reviewed and Ready to Integrate

#14236 Fix the preconditions related to packages in refactorings
  src/Refactoring-Core/RBCopyPackageRefactoring.class.st
  src/Refactoring-Core/RBPackageRefactoring.class.st
  src/Refactoring-Core/RBRenamePackageRefactoring.class.st
  src/Refactoring-Tests-Environment/RBBrowserEnvironmentTest.class.st
  src/Refactoring2-Transformations/RBPackageTransformation.class.st
  src/Refactoring2-Transformations/RBRenamePackageTransformation.class.st
Labels: Reviewed and Ready to Integrate

#14240 Refactor: clean `RBCondition` and add popUp flag
  src/Refactoring-Core/RBCondition.class.st
Labels: Reviewed and Ready to Integrate

#14167 Fix haltOn tests after debug them
  src/Debugging-Utils-Tests/HaltTest.class.st
Labels: Reviewed and Ready to Integrate

#14253 DeadCodeCleanup-07-10
  src/EnlumineurFormatter-Tests/EFBenchTest.class.st
  src/Morphic-Widgets-FastTable/FTBasicTreeListDataSource.class.st
  src/Rubric/RubTextEditor.class.st
  src/Text-Edition/TextEditor.class.st
  src/Tool-DependencyAnalyser-UI/DACycleDetectionPresenter.class.st
Labels: Reviewed and Ready to Integrate

#14246 Deprecate #includesPackageNamed:
  src/Calypso-SystemPlugins-Monticello-Browser/ClyCommitPackageCommand.class.st
  src/Calypso-SystemPlugins-Monticello-Browser/ClyIcebergShowMethodVersionCommand.class.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers/EpApplyPreviewer.class.st
  src/EpiceaBrowsers/EpHasImpactVisitor.class.st
  src/JenkinsTools-Core/TestCommandLineHandler.class.st
  src/Monticello-Tests/MCWorkingCopyForExtensionsTest.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/Refactoring-Core/RBNamespace.class.st
  src/Shift-ClassInstaller-Tests/ShClassInstallerTest.class.st
Labels: tests passed please review!

#14254 Introduce RPackageOrganizer>>ensurePackage:
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
Labels: tests passed please review!

#14258 Remove dead code in bootstrap
  src/Pharo30Bootstrap/PBImageBuilder50.class.st
  src/Pharo30Bootstrap/PBMethodCompiler.class.st
Labels: Reviewed and Ready to Integrate

#14210 FileBrowser. View as hex not working
  src/FileSystem-Core/AbstractFileReference.class.st
  src/Tool-FileList/FileList.class.st
Labels: Reviewed and Ready to Integrate

#14249 Update bootstrap scripts
  bootstrap/scripts/emulation/shrink.st
  scripts/export.st
Labels: Reviewed and Ready to Integrate

#14260 Deprecate RPackageOrganizer>>#registerPackageNamed:
  src/Deprecated12/RPackageOrganizer.extension.st
  src/FluidClassBuilder-Tests/FluidClassBuilderAbstractTest.class.st
  src/Hermes/HEInstaller.class.st
  src/Monticello-Tests/MCSnapshotTest.class.st
  src/Monticello-Tests/MCWorkingCopyForExtensionsTest.class.st
  src/Monticello/MCVersionLoader.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
  src/RPackage-Tests/RPackageRenameTest.class.st
  src/RPackage-Tests/RPackageTest.class.st
  src/Refactoring-Changes/RBAddPackageChange.class.st
Labels: tests passed please review!

#14225 Dependency Analyser title management
  src/Tool-DependencyAnalyser-UI/DAAddPackagePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DACycleDetectionTreePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DADependencyTreePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAPackageAnalyzerDiffTreePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAPackageDependenciesPresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAReverseTreePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAWelcomePresenter.class.st
Labels: Reviewed and Ready to Integrate

#14247 Rename some more tags into protocol
  src/Calypso-SystemQueries-Tests/ClyMethodsInProtocolGroupProviderTest.class.st
  src/Calypso-SystemQueries/ClassDescription.extension.st
  src/Calypso-SystemQueries/ClyDefaultSystemEnvironmentPlugin.class.st
  src/Calypso-SystemQueries/ClyMethodsInProtocolGroupProvider.class.st
  src/Calypso-SystemQueries/ClyTaggedMethodGroupProvider.class.st
  src/Calypso-SystemQueries/TraitedMetaclass.extension.st
  src/Calypso-SystemTools-FullBrowser/ClyConvertMethodGroupToProtocolCommand.class.st
  src/Calypso-SystemTools-FullBrowser/ClyConvertMethodGroupToTagCommand.class.st
  src/Ring-Core/RGBehavior.class.st
  src/Ring-Tests-Core/RGClassTest.class.st
  src/System-Announcements/Announcement.extension.st
  src/System-Announcements/ProtocolAnnouncement.class.st
Labels: tests passed please review!

#13886 Fix logging of protocol in Opal
  bootstrap/scripts/03-metacello-bootstrap/01-loadMetacello.st
  src/Monticello/MCWorkingCopy.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/System-Announcements/SystemAnnouncer.class.st
Labels: tests passed please review!

#14268 Bugfix: Fix double protocol request in Calypso
  src/Kernel/CompiledMethod.class.st
  src/ReleaseTests/ProperPackagesTest.class.st
  src/SystemCommands-MethodCommands/SycMoveMethodsToPackageDefiningClassCommand.class.st
  src/Tool-Base/MethodClassifier.class.st
Labels: Bug

#14265 Improve deprecated slot
  src/VariablesLibrary/DeprecatedSlot.class.st
  src/VariablesLibrary/SlotDeprecation.class.st
Labels: tests passed please review!

#14273 Do not prevent all announcements during method classification
  src/Kernel-Tests/ProtocolAnnouncementsTest.class.st
  src/Kernel/ClassDescription.class.st
Labels: Reviewed and Ready to Integrate

#14270 ClassParser: parse non-fluid defintion of CompiledBlock
  src/ClassParser-Tests/CDCompiledBlockClassParserTest.class.st
  src/ClassParser/CDClassDefinitionParser.class.st
Labels: Reviewed and Ready to Integrate

#14259 Treat Integers and Fractions as having scale 0 in ScaledDecimal arithmetic (fixes #14238)
  src/Kernel-Tests/ScaledDecimalTest.class.st
  src/Kernel/ScaledDecimal.class.st
Labels: Reviewed and Ready to Integrate

#14274 [Pharo11] This is a backport: 14034 debugger does not evaluate in the context of the receiver
  src/OpalCompiler-Core/Context.extension.st
  src/OpalCompiler-Core/OCContextualDoItSemanticScope.class.st
  src/OpalCompiler-Core/OCDoItSemanticScope.class.st
  src/OpalCompiler-Core/OCReceiverDoItSemanticScope.class.st
  src/OpalCompiler-Tests/OCDoitTest.class.st
Labels: Reviewed and Ready to Integrate

#14275 [Pharo11] backport Slot related fixes #13950 and #13949
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
  src/Slot-Tests/SlotMigrationTest.class.st
  src/Slot-Tests/WriteOnceSlotTest.class.st
Labels: Reviewed and Ready to Integrate

#14266 Rename more methods and classes to use "Protocol" vocabulary
  src/Calypso-Browser/ClyBrowserContext.class.st
  src/Calypso-SystemQueries/ClyMethodGroup.class.st
  src/Calypso-SystemQueries/ClyMethodsInProtocolGroup.class.st
  src/Calypso-SystemQueries/ClyMethodsInProtocolGroupProvider.class.st
  src/Calypso-SystemQueries/ClyMethodsInProtocolQuery.class.st
  src/Calypso-SystemQueries/ClyUnclassifiedMethodGroup.class.st
  src/Calypso-SystemTools-Core/ClyMethodCodeEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodCreationToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyProtocolAndPackageEditorMorph.class.st
  src/Calypso-SystemTools-Core/ClyRequestMethodPackageForEditorCommand.class.st
  src/Calypso-SystemTools-Core/ClyRequestMethodTagForEditorCommand.class.st
  src/Calypso-SystemTools-Core/ClyRequestProtocolForEditorCommand.class.st
  src/Calypso-SystemTools-Core/ClyResetMethodTagForEditorCommand.class.st
  src/Calypso-SystemTools-Core/ClyResetProtocolForEditorCommand.class.st
  src/Calypso-SystemTools-Core/SycClassifyMethodCommand.extension.st
  src/Calypso-SystemTools-Core/SycMoveMethodsToTheDefiningClassCommand.extension.st
  src/Calypso-SystemTools-FullBrowser/ClyConvertMethodGroupToProtocolCommand.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserContext.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserMorph.class.st
  src/Calypso-SystemTools-FullBrowser/ClyRenameProtocolCommand.class.st
  src/Calypso-SystemTools-FullBrowser/SycAddNewProtocolCommand.extension.st
  src/Commander-Core/CmdToolContext.class.st
  src/Deprecated12/CmdToolContext.extension.st
  src/SystemCommands-ClassCommands/SycAddNewMethodTagCommand.class.st
  src/SystemCommands-ClassCommands/SycAddNewProtocolCommand.class.st
  src/SystemCommands-MethodCommands/SycClassifyMethodCommand.class.st
  src/SystemCommands-MethodCommands/SycMethodCommand.class.st
  src/SystemCommands-MethodCommands/SycMethodRepackagingCommand.class.st
  src/SystemCommands-MethodCommands/SycMoveMethodsToPackageCommand.class.st
  src/SystemCommands-MethodCommands/SycMoveMethodsToPackageDefiningClassCommand.class.st
  src/SystemCommands-MethodCommands/SycMoveMethodsToTheDefiningClassCommand.class.st
  src/SystemCommands-MethodCommands/SycTagMethodCommand.class.st
  src/SystemCommands-RefactoringSupport/TRefactoringCommandSupport.trait.st
Labels: tests passed please review!

#14280 Push usage of #ensurePackage:
  src/Monticello-Tests/RPackageMCSynchronisationTest.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/Refactoring-Changes/RBAddPackageChange.class.st
  src/Refactoring2-Transformations-Tests/RBCopyPackageParametrizedTest.class.st
Labels: tests passed please review!

#14283 Start unification of package removal
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
  src/Deprecated12/RPackageOrganizer.extension.st
  src/Epicea-Tests/EpCodeChangeIntegrationTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers-Tests/EpLogBrowserOperationFactoryTest.class.st
  src/EpiceaBrowsers/EpApplyVisitor.class.st
  src/Gofer-Core/GoferUnload.class.st
  src/Kernel-Tests-Extended/ClassTest.class.st
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
Labels: tests passed please review!

#14285 Deprecate class reorganized
  src/Calypso-SystemQueries/ClassReorganized.extension.st
  src/Deprecated12/SystemAnnouncer.extension.st
  src/Kernel-Tests/ProtocolAnnouncementsTest.class.st
  src/Kernel/ClassDescription.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/Refactoring-Changes/RBClassCategoryChange.class.st
  src/Refactoring-Changes/RBRefactoryChangeManager.class.st
  src/Ring-Core/RGEnvironmentAnnouncer.class.st
  src/System-Announcements/ClassReorganized.class.st
  src/System-Announcements/ProtocolAnnouncement.class.st
  src/System-Announcements/SystemAnnouncer.class.st
  src/System-Changes/ChangeSet.class.st
Labels: tests passed please review!

#14288 Cleaning in RPackage tests
  src/RPackage-Tests/RPackageIncrementalTest.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
  src/RPackage-Tests/RPackageTestCase.class.st
Labels: tests passed please review!

#14264 Remove unclassify hack
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel-Tests/ClassDescriptionTest.class.st
  src/Kernel/ClassDescription.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#14290 Factorize some unregistering code
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageIncrementalTest.class.st
Labels: tests passed please review!

#14227 14226-nil-cannot-be-pinned-in-memory
  src/Kernel/Boolean.class.st
  src/Kernel/UndefinedObject.class.st
Labels: tests passed please review!

#14287 backport Pharo11: Fix doubleClick on tab and on text selection.
  src/Morphic-Base/MouseClickState.class.st
  src/Morphic-Base/Object.extension.st
  src/Morphic-Core/Morph.class.st
  src/Morphic-Tests/MockMorph.class.st
  src/Morphic-Tests/MorphicEventHandlerTest.class.st
  src/Rubric-Tests/RubEditingAreaTest.class.st
Labels: Reviewed and Ready to Integrate

#14295 Improve CompiledMethod>>#isExtension
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel/CompiledMethod.class.st
  src/RPackage-Core/CompiledMethod.extension.st
  src/ReleaseTests/ProperPackagesTest.class.st
  src/SystemCommands-MethodCommands/SycMoveMethodsToTheDefiningClassCommand.class.st
  src/Tool-Base/MethodClassifier.class.st
Labels: tests passed please review!

#14292 Remove brittle method in RPackage
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageIncrementalTest.class.st
Labels: tests passed please review!

#14306 Use better package API in Monticello
  src/Monticello/MCWorkingCopy.class.st
Labels: tests passed please review!

#14311 Update package API of slot tests
  src/Slot-Tests/SlotAnnouncementsTest.class.st
  src/Slot-Tests/SlotClassBuilderTest.class.st
  src/Slot-Tests/SlotErrorsTest.class.st
  src/Slot-Tests/SlotIntegrationTest.class.st
Labels: tests passed please review!

#14315 Remove usage of categories in Fuel
  src/Fuel-Core-Tests/FLClassFactoryForTestCase.class.st
  src/Fuel-Core-Tests/FLFullBasicSerializationTest.class.st
Labels: tests passed please review!

#14307 Do not remove categories through announcements
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: Reviewed and Ready to Integrate

#14312 Improve package cleaning API
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/Deprecated12/RPackageOrganizer.extension.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
  src/RPackage-Tests/RPackageTest.class.st
  src/SUnit-Core/ClassFactoryWithOrganization.class.st
  src/System-Support/SmalltalkImage.class.st
  src/Tool-ImageCleaner/ImageCleaner.class.st
Labels: Reviewed and Ready to Integrate

#14321 Improve package API used by Calypso
  src/Calypso-SystemPlugins-SUnit-Browser/TClyGenerateTestClass.trait.st
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
Labels: Reviewed and Ready to Integrate

#14320 Make sure packages created with protocols are announced
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: Reviewed and Ready to Integrate

#14327 Adapt check in RBAddMethodChange>>protocols: now that the argument may be a first-class Protocol (fixes #14324)
  src/Refactoring-Changes/RBAddMethodChange.class.st
Labels: tests passed please review!

#14329 Class are created with the wrong environment
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/Shift-ClassInstaller-Tests/ShClassInstallerTest.class.st
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
Labels: Reviewed and Ready to Integrate

#14331 Fix regex doc
  doc/Regex/1-Introduction.md
  doc/Regex/3-Syntax.md
  doc/Regex/4-Usage.md
  doc/Regex/5-ImplementationNotes.md
  doc/Regex/7-History.md
Labels: Reviewed and Ready to Integrate

#14330 Simplify class builder environment management
  src/ClassParser-Tests/ASTClassBuilderTest.class.st
  src/FluidClassBuilder/FluidBuilder.class.st
  src/Shift-ClassBuilder-Tests/ShAbstractClassBuilderTest.class.st
  src/Shift-ClassBuilder/ShGlobalsEnvironment.class.st
  src/Shift-ClassBuilder/ShSmalltalkGlobalsEnvironment.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/Shift-ClassInstaller-Tests/ShClassInstallerTest.class.st
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
  src/TraitsV2-Tests/T2TraitChangesTest.class.st
  src/UndefinedClasses-Tests/UndefinedClassTest.class.st
Labels: tests passed please review!

#14333 Improve coherence of RPackage tests
  src/Monticello-Tests/RPackageCategorySynchronisationTest.class.st
  src/Monticello-Tests/RPackageMCSynchronisationTest.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
  src/RPackage-Tests/RPackageTestCase.class.st
  src/RPackage-Tests/RPackageTraitTest.class.st
Labels: Reviewed and Ready to Integrate

#14322 Use "protocol" vocabulary in MCTestCase
  src/Monticello-Tests/MCPackageTest.class.st
  src/Monticello-Tests/MCTestCase.class.st
Labels: tests passed please review!

#14347 SImplify class addition in RPackage
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageReadOnlyCompleteSetupTest.class.st
Labels: tests passed please review!

#14350 Deprectaed #definedClassesDo:
  src/Deprecated12/RPackage.extension.st
  src/HeuristicCompletion-Model/CoBenchmarkPackage.class.st
  src/HeuristicCompletion-Model/SystemNavigation.extension.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/Ring-Core/RGReadOnlyImageBackend.class.st
Labels: tests passed please review!

#14359 Simplify class removal in packages
  src/Monticello-Tests/RPackageExtensionMethodsSynchronisationTest.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageCompleteSetupButForModificationTest.class.st
  src/RPackage-Tests/RPackageIncrementalTest.class.st
Labels: tests passed please review!

#14358 Simplify some classes management in RPackage
  src/Deprecated12/RPackage.extension.st
  src/RPackage-Core/RPackage.class.st
Labels: tests passed please review!

#14363 Do not remove classes from packages using the name
  src/Deprecated12/RPackage.extension.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageIncrementalTest.class.st
  src/RPackage-Tests/RPackageReadOnlyCompleteSetupTest.class.st
Labels: tests passed please review!

#14360 Clean method removal of RPackage
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageIncrementalTest.class.st
Labels: tests passed please review!

#14354 Forbid to have an extension method in the package owning the class
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ExtensionPointsOwningPackageNotification.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: tests passed please review!

#14230 Replaced the random generator from Pharo.
  src/Collections-Sequenceable-Tests/ArrayTest.class.st
  src/Random-Core/Random.class.st
  src/Random-Core/SequenceableCollection.extension.st
  src/Random-Tests/CollectionTest.extension.st
  src/Random-Tests/RandomTest.class.st
Labels: Need more work

#14366 Speed up in package management
  src/Deprecated12/CompiledCode.extension.st
  src/Kernel/CompiledMethod.class.st
  src/Monticello-Tests/RPackageExtensionMethodsSynchronisationTest.class.st
  src/Monticello-Tests/RPackageMethodsSynchronisationTest.class.st
  src/RPackage-Core/CompiledCode.extension.st
  src/RPackage-Core/CompiledMethod.extension.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageObsoleteTest.class.st
  src/RPackage-Tests/RPackageTraitTest.class.st
  src/TraitsV2/TaCompositionElement.class.st
  src/TraitsV2/TaRemoveMethod.class.st
  src/TraitsV2/TaSequence.class.st
Labels: tests passed please review!

#14370 Reduce usage of `RPackage organizer`
  src/Calypso-NavigationModel-Tests/ClyItemNameFilterTest.class.st
  src/Clap-Commands-Pharo/ClapTestRunner.class.st
  src/DrTests-CommentsToTests/DTCommentToTestPlugin.class.st
  src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
  src/DrTests-TestCoverage/DTTestCoveragePlugin.class.st
  src/DrTests-Tests/DrTestsTestRunnerTest.class.st
  src/DrTests-TestsProfiling-Tests/DTTestProfilingTest.class.st
  src/DrTests/DrTestsPlugin.class.st
  src/Epicea/EpCategoryChange.class.st
  src/Epicea/EpPlatform.class.st
  src/EpiceaBrowsers/EpDashboardPresenter.class.st
  src/FuzzyMatcher-Tests/FuzzyMatcherExample.class.st
  src/JenkinsTools-Core/HDTestReport.class.st
  src/JenkinsTools-ExtraReports/HDCoverageReport.class.st
  src/Monticello-Tests/RPackageMCSynchronisationTest.class.st
  src/Monticello/MCPackage.class.st
  src/Monticello/MCWorkingCopy.class.st
  src/RPackage-Core/ClassDescription.extension.st
  src/RPackage-Core/RPackageSet.class.st
  src/RPackage-Core/RPackageTag.class.st
  src/RPackage-Tests/RPackageIncrementalTest.class.st
  src/RPackage-Tests/RPackageTagTest.class.st
  src/RPackage-Tests/RPackageTest.class.st
  src/RPackage-Tests/RPackageTestCase.class.st
  src/SUnit-UI/TestRunner.class.st
  src/Tool-DependencyAnalyser/DADependenciesHTMLPublisher.class.st
  src/Tool-DependencyAnalyser/DADependencyChecker.class.st
Labels: Reviewed and Ready to Integrate

#14377 Simplify API of RPackage
  src/Deprecated12/RPackage.extension.st
  src/Monticello-Tests/RPackageClassesSynchronisationTest.class.st
  src/RPackage-Core/CompiledCode.extension.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageIncrementalTest.class.st
  src/RPackage-Tests/RPackageReadOnlyCompleteSetupTest.class.st
  src/TraitsV2-Tests/T2TraitWithPackagesTest.class.st
Labels: tests passed please review!

#14392 Fix fuel tests
  src/Fuel-Core-Tests/FLEnvironmentProtectingWrapper.class.st
Labels: easyReview

#14394 Push tag API in the class builder
  src/FluidClassBuilder/FluidBuilder.class.st
  src/SUnit-Core/ClassFactoryForTestCase.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
Labels: tests passed please review!

#14393 Remove the need of ClassFactoryWithOrganization
  src/SUnit-Core/ClassFactoryForTestCase.class.st
  src/SUnit-Core/ClassFactoryWithOrganization.class.st
  src/SUnit-Tests/ClassFactoryWithNonDefaultEnvironmentTest.class.st
  src/System-Support-Tests/SystemNavigationTest.class.st
Labels: tests passed please review!

#14346 rapid click on two different items in a list gets interpreted as a double-click on the first item
  src/Morphic-Core/MouseButtonEvent.class.st
  src/Morphic-Core/MouseButtonPseudoDoubleClickEvent.class.st
  src/Morphic-Widgets-FastTable/FTTableMorph.class.st
Labels: tests passed please review!

#14388 Do not remove classes through announcement
  src/Kernel/Class.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Core/RPackageTag.class.st
  src/RPackage-Tests/RPackageTagTest.class.st
  src/RPackage-Tests/RPackageTest.class.st
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
  src/System-Announcements/ClassRemoved.class.st
  src/System-Announcements/SystemAnnouncer.class.st
  src/System-Support/SystemDictionary.class.st
Labels: tests passed please review!

#14364 Simplify class addition assuming classes are created empty
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Tests/RPackageIncrementalTest.class.st
Labels: tests passed please review!
