Repository pharo-project/pharo, pull requests merged in 2023-06, with the labels that each got.

#13866 Remove Epicea catch all
  src/Epicea/EpMonitor.class.st
Labels: tests passed please review!

#13868 Finish to remove #organization from protocol tests
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel-Tests/ProtocolAnnouncementsTest.class.st
  src/Kernel-Tests/ProtocolTest.class.st
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#13873 Enh/refac
  src/Refactoring-Core/RBAbstractTransformation.class.st
  src/Refactoring-Core/RBRefactoring.class.st
  src/Refactoring-Core/RBTRefactoringBuilder.trait.st
  src/Refactoring2-Transformations/RBExtractMethodTransformation.class.st
  src/Refactoring2-Transformations/RBInlineMethodTransformation.class.st
  src/Refactoring2-Transformations/RBMoveMethodTransformation.class.st
  src/Refactoring2-Transformations/RBTransformation.class.st
Labels: more-information-needed

#13876 Moved Metalevel management to its own package
  src/BaselineOfInstrumentation/BaselineOfInstrumentation.class.st
  src/BaselineOfInstrumentation/package.st
  src/BaselineOfReflectivity/BaselineOfReflectivity.class.st
  src/Instrumentation/BlockClosure.extension.st
  src/Instrumentation/InstrumentationDeactivator.class.st
  src/Instrumentation/InstrumentationEnsurer.class.st
  src/Instrumentation/Process.extension.st
  src/Instrumentation/ProtoObject.extension.st
  src/Instrumentation/SmallInteger.extension.st
  src/Instrumentation/package.st
  src/Reflectivity/MetaLink.class.st
  src/Reflectivity/Process.extension.st
Labels: tests passed please review!

#13875 Clean OSWorldRender>>#doActivate
  src/OSWindow-Core/OSWorldRenderer.class.st
Labels: Cleanup, tests passed please review!

#13822 clean conditionals
  src/Morphic-Base/Form.extension.st
  src/Morphic-Base/ThumbnailMorph.class.st
Labels: tests passed please review!

#13861 Inline ClassOrganization
  src/CodeImport/ClassOrganizationChunk.class.st
  src/Deprecated12/ClassDescription.extension.st
  src/Deprecated12/ClassOrganization.extension.st
  src/Epicea-Tests/EpCodeChangeIntegrationTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyPreviewerTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers-Tests/EpRevertTest.class.st
  src/EpiceaBrowsers/EpApplyVisitor.class.st
  src/Fuel-Core/FLBehaviorCluster.class.st
  src/Gofer-Tests/GoferOperationTest.class.st
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel-Tests/ClassDescriptionTest.class.st
  src/Kernel/Class.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/Kernel/Protocol.class.st
  src/Monticello-Tests/RPackageClassesSynchronisationTest.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/Refactoring2-Transformations/RBAddMethodTransformation.class.st
  src/Ring-Definitions-Core/RGClassDescriptionDefinition.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/System-Announcements-Tests/SystemAnnouncerTest.class.st
  src/TraitsV2-Tests/T2TraitWithCategoriesTest.class.st
Labels: tests passed please review!

#13879 Introduce strategy design pattern in Finder model
  src/Tool-Finder/Finder.class.st
  src/Tool-Finder/FinderClassesSearchStrategy.class.st
  src/Tool-Finder/FinderExamplesSearchStrategy.class.st
  src/Tool-Finder/FinderMethodNode.class.st
  src/Tool-Finder/FinderPragmasSearchStrategy.class.st
  src/Tool-Finder/FinderSearchStrategy.class.st
  src/Tool-Finder/FinderSelectorsSearchStrategy.class.st
  src/Tool-Finder/FinderSourceSearchStrategy.class.st
  src/Tool-Finder/FinderUI.class.st
Labels: tests passed please review!

#13878 Fix reading "super" reflectively: same as reading self
  src/Kernel/SuperVariable.class.st
  src/Slot-Tests/SuperVariableTest.class.st
Labels: tests passed please review!

#13880 Deprecate ClassDescription>>#addMethodTag:
  src/Calypso-SystemQueries/ClyTaggedMethodGroup.class.st
  src/Deprecated12/ClassDescription.extension.st
  src/Deprecated12/RGBehavior.extension.st
  src/Kernel/ClassDescription.class.st
  src/Ring-Core/RGBehavior.class.st
  src/Ring-Core/RGMethod.class.st
  src/Ring-Tests-Core/RGBehaviorTest.class.st
  src/Ring-Tests-Core/RGClassTest.class.st
  src/SystemCommands-ClassCommands/SycAddNewMethodTagCommand.class.st
Labels: Reviewed and Ready to Integrate

#13882 Some simple cleanups (lookupVar: category, #home use ifNotNil...)
  src/Debugging-Core/Context.extension.st
  src/Fuel-Tests-Core/FLEnvironmentProtectingWrapper.class.st
  src/Kernel/Behavior.class.st
  src/Kernel/CompiledMethod.class.st
  src/Kernel/Context.class.st
  src/Kernel/ProcessorScheduler.class.st
  src/OpalCompiler-Core/Behavior.extension.st
  src/OpalCompiler-Core/CompiledMethod.extension.st
  src/OpalCompiler-Core/Context.extension.st
Labels: tests passed please review!

#13883 Reflectivity: thisProcess and remove #rfactiveProcess and #rfeffectiveProcess
  src/Reflectivity-Tests/ReflectivityControlTest.class.st
  src/Reflectivity-Tests/ReflectivityReificationTest.class.st
  src/Reflectivity/MetaLink.class.st
  src/Reflectivity/Process.extension.st
  src/Reflectivity/ProcessorScheduler.extension.st
Labels: tests passed please review!

#13896 Clean fluid class builder tests
  src/FluidClassBuilder-Tests/FluidClassBuilderAbstractTest.class.st
  src/FluidClassBuilder-Tests/FluidClassBuilderTest.class.st
  src/FluidClassBuilder-Tests/FluidClassSideClassBuilderTest.class.st
  src/FluidClassBuilder-Tests/FluidClassSideTraitBuilderTest.class.st
  src/FluidClassBuilder-Tests/FluidTraitBuilderTest.class.st
Labels: tests passed please review!

#13912 11476-TestAsserter--shouldnt-raise-whoseDescriptionIncludes-description-is-sending-an-unimplemented-messsage
  src/SUnit-Core/TestAsserter.class.st
  src/SUnit-Core/TestCase.class.st
Labels: tests passed please review!

#13919 Reduce references to Smalltalk
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/CodeExport/RPackageOrganizer.extension.st
  src/CodeExport/RPackageTag.extension.st
  src/Epicea/EpMonitor.class.st
  src/FluidClassBuilder-Tests/FluidClassBuilderAbstractTest.class.st
  src/Fuel-Tests-Core/FLClassFactoryForTestCase.class.st
  src/Fuel-Tests-Core/FLFullBasicSerializationTest.class.st
  src/Gofer-Core/GoferCleanup.class.st
  src/Gofer-Tests/GoferOperationTest.class.st
  src/JenkinsTools-Core/HDReport.class.st
  src/Kernel/Behavior.class.st
  src/Kernel/Object.class.st
  src/Metacello-PharoCommonPlatform/MetacelloPharoCommonPlatform.class.st
  src/Monticello-Tests/MCOrganizationTest.class.st
  src/Monticello-Tests/MCWorkingCopyForExtensionsTest.class.st
  src/Monticello-Tests/RPackageCategorySynchronisationTest.class.st
  src/Monticello-Tests/RPackageMCSynchronisationTest.class.st
  src/Monticello/MCOrganizationDefinition.class.st
  src/Monticello/MCPackage.class.st
  src/Monticello/MCPackageManager.class.st
  src/RPackage-Core/ClassDescription.extension.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Core/RPackageTag.class.st
  src/RPackage-Core/String.extension.st
  src/RPackage-Tests/RPackageIncrementalTest.class.st
  src/RPackage-Tests/RPackageOrganizerAndSystemOrganizeSynchTest.class.st
  src/RPackage-Tests/RPackageOrganizerSystemTest.class.st
  src/RPackage-Tests/RPackageRenameTest.class.st
  src/RPackage-Tests/RPackageTest.class.st
  src/RPackage-Tests/RPackageTraitTest.class.st
  src/RPackage-Tests/RPackageWithDoTest.class.st
  src/Refactoring-Environment/RBBrowserEnvironment.class.st
  src/ReleaseTests/ProperPackagesTest.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/Ring-OldChunkImporter/RingChunkImporter.class.st
  src/SUnit-Core/ClassFactoryForTestCase.class.st
  src/SUnit-Tests/ClassFactoryForTestCaseTest.class.st
  src/SUnit-UI/TestRunner.class.st
  src/Shift-ClassInstaller-Tests/ShAnonymousClassInstallerTest.class.st
  src/Slot-Tests/SlotClassBuilderTest.class.st
  src/System-Settings-Tests/SettingBrowserTest.class.st
  src/System-Support/SmalltalkImage.class.st
  src/Tool-DependencyAnalyser-Tests/DATarjanAlgorithmTest.class.st
  src/Tool-DependencyAnalyser-UI/DAAddPackagePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DACycleDetectionTreePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DADependencyTreePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAPackageAnalyzerPresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAPackageDependenciesPresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAWelcomePresenter.class.st
  src/Tool-DependencyAnalyser/DADependencyChecker.class.st
  src/Tool-DependencyAnalyser/DAMessageSendAnalyzer.class.st
  src/Tool-DependencyAnalyser/DAPackageCycleDetector.class.st
  src/Tool-DependencyAnalyser/DAPackageRelationGraph.class.st
  src/Tool-ImageCleaner/ImageCleaner.class.st
  src/TraitsV2-Tests/T2TraitWithPackagesTest.class.st
Labels: tests passed please review!

#13793 Fix some typos in the docs
  README.md
  doc/Announcements/Announcements.md
  doc/BoltsAndNuts/FreetypeFonts.md
  doc/BoltsAndNuts/ImportingResouces.md
  doc/BoltsAndNuts/PharoEnvironment.md
  doc/BoltsAndNuts/Settings.md
  doc/BoltsAndNuts/WorldMenuItems.md
  doc/Epicea/1-Epicea.md
  doc/RefactoringEngine/1-RefactoringEngine.md
  doc/RefactoringEngine/2-RefactoringList.md
  doc/RefactoringEngine/3-ScriptingRefactorings.md
  doc/RefactoringEngine/4-RefactoringEngineFoundation.md
  doc/RefactoringEngine/5-PatternMatcher.md
  doc/RefactoringEngine/6-Environment.md
  doc/RefactoringEngine/7-EnvironmentList.md
  doc/Regex/1-Introduction.md
  doc/Regex/3-Syntax.md
  doc/Regex/4-Usage.md
  doc/SUnit/1-SUnit.md
  doc/SUnit/4-tutorial.md
Labels: Documentation, Reviewed and Ready to Integrate, first impression counts

#13858 Cut dependency of Collection-Strings over SessionManager
  bootstrap/scripts/4-build.sh
  src/Collections-Strings/Symbol.class.st
  src/System-SessionManager/SessionManager.class.st
Labels: tests passed please review!

#13917 Show completion details setting
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion-Preferences/NECPreferences.class.st
Labels: tests passed please review!

#13924 Fixes #13908: isTransformation and remove duplicated code for now.
  src/Refactoring-Core/RBAbstractTransformation.class.st
  src/Refactoring-Core/RBFindAndReplaceTransformation.class.st
  src/Refactoring-Core/RBRefactoring.class.st
  src/Refactoring2-Transformations/RBTransformation.class.st
Labels: tests passed please review!

#12950 Remove font logic from Shout since it is all dead code
  src/Deprecated12/SHRBTextStyler.extension.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!, pharo12

#13923 Add benchmark comparison
  src/Kernel-Chronology-Extras/BenchmarkComparison.class.st
  src/Kernel-Chronology-Extras/BenchmarkResult.class.st
  src/Kernel-Chronology-Extras/BlockClosure.extension.st
  src/Kernel-Chronology-Extras/DateParser.class.st
Labels: tests passed please review!

#13927 Deprecate SHRBTextStyler>>#format:
  src/Deprecated12/SHRBTextStyler.extension.st
  src/Rubric-Styling/RubShoutStylerDecorator.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#13926 Fix last inconsistancy in Fluid tests package generation
  src/FluidClassBuilder-Tests/FluidClassBuilderTest.class.st
Labels: tests passed please review!

#13928 Clean #dependentClasses
  src/Kernel/Behavior.class.st
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#13936 Update more users of #protocol
  src/EpiceaBrowsers/EpMorphVisitor.class.st
  src/EpiceaBrowsers/EpNewStateVisitor.class.st
  src/EpiceaBrowsers/EpOldStateVisitor.class.st
  src/GeneralRules/ReInconsistentMethodClassificationRule.class.st
  src/Kernel-Tests/ClassDescriptionTest.class.st
  src/Kernel/CompiledMethod.class.st
  src/ReleaseTests/ProperPackagesTest.class.st
  src/Tool-Base/MethodClassifier.class.st
  src/TraitsV2-Tests/T2TraitWithCategoriesTest.class.st
Labels: tests passed please review!

#13941 Bring back coverage test
  src/Coverage/CoverageCollectorTest.class.st
Labels: tests passed please review!

#13949 13938-Changing-a-class-side-Slot-to-a-WriteOnceSlot-renders-a-NonBooleanReceiver-proceed-for-truth
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
  src/Slot-Tests/WriteOnceSlotTest.class.st
Labels: Reviewed and Ready to Integrate

#13948 ReGlobalVariablesUsageRule should ignore the aliases of deprecated classes
  src/GeneralRules/ReGlobalVariablesUsageRule.class.st
Labels: Reviewed and Ready to Integrate

#13956 Refactor: Move methods to class that only uses them
  src/Refactoring-Core/RBChangeMethodNameRefactoring.class.st
  src/Refactoring-Core/RBRefactoring.class.st
Labels: tests passed please review!

#13959 13957--RBRefactoringonErrordo--should-accept-both-0-and-1-arg-block
  src/Refactoring-Core/RBRefactoring.class.st
Labels: tests passed please review!

#13955 fix 13903 RBReplaceMessageSendTransformation
  src/Refactoring-Core/RBReplaceMessageSendTransformation.class.st
Labels: tests passed please review!

#13929 Move Color startup registration
  src/Colors/Color.class.st
  src/Graphics-Primitives/BitBlt.class.st
  src/Graphics-Primitives/Color.extension.st
Labels: tests passed please review!

#13954 Make width constants in RubTextSegmentIconDisplayer take the display scale factor into account
  src/Morphic-Core/Number.extension.st
  src/Rubric/RubTextSegmentIconDisplayer.class.st
Labels: tests passed please review!

#13953 Make initial extent of SettingBrowser, ThreadSafeTranscript, FinderUI, EpUnifiedBrowserPresenter and EpLogBrowserPresenter take the display scale factor into account
  src/EpiceaBrowsers/EpLogBrowserPresenter.class.st
  src/EpiceaBrowsers/EpUnifiedBrowserPresenter.class.st
  src/System-Settings-Browser/SettingBrowser.class.st
  src/Tool-Finder-UI/FinderUI.class.st
  src/Transcript-Core/ThreadSafeTranscript.class.st
Labels: tests passed please review!

#13961 13942-TraitCompositionTesttestAliasCompositions--passes-but-for-the-wrong-reason
  src/TraitsV2-Tests/TraitCompositionTest.class.st
Labels: tests passed please review!

#13960 Refact/clean
  src/Refactoring-Changes/RBAddProtocolChange.class.st
  src/Refactoring-Core/RBAbstractTransformation.class.st
  src/Refactoring-Core/RBInlineAllSendersRefactoring.class.st
  src/Refactoring2-Transformations-Tests/RBAddParameterParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBDeprecateMethodParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBExtractToTemporaryParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBInlineAllMethodParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBInlineMethodParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBRemoveAllMessageSendsTransformationTest.class.st
  src/Refactoring2-Transformations-Tests/RBRemoveAllSendersParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBRemoveSenderMethodParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBReplaceSendersMethodParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBTransformationsTest.class.st
  src/Refactoring2-Transformations/RBRemoveAllMessageSendsTransformation.class.st
Labels: more-information-needed

#13969 Remove empty packages
  src/Commander2-Deprecations/package.st
  src/Debugger-Filters-Tests/package.st
  src/Debugger-Filters/package.st
  src/EyeInspector/package.st
  src/Reflectivity-VariableBreakpoint/package.st
  src/Zinc-Resource-Meta-FileSystem/package.st
Labels: easyReview

#13968 Move some session manager registrations
  src/Kernel/SmallInteger.class.st
  src/Random-Core/Color.extension.st
  src/Random-Core/SharedRandom.class.st
  src/System-Platforms/OSPlatform.class.st
  src/System-SessionManager/SessionManager.class.st
  src/System-Support/EndianDetector.class.st
Labels: tests passed please review!

#13967 Update the way we deal with protocols from other classes
  src/CodeImport/ClassOrganizationChunk.class.st
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel-Tests/ProtocolAnnouncementsTest.class.st
  src/Kernel-Tests/ProtocolTest.class.st
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#13987 Rework UITheme tree forms for better display scaling support
  src/Polymorph-Widgets/UITheme.class.st
Labels: tests passed please review!

#13996 Simplify Metacello testing
  src/BaselineOfMetacello/BaselineOfMetacello.class.st
  src/Gofer-Tests/GoferResource.class.st
  src/Metacello-Core/MetacelloPlatform.class.st
  src/Metacello-MC/MetacelloMCVersionSpec.class.st
  src/Metacello-PharoCommonPlatform/MetacelloPharoCommonPlatform.class.st
  src/Metacello-TestsCommonMC/MetacelloTestsMCPackage.extension.st
  src/Metacello-TestsCommonMC/MetacelloTestsPackageSet.class.st
  src/Metacello-TestsCommonMC/package.st
  src/Metacello-TestsMCResources/MetacelloAlternateResource.class.st
  src/Metacello-TestsMCResources/MetacelloAtomicConfigurationResource.class.st
  src/Metacello-TestsMCResources/MetacelloAtomicMonticelloResource.class.st
  src/Metacello-TestsMCResources/MetacelloConfigurationResource.class.st
  src/Metacello-TestsMCResources/MetacelloIssue108Resource.class.st
  src/Metacello-TestsMCResources/MetacelloMonticelloResource.class.st
  src/Metacello-TestsMCResources/MetacelloScriptingResource.class.st
  src/Metacello-TestsMCResources/MetacelloTestsMCPackage.class.st
Labels: tests passed please review!

#13999 Handle single-sized collection in stdev method.
  src/Collections-Arithmetic-Tests/CollectionArithmeticTest.class.st
  src/Collections-Arithmetic/Collection.extension.st
Labels: Reviewed and Ready to Integrate

#14003 13988-two-senders-of-finalizeValues-in-WeakKeyDictionaryTest-class
  src/Collections-Weak-Tests/WeakKeyDictionaryTest.class.st
Labels: Reviewed and Ready to Integrate

#13768 Use more protocol object in RPackage
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageSet.class.st
  src/RPackage-Core/RPackageTag.class.st
  src/Refactoring-Critics/RBMultiEnvironment.class.st
  src/Refactoring-Environment/RBAndEnvironment.class.st
  src/Refactoring-Environment/RBBrowserEnvironment.class.st
  src/Refactoring-Environment/RBBrowserEnvironmentWrapper.class.st
  src/Refactoring-Environment/RBOrEnvironment.class.st
  src/Refactoring-Environment/RBProtocolEnvironment.class.st
  src/Refactoring-Environment/RBSelectorEnvironment.class.st
  src/Refactoring-Environment/RBVariableEnvironment.class.st
  src/Refactoring-Tests-Environment/RBBrowserEnvironmentTest.class.st
  src/Refactoring2-Transformations/RBRemoveProtocolTransformation.class.st
Labels: tests passed please review!

#13965 Modified the UUID class to use a primitive and added parsing options
  src/Network-Tests/UUIDGeneratorTest.class.st
  src/Network-Tests/UUIDPrimitivesTest.class.st
  src/Network-Tests/UUIDTest.class.st
  src/Network-UUID/ByteArray.extension.st
  src/Network-UUID/UUID.class.st
  src/Network-UUID/UUIDGenerator.class.st
  src/STON-Tests/STONWriteReadTest.class.st
Labels: Need more work

#14007 add more #ignoreNotImplementedSelectors: tags
  src/Metacello-Core/MetacelloPlatform.class.st
  src/Refactoring-Tests-Critics/RBSmalllintTestObject.class.st
  src/SUnit-Tests/SUnitTest.class.st
  src/TraitsV2-Tests/T2TraitTest.class.st
Labels: tests passed please review!

#14009 MetacelloPharoCommonPlatform>>#suspendSystemUpdateEventsDuring: should use #suspendAllWhile:
  src/Metacello-PharoCommonPlatform/MetacelloPharoCommonPlatform.class.st
Labels: tests passed please review!

#14011 move the extension methods of Spec to the class SHRBTextStyler
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#14015 Fix broken release tests + improve a test
  src/Kernel-Tests/MockWithComplexSlot.class.st
  src/Refactoring-DataForTesting/RBDummyLintRuleTest.class.st
  src/Refactoring-DataForTesting/RBFooDummyLintRuleTest.class.st
  src/Refactoring-DataForTesting/RBFooLintRuleTestData.class.st
  src/Refactoring-DataForTesting/RBLintRuleTestData.class.st
  src/Refactoring-DataForTesting/RBTransformationDummyRuleTest.class.st
  src/Refactoring-Tests-Changes/RBRefactoringChangeMock.class.st
  src/Refactoring2-Transformations-Tests/RBAbstractInstanceVariableParametrizedTest.class.st
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
Labels: tests passed please review!

#14012 Clean manifest builder test and cut dependency to Monticello
  src/Manifest-Tests/BuilderManifestTest.class.st
  src/Manifest-Tests/SmalllintManifestCheckerTest.class.st
Labels: tests passed please review!

#14023 Make WorldState and ProfStef take the display scale factor into account for the world menu items with the #pharo icon
  src/Morphic-Core/WorldState.class.st
  src/ProfStef-Core/ProfStef.class.st
Labels: tests passed please review!

#14020 Make `HaloMorph>>#handleSize` take the display scale factor into account
  src/Morphic-Base/HaloMorph.class.st
Labels: tests passed please review!

#14021 Change colors of the ‘grab’ and ‘rotate’ halo morph handles for better contrast with their icons
  src/Morphic-Base/HaloMorph.class.st
Labels: Reviewed and Ready to Integrate

#14032 Cleanup CDNode Hierarchy: #acceptVisitor:
  src/ClassParser/CDClassTagNode.class.st
  src/ClassParser/CDNode.class.st
  src/ClassParser/CDPackageNode.class.st
  src/ClassParser/CDTraitDefinitionNode.class.st
Labels: Reviewed and Ready to Integrate

#14035 Update some CompiledMethod>>#category senders
  src/Epicea/CompiledMethod.extension.st
  src/Monticello-Tests/RPackageCategorySynchronisationTest.class.st
  src/Monticello-Tests/RPackageExtensionMethodsSynchronisationTest.class.st
  src/Monticello-Tests/RPackageMethodsSynchronisationTest.class.st
  src/Monticello/RGMethodDefinition.extension.st
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: tests passed please review!

#14028 Fluid: show empty slots on the class side, too
  src/Kernel/FluidClassDefinitionPrinter.class.st
Labels: tests passed please review!

#14043 Remove unloaded deprecated packages
  src/Deprecated10/package.st
  src/Deprecated80/AbstractFileReference.extension.st
  src/Deprecated80/Archive.extension.st
  src/Deprecated80/AthensPluggableTextMorph.class.st
  src/Deprecated80/Base64MimeConverter.extension.st
  src/Deprecated80/Behavior.extension.st
  src/Deprecated80/CairoBackendCache.extension.st
  src/Deprecated80/Character.extension.st
  src/Deprecated80/Class.extension.st
  src/Deprecated80/ClassDescription.extension.st
  src/Deprecated80/CollectionElement.extension.st
  src/Deprecated80/DTCommentToTest.extension.st
  src/Deprecated80/DTMockPlugin.extension.st
  src/Deprecated80/DTTestCoverage.extension.st
  src/Deprecated80/DTTestsProfiling.extension.st
  src/Deprecated80/DTTestsRunner.extension.st
  src/Deprecated80/DateAndTime.extension.st
  src/Deprecated80/DebugSession.extension.st
  src/Deprecated80/DrTests.extension.st
  src/Deprecated80/DrTestsPlugin.extension.st
  src/Deprecated80/Editor.class.st
  src/Deprecated80/ExternalObject.extension.st
  src/Deprecated80/FFICalloutMethodBuilder.extension.st
  src/Deprecated80/FFILibrary.extension.st
  src/Deprecated80/FTFunction.extension.st
  src/Deprecated80/FTTableMorph.extension.st
  src/Deprecated80/FloatingPointException.class.st
  src/Deprecated80/GTSpotterStep.extension.st
  src/Deprecated80/Gofer.extension.st
  src/Deprecated80/Integer.extension.st
  src/Deprecated80/ManifestDeprecated80.class.st
  src/Deprecated80/NaNException.class.st
  src/Deprecated80/NotFoundError.class.st
  src/Deprecated80/OSPlatform.extension.st
  src/Deprecated80/Object.extension.st
  src/Deprecated80/PluggableListMorph.extension.st
  src/Deprecated80/PluggableTextFieldMorph.class.st
  src/Deprecated80/PluggableTextMorph.class.st
  src/Deprecated80/Pragma.extension.st
  src/Deprecated80/Protocol.extension.st
  src/Deprecated80/ProtocolOrganizer.extension.st
  src/Deprecated80/RPackage.extension.st
  src/Deprecated80/RPackageSet.extension.st
  src/Deprecated80/RPackageTag.extension.st
  src/Deprecated80/SequenceableCollection.extension.st
  src/Deprecated80/SetElement.class.st
  src/Deprecated80/SimpleHierarchicalListMorph.extension.st
  src/Deprecated80/SystemNavigation.extension.st
  src/Deprecated80/TraitedClass.extension.st
  src/Deprecated80/WeakSubscriptionBuilder.extension.st
  src/Deprecated80/ZipArchive.extension.st
  src/Deprecated80/package.st
  src/Deprecated90/package.st
Labels: Reviewed and Ready to Integrate

#14042 Fix finder selection
  src/Tool-Finder/FinderClassesSearchStrategy.class.st
  src/Tool-Finder/FinderExamplesSearchStrategy.class.st
  src/Tool-Finder/FinderPragmasSearchStrategy.class.st
  src/Tool-Finder/FinderSelectorsSearchStrategy.class.st
  src/Tool-Finder/FinderSourceSearchStrategy.class.st
Labels: tests passed please review!

#13494 Ensure renaming of protocol announce the changes
  src/Kernel-Tests/ProtocolAnnouncementsTest.class.st
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#14046 Do not poluate Monticello cache in tests
  src/Monticello-Tests/MCWorkingCopyTest.class.st
  src/Monticello/MCCacheRepository.class.st
Labels: tests passed please review!

#14040 Simplify MCWorkingCopy management
  src/Monticello-Tests/MCChangeNotificationTest.class.st
  src/Monticello-Tests/MCMethodDefinitionTest.class.st
  src/Monticello-Tests/MCPackageManagerTest.class.st
  src/Monticello-Tests/MCSerializationTest.class.st
  src/Monticello-Tests/MCSnapshotTest.class.st
  src/Monticello-Tests/MCWorkingCopyTest.class.st
  src/Monticello-Tests/RPackageMonticelloSynchronisationTest.class.st
  src/Monticello/MCPackage.class.st
  src/Monticello/MCPackageManager.class.st
  src/Monticello/MCWorkingCopy.class.st
  src/Monticello/MonticelloBootstrap.class.st
  src/MonticelloGUI/MCFileRepositoryInspector.class.st
  src/MonticelloGUI/MCWorkingCopyBrowser.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageRenameTest.class.st
  src/RPackage-Tests/RPackageTest.class.st
Labels: tests passed please review!

#14047 Deprecated CompiledMethod>>category
  src/Kernel/CompiledMethod.class.st
  src/OpalCompiler-Core/CompiledMethod.extension.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/Ring-Definitions-Core/CompiledMethod.extension.st
  src/Ring-Definitions-Core/RGMethodDefinition.class.st
  src/System-SourcesCondenser/PharoChangesCondenser.class.st
Labels: tests passed please review!

#14041 Merge MCWorkingCopy and MCPackageManager
  bootstrap/scripts/emulation/shrink.st
  src/Monticello-Tests/MCWorkingCopyManagementTest.class.st
  src/Monticello/MCPackageManager.class.st
  src/Monticello/MCWorkingCopy.class.st
  src/Pharo30Bootstrap/PBBootstrap.class.st
Labels: tests passed please review!

#14050 Update MethodAddition to use #protocol
  src/CodeExport/ClassDescription.extension.st
  src/Monticello/MethodAddition.class.st
Labels: tests passed please review!

#14044 Move Margin from Kernel to Graphics
  src/Graphics-Display Objects/Margin.class.st
  src/Graphics-Display Objects/Number.extension.st
  src/Graphics-Display Objects/Point.extension.st
  src/Graphics-Display Objects/Rectangle.extension.st
  src/Graphics-Display Objects/Screenshot.class.st
  src/Kernel/Number.class.st
  src/Kernel/Point.class.st
  src/Kernel/Rectangle.class.st
Labels: tests passed please review!

#14048 Enh/refact pass on preconditions
  src/Refactoring-Core/RBAbstractVariablesRefactoring.class.st
  src/Refactoring-Core/RBCondition.class.st
  src/Refactoring-Core/RBMakeClassAbstractTransformation.class.st
  src/Refactoring-Tests-Core/RBConditionTest.class.st
  src/Refactoring2-Transformations-Tests/RBRealizeClassParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBStaticModelCreationTest.class.st
  src/Refactoring2-Transformations/RBAbstractVariablesTransformation.class.st
  src/Refactoring2-Transformations/RBRealizeClassTransformation.class.st
Labels: tests passed please review!

#14052 adding-perm-space-statistics
  src/System-Support/VirtualMachine.class.st
Labels: Reviewed and Ready to Integrate

#14054 Fix class parser for non-fluid nil subclass definitions
  src/ClassParser-Tests/CDNilSubclassParserTest.class.st
  src/ClassParser/CDClassDefinitionParser.class.st
  src/ClassParser/CDClassNameNode.class.st
Labels: Reviewed and Ready to Integrate

#14058 reduce the usage of the non-fluid class definiton methods
  src/Kernel/Class.class.st
  src/Kernel/UndefinedObject.class.st
  src/TraitsV2-Tests/TraitsResource.class.st
Labels: tests passed please review!

#14064 Remove double initialization of MCWorkingCopy
  src/Pharo30Bootstrap/PBBootstrap.class.st
Labels: Reviewed and Ready to Integrate

#14066 ClassBuilder users: Do not set 'Unclassified' category/package explicitly
  src/ClassParser/ShiftClassBuilder.extension.st
  src/Kernel/Class.class.st
Labels: Reviewed and Ready to Integrate

#14067 Move Monticello diffs to its own package
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/Monticello-GUI-Diff/CommandLineUIManager.extension.st
  src/Monticello-GUI-Diff/DummyUIManager.extension.st
  src/Monticello-GUI-Diff/MCMergeResolutionRequest.extension.st
  src/Monticello-GUI-Diff/MCModification.extension.st
  src/Monticello-GUI-Diff/MCOrganizationDefinition.extension.st
  src/Monticello-GUI-Diff/MCPatchBrowser.extension.st
  src/Monticello-GUI-Diff/MCPatchOperation.extension.st
  src/Monticello-GUI-Diff/MCVersionHistoryBrowser.extension.st
  src/Monticello-GUI-Diff/MCVersionInspector.extension.st
  src/Monticello-GUI-Diff/MCWorkingCopyBrowser.extension.st
  src/Monticello-GUI-Diff/MorphicUIManager.extension.st
  src/Monticello-GUI-Diff/NonInteractiveUIManager.extension.st
  src/Monticello-GUI-Diff/PSMCChangeWrapper.class.st
  src/Monticello-GUI-Diff/PSMCChangesGrouper.class.st
  src/Monticello-GUI-Diff/PSMCClassChangeWrapper.class.st
  src/Monticello-GUI-Diff/PSMCMergeMorph.class.st
  src/Monticello-GUI-Diff/PSMCMergePatchMorph.class.st
  src/Monticello-GUI-Diff/PSMCOrganizationChangeWrapper.class.st
  src/Monticello-GUI-Diff/PSMCPatchMorph.class.st
  src/Monticello-GUI-Diff/PSMCPatchOperationWrapper.class.st
  src/Monticello-GUI-Diff/UIManager.extension.st
  src/Monticello-GUI-Diff/package.st
  src/Monticello/RPackageOrganizer.extension.st
  src/Polymorph-Widgets/MorphicUIManager.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
  src/Tool-ExternalBrowser/ExternalChangesBrowser.class.st
  src/UIManager/DummyUIManager.class.st
  src/UIManager/UIManager.class.st
Labels: tests passed please review!

#14069 Simplify ClyMethodEditorToolMorph
  src/Calypso-SystemTools-Core/ClyMethodCodeEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodCreationToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodTagsAndPackageEditorMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodTagsEditorMorph.class.st
  src/Deprecated12/ClyMethodEditorToolMorph.extension.st
Labels: tests passed please review!

#14071 rename ReservedVariable to PseudoVariable
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBVariableNode.class.st
  src/Kernel/DoItVariable.class.st
  src/Kernel/PseudoVariable.class.st
  src/Kernel/SelfVariable.class.st
  src/Kernel/SuperVariable.class.st
  src/Kernel/ThisContextVariable.class.st
  src/Kernel/ThisProcessVariable.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/Variable.extension.st
  src/OpalCompiler-Tests/OCCompilerNotifyingTest.class.st
  src/Ring-Core/RGEnvironment.class.st
  src/Ring-Core/RGVariable.class.st
  src/Shout/PseudoVariable.extension.st
  src/Shout/ReservedVariable.extension.st
  src/System-Support/SystemDictionary.class.st
Labels: Reviewed and Ready to Integrate

#14072 Decouple Monticello and RPackage on package removal
  src/Monticello/MCWorkingCopy.class.st
  src/Monticello/RPackage.extension.st
  src/Monticello/RPackageOrganizer.extension.st
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: tests passed please review!

#14076 Fix package file out
  src/CodeExport/RPackage.extension.st
Labels: Reviewed and Ready to Integrate

#14078 Deprecate CompiledMethod>>#tags
  src/Calypso-SystemQueries/ClyUnclassifiedMethodsQuery.class.st
  src/Deprecated12/CompiledMethod.extension.st
  src/Kernel/CompiledMethod.class.st
  src/SystemCommands-MethodCommands/SycSilentlyRemoveMethodStrategy.class.st
Labels: tests passed please review!

#14077 Finish Monticello decoupling in RPackage
  src/RPackage-Core/ManifestRPackageCore.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: tests passed please review!

#14081 Iteration on package tag announcements
  src/RPackage-Core/PackageRenamed.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageTag.class.st
  src/System-Announcements/ClassTagAdded.class.st
  src/System-Announcements/ClassTagAnnouncement.class.st
  src/System-Announcements/ClassTagRemoved.class.st
  src/System-Announcements/ClassTagRenamed.class.st
  src/System-Announcements/PackageTagAdded.class.st
  src/System-Announcements/PackageTagAnnouncement.class.st
  src/System-Announcements/PackageTagRemoved.class.st
  src/System-Announcements/PackageTagRenamed.class.st
  src/System-Announcements/SystemAnnouncer.class.st
Labels: tests passed please review!

#14088 Fix trait definition in Calypso when fluid is enabled
  src/Calypso-SystemPlugins-Traits-Queries/ClySystemEnvironment.extension.st
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
Labels: Reviewed and Ready to Integrate

#14087 Epicea: Clean package addition and fix bugs
  src/Epicea/EpCategoryChange.class.st
  src/Epicea/EpCategoryRegistration.class.st
  src/Epicea/EpCategoryRename.class.st
  src/Epicea/EpMonitor.class.st
  src/Epicea/EpPackageAddition.class.st
  src/Epicea/EpTCodeChangeVisitor.trait.st
  src/EpiceaBrowsers/EpApplyPreviewer.class.st
  src/EpiceaBrowsers/EpApplyVisitor.class.st
  src/EpiceaBrowsers/EpBrowseVisitor.class.st
  src/EpiceaBrowsers/EpHasImpactVisitor.class.st
  src/EpiceaBrowsers/EpIconVisitor.class.st
  src/EpiceaBrowsers/EpInverseVisitor.class.st
  src/EpiceaBrowsers/EpMorphVisitor.class.st
  src/EpiceaBrowsers/EpNewStateVisitor.class.st
  src/Kernel/Class.class.st
Labels: tests passed please review!

#14091 Refactor: Add "(T)" prefix to Find and Replace transformation
  src/SystemCommands-MessageCommands/SycFindAndReplaceMethodCommand.class.st
Labels: Reviewed and Ready to Integrate

#14099 Non-Fluid class creation: use class builder, last batch
  src/Kernel/Class.class.st
  src/TraitsV2/Class.extension.st
Labels: Reviewed and Ready to Integrate

#14059 Remove some Monticello GUI
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/Monticello-GUI-Diff/MCWorkingCopyBrowser.extension.st
  src/Monticello/MCDirectoryRepository.class.st
  src/Monticello/MCRepository.class.st
  src/MonticelloGUI-Tests/MCWorkingCopyBrowserTest.class.st
  src/MonticelloGUI/MCDependentsWrapper.class.st
  src/MonticelloGUI/MCDictionaryRepository.extension.st
  src/MonticelloGUI/MCDirectoryRepository.extension.st
  src/MonticelloGUI/MCFileBasedRepository.extension.st
  src/MonticelloGUI/MCFileRepositoryInspector.class.st
  src/MonticelloGUI/MCFtpRepository.extension.st
  src/MonticelloGUI/MCHttpRepository.extension.st
  src/MonticelloGUI/MCRepository.extension.st
  src/MonticelloGUI/MCRepositoryInspector.class.st
  src/MonticelloGUI/MCSearchFacade.class.st
  src/MonticelloGUI/MCTool.class.st
  src/MonticelloGUI/MCWorkingCopyBrowser.class.st
  src/MonticelloGUI/MCWorkingHistoryBrowser.class.st
Labels: Reviewed and Ready to Integrate

#14092 Epicea: Add test on PackageAddition event
  src/Epicea-Tests/EpCodeChangeIntegrationTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyPreviewerTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers-Tests/EpRevertTest.class.st
  src/Morphic-Base/Object.extension.st
  src/Morphic-Base/StringMorph.class.st
  src/RPackage-Core/RPackageTag.class.st
  src/RPackage-Tests/RPackageOrganizerSystemTest.class.st
  src/Slot-Tests/SlotAnnouncementsTest.class.st
  src/TraitsV2-Tests/TraitFileOutTest.class.st
Labels: tests passed please review!

#14103 Updated version of graph algos to use the latest one
  src/BaselineOfDependencyAnalyzer/BaselineOfDependencyAnalyzer.class.st
Labels: tests passed please review!

#14101 Epicea: Fix application of package addition and cleanup EpPackageAddition
  src/Epicea/EpEvent.class.st
  src/Epicea/EpMonitor.class.st
  src/Epicea/EpPackageAddition.class.st
  src/Epicea/EpPackageChange.class.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers/EpApplyPreviewer.class.st
  src/EpiceaBrowsers/EpApplyVisitor.class.st
  src/EpiceaBrowsers/EpBrowseVisitor.class.st
  src/EpiceaBrowsers/EpHasImpactVisitor.class.st
  src/EpiceaBrowsers/EpInverseVisitor.class.st
  src/EpiceaBrowsers/EpMorphVisitor.class.st
  src/EpiceaBrowsers/EpNewStateVisitor.class.st
Labels: tests passed please review!

#14097 Cleanup: change method name refactoring
  src/Refactoring-Core/RBAddParameterRefactoring.class.st
  src/Refactoring-Core/RBChangeMethodNameRefactoring.class.st
  src/Refactoring-Core/RBRenameMethodRefactoring.class.st
  src/Refactoring-Core/RBReplaceMessageSendTransformation.class.st
Labels: Reviewed and Ready to Integrate

#14102 Epicea: Introduce Package removal
  src/Epicea-Tests/EpCodeChangeIntegrationTest.class.st
  src/Epicea/EpMonitor.class.st
  src/Epicea/EpPackageRemoval.class.st
  src/Epicea/EpTCodeChangeVisitor.trait.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers/EpApplyPreviewer.class.st
  src/EpiceaBrowsers/EpApplyVisitor.class.st
  src/EpiceaBrowsers/EpHasImpactVisitor.class.st
  src/EpiceaBrowsers/EpIconVisitor.class.st
  src/EpiceaBrowsers/EpInverseVisitor.class.st
  src/EpiceaBrowsers/EpMorphVisitor.class.st
  src/EpiceaBrowsers/EpNewStateVisitor.class.st
Labels: tests passed please review!

#14100 4074-Transcript-should-be-able-to-clear-the-contents-of-the-transcript
  src/Transcript-Core/ThreadSafeTranscript.class.st
Labels: Reviewed and Ready to Integrate

#14055 Added the `LinkedList>>#rechain:` method to be able to replace multiple links/adding chains in one go in the middle of the `LinkedList`
  src/Collections-Sequenceable-Tests/LinkedListTest.class.st
  src/Collections-Sequenceable/LinkedList.class.st
Labels: Reviewed and Ready to Integrate

#13947 Remove ReUtilityMethodsRule
  src/GeneralRules-Tests/ReUtilityMethodsRuleTest.class.st
  src/GeneralRules/ReUtilityMethodsRule.class.st
Labels: tests passed please review!

#13994 Move registration to SessionManager of more elements
  bootstrap/scripts/4-build.sh
  src/Collections-Weak/WeakArray.class.st
  src/FFI-Kernel/ExternalObject.class.st
  src/FFI-Kernel/FFIBackend.class.st
  src/Files/File.class.st
  src/Files/Stdio.class.st
  src/PharoBootstrap-Initialization/PharoBootstrapInitialization.class.st
  src/System-SessionManager/SessionManager.class.st
Labels: tests passed please review!

#14105 Epicea: Reduces calls to #addCategory:
  src/EpiceaBrowsers-Tests/EpApplyPreviewerTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers-Tests/EpLogBrowserOperationFactoryTest.class.st
  src/EpiceaBrowsers-Tests/EpRevertTest.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: Reviewed and Ready to Integrate

#14111 Calypso: Clean methods in protocol groups
  src/Calypso-SystemQueries-Tests/ClyAllMethodGroupsQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyClassScopeTest.class.st
  src/Calypso-SystemQueries-Tests/ClyTaggedMethodGroupProviderTest.class.st
  src/Calypso-SystemQueries/ClyMethodGroup.class.st
  src/Calypso-SystemQueries/ClyMethodsInProtocolGroup.class.st
  src/Calypso-SystemQueries/ClyNoTagMethodGroup.class.st
  src/Calypso-SystemQueries/ClyTaggedMethodGroup.class.st
  src/Calypso-SystemQueries/ClyTaggedMethodGroupProvider.class.st
  src/Calypso-SystemQueries/ClyUnclassifiedMethodGroup.class.st
  src/Calypso-SystemQueries/ClyUnclassifiedMethodGroupProvider.class.st
  src/Calypso-SystemQueries/ClyUnclassifiedMethodsQuery.class.st
  src/Calypso-SystemTools-Core/ClyClassSideLinkTableDecorator.class.st
  src/Calypso-SystemTools-Core/ClyMethodCreationToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodsInProtocolGroup.extension.st
  src/Calypso-SystemTools-FullBrowser/ClyConvertMethodGroupToTagCommand.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserContext.class.st
  src/Calypso-SystemTools-FullBrowser/ClyMoveMethodsToGroupCommand.class.st
  src/Calypso-SystemTools-FullBrowser/ClyRenameMethodTagCommand.class.st
  src/Deprecated12/ClyMethodsInProtocolGroup.extension.st
  src/SystemCommands-MethodCommands/SycAddProtocolScopeCommand.class.st
Labels: tests passed please review!

#14110 Packages should know their organizer
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: tests passed please review!

#14118 Fix #12171 remove unused methods.
  src/Kernel/Class.class.st
Labels: Reviewed and Ready to Integrate

#14121 Remove some more categories in Epicea
  src/Epicea-Tests/EpCodeChangeIntegrationTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyPreviewerTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers-Tests/EpLogBrowserOperationFactoryTest.class.st
  src/RPackage-Core/RPackage.class.st
Labels: tests passed please review!

#14096 Compiler: allow shadowing of PseudoVariables
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Tests/OCCompilerTest.class.st
  src/OpalCompiler-Tests/OpalCompilerTest.class.st
Labels: tests passed please review!

#14137 T2TraitSlotScopeTest: use classinstaller instead of class creation method
  src/TraitsV2-Tests/T2TraitSlotScopeTest.class.st
Labels: tests passed please review!, easyReview

#14126 14123-ReTestBasedTestCasesetUp-uses-old-style-class-creation-method
  src/SUnit-Rules-Tests/ReTestBasedTestCase.class.st
Labels: tests passed please review!, easyReview

#14125 Calypso: add test for trait and class creation
  src/Calypso-SystemPlugins-Traits-Queries/ClySystemEnvironment.extension.st
  src/Calypso-SystemQueries-Tests/ClySystemEnvironmentTest.class.st
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
Labels: tests passed please review!

#14124 Allow repeated file-in (Named ChangeSet)
  src/System-Changes-FileServices/ChangeSet.extension.st
  src/System-Changes/ChangeSet.class.st
Labels: tests passed please review!

#14150 fix noRemoteBlockReturn to use a known selector
  src/OpalCompiler-Tests/OCOpalExamples.class.st
Labels: tests passed please review!

#14144 Remove instance var driver
  src/Calypso-Browser/ClyBrowserToolMorph.class.st
  src/Calypso-SystemTools-FullBrowser/SycRemoveVariable2Command.extension.st
  src/Calypso-SystemTools-FullBrowser/SycRemoveVariableCommand.extension.st
  src/Refactoring-Core/RBAbstractTransformation.class.st
  src/Refactoring-Core/RBCondition.class.st
  src/Refactoring-Core/RBPushDownInstanceVariableRefactoring.class.st
  src/Refactoring-Core/RBRemoveClassRefactoring.class.st
  src/Refactoring-Core/RBRemoveInstanceVariableRefactoring2.class.st
  src/Refactoring-Core/RBSplitClassRefactoring.class.st
  src/Refactoring-Core/RBVariableRefactoring.class.st
  src/Refactoring-UI/RBBreakingChangeReport.class.st
  src/Refactoring-UI/RBDriver.class.st
  src/Refactoring-UI/RBInstanceVariableStillReferenced.class.st
  src/Refactoring-UI/RBMoveMethodsToClassSideDriver.class.st
  src/Refactoring-UI/RBRemoveInstanceVariableDriver.class.st
  src/Refactoring-UI/StRefactoringPreviewPresenter.class.st
  src/Refactoring2-Transformations-Tests/RBRemoveInstanceVariable2ParametrizedTest.class.st
  src/SystemCommands-ClassCommands/SycGenerateAllInstVarAccessorsCommand.class.st
  src/SystemCommands-VariableCommands/SycRemoveVariable2Command.class.st
  src/SystemCommands-VariableCommands/SycRemoveVariableCommand.class.st
  src/SystemCommands-VariableCommands/SycVariableCommand.class.st
Labels: tests passed please review!

#14135 14133-CompiledCode-improve-and-add-tests-for-user-flag
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/Kernel/CompiledBlock.class.st
  src/Kernel/CompiledCode.class.st
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!
