Repository pharo-project/pharo, pull requests merged in 2023-05, with the labels that each got.

#13603 extract return from ifTrue:ifFalse: expression
  src/AST-Core/RBSequenceNode.class.st
Labels: Reviewed and Ready to Integrate

#13541 Compiler: do generation
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
Labels: Reviewed and Ready to Integrate

#13605 Remove ClassOrganization>>#protocolNameOfElement:ifAbsent:
  src/Deprecated12/ClassOrganization.extension.st
  src/Kernel/ClassOrganization.class.st
  src/Refactoring-Environment/RBBrowserEnvironment.class.st
Labels: tests passed please review!

#13601 extract return from ifTrue:ifFalse: expression
  src/Kernel-Tests-Extended/SizeInMemoryTest.class.st
Labels: Reviewed and Ready to Integrate

#13604 Simplify classify:under:
  src/Kernel/ClassOrganization.class.st
Labels: tests passed please review!

#13622 Remove some dead code in ChangeSet
  src/System-Changes/ChangeSet.class.st
Labels: Reviewed and Ready to Integrate

#13606 Compiler: get requestor
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: Reviewed and Ready to Integrate

#13621 Do not reclassify already classified method
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassOrganization.class.st
Labels: Reviewed and Ready to Integrate

#13625 Code Completion: multiple fixes on replacements annoying bugs
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion-Tests/CompletionEngineTest.class.st
Labels: tests passed please review!

#13627 HEInstaller should take the trailerSize into account
  src/Hermes/HEInstaller.class.st
  src/Kernel/Object.class.st
Labels: tests passed please review!

#13557 AST: add a scanner state
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core/RBNotice.class.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBPatternParser.class.st
  src/AST-Core/RBScanner.class.st
Labels: tests passed please review!

#13580 Set #trailerSize to 5
  src/Kernel/CompiledMethod.class.st
Labels: Need more work

#13590 Clean blocks for announcement
  doc/Announcements/Announcements.md
  src/Announcements-Core-Tests/AnnouncerSubscriberMockA.class.st
  src/Announcements-Core-Tests/AnnouncerTest.class.st
  src/Announcements-Core-Tests/WeakAnnouncerTest.class.st
  src/Announcements-Core/Announcer.class.st
  src/Announcements-Core/WeakAnnouncementSubscription.class.st
  src/Announcements-Core/WeakSubscriptionBuilder.class.st
  src/Clap-Commands-Pharo/ClapTestRunner.class.st
  src/Deprecated11/package.st
  src/Deprecated12/Announcer.extension.st
  src/Deprecated12/ToolRegistry.extension.st
  src/Deprecated12/WeakSubscriptionBuilder.extension.st
  src/DrTests-CommentsToTests/DTCommentToTestPlugin.class.st
  src/DrTests-TestCoverage/DTTestCoveragePlugin.class.st
  src/DrTests-TestsRunner/DTTestsRunnerPlugin.class.st
  src/Monticello-Tests/RPackageClassesSynchronisationTest.class.st
  src/Monticello-Tests/RPackageMCSynchronisationTest.class.st
  src/Morphic-Core/Morph.class.st
  src/Morphic-Tests/WindowAnnouncementTest.class.st
  src/NewValueHolder-Core/CollectionValueHolder.class.st
  src/OSWindow-Core/GLMOSWindowWorldMorph.class.st
  src/Ombu-Tests/OmSessionStoreTest.class.st
  src/Polymorph-Widgets/MorphicUIManager.class.st
  src/RPackage-Tests/RPackageTest.class.st
  src/Ring-Tests-Core/RGAnnouncementsTest.class.st
  src/SUnit-Core/TestSuite.class.st
  src/SUnit-Tests/TestCaseTest.class.st
  src/SUnit-UI/TestRunner.class.st
  src/System-Announcements-Tests/SystemAnnouncerTest.class.st
  src/System-Model/Model.class.st
  src/Tool-Registry/ToolRegistry.class.st
  src/Zinc-HTTP/ZnLogEvent.class.st
Labels: Reviewed and Ready to Integrate, cleanblocks

#13632 Remove references to SystemOrganization
  bootstrap/scripts/emulation/shrink.st
  bootstrap/scripts/generateKernelHermesFiles.st
  bootstrap/scripts/generateSUnitHermesFiles.st
  bootstrap/scripts/generateTraitsHermesFiles.st
  src/GeneralRules/ReGlobalVariablesUsageRule.class.st
  src/Pharo30Bootstrap/PBBootstrap.class.st
Labels: tests passed please review!

#13636 Completion: prepare for empty token
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion-Tests/CompletionEngineTest.class.st
  src/Rubric/RubSmalltalkEditor.class.st
Labels: tests passed please review!

#13635 Ensure #addSelector:withMethod: classifies methods
  src/Kernel-Tests/ClassDescriptionTest.class.st
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#13637 Complete super message send
  src/HeuristicCompletion-Model/CoSuperMessageHeuristic.class.st
Labels: Reviewed and Ready to Integrate

#13373 ClassOrganization classification cleanings
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassOrganization.class.st
Labels: tests passed please review!

#13403 Make Smalltalk environnement return a RPackageOrganizer
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageOrganizerSystemTest.class.st
  src/System-Support-Tests/SystemDictionaryTest.class.st
  src/System-Support-Tests/SystemOrganizerTest.class.st
  src/System-Support/SystemDictionary.class.st
Labels: tests passed please review!

#13650 Do not classify silently methods
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassOrganization.class.st
  src/TraitsV2/TaAbstractComposition.class.st
Labels: tests passed please review!

#13649 Start protocol announcements testing + add feature to Announcer
  src/Announcements-Core-Tests/AnnouncerTest.class.st
  src/Announcements-Core/Announcer.class.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel-Tests/ProtocolAnnouncementsTest.class.st
  src/Kernel-Tests/ProtocolTest.class.st
  src/Kernel/ClassOrganization.class.st
Labels: tests passed please review!

#13664 Fix bug (issue #13663): enabling the setting ‘Show lines numbers for all browsers’ only showed line numbers for the first method selected in a class
  src/Calypso-Browser/ClyTextLineNumbersSwitchMorph.class.st
Labels: Reviewed and Ready to Integrate

#13666 Reduces the references to RPackageOrganizer class>>default
  src/Epicea/EpMonitor.class.st
  src/FluidClassBuilder-Tests/FluidClassBuilderTest.class.st
  src/Monticello-Tests/MCWorkingCopyForExtensionsTest.class.st
  src/Monticello/MCPackage.class.st
  src/Monticello/MCPackageManager.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Core/String.extension.st
  src/RPackage-Tests/RPackageOrganizerAndSystemOrganizeSynchTest.class.st
  src/RPackage-Tests/RPackageOrganizerSystemTest.class.st
  src/RPackage-Tests/RPackageRenameTest.class.st
  src/RPackage-Tests/RPackageTest.class.st
  src/RPackage-Tests/RPackageTraitTest.class.st
  src/RPackage-Tests/RPackageWithDoTest.class.st
  src/ReleaseTests/ProperPackagesTest.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/Shift-ClassInstaller-Tests/ShAnonymousClassInstallerTest.class.st
  src/System-Settings-Tests/SettingBrowserTest.class.st
  src/Tool-DependencyAnalyser-Tests/DATarjanAlgorithmTest.class.st
  src/Tool-DependencyAnalyser/DAMessageSendAnalyzer.class.st
  src/Tool-DependencyAnalyser/DAPackageRelationGraph.class.st
  src/TraitsV2-Tests/T2TraitWithPackagesTest.class.st
Labels: tests passed please review!

#13665 Backport fixe #13663
  src/Calypso-Browser/ClyTextLineNumbersSwitchMorph.class.st
Labels: tests passed please review!

#13642 Small cleanup on protocol cleaning
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassOrganization.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/TraitsV2/TraitBuilderEnhancer.class.st
Labels: Reviewed and Ready to Integrate

#13671 Use Smalltalk organization in DependencyAnalyzer
  src/Tool-DependencyAnalyser-UI/DAAddPackagePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DACycleDetectionTreePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DADependencyTreePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAPackageAnalyzerPresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAPackageDependenciesPresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAWelcomePresenter.class.st
  src/Tool-DependencyAnalyser/DADependencyChecker.class.st
  src/Tool-DependencyAnalyser/DAMessageSendAnalyzer.class.st
  src/Tool-DependencyAnalyser/DAPackageCycleDetector.class.st
Labels: tests passed please review!

#13669 Use real protocol in recategorization mecanism
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/SystemCommands-MessageCommands/SycInlineAllSendersMessageCommand.class.st
  src/TraitsV2/MetaclassForTraits.class.st
  src/TraitsV2/Trait.class.st
  src/TraitsV2/TraitedClass.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: tests passed please review!

#13670 Rename Protocol class>>#name: into #named:
  src/Kernel/ClassOrganization.class.st
  src/Kernel/Protocol.class.st
Labels: tests passed please review!

#13647 Completion autoclose menu
  src/HeuristicCompletion-Model/CoCompletionContext.class.st
  src/HeuristicCompletion-Tests/CoCompletionEngineTest.class.st
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion/CompletionContext.class.st
Labels: tests passed please review!

#13658 Introduce ClassDescription>>#protocolNames and start using it
  src/Collections-Sequenceable-Tests/OrderedDictionaryTest.class.st
  src/Collections-Unordered-Tests/DictionaryTest.class.st
  src/FuzzyMatcher-Tests/FuzzyMatcherTest.class.st
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Monticello/MCPackageManager.class.st
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
  src/ReleaseTests/ProtocolConventionsTest.class.st
  src/Ring-Core/RGReadOnlyImageBackend.class.st
  src/Ring-Definitions-Core/Behavior.extension.st
  src/Ring-Definitions-Core/ClassDescription.extension.st
  src/Ring-Tests-Core/RGReadOnlyImageBackendTest.class.st
  src/System-Support-Tests/SystemNavigationTest.class.st
  src/System-Support/SystemNavigation.class.st
  src/SystemCommands-RefactoringSupport/RBEnvironmentVisitor.class.st
  src/Tool-ExternalBrowser/ExternalBrowser.class.st
Labels: tests passed please review!

#13668 Clean some code using better condition branches
  src/Kernel/Behavior.class.st
  src/Kernel/ClassDescription.class.st
  src/Refactoring-Core/RBAbstractClass.class.st
  src/Refactoring-Critics/RBSmalllintContext.class.st
  src/System-Changes/ChangeSet.class.st
Labels: tests passed please review!

#13661 Added `thisProcess` pseudovariable using existing bytecode.
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core/RBVariableNode.class.st
  src/Kernel/DoItVariable.class.st
  src/Kernel/Slot.class.st
  src/Kernel/ThisProcessVariable.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Tests/OpalCompilerTest.class.st
  src/Shout-Tests/SHRBMockTextStyler.class.st
  src/Shout-Tests/SHRBStyleAttributionTest.class.st
  src/Shout/SHRBTextStyler.class.st
  src/Shout/ThisProcessVariable.extension.st
  src/Slot-Tests/SlotErrorsTest.class.st
Labels: tests passed please review!

#13683 Completion: replacement put caret at the right place
  src/HeuristicCompletion-Tests/CoCompletionEngineTest.class.st
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion-Tests/CompletionEngineTest.class.st
Labels: tests passed please review!

#13689 Improve some error logging
  src/Kernel/Object.class.st
  src/Kernel/SubscriptOutOfBounds.class.st
Labels: Reviewed and Ready to Integrate

#13687 Basic type analysis for better completion
  src/AST-Core-Tests/ASTTypingVisitorTest.class.st
  src/AST-Core/ASTTypingVisitor.class.st
  src/HeuristicCompletion-Model/CoASTHeuristicsResultSetBuilder.class.st
  src/HeuristicCompletion-Model/CoASTResultSetBuilder.class.st
  src/HeuristicCompletion-Model/CoTypedReceiverMessageHeuristic.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/LocalVariable.class.st
Labels: Reviewed and Ready to Integrate

#13696 Completion mini fixes
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion-Tests/CompletionEngineTest.class.st
  src/NECompletion/NECSelectorEntry.class.st
Labels: tests passed please review!

#13697 More type analysis
  src/AST-Core-Tests/ASTTypingVisitorTest.class.st
  src/AST-Core/ASTTypingVisitor.class.st
Labels: tests passed please review!

#13701 Simplify ReservedVariable: #styleNameIn and remove #nameIsReserved:
  src/Kernel/ReservedVariable.class.st
  src/Ring-Core/RGEnvironment.class.st
  src/Ring-Tests-Core/RGReadOnlyImageBackendTest.class.st
  src/Shout/ReservedVariable.extension.st
  src/Shout/SelfVariable.extension.st
  src/Shout/SuperVariable.extension.st
  src/Shout/ThisContextVariable.extension.st
  src/Shout/ThisProcessVariable.extension.st
  src/Slot-Tests/ReservedVariableTest.class.st
Labels: Reviewed and Ready to Integrate

#13699 Completion browse with Ctrl-B
  src/Calypso-Browser/ClyTextEditor.class.st
  src/Calypso-Browser/Object.extension.st
  src/HeuristicCompletion-Tests/CoCompletionEngineTest.class.st
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion-Morphic/NECDetailMorph.class.st
  src/NECompletion-Morphic/NECMenuMorph.class.st
  src/NECompletion-Preferences/NECPreferences.class.st
  src/Rubric/RubSmalltalkEditor.class.st
Labels: tests passed please review!

#13700 Completion: better update
  src/HeuristicCompletion-Model/CoCompletionContext.class.st
  src/HeuristicCompletion-Tests/CoMockEngine.class.st
  src/NECompletion-Morphic/CompletionEngine.class.st
Labels: tests passed please review!

#13690 Remove SystemOrganizer
  src/CodeExport/RPackageOrganizer.extension.st
  src/CodeExport/SystemOrganizer.extension.st
  src/Deprecated12/SystemOrganizer.extension.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Core/SystemOrganizer.class.st
  src/RPackage-Tests/RPackageOrganizerAndSystemOrganizeSynchTest.class.st
Labels: tests passed please review!

#13566 add object to represent the Native Window
  src/Morphic-Base/DeleteWindowByCrossAnnouncement.class.st
  src/Morphic-Base/MorphicNativeWindow.class.st
  src/Morphic-Base/MorphicWindowManager.class.st
  src/Morphic-Base/WindowTitleAnnouncement.class.st
  src/Morphic-Core/NullWorldRenderer.class.st
  src/Morphic-Tests/AbstractWindowManagerTest.class.st
  src/Morphic-Tests/MorphicNativeWindowTest.class.st
  src/Morphic-Tests/MorphicWindowManagerTest.class.st
  src/Morphic-Widgets-Taskbar/TaskbarMorph.class.st
  src/Morphic-Widgets-Taskbar/TaskbarMorphForManager.class.st
  src/OSWindow-Core/OSWindow.class.st
  src/OSWindow-Core/OSWindowAttributes.class.st
  src/OSWindow-Core/OSWorldRenderer.class.st
Labels: Need more work

#13737 Compiler: remove #lookupVar:declare:
  src/Debugging-Core/Context.extension.st
  src/OpalCompiler-Core/Behavior.extension.st
  src/Ring-Core/RGBehavior.class.st
  src/System-Support/SystemDictionary.class.st
Labels: Reviewed and Ready to Integrate

#13738 Cleanup-MetacelloPharoPlatform
  src/Metacello-Core/MetacelloPlatform.class.st
  src/Metacello-PharoCommonPlatform/FileReference.extension.st
  src/Metacello-PharoCommonPlatform/MetacelloPharoCommonPlatform.class.st
  src/Metacello-Platform/MetacelloPharoPlatform.class.st
Labels: Reviewed and Ready to Integrate

#13739 13723-Binding-for-variable-in-Playground-is-nil-after-assigning-a-number-to-it
  src/OpalCompiler-Core/OCRequestorScope.class.st
Labels: Reviewed and Ready to Integrate

#13736 remove Object bindingOf: and hasBindingOf:
  src/HeuristicCompletion-Tests/CoCompletionEngineTest.class.st
  src/Kernel/Behavior.class.st
  src/Kernel/Object.class.st
  src/Rubric/RubEditingArea.class.st
Labels: tests passed please review!

#13748 Inline ClassOrganization>>#removeElement: in ClassDescription
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/TraitsV2/TraitChange.class.st
  src/TraitsV2/TraitedClass.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: tests passed please review!

#13753 Inline protocol removal from ClassOrganization
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/Deprecated12/ClassOrganization.extension.st
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/System-Support/SmalltalkImage.class.st
  src/SystemCommands-ClassCommands/SycRemoveEmptyMethodTagsCommand.class.st
  src/SystemCommands-MethodCommands/SycMoveMethodsToClassCommand.class.st
  src/SystemCommands-MethodCommands/SycMoveMethodsToPackageCommand.class.st
  src/Tool-ImageCleaner/ImageCleaner.class.st
  src/TraitsV2/TraitBuilderEnhancer.class.st
Labels: tests passed please review!

#13759 Clean the way to get the selectors in a protocol
  src/AST-Core/RBMessageNode.class.st
  src/Collections-Sequenceable-Tests/OrderedDictionaryTest.class.st
  src/Deprecated12/ClassDescription.extension.st
  src/Deprecated12/ClassOrganization.extension.st
  src/EpiceaBrowsers/EpHasImpactVisitor.class.st
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/Morphic-Examples/PackageClassNodeExample.class.st
  src/Morphic-Examples/PackageMethodCategoryNodeExample.class.st
  src/OpalCompiler-Tests/MethodPragmaTest.class.st
  src/Refactoring-Environment/RBBrowserEnvironment.class.st
  src/Refactoring-Environment/RBNotEnvironment.class.st
  src/Ring-Core/RGEnvironmentAnnouncer.class.st
  src/SUnit-Core/ClassTestCase.class.st
Labels: tests passed please review!

#13770 Fix: `RBClassRegexRefactoring`
  src/Refactoring-Core/RBClassRegexRefactoring.class.st
Labels: tests passed please review!

#13774 Remove dead method ClassDescription>>#zapOrganization
  src/Kernel/ClassDescription.class.st
Labels: tests passed please review!

#13778 Fix #13478: Filter on `calypsoName` instead of `name`
  src/Calypso-NavigationModel/Class.extension.st
  src/Calypso-NavigationModel/ClyBrowserItem.class.st
  src/Calypso-NavigationModel/ClyItemNameFilter.class.st
  src/Calypso-NavigationModel/CompiledMethod.extension.st
  src/Calypso-NavigationModel/RPackage.extension.st
Labels: Reviewed and Ready to Integrate

#13787 Improve CoverageCollectorTest assertions
  src/Coverage/CoverageCollectorTest.class.st
Labels: Reviewed and Ready to Integrate

#13789 Migrate variables of VariableLayout only if old instance was also variable
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
Labels: Reviewed and Ready to Integrate

#13786 Add tests for Calypso's item filter
  src/Calypso-NavigationModel-Tests/ClyItemNameFilterTest.class.st
Labels: Reviewed and Ready to Integrate

#13756 Merge SHTextStyler and SHRBTextStyler
  src/Shout/SHRBTextStyler.class.st
  src/Shout/SHTextStyler.class.st
  src/SystemCommands-ClassCommands-Tests/SycRemoveClassStrategyTest.class.st
Labels: Reviewed and Ready to Integrate

#13809 Fix completion tests after p11 synch
  src/NECompletion-Morphic/CompletionEngine.class.st
Labels: tests passed please review!

#13794 Backport fix to calypso method search
  src/Calypso-NavigationModel-Tests/ClyItemNameFilterTest.class.st
  src/Calypso-NavigationModel/Class.extension.st
  src/Calypso-NavigationModel/ClyBrowserItem.class.st
  src/Calypso-NavigationModel/ClyItemNameFilter.class.st
  src/Calypso-NavigationModel/CompiledMethod.extension.st
  src/Calypso-NavigationModel/RPackage.extension.st
Labels: Reviewed and Ready to Integrate, pharo11

#13811 FIx DebugSession test
  src/Debugger-Model/DebugSession.class.st
Labels: tests passed please review!

#13815 Enhance logs
  bootstrap/scripts/transform_32_into_64.sh
Labels: Annoying

#13792 Inline ClassOrganization>>#protocolNamed:[ifAbsent:]
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel-Tests/ProtocolAnnouncementsTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/RPackage-Core/RPackage.class.st
  src/Refactoring2-Transformations-Tests/RBMethodProtocolTransformationTest.class.st
  src/Refactoring2-Transformations/RBRemoveProtocolTransformation.class.st
  src/UnifiedFFI/FFIStructure.class.st
Labels: tests passed please review!

#13693 Add highlight text color to theme for debugger stack coloring
  src/Polymorph-Widgets/DarkThemeColorConfigurator.class.st
  src/Polymorph-Widgets/UITheme.class.st
  src/Polymorph-Widgets/UIThemeColorConfigurator.class.st
  src/Polymorph-Widgets/UIThemePalette.class.st
Labels: Reviewed and Ready to Integrate

#13777 Add #getTemporaryDirectory to UnixPlatform and WinPlatform
  src/FileSystem-Core/UnixResolver.class.st
  src/FileSystem-Core/WindowsResolver.class.st
  src/FileSystem-Tests-Core/UnixResolverTest.class.st
  src/FileSystem-Tests-Core/WindowsResolverTest.class.st
  src/System-OSEnvironments-Tests/OSEnvironmentTest.class.st
  src/System-OSEnvironments/OSEnvironment.class.st
  src/System-Platforms-Tests/Win32EnvironmentTest.class.st
  src/System-Platforms-Tests/Win32WideStringTest.class.st
  src/System-Platforms-Tests/WinPlatformTest.class.st
  src/System-Platforms/WinPlatform.class.st
Labels: tests passed please review!

#13824 Change `Object>>#split:` definition as recomended by pharo-project/Pharo#13656
  src/Collections-Abstract/Object.extension.st
Labels: Reviewed and Ready to Integrate

#13826 Move CompiledMethod>> basicNew: and basicNew to CompiledCode
  src/Kernel/CompiledCode.class.st
  src/Kernel/CompiledMethod.class.st
Labels: Reviewed and Ready to Integrate

#13819 delete unneeded tools registry redefinition
  src/Tool-Base/ToolShortcutsCategory.class.st
Labels: tests passed please review!

#13820 Clean Form magnifying
  src/Graphics-Display Objects/Form.class.st
  src/Graphics-Fonts/StrikeFont.class.st
  src/Morphic-Base/AlphaImageMorph.class.st
  src/Morphic-Base/Form.extension.st
  src/Morphic-Base/Object.extension.st
  src/Morphic-Base/ThumbnailMorph.class.st
  src/Polymorph-Widgets/UITheme.class.st
Labels: tests passed please review!

#13829 13797-Monticello-can-not-create-the-class-CompileCode-subclasses
  src/Monticello/MCClassDefinition.class.st
Labels: Reviewed and Ready to Integrate

#13812 Compile 'thisContext' (and all other PseudoVariables) as DoitVariable in DoIts
  src/AST-Core-Tests/ASTEvaluationTest.class.st
  src/Kernel/ReservedVariable.class.st
  src/Slot-Tests/ReservedVariableTest.class.st
  src/Slot-Tests/ThisContextVariableTest.class.st
Labels: tests passed please review!

#13767 Remove unused UITheme forms and add support for scale 2.0 icons
  src/Polymorph-Widgets/ThemeIcons.class.st
  src/Polymorph-Widgets/UITheme.class.st
Labels: tests passed please review!

#13834 Less subclass: instancevariablenames: ....
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel/Class.class.st
  src/RPackage-Tests/RPackageRenameTest.class.st
  src/Reflectivity-Tests/VariableBreakpointTest.class.st
  src/Slot-Tests/SlotIntegrationTest.class.st
  src/UndefinedClasses/UndefinedClass.class.st
Labels: Reviewed and Ready to Integrate

#13837 Fix for 13767
  src/Polymorph-Widgets/ThemeIcons.class.st
Labels: more-information-needed

#13844 Remove FLPharo11Platform
  src/Fuel-Platform-Pharo-12/FLPharo11Platform.class.st
Labels: tests passed please review!

#13843 Inline ClassOrganization>>classify:under:
  src/Fuel-Platform-Core/FLExtensionWrapper.class.st
  src/Fuel-Platform-Pharo-12/FLPharo12Platform.class.st
  src/InitializePackagesCommandLineHandler/InitializePackagesCommandLineHandler.class.st
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel-Tests/ProtocolAnnouncementsTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/Kernel/CompiledMethod.class.st
  src/Monticello-Tests/RPackageMCSynchronisationTest.class.st
  src/Monticello-Tests/RPackageMethodsSynchronisationTest.class.st
  src/Monticello/MethodAddition.class.st
  src/RPackage-Tests/RPackageTest.class.st
  src/TraitsV2-Tests/T2TraitWithCategoriesTest.class.st
  src/TraitsV2-Tests/TraitMethodDescriptionTest.class.st
  src/TraitsV2-Tests/TraitPureBehaviorTest.class.st
  src/TraitsV2/TaAbstractComposition.class.st
  src/TraitsV2/TraitedClass.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: tests passed please review!

#13827 Fix/13718: Installing a version of a class method adds an instance method
  src/Ring-Definitions-Core/RGElementDefinition.class.st
  src/Ring-Definitions-Tests-Monticello/RGContainerTest.extension.st
  src/Ring-Definitions-Tests-Monticello/RGMethodDefinitionTest.extension.st
Labels: tests passed please review!

#13846 Fix bug in Epicea
  src/Epicea/EpMonitor.class.st
Labels: tests passed please review!

#13845 Mulitple cleanups for ClassOrganization inlining
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel-Tests/ClassDescriptionTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
Labels: tests passed please review!

#13857 Fix bug in Epicea management
  src/Calypso-SystemQueries/MethodRecategorized.extension.st
  src/Epicea/EpMonitor.class.st
  src/Monticello-Tests/RPackageExtensionMethodsSynchronisationTest.class.st
Labels: tests passed please review!

#13859 fix variable names in BlockClosureTest
  src/Kernel-Tests-Extended/BlockClosureTest.extension.st
  src/Kernel-Tests/BlockClosureTest.class.st
Labels: Reviewed and Ready to Integrate

#13674 ClassDescription>>protocols should return protocols
  src/Calypso-SystemQueries/ClassDescription.extension.st
  src/Calypso-SystemQueries/TraitedMetaclass.extension.st
  src/CodeExport/ClassDescription.extension.st
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Monticello/MCClassDefinition.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
  src/Ring-Definitions-Core/ClassDescription.extension.st
Labels: tests passed please review!

#13860 Remove unecessary cleanup in Gofer
  src/Gofer-Core/GoferCleanup.class.st
  src/Gofer-Core/RPackageSet.extension.st
  src/Metacello-TestsMC/Gofer.extension.st
  src/Metacello-TestsMC/MetacelloTestsGoferCleanup.class.st
  src/Metacello-TestsMC/MetacelloTestsGoferUnload.class.st
Labels: tests passed please review!

#13618 First step at class name deprecation
  src/Kernel-Tests/ClassDescriptionTest.class.st
  src/Kernel/Class.class.st
  src/Kernel/ClassDescription.class.st
Labels: Reviewed and Ready to Integrate

#13821 Avoid NewUndeclaredWarning when loading RingChunkImporter
  src/BaselineOfMonticello/BaselineOfMonticello.class.st
Labels: Reviewed and Ready to Integrate

#13833 little cleaning and optimization
  src/Colors/Color.class.st
  src/Colors/ColorMap.class.st
Labels: Reviewed and Ready to Integrate

#13862 Fix bug in slot names
  src/Slot-Tests/SlotClassVariableTest.class.st
Labels: tests passed please review!

#13863 Remove some organization references
  src/CodeExport/ClassDescription.extension.st
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel/ClassDescription.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageSet.class.st
  src/Refactoring-Changes/RBRemoveProtocolChange.class.st
  src/System-Announcements-Tests/SystemAnnouncerTest.class.st
Labels: tests passed please review!

#13798 Disable Epicea debug mode in tests
  src/Epicea/EpMonitor.class.st
Labels: tests passed please review!

#13855 13591-Clean-Blocks-self-is-nil-on-Debugger
  src/Kernel/Context.class.st
  src/Kernel/SelfVariable.class.st
  src/Kernel/SuperVariable.class.st
  src/Kernel/ThisContextVariable.class.st
  src/Slot-Tests/SelfVariableTest.class.st
Labels: tests passed please review!

#13850 Fix System Browser tables scaling
  src/Calypso-Browser/ClyMainItemCellMorph.class.st
  src/Calypso-SystemPlugins-InheritanceAnalysis-Browser/ClyOverriddenMethodTableDecorator.class.st
  src/Morphic-Core/BorderStyle.class.st
  src/Morphic-Widgets-Basic/IconicButtonMorph.class.st
  src/Morphic-Widgets-FastTable/FTTreeDataSource.class.st
Labels: tests passed please review!

#13229 FFI: Add +optAutoReleaseReturnedValue option
  src/UnifiedFFI-Tests/FFIAutoReleaseOptionCalloutTest.class.st
  src/UnifiedFFI/ExternalObject.extension.st
  src/UnifiedFFI/FFICallbackType.class.st
  src/UnifiedFFI/FFICallout.class.st
  src/UnifiedFFI/FFICharacterType.class.st
  src/UnifiedFFI/FFIExternalReferenceType.class.st
  src/UnifiedFFI/FFIExternalResourceManager.class.st
  src/UnifiedFFI/FFIExternalStructureType.class.st
  src/UnifiedFFI/FFIVoid.class.st
Labels: tests passed please review!

#13864 Compiler-canAddBindingOf-Check-Synthezised
  src/OpalCompiler-Core/OCRequestorScope.class.st
  src/OpalCompiler-Tests/OCDoitTest.class.st
Labels: Reviewed and Ready to Integrate
