Repository pharo-project/pharo, pull requests merged in 2023-10, with the labels that each got.

#14835 Refactor Pragma
  src/Kernel/Pragma.class.st
Labels: Cleanup

#14852 Refactoring: Get away from class definition
  src/Refactoring-Changes/RBAddClassChange.class.st
  src/Refactoring-Changes/RBAddClassTraitChange.class.st
  src/Refactoring-Changes/RBAddMetaclassChange.class.st
  src/Refactoring-Changes/RBAddTraitChange.class.st
  src/Refactoring-Changes/RBRefactoryChangeFactory.class.st
  src/Refactoring-Changes/RBRefactoryDefinitionChange.class.st
  src/Refactoring-Changes/RBRemoveClassChange.class.st
  src/Refactoring-Changes/SystemDictionary.extension.st
  src/Refactoring-Core/RBClass.class.st
  src/Refactoring-Core/RBClassRegexRefactoring.class.st
  src/Refactoring-Core/RBCondition.class.st
  src/Refactoring-Core/RBInsertNewClassRefactoring.class.st
  src/Refactoring-Core/RBNamespace.class.st
  src/Refactoring-Core/RBUpFrontPreconditionCheckingCompositeRefactoring.class.st
  src/Refactoring-Environment/RBPackageEnvironment.class.st
  src/Refactoring-Tests-Changes/RBRefactoringChangeTest.class.st
  src/Refactoring-Tests-Core/RBClassTest.class.st
  src/Refactoring-Tests-Core/RBConditionTest.class.st
  src/Refactoring-Tests-Core/RBNamespaceTest.class.st
  src/Refactoring-Tests-Core/RBSharedPoolTest.class.st
  src/Refactoring2-Transformations-Tests/RBAbstractEnvTestCase.class.st
  src/Refactoring2-Transformations-Tests/RBAddInstanceVariableParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBAddInstanceVariableRefactoringTest.class.st
  src/Refactoring2-Transformations-Tests/RBChildrenToSiblingsParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBCopyPackageParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBDeprecateClassParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBInlineMethodParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBPullUpMethodParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBPushDownClassVariableParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBPushDownClassVariableRefactoringTest.class.st
  src/Refactoring2-Transformations-Tests/RBPushDownInstanceVariableParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBPushDownMethodRefactoringTest.class.st
  src/Refactoring2-Transformations-Tests/RBRemoveInstanceVariable2ParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBRenameClassRefactoringTest.class.st
  src/Refactoring2-Transformations-Tests/RBTemporaryToInstanceVariableParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBTransformationsTest.class.st
  src/Refactoring2-Transformations/RBInsertNewClassTransformation.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
Labels: tests passed please review!

#14853 Defer change list update to avoid a race condition
  src/EpiceaBrowsers/EpLogBrowserPresenter.class.st
Labels: tests passed please review!

#14855 Remove some unused methods from the Canvas hierarchy
  src/FormCanvas-Core/FormCanvas.class.st
  src/Graphics-Canvas/Canvas.class.st
  src/Graphics-Canvas/ClippingCanvas.class.st
  src/Graphics-Canvas/PluggableCanvas.class.st
Labels: tests passed please review!

#14856 Ring-Cleanup-isMetaSide
  src/Epicea/CompiledMethod.extension.st
  src/Epicea/TestCase.extension.st
  src/Manifest-Core/RGMethodDefinition.extension.st
  src/Manifest-Tests/RGMethodDefinitionTest.extension.st
  src/Monticello/RGMethodDefinition.extension.st
  src/Ring-Core/RGMethod.class.st
  src/Ring-Definitions-Core/ChangeRecord.extension.st
  src/Ring-Definitions-Core/CompiledMethod.extension.st
  src/Ring-Definitions-Core/RGClassInstanceVariableDefinition.class.st
  src/Ring-Definitions-Core/RGElementDefinition.class.st
  src/Ring-Definitions-Core/RGMethodDefinition.class.st
  src/Ring-Definitions-Monticello/MCMethodDefinition.extension.st
  src/Ring-Definitions-Monticello/RGMethodDefinition.extension.st
  src/Ring-Definitions-Tests-Core/RGClassDefinitionTest.class.st
  src/Ring-Definitions-Tests-Core/RGMethodDefinitionTest.class.st
  src/Ring-Definitions-Tests-Core/RGTraitDefinitionTest.class.st
  src/Ring-Definitions-Tests-Core/RGVariableDefinitionTest.class.st
  src/Ring-OldChunkImporter/RingChunkImporter.class.st
  src/Ring-Tests-Core/RGMethodTest.class.st
  src/System-Changes/ChangeSet.class.st
  src/System-Changes/SourceFileArray.extension.st
Labels: tests passed please review!

#14861 Bootstrap: Add logs to early steps of the bootstrap
  src/Pharo30Bootstrap/PBBootstrapLogger.class.st
  src/Pharo30Bootstrap/PBImageBuilder50.class.st
  src/Pharo30Bootstrap/PBImageBuilderSpur50.class.st
Labels: tests passed please review!

#14857 Monticello: Simplify classRemoved:
  src/Monticello/MCWorkingCopy.class.st
Labels: tests passed please review!

#14873 speedup-runtimeUndeclaredRead
  src/Kernel/LiteralVariable.class.st
Labels: tests passed please review!

#14872 Fix Deprecation for methods that use #runtimeUndeclaredRead
  src/AST-Core/CompiledMethod.extension.st
Labels: tests passed please review!

#14870 EDDebuggingAPI: use #changeRecordsFor:
  src/EmergencyDebugger/EDDebuggingAPI.class.st
Labels: tests passed please review!, easyReview

#14866 10094-SourceFileArraychangeRecordsFordo-is-Ring1-specific
  src/Monticello/MCMethodDefinition.class.st
  src/System-Changes/SourceFileArray.extension.st
Labels: tests passed please review!

#14877 Remove usage of #category: in trait tests
  src/TraitsV2-Tests/T2TraitChangesTest.class.st
  src/TraitsV2-Tests/T2TraitSlotScopeTest.class.st
Labels: tests passed please review!

#14875 RPackage: Simplify tests and fix bug in package removal
  src/Deprecated12/RPackage.extension.st
  src/Deprecated12/RPackageTag.extension.st
  src/Monticello-Tests/MCClassDefinitionTest.class.st
  src/Monticello-Tests/MCTestCase.class.st
  src/Monticello-Tests/RPackageMCSynchronisationTest.class.st
  src/Monticello-Tests/RPackageMonticelloSynchronisationTest.class.st
  src/RPackage-Core/PackageRenamed.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Core/RPackageTag.class.st
  src/RPackage-Tests/RPackageClassesSynchronisationTest.class.st
  src/RPackage-Tests/RPackageExtensionMethodsSynchronisationTest.class.st
  src/RPackage-Tests/RPackageIncrementalTest.class.st
  src/RPackage-Tests/RPackageMethodsSynchronisationTest.class.st
  src/RPackage-Tests/RPackageSynchronisationTest.class.st
  src/RPackage-Tests/RPackageTagTest.class.st
  src/RPackage-Tests/RPackageTestCase.class.st
  src/RPackage-Tests/RPackageTraitSynchronisationTest.class.st
Labels: tests passed please review!

#14879 RPackage: remove private import method
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Tests/RPackageIncrementalTest.class.st
  src/RPackage-Tests/RPackageReadOnlyCompleteSetupTest.class.st
  src/RPackage-Tests/RPackageTest.class.st
Labels: tests passed please review!

#14880 Change set should not depend on ClassRecategorized
  src/System-Changes/ChangeSet.class.st
Labels: easyReview

#14883 RPackage: New step at cleaning tests
  src/RPackage-Core/ClassDescription.extension.st
  src/RPackage-Tests/PackageAnnouncementsTest.class.st
  src/RPackage-Tests/RPackageClassesSynchronisationTest.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
  src/RPackage-Tests/RPackageTagTest.class.st
  src/RPackage-Tests/RPackageTest.class.st
  src/RPackage-Tests/RPackageTestCase.class.st
  src/RPackage-Tests/RPackageTraitSynchronisationTest.class.st
Labels: tests passed please review!

#14899 10066-Cleanup-deprecated-method-in-Trait
  src/TraitsV2/Trait.class.st
Labels: tests passed please review!

#14851 Fix versioning error handling already versioned file names
  src/FileSystem-Core/FileReference.class.st
  src/FileSystem-Core/FileVersionner.class.st
  src/FileSystem-Tests-Core/FileReferenceTest.class.st
Labels: Need more work

#14885 Calypso: Show protocol edition bar only in edition
  src/Calypso-SystemTools-Core/ClyMethodCodeEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyProtocolEditorMorph.class.st
Labels: tests passed please review!

#14882 RPackage: #moveClass:toTag: can be simpler if the package do not change
  src/RPackage-Core/RPackage.class.st
Labels: tests passed please review!

#14893 Epicea: Remove most references to categories
  src/Deprecated12/ClassRepackaged.extension.st
  src/Deprecated12/PackageTagRenamed.extension.st
  src/Epicea-Tests/EpCodeChangeIntegrationTest.class.st
  src/Epicea/EpBehaviorCategoryChange.class.st
  src/Epicea/EpBehaviorRepackagedChange.class.st
  src/Epicea/EpMonitor.class.st
  src/Epicea/EpTCodeChangeVisitor.trait.st
  src/EpiceaBrowsers-Tests/EpApplyPreviewerTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers-Tests/EpLostChangesDetectorTest.class.st
  src/EpiceaBrowsers-Tests/EpRevertTest.class.st
  src/EpiceaBrowsers/EpApplyPreviewer.class.st
  src/EpiceaBrowsers/EpApplyVisitor.class.st
  src/EpiceaBrowsers/EpHasImpactVisitor.class.st
  src/EpiceaBrowsers/EpIconVisitor.class.st
  src/EpiceaBrowsers/EpInverseVisitor.class.st
  src/EpiceaBrowsers/EpMorphVisitor.class.st
  src/EpiceaBrowsers/EpNewStateVisitor.class.st
  src/EpiceaBrowsers/EpOldStateVisitor.class.st
  src/Gofer-Tests/GoferOperationTest.class.st
  src/RPackage-Core/ClassDescription.extension.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/PackageAnnouncementsTest.class.st
  src/RPackage-Tests/RPackageTestCase.class.st
  src/RPackage-Tests/UndefinedPackageTagTest.class.st
Labels: tests passed please review!

#14860 Refactorings: Update all code relying on categories to use package/tag instead
  src/GeneralRules-Tests/ReSmalllintTest.class.st
  src/Refactoring-Changes/RBAddClassChange.class.st
  src/Refactoring-Changes/RBClassCategoryChange.class.st
  src/Refactoring-Changes/RBClassRepackagingChange.class.st
  src/Refactoring-Changes/RBCompositeRefactoryChange.class.st
  src/Refactoring-Changes/RBRemovePackageChange.class.st
  src/Refactoring-Core/RBBrowserEnvironment.extension.st
  src/Refactoring-Core/RBChildrenToSiblingsRefactoring.class.st
  src/Refactoring-Core/RBClass.class.st
  src/Refactoring-Core/RBCopyClassRefactoring.class.st
  src/Refactoring-Core/RBInsertNewClassRefactoring.class.st
  src/Refactoring-Core/RBMethod.class.st
  src/Refactoring-Core/RBNamespace.class.st
  src/Refactoring-Core/RBSplitClassRefactoring.class.st
  src/Refactoring-Tests-Changes/RBRefactoringChangeTest.class.st
  src/Refactoring2-Transformations-Tests/RBChildrenToSiblingsParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBCopyPackageParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBInsertClassParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBMoveClassTransformationTest.class.st
  src/Refactoring2-Transformations-Tests/RBRenameClassRefactoringTest.class.st
  src/Refactoring2-Transformations-Tests/RBTransformationsTest.class.st
  src/Refactoring2-Transformations/RBClassTransformation.class.st
  src/Refactoring2-Transformations/RBInsertNewClassTransformation.class.st
  src/Refactoring2-Transformations/RBMoveClassTransformation.class.st
  src/Refactoring2-Transformations/RBRealizeClassTransformation.class.st
  src/Refactoring2-Transformations/RBRemoveClassTransformation.class.st
  src/Refactoring2-Transformations/RBRenameAndDeprecateClassTransformation.class.st
  src/Refactoring2-Transformations/RBSplitClassTransformation.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/SystemCommands-ClassCommands/SycCmAddSubclassCommand.class.st
  src/SystemCommands-ClassCommands/SycCmInsertSubclassCommand.class.st
  src/SystemCommands-ClassCommands/SycCmInsertSuperclassCommand.class.st
Labels: tests passed please review!

#14894 11629-Finish-FluidClassBuilderTesttestBuildSimplePoint2
  src/FluidClassBuilder-Tests/FluidClassBuilderTest.class.st
  src/FluidClassBuilder-Tests/FluidTraitBuilderTest.class.st
Labels: tests passed please review!

#14911 Clean test on repackaging
  src/Deprecated12/ClassRepackaged.extension.st
  src/Shift-ClassInstaller-Tests/ShClassInstallerAnnouncementsTest.class.st
  src/Shift-ClassInstaller-Tests/ShClassInstallerTest.class.st
  src/Slot-Tests/SlotAnnouncementsTest.class.st
Labels: tests passed please review!

#14909 Allow formatting only part of a method or playground (fixes #14618)
  src/Rubric/RubSmalltalkCodeMode.class.st
Labels: tests passed please review!

#14897 Add back #keyword in Pragma for compatibility
  src/Kernel/Pragma.class.st
Labels: tests passed please review!

#14908 Optimize Dictionary>>unreferencedKeys
  src/Collections-Unordered/Dictionary.class.st
Labels: tests passed please review!

#14797 RPackage: Finish to clean the package/tag import logic
  src/Calypso-SystemQueries/RPackage.extension.st
  src/Deprecated12/RPackage.extension.st
  src/RPackage-Core/ClassDescription.extension.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageTag.class.st
  src/RPackage-Tests/PackageAnnouncementsTest.class.st
Labels: tests passed please review!

#14919 Fix #14918 and adds a test
  src/Refactoring-Core/RBAbstractClass.class.st
  src/Refactoring-Tests-Core/RBClassTest.class.st
Labels: tests passed please review!

#14927 Fix failing tests on RPackage
  src/RPackage-Core/ClassDescription.extension.st
Labels: easyReview

#14933 Cleanup-methodsWithUnboundGlobals
  src/ReleaseTests/ReleaseTest.class.st
  src/System-Support/SystemNavigation.class.st
Labels: tests passed please review!

#14936 reduce the amount of calls to #cleanOutUndeclared during full image load
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
Labels: tests passed please review!

#14902 Merge FluidClassBuilder and ShiftClassBuilder
  src/BaselineOfPharo/BaselineOfPharo.class.st
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
  src/Deprecated12/ShiftClassBuilder.extension.st
  src/FluidClassBuilder-Tests/FluidClassSideClassBuilderTest.class.st
  src/FluidClassBuilder-Tests/FluidClassSideTraitBuilderTest.class.st
  src/FluidClassBuilder-Tests/package.st
  src/FluidClassBuilder/FluidBuilder.class.st
  src/FluidClassBuilder/FluidClassBuilder.class.st
  src/FluidClassBuilder/FluidClassSideClassBuilder.class.st
  src/FluidClassBuilder/FluidClassSideTraitBuilder.class.st
  src/FluidClassBuilder/FluidTraitBuilder.class.st
  src/FluidClassBuilder/ManifestFluidClassBuilder.class.st
  src/FluidClassBuilder/Trait.extension.st
  src/FluidClassBuilder/UndefinedObject.extension.st
  src/FluidClassBuilder/package.st
  src/Shift-Changes/ShBitLayoutChangeDetector.class.st
  src/Shift-Changes/ShBitLayoutChanged.class.st
  src/Shift-Changes/ShClassSlotChangeDetector.class.st
  src/Shift-Changes/ShLayoutChangeDetector.class.st
  src/Shift-ClassBuilder-Tests/ShiftClassBuilderAbstractTest.class.st
  src/Shift-ClassBuilder-Tests/ShiftClassBuilderTest.class.st
  src/Shift-ClassBuilder-Tests/ShiftClassSideClassBuilderTest.class.st
  src/Shift-ClassBuilder-Tests/ShiftClassSideTraitBuilderTest.class.st
  src/Shift-ClassBuilder-Tests/ShiftTraitBuilderTest.class.st
  src/Shift-ClassBuilder-Tests/TViewModelMock.trait.st
  src/Shift-ClassBuilder-Tests/TViewModelMock2.trait.st
  src/Shift-ClassBuilder/Behavior.extension.st
  src/Shift-ClassBuilder/Metaclass.extension.st
  src/Shift-ClassBuilder/ShLayoutDefinition.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/Shift-ClassBuilder/ShiftClassSideBuilder.class.st
  src/Shift-ClassBuilder/UndefinedObject.extension.st
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
  src/Slot-Tests/SlotClassVariableTest.class.st
  src/Slot-Tests/SlotIntegrationTest.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
  src/TraitsV2/ShiftClassBuilder.extension.st
  src/TraitsV2/Trait.class.st
Labels: tests passed please review!

#14955 Remove MCWorkingCopy>>#merge:
  src/Monticello/MCWorkingCopy.class.st
Labels: tests passed please review!

#14953 Simplify ClassAdded
  src/Deprecated12/ClassAdded.extension.st
  src/Kernel/Class.class.st
  src/Ring-Core/RGEnvironmentAnnouncer.class.st
  src/Ring-Tests-Core/RGAnnouncementsTest.class.st
  src/System-Announcements/ClassAdded.class.st
  src/System-Announcements/SystemAnnouncer.class.st
Labels: tests passed please review!

#14952 Reduce once more the usage of the category API
  src/ClassParser/ShiftClassBuilder.extension.st
  src/Gofer-Tests/GoferOperationTest.class.st
  src/RPackage-Core/ClassDescription.extension.st
  src/RPackage-Tests/RPackageClassesSynchronisationTest.class.st
  src/RPackage-Tests/RPackageSynchronisationTest.class.st
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
Labels: tests passed please review!

#14960 remove some methods that are duplicated in the hierarchy
  src/OSWindow-SDL2-Examples/SDL2TouchExample.class.st
  src/OSWindow-SDL2-Examples/SDL2TouchGestureExample.class.st
  src/OSWindow-SDL2-Examples/SDL2TouchGestureExample2.class.st
  src/Refactoring-Core/RBClassCondition.class.st
  src/Refactoring-UI/RBDeprecateMethodDriver.class.st
  src/Refactoring-UI/RBMoveMethodsToClassSideDriver.class.st
  src/Refactoring-UI/RBRemoveMethodDriver.class.st
  src/UnifiedFFI/FFIWin64CallbackArgumentReader.class.st
Labels: tests passed please review!, easyReview

#14959 deprecate #isMetaSide in Ring
  src/Ring-Core/RGMethod.class.st
  src/Ring-Definitions-Core/RGElementDefinition.class.st
Labels: tests passed please review!, easyReview

#14878 Do not rely on old class definition in code importer
  src/CodeImport-Tests/ChunkImportTestCase.class.st
  src/CodeImport/DoItChunk.class.st
  src/CodeImport/MethodChunk.class.st
  src/Monticello/MCClassDefinition.class.st
  src/Shift-ClassBuilder-Tests/ShCreateClassTest.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
Labels: tests passed please review!

#14951 Fix unsubscriptions of WeakSubscriptions
  bootstrap/scripts/2-download.sh
  bootstrap/scripts/3-prepare.sh
  bootstrap/scripts/4-build.sh
  bootstrap/scripts/envvars.sh
  src/Announcements-Core/SubscriptionRegistry.class.st
  src/Announcements-Core/WeakAnnouncementSubscription.class.st
Labels: Need more work

#14971 Add missing methods to ring for Hermes
  src/Ring-Core/RGVariable.class.st
Labels: tests passed please review!

#14954 14934-When-prompted-to-create-a-class-the-definition-information-are-ignored
  src/OpalCompiler-Core/OCCodeReparator.class.st
  src/OpalCompiler-Tests/OCCodeReparatorTest.class.st
Labels: tests passed please review!

#14976 reduce-ASTCache-reset
  src/PharoDocComment-Tests/DocCommentsReleaseTest.class.st
  src/ReleaseTests/ReleaseTest.class.st
Labels: tests passed please review!

#14977 Remove-recompile-Morphic-baseline
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/BaselineOfMorphicCore/BaselineOfMorphicCore.class.st
Labels: tests passed please review!

#14974 Small cleanup of ImageCleaner: #helpPackages
  src/Tool-ImageCleaner/ImageCleaner.class.st
Labels: tests passed please review!, easyReview

#14981 Cleanup: BaselineOfIDE loading RPackage-Tests in the postload
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: tests passed please review!

#14988 Morphic-load-no-rehash
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
Labels: tests passed please review!

#14575 Reduce UIManager references in Presenters + use new API
  src/ProfilerUI/ProfilerResultsPresenter.class.st
  src/Refactoring-UI/StMethodNameEditorPresenter.class.st
Labels: Need more work

#14990 Remove BaselineOfIDE obsolete management
  src/BaselineOfIDE/BaselineOfIDE.class.st
Labels: tests passed please review!

#14984 Add tests on Fluid class parser and fix bugs
  src/ClassParser-Tests/ASTClassBuilderTest.class.st
  src/ClassParser/CDFluidClassDefinitionParser.class.st
  src/UndefinedClasses-Tests/UndefinedClassTest.class.st
Labels: tests passed please review!

#14995 RPackage: Remove #toCategoryName: and clean
  src/RPackage-Core/RPackageTag.class.st
Labels: tests passed please review!

#14997 RPackage: Remove users of ClassRecatogrized
  src/Kernel/Class.class.st
  src/RPackage-Core/RPackageTag.class.st
  src/RPackage-Tests/PackageAnnouncementsTest.class.st
  src/Ring-Core/RGEnvironmentAnnouncer.class.st
  src/System-Announcements/SystemAnnouncer.class.st
Labels: tests passed please review!

#15004 RPackage: Change root tag name
  src/Kernel/FluidClassDefinitionPrinter.class.st
  src/Monticello-BackwardCompatibility/MCClassTraitDefinition.class.st
  src/Monticello/MCClassDefinition.class.st
  src/Monticello/MCOrganizationDefinition.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Tests/RPackageRenameTest.class.st
  src/RPackage-Tests/RPackageTagTest.class.st
  src/Ring-Definitions-Core/RGClassDefinition.class.st
  src/Ring-Definitions-Core/RGTraitDefinition.class.st
Labels: tests passed please review!

#14922 Fix #magnifyBy:smoothing: on AthensCairoSurfaceForm
  src/Athens-Cairo/AthensCairoSurfaceForm.class.st
Labels: tests passed please review!

#15026 Metacello: Simplify repository creation
  src/Metacello-Bitbucket/MCBitbucketRepository.class.st
  src/Metacello-Core/MCRepository.extension.st
  src/Metacello-Core/MetacelloPlatform.class.st
  src/Metacello-GitHub/MCGitHubRepository.class.st
  src/Metacello-MC/MCDictionaryRepository.extension.st
  src/Metacello-MC/MCDirectoryRepository.extension.st
  src/Metacello-MC/MCFileTreeRepository.extension.st
  src/Metacello-MC/MCFtpRepository.extension.st
  src/Metacello-MC/MCHttpRepository.extension.st
  src/Metacello-PharoCommonPlatform/MetacelloPharoCommonPlatform.class.st
Labels: tests passed please review!

#15029 RBTransformationsTest>>#testAddProtocolTransform should clean after execution
  src/Refactoring-Transformations-Tests/RBTransformationsTest.class.st
Labels: tests passed please review!

#15030 Clean system after ClyBrowserToolValidityTest
  src/Calypso-Browser-Tests/ClyBrowserToolValidityTest.class.st
Labels: tests passed please review!

#15021 Baselines: No need to nuke RBRefactoryChangeManager
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/Refactoring-Changes/RBRefactoryChangeManager.class.st
Labels: tests passed please review!

#15046 Improve new chunk importer
  src/CodeImport/DoItChunk.class.st
Labels: tests passed please review!

#15047 Remove the use of categories in bootstrap class definition
  src/Pharo30Bootstrap/PBClassLoader.class.st
  src/Pharo30Bootstrap/PBSpurClassLoader.class.st
Labels: tests passed please review!

#15032 Improve disabling of Epicea in tests
  src/Epicea/EpMonitor.class.st
Labels: tests passed please review!

#14969 [WIP] Preserve tree expansion state when (un)checking a class in the method visibility tree (fixes #14559)
  src/Calypso-Browser/ClyQueryViewMorph.class.st
Labels: tests passed please review!

#15013 Enhance roassal with version v1.04b #14985
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: tests passed please review!

#15022 Bootstrap: Use Hermes V3
  src/BaselineOfPharoBootstrapProcess/BaselineOfPharoBootstrapProcess.class.st
  src/Hermes/HEFraction.class.st
  src/Hermes/HEInstaller.class.st
  src/Hermes/HEMethod.class.st
  src/Hermes/HEMethodContainer.class.st
  src/Hermes/HEPackage.class.st
  src/Hermes/HEScaledDecimal.class.st
  src/Hermes/HESendMessage.class.st
  src/Hermes/HETrait.class.st
  src/TraitsV2/HEInstaller.extension.st
Labels: tests passed please review!

#15053 Remove usage of old class definition syntax
  src/Calypso-SystemPlugins-Traits-Browser/ClyCreateClassCommand.class.st
  src/Calypso-SystemPlugins-Traits-Browser/ClyCreateTestCaseCommand.class.st
  src/Calypso-SystemPlugins-Traits-Browser/ClyCreateTraitCommand.class.st
  src/Calypso-SystemQueries-Tests/ClySystemEnvironmentTest.class.st
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
  src/Calypso-SystemTools-Core/ClyClassCreationToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyClassDefinitionEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyFluidClassDefinitionSwitchMorph.class.st
  src/ClassParser-Tests/CDClassParserSelectionTest.class.st
  src/ClassParser/CDAbstractClassDefinitionParser.class.st
  src/ClassParser/CDClassDefinitionParser.class.st
  src/ClassParser/CDFluidClassDefinitionParser.class.st
  src/ClassParser/ClassDescription.extension.st
  src/ClassParser/FluidClassDefinitionPrinter.extension.st
  src/ClassParser/OldPharoClassDefinitionPrinter.extension.st
  src/ClassParser/RBCascadeNode.extension.st
  src/ClassParser/RBMessageNode.extension.st
  src/CodeImport/DoItChunk.class.st
  src/CodeImport/OldClassDefinitionBuilder.class.st
  src/Kernel-Tests/ClassDefinitionPrinterConfigurationTest.class.st
  src/Kernel-Tests/CommonClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/FluidClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/OldClassDefinitionPrinterTest.class.st
  src/Kernel-Tests/ProcessTerminateBugTest.class.st
  src/Kernel/ClassDefinitionPrinter.class.st
  src/Kernel/LegacyClassDefinitionPrinter.class.st
  src/Kernel/OldPharoClassDefinitionPrinter.class.st
  src/OpalCompiler-Core/OCCodeReparator.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/Ring-Core/RGMetaclassStrategy.class.st
  src/Ring-Core/RGMetaclassTraitV2Strategy.class.st
  src/Ring-Definitions-Tests-Core/RGClassDefinitionTest.class.st
  src/TraitsV2-Tests/T2CommonClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2FluidClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2LegacyPharoClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2OldPharoClassDefinitionPrinterTest.class.st
Labels: tests passed please review!

#15066 Simplify Metacello platform code
  bootstrap/scripts/03-metacello-bootstrap/01-loadMetacello.st
  src/BaselineOfMetacello/BaselineOfMetacello.class.st
  src/Compression/ZipArchive.class.st
  src/Metacello-Core/MetacelloAbstractVersionConstructor.class.st
  src/Metacello-Core/MetacelloPlatform.class.st
  src/Metacello-Core/MetacelloProject.class.st
  src/Metacello-Core/MetacelloScriptEngine.class.st
  src/Metacello-Core/MetacelloVersionConstructor.class.st
  src/Metacello-FileTree/MCFileTreeRepository.extension.st
  src/Metacello-GitBasedRepository/MCGitBasedNetworkRepository.class.st
  src/Metacello-GitHub/MCGitHubRepository.class.st
  src/Metacello-MC/FileReference.extension.st
  src/Metacello-MC/MCFtpRepository.extension.st
  src/Metacello-MC/MetacelloCommonMCSpecLoader.class.st
  src/Metacello-MC/MetacelloGoferCommit.class.st
  src/Metacello-MC/MetacelloLoadingMCSpecLoader.class.st
  src/Metacello-MC/MetacelloMCProject.class.st
  src/Metacello-MC/MetacelloNullRecordingMCSpecLoader.class.st
  src/Metacello-PharoCommonPlatform/MCFtpRepository.extension.st
  src/Metacello-PharoCommonPlatform/MetacelloPharoCommonPlatform.class.st
  src/Metacello-PharoCommonPlatform/package.st
  src/Metacello-Platform/MetacelloPharoPlatform.class.st
  src/Metacello-TestsCore/MetacelloStackCacheTestCase.class.st
  src/Metacello-TestsMCCore/MCGitBasedNetworkRepositoryTest.class.st
  src/Metacello-TestsMCCore/MetacelloRepositorySqueakCommonTestCase.class.st
  src/Metacello-TestsPlatform/MCFtpRepository.extension.st
  src/Metacello-TestsPlatform/package.st
  src/Metacello-ToolBox/MetacelloToolBox.class.st
  src/MonticelloRemoteRepositories/MCFtpRepository.class.st
Labels: tests passed please review!

#15069 Move regex core loading
  bootstrap/scripts/03-metacello-bootstrap/01-loadMetacello.st
  src/BaselineOfMetacello/BaselineOfMetacello.class.st
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
Labels: tests passed please review!

#15072 Simplify bootstraping of Metacello
  src/BaselineOfParametrizedTests/BaselineOfParametrizedTests.class.st
  src/BaselineOfTaskIt/BaselineOfTaskIt.class.st
  src/Metacello-Base/BaselineOf.class.st
  src/Metacello-Base/ConfigurationOf.class.st
  src/Metacello-Base/Metacello.class.st
  src/Metacello-MC/MetacelloConfigTemplate.class.st
  src/Metacello-MC/MetacelloConfigTemplateExample.class.st
  src/Metacello-ToolBox/BaselineOf.extension.st
  src/Metacello-ToolBox/ConfigurationOf.extension.st
  src/Metacello-ToolBox/MetacelloToolBox.class.st
  src/Metacello-Tutorial/MetacelloProjectRefTutorialConfig.class.st
  src/Metacello-Tutorial/MetacelloTutorialConfig.class.st
Labels: tests passed please review!

#15073 Fix bug marking too many packages as dirty in Iceberg
  src/RPackage-Tests/PackageAnnouncementsTest.class.st
  src/System-Announcements/MethodAnnouncement.class.st
  src/System-Announcements/MethodRemoved.class.st
Labels: tests passed please review!

#15077 Fix moving a class from a tag in Calypso
  src/Calypso-SystemQueries/ClyClassGroup.class.st
  src/Calypso-SystemQueries/ClyNoTagClassGroup.class.st
  src/Calypso-SystemQueries/ClyTaggedClassGroup.class.st
  src/RPackage-Core/ClassDescription.extension.st
Labels: tests passed please review!

#15084 Calypso: Remove duplicated registration of SycRemoveClassCommand
  src/SystemCommands-ClassCommands/SycRemoveClassCommand.class.st
Labels: tests passed please review!

#15045 Fix Jump to test method from implementors view
  src/Calypso-Browser/ClyBrowserContext.class.st
  src/Calypso-SystemPlugins-SUnit-Browser/ClyJumpToTestMethodCommand.class.st
  src/Calypso-SystemPlugins-SUnit-Browser/ClyOpenTestMethodCommand.class.st
  src/Calypso-SystemTools-QueryBrowser/ClyQueryBrowserContext.class.st
Labels: tests passed please review!, Fix proposed

#15088 Monticello: Class/Trait definition creation shouldnt use categories
  src/Monticello/MCClassDefinition.class.st
  src/Monticello/MCTraitDefinition.class.st
Labels: tests passed please review!

#15087 15074-Pragmas-lost-when-updating-methods
  src/Kernel-Tests/PragmaTest.class.st
  src/Kernel/AdditionalMethodState.class.st
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#15086 Improve MCSystemCategoryParser
  src/Monticello-BackwardCompatibility/MCSystemCategoryParser.class.st
Labels: tests passed please review!

#15090 AdditionalMethodState: do not copy the Associations/Pragmas when growing or shrinking
  src/Kernel-Tests/PragmaTest.class.st
  src/Kernel/AdditionalMethodState.class.st
  src/Kernel/CompiledMethod.class.st
Labels: tests passed please review!

#15094 Improve ShiftClassBuilder>>category:
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
Labels: tests passed please review!

#15092 RBPragmaNode/Pragma: add #sourceNode, reduce #asPragma
  src/AST-Core/RBPragmaNode.class.st
  src/Kernel/Pragma.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Tests/OCPragmaTest.class.st
  src/Reflectivity/RBMethodNode.extension.st
Labels: tests passed please review!

#15102 Introduce and use CategoryConverter
  src/CodeImport/OldClassDefinitionBuilder.class.st
  src/Monticello-BackwardCompatibility/MCSystemCategoryParser.class.st
  src/Monticello/MCClassDefinition.class.st
  src/Monticello/MCStReader.class.st
  src/Monticello/MCTraitParser.class.st
  src/Shift-ClassBuilder/CategoryConverter.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
Labels: Status: Tests passed please review!

#15101 Rewrite `== nil ifFalse:` into `ifNotNil:`
  src/Collections-Unordered/Set.class.st
  src/Compression/InflateStream.class.st
  src/EmergencyDebugger/EDEmergencyDebugger.class.st
  src/FFI-Kernel/ExternalType.class.st
  src/FreeType-Graphics/FreeTypeSettings.extension.st
  src/FreeType/FreeTypeSettings.class.st
  src/Graphics-Display Objects/ColorForm.class.st
  src/Graphics-Fonts/StrikeFont.class.st
  src/Graphics-Primitives/BitBlt.class.st
  src/Kernel/Behavior.class.st
  src/Kernel/Class.class.st
  src/Kernel/DependentsArray.class.st
  src/Metacello-Core/MetacelloVersionConstructor.class.st
  src/Polymorph-Widgets/MorphicUIManager.class.st
  src/Rubric/RubCharacterBlockScanner.class.st
  src/Rubric/RubCharacterScanner.class.st
  src/Tool-Profilers/MessageTally.class.st
Labels: Status: Tests passed please review!

#15099 [P11] Add Support for proxy in Iceberg
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: Status: Need more work

#15100 Undeclared: keep weak reference to all methods using the Undeclared Variable
  src/Kernel/UndeclaredVariable.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OCCompiledMethodIntegrityTest.class.st
  src/Slot-Core/SystemDictionary.extension.st
Labels: Status: Tests passed please review!

#15111 Update location of setting the MCZ old format flag
  src/Monticello/MonticelloBootstrap.class.st
Labels: Status: Tests passed please review!

#15112 Small cleanup: use pragma, not #expectedFailures method
  src/Monticello/MCWorkingCopy.class.st
  src/Ring-Tests-ChunkImporter/Ring2ChunkImporterTest.class.st
  src/System-Sources-Tests/SourceFileBufferedReadWriteStreamTest.class.st
  src/TaskIt-Tests/TKTCommonQueueWorkerPoolTest.class.st
Labels: Status: Tests passed please review!

#15113 Merge OCPragmaTest into MethodPragmaTest
  src/OpalCompiler-Tests/MethodPragmaTest.class.st
  src/OpalCompiler-Tests/OCPragmaTest.class.st
Labels: Status: Tests passed please review!

#15123 Clean AthensFontDescription>>#asString
  src/Athens-Cairo/AthensFontDescription.class.st
Labels: Easy

#15119 Remove BaselineOfTelePharoSupport
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfTelePharoSupport/BaselineOfTelePharoSupport.class.st
  src/BaselineOfTelePharoSupport/package.st
Labels: Status: Tests passed please review!

#15116 Improve the management of TTranscript
  bootstrap/scripts/4-build.sh
  src/BaselineOfTraits/BaselineOfTraits.class.st
  src/Transcript-Core-Traits/package.st
  src/Transcript-Core/TTranscript.trait.st
  src/Transcript-Core/ThreadSafeTranscript.class.st
Labels: Status: Tests passed please review!

#15108 Make finalization registry a normal strong double linked list P12
  src/BaselineOfMorphicCore/BaselineOfMorphicCore.class.st
  src/BaselineOfPharoBootstrap/BaselineOfPharoBootstrap.class.st
  src/Collections-DoubleLinkedList/DoubleLinkedList.class.st
  src/Collections-DoubleLinkedList/Object.extension.st
  src/System-Finalization-Tests/FinalizationRegistryEntryTest.class.st
  src/System-Finalization/FinalizationRegistry.class.st
  src/System-Finalization/FinalizationRegistryEntry.class.st
Labels: Status: Tests passed please review!

#15107 Make finalization registry a normal strong double linked list
  src/BaselineOfMorphicCore/BaselineOfMorphicCore.class.st
  src/BaselineOfPharoBootstrap/BaselineOfPharoBootstrap.class.st
  src/Collections-DoubleLinkedList/DoubleLinkedList.class.st
  src/Collections-DoubleLinkedList/Object.extension.st
  src/System-Finalization-Tests/FinalizationRegistryEntryTest.class.st
  src/System-Finalization/FinalizationRegistry.class.st
  src/System-Finalization/FinalizationRegistryEntry.class.st
Labels: Status: Tests passed please review!

#15122 Do not use categories in ShiftClassInstaller
  bootstrap/scripts/4-build.sh
  bootstrap/scripts/runKernelTests.sh
  src/ClassParser-Tests/ASTClassBuilderTest.class.st
  src/InitializePackagesCommandLineHandler/InitializePackagesCommandLineHandler.class.st
  src/InitializePackagesCommandLineHandler/RPackageOrganizer.extension.st
  src/Kernel/Class.class.st
  src/Kernel/Context.class.st
  src/Monticello/MCPackageLoader.class.st
  src/Monticello/MCWorkingCopy.class.st
  src/Monticello/MonticelloBootstrap.class.st
  src/Pharo30Bootstrap/PBBootstrap.class.st
  src/RPackage-Core/ClassDescription.extension.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Core/UndefinedPackage.class.st
  src/RPackage-Core/UndefinedPackageTag.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/Shift-ClassInstaller/ShiftAnonymousClassInstaller.class.st
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
  src/System-Support/SystemDictionary.class.st
  src/TraitsV2-Tests/T2SubclassingTraitedClassTest.class.st
Labels: Status: Tests passed please review!, Priotity: High

#15133 Do not announce method recategorization when removing a selector from a protocol
  src/Epicea/EpMonitor.class.st
  src/Epicea/TestCase.extension.st
  src/Kernel/ClassDescription.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: Status: Tests passed please review!

#15146 Fix moving classes in tags
  src/Calypso-SystemQueries/ClyClassGroup.class.st
Labels: Status: Tests passed please review!

#15141 Cut dependency from AST-Core-Tests to SystemCommands-SourceCodeCommands
  src/AST-Core-Tests/RBCodeSnippetTest.class.st
Labels: Status: Tests passed please review!

#15139 Split finalization registry from WeakArray and sort dependencies
  src/Collections-Weak/WeakArray.class.st
  src/Collections-Weak/WeakRegistry.class.st
  src/EmergencyDebugger-Tests/EDDebuggingAPITest.class.st
  src/EmergencyDebugger/EDDebuggingAPI.class.st
  src/OSWindow-SDL2/UserInterruptHandler.class.st
  src/PharoBootstrap-Initialization/PharoBootstrapInitialization.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/System-Finalization/FinalizationProcess.class.st
  src/System-Finalization/FinalizationRegistry.class.st
  src/System-Finalization/FinalizationRegistryEntry.class.st
  src/System-SessionManager/SessionManager.class.st
  src/Tool-ImageCleaner/ImageCleaner.class.st
  src/Tool-ProcessBrowser/ProcessBrowser.class.st
Labels: Status: Tests passed please review!

#14905 Force rescheduling of inactive process when changing its priority (fixes #14701)
  src/Kernel-Tests-Extended/ProcessTest.class.st
  src/Kernel/ProcessorScheduler.class.st
Labels: Status: Tests passed please review!

#15140 Guard RubAbstractTextArea>>#recomputeSelection for empty paragraphs
  src/Rubric/RubAbstractTextArea.class.st
Labels: Status: Tests passed please review!

#15144 Fix cyclic dependencies between compiler and ASTs/parser and their tests
  src/AST-Core-Tests/ManifestASTCoreTests.class.st
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBCodeSnippetTest.class.st
  src/AST-Core-Tests/RBVariableNodeTest.class.st
  src/AST-Core/RBMethodNode.class.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/OpalCompiler-Tests/RBCodeSnippetTest.extension.st
  src/OpalCompiler-Tests/RBVariableNodeTest.extension.st
Labels: Status: Tests passed please review!

#15150 Replacing the use of species new with copyEmpty.
  src/Collections-Abstract/Collection.class.st
  src/Collections-Sequenceable/OrderedCollection.class.st
  src/Collections-Sequenceable/OrderedDictionary.class.st
  src/Collections-Unordered/Dictionary.class.st
  src/Collections-Unordered/KeyedTree.class.st
  src/Collections-Unordered/SmallDictionary.class.st
Labels: Status: Tests passed please review!

#15138 Pusing down dependencies of Collection-Abstract
  src/Collections-Abstract/Collection.class.st
  src/Collections-Abstract/Object.extension.st
  src/Collections-Native/Collection.extension.st
  src/Collections-Sequenceable/ArrayedCollection.class.st
  src/Collections-Sequenceable/Collection.extension.st
  src/Collections-Sequenceable/Object.extension.st
  src/Collections-Sequenceable/SequenceableCollection.class.st
  src/Collections-Strings/CharacterSet.class.st
  src/Collections-Strings/CharacterSetComplement.class.st
  src/Collections-Strings/Collection.extension.st
  src/Collections-Strings/WideCharacterSet.class.st
  src/Collections-Unordered/Collection.extension.st
  src/Collections-Unordered/HashedCollection.class.st
  src/Tool-DependencyAnalyser-Tests/DAMessageSendAnalyzerTest.class.st
Labels: Status: Tests passed please review!

#15166 Reduce usage of category for protocol
  src/CodeImport/ChunkFileFormatParser.class.st
  src/CodeImport/MethodChunk.class.st
  src/Deprecated12/MethodChunk.extension.st
  src/Monticello/CompiledMethod.extension.st
  src/Monticello/MCMethodDefinition.class.st
  src/Monticello/MCStWriter.class.st
  src/MonticelloFileTree-Core/MCFileTreeStCypressWriter.class.st
  src/MonticelloGUI/MCSnapshotBrowser.class.st
  src/Ring-ChunkImporter/RGChunkImporter.class.st
  src/Ring-Definitions-Monticello/RGMethodDefinition.extension.st
  src/Ring-Definitions-Tests-Monticello/RGMonticelloTest.class.st
  src/Ring-Monticello/MCMethodDefinition.extension.st
  src/Ring-OldChunkImporter/RingChunkImporter.class.st
  src/TraitsV2-Tests/TraitPureBehaviorTest.class.st
Labels: Status: Tests passed please review!

#15165 Remove more old class creation API
  src/Deprecated12/Trait.extension.st
  src/Deprecated12/UndefinedObject.extension.st
  src/Kernel/UndefinedObject.class.st
  src/Monticello-BackwardCompatibility/MCClassTraitDefinition.class.st
  src/Monticello/MCClassDefinition.class.st
  src/Monticello/MCTraitDefinition.class.st
  src/TraitsV2/Trait.class.st
Labels: Status: Tests passed please review!

#15155 Calypso: Introduce a project view based on baselines in the image
  src/Calypso-Browser-Tests/ClyBrowserToolValidityTest.class.st
  src/Calypso-NavigationModel/Project.extension.st
  src/Calypso-Ring/ClyRing2Environment.class.st
  src/Calypso-SystemQueries/ClyAllProjectsQuery.class.st
  src/Calypso-SystemQueries/ClyManagedProject.class.st
  src/Calypso-SystemQueries/ClyProjectChildItem.class.st
  src/Calypso-SystemQueries/ClyProjectContentQuery.class.st
  src/Calypso-SystemQueries/ClyProjectManager.class.st
  src/Calypso-SystemQueries/ClyProjectManagerRegistry.class.st
  src/Calypso-SystemQueries/ClyProjectScope.class.st
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
  src/Calypso-SystemQueries/ClySystemEnvironmentScope.class.st
  src/Calypso-SystemQueries/Project.extension.st
  src/Calypso-SystemQueries/RPackage.extension.st
  src/Calypso-SystemTools-Core/ClyProjectChildItem.extension.st
  src/Calypso-SystemTools-Core/ClyProjectChildItemTableDecorator.class.st
  src/Calypso-SystemTools-Core/ClyProjectIconTableDecorator.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserContext.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserMorph.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserProjectContext.class.st
  src/Calypso-SystemTools-FullBrowser/ClyProjectTableIndentationDecorator.class.st
  src/Calypso-SystemTools-FullBrowser/ClySwitchToPackagesCommand.class.st
  src/Calypso-SystemTools-FullBrowser/ClySwitchToProjectsCommand.class.st
  src/Metacello-Base/BaselineOf.class.st
  src/Metacello-TestsCore/BaselineOfTestToLock1.class.st
  src/Metacello-TestsCore/BaselineOfTestToLock2.class.st
  src/RPackage-Core/RPackage.class.st
  src/Tools-Tests/ProjectManagerTest.class.st
  src/Tools/Project.class.st
  src/Tools/ProjectManager.class.st
Labels: Type: New Feature, Status: Tests passed please review!

#15172 Monticello: Multiple MethodAddition cleanings (announce protocol changes, compile before installing, cleanup)
  src/Deprecated12/MethodAddition.extension.st
  src/Monticello/MCMethodDefinition.class.st
  src/Monticello/MCPackageLoader.class.st
  src/Monticello/MethodAddition.class.st
  src/System-Sources/ClassDescription.extension.st
Labels: Type: Cleanup, Status: Tests passed please review!

#15173 tiny speedup for testNoShadowedVariablesInMethods
  src/ReleaseTests/ReleaseTest.class.st
Labels: Status: Tests passed please review!

#15176 Calypso: Project view should activate class creation tool
  src/Calypso-SystemTools-FullBrowser/ClyClassCreationToolMorph.extension.st
Labels: Status: Tests passed please review!

#15175 Fix random bug in auto completion
  src/HeuristicCompletion-Model/CoGlobalSorterResultSetBuilder.class.st
  src/HeuristicCompletion-Tests/CoNarrowHistoryFetcherTest.class.st
  src/NECompletion/CompletionContext.class.st
  src/NECompletion/RBMessageNode.extension.st
Labels: Status: Tests passed please review!

#15182 Remove #acceptsLoggingOfCompilation
  src/Graphics-Fonts/FontSet.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/Metaclass.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/System-Sources/ChangesLog.class.st
Labels: Status: Tests passed please review!

#15188 Metacello: Clean the way to create a class
  src/Metacello-Core/MetacelloPlatform.class.st
  src/Metacello-Core/MetacelloScriptEngine.class.st
  src/Metacello-ToolBox/MetacelloToolBox.class.st
Labels: Status: Tests passed please review!

#15187 Do a pass on shift after recent improvements
  src/Shift-ClassBuilder-Tests/ShCreateClassTest.class.st
  src/Shift-ClassBuilder-Tests/ShModifyClassTest.class.st
  src/Shift-ClassBuilder-Tests/ShiftClassBuilderAbstractTest.class.st
  src/Shift-ClassBuilder-Tests/ShiftClassBuilderTest.class.st
  src/Shift-ClassBuilder-Tests/ShiftTraitBuilderTest.class.st
  src/Shift-ClassInstaller-Tests/ShAnonymousClassInstallerTest.class.st
  src/Shift-ClassInstaller-Tests/ShClassInstallerTest.class.st
Labels: Status: Tests passed please review!

#15186 Deprecate ClassRenamed>>category
  src/Deprecated12/ClassRenamed.extension.st
  src/System-Announcements/ClassRenamed.class.st
Labels: Status: Tests passed please review!

#15181 Simplify ChunkImportTestCase
  src/CodeImport-Tests/ChunkImportTestCase.class.st
Labels: Status: Tests passed please review!

#15185 Improve ClassFactoryForTestCase
  src/Deprecated12/ClassFactoryForTestCase.extension.st
  src/EpiceaBrowsers-Tests/EpApplyPreviewerTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers-Tests/EpRevertTest.class.st
  src/Kernel-Tests-WithCompiler/BehaviorWithCompilerTest.class.st
  src/SUnit-Core/ClassFactoryForTestCase.class.st
  src/SUnit-Tests/ClassFactoryForTestCaseTest.class.st
Labels: Status: Tests passed please review!

#15180 RPackage: Do not register to MethodAdded
  src/Kernel-Tests/AbstractObjectsAsMethod.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/CompiledMethod.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
Labels: Status: Tests passed please review!

#15184 Move critics UI methods to critic UI package
  src/Manifest-Core/ClassDescription.extension.st
  src/Manifest-Core/CompiledMethod.extension.st
  src/Manifest-Core/RPackage.extension.st
  src/Renraku/ReSmalllintChecker.class.st
Labels: Status: Tests passed please review!

#15179 Calypso: Improve some namings on package tags
  src/Calypso-Browser-Tests/ClyBrowserContextAbstractTest.class.st
  src/Calypso-SystemPlugins-Traits-Browser/ClyCreateClassCommand.class.st
  src/Calypso-SystemPlugins-Traits-Browser/ClyCreateTestCaseCommand.class.st
  src/Calypso-SystemPlugins-Traits-Browser/ClyCreateTraitCommand.class.st
  src/Calypso-SystemQueries-Tests/ClyAllPackageTagsQueryTest.class.st
  src/Calypso-SystemQueries-Tests/ClyClassGroupProviderTest.class.st
  src/Calypso-SystemQueries-Tests/ClyPackageScopeTest.class.st
  src/Calypso-SystemQueries/ClyAllClassGroupsQuery.class.st
  src/Calypso-SystemQueries/ClyAllPackageTagsQuery.class.st
  src/Calypso-SystemQueries/ClyClassGroup.class.st
  src/Calypso-SystemQueries/ClyDefaultSystemEnvironmentPlugin.class.st
  src/Calypso-SystemQueries/ClyExtendedClassGroupProvider.class.st
  src/Calypso-SystemQueries/ClyNoTagClassGroup.class.st
  src/Calypso-SystemQueries/ClyNoTagClassGroupProvider.class.st
  src/Calypso-SystemQueries/ClyPackageScope.class.st
  src/Calypso-SystemQueries/ClyPackageTagProvider.class.st
  src/Calypso-SystemQueries/ClySingleClassGroupProvider.class.st
  src/Calypso-SystemQueries/ClySystemEnvironmentPlugin.class.st
  src/Calypso-SystemQueries/ClyTaggedClassGroup.class.st
  src/Calypso-SystemQueries/ClyTaggedClassGroupProvider.class.st
  src/Calypso-SystemQueries/ClyTypedScope.extension.st
  src/Calypso-SystemQueries/RPackage.extension.st
  src/Calypso-SystemTools-Core/ClyClassCreationToolMorph.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserClassGroupContext.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserContext.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserMorph.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserPackageContext.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserProjectContext.class.st
  src/Calypso-SystemTools-FullBrowser/ClyRemoveClassGroupCommand.class.st
  src/Calypso-SystemTools-FullBrowser/ClyRenamePackageTagCommand.class.st
  src/SystemCommands-PackageCommands/SycAddNewClassTagCommand.class.st
  src/SystemCommands-PackageCommands/SycDemoteToPackageWithTagCommand.class.st
  src/SystemCommands-PackageCommands/SycPromotePackageFromTagCommand.class.st
Labels: Status: Tests passed please review!

#15190 Another pass on #usingMethods for UndeclaredVariable: filter for installed methods
  src/Kernel/UndeclaredVariable.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OCCompiledMethodIntegrityTest.class.st
  src/Slot-Core/SystemDictionary.extension.st
Labels: Status: Tests passed please review!

#15189 Refactor AlphaImageMorph to replace ‘cachedForm’ by ‘cachedFormSet’
  src/Graphics-Display Objects/FormSet.class.st
  src/Graphics-Tests/FormSetTest.class.st
  src/Morphic-Base/AlphaImageMorph.class.st
  src/Morphic-Base/FormSet.extension.st
  src/Morphic-Widgets-PolyTabs/TabSelectorMorph.class.st
  src/Morphic-Widgets-Scrolling/IncrementalSliderMorph.class.st
  src/Morphic-Widgets-Scrolling/ScrollBarMorph.class.st
  src/Polymorph-Widgets/ExpanderTitleMorph.class.st
  src/Polymorph-Widgets/OverflowRowMorph.class.st
  src/Polymorph-Widgets/UITheme.class.st
Labels: Status: Tests passed please review!

#15132 RPackage: Clean protocols management
  src/Calypso-SystemQueries/ClyExternalPackageMethodGroup.class.st
  src/HeuristicCompletion-Tests/CoNarrowHistoryFetcherTest.class.st
  src/Kernel/ClassDescription.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
  src/SystemCommands-MethodCommands/SycMoveMethodsToPackageCommand.class.st
Labels: Status: Tests passed please review!, Priority: Medium

#14773 Following symbolic links when canonicalising FileReferences.
  src/FileSystem-Core/FileReference.class.st
  src/FileSystem-Core/MemoryDirectoryEntry.class.st
  src/FileSystem-Disk/DiskStore.class.st
  src/FileSystem-Memory/MemoryStore.class.st
  src/FileSystem-Path/AbsolutePath.class.st
  src/FileSystem-Path/Path.class.st
  src/FileSystem-Tests-Attributes/FileReferenceAttributeTest.class.st
  src/FileSystem-Tests-Core/DeleteVisitorTest.class.st
  src/FileSystem-Tests-Core/FileReferenceTest.class.st
  src/Files/File.class.st
Labels: Status: Tests passed please review!
