Repository pharo-project/pharo, pull requests merged in 2023-03, with the labels that each got.

#12829 Sync ston
  src/STON-Core/Bag.extension.st
  src/STON-Core/Boolean.extension.st
  src/STON-Core/ByteArray.extension.st
  src/STON-Core/Class.extension.st
  src/STON-Core/Collection.extension.st
  src/STON-Core/Date.extension.st
  src/STON-Core/DateAndTime.extension.st
  src/STON-Core/Dictionary.extension.st
  src/STON-Core/FileReference.extension.st
  src/STON-Core/Float.extension.st
  src/STON-Core/Interval.extension.st
  src/STON-Core/Metaclass.extension.st
  src/STON-Core/Number.extension.st
  src/STON-Core/Object.extension.st
  src/STON-Core/OrderedDictionary.extension.st
  src/STON-Core/Path.extension.st
  src/STON-Core/STON.class.st
  src/STON-Core/STONCStyleCommentsSkipStream.class.st
  src/STON-Core/STONFileReference.class.st
  src/STON-Core/STONReader.class.st
  src/STON-Core/STONReaderError.class.st
  src/STON-Core/STONStreamWriter.class.st
  src/STON-Core/STONWriter.class.st
  src/STON-Core/SequenceableCollection.extension.st
  src/STON-Core/Set.extension.st
  src/STON-Core/SmallDictionary.extension.st
  src/STON-Core/SortedCollection.extension.st
  src/STON-Core/String.extension.st
  src/STON-Core/Time.extension.st
  src/STON-Core/UndefinedObject.extension.st
  src/STON-Extensions/Color.extension.st
  src/STON-Extensions/DefaultSortFunction.extension.st
  src/STON-Extensions/ZnUrl.extension.st
  src/STON-Tests/STONAlternativeRepresentationTestObject.class.st
  src/STON-Tests/STONCStyleCommentsSkipStreamTest.class.st
  src/STON-Tests/STONJSONTest.class.st
  src/STON-Tests/STONLargeWriteReadTest.class.st
  src/STON-Tests/STONReaderTest.class.st
  src/STON-Tests/STONTest.class.st
  src/STON-Tests/STONTestAssociation.class.st
  src/STON-Tests/STONTestDomainObject.class.st
  src/STON-Tests/STONTestKnownObject.class.st
  src/STON-Tests/STONTestMap.class.st
  src/STON-Tests/STONTestUser.class.st
  src/STON-Tests/STONTestUser2.class.st
  src/STON-Tests/STONWriteAsciiOnlyReadTest.class.st
  src/STON-Tests/STONWritePrettyPrinterReadTest.class.st
  src/STON-Tests/STONWriteReadCommentsTest.class.st
  src/STON-Tests/STONWriteReadTest.class.st
  src/STON-Tests/STONWriterTest.class.st
  src/STON-Text support/RunArray.extension.st
  src/STON-Text support/Text.extension.st
  src/System-Settings-Tests/ManifestSystemSettingsTests.class.st
  src/System-Settings-Tests/SettingsStonWriterTest.class.st
  src/System-Settings-Tests/SystemSettingsPersistenceTest.class.st
Labels: tests passed please review!

#12879 Improve faulty parsing of methods
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBCodeSnippetTest.class.st
  src/AST-Core-Tests/RBErrorNodeParserTest.class.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBPragmaErrorNode.class.st
  src/EnlumineurFormatter/EFFormatter.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Tests/RBCodeSnippet.extension.st
  src/OpalCompiler-Tests/RBCodeSnippetTest.extension.st
Labels: tests passed please review!

#12882 Use MethodClassifier protocol for new methods instead of the selected protocol
  src/Calypso-SystemTools-Core/ClyMethodCodeEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodCreationToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodEditorToolMorph.class.st
  src/Debugger-Model/DebugSession.class.st
  src/Tool-Base/MethodClassifier.class.st
Labels: Enhancement, tests passed please review!, easyReview, Annoying, pharo11, system usability, first impression counts

#12887 Skipping test in windows as it is hanging
  src/Zinc-Tests/ZnServerTest.class.st
Labels: tests passed please review!

#12890 Microdown-RichTextComposer is now managed outside
  src/Microdown-RichTextComposer/MicroDownParser.extension.st
  src/Microdown-RichTextComposer/PRRichTextComposer.extension.st
  src/Microdown-RichTextComposer/package.st
Labels: tests passed please review!

#12863 Fix #10929 Graphic UI selection glitch with selected text on large screens
  src/FormCanvas-Core-Tests/BalloonEngineTest.class.st
  src/FormCanvas-Core-Tests/package.st
  src/FormCanvas-Core/BalloonEngine.class.st
Labels: Graphics, Reviewed and Ready to Integrate, Fix proposed, pharo11

#12893 Improve faulty parsing by testing unreachable code
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/OpalCompiler-Tests/RBCodeSnippetTest.extension.st
  src/Renraku-Tests/RBCodeSnippetTest.extension.st
Labels: tests passed please review!

#12891 Improve faulty parsing on chars (and primitive arrays)
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core/RBParser.class.st
Labels: tests passed please review!

#12864 new general rule ReNotEqualityOperatorsRule to inform users of != or !==
  src/GeneralRules/ReNotEqualityOperatorsRule.class.st
  src/GeneralRules/ReSentNotImplementedRule.class.st
Labels: tests passed please review!

#12460 Fix #12459 : text selection drag and drop problem.
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/Rubric-Tests/RubTextEditorTest.class.st
  src/Rubric/RubAbstractTextArea.class.st
  src/Rubric/RubTextEditor.class.st
Labels: Graphics, tests passed please review!, Fix proposed, pharo11

#12892 Improve faulty scanning on comments
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBScannerTest.class.st
  src/AST-Core/RBScanner.class.st
Labels: tests passed please review!

#12901 RBCodeSnippets test decompilation
  src/OpalCompiler-Tests/RBCodeSnippetTest.extension.st
Labels: tests passed please review!

#12895 InitializedSlot-check-default
  src/VariablesLibrary-Tests/InitializedSlotTest.class.st
  src/VariablesLibrary/AbstractInitializedSlot.class.st
Labels: tests passed please review!

#12425 Fix Calypso browsing unloaded package artifacts from Iceberg
  src/Calypso-SystemTools-Core/ClyClassDefinitionEditorToolMorph.class.st
  src/Morphic-Base/Object.extension.st
  src/Ring-Core/RGBehavior.class.st
  src/Ring-Core/RGClassStrategy.class.st
  src/Ring-Core/RGInstanceVariableSlot.class.st
  src/Ring-Core/RGPackage.class.st
  src/Ring-Core/RGUnresolvedValue.class.st
  src/Ring-Tests-Core/RGBehaviorTest.class.st
  src/Tool-DependencyAnalyser-Tests/DAMessageSendAnalyzerTest.class.st
Labels: tests passed please review!

#12904 new class SycInspectNodeCommand to simply inspect an AST node
  src/SystemCommands-SourceCodeCommands/SycInspectNodeCommand.class.st
Labels: tests passed please review!

#12852 remove method Object asOrderedCollection
  src/Collections-Strings/Symbol.class.st
  src/Deprecated11/Object.extension.st
  src/Kernel/Object.class.st
Labels: Reviewed and Ready to Integrate

#12570 Fixing bugged undo-redo commands after using completion
  src/NECompletion-Morphic/CompletionEngine.class.st
Labels: tests passed please review!

#12932 Synch zinc zodiac
  src/BaselineOfZodiac/BaselineOfZodiac.class.st
  src/Zinc-Zodiac-Tests/ZnHTTPSTest.class.st
  src/Zinc-Zodiac-Tests/package.st
  src/Zinc-Zodiac/package.st
Labels: tests passed please review!

#12919 Improve faulty compilation - semantic error
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBProgramNodeTest.class.st
  src/AST-Core/RBArrayNode.class.st
  src/AST-Core/RBAssignmentNode.class.st
  src/AST-Core/RBBlockNode.class.st
  src/AST-Core/RBCascadeNode.class.st
  src/AST-Core/RBLiteralArrayNode.class.st
  src/AST-Core/RBMessageNode.class.st
  src/AST-Core/RBMethodNode.class.st
  src/AST-Core/RBParseErrorNode.class.st
  src/AST-Core/RBPragmaNode.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBReturnNode.class.st
  src/AST-Core/RBSequenceNode.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Tests/RBCodeSnippetTest.extension.st
  src/Reflectivity/RFASTTranslator.class.st
Labels: tests passed please review!

#12930 Speed up ClassVar>>#isReferenced
  src/Kernel/Class.class.st
  src/Kernel/ClassVariable.class.st
  src/Kernel/SharedPool.class.st
Labels: tests passed please review!

#12897 Add new attributes to SDL_MouseWheelEvent
  src/OSWindow-SDL2/SDL_MouseWheelDirection.class.st
  src/OSWindow-SDL2/SDL_MouseWheelEvent.class.st
Labels: Reviewed and Ready to Integrate

#12915 Improve styler
  src/OSWindow-SDL2/SDL_TextEditingEvent.class.st
  src/Polymorph-Widgets/PharoLightTheme.class.st
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
  src/Shout-Tests/SHRBMockSharedPoolStyler.class.st
  src/Shout-Tests/SHRBMockTextStyler.class.st
  src/Shout-Tests/SHRBStyleAttributionTest.class.st
  src/Shout-Tests/SHRBTextFlagAttribute.class.st
  src/Shout-Tests/SHRBTextStylerTest.class.st
  src/Shout/SHPreferences.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: Reviewed and Ready to Integrate

#12945 Shout: Rename some styles
  src/Polymorph-Widgets/PharoLightTheme.class.st
  src/Shout-Tests/SHRBStyleAttributionTest.class.st
  src/Shout/SHPreferences.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#12952 Simplify styler
  src/Shout/ArgumentVariable.extension.st
  src/Shout/ClassVariable.extension.st
  src/Shout/DoItVariable.extension.st
  src/Shout/GlobalVariable.extension.st
  src/Shout/RBVariableNode.extension.st
  src/Shout/SHRBTextStyler.class.st
  src/Shout/SelfVariable.extension.st
  src/Shout/Slot.extension.st
  src/Shout/SuperVariable.extension.st
  src/Shout/TemporaryVariable.extension.st
  src/Shout/ThisContextVariable.extension.st
  src/Shout/UndeclaredVariable.extension.st
  src/Shout/Variable.extension.st
  src/Shout/WorkspaceVariable.extension.st
Labels: Reviewed and Ready to Integrate

#12956 12955-TFStringType-is-leaking-when-allocates-the-string-for-calling-a-function
  src/ThreadedFFI-UFFI-Tests/TFUFFIDerivedTypeMarshallingTest.class.st
  src/ThreadedFFI/TFStringType.class.st
Labels: tests passed please review!

#12949 Remove dead code in SHTextStyler
  src/Shout/SHTextStyler.class.st
Labels: Reviewed and Ready to Integrate

#12964 Loop imbricated styles + remove dead code
  src/Polymorph-Widgets/PharoLightTheme.class.st
  src/Shout/SHRBTextStyler.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: tests passed please review!

#12962 correcting computation of sets of protocols to remove and add
  src/Calypso-SystemTools-Core/ClyMethodEditorToolMorph.class.st
Labels: Reviewed and Ready to Integrate

#12971 better fix for #12858: check isTempVariable
  src/OpalCompiler-Core/CopiedLocalVariable.class.st
  src/Shout/CopiedLocalVariable.extension.st
Labels: Reviewed and Ready to Integrate

#12970 Fix bug when updating the package of an extension method
  src/SystemCommands-MethodCommands/SycMethodRepackagingCommand.class.st
Labels: tests passed please review!, easyReview

#12938 fix the default loadLibrary: for linux
  src/UnifiedFFI/UnixDynamicLoader.class.st
Labels: tests passed please review!

#12987 Fix formating of non methods
  src/Calypso-SystemTools-Core/ClyClassEditorToolMorph.class.st
Labels: Bug, Reviewed and Ready to Integrate, pharo11

#12042 New finalization
  bootstrap/scripts/2-download.sh
  src/Announcements-Core/WeakAnnouncementSubscription.class.st
  src/BaselineOfKernelTests/BaselineOfKernelTests.class.st
  src/Collections-Weak-Tests/MockExceptionWithPassAction.class.st
  src/Collections-Weak-Tests/WeakRegistryTest.class.st
  src/Collections-Weak/WeakArray.class.st
  src/Collections-Weak/WeakRegistry.class.st
  src/FileSystem-Disk/FileHandle.class.st
  src/Files/File.class.st
  src/Kernel-Tests/BehaviorTest.class.st
  src/Kernel/Object.class.st
  src/Network-Kernel/Socket.class.st
  src/Ring-Tests-Core/RGReadOnlyImageBackendTest.class.st
  src/System-Announcements/SystemAnnouncer.class.st
  src/System-Finalization-Tests/FinalizationRegistryTest.class.st
  src/System-Finalization-Tests/MockFinalizerAction.class.st
  src/System-Finalization-Tests/VileFinalizer.class.st
  src/System-Finalization-Tests/package.st
  src/System-Finalization/EphemeronRegistry.class.st
  src/System-Finalization/FinalizationRegistry.class.st
  src/System-Finalization/FinalizationRegistryEntry.class.st
  src/System-Finalization/WeakArray.extension.st
  src/TaskIt/TFinalizable.trait.st
  src/TaskIt/TKTWorker.class.st
  src/Tests/EphemeronTest.class.st
  src/Tool-Registry/ToolRegistry.class.st
  src/UnifiedFFI/FFIExternalResourceManager.class.st
Labels: tests passed please review!

#12992 Fix infinite loop in faulty literal array parsing
  src/Rubric/RubSmalltalkEditor.class.st
Labels: pharo11

#13008 Escape '|' and '.' characters to prevent regex interpretation
  src/Text-Edition/FindReplaceService.class.st
Labels: tests passed please review!

#12998 re-Enable Format Incomplete Variables
  src/Shout-Tests/SHRBTextStylerTest.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#12905 Backport fix to bugged undo-redo commands after using completion
  src/NECompletion-Morphic/CompletionEngine.class.st
Labels: tests passed please review!

#13009 Removing makefile files that are obsolete (cheched with Guille)
  Makefile
  Makefile-old
Labels: Reviewed and Ready to Integrate

#13010 Use internal FuelPlatform
  src/BaselineOfFuel/BaselineOfFuel.class.st
  src/BaselineOfFuelPlatform/BaselineOfFuelPlatform.class.st
  src/Fuel-Core/FLWordObjectCluster.class.st
  src/UnifiedFFI/FFIExternalResourceManager.class.st
Labels: tests passed please review!

#12973 11407-CI-System-variable-environment-on-windows-does-not-use-adequate-encodings
  src/System-OSEnvironments/Win32Environment.class.st
Labels: Reviewed and Ready to Integrate

#13013 "Close" instead of "Cancel" in the button label of the Find & Replace…
  src/Rubric-SpecFindReplaceDialog/SpRubFindReplaceDialog.class.st
Labels: Reviewed and Ready to Integrate

#13004 Fix Pharo 12 loading
  Makefile
  Makefile-old
  src/BaselineOfFuel/BaselineOfFuel.class.st
  src/BaselineOfFuelPlatform/BaselineOfFuelPlatform.class.st
  src/BaselineOfTaskIt/BaselineOfTaskIt.class.st
  src/Fuel-Core/FLWordObjectCluster.class.st
  src/Fuel-Platform-Pharo-11/package.st
  src/Fuel-Platform-Pharo-12/FLPharo12Platform.class.st
  src/Fuel-Platform-Pharo-12/package.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Shout-Tests/SHRBTextStylerTest.class.st
  src/Shout/SHRBTextStyler.class.st
  src/System-OSEnvironments/Win32Environment.class.st
  src/System-Support/VirtualMachine.class.st
  src/Text-Edition/FindReplaceService.class.st
  src/UnifiedFFI/FFIExternalResourceManager.class.st
Labels: tests passed please review!

#12910 Kill syntax error debugger
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/CodeImportCommandLineHandlers/CommandLineUIManager.extension.st
  src/OpalCompiler-Core/SyntaxErrorNotification.class.st
  src/Polymorph-Widgets/MorphicUIManager.class.st
  src/Tool-Registry/PharoCommonTools.class.st
  src/Tools/SyntaxErrorDebugger.class.st
  src/UIManager/DummyUIManager.class.st
  src/UIManager/NonInteractiveUIManager.class.st
  src/UIManager/UIManager.class.st
Labels: tests passed please review!, Reviewed and Ready to Integrate, pharo12

#12978 Improve OCUndeclaredVariableWarning>>declareTempAndPaste
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
Labels: pharo12

#12981 Improve ClyClassDefinitionEditorToolMorph>>applyChanges
  src/Calypso-SystemTools-Core/ClyClassDefinitionEditorToolMorph.class.st
Labels: pharo12

#12995 [for Pharo12] Improve faulty parsing: small things
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core/RBSequenceNode.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Tests/OCCompilerNotifyingTest.class.st
  src/OpalCompiler-Tests/OCCompilerTest.class.st
  src/OpalCompiler-Tests/OCMockRequestor.class.st
  src/OpalCompiler-Tests/RBCodeSnippetTest.extension.st
Labels: pharo12

#12980 Improve OCUndeclaredVariableWarning>>openMenuIn
  src/OpalCompiler-Core/OCSemanticWarning.class.st
  src/OpalCompiler-Core/OCShadowVariableWarning.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
Labels: pharo12

#12982 Improve ClySystemEnvironment>>defineNewClassFrom
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: pharo12

#13022 Make sure SharedRandom globalGenerator is reset (i.e. a new one is cr…
  src/Random-Core/SharedRandom.class.st
Labels: Reviewed and Ready to Integrate

#12787 Add document browser
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: tests passed please review!

#13029 Faulty compiler: new CodeError class
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBCodeSnippetTest.class.st
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core/CodeError.class.st
  src/AST-Core/RBParser.class.st
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
  src/CodeImportCommandLineHandlers/STCommandLineHandler.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCSemanticError.class.st
  src/OpalCompiler-Core/OCShadowVariableWarning.class.st
  src/OpalCompiler-Core/OCStoreIntoReadOnlyVariableError.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Core/SyntaxErrorNotification.class.st
  src/OpalCompiler-Tests/OCCompilerSyntaxErrorNotifyingTest.class.st
  src/OpalCompiler-Tests/RBCodeSnippet.extension.st
  src/OpalCompiler-Tests/RBCodeSnippetTest.extension.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Tool-Finder/Finder.class.st
Labels: tests passed please review!, pharo12

#13007 Improve faulty compilation - unify handling of undeclared variables
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel/UndeclaredVariable.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
  src/OpalCompiler-Tests/OCCompilerTest.class.st
Labels: tests passed please review!

#13021 Ensuring that Calypso catches any NotFound errors that could appear when a breakpoint on a test under debug doesn' exist anymore
  src/Calypso-SystemPlugins-SUnit-Browser/ClyDebugTestCommand.class.st
Labels: tests passed please review!

#12785 Tests that CI handle properly Syntax Errors during tests
  src/AST-Core-Tests/RBParserTest.class.st
Labels: tests passed please review!

#13042 Faulty parsing: change logic of errorBlock
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core/RBParser.class.st
  src/OpalCompiler-Tests/RBCodeSnippet.extension.st
  src/Refactoring-Core/RBExtractMethodRefactoring.class.st
Labels: tests passed please review!

#13040 Unify package unregistration
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
Labels: tests passed please review!

#13045 Compiler: remove getSourceFromRequestorSelection
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/MockSourceEditor.class.st
  src/OpalCompiler-Tests/OCCompilerNotifyingTest.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Rubric/RubTextEditor.class.st
  src/Text-Edition/TextEditor.class.st
Labels: tests passed please review!

#13036 Faulty code - test Monticello
  src/AST-Core-Tests/RBCodeSnippetTest.class.st
  src/Monticello/MCMethodDefinition.class.st
Labels: tests passed please review!

#12878 Use primitive 158 for string comparison
  src/Collections-Strings/ByteString.class.st
  src/Collections-Strings/String.class.st
  src/Deprecated11/ByteString.extension.st
  src/SortFunctions-Core/String.extension.st
Labels: tests passed please review!, pharo12

#13044 Faulty parser - better error position and messages
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBErrorNodeParserTest.class.st
  src/AST-Core/RBDumpVisitor.class.st
  src/AST-Core/RBEnglobingErrorNode.class.st
  src/AST-Core/RBParseErrorNode.class.st
  src/AST-Core/RBParser.class.st
  src/OpalCompiler-Tests/OCCompilerNotifyingTest.class.st
Labels: tests passed please review!

#13047 Compiler: stop playing notification pingpong
  src/CodeImport/FileCompilerRequestor.class.st
  src/CodeImport/MethodChunk.class.st
  src/CodeImport/MethodChunkCompilerRequestor.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Core/ReparseAfterSourceEditing.class.st
  src/OpalCompiler-Tests/OCCompilerExceptionsTest.class.st
  src/OpalCompiler-Tests/OCMockRequestor.class.st
Labels: tests passed please review!

#13069 Fix refacotring bug
  src/Refactoring-Core/RBRefactoring.class.st
  src/Refactoring-Core/RBRenameClassRefactoring.class.st
Labels: tests passed please review!

#13056 Speedup RBBrowserEnvironment>>#classesInPackages:do:
  src/Refactoring-Core/RBBrowserEnvironment.extension.st
Labels: tests passed please review!

#13066 Do not fire systemClassRecategorizedActionFrom: everytime
  src/RPackage-Core/RPackageOrganizer.class.st
  src/System-Announcements/SystemAnnouncer.class.st
Labels: tests passed please review!

#13046 Some cleanings of ClassDescription
  src/Kernel/ClassDescription.class.st
  src/Monticello/MethodAddition.class.st
  src/RPackage-Core/ClassDescription.extension.st
Labels: Cleanup, Reviewed and Ready to Integrate

#13067 Some various speedup
  src/Kernel/AbstractLayoutScope.class.st
  src/Kernel/LayoutClassScope.class.st
  src/Kernel/LayoutEmptyScope.class.st
  src/Manifest-Core/RBSelectorEnvironment.extension.st
  src/Refactoring-Critics/RBSmalllintChecker.class.st
  src/Refactoring-Environment/RBAndEnvironment.class.st
  src/Refactoring-Environment/RBBrowserEnvironment.class.st
  src/Refactoring-Environment/RBOrEnvironment.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/Renraku/ReSmalllintChecker.class.st
  src/TraitsV2/TaClassCompositionElement.class.st
Labels: tests passed please review!

#13023 Use dictionary in SystemOrganizer
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/Monticello/MCOrganizationDefinition.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/SUnit-Core/ClassFactoryWithOrganization.class.st
  src/System-Support/SmalltalkImage.class.st
  src/System-Support/SystemOrganizer.class.st
  src/Tool-ImageCleaner/ImageCleaner.class.st
Labels: tests passed please review!

#13050 Make unreachable statements a warning instead of an error
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core-Traits/TRBProgramNodeVisitor.trait.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBProgramNodeVisitor.class.st
  src/AST-Core/RBUnreachableStatementErrorNode.class.st
  src/Kernel-ExtraUtils/ClassHierarchyPrinterTest.class.st
  src/Reflectivity-Tools/ErrorNodeStyler.class.st
  src/Reflectivity-Tools/SemanticWarningIconStyler.class.st
Labels: Reviewed and Ready to Integrate

#13055 Faulty code: strip OCUndeclaredVariableWarning of its reparation duties
  src/ClassParser/CDAbstractClassDefinitionParser.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCCodeReparator.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OCCodeReparatorTest.class.st
  src/OpalCompiler-Tests/OCCompilerExceptionsTest.class.st
  src/Slot-Tests/DoItVariableTest.class.st
Labels: tests passed please review!

#13019 Rename ClassOrganization #*category* into #*protocolName*
  .gitignore
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/BaselineOfPharo/BaselineOfPharo.class.st
  src/CodeExport/ClassDescription.extension.st
  src/CodeImport/ClassOrganization.extension.st
  src/Debugger-Model/DebugContext.class.st
  src/Deprecated12/ClassOrganization.extension.st
  src/Deprecated12/package.st
  src/Epicea-Tests/EpCodeChangeIntegrationTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyPreviewerTest.class.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers-Tests/EpRevertTest.class.st
  src/EpiceaBrowsers/EpApplyVisitor.class.st
  src/Gofer-Core/GoferCleanup.class.st
  src/Gofer-Core/RPackageSet.extension.st
  src/Gofer-Tests/GoferOperationTest.class.st
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
  src/Kernel/CompiledMethod.class.st
  src/Kernel/ProtocolOrganizer.class.st
  src/Monticello-Tests/RPackageClassesSynchronisationTest.class.st
  src/Monticello/MCMethodDefinition.class.st
  src/Monticello/MCPackageManager.class.st
  src/Monticello/MethodAddition.class.st
  src/MonticelloGUI-Tests/MCSnapshotBrowserTest.class.st
  src/OpalCompiler-Tests/MethodPragmaTest.class.st
  src/RPackage-Core/RPackage.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/RPackage-Core/RPackageSet.class.st
  src/RPackage-Tests/RPackageOrganizerTest.class.st
  src/Refactoring-Changes/RBAddProtocolChange.class.st
  src/Refactoring-Environment/RBBrowserEnvironment.class.st
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
  src/Ring-Definitions-Core/Behavior.extension.st
  src/Ring-Definitions-Core/RGBehaviorDefinition.class.st
  src/SUnit-Core/ClassTestCase.class.st
  src/System-Support/SmalltalkImage.class.st
  src/SystemCommands-ClassCommands/SycRemoveEmptyMethodTagsCommand.class.st
  src/SystemCommands-MethodCommands/SycMoveMethodsToClassCommand.class.st
  src/SystemCommands-MethodCommands/SycMoveMethodsToPackageCommand.class.st
  src/Tool-Base/AbstractTool.class.st
  src/Tool-ImageCleaner/ImageCleaner.class.st
  src/Tool-Profilers/TimeProfiler.class.st
  src/TraitsV2-Tests/T2TraitWithCategoriesTest.class.st
  src/TraitsV2-Tests/T2TraitWithPackagesTest.class.st
  src/TraitsV2/TaAbstractComposition.class.st
  src/TraitsV2/TraitBuilderEnhancer.class.st
  src/TraitsV2/TraitedClass.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: Reviewed and Ready to Integrate, pharo12

#12824 Sync zinc
  src/Ombu-Tests/OmFileStoreTest.class.st
  src/Ombu/OmBlockFileStore.class.st
  src/Ombu/OmFileStore.class.st
  src/Ombu/OmSTONEntryReader.class.st
  src/Zinc-Character-Encoding-Core/ZnBufferedReadStream.class.st
  src/Zinc-Character-Encoding-Core/ZnCharacterEncoder.class.st
  src/Zinc-Character-Encoding-Core/ZnEncodedReadStream.class.st
  src/Zinc-Character-Encoding-Core/ZnEncodedStream.class.st
  src/Zinc-Character-Encoding-Core/ZnEndianSensitiveUTFEncoder.class.st
  src/Zinc-Character-Encoding-Core/ZnNullEncoder.class.st
  src/Zinc-Character-Encoding-Core/ZnSimplifiedByteEncoder.class.st
  src/Zinc-Character-Encoding-Core/ZnUTF16Encoder.class.st
  src/Zinc-Character-Encoding-Core/ZnUTF32Encoder.class.st
  src/Zinc-Character-Encoding-Core/ZnUTF8Encoder.class.st
  src/Zinc-Character-Encoding-Tests/ZnBase64EncoderTest.class.st
  src/Zinc-Character-Encoding-Tests/ZnBufferedReadStreamTest.class.st
  src/Zinc-Character-Encoding-Tests/ZnBufferedStreamByteTest.class.st
  src/Zinc-Character-Encoding-Tests/ZnBufferedWriteStreamTest.class.st
  src/Zinc-Character-Encoding-Tests/ZnCharacterEncoderTest.class.st
  src/Zinc-Character-Encoding-Tests/ZnCharacterStreamTest.class.st
  src/Zinc-Character-Encoding-Tests/ZnFastLineReaderTest.class.st
  src/Zinc-Character-Encoding-Tests/ZnPercentEncoderTest.class.st
  src/Zinc-Character-Encoding-Tests/ZnPositionableReadStreamTest.class.st
  src/Zinc-HTTP/ZnUtils.class.st
  src/Zinc-Zodiac-Tests/ZnHTTPSTest.class.st
Labels: tests passed please review!, pharo11

#13077 Synch with p11
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfPharo/BaselineOfPharo.class.st
  src/Calypso-SystemPlugins-SUnit-Browser/ClyDebugTestCommand.class.st
  src/Collections-Arithmetic/SequenceableCollection.extension.st
  src/Random-Core/SharedRandom.class.st
  src/Rubric-SpecFindReplaceDialog/SpRubFindReplaceDialog.class.st
Labels: tests passed please review!

#12954 Setting image version in the header of the image file
  bootstrap/scripts/2-download.sh
  bootstrap/scripts/4-build.sh
  src/ReleaseTests/ReleaseTest.class.st
  src/System-Support/VirtualMachine.class.st
Labels: Reviewed and Ready to Integrate

#13087 Faulty code: keep AST and source information in faulty CompiledMethod
  src/Kernel/CompiledMethod.class.st
  src/OpalCompiler-Core/OCDoItSemanticScope.class.st
  src/OpalCompiler-Core/OCMethodSemanticScope.class.st
  src/OpalCompiler-Core/OCSemanticScope.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/RBCodeSnippetTest.extension.st
Labels: tests passed please review!

#13080 Fauty code: RBParser parse only faulty code
  src/AST-Core-Tests/RBCodeSnippetTest.class.st
  src/AST-Core-Tests/RBErrorNodeParserTest.class.st
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBPatternParser.class.st
  src/AST-Core/RBProgramNode.class.st
  src/AST-Core/RBTemporariesErrorNode.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/Refactoring-Core/RBExtractMethodRefactoring.class.st
Labels: tests passed please review!

#13086 Speed up in rpackage
  src/Kernel/ClassDescription.class.st
  src/RPackage-Core/ClassDescription.extension.st
  src/RPackage-Core/RPackage.class.st
Labels: tests passed please review!

#13084 Compiler gets permitFaulty
  src/AST-Core/CompiledMethod.extension.st
  src/AST-Core/RBErrorNodeNotice.class.st
  src/AST-Core/RBNotice.class.st
  src/AST-Core/RBProgramNode.class.st
  src/Calypso-SystemTools-Core/ClyMethodEditorToolMorph.class.st
  src/HeuristicCompletion-Model/CoASTResultSetBuilder.class.st
  src/Kernel-Tests-Extended/CompiledMethodTest.class.st
  src/Kernel/CompiledMethod.class.st
  src/NECompletion/CompletionContext.class.st
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCRequestorScope.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OCASTTranslatorTest.class.st
  src/OpalCompiler-Tests/OCCompileWithFailureTest.class.st
  src/OpalCompiler-Tests/OCCompilerTest.class.st
  src/OpalCompiler-Tests/RBCodeSnippet.extension.st
  src/PharoDocComment/PharoDocCommentExpression.class.st
  src/Shout-Tests/SHRBStyleAttributionTest.class.st
  src/Shout-Tests/SHRBTextStylerTest.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#13082 ClassOrganization>>#classify:under:suppressIfDefault: is always called with the same parameter
  src/Kernel-Tests/ClassOrganizationTest.class.st
  src/Kernel/ClassOrganization.class.st
  src/Tests/TraitPureBehaviorTest.class.st
  src/TraitsV2/TraitedClass.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: tests passed please review!

#13103 fixes case sensitive string literal search (use Ctrl+Shift+U shortcut)
  src/Rubric/RubEditingMode.class.st
  src/Rubric/RubSmalltalkEditor.class.st
Labels: Reviewed and Ready to Integrate

#13105 Remove travis file
  .travis.yml
Labels: tests passed please review!, easyReview

#13117 LongMessageDialogWindow wraps the text
  src/Polymorph-Widgets/LongMessageDialogWindow.class.st
Labels: Reviewed and Ready to Integrate

#13118 Fix #13107 cannot remove used slot
  src/Calypso-Browser/ClyTextEditor.class.st
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#13112 Improving debug session to be able customize debug contexts model
  src/Debugger-Model/DebugSession.class.st
Labels: tests passed please review!

#13116 Speed up FreeTypeFont>>widthOf:
  src/Announcements-Core/SubscriptionRegistry.class.st
  src/FreeType/FreeTypeFont.class.st
Labels: tests passed please review!

#13095 Rubric/Calypso improve menu entries (especially browse)
  src/Rubric/RubEditingMode.class.st
  src/Rubric/RubSmalltalkCodeMode.class.st
  src/Rubric/RubSmalltalkEditor.class.st
Labels: tests passed please review!

#13078 Move machineEpsilon to Float.
  src/Kernel/Float.class.st
  src/Math-Operations-Extensions/Float.extension.st
Labels: tests passed please review!, easyReview

#13075 Disable ReCompactSourceCodeRule for p11
  src/Renraku/ReCompactSourceCodeRule.class.st
Labels: Reviewed and Ready to Integrate

#13124 Add a way to know the real processor architecture
  src/System-Platforms/Unix32Platform.class.st
  src/System-Platforms/Unix64Platform.class.st
  src/System-Platforms/UnixARM32Platform.class.st
  src/UnifiedFFI/MacOSXPlatform.extension.st
  src/UnifiedFFI/OSPlatform.extension.st
  src/UnifiedFFI/WinPlatform.extension.st
Labels: Reviewed and Ready to Integrate, pharo11

#13147 Synch with p11
  bootstrap/scripts/2-download.sh
  bootstrap/scripts/4-build.sh
  src/Debugger-Model/DebugSession.class.st
  src/Kernel-Tests-Extended/BlockClosureTest.extension.st
  src/Kernel-Tests/CompiledCodeTest.class.st
  src/OpalCompiler-Core/OCASTTranslatorForEffect.class.st
  src/OpalCompiler-Tests/MethodMapTest.class.st
  src/Polymorph-Widgets/LongMessageDialogWindow.class.st
  src/Reflectivity/RFASTTranslatorForEffect.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/Renraku/ReCompactSourceCodeRule.class.st
  src/Rubric/RubEditingMode.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/System-Finalization/FinalizationRegistry.class.st
  src/System-Platforms/Unix32Platform.class.st
  src/System-Platforms/Unix64Platform.class.st
  src/System-Platforms/UnixARM32Platform.class.st
  src/System-Support/VirtualMachine.class.st
  src/UnifiedFFI/MacOSXPlatform.extension.st
  src/UnifiedFFI/OSPlatform.extension.st
  src/UnifiedFFI/WinPlatform.extension.st
Labels: IMPORTANT ISSUE

#13144 Speed up #assertCollection:hasSameElements: in case they are equals.
  src/SUnit-Core-Traits/TAssertable.trait.st
  src/SUnit-Core/TestAsserter.class.st
Labels: tests passed please review!

#13130 13122 rbparser cutting tokens in stepBar [Pharo12]
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core/RBParser.class.st
Labels: Reviewed and Ready to Integrate, pharo12

#13016 move bootstrap/src into main src
  bootstrap/src/BaselineOfPharoBootstrapProcess
  bootstrap/src/Pharo30Bootstrap
  src/BaselineOfPharoBootstrapProcess/BaselineOfPharoBootstrapProcess.class.st
  src/BaselineOfPharoBootstrapProcess/NonInteractiveTranscript.extension.st
  src/BaselineOfPharoBootstrapProcess/package.st
  src/Pharo30Bootstrap/PBBootstrap.class.st
  src/Pharo30Bootstrap/PBBootstrap30.class.st
  src/Pharo30Bootstrap/PBBootstrapLogger.class.st
  src/Pharo30Bootstrap/PBBootstrapStatistics.class.st
  src/Pharo30Bootstrap/PBClassDefinition.class.st
  src/Pharo30Bootstrap/PBClassLoader.class.st
  src/Pharo30Bootstrap/PBDefinitionFetcher.class.st
  src/Pharo30Bootstrap/PBImageBuilder50.class.st
  src/Pharo30Bootstrap/PBImageBuilderSpur50.class.st
  src/Pharo30Bootstrap/PBImageBuilderSpur5032bit.class.st
  src/Pharo30Bootstrap/PBImageBuilderSpur5064bit.class.st
  src/Pharo30Bootstrap/PBInstanceVariableMapping.class.st
  src/Pharo30Bootstrap/PBMethodCompiler.class.st
  src/Pharo30Bootstrap/PBOldExtendedBootstrap.class.st
  src/Pharo30Bootstrap/PBSignal.class.st
  src/Pharo30Bootstrap/PBSpurClassLoader.class.st
  src/Pharo30Bootstrap/PBStepFinishedSignal.class.st
  src/Pharo30Bootstrap/PBStepStartedSignal.class.st
  src/Pharo30Bootstrap/PBSubStepFinishedSignal.class.st
  src/Pharo30Bootstrap/PBVersionInfo.class.st
  src/Pharo30Bootstrap/PBVersionInfoTest.class.st
  src/Pharo30Bootstrap/RGEnvironment.extension.st
  src/Pharo30Bootstrap/TonelRepository.extension.st
  src/Pharo30Bootstrap/package.st
Labels: Reviewed and Ready to Integrate, pharo12

#13133 Faulty code: improve error on unexpected block parameter
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core/RBEnglobingErrorNode.class.st
  src/AST-Core/RBParser.class.st
Labels: Reviewed and Ready to Integrate

#13129 13122 rbparser cutting tokens in stepBar [Pharo11]
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core/RBParser.class.st
Labels: tests passed please review!, pharo11

#13099 Refactoring push down method command to use driver
  src/Refactoring-Core/RBPushDownMethodRefactoring.class.st
  src/Refactoring-UI/RBPushDownMethodDriver.class.st
  src/SystemCommands-MethodCommands/SycPushDownMethodCommand.class.st
Labels: tests passed please review!

#13145 More explicit error message for slot usage in bootstrap
  src/Pharo30Bootstrap/PBClassLoader.class.st
  src/Pharo30Bootstrap/RGInstanceVariableSlot.extension.st
  src/Pharo30Bootstrap/RGSlot.extension.st
Labels: tests passed please review!

#13132 Faulty code: improve shadowing policy and implementation
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCShadowVariableWarning.class.st
  src/OpalCompiler-Tests/OCCompilerTest.class.st
Labels: tests passed please review!

#13155 remove end line characters in returned value of processorArchitecture
  src/UnifiedFFI/OSPlatform.extension.st
  src/UnifiedFFI/WinPlatform.extension.st
Labels: tests passed please review!

#13157 Rename #nullCategory into #nullProtocolName
  src/Kernel/AbstractProtocol.class.st
  src/Kernel/AllProtocol.class.st
  src/Tool-Base/AbstractTool.class.st
Labels: tests passed please review!, easyReview

#13163 Faulty code: cleanup CodeError
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core/CodeError.class.st
  src/AST-Core/RBProgramNode.class.st
  src/CodeImport/MethodChunk.class.st
  src/CodeImportCommandLineHandlers/STCommandLineHandler.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/RBCodeSnippetTest.extension.st
Labels: tests passed please review!

#13127 CodeSnippet: can update itself thaks to metaprogramming and code transformation
  src/AST-Core-Tests/RBCodeSnippet.class.st
Labels: tests passed please review!

#13148 Faulty code: introduce invalid variables
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core/RBParseErrorNode.class.st
  src/AST-Core/RBSimpleFormatter.class.st
  src/AST-Core/RBTemporariesErrorNode.class.st
  src/EnlumineurFormatter/EFFormatter.class.st
  src/Kernel/Variable.class.st
  src/OpalCompiler-Core/InvalidVariable.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCASTTranslator.class.st
Labels: tests passed please review!

#13131 Refactorings clean up
  src/Refactoring2-Transformations/RBInsertClassTransformation.class.st
  src/Refactoring2-Transformations/RBMethodProtocolTransformation.class.st
  src/Refactoring2-Transformations/RBRealizeClassTransformation.class.st
  src/Refactoring2-Transformations/RBTransformation.class.st
  src/SystemCommands-ClassCommands/SycRealizeClassCommand.class.st
Labels: tests passed please review!

#13135 Faulty code improve scanner on error tokens
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core/RBErrorToken.class.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBScanner.class.st
Labels: tests passed please review!

#13169 ProtocolOrganizer cleanings
  src/CodeImport/ProtocolOrganizer.extension.st
  src/EpiceaBrowsers-Tests/EpApplyTest.class.st
  src/EpiceaBrowsers-Tests/EpRevertTest.class.st
  src/EpiceaBrowsers/EpApplyPreviewer.class.st
  src/EpiceaBrowsers/EpHasImpactVisitor.class.st
  src/Kernel/ClassOrganization.class.st
  src/Kernel/ProtocolOrganizer.class.st
Labels: tests passed please review!

#13167 implement #selectedClassOrMetaClass in MCTool to return nil
  src/MonticelloGUI/MCCodeTool.class.st
  src/MonticelloGUI/MCTool.class.st
Labels: tests passed please review!

#13174 Faulty code: improve code error descriptions
  src/AST-Core/CodeError.class.st
  src/AST-Core/RBNotice.class.st
  src/CodeImportCommandLineHandlers/STCommandLineHandler.class.st
Labels: tests passed please review!

#13152 OpalCompiler gain install
  src/Kernel/ClassDescription.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OpalCompilerTest.class.st
Labels: Reviewed and Ready to Integrate

#13179 Removing unused instance variable `topContext` in DebugContext
  src/Debugger-Model/DebugContext.class.st
  src/Debugger-Model/DebugSession.class.st
Labels: tests passed please review!

#13178 Improve announcements printing
  src/Announcements-Core/AnnouncementSubscription.class.st
  src/Announcements-Core/WeakAnnouncementSubscription.class.st
Labels: tests passed please review!

#13182 13181-DeprecationPerformedNotification-Automatic-deprecation-code-rewrite
  src/Kernel/Object.class.st
Labels: tests passed please review!

#13176 remove commentSourcePointer from ClassOrganization
  src/Fuel-Tests-Core/FLTCreateClassOrTraitSerializationTest.trait.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/ClassOrganization.class.st
Labels: Reviewed and Ready to Integrate

#13184 Compiler source code is String
  src/Calypso-SystemTools-Core/ClyMethodCodeEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodEditorToolMorph.class.st
  src/Monticello-Tests/MCStWriterTest.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Tests/OCCompilerSyntaxErrorNotifyingTest.class.st
  src/System-Changes/ChangeRecord.class.st
Labels: tests passed please review!

#13188 ChangeRecord: rename category into protocol
  src/Deprecated12/ChangeRecord.extension.st
  src/Monticello/ChangeRecord.extension.st
  src/Ring-Definitions-Core/ChangeRecord.extension.st
  src/System-Changes/ChangeRecord.class.st
  src/System-Changes/ChangeSet.class.st
  src/System-Changes/SourceFileArray.extension.st
Labels: Reviewed and Ready to Integrate

#13186 Faulty code: Make OCUndeclaredVariableWarning a little less special
  src/AST-Core/RBNotice.class.st
  src/AST-Core/RBProgramNode.class.st
  src/CodeImportCommandLineHandlers/STCommandLineHandler.class.st
  src/OpalCompiler-Core/OCASTSemanticAnalyzer.class.st
  src/OpalCompiler-Core/OCSemanticWarning.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableNotice.class.st
  src/OpalCompiler-Core/OCUndeclaredVariableWarning.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#13185 Factorize announcement subscribers
  src/Announcements-Core/AbstractAnnouncementSubscription.class.st
  src/Announcements-Core/AnnouncementSubscription.class.st
  src/Announcements-Core/WeakAnnouncementSubscription.class.st
Labels: tests passed please review!

#13194 Inline extensions of protocol organizer
  src/CodeExport/ClassOrganization.extension.st
  src/CodeExport/ProtocolOrganizer.extension.st
  src/CodeImport/ClassOrganization.extension.st
  src/CodeImport/ProtocolOrganizer.extension.st
Labels: tests passed please review!

#13202 ProtocolOrganizer: Move a bunch more behavior to ClassOrganization
  src/Kernel/ClassOrganization.class.st
  src/Kernel/ProtocolOrganizer.class.st
Labels: tests passed please review!

#13195 Bootstrap scripts: do not use undeclared variables
  bootstrap/scripts/01-initialization/01-init.st
  bootstrap/scripts/02-monticello-bootstrap/03-bootstrapMonticelloRemote.st
  bootstrap/scripts/03-metacello-bootstrap/01-loadMetacello.st
Labels: tests passed please review!

#13208 Extract SystemChanges tests to their own package
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/System-Changes-Tests/ChangeSetClassChangesTest.class.st
  src/System-Changes-Tests/ClassRenameFixTest.class.st
  src/System-Changes-Tests/package.st
  src/System-Changes/ManifestSystemChanges.class.st
Labels: tests passed please review!

#13203 Protocol: Rename "category" into protocol in rules
  src/GeneralRules/ReInconsistentMethodClassificationRule.class.st
  src/GeneralRules/ReNoSpaceAroundMethodCategoryNameRule.class.st
  src/GeneralRules/ReNoSpaceAroundProtocolRule.class.st
  src/GeneralRules/ReUnaryAccessingMethodWithoutReturnRule.class.st
  src/Renraku/ReProperMethodProtocolNameForTestsRule.class.st
  src/Renraku/ReProperMethodProtocolNameRule.class.st
  src/Renraku/ReSmalllintChecker.class.st
Labels: tests passed please review!

#13190 Rename some "category" into protocol in code export
  src/CodeExport-Traits/TraitedClass.extension.st
  src/CodeExport-Traits/TraitedMetaclass.extension.st
  src/CodeExport/ClassDescription.extension.st
  src/Monticello/MethodAddition.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/System-Sources/ClassDescription.extension.st
  src/System-Sources/CompiledMethod.extension.st
Labels: tests passed please review!

#13140 Move runarray to collections support
  src/Collections-Support-Tests/RunArrayTest.class.st
  src/Collections-Support/RunArray.class.st
  src/Text-Core/RunArray.extension.st
  src/Text-Tests/RunArrayTest.extension.st
  src/Tool-DependencyAnalyser-Tests/DAMessageSendAnalyzerTest.class.st
Labels: Reviewed and Ready to Integrate

#13200 This commit simplifies some conditionals using `isEmpty` followed by an #ifTrue:[ifFalse:]
  src/Kernel-Chronology-Extras/Stopwatch.class.st
  src/Kernel/Class.class.st
  src/Kernel/ClassDescription.class.st
  src/Kernel/CompiledMethod.class.st
  src/Kernel/Context.class.st
  src/Kernel/Message.class.st
  src/Kernel/MessageSend.class.st
  src/Kernel/Monitor.class.st
  src/Kernel/Object.class.st
  src/Kernel/ProcessList.class.st
  src/Kernel/ProcessorScheduler.class.st
  src/Kernel/Semaphore.class.st
  src/Kernel/WeakMessageSend.class.st
  src/Math-Operations-Extensions/Integer.extension.st
  src/System-Object Events/Object.extension.st
Labels: tests passed please review!

#13218 Fix selection of multiword
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion-Tests/CompletionEngineTest.class.st
  src/Rubric-Tests/RubTextEditorTest.class.st
  src/Rubric/RubTextEditor.class.st
Labels: tests passed please review!

#13211 KeyboardKey class>>#initializeKeyFromCharacterCompatibilityTable maps 3 characters incorrectly
  src/System-Platforms/KeyboardKey.class.st
Labels: tests passed please review!

#13206 Rename SystemOrganizer "elements" into "Behavior"
  src/Deprecated12/SystemOrganizer.extension.st
  src/Fuel-Tests-Core/FLClassFactoryForTestCase.class.st
  src/Kernel/Class.class.st
  src/Metacello-PharoCommonPlatform/MetacelloPharoCommonPlatform.class.st
  src/RPackage-Core/RPackageOrganizer.class.st
  src/Refactoring-Environment/RBBrowserEnvironment.class.st
  src/System-Changes/ChangeSet.class.st
  src/System-Support/SystemDictionary.class.st
  src/System-Support/SystemOrganizer.class.st
  src/Tests/ClassTraitTest.class.st
  src/Tests/TraitMethodDescriptionTest.class.st
  src/Tests/TraitPureBehaviorTest.class.st
Labels: tests passed please review!

#12946 SDL2 on MacOS required to postpone focus
  src/OSWindow-Core/OSWorldRenderer.class.st
  src/OSWindow-SDL2/OSSDL2Driver.class.st
Labels: tests passed please review!

#13236 Declare global variables Display, World and ActiveWorld
  src/BaselineOfDisplay/BaselineOfDisplay.class.st
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
Labels: tests passed please review!
