Repository pharo-project/pharo, pull requests merged in 2023-02, with the labels that each got.

#12476 extract return from ifTrue: ifFalse: and remove white spaces
  src/TraitsV2/HEInstaller.extension.st
Labels: tests passed please review!

#12473 Honor theme changed events
  src/Morphic-Widgets-FastTable/FTTableContainerMorph.class.st
  src/Rubric/RubAbstractTextArea.class.st
Labels: tests passed please review!

#12512 Extract set up now classify setUp in #running
  src/Refactoring-Core/RBAbstractClass.class.st
  src/Refactoring-Core/RBExtractSetUpMethodRefactoring.class.st
Labels: tests passed please review!

#12523 5500-Ban-rule-on-testReadComputedSlotCompiled
  src/VariablesLibrary-Tests/ComputedSlotTest.class.st
  src/VariablesLibrary-Tests/ManifestVariablesLibraryTests.class.st
Labels: tests passed please review!

#12522 Remove SourceCodeFont setting that has no effect
  src/EmbeddedFreeType/SourceCodeFonts.class.st
Labels: tests passed please review!

#12510 Stepping mecanisme should be used by model and morph. But it is curre…
  src/Deprecated11/Object.extension.st
  src/Kernel/Object.class.st
  src/Morphic-Core/Morph.class.st
  src/Morphic-Widgets-Windows/SystemWindow.class.st
Labels: tests passed please review!

#12495 FindAndReplaceRefactoring is a transformation
  src/Refactoring-Core/RBExtractMethodAndOccurrences.class.st
  src/Refactoring-Core/RBExtractSetUpMethodAndOccurrences.class.st
  src/Refactoring-Core/RBFindAndReplaceSetUpTransformation.class.st
  src/Refactoring-Core/RBFindAndReplaceTransformation.class.st
  src/Refactoring2-Transformations-Tests/RBFindAndReplaceParametrizedTest.class.st
  src/Refactoring2-Transformations-Tests/RBFindAndReplaceSetUpParametrizedTest.class.st
  src/SystemCommands-MessageCommands/SycFindAndReplaceMethodCommand.class.st
  src/SystemCommands-MethodCommands/SycFindAndReplaceSetUpCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycInlineMethodCommand.class.st
Labels: tests passed please review!

#12464 Fix #12408, remove containerTabs from the notebook and not from the owner submorphs
  src/Calypso-Browser/ClyBrowserToolMorph.class.st
Labels: tests passed please review!

#12543 Cleanup: Condense Ombu packages
  src/Ombu-Tests/OmBlockFileStoreTest.class.st
  src/Ombu-Tests/OmDeferrerTest.class.st
  src/Ombu-Tests/OmFileStoreTest.class.st
  src/Ombu-Tests/OmMemoryStoreTest.class.st
  src/Ombu-Tests/OmRandomSuffixStrategyTest.class.st
  src/Ombu-Tests/OmSessionStoreNameStrategyTest.class.st
  src/Ombu-Tests/OmSessionStoreTest.class.st
  src/Ombu-Tests/OmStoreFactoryTest.class.st
  src/Ombu-Tests/OmStoreTest.class.st
  src/Ombu/OmBlock.class.st
  src/Ombu/OmBlockFileStore.class.st
  src/Ombu/OmDeferrer.class.st
  src/Ombu/OmEntry.class.st
  src/Ombu/OmEntryReader.class.st
  src/Ombu/OmEntryWriter.class.st
  src/Ombu/OmFileStore.class.st
  src/Ombu/OmFuelEntryWriter.class.st
  src/Ombu/OmMemoryStore.class.st
  src/Ombu/OmNullReference.class.st
  src/Ombu/OmReference.class.st
  src/Ombu/OmSTONEntryReader.class.st
  src/Ombu/OmSTONEntryWriter.class.st
  src/Ombu/OmSequentialSuffixStrategy.class.st
  src/Ombu/OmSessionStore.class.st
  src/Ombu/OmSessionStoreNamingStrategy.class.st
  src/Ombu/OmStore.class.st
  src/Ombu/OmStoreFactory.class.st
  src/Ombu/OmSuffixAfterDotStrategy.class.st
  src/Ombu/RPackageTag.extension.st
  src/Ombu/WeakValueDictionary.extension.st
Labels: tests passed please review!

#12529 12518-ImageCleaner-shareLiterals-shouldnt-consider-Strings-and-Symbols-the-same
  src/Tool-ImageCleaner/ImageCleaner.class.st
Labels: tests passed please review!

#12580 12498-Documentation-fix-for-Dictionary--keysAndValuesDo
  src/Collections-Unordered/Dictionary.class.st
Labels: tests passed please review!

#12524 12080-Dead-code-viewContentsInWorkspace
  src/System-Settings-Browser/SettingBrowser.class.st
  src/System-Settings-Core/SettingDeclaration.class.st
  src/Tool-FileList/FileList.class.st
Labels: tests passed please review!

#12581 Improve robustess of DependencyAnalyzer
  src/Tool-DependencyAnalyser-Tests/DAPackageTest.class.st
  src/Tool-DependencyAnalyser-UI/DADependencyTreePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAPotentialDependenciesNode.class.st
  src/Tool-DependencyAnalyser/DADependencyChecker.class.st
  src/Tool-DependencyAnalyser/DAMessageSendAnalyzer.class.st
  src/Tool-DependencyAnalyser/DAPackageRelationGraph.class.st
  src/Tool-DependencyAnalyser/DAPotentialOutDatedDependencyWarning.class.st
  src/Tool-DependencyAnalyser/DAUnknownManuallyResolvedPackage.class.st
Labels: tests passed please review!

#12582 remove dead code with wikiStyleHelp: pragma
  src/RPackage-Core/RPackage.class.st
  src/System-Settings-Browser/SettingBrowser.class.st
Labels: tests passed please review!

#12583 Add <ignoreForCoverage> to methods generated by the manifest builder
  src/Manifest-Core/TheManifestBuilder.class.st
Labels: tests passed please review!

#12588 Add #ensureOpen to Trascript to not open multiple transcripts while s…
  src/Transcript-Tool/ThreadSafeTranscript.extension.st
Labels: tests passed please review!

#12530 skip the test testNewProcessTaskRunnerRunsInNewProcessEveryTime on the CI
  src/TaskIt-Tests/TKTNewProcessTaskRunnerTest.class.st
Labels: tests passed please review!

#12520 Rename PlatformIndependentEnvironment into NullOSEnvironment
  src/Deprecated11/PlatformIndependentEnvironment.class.st
  src/System-OSEnvironments-Tests/OSEnvironmentTest.class.st
  src/System-OSEnvironments/NullOSEnvironment.class.st
  src/System-OSEnvironments/OSEnvironment.class.st
  src/System-OSEnvironments/PlatformIndependentEnvironment.class.st
Labels: tests passed please review!

#12603 fix transcript output testIgnoreDeprecationWarnings
  src/SUnit-Tests/SUnitTest.class.st
Labels: tests passed please review!

#12475 Disable setting formatIncompleteIdentifiers by default
  src/Shout/SHRBTextStyler.class.st
Labels: tests passed please review!

#12429 add a "parse plugin" mechanism to OpalCompiler
  src/AST-Core-Tests/RBMessageNodeTest.class.st
  src/AST-Core/RBMessageNode.class.st
  src/OpalCompiler-Core/CompilationContext.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
Labels: tests passed please review!

#12589 12418-MCMethodDefinition-asSymbol-error-when-catString-isNil-loading-BaselineOf
  src/Monticello/MCMethodDefinition.class.st
Labels: tests passed please review!

#12604 Compiler: enable optionInlineTimesRepeat and optionInlineRepeat by default
  src/Kernel-Tests/CompiledBlockTest.class.st
  src/OpalCompiler-Core/CompilationContext.class.st
Labels: tests passed please review!

#12640 Missing class comment: BaselineOfBeacon
  src/BaselineOfBeacon/BaselineOfBeacon.class.st
Labels: Reviewed and Ready to Integrate

#12679 Cleanup: Condense System-Installers packages
  src/System-Installers-Tests/MCMczInstallerTest.class.st
  src/System-Installers/MczInstaller.class.st
Labels: Reviewed and Ready to Integrate

#12667 Cleanup: Condense System-DependenciesTests packages
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: Reviewed and Ready to Integrate

#12656 Cleanup: Condense System-Announcements packages
  src/System-Announcements/AnnouncementLogger.class.st
  src/System-Announcements/BlockClosure.extension.st
  src/System-Announcements/ClassModificationApplied.class.st
  src/System-Announcements/ClassRecategorized.class.st
  src/System-Announcements/ClassRemoved.class.st
  src/System-Announcements/ClassRenamed.class.st
  src/System-Announcements/ClassReorganized.class.st
  src/System-Announcements/ClassRepackaged.class.st
  src/System-Announcements/ClassTagAnnouncement.class.st
  src/System-Announcements/ExpressionEvaluated.class.st
  src/System-Announcements/MethodAnnouncement.class.st
  src/System-Announcements/MethodModified.class.st
  src/System-Announcements/MethodRecategorized.class.st
  src/System-Announcements/MethodRemoved.class.st
  src/System-Announcements/MethodRepackaged.class.st
  src/System-Announcements/SnapshotDone.class.st
  src/System-Announcements/SystemAnnouncement.class.st
  src/System-Announcements/SystemAnnouncer.class.st
Labels: Reviewed and Ready to Integrate

#12654 Cleanup: Condense StartupPreferences packages
  src/StartupPreferences/StartupAction.class.st
  src/StartupPreferences/StartupPreferencesHandler.class.st
  src/StartupPreferences/StartupPreferencesLoader.class.st
Labels: Reviewed and Ready to Integrate

#12642 Missing class comment BaselineOfClap and lint issue
  src/BaselineOfClap/BaselineOfClap.class.st
Labels: Reviewed and Ready to Integrate

#12638 Adjust #initialize categorization cases
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
Labels: Reviewed and Ready to Integrate

#12768 11368-Failing-on-CI-random-CoNarrowHistoryFetcherTesttestNarrowingReturnsSameElementsThatCallingDirectly
  src/HeuristicCompletion-Tests/CoNarrowHistoryFetcherTest.class.st
Labels: Reviewed and Ready to Integrate

#12636 Cleanup: Condense Shift packages
  src/Shift-Changes/ShAbstractChange.class.st
  src/Shift-Changes/ShAbstractChangeDetector.class.st
  src/Shift-Changes/ShAbstractClassChangeDetector.class.st
  src/Shift-Changes/ShAbstractInstanceSideClassChangeDetector.class.st
  src/Shift-Changes/ShBitLayoutChanged.class.st
  src/Shift-Changes/ShClassChanged.class.st
  src/Shift-Changes/ShInstanceShapeChanged.class.st
  src/Shift-Changes/ShMetaclassChanged.class.st
  src/Shift-Changes/ShSharedVariablesChangeDetector.class.st
  src/Shift-Changes/ShSuperclassChanged.class.st
  src/Shift-ClassBuilder-Tests/ShAbstractClassBuilderTest.class.st
  src/Shift-ClassBuilder-Tests/ShCreateClassTest.class.st
  src/Shift-ClassBuilder-Tests/ShModifyClassTest.class.st
  src/Shift-ClassBuilder/DangerousClassNotifier.class.st
  src/Shift-ClassBuilder/ShDefaultBuilderEnhancer.class.st
  src/Shift-ClassBuilder/ShGlobalsEnvironment.class.st
  src/Shift-ClassBuilder/ShLayoutDefinition.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/Shift-ClassInstaller-Tests/ShAnonymousClassInstallerTest.class.st
  src/Shift-ClassInstaller-Tests/ShClassInstallerTest.class.st
  src/Shift-ClassInstaller/Class.extension.st
  src/Shift-ClassInstaller/Metaclass.extension.st
  src/Shift-ClassInstaller/ShiftClassInstaller.class.st
  src/Shift-ClassInstaller/SmalltalkImage.extension.st
Labels: Reviewed and Ready to Integrate

#12750 Cleanup: Condense UndefinedClasses packages
  src/UndefinedClasses-Tests/UndefinedClassTest.class.st
  src/UndefinedClasses/Behavior.extension.st
  src/UndefinedClasses/UndefinedClass.class.st
Labels: Reviewed and Ready to Integrate

#12618 Cleanup: Condense ReleaseTests packages
  src/ReleaseTests/NoUnusedVariablesLeftTest.class.st
  src/ReleaseTests/ObsoleteTest.class.st
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
  src/ReleaseTests/ProperPackagesTest.class.st
  src/ReleaseTests/ProperlyImplementedSUnitClassesTest.class.st
  src/ReleaseTests/ProtocolConventionsTest.class.st
  src/ReleaseTests/ReleaseTest.class.st
Labels: Reviewed and Ready to Integrate

#12634 Cleanup: Condense Settings packages
  src/Settings-Graphics/GraphicFontSettings.class.st
  src/Settings-Polymorph/PolymorphSystemSettings.class.st
  src/Settings-System/SystemSystemSettings.class.st
Labels: Reviewed and Ready to Integrate

#12758 Cleanup: Condense WebBrowser packages
  src/WebBrowser-Core/WBMacWebBrowser.class.st
  src/WebBrowser-Core/WBUnixWebBrowser.class.st
  src/WebBrowser-Core/WBWindowsWebBrowser.class.st
  src/WebBrowser-Core/WebBrowser.class.st
Labels: Reviewed and Ready to Integrate

#12632 Cleanup: Condense ScriptingExtensions packages
  src/ScriptingExtensions-Tests/StringTest.extension.st
  src/ScriptingExtensions-Tests/SymbolTest.extension.st
  src/ScriptingExtensions/String.extension.st
Labels: Reviewed and Ready to Integrate

#12746 Cleanup: Condense Transcript packages
  src/Transcript-Core-Traits/TTranscript.trait.st
  src/Transcript-Core/Object.extension.st
  src/Transcript-Core/ThreadSafeTranscript.class.st
  src/Transcript-NonInteractive-Tests/NonInteractiveTranscriptTest.class.st
  src/Transcript-NonInteractive/DailyNonInteractiveTranscript.class.st
  src/Transcript-NonInteractive/NonInteractiveTranscript.class.st
  src/Transcript-Tool/ThreadSafeTranscript.extension.st
Labels: Reviewed and Ready to Integrate

#12736 Cleanup: Condense Tool-Workspace packages
  src/Tool-Workspace/RubWorkspaceBarRuler.class.st
  src/Tool-Workspace/Workspace.class.st
Labels: Reviewed and Ready to Integrate

#12732 Cleanup: Condense Tool-Profilers packages
  src/Tool-Profilers-Tests/AndreasSystemProfilerTest.class.st
  src/Tool-Profilers-Tests/MessageTallyTest.class.st
  src/Tool-Profilers/AndreasSystemProfiler.class.st
  src/Tool-Profilers/BlockClosure.extension.st
  src/Tool-Profilers/MessageTally.class.st
  src/Tool-Profilers/QSystemTally.class.st
  src/Tool-Profilers/SmalltalkImage.extension.st
  src/Tool-Profilers/SpaceTally.class.st
  src/Tool-Profilers/SpaceTallyItem.class.st
  src/Tool-Profilers/SpaceTallyResult.class.st
  src/Tool-Profilers/TimeProfiler.class.st
  src/Tool-Profilers/TimeProfilerNode.class.st
Labels: Reviewed and Ready to Integrate

#12740 Cleanup: Condense Tools-Tests packages
  src/Tools-Tests/MethodClassifierTest.class.st
  src/Tools-Tests/OpenToolTest.class.st
Labels: Reviewed and Ready to Integrate

#12742 Cleanup: Condense Tools packages
  src/Tools/Behavior.extension.st
  src/Tools/KeyPrinterMorph.class.st
  src/Tools/LogDebugger.class.st
  src/Tools/SyntaxErrorDebugger.class.st
Labels: Reviewed and Ready to Integrate

#12652 Cleanup: Condense SortFunctions packages
  src/SortFunctions-Core/BlockClosure.extension.st
  src/SortFunctions-Core/CollatorBlockFunction.class.st
  src/SortFunctions-Core/PropertySortFunction.class.st
  src/SortFunctions-Core/SortFunction.class.st
  src/SortFunctions-Tests/ChainedSortFunctionTest.class.st
  src/SortFunctions-Tests/SortFunctionTest.class.st
Labels: Reviewed and Ready to Integrate

#12692 Cleanup: Condense System-Serial Port packages
  src/System-Serial Port/SerialPort.class.st
Labels: Reviewed and Ready to Integrate

#12624 Cleanup: Condense RottenTestsFinder packages
  src/RottenTestsFinder-FakeTests/RTFFakeTestClass.class.st
  src/RottenTestsFinder-Tests/RTFLeadsToAssertPrimitiveCallCheckerTest.class.st
  src/RottenTestsFinder-Tests/RTFMethodCallsCollectorTest.class.st
  src/RottenTestsFinder-Tests/RTFSelfCallInterpreterTest.class.st
  src/RottenTestsFinder-Tests/RTFSelfCallTreeCleanerTest.class.st
  src/RottenTestsFinder-Tests/RottenTestsFinderTest.class.st
  src/RottenTestsFinder/RTFLeadsToAssertPrimitiveCallChecker.class.st
  src/RottenTestsFinder/RTFMethodTracer.class.st
  src/RottenTestsFinder/RTFMethodTracersSet.class.st
  src/RottenTestsFinder/RTFRecursiveMetalinksUninstaller.class.st
  src/RottenTestsFinder/RTFRottenHelpersFinder.class.st
  src/RottenTestsFinder/RTFSelfCallInterpreter.class.st
  src/RottenTestsFinder/RottenTestImplementedInSuperClass.class.st
  src/RottenTestsFinder/RottenTestsFinder.class.st
  src/RottenTestsFinder/RottenTestsSet.class.st
Labels: Reviewed and Ready to Integrate

#12644 Cleanup: Condense Shout packages
  src/Shout-Tests/SHRBTextStylerTest.class.st
  src/Shout-Tests/SHStyleElementTest.class.st
  src/Shout/SHPreferences.class.st
  src/Shout/SHRBTextStyler.class.st
  src/Shout/SHStyleElement.class.st
  src/Shout/SHTextStyler.class.st
Labels: Reviewed and Ready to Integrate

#12609 Cleanup: Condense Regex packages
  src/Regex-Core-Tests/RxMatcherTest.class.st
  src/Regex-Core-Tests/RxParserTest.class.st
  src/Regex-Core/RegexSyntaxError.class.st
  src/Regex-Core/RxCharSetParser.class.st
  src/Regex-Core/RxMatchOptimizer.class.st
  src/Regex-Core/RxMatcher.class.st
  src/Regex-Core/RxParser.class.st
  src/Regex-Core/RxmLink.class.st
  src/Regex-Core/RxmLookahaed.class.st
  src/Regex-Core/RxmPredicate.class.st
  src/Regex-Core/RxsCharacter.class.st
  src/Regex-Core/RxsLookaround.class.st
  src/Regex-Core/RxsNode.class.st
  src/Regex-Core/RxsPiece.class.st
  src/Regex-Core/RxsRange.class.st
  src/Regex-Core/String.extension.st
  src/Regex-Core/UIManager.extension.st
Labels: Reviewed and Ready to Integrate

#12780 categorization tests should print culprints if any
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
Labels: Reviewed and Ready to Integrate

#12726 Cleanup: Condense Tool-Finder packages
  src/Tool-Finder-Tests/MethodFinderBottomClass.class.st
  src/Tool-Finder-Tests/MethodFinderTest.class.st
  src/Tool-Finder-Tests/MethodFinderTopClass.class.st
  src/Tool-Finder/ClassDescription.extension.st
  src/Tool-Finder/Finder.class.st
  src/Tool-Finder/FinderClassNode.class.st
  src/Tool-Finder/FinderExampleMethodNode.class.st
  src/Tool-Finder/FinderMethodNode.class.st
  src/Tool-Finder/FinderNode.class.st
  src/Tool-Finder/FinderPragmaMethodNode.class.st
  src/Tool-Finder/FinderPragmaNode.class.st
  src/Tool-Finder/FinderUI.class.st
  src/Tool-Finder/MethodFinder.class.st
  src/Tool-Finder/MethodFinderSend.class.st
Labels: Reviewed and Ready to Integrate

#12669 Cleanup: Condense System-FileRegistry packages
  src/System-FileRegistry/FileServices.class.st
  src/System-FileRegistry/GZipReadStream.extension.st
  src/System-FileRegistry/SimpleServiceEntry.class.st
  src/System-FileRegistry/ZipArchive.extension.st
Labels: Reviewed and Ready to Integrate

#12744 Cleanup: Condense TraitsV2 packages
  src/TraitsV2-Compatibility/TaAbstractComposition.extension.st
  src/TraitsV2-Compatibility/TaCompositionElement.extension.st
  src/TraitsV2-Compatibility/TaEmptyComposition.extension.st
  src/TraitsV2-Compatibility/TaSequence.extension.st
  src/TraitsV2-Compatibility/TaSingleComposition.extension.st
  src/TraitsV2-Compatibility/TraitMethodDescription.class.st
  src/TraitsV2-Tests/T2AbstractTest.class.st
  src/TraitsV2-Tests/T2CommonClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2FluidClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2LegacyPharoClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2ObsoleteClassTest.class.st
  src/TraitsV2-Tests/T2OldPharoClassDefinitionPrinterTest.class.st
  src/TraitsV2-Tests/T2OverloadingOfMethodsInTraitedClassTest.class.st
  src/TraitsV2-Tests/T2PrecedenceCompositionTest.class.st
  src/TraitsV2-Tests/T2SubclassingTraitedClassTest.class.st
  src/TraitsV2-Tests/T2TraitAnnouncementsTest.class.st
  src/TraitsV2-Tests/T2TraitChangesTest.class.st
  src/TraitsV2-Tests/T2TraitInTraitClassTest.class.st
  src/TraitsV2-Tests/T2TraitMCDefinitionsTest.class.st
  src/TraitsV2-Tests/T2TraitSlotScopeTest.class.st
  src/TraitsV2-Tests/T2TraitTest.class.st
  src/TraitsV2-Tests/T2TraitWithAliasTest.class.st
  src/TraitsV2-Tests/T2TraitWithCategoriesTest.class.st
  src/TraitsV2-Tests/T2TraitWithComplexSlotsTest.class.st
  src/TraitsV2-Tests/T2TraitWithConflictsTest.class.st
  src/TraitsV2-Tests/T2TraitWithPackagesTest.class.st
  src/TraitsV2-Tests/T2TraitWithSlotsTest.class.st
  src/TraitsV2-Tests/TMockWithComplexSlot.trait.st
  src/TraitsV2/Behavior.extension.st
  src/TraitsV2/Class.extension.st
  src/TraitsV2/HEInstaller.extension.st
  src/TraitsV2/Metaclass.extension.st
  src/TraitsV2/MetaclassForTraits.class.st
  src/TraitsV2/ShiftClassBuilder.extension.st
  src/TraitsV2/TaAbstractComposition.class.st
  src/TraitsV2/TaAliasMethod.class.st
  src/TraitsV2/TaClassCompositionElement.class.st
  src/TraitsV2/TaCompositionElement.class.st
  src/TraitsV2/TaDeepAliasMethod.class.st
  src/TraitsV2/TaEmptyComposition.class.st
  src/TraitsV2/TaPrecedenceComposition.class.st
  src/TraitsV2/TaRemoveMethod.class.st
  src/TraitsV2/TaRemoveSlot.class.st
  src/TraitsV2/TaRenameSlot.class.st
  src/TraitsV2/TaSequence.class.st
  src/TraitsV2/TaSingleComposition.class.st
  src/TraitsV2/Trait.class.st
  src/TraitsV2/TraitBuilderEnhancer.class.st
  src/TraitsV2/TraitChange.class.st
  src/TraitsV2/TraitedClass.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: Reviewed and Ready to Integrate

#12694 Cleanup: Condense System-SessionManager packages
  src/System-SessionManager-Tests/SessionCreationTest.class.st
  src/System-SessionManager-Tests/SessionErrorHandlingTest.class.st
  src/System-SessionManager-Tests/SessionManagerRegistrationOrderTest.class.st
  src/System-SessionManager-Tests/SessionManagerRegistrationTest.class.st
  src/System-SessionManager-Tests/SessionManagerUnregistrationTest.class.st
  src/System-SessionManager-Tests/TestSessionHandler.class.st
  src/System-SessionManager-Tests/TestWorkingSession.class.st
  src/System-SessionManager/AbstractSessionHandler.class.st
  src/System-SessionManager/ClassSessionHandler.class.st
  src/System-SessionManager/SessionAccessModeResolver.class.st
  src/System-SessionManager/SessionCategory.class.st
  src/System-SessionManager/SessionManager.class.st
  src/System-SessionManager/StartupUIManager.class.st
  src/System-SessionManager/UIManagerSessionHandler.class.st
  src/System-SessionManager/WorkingSession.class.st
Labels: Reviewed and Ready to Integrate

#12612 Remove BlueInk packages
  src/BaselineOfBlueInk/BaselineOfBlueInk.class.st
  src/BaselineOfBlueInk/package.st
  src/BlueInk-Core/BIConfigurableFormatter.class.st
  src/BlueInk-Core/BIFormatSettingsExample.class.st
  src/BlueInk-Core/BIPrettyPrinterContext.class.st
  src/BlueInk-Core/BISettingsChanged.class.st
  src/BlueInk-Core/package.st
  src/BlueInk-Extras/BISettingPreviewer.class.st
  src/BlueInk-Extras/package.st
  src/BlueInk-Tests/BIArrayExpressionTest.class.st
  src/BlueInk-Tests/BIAssignmentExpressionTest.class.st
  src/BlueInk-Tests/BIBlock2ExpressionTest.class.st
  src/BlueInk-Tests/BIBlockExpressionTest.class.st
  src/BlueInk-Tests/BICascadeExpressionTest.class.st
  src/BlueInk-Tests/BIConfigurableFormatterFormattingTest.class.st
  src/BlueInk-Tests/BILiteralArrayExpressionTest.class.st
  src/BlueInk-Tests/BILiteralValueExpressionTest.class.st
  src/BlueInk-Tests/BIMessageExpressionTest.class.st
  src/BlueInk-Tests/BIMethodeExpressionTest.class.st
  src/BlueInk-Tests/BIParseErrorExpressionTest.class.st
  src/BlueInk-Tests/BIPatternBlockExpressionTest.class.st
  src/BlueInk-Tests/BIPragmaExpressionTest.class.st
  src/BlueInk-Tests/BIReturnExpressionTest.class.st
  src/BlueInk-Tests/BISequenceExpressionTest.class.st
  src/BlueInk-Tests/BISingleExpressionTest.class.st
  src/BlueInk-Tests/BITemporariesExpressionTest.class.st
  src/BlueInk-Tests/BIVariableExpressionTest.class.st
  src/BlueInk-Tests/package.st
Labels: tests passed please review!

#12782 FIx #wantsSteps deprecated calls
  src/Morphic-Widgets-Windows/SystemWindow.class.st
Labels: tests passed please review!

#12777 add some Duration tests
  src/Kernel-Tests/DurationTest.class.st
  src/Kernel/Duration.class.st
Labels: tests passed please review!

#12616 load equals packages
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/Equals-Tests/EqFruit.class.st
  src/Equals-Tests/EqPerson.class.st
  src/Equals-Tests/TEqualityTest.class.st
Labels: Reviewed and Ready to Integrate

#12793 Remove #wantsSteps from object and uses #respondsTo: in the system wi…
  src/Deprecated11/Object.extension.st
  src/Morphic-Widgets-Windows/SystemWindow.class.st
Labels: tests passed please review!

#12797 Fixes testInstanceSideInitializeMethodNeedsToBeInInitializationProtocol
  src/Equals-Tests/EqFruit.class.st
  src/Equals-Tests/EqStudent.class.st
  src/Equals-Tests/EqTeacher.class.st
  src/Polymorph-Widgets/EditorFindReplaceDialogWindow.extension.st
  src/ReleaseTests/ProperMethodCategorizationTest.class.st
  src/Text-Edition/EditorFindReplaceDialogWindow.class.st
Labels: tests passed please review!

#12792 Update Roassal version v0.9.9m
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: tests passed please review!

#12810 extract return. fix: #12809
  src/Kernel/Class.class.st
Labels: Reviewed and Ready to Integrate

#12808 Remove depreceted class reference
  src/Morphic-Examples/WidgetExample.class.st
Labels: tests passed please review!

#12778 Improve faulty parsing
  src/AST-Core-Tests/RBErrorNodeParserTest.class.st
  src/AST-Core-Tests/RBFormatterTest.class.st
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core-Tests/RBScannerTest.class.st
  src/AST-Core/RBDumpVisitor.class.st
  src/AST-Core/RBEnglobingErrorNode.class.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBScanner.class.st
  src/EnlumineurFormatter/EFFormatter.class.st
  src/NumberParser/NumberParser.class.st
  src/OpalCompiler-Tests/OCCompilerNotifyingTest.class.st
Labels: tests passed please review!

#12771 Introducing a Color Palette to cache the allocation of Color objects by tht UITheme
  src/DrTests-CommentsToTests/DTCommentToTestResult.class.st
  src/DrTests-TestsRunner/DTTestsRunnerResult.class.st
  src/DrTests/DTStyleContributor.class.st
  src/DrTests/PharoDarkTheme.extension.st
  src/DrTests/UITheme.extension.st
  src/Growl/UITheme.extension.st
  src/Polymorph-Widgets/DarkThemeColorConfigurator.class.st
  src/Polymorph-Widgets/LightThemeColorConfigurator.class.st
  src/Polymorph-Widgets/PharoDarkTheme.class.st
  src/Polymorph-Widgets/PharoLightTheme.class.st
  src/Polymorph-Widgets/ThemeSettings.class.st
  src/Polymorph-Widgets/UITheme.class.st
  src/Polymorph-Widgets/UITheme.extension.st
  src/Polymorph-Widgets/UIThemeColorConfigurator.class.st
  src/Polymorph-Widgets/UIThemePalette.class.st
  src/SUnit-Core/TestResult.class.st
Labels: Need more work

#12762 Cleanup: Condense Zodiac packages
  src/Zodiac-Core/ZdcAbstractSSLSession.class.st
  src/Zodiac-Core/ZdcAbstractSocketStream.class.st
  src/Zodiac-Core/ZdcByteArrayManager.class.st
  src/Zodiac-Core/ZdcIOBuffer.class.st
  src/Zodiac-Core/ZdcOptimizedSocketStream.class.st
  src/Zodiac-Core/ZdcPluginSSLSession.class.st
  src/Zodiac-Core/ZdcSecureSocketStream.class.st
  src/Zodiac-Core/ZdcSimpleSocketStream.class.st
  src/Zodiac-Core/ZdcSocketStream.class.st
  src/Zodiac-Extra/ZdcSecurePOP3Client.class.st
  src/Zodiac-Extra/ZdcSecureSMTPClient.class.st
  src/Zodiac-Tests/ZdcAbstractSocketStreamTest.class.st
  src/Zodiac-Tests/ZdcIOBufferTest.class.st
  src/Zodiac-Tests/ZdcOptimizedSocketStreamTest.class.st
  src/Zodiac-Tests/ZdcPluginSSLSessionTest.class.st
  src/Zodiac-Tests/ZdcReferenceSocketStreamTest.class.st
  src/Zodiac-Tests/ZdcSecureSocketStreamTest.class.st
  src/Zodiac-Tests/ZdcSimpleSocketStreamTest.class.st
  src/Zodiac-Tests/ZdcSocketStreamTest.class.st
Labels: Reviewed and Ready to Integrate

#12812 Rename bootstrap 3rd step to be the 2nd now
  bootstrap/scripts/01-initialization/02-initUnicode.st
  bootstrap/scripts/4-build.sh
Labels: tests passed please review!

#12800 Add #closeTo: on sequenceable collection
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/Math-Operations-Extensions-Tests/MathOperationsExtensionsTest.class.st
  src/Math-Operations-Extensions-Tests/package.st
  src/Math-Operations-Extensions/SequenceableCollection.extension.st
Labels: Reviewed and Ready to Integrate

#12605 Make all PRs to run in the latest VM
  bootstrap/scripts/runKernelTests.sh
  bootstrap/scripts/runTests.sh
Labels: Reviewed and Ready to Integrate

#12613 Remove help packages that are not loaded in the image
  src/Announcements-Help/package.st
  src/FreeType-Help/FreeTypeFontHelp.class.st
  src/FreeType-Help/package.st
  src/Pharo-Help/HowToContributeHelp.class.st
  src/Pharo-Help/ImportingResourceHelp.class.st
  src/Pharo-Help/PharoEnvironmentHelp.class.st
  src/Pharo-Help/WorldMenuHelp.class.st
  src/Pharo-Help/package.st
  src/ProfStef-Help/ManifestProfStefHelp.class.st
  src/ProfStef-Help/PharoTutorialHelpTutorialBuilder.class.st
  src/ProfStef-Help/package.st
  src/Renraku-Help/package.st
Labels: tests passed please review!

#12615 Fix float comparision with precision and start to test Math-Operation…
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/Kernel-Tests-Extended/FloatTest.extension.st
  src/Math-Operations-Extensions-Tests/MathOperationnsExtensionsTest.class.st
  src/Math-Operations-Extensions/Float.extension.st
  src/STON-Tests/STONReaderTest.class.st
Labels: tests passed please review!

#12584 Remove dependency of ChangeSet on Author
  src/System-Changes/ChangeSet.class.st
  src/Tests/ChangeSet.extension.st
Labels: tests passed please review!

#12818 Improve faulty parsing of byte array literal (alternative version)
  src/AST-Core-Tests/RBErrorNodeParserTest.class.st
  src/AST-Core-Tests/RBFormatterTest.class.st
  src/AST-Core/RBParser.class.st
Labels: tests passed please review!

#12833 Refactoring `TDebugger class>>#handlesContext:` to `TDebugger>>#handlesDebugSession:`
  bootstrap/scripts/4-build.sh
  src/Debugger-Model-Tests/TDebuggerTest.class.st
  src/Debugger-Model/TDebugger.trait.st
  src/Debugger-Oups-Tests/OupsDummyDebugger.class.st
  src/Debugger-Oups/OupsDebuggerSelector.class.st
  src/Zinc-HTTP/ZnUtils.class.st
Labels: tests passed please review!

#12835 NumberParser: kill `requestor`
  src/NumberParser/NumberParser.class.st
Labels: tests passed please review!

#12836 Add RBToken>>isSpecial: to simplify parsing code
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBPatternParser.class.st
  src/AST-Core/RBSpecialCharacterToken.class.st
  src/AST-Core/RBToken.class.st
Labels: tests passed please review!

#12511 New try at not hardcoding Metacello Attributes
  src/System-Support/SmalltalkImage.class.st
Labels: tests passed please review!

#12838 Deprecate all nativeboost methods
  src/Deprecated11/ByteArray.extension.st
  src/UnifiedFFI-Legacy/ByteArray.extension.st
Labels: tests passed please review!

#12855 Clean up spaces in Polymorph-Widgets package
  src/Polymorph-Widgets/DarkThemeColorConfigurator.class.st
  src/Polymorph-Widgets/MorphicUIManager.class.st
  src/Polymorph-Widgets/PharoDarkTheme.class.st
  src/Polymorph-Widgets/ThemeSettings.class.st
  src/Polymorph-Widgets/UITheme.class.st
  src/Polymorph-Widgets/UIThemeColorConfigurator.class.st
Labels: tests passed please review!

#12851 Update the version of graph algos to use the latest one
  src/BaselineOfDependencyAnalyzer/BaselineOfDependencyAnalyzer.class.st
Labels: tests passed please review!

#12861 Clean some parsing code
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBPatternParser.class.st
  src/AST-Core/RBScanner.class.st
  src/OpalCompiler-Tests/OCTargetCompilerParser.class.st
Labels: tests passed please review!

#12857 Improve scanning: escape comments
  src/AST-Core-Tests/RBErrorNodeParserTest.class.st
  src/AST-Core-Tests/RBScannerTest.class.st
  src/AST-Core/RBComment.class.st
  src/AST-Core/RBScanner.class.st
  src/Collections-Strings/String.class.st
  src/EnlumineurFormatter/EFFormatter.class.st
  src/PharoDocComment-Tests/PharoDocCommentTest.class.st
  src/PharoDocComment/SHRBTextStyler.extension.st
Labels: tests passed please review!

#12846 Fix TPrintTests rotten green tests
  src/Collections-Abstract-Tests/TPrintOnSequencedTest.trait.st
  src/Collections-Abstract-Tests/TPrintTest.trait.st
  src/Collections-Sequenceable-Tests/ArrayTest.class.st
  src/Collections-Sequenceable-Tests/IntervalTest.class.st
  src/Collections-Strings-Tests/StringTest.class.st
  src/Collections-Strings-Tests/SymbolTest.class.st
  src/Kernel/Character.class.st
  src/System-Support-Tests/SystemDictionaryTest.class.st
Labels: tests passed please review!

#12869 12858-CopiedLocalVariable-answers-false-to-isTemporaryVariable-even-when-it-is
  src/OpalCompiler-Core/CopiedLocalVariable.class.st
  src/OpalCompiler-Tests/OCASTClosureAnalyzerTest.class.st
Labels: Reviewed and Ready to Integrate

#12528 Refactoring UI cleanup
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/Refactoring-UI/RBDeprecateMethodDriver.class.st
  src/Refactoring-UI/RBDriver.class.st
  src/Refactoring-UI/RBMoveMethodsToClassSideDriver.class.st
  src/Refactoring-UI/StRefactoringPreviewPresenter.class.st
  src/Refactoring-UI/package.st
Labels: tests passed please review!

#12877 use ifEmpty ifNotEmpty
  src/TraitsV2/Array.extension.st
Labels: Reviewed and Ready to Integrate

#12872 EFFormatter use parenthesis on error nodes if some were present
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/EnlumineurFormatter/EFFormatter.class.st
Labels: tests passed please review!

#12871 RBCodeSnippet nice overview of error messages
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core/RBProgramNode.class.st
Labels: tests passed please review!

#12874 Rewrite some error messages to follow the style `Foo expected`
  src/AST-Core-Tests/RBErrorNodeParserTest.class.st
  src/AST-Core-Tests/RBScannerTest.class.st
  src/AST-Core/RBParser.class.st
  src/AST-Core/RBScanner.class.st
  src/OpalCompiler-Tests/OCCompilerNotifyingTest.class.st
Labels: tests passed please review!

#12868 Improve faulty parsing on variables
  src/AST-Core-Tests/RBCodeSnippet.class.st
  src/AST-Core/RBBlockErrorNode.class.st
  src/AST-Core/RBParser.class.st
  src/EnlumineurFormatter/EFFormatter.class.st
Labels: tests passed please review!
