Repository pharo-project/pharo, pull requests merged in 2024-09, with the labels that each got.

#17048 Just add the menu to load Bloc and Toplo that was present in Pharo 12.
  src/Tool-Registry/PharoCommonTools.class.st
Labels: Easy

#17040 Rename RBComment into ASTCommentNode
  src/AST-Core-Tests/ASTCommentNodeTest.class.st
  src/AST-Core-Tests/RBParserTest.class.st
  src/AST-Core/ASTCommentNode.class.st
  src/AST-Core/RBCommentNodeVisitor.class.st
  src/AST-Core/RBParser.class.st
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/Kernel-ExtraUtils/ClassHierarchyPrinter.class.st
  src/Kernel-ExtraUtils/ClassHierarchyPrinterTest.class.st
  src/PharoDocComment/ASTCommentNode.extension.st
  src/PharoDocComment/PharoDocCommentExpression.class.st
  src/PharoDocComment/PharoDocCommentNode.class.st
  src/PharoDocComment/SHRBTextStyler.extension.st
  src/Refactoring-Core/RBInlineMethodRefactoring.class.st
  src/Reflectivity/Breakpoint.class.st
Labels: Status: Tests passed please review!

#17061 Fix Issue downloading icon packs
  src/IconPacks/IconPacksFetchPresenter.class.st
  src/Polymorph-Widgets/ThemeIcons.class.st
Labels: Type: Enhancement, Easy, Status: Tests passed please review!, Version: Pharo 13

#17065 Clean unused TickDialogWindow
  src/Polymorph-Widgets/TickDialogWindow.class.st
Labels: Type: Cleanup

#17069 Upgrade iceberg to v2.3.2
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: more-information-needed

#17082 Minor fixes and convenience methods to debug settings
  src/Growl/GrowlMorph.class.st
  src/IconPacks/IconPacksFetchPresenter.class.st
  src/System-Settings-Core/PragmaSetting.class.st
Labels: Easy

#17085 [Refactoring] Fix Duplicate + browse class -> raises Error
  src/Refactoring-UI/ReDuplicateClassDriver.class.st
  src/Refactoring-UI/StClassAndMethodsSelectionPresenter.class.st
  src/Refactoring-UI/StRequestClassPresenter.class.st
Labels: Project: Refactorings

#17076 Cleanup metacello spec resolution
  src/Metacello-Core/MetacelloAbstractPackageSpec.class.st
  src/Metacello-Core/MetacelloAbstractVersionConstructor.class.st
  src/Metacello-Core/MetacelloGroupSpec.class.st
  src/Metacello-Core/MetacelloMCPartiallyLoadedStatus.class.st
  src/Metacello-Core/MetacelloPackageSpec.class.st
  src/Metacello-Core/MetacelloPackageSpecResolutionError.class.st
  src/Metacello-Core/MetacelloProject.class.st
  src/Metacello-Core/MetacelloProjectSpec.class.st
  src/Metacello-Core/MetacelloProjectSpecLoadConflict.class.st
  src/Metacello-Core/MetacelloProjectSpecLoadError.class.st
  src/Metacello-Core/MetacelloRecordTarget.class.st
  src/Metacello-Core/MetacelloVersion.class.st
  src/Metacello-Core/MetacelloVersionLoadDirective.class.st
  src/Metacello-Core/MetacelloVersionSpec.class.st
  src/Metacello-Cypress/MetacelloCypressBaselineProject.class.st
  src/Metacello-Cypress/MetacelloCypressPackageSpec.class.st
  src/Metacello-Cypress/MetacelloMCBaselineProject.extension.st
Labels: Status: Tests passed please review!

#17102 Fix incomplete PR for browsing duplicated class
  src/Refactoring-Core/ReCopyClassRefactoring.class.st
  src/Refactoring-UI/ReDuplicateClassDriver.class.st
  src/Refactoring-UI/StClassAndMethodsSelectionPresenter.class.st
  src/SystemCommands-ClassCommands/SycCmDuplicateClassCommand.class.st
Labels: Project: Calypso

#17105 Remove Metacello difference
  src/Metacello-Core/MetacelloVersion.class.st
  src/Metacello-Core/MetacelloVersionDiffReport.class.st
  src/Metacello-Core/MetacelloVersionSpec.class.st
  src/Metacello-TestsCore/MetacelloCoreVersionQueryTestCase.class.st
Labels: Status: Tests passed please review!

#17087 Unify declaration of default theme
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/DarkBlueTheme/SHRBTextStyler.extension.st
  src/Settings-Polymorph/PolymorphSystemSettings.class.st
  src/Shout/SHRBTextStyler.class.st
Labels: Status: Tests passed please review!

#17109 Use small fix from the settingsOn: version in NewTools.
  src/NECompletion-Preferences/NECPreferences.class.st
Labels: Easy, more-information-needed

#17108 Fix FileList extensions loading order
  src/BaselineOfMetacello/BaselineOfMetacello.class.st
  src/System-FileRegistry/FileList.extension.st
  src/Tool-FileList/FileList.class.st
Labels: Status: Tests passed please review!

#17107 Remove duplicated ZipArchive class>>#extractAllIn:
  src/Compression/ZipArchive.class.st
Labels: Status: Tests passed please review!

#17114 Remove debugger code overriding itself
  src/Debugging-Core/Process.extension.st
Labels: Status: Tests passed please review!

#17115 Make finder more configurable
  src/Tool-Finder/MethodFinder.class.st
Labels: Status: Tests passed please review!

#17089 Implements a menu option to profile the selected method in Calypso
  src/Calypso-SystemTools-Core/SycProfileTestMethodCommand.extension.st
  src/SystemCommands-MethodCommands/SycMethodCmCommand.class.st
  src/SystemCommands-MethodCommands/SycProfileTestMethodCommand.class.st
Labels: Type: Enhancement, Status: Tests passed please review!

#17122 Update DarkBlueTheme background color
  src/DarkBlueTheme/DarkBlueThemeConfigurator.class.st
Labels: Status: Tests passed please review!

#17126 17058-ASTLiteralValueNodesourceText-leads-to-infinite-recursion-when-value-is-a-BreakDebugPoint
  src/AST-Core/ASTLiteralValueNode.class.st
  src/AST-Core/RBSimpleFormatter.class.st
  src/EnlumineurFormatter/EFFormatter.class.st
Labels: Status: Tests passed please review!

#17125 Remove unused RBSlotInitializationNode
  src/ClassParser/RBSlotInitializationNode.class.st
  src/Kernel-ExtraUtils/ClassHierarchyPrinterTest.class.st
Labels: Status: Tests passed please review!

#17118 17029-port-to-P13
  src/ThreadedFFI-UFFI-Tests/TFUFFIConcurrencyTest.class.st
  src/UnifiedFFI/FFICalloutAPI.class.st
Labels: Status: Tests passed please review!

#17134 Rename notices to start by AST instead of RB
  src/AST-Core/ASTErrorNotice.class.st
  src/AST-Core/ASTNotice.class.st
  src/AST-Core/ASTParseErrorNode.class.st
  src/AST-Core/ASTProgramNode.class.st
  src/AST-Core/ASTSyntaxErrorNotice.class.st
  src/AST-Core/ASTWarningNotice.class.st
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/OpalCompiler-Core/ASTNotice.extension.st
  src/OpalCompiler-Core/OCUndeclaredVariableNotice.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/OpalCompiler-Core/RBNotice.extension.st
Labels: Status: Tests passed please review!

#17101 Migrate "Extra" class commands to Commander 2
  src/BaselineOfCalypso/BaselineOfCalypso.class.st
  src/Calypso-Browser/ClyCopyClassNameCommand.class.st
  src/Calypso-Browser/ClyInspectSelectionCommand.class.st
  src/Calypso-Browser/ClyUpdateBrowserCommand.class.st
  src/Calypso-SystemPlugins-FileOut-Browser/ClyFileOutCommand.class.st
  src/Calypso-SystemPlugins-FileOut-Browser/package.st
  src/SystemCommands-ClassCommands/SycClassExtraCmCommand.class.st
  src/SystemCommands-ClassCommands/SycCmCopyClassNameCommand.class.st
  src/SystemCommands-ClassCommands/SycCmFileOutClassCommand.class.st
  src/SystemCommands-ClassCommands/SycCmInspectClassCommand.class.st
  src/SystemCommands-ClassCommands/SycCmUpdateClassCommand.class.st
Labels: Project: Calypso, Type: Cleanup, Status: Tests passed please review!

#17145 Update some dialog icons to remove deprecated ways to declare them
  src/Polymorph-Widgets/AlertDialogWindow.class.st
  src/Polymorph-Widgets/DenyDialogWindow.class.st
  src/Polymorph-Widgets/ErrorDialogWindow.class.st
  src/Polymorph-Widgets/MessageDialogWindow.class.st
Labels: Status: Tests passed please review!

#16816 Migrated references of `SycMethodNameEditorPresenter` to `StMethodNameEditorPresenter`
  src/BaselineOfQA/BaselineOfQA.class.st
  src/NautilusRefactoring/NautilusRefactoring.class.st
  src/SystemCommands-MessageCommands/SycChangeMessageSignatureCommand.class.st
  src/SystemCommands-MessageCommands/SycMessageDescription.class.st
  src/SystemCommands-MessageCommands/SycReplaceMessageCommand.class.st
  src/SystemCommands-RefactoringSupport-Tests/StMethodNameEditorPresenterTest.class.st
  src/SystemCommands-RefactoringSupport-Tests/SycMethodNameEditorTest.class.st
  src/SystemCommands-RefactoringSupport/SycMethodNameEditorPresenter.class.st
  src/SystemCommands-SourceCodeCommands/SycExtractMethodAndOccurrencesCommand.class.st
  src/SystemCommands-SourceCodeCommands/SycExtractMethodCommand.class.st
Labels: Status: Need more work

#17137 Manage changes of theme for the morph sliders
  src/Morphic-Widgets-Scrolling/PluggableSliderMorph.class.st
  src/Morphic-Widgets-Scrolling/SliderMorph.class.st
Labels: Status: Tests passed please review!

#17156 Added traits: example to the FluidClassDefinition doc
  doc/FluidClassDefinition/FluidClassDefinition.md
Labels: more-information-needed

#17133 [P13] 17130-Improve-the-allocation-of-holders-used-by-SDL
  src/FFI-Kernel/ExternalAddress.class.st
  src/OSWindow-SDL2/OSSDL2BackendWindow.class.st
  src/OSWindow-SDL2/OSSDL2GLRenderer.class.st
Labels: Status: Tests passed please review!

#17147 Move "Extras" menu item to last position in the Calypso Class menu
  src/SystemCommands-ClassCommands/SycOpenExtraInClassMenuCommand.class.st
Labels: Easy

#17177 Cleanup: remove not used SystemSettingLauncher
  src/System-Settings-Browser/SettingTreeBuilder.class.st
  src/System-Settings-Browser/SystemSettingLauncher.class.st
Labels: Status: Tests passed please review!

#17172 Differentiate Morph scale factor from World zoom factor.
  src/Morphic-Core/WorldMorph.class.st
  src/OSWindow-Core/OSWorldRenderer.class.st
Labels: Status: Tests passed please review!

#17181 Move NumberParsingTests to NumberParser-Tests package
  src/NumberParser-Tests/NumberParsingTest.class.st
Labels: Status: Tests passed please review!

#17180 Improve the Duplicate class refactoring
  src/Refactoring-Core/ReCopyClassRefactoring.class.st
  src/Refactoring-UI/ReClassInteractionDriver.class.st
  src/Refactoring-UI/ReDuplicateClassDriver.class.st
  src/Refactoring-UI/StClassAndMethodsSelectionPresenter.class.st
Labels: Status: Tests passed please review!

#17178 Deprecate BlockClosure>>#valueWithoutNotifications
  src/Deprecated13/BlockClosure.extension.st
  src/System-Announcements/BlockClosure.extension.st
Labels: Status: Tests passed please review!

#17176 Add some useful methods on Color
  src/Colors/Color.class.st
Labels: Status: Tests passed please review!
