Repository pharo-project/pharo, pull requests merged in 2024-10, with the labels that each got.

#17199 Fix bug in loading of methods that failed to load before
  src/Kernel-CodeModel/ClassDescription.class.st
  src/Kernel-Tests/MethodAnnouncementsTest.class.st
Labels: Status: Tests passed please review!

#17187 Adding the generation of a preference file from Pharo First version without the possibility to edit it.
  src/StartupPreferences/StartupPreferencesLoader.class.st
  src/System-Settings-Browser/StartupPreferencesLoader.extension.st
Labels: more-information-needed

#17159 Cleaning of #dialog: method in GraphicFontSettings
  src/Settings-Graphics/GraphicFontSettings.class.st
  src/System-Settings-Core/PragmaSetting.class.st
  src/System-Settings-Core/SettingDeclaration.class.st
Labels: Type: Cleanup

#17201 [Refactorings] Fix classes and traits iteration API
  src/Deprecated13/RBBrowserEnvironment.extension.st
  src/Refactoring-Critics/RBSmalllintChecker.class.st
  src/Refactoring-Environment/RBBrowserEnvironment.class.st
  src/Tool-Finder/FinderClassesSearchStrategy.class.st
  src/Tool-Finder/FinderSearchStrategy.class.st
Labels: Status: Need more work, Status: Discussion

#17237 17139-isInClassHierarchyOf-does-not-work-for-Metaclasses
  src/Kernel-CodeModel/Behavior.class.st
  src/Kernel-Tests/BehaviorTest.class.st
  src/Reflectivity/Class.extension.st
Labels: Status: Tests passed please review!

#17174 Detach Calypso navigation model
  src/BaselineOfCalypso/BaselineOfCalypso.class.st
  src/BaselineOfCalypsoNavigationModel/BaselineOfCalypsoNavigationModel.class.st
  src/BaselineOfCalypsoNavigationModel/package.st
  src/System-Dependencies-Tests/SystemDependenciesTest.class.st
Labels: Project: Calypso, Type: Cleanup, Status: Tests passed please review!

#17246 Fix Generate accessors does not work anymore in the source code pane
  src/Refactoring-Core/RBCreateAccessorsForVariableTransformation.class.st
  src/SystemCommands-RefactoringSupport-Tests/SycRefactoringPreviewMockCommand.class.st
  src/SystemCommands-RefactoringSupport/SycRefactoringPreviewPresenter.class.st
  src/SystemCommands-VariableCommands/SycGenerateVariableAccessorCommand.class.st
Labels: Project: Calypso, Status: Tests passed please review!, Project: Refactorings

#17242 Cleaning monolithic extract method
  src/Refactoring-Core/RBExtractMethodRefactoring.class.st
  src/Refactoring-Core/RBExtractSetUpMethodRefactoring.class.st
  src/Refactoring-Transformations-Tests/RBExtractSetUpMethodAndOccurrencesParametrizedTest.class.st
  src/Refactoring-Transformations-Tests/RBExtractSetUpMethodParametrizedTest.class.st
Labels: Status: Tests passed please review!

#17260 Restore the Calypso tab copy button to copy method name(s) to Clipboard
  src/Calypso-SystemTools-Core/SycCopyMethodNameToClypboardCommand.extension.st
  src/SystemCommands-MethodCommands/SycCopyMethodNameToClypboardCommand.class.st
Labels: Type: Enhancement, Project: Calypso, Version: Pharo 13

#17268 Support methods for the new setting browser
  src/Renraku/ReSettings.class.st
  src/Settings-System/SystemSystemSettings.class.st
  src/System-Settings-Core/ActionSettingDeclaration.class.st
  src/System-Settings-Core/PragmaSetting.class.st
Labels: Type: Enhancement

#17271 Stupid method categorization fix
  src/Refactoring-Core/RBRenameInstanceVariableRefactoring.class.st
Labels: Project: Refactorings, Version: Pharo 13

#17263 Use allNonMetaClasses in Duplicate Class driver
  src/Refactoring-UI/ReDuplicateClassDriver.class.st
Labels: Easy, Project: Refactorings

#17279 reintroduce waitTimeoutMSecs:
  src/System-Time/Semaphore.extension.st
Labels: Status: Tests passed please review!

#17179 Remove hardcoded SystemAnnouncer in System-Sources
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/SUnit-Core/ClassFactoryForTestCase.class.st
  src/System-Sources/ChangesLog.class.st
Labels: Status: Tests passed please review!

#17282 Fix renaming protocol with no method
  src/Calypso-SystemTools-FullBrowser/ClyRenameProtocolCommand.class.st
Labels: Status: Tests passed please review!

#17281 Add owning class info to Protocol
  src/Kernel-CodeModel/ClassDescription.class.st
  src/Kernel-CodeModel/Protocol.class.st
  src/Kernel-Tests/ClassDescriptionProtocolsTest.class.st
  src/Kernel-Tests/ProtocolAnnouncementsTest.class.st
  src/SystemCommands-RefactoringSupport/CmdCommand.extension.st
Labels: Status: Tests passed please review!

#17273 Fix export settings
  src/System-Settings-Core/Object.extension.st
  src/System-Settings-Core/SettingDeclaration.class.st
  src/System-Settings-Core/SystemSettingsPersistence.class.st
Labels: Status: Tests passed please review!, Version: Pharo 13

#17300 Migrate Rename Temporary to use the Driver architecture
  src/Refactoring-Core/RBCondition.class.st
  src/Refactoring-Core/RBRenameArgumentOrTemporaryRefactoring.class.st
  src/Refactoring-UI/RBInteractionDriver.class.st
  src/Refactoring-UI/ReExtractMethodDriver.class.st
  src/Refactoring-UI/ReRenameArgumentOrTemporaryDriver.class.st
  src/Refactoring-UI/ReRenameClassDriver.class.st
  src/SystemCommands-SourceCodeCommands/SycRenameArgOrTempCommand.class.st
Labels: Status: Reviewed and Ready to Integrate

#17290 restore Pharo13 branches for NewTools and Spec
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: Status: Tests passed please review!

#17283 Simplify progress bar theme management
  src/Morphic-Base/ProgressBarMorph.class.st
  src/Morphic-Base/SystemProgressMorph.class.st
  src/Polymorph-Widgets/SystemWindow.extension.st
  src/Polymorph-Widgets/UITheme.class.st
  src/Polymorph-Widgets/UIThemeColorConfigurator.class.st
  src/Polymorph-Widgets/UIThemePalette.class.st
Labels: Status: Tests passed please review!

#17317 Fix typo: change "The cyclomatic complexity is heigh" to "The cyclomatic complexity is high"
  src/General-Rules/ReCyclomaticComplexityRule.class.st
Labels: Status: Tests passed please review!

#17311 Major update of the Keymap Descriptions to a Shortcuts Editor
  src/Commander-Activators-Shortcut/CmdShortcutActivation.class.st
  src/Keymapping-Core/KMCategory.class.st
  src/Keymapping-Tools-Spec/KMCategory.extension.st
  src/Keymapping-Tools-Spec/KMCategoryItemPresenter.class.st
  src/Keymapping-Tools-Spec/KMDescriptionPresenter.class.st
  src/Keymapping-Tools-Spec/KMKeymap.extension.st
  src/Keymapping-Tools-Spec/SpDropListPresenter.extension.st
  src/System-Dependencies-Tests/SystemDependenciesTest.class.st
Labels: Type: Enhancement, Status: Tests passed please review!, Version: Pharo 13

#17321 Prevent raising an Error in updateSettingNode: during image start
  src/System-Settings-Core/ActionSettingDeclaration.class.st
Labels: Status: Tests passed please review!

#16831 fix #16799: Better api for beReadOnlyObject
  src/Kernel-Extended-Tests/WriteBarrierTest.class.st
  src/Kernel/Object.class.st
Labels: Status: Need more work
