Repository pharo-project/pharo, pull requests merged in 2024-05, with the labels that each got.

#16563 Renaming DebugPointSideEffect into DebugPointMetaBehavior
  src/DebugPoints/ChainBehavior.class.st
  src/DebugPoints/CountBehavior.class.st
  src/DebugPoints/DebugPointMetaBehavior.class.st
  src/DebugPoints/OnceBehavior.class.st
  src/DebugPoints/ScriptBehavior.class.st
  src/DebugPoints/TranscriptBehavior.class.st
Labels: Status: Reviewed and Ready to Integrate

#16578 prof stef lesson view did not understand has binding of
  src/ProfStef-Core/LessonView.class.st
Labels: backport

#16582 16576-Problem-with-completion-in-the-tutorial
  src/ProfStef-Core/LessonView.class.st
Labels: Status: Tests passed please review!

#16552 Taskbar option to close windows hidden behind other windows
  src/Morphic-Widgets-Taskbar/SystemWindow.extension.st
Labels: Status: Tests passed please review!

#16584 Fixing reflectivity tests that can randomly fail because of unstable and unpredictable tests generating methods
  src/Reflectivity-Tests/LinkInstallerTest.class.st
  src/Reflectivity-Tests/ReflectivityExamples2.class.st
Labels: Status: Tests passed please review!

#16588 Cleanup: TestCase class>>#lastRunMethodNamed:
  src/SUnit-Core/TestCase.class.st
Labels: Status: Tests passed please review!

#16586 Cleanup: TestCase class>>#hasErrorTest, TestCase class>>#hasPassedTest and TestCase class>>#hasFailedTest
  src/SUnit-Core/TestCase.class.st
Labels: Status: Tests passed please review!

#16385 Changed 'Transcript show:' construct to 'self trace'
  src/Beacon-Core/TranscriptLogger.class.st
  src/DebugPoints/TranscriptBehavior.class.st
  src/Refactoring-Critics-Tests/RBSmalllintTestObject.class.st
Labels: Status: Tests passed please review!

#16595 Update roassal to v1.06d
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: Status: Tests passed please review!

#16583 proposition refactoring -> Cleanup: 2 duplicated methods in FreeType
  src/EmbeddedFreeType/AbstractFreeTypeFontFile.class.st
  src/EmbeddedFreeType/EmbeddedFreeTypeFontInstaller.class.st
  src/EmbeddedFreeType/FreeTypeFontFileInstaller.class.st
  src/EmbeddedFreeType/FreeTypeFontFileUpdator.class.st
  src/FreeType/FreeTypeFontProvider.class.st
Labels: Status: Need more work

#16474 tests for rules from the General-Rules package
  src/General-Rules-Tests/ReClassNotCategorizedRuleTest.class.st
  src/General-Rules-Tests/ReClassVariableCapitalizationRuleTest.class.st
  src/General-Rules-Tests/ReEquivalentSuperclassMethodsRuleTest.class.st
  src/General-Rules-Tests/ReExcessiveInheritanceRuleTest.class.st
  src/General-Rules-Tests/ReExcessiveVariablesRuleTest.class.st
  src/General-Rules-Tests/ReInconsistentMethodClassificationRuleTest.class.st
  src/General-Rules-Tests/ReLongMethodsRuleTest.class.st
  src/General-Rules-Tests/ReRefersToClassRuleTest.class.st
  src/Renraku/ReNodeRewriteRule.class.st
Labels: Status: Need more work

#16621 Package "System-DependenciesTests" should be "System-Dependencies-Tests"
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/System-Dependencies-Tests/SystemDependenciesReportResource.class.st
  src/System-Dependencies-Tests/SystemDependenciesTest.class.st
  src/System-Dependencies-Tests/package.st
  src/System-DependenciesTests/package.st
Labels: Status: Tests passed please review!

#16628 Cleanup: AthensTransformTest>>transformClass should be in accessing
  src/Athens-Cairo-Tests/AthensCairoMatrixTest.class.st
  src/Athens-Core-Tests/AthensAffineTransformTest.class.st
  src/Athens-Core-Tests/AthensProjectiveTransformTest.class.st
  src/Athens-Core-Tests/AthensTransformTest.class.st
Labels: Status: Tests passed please review!

#16623 Simplify script pragma for FinderUI
  src/Tool-Finder-UI/FinderUI.class.st
Labels: Easy, Status: Tests passed please review!

#16619 CommentTestCase should be moved to PharoDocComment-Tests
  src/PharoDocComment-Tests/CommentTestCase.class.st
Labels: Status: Tests passed please review!

#16613 Cleanup: CoverageCollectorTest should be in an own test package
  src/BaselineOfSUnit/BaselineOfSUnit.class.st
  src/Coverage-Tests/CoverageCollectorTest.class.st
  src/Coverage-Tests/package.st
  src/Tools-Tests/ProjectManagerTest.class.st
Labels: Status: Tests passed please review!

#16626 Introduce CompiledMethod>>#isInstanceSide
  src/Kernel-CodeModel/CompiledMethod.class.st
  src/Kernel-Extended-Tests/CompiledMethodTest.class.st
Labels: Status: Tests passed please review!

#16615 Enhancement: Provide a lint rule to check for a "super initialize" call in instance side #initialize methods
  src/General-Rules-Tests/ReShouldSendSuperInitializeAsFirstMessageTest.class.st
  src/SUnit-Rules/ReShouldSendSuperInitializeAsFirstMessage.class.st
Labels: Status: Tests passed please review!

#16565 Issue 16430 - String>> asSymbol no protected against concurrent access (alternative solution)
  src/Collections-Strings/Symbol.class.st
  src/Collections-Strings/SymbolTableSemaphore.class.st
  src/PharoBootstrap/PBAbstractImageBuilder.class.st
Labels: Status: Tests passed please review!

#16651 SourceFile>>#isOpen should use isNotNil
  src/System-Sources/SourceFile.class.st
Labels: Status: Tests passed please review!

#16649 Review ReClassNotCategorizedRuleTest>>#testRule
  src/General-Rules-Tests/ReClassNotCategorizedRuleTest.class.st
Labels: Status: Tests passed please review!

#16644 Add missing RGGlobalVariable>>isInstanceVariable
  src/Ring-Core/RGGlobalVariable.class.st
Labels: Status: Tests passed please review!

#16653 Sindarin/ScriptableDebugger should be listed as external project
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: Status: Tests passed please review!

#16601 Clean up in SDL_Texture and SDL_Renderer
  src/OSWindow-SDL2/SDL_Renderer.class.st
  src/OSWindow-SDL2/SDL_Texture.class.st
Labels: Status: Tests passed please review!

#16648 Improve ReBaselineProperlyPackagedRule and ReBaselineWithProperSuperclassRule and cover with tests
  src/General-Rules-Tests/ReBaselineProperlyPackagedRuleTest.class.st
  src/General-Rules-Tests/ReBaselineWithProperSuperclassRuleTest.class.st
  src/General-Rules/ReBaselineProperlyPackagedRule.class.st
  src/General-Rules/ReBaselineWithProperSuperclassRule.class.st
Labels: Status: Tests passed please review!

#16663 15652-Check-and-add-test-for--CompiledCodenewFrom
  src/Kernel-CodeModel/CompiledBlock.class.st
  src/Kernel-CodeModel/CompiledCode.class.st
  src/Kernel-Tests/CompiledCodeTest.class.st
Labels: Status: Tests passed please review!

#16347 Make class abstract driver
  src/Refactoring-Core/RBAbstractClass.class.st
  src/Refactoring-Core/RBMakeClassAbstractTransformation.class.st
  src/Refactoring-DataForTesting/RBClassWithoutSelfClassReferenceTest.class.st
  src/Refactoring-DataForTesting/RBWithSelfClassReferenceTest.class.st
  src/Refactoring-Transformations-Tests/RBAbstractRefactoringTest.class.st
  src/Refactoring-Transformations-Tests/RBMakeClassAbstractParametrizedTest.class.st
  src/Refactoring-UI-Tests/ReMakeClassAbstractDriverTest.class.st
  src/Refactoring-UI/RBInteractionDriver.class.st
  src/Refactoring-UI/RBMakeClassAbstractDriver.class.st
  src/SystemCommands-ClassCommands/SycCMakeAbstractCommand.class.st
Labels: Project: Refactorings

#16489 Reflectivity fixing bytecode to ast mapping
  src/Reflectivity-Tests/ReflectiveMethodTest.class.st
  src/Reflectivity/CompiledMethod.extension.st
  src/Reflectivity/RBMethodNode.extension.st
  src/Reflectivity/ReflectiveMethod.class.st
Labels: Status: Need more work

#16562 Fix a small bug with FFI calls when passing 'NULL' as argument to the C function
  src/UnifiedFFI/FFIStrictResolutionMode.class.st
Labels: Status: Tests passed please review!

#16722 Fix multiple bugs in metaclass management of ShiftClassBuilder
  src/Shift-ClassBuilder-Tests/ShClassInstallerTest.class.st
  src/Shift-ClassBuilder/ShDefaultBuilderEnhancer.class.st
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/System-Dependencies-Tests/SystemDependenciesTest.class.st
  src/Traits-Tests/ShTraitBuilderTest.class.st
  src/Traits-Tests/ShTraitInstallerTest.class.st
  src/Traits/ShiftClassBuilder.extension.st
  src/Traits/TraitBuilderEnhancer.class.st
Labels: Status: Tests passed please review!

#16353 Add subclass driver
  src/Refactoring-Core/RBAbstractClass.class.st
  src/Refactoring-Core/RBClass.class.st
  src/Refactoring-Core/RBInsertNewClassRefactoring.class.st
  src/Refactoring-Core/RBMakeClassAbstractTransformation.class.st
  src/Refactoring-DataForTesting/RBClassWithoutSelfClassReferenceTest.class.st
  src/Refactoring-DataForTesting/RBRootClassForInsertingSubclasses.class.st
  src/Refactoring-DataForTesting/RBWithSelfClassReferenceTest.class.st
  src/Refactoring-Transformations-Tests/RBAbstractRefactoringTest.class.st
  src/Refactoring-Transformations-Tests/RBMakeClassAbstractParametrizedTest.class.st
  src/Refactoring-UI-Tests/ReAddSubclassDriverTest.class.st
  src/Refactoring-UI-Tests/ReMakeClassAbstractDriverTest.class.st
  src/Refactoring-UI/RBInteractionDriver.class.st
  src/Refactoring-UI/RBMakeClassAbstractDriver.class.st
  src/Refactoring-UI/ReAddSubclassDriver.class.st
  src/Refactoring-UI/StRefactoringAddClassPresenter.class.st
  src/SystemCommands-ClassCommands/SycCMakeAbstractCommand.class.st
  src/SystemCommands-ClassCommands/SycClassCmCommand.class.st
  src/SystemCommands-ClassCommands/SycCmAddSubclassCommand.class.st
  src/SystemCommands-ClassCommands/SycCmInsertSubclassCommand.class.st
  src/SystemCommands-ClassCommands/SycCmInsertSuperclassCommand.class.st
  src/SystemCommands-ClassCommands/SycCmNewClassCreationCommand.class.st
Labels: Project: Refactorings
