Repository pharo-project/pharo, pull requests merged in 2024-03, with the labels that each got.

#16264 16246-CI-Failing-test-SystemDependenciesTesttestExternalIDEDependencies
  src/System-DependenciesTests/SystemDependenciesTest.class.st
Labels: Status: Tests passed please review!

#16253 Fix for: UFFI/TFFI call for WebBrowser with specific URL length adds strange characters to the URL #15980
  src/WebBrowser-Core/WBWindowsWebBrowser.class.st
Labels: Status: Need more work, Pharo 10

#16260 Fix Bug: `OrderedDictionary>>#at:at:put:` not updating ordered keys
  src/Collections-Sequenceable-Tests/OrderedDictionaryTest.class.st
  src/Collections-Sequenceable/OrderedDictionary.class.st
Labels: Type: Bug, Status: Tests passed please review!, Version: Pharo 12, To fix before release

#16274 Restore original message String
  src/SystemCommands-SourceCodeCommands/SycInlineMethodCommand.class.st
Labels: Status: Tests passed please review!, Project: Refactorings, Version: Pharo 12

#16273 Fix Method name editor dialog up/down buttons
  src/Refactoring-UI/RERenameMethodDriver.class.st
  src/Refactoring-UI/StMethodNameEditorPresenter.class.st
Labels: Project: Refactorings, Version: Pharo 12

#16279 Remove unused instance variable in #ReRenameMethodRefactoring
  src/Refactoring-Core/ReRenameMethodRefactoring.class.st
Labels: Type: Cleanup, Version: Pharo 12

#16225 Fix #magnifyBy:smoothing: on OSSDL2ExternalForm
  src/OSWindow-SDL2/OSSDL2ExternalForm.class.st
Labels: Status: Tests passed please review!

#16281 Prevents asking for user input twice during the Pushing up method refactoring
  src/Refactoring-UI/RBPushUpMethodDriver.class.st
Labels: Status: Tests passed please review!

#16254 16233-ChangeRecordtimeStamp-calls-deprecated-method
  src/System-Changes/ChangeRecord.class.st
Labels: Status: Tests passed please review!

#16293 Fixing issue #16291 - RBRemoveDirectAccessToVariableTransformationTest is failing
  src/Refactoring-Transformations-Tests/RBRemoveDirectAccessToVariableTransformationTest.class.st
Labels: Status: Tests passed please review!

#16297 15564-No-menubar-in-Mac-OS-Sonoma
  src/OSWindow-SDL2/ObjCLibrary.class.st
  src/OSWindow-SDL2/SDLAbstractPlatform.class.st
  src/OSWindow-SDL2/SDLNullPlatform.class.st
  src/OSWindow-SDL2/SDLOSXPharoMenu.class.st
  src/OSWindow-SDL2/SDLOSXPlatform.class.st
  src/OSWindow-SDL2/SDLUnixPlatform.class.st
  src/OSWindow-SDL2/SDLWindowsPlatform.class.st
Labels: Status: Tests passed please review!

#16306 Fix parsing twice per keystroke in Calypso
  src/Calypso-SystemTools-Core/ClyMethodEditorToolMorph.class.st
Labels: Type: Bug

#16302 Take the selector into account in #AdditionalMethodState>>#analogousCodeTo:
  src/Kernel-CodeModel/AdditionalMethodState.class.st
  src/Kernel-Extended-Tests/AdditionalMethodStateTest.class.st
Labels: Version: Pharo 12, To fix before release

#16349 Remove old backward compatibility code from FFILibrary
  src/ReleaseTests/ReleaseTest.class.st
  src/UnifiedFFI/FFILibrary.class.st
Labels: Status: Tests passed please review!
