Repository pharo-project/pharo, pull requests merged in 2024-07, with the labels that each got.

#16868 Fix failing tests making CI to fail
  src/Debugger-Oups-Tests/OupsDummyDebuggerSystem.class.st
  src/Reflectivity-Tests/MetaLinkAnonymousClassBuilderTest.class.st
Labels: Priority: High

#16864 Small PR to add support to set class rules in the Smallint checker
  src/General-Rules-Tests/ReSmalllintTest.class.st
  src/Renraku/ReSmalllintChecker.class.st
  src/SystemCommands-ClassCommands/SycCmDuplicateClassCommand.class.st
Labels: Type: Enhancement

#16886 Update FormSet to not recompute each scalling all the time
  src/Graphics-Display Objects/CachedFormSet.class.st
  src/Morphic-Base/AlphaImageMorph.class.st
Labels: Status: Tests passed please review!

#16906 fix testThatThereAreNoSelectorsRemainingThatAreSentButNotImplemented
  src/Reflectivity/MetaLinkInstaller.class.st
Labels: Status: Need more work

#16915 Move UnifiedDiffJoinSection to Pharo
  src/Tool-Diff/UnifiedDiffChangesMorph.class.st
  src/Tool-Diff/UnifiedDiffJoinSection.class.st
Labels: Status: Tests passed please review!

#16887 [Backport] Update FormSet to not recompute each scalling all the time
  src/Graphics-Display Objects/CachedFormSet.class.st
  src/Morphic-Base/AlphaImageMorph.class.st
Labels: Status: Tests passed please review!

#16932 Add custom comparator support to SequenceableCollection
  src/Collections-Abstract-Tests/TIndexAccess.trait.st
  src/Collections-Sequenceable/SequenceableCollection.class.st
Labels: Type: Enhancement, Version: Pharo 13

#16920 Catch CmCommandAborted in Calypso
  src/Calypso-SystemTools-Core/ClyMethodEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClyMethodExtensionSwitchMorph.class.st
  src/Calypso-SystemTools-Core/ClyProtocolEditorMorph.class.st
  src/Calypso-SystemTools-FullBrowser/ClyBrowserMorph.extension.st
Labels: Status: Tests passed please review!

#16936 Fix bug in protocol management of Traits
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/Traits-Tests/ShTraitInstallerTest.class.st
Labels: Status: Tests passed please review!

#16949 Monticello: remove dead code and some Morphic UI
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/Monticello-Tests/MCWorkingCopyTest.class.st
  src/Monticello/MCVersionNameAndMessageRequest.class.st
  src/Monticello/MCWorkingCopy.class.st
  src/MonticelloGUI/MCSaveVersionDialog.class.st
  src/MonticelloGUI/MCVersionNameAndMessageRequest.extension.st
Labels: Status: Tests passed please review!

#16928 Remove usage of cached repository from file base repositories
  src/Monticello/MCFileBasedRepository.class.st
  src/Monticello/MCRepository.class.st
  src/MonticelloRemoteRepositories/MCFtpRepository.class.st
  src/MonticelloRemoteRepositories/MCHttpRepository.class.st
  src/MonticelloRemoteRepositories/MCRemoteFileBasedRepository.class.st
Labels: Status: Tests passed please review!

#16919 Adding "OnStack replacement" feature to Reflectivity
  src/BaselineOfReflectivity/BaselineOfReflectivity.class.st
  src/OpalCompiler-Core/CompiledBlock.extension.st
  src/OpalCompiler-Core/CompiledMethod.extension.st
  src/OpalCompiler-Core/RBBlockNode.extension.st
  src/OpalCompiler-Core/RBMethodNode.extension.st
  src/Reflectivity-Tests/ReflectivityExampleOnStack.class.st
  src/Reflectivity-Tests/ReflectivityOnStackTest.class.st
  src/Reflectivity/Context.extension.st
  src/Reflectivity/Process.extension.st
  src/Reflectivity/ProcessorScheduler.extension.st
  src/Reflectivity/RFReflectivityASTCacheStrategy.class.st
  src/Reflectivity/ReflectiveMethod.class.st
Labels: Status: Tests passed please review!

#16235 Fix clean blocks serialization
  src/Fuel-Core-Tests/FLBlockClosureSerializationTest.class.st
  src/Fuel-Core-Tests/FLFullBlockClosureSerializationTest.class.st
  src/Fuel-Core-Tests/FLSerializationTest.class.st
  src/Fuel-Core/FLGlobalCompiledBlockCluster.class.st
  src/Fuel-Core/FLGlobalCompiledCodeCluster.class.st
  src/Fuel-Core/FLGlobalCompiledMethodCluster.class.st
  src/Fuel-Core/FLMethodChanged.class.st
  src/Fuel-Core/FLVariableObjectCluster.class.st
  src/Kernel-CodeModel/BlockClosure.class.st
  src/Kernel-CodeModel/CleanBlockClosure.class.st
  src/Kernel-CodeModel/CompiledBlock.class.st
  src/Kernel-CodeModel/CompiledMethod.class.st
  src/Kernel-CodeModel/ConstantBlockClosure.class.st
  src/Kernel-Tests/BlockClosureTest.class.st
Labels: Status: Tests passed please review!

#16952 Remove MCTool
  src/Monticello/MCLazyVersionInfo.class.st
  src/MonticelloGUI/MCLazyVersionInfo.extension.st
  src/MonticelloGUI/MCSnapshotBrowser.class.st
  src/MonticelloGUI/MCTool.class.st
Labels: Status: Tests passed please review!

#16962 Fix for SettingsBrowser shows rule class and not rule text
  src/Renraku/ReRuleManager.class.st
Labels: Easy, Status: Tests passed please review!

#16967 Fix Duplicate class command UX issues
  src/Refactoring-UI/ReDuplicateClassDriver.class.st
  src/Refactoring-UI/StClassAndMethodsSelectionPresenter.class.st
Labels: Type: Enhancement

#16966 A small fix in a FileReference method comment, as suggested by @Ducasse
  src/FileSystem-Core/FileSystem.class.st
Labels: Easy

#16955 16923-ReferenceFinder-should-not-look-at-ephemeron-references
  src/ReferenceFinder-Core/ReferenceFinder.class.st
  src/ReferenceFinder-Core/ReferenceFinderTest.class.st
Labels: Status: Tests passed please review!
