Repository pharo-project/pharo, pull requests merged in 2024-04, with the labels that each got.

#16379 New tools parent menu entry
  src/Morphic-Base/Object.extension.st
  src/Morphic-Base/WorldState.extension.st
Labels: Easy, Status: Tests passed please review!, Version: Pharo 12

#16400 Provide a default String for settings without #default: sends.
  src/System-Settings-Core/SettingDeclaration.class.st
Labels: Type: Bug, Version: Pharo 12

#16384 Fix Generate Equals and Hash DNU
  src/SystemCommands-ClassCommands/SycGenerateEqualAndHashCommand.class.st
Labels: Project: Refactorings

#16409 Do not suggest trait when deprecating a class
  src/Refactoring-UI/RBDeprecateClassDriver.class.st
Labels: Status: Tests passed please review!

#16404 Exclude some commands from virtual method groups on Calypso
  src/Calypso-SystemQueries/ClyExternalPackageMethodGroup.class.st
  src/Calypso-SystemQueries/ClyMethodGroup.class.st
  src/Calypso-SystemTools-FullBrowser/ClyConvertMethodGroupToProtocolCommand.class.st
  src/Calypso-SystemTools-FullBrowser/ClyFullBrowserContext.class.st
  src/Calypso-SystemTools-FullBrowser/ClyMoveMethodGroupsToPackageCommand.class.st
Labels: Status: Tests passed please review!

#16382 quick fix that hide the debug context menus when there are unsaved changes
  src/Calypso-SystemPlugins-Reflectivity-Browser/ClyDebuggingCommand.class.st
  src/Calypso-SystemTools-Core/ClySourceCodeContext.class.st
  src/Commander-Core/CmdToolContext.class.st
Labels: Status: Tests passed please review!

#16408 16407-RBNodes-errorNotices-creates-unneeded-empty-collections
  src/AST-Core/RBProgramNode.class.st
Labels: Version: Pharo 12

#16401 Add support for Epicea file out
  src/Epicea-Tests/EpCodeChangeIntegrationTest.class.st
  src/Epicea/EpBehaviorCommentChange.class.st
  src/Epicea/EpBehaviorNameChange.class.st
  src/Epicea/EpClassModification.class.st
  src/Epicea/TestCase.extension.st
Labels: Type: Bug, Version: Pharo 12

#16421 Fix Refactorings should have help menus to explain their actions
  src/Calypso-Browser/ClyBrowserCommand.class.st
  src/Calypso-SystemPlugins-FileOut-Browser/ClyFileOutCommand.class.st
  src/Calypso-SystemPlugins-Traits-Browser/ClyCreateClassCommand.class.st
  src/Calypso-SystemPlugins-Traits-Browser/ClyCreateTestCaseCommand.class.st
  src/Calypso-SystemTools-QueryBrowser/ClyShowTraitUsersCommand.class.st
  src/SystemCommands-ClassCommands/SycClassCommand.class.st
  src/SystemCommands-ClassCommands/SycDuplicateClassCommand.class.st
  src/SystemCommands-ClassCommands/SycGenerateEqualAndHashCommand.class.st
  src/SystemCommands-ClassCommands/SycGeneratePrintOnCommand.class.st
  src/SystemCommands-ClassCommands/SycRemoveClassCommand.class.st
  src/SystemCommands-ClassCommands/SycRenameClassCommand.class.st
  src/SystemCommands-ClassCommands/SycSingleClassCommand.class.st
  src/SystemCommands-RefactoringSupport/SycCmCommand.class.st
Labels: Version: Pharo 12, To fix before release

#16420 Reposition Calypso contextual class menu items
  src/Calypso-SystemTools-Core/SycBrowseClassCommand.extension.st
  src/Calypso-SystemTools-Core/SycDeprecateClassCommand.extension.st
  src/Calypso-SystemTools-Core/SycRenameClassCommand.extension.st
Labels: Type: Bug, To fix before release

#16417 Use #setUp instead of #initialize for test cases
  src/SUnit-Tests/FailingTearDownTest.class.st
  src/Tools-CodeNavigation-Tests/CNSelectorExtractorTest.class.st
Labels: Status: Tests passed please review!

#16416 Remove CharacterTable
  src/Kernel/Character.class.st
  src/PharoBootstrap/PBAbstractImageBuilder.class.st
Labels: Status: Tests passed please review!

#16429 Add Toplo world menu entry
  src/BaselineOfPharo/BaselineOfPharo.class.st
  src/BaselineOfPharo/BlLoadProjectWorldMenu.class.st
Labels: more-information-needed

#16427 Add LibTTY providing access to the VM library for spawning a process connected to a pseudo-terminal
  src/UnifiedFFI-Tests/LibTTYTest.class.st
  src/UnifiedFFI/LibC.class.st
  src/UnifiedFFI/LibCTypes.class.st
  src/UnifiedFFI/LibTTY.class.st
Labels: Status: Tests passed please review!

#16466 16355-Wrong-class-definition-creates-strange-DNUs
  src/Calypso-SystemQueries/ClyScopedSystemEnvironment.class.st
  src/Calypso-SystemQueries/ClySystemEnvironment.class.st
  src/ClassParser/CDUnrecognizedClassPart.class.st
Labels: Status: Tests passed please review!, Version: Pharo 12, To fix before release

#16422 Update the Playground shortcut
  src/Deprecated12/ToolShortcutsCategory.extension.st
  src/MenuRegistration/MenuRegistrationExample.class.st
  src/Morphic-Base/Object.extension.st
  src/Morphic-Base/PluggableMenuSpec.extension.st
  src/Tool-Base/PharoShortcuts.class.st
  src/Tool-Base/ToolShortcutsCategory.class.st
  src/Tool-Registry/ToolRegistry.class.st
Labels: Status: Tests passed please review!

#16469 Do not select the # in symbol selection
  src/Rubric-Tests/RubTextEditorTest.class.st
  src/Rubric/RubTextEditor.class.st
Labels: Status: Tests passed please review!, To fix before release

#16434 Clean package generation of "Jump to test class"
  src/Calypso-SystemPlugins-SUnit-Browser/TClyGenerateTestClass.trait.st
Labels: Easy

#16470 Restore fileIn button in File Browser
  src/System-FileRegistry/FileList.extension.st
  src/Tool-ExternalBrowser/ExternalBrowser.class.st
Labels: Project: Tools, Version: Pharo 12

#16473 Fix bug while adding a trait to a class without trait
  src/Traits-Tests/TraitTest.class.st
  src/Traits/Metaclass.extension.st
Labels: Status: Tests passed please review!, To fix before release

#16487 Fix 16345: serialization of classes with traits in hierarchy
  src/Shift-ClassBuilder-Tests/ShiftClassBuilderTest.class.st
  src/Traits-Tests/TraitSubclassingTraitedClassTest.class.st
  src/Traits-Tests/TraitTest.class.st
  src/Traits/TraitedMetaclass.class.st
Labels: Status: Tests passed please review!

#16477 Font-Tests: #testIsAbstractClass should be testIsAbstract like in oth…
  src/Fonts-Infrastructure-Tests/AbstractFontFamilyMemberTest.class.st
  src/Fonts-Infrastructure-Tests/AbstractFontFamilyTest.class.st
  src/Fonts-Infrastructure-Tests/AbstractFontProviderTest.class.st
Labels: Version: Pharo 12

#16444 Fix: rename method loop
  src/Refactoring-Core/RBAbstractTransformation.class.st
  src/Refactoring-Core/RBNewAbstractCondition.class.st
  src/Refactoring-Core/RBPullUpClassVariableRefactoring.class.st
  src/Refactoring-Core/ReBlockCondition.class.st
  src/Refactoring-Core/ReClassesCondition.class.st
  src/Refactoring-Core/ReMethodsCondition.class.st
  src/Refactoring-Core/ReNameIsGlobalCondition.class.st
  src/Refactoring-Core/ReReifiedCondition.class.st
  src/Refactoring-Core/ReRenameMethodRefactoring.class.st
  src/Refactoring-Core/ReSubtreeCondition.class.st
  src/Refactoring-Core/ReValidClassNameCondition.class.st
  src/Refactoring-UI-Tests/ReRenameMethodDriverTest.class.st
  src/Refactoring-UI/ReRenameMethodDriver.class.st
Labels: Status: Tests passed please review!, To fix before release

#16493 Remove calypso context from search dialogs
  src/Calypso-Browser/ClyBrowserDialogContext.class.st
  src/Calypso-SystemTools-FullBrowser/ClySystemSearchDialogContext.extension.st
  src/Calypso-SystemTools-QueryBrowser/ClySystemSearchDialogContext.extension.st
  src/Morphic-Widgets-Windows/DialogWindowMorph.class.st
Labels: Status: Tests passed please review!

#16503 Clean System-Announcements-Tests
  src/Announcements-Core-Tests/AnnouncerTest.class.st
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/System-Announcements-Tests/SystemAnnouncerLiveTest.class.st
  src/System-Announcements-Tests/SystemAnnouncerTest.class.st
  src/System-Announcements-Tests/package.st
Labels: Status: Tests passed please review!

#16490 Issue 16462
  src/SystemCommands-MethodCommands/SycFindAndReplaceSetUpCommand.class.st
  src/SystemCommands-MethodCommands/SycOpenAdvancedDebuggingInMethodMenuCommand.class.st
  src/SystemCommands-MethodCommands/SycOpenDebuggingInMethodMenuCommand.class.st
  src/SystemCommands-MethodCommands/SycOpenReflectivityInMethodMenuCommand.class.st
  src/SystemCommands-MethodCommands/SycPushDownMethodCommand.class.st
  src/SystemCommands-MethodCommands/SycPushDownMethodInSomeClassesCommand.class.st
  src/SystemCommands-MethodCommands/SycPushUpMethodCommand.class.st
  src/SystemCommands-MethodCommands/SycRefactoringMethodCommand.class.st
  src/SystemCommands-MethodCommands/SycRemoveMethodsInHierarchyCommand.class.st
Labels: Status: Tests passed please review!

#16486 During compilation there are redundant allocation of collections
  src/Files/AbstractBinaryFileStream.class.st
  src/System-Sources/ChunkWriteStream.class.st
Labels: Status: Reviewed and Ready to Integrate

#16172 Release waiting processes when destroying a socket (without ThreadedFFI dependency)
  src/Network-Kernel/Socket.class.st
  src/Network-Tests/SocketStreamTest.class.st
Labels: Status: Tests passed please review!, To fix before release

#16519 P13 use branch repository
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: Status: Tests passed please review!

#16418 Rename SqueakEpoch to Epoch
  src/Refactoring-Core-Tests/RBSharedPoolTest.class.st
  src/System-Time/ChronologyConstants.class.st
  src/System-Time/Date.class.st
  src/System-Time/DateAndTime.class.st
Labels: Status: Reviewed and Ready to Integrate

#16518 New pass at removing SystemAnnouncer references
  src/ClassAnnotation/ClassAnnotationRegistry.class.st
  src/DebugPoints-Tests/DebugPointObserverTest.class.st
  src/DebugPoints/DebugPointManager.class.st
  src/Epicea/EpMonitor.class.st
  src/General-Rules/ReImplementedNotSentRule.class.st
  src/Kernel-Tests/AbstractClassDescriptionAnnouncementTest.class.st
  src/Reflectivity/ReflectiveMethod.class.st
  src/Renraku/ReRuleManager.class.st
  src/Ring-Definitions-Core-Tests/RGMethodDefinitionTest.class.st
  src/System-Support-Tests/SystemNavigationTest.class.st
  src/Traits/TaAbstractComposition.class.st
Labels: Status: Tests passed please review!

#16336 Announcer: Return early if there isn't any subscriber
  src/Announcements-Core/Announcer.class.st
  src/Announcements-Core/SubscriptionRegistry.class.st
Labels: Type: Enhancement, Status: Tests passed please review!, Version: Pharo 13

#16524 5 test for rules
  src/General-Rules-Tests/ReAssignmentInIfTrueRuleTest.class.st
  src/General-Rules-Tests/ReAssignmentWithoutEffectRuleTest.class.st
  src/General-Rules-Tests/ReBetweenAndRuleTest.class.st
  src/General-Rules-Tests/ReTemporaryNeitherReadNorWrittenRuleTest.class.st
  src/General-Rules-Tests/ReYourselfNotUsedRuleTest.class.st
Labels: Status: Tests passed please review!

#16419 Change #shrinkTo: on FreeTypeCache to selectively remove entries rather than all of them
  src/FreeType-Tests/FreeTypeCacheTest.class.st
  src/FreeType/FreeTypeCache.class.st
  src/FreeType/FreeTypeCacheLinkedList.class.st
  src/FreeType/FreeTypeFont.class.st
Labels: Status: Tests passed please review!

#16478 Add Toplo world menu entry (part 2)
  src/Tool-Registry/PharoCommonTools.class.st
Labels: Status: Tests passed please review!, Version: Pharo 12
