Repository pharo-project/pharo, pull requests merged in 2024-01, with the labels that each got.

#15881 2023 12 29 rename method driver
  src/Calypso-SystemTools-Core/SycRenameMessage2Command.extension.st
  src/Refactoring-Core-Tests/ReHierarchyDefinesMethodTest.class.st
  src/Refactoring-Core-Tests/ReUpToRootDefinesMethodTest.class.st
  src/Refactoring-Core/RBAbstractTransformation.class.st
  src/Refactoring-Core/RBClassCondition.class.st
  src/Refactoring-Core/RBClassNameCondition.class.st
  src/Refactoring-Core/RBMoveMethodToClassSideRefactoring.class.st
  src/Refactoring-Core/RBPullUpMethodRefactoring.class.st
  src/Refactoring-Core/RBPushDownMethodRefactoring.class.st
  src/Refactoring-Core/RBRemoveInstanceVariableRefactoring.class.st
  src/Refactoring-Core/RBRemoveMethodRefactoring.class.st
  src/Refactoring-Core/RBRemoveSharedVariableRefactoring.class.st
  src/Refactoring-Core/RBRenameMethodRefactoring.class.st
  src/Refactoring-Core/REHierarchyDefinesMethod.class.st
  src/Refactoring-Core/REUpToRootDefinesMethod.class.st
  src/Refactoring-Core/ReBlockCondition.class.st
  src/Refactoring-Core/ReRenameMethodRefactoring.class.st
  src/Refactoring-Transformations-Tests/RBRenameMethodParametrizedTest.class.st
  src/Refactoring-Transformations-Tests/RBRenameMethodRefactoringTest.class.st
  src/Refactoring-UI/RBRenameMethodDriver.class.st
  src/Refactoring-UI/RERenameMethodDriver.class.st
  src/SystemCommands-ClassCommands/SycRenameClassCommand.class.st
  src/SystemCommands-MessageCommands/SycRenameMessageCommand.class.st
Labels: Status: Need help

#15842 Add Search filter to Epicea
  src/Epicea/EpCodeChange.class.st
  src/Epicea/EpMethodChange.class.st
  src/Epicea/EpPackageChange.class.st
  src/Epicea/EpPackageTagChange.class.st
  src/Epicea/TestCase.extension.st
  src/EpiceaBrowsers-Tests/EpFileOutModificationsTest.class.st
  src/EpiceaBrowsers/EpLogBrowserPresenter.class.st
  src/EpiceaBrowsers/EpLogBrowserToolbarPresenter.class.st
  src/Ombu/OmEntry.class.st
Labels: Project: Tools

#15908 Fix #15907 Remove teachable and teachableTest
  src/SUnit-MockObjects-Tests/TeachableTest.class.st
  src/SUnit-MockObjects/Teachable.class.st
Labels: more-information-needed

#15854 Fixed obvious unnecessary users of duration.
  src/AST-Core/ASTTypingVisitor.class.st
  src/Announcements-Core-Tests/AnnouncerTest.class.st
  src/Announcements-Core-Tests/WeakAnnouncerTest.class.st
  src/Debugger-Model/DebugSession.class.st
  src/DrTests-TestsProfiling/DTTestsProfilerVisitor.class.st
  src/Flashback-Decompiler-Tests/FBDExamples.class.st
  src/FuzzyMatcher-Tests/FuzzyMatcherExample.class.st
  src/JenkinsTools-Core/HDTestReport.class.st
  src/Jobs/Job.class.st
  src/Kernel-Chronology-Extras/BlockClosure.extension.st
  src/Kernel-Chronology-Extras/Duration.class.st
  src/Kernel-CodeModel/BlockClosure.class.st
  src/Kernel-Tests-Extended/ContextTest.extension.st
  src/Kernel-Tests-Extended/ProcessTest.class.st
  src/Kernel-Tests-Extended/ValueWithinFixTest.class.st
  src/Kernel-Tests/ExceptionTester.class.st
  src/Kernel/Delay.class.st
  src/Morphic-Examples/TabExample.class.st
  src/Morphic-Tests/DelaySchedulerBackgroundWorkerMorph.class.st
  src/Morphic-Widgets-Basic/PluggableButtonMorph.class.st
  src/Morphic-Widgets-Tabs/TabMorph.class.st
  src/Network-Tests/UUIDGeneratorTest.class.st
  src/Network-Tests/UUIDTest.class.st
  src/SUnit-Core-Traits/TAssertable.trait.st
  src/SUnit-Core/TestAsserter.class.st
  src/SUnit-Tests/ProcessMonitorTestServiceTest.class.st
  src/SUnit-Tests/SUnitExtensionsTest.class.st
  src/System-Caching-Tests/TTLCacheTest.class.st
  src/System-Support/VirtualMachine.class.st
  src/Tool-Profilers/BlockClosure.extension.st
  src/Traits-Tests/TimeMeasuringTest.class.st
Labels: Status: Tests passed please review!

#15917 Doing a pass on comments and protocol to improve understanding the mock
  src/SUnit-Core/ClassFactoryForTestCase.class.st
  src/SUnit-MockObjects-Tests/MockBasicAPITest.class.st
  src/SUnit-MockObjects-Tests/MockMessageArgumentTest.class.st
  src/SUnit-MockObjects-Tests/MockMessageSequenceTest.class.st
  src/SUnit-MockObjects-Tests/MockVerifyMessageTest.class.st
  src/SUnit-MockObjects-Tests/MyClassUsingMock2Test.class.st
  src/SUnit-MockObjects/MockBasicObject.class.st
  src/SUnit-MockObjects/MockMessageSend.class.st
  src/SUnit-MockObjects/MockObject.class.st
  src/SUnit-MockObjects/TestCase.extension.st
Labels: more-information-needed

#15632 Fix a bug in return simulation
  src/Debugging-Core/Context.extension.st
  src/Kernel-CodeModel/Context.class.st
  src/Kernel-Tests-Extended/ContextTest.extension.st
  src/Kernel-Tests-Extended/InstructionStreamTest.class.st
Labels: Status: Need more work, Status: Discussion

#15897 Deprecate Gofer
  bootstrap/scripts/03-metacello-bootstrap/01-loadMetacello.st
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfMetacello/BaselineOfMetacello.class.st
  src/Gofer-Core/MCFileBasedRepository.extension.st
  src/Gofer-Core/ManifestGoferCore.class.st
  src/Gofer-Core/package.st
  src/Gofer-Deprecated/Gofer.class.st
  src/Gofer-Deprecated/Gofer.extension.st
  src/Gofer-Deprecated/GoferApiTest.extension.st
  src/Gofer-Deprecated/GoferConfigurationReference.class.st
  src/Gofer-Deprecated/GoferLoad.class.st
  src/Gofer-Deprecated/GoferOperation.class.st
  src/Gofer-Deprecated/GoferOperationTest.extension.st
  src/Gofer-Deprecated/GoferPackageReference.class.st
  src/Gofer-Deprecated/GoferReference.class.st
  src/Gofer-Deprecated/GoferReferenceTest.extension.st
  src/Gofer-Deprecated/GoferRepositoryError.class.st
  src/Gofer-Deprecated/GoferResolvedReference.class.st
  src/Gofer-Deprecated/GoferResolvedReference.extension.st
  src/Gofer-Deprecated/GoferVersionReference.class.st
  src/Gofer-Deprecated/MCDictionaryRepository.extension.st
  src/Gofer-Deprecated/MCDirectoryRepository.extension.st
  src/Gofer-Deprecated/MCFileBasedRepository.extension.st
  src/Gofer-Deprecated/MCRepository.extension.st
  src/Gofer-Tests/GoferApiTest.class.st
  src/Gofer-Tests/GoferOperationTest.class.st
  src/Gofer-Tests/GoferReferenceTest.class.st
  src/Gofer-Tests/GoferResource.class.st
  src/Gofer-Tests/GoferTest.class.st
  src/Gofer-Tests/package.st
  src/Metacello-GitBasedRepository/MCGitBasedNetworkRepository.class.st
  src/Monticello/MCFileBasedRepository.class.st
Labels: Status: Need more work

#15666 Extend FFIExternalStructureReferenceHandle with tfPointerAddress
  src/ThreadedFFI-UFFI-Tests/TFUFFIStructuresTest.class.st
  src/ThreadedFFI-UFFI/FFIExternalStructureReferenceHandle.extension.st
Labels: Status: Tests passed please review!

#15966 Adding documentation on the rewrite rules
  doc/Rewrite/1-Introduction.md
  doc/Rewrite/2-CodePattern.md
  doc/Rewrite/3-ParseTreeSearcher
  doc/Rewrite/4-Examples
Labels: more-information-needed

#15981 Fix: cannot move method to class side
  src/Refactoring-Core/RBCompositeRefactoring.class.st
  src/Refactoring-Core/RBMethodsHaveNoSendersCondition.class.st
  src/Refactoring-Core/RBRefactoring.class.st
  src/Refactoring-Core/RBRefactoringError.class.st
  src/Refactoring-Core/RBRefactoringWarning.class.st
  src/Refactoring-Core/RBRemoveMethodsRefactoring.class.st
Labels: Status: Tests passed please review!

#15986 Improve the way to know if a class includes a trait
  src/Traits/Behavior.extension.st
  src/Traits/TaAbstractComposition.class.st
  src/Traits/TaCompositionElement.class.st
  src/Traits/TaEmptyComposition.class.st
  src/Traits/TaSequence.class.st
  src/Traits/TaSingleComposition.class.st
  src/Traits/TraitedClass.class.st
  src/Traits/TraitedMetaclass.class.st
Labels: Status: Tests passed please review!

#15992 Add missing caret in #textToDisplay method.
  src/Refactoring-Changes/RBRenameVariableChange.class.st
Labels: Project: Refactorings, Version: Pharo 12

#16005 Categorize methods in Metacello
  src/Metacello-Core/MetacelloProjectSpec.class.st
  src/Metacello-Core/MetacelloVersionSpec.class.st
Labels: Easy

#15987 [Backport] Improve the way to know if a class includes a trait
  src/TraitsV2/Behavior.extension.st
  src/TraitsV2/TaAbstractComposition.class.st
  src/TraitsV2/TaCompositionElement.class.st
  src/TraitsV2/TaEmptyComposition.class.st
  src/TraitsV2/TaSequence.class.st
  src/TraitsV2/TaSingleComposition.class.st
  src/TraitsV2/TraitedClass.class.st
  src/TraitsV2/TraitedMetaclass.class.st
Labels: Status: Tests passed please review!

#16010 Fix for Wrong text selection: selection selects an extra character
  src/Calypso-Browser-Tests/ClyTextEditorToolMorphTest.class.st
  src/Calypso-Browser/ClyTextEditorToolMorph.class.st
  src/Calypso-SystemTools-QueryBrowser/ClyTextEditor.extension.st
Labels: Project: Tools, Status: Need more work, Version: Pharo 12

#16020 Refactor refactoring preconditions
  src/Refactoring-Core/RBAbstractTransformation.class.st
  src/Refactoring-Core/RBAbstractVariablesRefactoring.class.st
  src/Refactoring-Core/RBAddMethodRefactoring.class.st
  src/Refactoring-Core/RBChildrenToSiblingsRefactoring.class.st
  src/Refactoring-Core/RBCopyClassRefactoring.class.st
  src/Refactoring-Core/RBDeprecateClassRefactoring.class.st
  src/Refactoring-Core/RBExpandReferencedPoolsRefactoring.class.st
  src/Refactoring-Core/RBExtractMethodAndOccurrences.class.st
  src/Refactoring-Core/RBExtractMethodToComponentRefactoring.class.st
  src/Refactoring-Core/RBExtractToTemporaryRefactoring.class.st
  src/Refactoring-Core/RBFindAndReplaceTransformation.class.st
  src/Refactoring-Core/RBGenerateEqualHashTransformation.class.st
  src/Refactoring-Core/RBGeneratePrintOnTransformation.class.st
  src/Refactoring-Core/RBInlineAllSendersRefactoring.class.st
  src/Refactoring-Core/RBInlineTemporaryRefactoring.class.st
  src/Refactoring-Core/RBInsertNewClassRefactoring.class.st
  src/Refactoring-Core/RBMethodRefactoring.class.st
  src/Refactoring-Core/RBMoveMethodToClassRefactoring.class.st
  src/Refactoring-Core/RBMoveVariableDefinitionToSmallestValidScopeRefactoring.class.st
  src/Refactoring-Core/RBPrettyPrintCodeTransformation.class.st
  src/Refactoring-Core/RBRefactoring.class.st
  src/Refactoring-Core/RBRegexRefactoring.class.st
  src/Refactoring-Core/RBRenameArgumentOrTemporaryRefactoring.class.st
  src/Refactoring-Core/RBReplaceMessageSendTransformation.class.st
  src/Refactoring-Core/RBSplitCascadeRefactoring.class.st
  src/Refactoring-Core/RBSplitClassRefactoring.class.st
  src/Refactoring-Core/RBSwapMethodRefactoring.class.st
  src/Refactoring-Core/RBTemporaryToInstanceVariableRefactoring.class.st
  src/Refactoring-Core/ReRenameClassRefactoring.class.st
  src/Refactoring-Transformations-Tests/RBAbstractRefactoringTest.class.st
  src/Refactoring-Transformations/RBTransformation.class.st
Labels: Status: Tests passed please review!

#16022 Refactor: change method name preconditions
  src/Refactoring-Core/RBAddParameterRefactoring.class.st
  src/Refactoring-Core/RBChangeMethodNameRefactoring.class.st
  src/Refactoring-Core/RBInlineParameterRefactoring.class.st
  src/Refactoring-Core/RBParameterRemovalRefactoring.class.st
  src/Refactoring-Core/RBRemoveParameterRefactoring.class.st
Labels: Status: Tests passed please review!

#16009 Fixes for browsing a package from a repository using Calypso
  src/Calypso-Ring/RGBehavior.extension.st
  src/Calypso-Ring/RGMetaclassStrategy.extension.st
  src/Calypso-Ring/RGMethod.extension.st
  src/Calypso-Ring/RGObject.extension.st
  src/Calypso-SystemQueries/ClyMethodDefinitionProperty.class.st
  src/Calypso-SystemQueries/ClyMethodsInProtocolQuery.class.st
  src/Calypso-SystemQueries/ClyUnclassifiedMethodsQuery.class.st
  src/Calypso-SystemQueries/ClyUntaggedClassesQuery.class.st
  src/Calypso-SystemQueries/MethodRecategorized.extension.st
  src/Calypso-SystemTools-Core/ClyMethodCodeEditorToolMorph.class.st
  src/Refactoring-Core/REHierarchyDefinesMethod.class.st
  src/Refactoring-Core/REUpToRootDefinesMethod.class.st
  src/Rubric-Styling/RubShoutStylerDecorator.class.st
  src/SystemCommands-ClassCommands/SycCMakeAbstractCommand.class.st
  src/SystemCommands-ClassCommands/SycDeprecateClassCmCommand.class.st
  src/SystemCommands-ClassCommands/SycDeprecateClassCommand.class.st
Labels: Project: Calypso, Status: Need more work, Version: Pharo 12

#16066 SycBrowseClassCommand fix for Browse to class in method editor
  src/SystemCommands-ClassCommands/SycBrowseClassCommand.class.st
Labels: Project: Calypso, Version: Pharo 12

#16074 Expand the dependency analyzer roots by default
  src/Tool-DependencyAnalyser-UI/DAPackageTreePresenter.class.st
Labels: Status: Tests passed please review!
