Repository pharo-project/pharo, pull requests merged in 2024-02, with the labels that each got.

#14497 SortedCollection should not implement #addLast: (fixes #9286)
  src/Collections-Abstract-Tests/SplitJoinTest.class.st
  src/Collections-Sequenceable-Tests/SortedCollectionTest.class.st
  src/Collections-Sequenceable/OrderedCollection.class.st
  src/Collections-Sequenceable/SortedCollection.class.st
  src/Collections-Unordered/SmallDictionary.class.st
Labels: Status: Need more work

#16068 Remove UIManager dependencies from Compression.
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/Compression/ZipArchive.class.st
  src/System-Spec/Archive.extension.st
  src/System-Spec/GZipReadStream.extension.st
  src/System-Spec/StPharoApplication.extension.st
  src/System-Spec/ZipArchive.extension.st
  src/System-Spec/package.st
Labels: Type: Cleanup, Version: Pharo 12

#15979 Report exception message text when class definition loading fails
  src/Monticello/MCPackageLoader.class.st
Labels: Type: Enhancement, Version: Pharo 12

#16102 Refactor: remove preconditions from extract method's `buildTransformations`
  src/Refactoring-Core-Tests/RBParsableSubtreeConditionTest.class.st
  src/Refactoring-Core/ReParsableSubtreeCondition.class.st
  src/Refactoring-Transformations/RBExtractMethodTransformation.class.st
Labels: Status: Tests passed please review!

#16097 Just renamed two classes
  src/Refactoring-Core/ReCompositeContinuingRefactoring.class.st
  src/Refactoring-Core/ReUpFrontPreconditionCheckingCompositeRefactoring.class.st
  src/Refactoring-UI/ReRemoveInstanceVariablesDriver.class.st
  src/Refactoring-UI/ReRemoveSharedVariablesDriver.class.st
Labels: more-information-needed

#15977 Remove object initialization from bootstrap
  src/PharoBootstrap/PBAbstractImageBuilder.class.st
Labels: Status: Tests passed please review!

#16100 16057-Cleanup-use-cascaded-nextPutAll-in-LocaleIDstoreOn
  src/System-Localization/LocaleID.class.st
Labels: Status: Tests passed please review!

#16115 15965-CI-Failing-tests-on-the-CI-ReleaseTeststestThatThereAreNoSelectorsRemainingThatAreSentButNotImplemented
  src/Kernel-Tests/DeprecationTest.class.st
Labels: Status: Tests passed please review!

#15978 Fix bug in class trait composition export
  src/Shift-ClassBuilder/ShiftClassBuilder.class.st
  src/Traits-Tests/TraitSubclassingTraitedClassTest.class.st
  src/Traits/TraitBuilderEnhancer.class.st
Labels: Status: Tests passed please review!

#16124 Avoid merged tags without abbrev parameter for vm download in bootstrap script
  bootstrap/scripts/envversion.sh
Labels: Project: Bootstrap

#16120 Rename RPackage-Tests
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/BaselineOfGeneralTests/BaselineOfGeneralTests.class.st
  src/Kernel-CodeModel-Tests/PackageAndClassesTest.class.st
  src/Kernel-CodeModel-Tests/PackageAndMethodsTest.class.st
  src/Kernel-CodeModel-Tests/PackageAndTraitOnModelTest.class.st
  src/Kernel-CodeModel-Tests/PackageAndTraitsTest.class.st
  src/Kernel-CodeModel-Tests/PackageAnnouncementsTest.class.st
  src/Kernel-CodeModel-Tests/PackageObsoleteTest.class.st
  src/Kernel-CodeModel-Tests/PackageOnModelTest.class.st
  src/Kernel-CodeModel-Tests/PackageOrganizerTest.class.st
  src/Kernel-CodeModel-Tests/PackageRenameTest.class.st
  src/Kernel-CodeModel-Tests/PackageTagTest.class.st
  src/Kernel-CodeModel-Tests/PackageTest.class.st
  src/Kernel-CodeModel-Tests/PackageTestCase.class.st
  src/Kernel-CodeModel-Tests/UndefinedPackageTagTest.class.st
  src/Kernel-CodeModel-Tests/UndefinedPackageTest.class.st
  src/Kernel-CodeModel-Tests/package.st
  src/RPackage-Tests/package.st
Labels: Status: Tests passed please review!

#16129 6082-Fixed-makeResolved-collection-juggling
  src/Ring-Core-Tests/RGLayoutDefinitionTest.class.st
  src/Ring-Core/RGPointerLayout.class.st
Labels: Status: Tests passed please review!

#16128 use #isPinnedInMemory instead of isPinned
  src/ThreadedFFI/PointerUtils.class.st
Labels: Status: Tests passed please review!

#16142 16055-Cleanup-uses-cascaded-nextPutAll-in-ObjectstoreOn
  src/Kernel/Object.class.st
Labels: Status: Tests passed please review!

#16157 16133 transforming deprecation should not raise a debugger by default but rewrite the code
  src/Kernel/Deprecation.class.st
Labels: Status: Tests passed please review!

#16159 16153-AST-testIsClean-and-testHasNonLocalReturn-failing-and-more
  src/AST-Core/RBArrayNode.class.st
Labels: Status: Tests passed please review!

#16152 #asUncommentedCode is deprecated, we can remove the test
  src/Collections-Strings-Tests/StringTest.class.st
Labels: Status: Tests passed please review!

#16151 15733-OldClassDefinitionBuilder-needs-to-support-usesinstanceVariableNames
  src/CodeImport/OldClassDefinitionBuilder.class.st
Labels: Status: Tests passed please review!

#15683 Activate strict FFI
  src/Athens-Cairo/AthensCairoCanvas.class.st
  src/Athens-Cairo/CairoFontMetricsProvider.class.st
  src/OSWindow-SDL2/SDL2.class.st
  src/OSWindow-SDL2/SDL_Renderer.class.st
  src/OSWindow-SDL2/SDL_Texture.class.st
  src/System-OSEnvironments/UnixEnvironment.class.st
  src/UnifiedFFI-Tests/FFICalloutAPITest.class.st
  src/UnifiedFFI/FFILibrary.class.st
  src/UnifiedFFI/FFIStrictResolutionMode.class.st
Labels: Status: Need more work

#16030 Author removal v2
  bootstrap/scripts/emulation/shrink.st
  doc/RefactoringEngine/5-PatternMatcher.md
  doc/RefactoringEngine/6-Environment.md
  src/AST-Core/RBParseTreeRewriter.class.st
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/BaselineOfMorphic/BaselineOfMorphic.class.st
  src/Deprecated12/MetacelloPlatform.extension.st
  src/Epicea-Tests/EpTestLogBuilder.class.st
  src/Epicea/EpLog.class.st
  src/Epicea/EpMonitor.class.st
  src/Epicea/EpProtocolRemoval.class.st
  src/EpiceaBrowsers-Tests/EpFileOutModificationsTest.class.st
  src/EpiceaBrowsers/EpLogBrowserPresenter.class.st
  src/JenkinsTools-Core/HDTestReport.class.st
  src/Kernel-CodeModel/ClassDescription.class.st
  src/Kernel-CodeModel/Slot.class.st
  src/Kernel/Deprecation.class.st
  src/Manifest-Core/Package.extension.st
  src/Monticello-Tests/MCMockDependency.class.st
  src/Monticello-Tests/MCTestCase.class.st
  src/Monticello-Tests/MCWorkingCopyTest.class.st
  src/Monticello/MCLazyVersionInfo.class.st
  src/Monticello/MCVersionInfo.class.st
  src/Monticello/MCWorkingAncestry.class.st
  src/Monticello/MCWorkingCopy.class.st
  src/MonticelloFileTree-Core/MCFileTreeAbstractReader.class.st
  src/MonticelloFileTree-Core/MCFileTreeStCypressReader.class.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/Refactoring-Changes/RBRefactoryChange.class.st
  src/Reflectivity-Tools-Tests/BreakpointTest.class.st
  src/Renraku/ReAbstractCritique.class.st
  src/Renraku/ReFeedbacker.class.st
  src/Ring-Definitions-Core-Tests/RGMethodDefinitionTest.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/SUnit-Core/ClassFactoryForTestCase.class.st
  src/Slot-Tests/SlotSilentTest.class.st
  src/StartupPreferences/StartupPreferencesLoader.class.st
  src/System-Settings-Tests/SystemSettingsPersistenceTest.class.st
  src/System-Sources-Tests/SourceFileBufferedReadWriteStreamTest.class.st
  src/System-Support-Tests/AuthorTest.class.st
  src/System-Support/Author.class.st
  src/System-Support/AuthorNameRequest.class.st
  src/System-Support/SmalltalkImage.class.st
  src/Tool-ImageCleaner/ImageCleaner.class.st
  src/UnifiedFFI/FFIStructure.class.st
Labels: Status: Need more work

#16108 improving-snapshot-process-P11
  src/System-BasicCommandLineHandler/SaveCommandLineHandler.class.st
  src/System-SessionManager/SessionManager.class.st
  src/System-Support/SmalltalkImage.class.st
  src/System-Support/SnapshotOperation.class.st
  src/Tool-Base/ToolShortcutsCategory.class.st
Labels: Status: Tests passed please review!

#16170 Make addReturn answer the receiver
  src/AST-Core-Tests/RBProgramNodeTest.class.st
  src/AST-Core/RBSequenceNode.class.st
Labels: Type: Enhancement, Version: Pharo 12

#16168 Replace $r key combination in method editor pane
  src/Calypso-SystemTools-Core/SycSuperclassImplementorsCommand.extension.st
Labels: Project: Calypso, Version: Pharo 12

#16197 Refactor: push down method driver
  src/Refactoring-Core/RBClass.class.st
  src/Refactoring-Core/RBMethod.class.st
  src/Refactoring-Core/RBPushDownMethodRefactoring.class.st
  src/Refactoring-Core/ReClassesAreAbstractCondition.class.st
  src/Refactoring-Core/ReRemoveClassPushingStateToSubclassesRefactoring.class.st
  src/Refactoring-Core/ReSubclassesDontSendSuperCondition.class.st
  src/Refactoring-DataForTesting/MyClassA.class.st
  src/Refactoring-Transformations-Tests/RBPushDownMethodParametrizedTest.class.st
  src/Refactoring-Transformations-Tests/RBPushDownMethodRefactoringTest.class.st
  src/Refactoring-UI-Tests/RePushDownMethodDriverTest.class.st
  src/Refactoring-UI-Tests/StMethodsSelectionPresenterMock.class.st
  src/Refactoring-UI/RBPushDownMethodDriver.class.st
  src/Refactoring-UI/RBPushDownMethodInSomeClassesDriver.class.st
  src/Refactoring-UI/ReBrowseSubclassSuperSendsChoice.class.st
  src/Refactoring-UI/ReMethodChoice.class.st
  src/Refactoring-UI/RePushDownMethodChoice.class.st
  src/Refactoring-UI/RePushDownMethodDriver.class.st
  src/Refactoring-UI/ReRemoveClassDriver.class.st
  src/Refactoring-UI/ReRemoveInstanceVariablesDriver.class.st
  src/Refactoring-UI/StItemsSelectionPresenter.class.st
  src/SystemCommands-MethodCommands/SycPushDownMethodCommand.class.st
Labels: Status: Tests passed please review!

#16198 Fix: extract method failing tests
  src/Refactoring-Transformations-Tests/RBExtractMethodTransformationTest.class.st
  src/Refactoring-Transformations-Tests/ReSemanticsOfExtractMethodTransformationTest.class.st
  src/Refactoring-Transformations/RBExtractMethodTransformation.class.st
Labels: Status: Tests passed please review!

#16206 16132-Caret-return-char-broken-in-Pharo-11-macOS-Keyboard-as-US-International---PC
  src/OSWindow-Core/OSWindowMorphicEventHandler.class.st
Labels: Version: Pharo 12

#16205 16204-RubPluggableTextFieldMorph-does-not-open-drop-list
  src/Polymorph-Widgets/EntryCompletion.class.st
  src/Polymorph-Widgets/IdentifierChooserMorph.class.st
Labels: Version: Pharo 12

#16247 Fix adding slots in Ring
  src/Ring-Core/RGPointerLayout.class.st
Labels: Status: Tests passed please review!
