Repository pharo-project/pharo, pull requests merged in 2024-08, with the labels that each got.

#16961 Remove dead code in Monticello
  src/Deprecated13/MCFileBasedRepository.extension.st
  src/Metacello-GitBasedRepository/MCGitBasedNetworkRepository.class.st
  src/Monticello-BackwardCompatibility/MCDataStream.extension.st
  src/Monticello-GUI-Diff/MCPatchOperation.extension.st
  src/Monticello-GUI-Diff/PSMCMergePatchMorph.class.st
  src/Monticello-Model/MCClassDefinition.class.st
  src/Monticello-Model/MCDefinition.class.st
  src/Monticello-Model/MCMethodDefinition.class.st
  src/Monticello-Tests/MCMergingTest.class.st
  src/Monticello-Tests/MCVersionTest.class.st
  src/Monticello/MCAncestry.class.st
  src/Monticello/MCCacheRepository.class.st
  src/Monticello/MCDataStream.class.st
  src/Monticello/MCDependencySorter.class.st
  src/Monticello/MCDictionaryRepository.class.st
  src/Monticello/MCDirectoryRepository.class.st
  src/Monticello/MCFileBasedRepository.class.st
  src/Monticello/MCLazyVersionInfo.class.st
  src/Monticello/MCMczReader.class.st
  src/Monticello/MCModification.class.st
  src/Monticello/MCPackageLoader.class.st
  src/Monticello/MCPatch.class.st
  src/Monticello/MCPatchOperation.class.st
  src/Monticello/MCRemoval.class.st
  src/Monticello/MCRepository.class.st
  src/Monticello/MCStReader.class.st
  src/Monticello/MCVersion.class.st
  src/Monticello/MCVersionInfo.class.st
  src/Monticello/MCVersionLoader.class.st
  src/Monticello/MCVersionSorter.class.st
  src/Monticello/MCWorkingAncestry.class.st
  src/Monticello/MCWorkingCopy.class.st
  src/Monticello/MonticelloBootstrap.class.st
  src/Monticello/Object.extension.st
  src/Monticello/PackageOrganizer.extension.st
  src/MonticelloFileTree-Core/MCFileBasedRepository.extension.st
  src/MonticelloFileTree-Core/MCFileTreeRepository.class.st
  src/MonticelloFileTree-Core/MCRepository.extension.st
  src/MonticelloGUI/MCAddition.extension.st
  src/MonticelloGUI/MCPatchOperation.extension.st
  src/MonticelloRemoteRepositories/MCFtpRepository.class.st
  src/MonticelloRemoteRepositories/MCHttpRepository.class.st
  src/MonticelloRemoteRepositories/MCSmalltalkhubRepository.class.st
  src/Ring-Definitions-Core/String.extension.st
  src/Ring-Definitions-Tests-Containers/RGPackageDefinitionTest.class.st
Labels: Status: Tests passed please review!

#16948 Move execution environments out of the Kernel
  src/Debugging-Utils/Halt.class.st
  src/Kernel-Tests/ProcessSpecificTest.class.st
  src/SUnit-Core/CurrentExecutionEnvironment.class.st
  src/SUnit-Core/CurrentExecutionEnvironment.extension.st
  src/SUnit-Core/DefaultExecutionEnvironment.class.st
  src/SUnit-Core/DefaultExecutionEnvironment.extension.st
  src/SUnit-Core/ExecutionEnvironment.class.st
  src/SUnit-Core/ExecutionEnvironment.extension.st
  src/SUnit-Core/Halt.extension.st
  src/SUnit-Core/TestExecutionEnvironment.class.st
  src/SUnit-Tests/ExecutionEnvironmentTest.class.st
Labels: Status: Need more work

#16941 fix issue #12916: Autofix of Single branch condition lint removed method comment
  src/General-Rules/ReGuardClauseRule.class.st
Labels: Status: Tests passed please review!

#16977 Remove inspectIn: fix #11750
  src/Refactoring-Environment/RBBrowserEnvironment.class.st
Labels: more-information-needed

#16968 Remove unused ReCollectionMessagesToExternalObjectRule
  src/General-Rules-Tests/ReSmalllintTest.class.st
  src/General-Rules/ReCollectionMessagesToExternalObjectRule.class.st
Labels: Type: Cleanup, Easy, Status: Tests passed please review!

#16982 Add a setting to enable to set the ClyBrowserMorph navigation history
  src/Calypso-Browser/ClyBrowserMorph.class.st
Labels: Type: Enhancement, Project: Calypso

#16997 Missing default setting in Cly navigation history configuraiton
  src/Calypso-Browser/ClyBrowserMorph.class.st
Labels: Easy

#17002 Add Shout code styler tool
  src/BaselineOfShout/BaselineOfShout.class.st
  src/Shout-UI/SHStylePresenter.class.st
  src/Shout-UI/package.st
  src/Shout/SHRBTextStyler.class.st
Labels: Type: Enhancement, Project: Tools, Type: UX

#16998 Fix UndeclaredVariableTest with CleanBlockClosures
  src/Kernel-CodeModel/CleanBlockClosure.class.st
Labels: Status: Tests passed please review!

#16934 Re organisation renraku package
  src/General-Rules-Tests/ReNoNilAssignationInInitializeRuleTest.class.st
  src/General-Rules-Tests/ReNoPrintStringInPrintOnRule.class.st
  src/General-Rules-Tests/RePackageManifestShouldBePackagedInManifestTagRuleTest.class.st
  src/General-Rules-Tests/ReSmalllintTest.class.st
  src/General-Rules-Tests/ReThemeAccessRuleTest.class.st
  src/General-Rules/ReClassNameInSelectorRule.class.st
  src/General-Rules/ReClassVariableCapitalizationRule.class.st
  src/General-Rules/ReCompactSourceCodeRule.class.st
  src/General-Rules/ReGuardClauseRule.class.st
  src/General-Rules/ReInstanceSideBaselineMethodProtocolRule.class.st
  src/General-Rules/ReInstanceSideEqualsMethodProtocolRule.class.st
  src/General-Rules/ReInstanceSideFinalizeMethodProtocolRule.class.st
  src/General-Rules/ReInstanceSideHashMethodProtocolRule.class.st
  src/General-Rules/ReInstanceSideInitializeMethodProtocolRule.class.st
  src/General-Rules/ReInstanceSidePrintOnMethodProtocolRule.class.st
  src/General-Rules/ReInstanceSideSpeciesMethodProtocolRule.class.st
  src/General-Rules/ReInstanceSideValueMethodProtocolRule.class.st
  src/General-Rules/ReInstanceVariableCapitalizationRule.class.st
  src/General-Rules/ReNoNilAssignationInInitializeRule.class.st
  src/General-Rules/RePackageManifestShouldBePackagedInManifestTagRule.class.st
  src/General-Rules/ReProperMethodProtocolNameForAccessingRule.class.st
  src/General-Rules/ReProperMethodProtocolNameForAddingRemovingRule.class.st
  src/General-Rules/ReProperMethodProtocolNameForConvertingRule.class.st
  src/General-Rules/ReProperMethodProtocolNameForFileInOutRule.class.st
  src/General-Rules/ReProperMethodProtocolNameForInstanceCreationRule.class.st
  src/General-Rules/ReProperMethodProtocolNameForRemovalRule.class.st
  src/General-Rules/ReProperMethodProtocolNameForTestsRule.class.st
  src/General-Rules/ReProperMethodProtocolNameForUtilitiesRule.class.st
  src/General-Rules/ReReturnMethodRule.class.st
  src/General-Rules/ReThemeAccessRule.class.st
  src/General-Rules/ReUnclassifiedMethodsRule.class.st
  src/Renraku/ReClassSideInitializeMethodProtocolRule.class.st
  src/Renraku/ReClassSideResetMethodProtocolRule.class.st
  src/Renraku/ReEndTrueFalseRule.class.st
  src/Renraku/ReGuardingClauseRule.class.st
  src/Renraku/ReProperInstanceMethodProtocolRule.class.st
  src/Renraku/ReProperMethodProtocolNameRule.class.st
Labels: Status: Need more work

#17000 Remove references to SystemAnnouncer from Breakpoint tests
  src/Reflectivity-Tools-Tests/BreakpointObserverTest.class.st
  src/Reflectivity-Tools-Tests/BreakpointTest.class.st
  src/System-Support/SystemEnvironment.class.st
Labels: Status: Tests passed please review!

#16674 Remove deprecated classes
  src/BeautifulComments/ClyPackageRichTextCommentEditorToolMorph.class.st
  src/BeautifulComments/ClyRichTextClassCommentEditorToolMorph.class.st
  src/Calypso-Browser/ClyTextEditorToolMorph.class.st
  src/Collections-Sequenceable/Array2D.class.st
  src/Metacello-Core/MetacelloIgnorePackageLoaded.class.st
  src/NautilusRefactoring/ChangesBrowser.class.st
  src/NautilusRefactoring/RewriteRuleChangesBrowser.class.st
  src/NautilusRefactoring/StRewriteRuleChangesBrowserPresenter.class.st
  src/Random-Core/Array2D.extension.st
  src/System-Support/Author.class.st
  src/System-Support/AuthorNameRequest.class.st
Labels: Status: Tests passed please review!

#17007 Fix for Disable push down variable from final class
  src/SystemCommands-VariableCommands/SycPushDownVariableCommand.class.st
Labels: Project: Refactorings

#17011 Fix senders broken in Calypso editors
  src/Calypso-SystemTools-QueryBrowser/ClyBrowserMorph.extension.st
Labels: Priority: Critical

#17014 Enable Calypso to use a custom navigation history
  src/Calypso-Browser/ClyBrowserMorph.class.st
  src/Calypso-Browser/ClyTextEditorToolMorph.class.st
Labels: Project: Calypso, Easy, Status: Tests passed please review!

#17026 Unhook Settings Browser `dialog:` method from Morphic
  src/Morphic-Base/ShortcutReminder.class.st
  src/System-Settings-Browser/SettingNodeBuilder.class.st
  src/System-Settings-Browser/SettingTreeBuilder.class.st
  src/System-Settings-Core/ActionSettingDeclaration.class.st
Labels: Status: Tests passed please review!, Project: Prepare morphic phase out

#16994 Remove usage of Calypso browser search dialog made in Morphic
  src/Calypso-Browser/ClyBrowserMorph.class.st
  src/Calypso-Browser/ClyBrowserSearchDialogWindow.class.st
  src/Calypso-SystemTools-Core/ClyFindClassCommand.class.st
  src/Calypso-SystemTools-Core/ClyMethodEditorToolMorph.class.st
  src/Calypso-SystemTools-Core/ClySystemBrowserContext.class.st
  src/Calypso-SystemTools-FullBrowser/ClyBrowserMorph.extension.st
  src/Calypso-SystemTools-FullBrowser/ClyFindMethodInBrowserCommand.class.st
  src/Calypso-SystemTools-FullBrowser/ClySwitchToScopedModeCommand.class.st
  src/Calypso-SystemTools-FullBrowser/ClyTextEditor.extension.st
  src/Commander2/CmCommandAborted.class.st
  src/SystemCommands-ClassCommands/SycDeprecateClassCommand.class.st
  src/SystemCommands-ClassCommands/SycMigrateReferencesOfClassCommand.class.st
  src/SystemCommands-VariableCommands/SycMergeVariableCommand.class.st
Labels: Status: Tests passed please review!

#17005 Avoid rewriting methods that are not installed
  src/Kernel/Deprecation.class.st
Labels: Status: Reviewed and Ready to Integrate

#16879 Add SocketAddressInformation for IPv6 support
  src/Network-Kernel/NetNameResolver.class.st
  src/Network-Kernel/Socket.class.st
  src/Network-Kernel/SocketAddressInformation.class.st
Labels: Status: Tests passed please review!

#17052 Update External Browser class definition access
  src/Tool-ExternalBrowser/ExternalBrowser.class.st
Labels: Easy
