Repository pharo-project/pharo, pull requests merged in 2024-12, with the labels that each got.

#17475 Do not change the border color of an ImageMorph if it already has a color
  src/Morphic-Base/ImageMorph.class.st
Labels: Status: Tests passed please review!

#17470 Fix ring global variable
  src/Ring-Core/RGGlobalVariable.class.st
Labels: Project: Bootstrap

#17498 Skip some socket tests on windows
  src/Network-Tests/SocketStreamTest.class.st
Labels: Status: Tests passed please review!

#17496 Fix crash of Mac on 4K display
  src/OSWindow-SDL2/SDL_Window.class.st
Labels: Status: Tests passed please review!

#17497 Fix release tests
  src/Rubric/RubWorkspaceExample.class.st
Labels: Status: Tests passed please review!

#17474 Fix #17471: custom Job interruption
  src/Jobs/Job.class.st
  src/Morphic-Base/JobProgressMorph.class.st
Labels: Status: Tests passed please review!

#17526 Better comment in opal
  src/Flashback-Decompiler/FBIRBytecodeDecompiler.class.st
  src/OpalCompiler-Core/IRBytecodeGenerator.class.st
  src/OpalCompiler-Core/IRPrimitive.class.st
  src/OpalCompiler-Core/IRReconstructor.class.st
  src/OpalCompiler-Core/IRReconstructorBuilder.class.st
  src/OpalCompiler-Core/OCASTSemanticCleaner.class.st
Labels: more-information-needed

#17536 Fixing the rename from call site.
  src/Refactoring-Core-Tests/LowLevelReflectiveAPITest.class.st
  src/Refactoring-Core-Tests/RBClassTest.class.st
  src/Refactoring-Core-Tests/RBNamespaceTest.class.st
  src/Refactoring-Core-Tests/RBRefactoringBrowserTest.class.st
  src/Refactoring-Core-Tests/RBSearchTest.class.st
  src/Refactoring-Core-Tests/RBSharedPoolTest.class.st
  src/Refactoring-Core-Tests/RBVariableTypeTest.class.st
  src/Refactoring-Core-Tests/RESafeMethodNameForbasedOnTest.class.st
  src/Refactoring-Core/ReAbstractTransformation.class.st
  src/Refactoring-UI/ReRenameMethodDriver.class.st
Labels: more-information-needed

#17538 Deprecate IRFix
  src/OpalCompiler-Core/IRFix.class.st
  src/OpalCompiler-Core/IRMethod.class.st
  src/OpalCompiler-Core/IRTranslator.class.st
  src/OpalCompiler-Core/IRTranslatorVisitor.class.st
Labels: more-information-needed

#17540 Better class comment for commentTestCase
  src/PharoDocComment-Tests/CommentTestCase.class.st
Labels: more-information-needed

#17564 Resolution for issue 17548 - Removed Network setting BlabEmail
  src/Network-Kernel/NetworkSystemSettings.class.st
Labels: more-information-needed

#17559 Update FFI generation code to not generate multiple time the same methods
  src/FreeType/FTBBox.class.st
  src/FreeType/FTBitmap.class.st
  src/FreeType/FTBitmapSize.class.st
  src/FreeType/FTCharMapRec.class.st
  src/FreeType/FTFaceRec.class.st
  src/FreeType/FTGeneric.class.st
  src/FreeType/FTGlyphMetrics.class.st
  src/FreeType/FTGlyphSlotRec.class.st
  src/FreeType/FTListRec.class.st
  src/FreeType/FTMatrix.class.st
  src/FreeType/FTOutline.class.st
  src/FreeType/FTSizeMetrics.class.st
  src/FreeType/FTSizeRec.class.st
  src/FreeType/FTVector.class.st
  src/General-Rules/ReEquivalentSuperclassMethodsRule.class.st
  src/Kernel-CodeModel/CompiledMethod.class.st
  src/OSWindow-SDL2/SDL_AudioSpec.class.st
  src/OSWindow-SDL2/SDL_ControllerButtonDownEvent.class.st
  src/OSWindow-SDL2/SDL_ControllerButtonUpEvent.class.st
  src/OSWindow-SDL2/SDL_ControllerDeviceAddedEvent.class.st
  src/OSWindow-SDL2/SDL_ControllerDeviceRemappedEvent.class.st
  src/OSWindow-SDL2/SDL_ControllerDeviceRemovedEvent.class.st
  src/OSWindow-SDL2/SDL_DropEvent.class.st
  src/OSWindow-SDL2/SDL_JoyButtonDownEvent.class.st
  src/OSWindow-SDL2/SDL_JoyButtonUpEvent.class.st
  src/OSWindow-SDL2/SDL_JoyDeviceAddedEvent.class.st
  src/OSWindow-SDL2/SDL_JoyDeviceRemovedEvent.class.st
  src/OSWindow-SDL2/SDL_KeyDownEvent.class.st
  src/OSWindow-SDL2/SDL_KeyUpEvent.class.st
  src/OSWindow-SDL2/SDL_MouseButtonDownEvent.class.st
  src/OSWindow-SDL2/SDL_MouseButtonUpEvent.class.st
  src/OSWindow-SDL2/SDL_Palette.class.st
  src/OSWindow-SDL2/SDL_PixelFormat.class.st
  src/OSWindow-SDL2/SDL_QuitEvent.class.st
  src/OSWindow-SDL2/SDL_RendererInfo.class.st
  src/OSWindow-SDL2/SDL_Surface.class.st
  src/OSWindow-SDL2/SDL_SysWMEvent.class.st
  src/OSWindow-SDL2/SDL_SysWMinfo_AndroidInfo.class.st
  src/OSWindow-SDL2/SDL_SysWMinfo_CocoaInfo.class.st
  src/OSWindow-SDL2/SDL_SysWMinfo_DirectFBInfo.class.st
  src/OSWindow-SDL2/SDL_SysWMinfo_InfoUnion.class.st
  src/OSWindow-SDL2/SDL_SysWMinfo_MirInfo.class.st
  src/OSWindow-SDL2/SDL_SysWMinfo_UIKitInfo.class.st
  src/OSWindow-SDL2/SDL_SysWMinfo_WaylandInfo.class.st
  src/OSWindow-SDL2/SDL_SysWMinfo_WindowsInfo.class.st
  src/OSWindow-SDL2/SDL_SysWMinfo_WindowsRTInfo.class.st
  src/OSWindow-SDL2/SDL_SysWMinfo_X11Info.class.st
  src/OSWindow-SDL2/SDL_SysWMmsgUnion.class.st
  src/OSWindow-SDL2/SDL_SysWMmsg_Windows.class.st
  src/OSWindow-SDL2/SDL_TouchFingerDownEvent.class.st
  src/OSWindow-SDL2/SDL_TouchFingerMotionEvent.class.st
  src/OSWindow-SDL2/SDL_TouchFingerUpEvent.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/ThreadedFFI-Tests/TFInnerTestStruct.class.st
  src/ThreadedFFI-Tests/TFLongTestStruct.class.st
  src/UnifiedFFI-Tests/FFITestArrayStructure.class.st
  src/UnifiedFFI-Tests/FFITestNestingStructureWithArray.class.st
  src/UnifiedFFI-Tests/FFITestPointerStructure.class.st
  src/UnifiedFFI-Tests/FFITestStructureByPlatform.class.st
  src/UnifiedFFI/FFIStructure.class.st
Labels: Status: Tests passed please review!
