Repository pharo-project/pharo, pull requests merged in 2025-01, with the labels that each got.

#17570 17569 deprecate setparse options
  src/OpalCompiler-Core/OCCompilationContext.class.st
  src/OpalCompiler-Tests/OCCompilationContextTest.class.st
  src/Reflectivity-Tests/MetaLinkTest.class.st
  src/Reflectivity-Tools-Tests/BreakpointTest.class.st
  src/Reflectivity-Tools-Tests/VariableBreakpointMockClass.class.st
  src/Reflectivity/CompiledMethod.extension.st
  src/Reflectivity/HookGenerator.class.st
  src/Reflectivity/MetaLink.class.st
  src/Reflectivity/OCCompilationContext.extension.st
  src/Reflectivity/OCMethodNode.extension.st
Labels: more-information-needed

#17285 [Backport to P12] Improve word-by-word text navigation + tests
  bootstrap/scripts/upload_to_files.pharo.org.sh
  src/NECompletion-Tests/CompletionEngineTest.class.st
  src/Rubric-Tests/RubTextEditorTest.class.st
  src/Rubric/RubTextEditor.class.st
Labels: Status: Need more work

#17580 Symbol should not depend on AST (Fix dependency test)
  src/AST-Core/Symbol.extension.st
  src/Collections-Strings/Symbol.class.st
Labels: Status: Tests passed please review!

#17476 New cursor jumping
  src/Kernel/Character.class.st
  src/Morphic-Core/UserInputEvent.class.st
  src/Morphic-Widgets-Windows/SystemWindow.class.st
  src/Rubric-Tests/RubTextEditorTest.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Rubric/RubTextEditor.class.st
Labels: Status: Need more work

#17469 Move compiled method installation code from compile to install step
  src/OpalCompiler-Core/Behavior.extension.st
  src/OpalCompiler-Core/OpalCompiler.class.st
  src/Reflectivity/ReflectiveMethod.class.st
Labels: Project: Bootstrap

#17595 Trying to make sure that we get the correct method class once we set …
  src/AST-Core-Tests/OCParserTest.class.st
  src/AST-Core/OCMethodNode.class.st
Labels: Status: Tests passed please review!

#17592 Remove some methods with equivalent in superclass in Calypso
  src/Calypso-SystemQueries/ClyScopedSystemEnvironment.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/SystemCommands-ClassCommands/SycCmCopyClassNameCommand.class.st
  src/SystemCommands-ClassCommands/SycRemoveClassCommand.class.st
  src/SystemCommands-MessageCommands/SycRemoveMessageArgumentCommand.class.st
  src/SystemCommands-MessageCommands/SycShowLocalSendersCommand.class.st
  src/SystemCommands-MessageCommands/SycSuperclassImplementorsCommand.class.st
  src/SystemCommands-MethodCommands/SycRemoveMethodCommand.class.st
  src/SystemCommands-PackageCommands/SycPackageCommand.class.st
Labels: Status: Tests passed please review!

#17621 Move LocalProcessException and LocalRecursionStopper to debugger packages
  src/Debugging-Core/LocalProcessException.class.st
  src/Debugging-Utils/LocalRecursionStopper.class.st
Labels: Status: Tests passed please review!

#17619 Clean TransferMorph
  src/Morphic-Base/TransferMorph.class.st
  src/ReleaseTests/ReleaseTest.class.st
Labels: Status: Tests passed please review!

#17615 Backport fix making #loadVersionFromFileNamed: on MCRemoteFileBasedRepository always answer the version
  src/Monticello-Tests/MCSmalltalkhubRepositoryTest.class.st
  src/MonticelloRemoteRepositories/MCRemoteFileBasedRepository.class.st
Labels: backport

#17628 Calypso: Fix remove protocol when there is no method in the protocol
  src/Calypso-SystemQueries/ClyMethodGroup.class.st
  src/Calypso-SystemQueries/ClyMethodsInProtocolGroup.class.st
  src/Calypso-SystemTools-FullBrowser/ClyRemoveMethodGroupCommand.class.st
Labels: Status: Tests passed please review!

#17649 Branch: MakingDrTestMemorizingSize.
  src/DrTests/AbstractDrTestsPresenter.class.st
  src/DrTests/DrTests.class.st
  src/DrTests/MiniDrTests.class.st
Labels: more-information-needed

#17632 Remove dead code
  src/Debugger-Model/DebugSession.class.st
  src/DrTests/DTReRunConfiguration.class.st
  src/Keymapping-KeyCombinations/KMAltModifier.class.st
  src/Keymapping-KeyCombinations/KMCommandModifier.class.st
  src/Keymapping-KeyCombinations/KMComposedModifier.class.st
  src/Keymapping-KeyCombinations/KMCtrlModifier.class.st
  src/Keymapping-KeyCombinations/KMKeyCombination.class.st
  src/Keymapping-KeyCombinations/KMMetaModifier.class.st
  src/Keymapping-KeyCombinations/KMModifier.class.st
  src/Keymapping-KeyCombinations/KMShiftModifier.class.st
  src/Morphic-Base/MenuItemMorph.class.st
  src/Morphic-Base/StringMorph.class.st
  src/Morphic-Widgets-Extra/DockingBarMenuItemMorph.class.st
  src/Morphic-Widgets-Extra/DockingBarToggleMenuItemMorph.class.st
  src/Morphic-Widgets-Tree/MorphTreeMorph.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/Rubric-SpecFindReplaceDialog/SpRubFindReplaceDialog.class.st
Labels: Status: Tests passed please review!

#17630 Update word navigation to handle different character groups
  src/Kernel/Character.class.st
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion-Tests/CompletionEngineTest.class.st
  src/Rubric-Tests/RubTextEditorTest.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Rubric/RubTextEditor.class.st
Labels: Status: Need more work

#17663 Move OCBytecodeDecompilerExamplesTest to Flashback
  src/Flashback-Decompiler-Tests/FBDBytecodeDecompilerExamplesTest.class.st
Labels: Status: Tests passed please review!

#17664 Move OpalCompiler-UI tests to OpalCompiler-UI-Tests
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/OpalCompiler-UI-Tests/OCCodeReparatorTest.class.st
  src/OpalCompiler-UI-Tests/package.st
Labels: Status: Tests passed please review!

#17679 17677 pharo syntax tutorial testtest divide two by zero signals zero divide
  src/ProfStef-Core/PharoSyntaxTutorial.class.st
  src/ProfStef-Tests/PharoSyntaxTutorialTest.class.st
Labels: more-information-needed

#17678 Move (OC)DoItVariable to the compiler
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/Kernel-CodeModel/PseudoVariable.class.st
  src/OpalCompiler-Core/LocalVariable.class.st
  src/OpalCompiler-Core/OCDoItVariable.class.st
  src/OpalCompiler-Core/PseudoVariable.extension.st
  src/OpalCompiler-Tests/OCDoItVariableTest.class.st
  src/Shout/DoItVariable.extension.st
  src/Shout/OCDoItVariable.extension.st
Labels: Status: Tests passed please review!

#17665 AST-Core-Tests should not depend on Monticello
  src/AST-Core-Tests/OCCodeSnippetTest.class.st
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/Monticello-Tests/OCCodeSnippetTest.extension.st
  src/System-Dependencies-Tests/SystemDependenciesTest.class.st
Labels: Status: Tests passed please review!

#17683 Cleaning Presenter
  src/Athens-Examples/AthensDemoPresenter.class.st
  src/EpiceaBrowsers/EpDashboardPresenter.class.st
  src/EpiceaBrowsers/EpLogBrowserPresenter.class.st
  src/EpiceaBrowsers/EpUnifiedBrowserPresenter.class.st
  src/IconPacks/SpIconPacksFetchPresenter.class.st
  src/Keymapping-Tools-Spec/KMDescriptionPresenter.class.st
  src/Refactoring-UI/StClassAndMethodsSelectionPresenter.class.st
  src/Refactoring-UI/StRefactoringAddClassPresenter.class.st
  src/Refactoring-UI/StRefactoringPreviewPresenter.class.st
  src/Refactoring-UI/StRequestClassPresenter.class.st
  src/Reflectivity-Examples/CoverageDemoPresenter.class.st
  src/Reflectivity-Tools/WatchesWindowPresenter.class.st
  src/Rubric-SpecFindReplaceDialog/SpRubFindReplaceDialog.class.st
  src/Shout-UI/SHStylePresenter.class.st
  src/Tool-DependencyAnalyser-UI-Tab/DATabPackageDependenciesPresenter.class.st
  src/Tool-DependencyAnalyser-UI/DACycleDetectionTreePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DADependencyTreePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAReverseTreePresenter.class.st
  src/Tool-DependencyAnalyser-UI/DAWelcomePresenter.class.st
  src/Tool-ExternalBrowser/ExternalBrowser.class.st
  src/Tool-ExternalBrowser/ExternalChangesBrowser.class.st
Labels: more-information-needed

#17686 Do not restore ffi methods if they are not installed
  src/ThreadedFFI-UFFI-Tests/TFFITraitForTest.trait.st
  src/ThreadedFFI-UFFI-Tests/TFUFFIMethodRegistryTest.class.st
  src/ThreadedFFI-UFFI-Tests/TFUFFITestClassWithTrait.class.st
  src/UnifiedFFI/FFIMethodRegistry.class.st
Labels: Status: Need more work

#17654 Transformations cleanup: better preview API and updated class comments
  src/Refactoring-Changes/RBCompositeRefactoryChange.class.st
  src/Refactoring-Changes/RBRefactoryChange.class.st
  src/Refactoring-Changes/RBRefactoryClassChange.class.st
  src/Refactoring-Changes/RBRefactoryPackageChange.class.st
  src/Refactoring-Core/RBRefactoryTyper.class.st
  src/Refactoring-Transformations-Tests/RBRemoveMethodRefactoringTest.class.st
  src/Refactoring-Transformations/RBAddAccessorsForClassTransformation.class.st
  src/Refactoring-Transformations/RBAddAssignmentTransformation.class.st
  src/Refactoring-Transformations/RBAddClassCommentTransformation.class.st
  src/Refactoring-Transformations/RBAddMessageSendTransformation.class.st
  src/Refactoring-Transformations/RBAddMethodCommentTransformation.class.st
  src/Refactoring-Transformations/RBAddMethodTransformation.class.st
  src/Refactoring-Transformations/RBAddPragmaTransformation.class.st
  src/Refactoring-Transformations/RBAddProtocolTransformation.class.st
  src/Refactoring-Transformations/RBAddReturnStatementTransformation.class.st
  src/Refactoring-Transformations/RBAddSubtreeTransformation.class.st
  src/Refactoring-Transformations/RBAddTemporaryVariableTransformation.class.st
  src/Refactoring-Transformations/RBAddVariableAccessorTransformation.class.st
  src/Refactoring-Transformations/RBAddVariableAccessorWithLazyInitializationTransformation.class.st
  src/Refactoring-Transformations/RBAddVariableTransformation.class.st
  src/Refactoring-Transformations/RBChangeMethodNameTransformation.class.st
  src/Refactoring-Transformations/RBCustomTransformation.class.st
  src/Refactoring-Transformations/RBDeprecateClassTransformation.class.st
  src/Refactoring-Transformations/RBDeprecateMethodTransformation.class.st
  src/Refactoring-Transformations/RBInsertNewClassTransformation.class.st
  src/Refactoring-Transformations/RBMethodProtocolTransformation.class.st
  src/Refactoring-Transformations/RBMoveClassTransformation.class.st
  src/Refactoring-Transformations/RBMoveInstanceVariableToClassTransformation.class.st
  src/Refactoring-Transformations/RBMoveMethodToClassSideTransformation.class.st
  src/Refactoring-Transformations/RBMoveMethodToClassTransformation.class.st
  src/Refactoring-Transformations/RBMoveMethodTransformation.class.st
  src/Refactoring-Transformations/RBMoveTemporaryVariableDefinitionTransformation.class.st
  src/Refactoring-Transformations/RBProtectVariableTransformation.class.st
  src/Refactoring-Transformations/RBPullUpVariableTransformation.class.st
  src/Refactoring-Transformations/RBPushDownVariableTransformation.class.st
  src/Refactoring-Transformations/RBRemoveAllMessageSendsTransformation.class.st
  src/Refactoring-Transformations/RBRemoveAssignmentTransformation.class.st
  src/Refactoring-Transformations/RBRemoveClassTransformation.class.st
  src/Refactoring-Transformations/RBRemoveDirectAccessToVariableTransformation.class.st
  src/Refactoring-Transformations/RBRemoveMethodTransformation.class.st
  src/Refactoring-Transformations/RBRemovePragmaTransformation.class.st
  src/Refactoring-Transformations/RBRemoveProtocolTransformation.class.st
  src/Refactoring-Transformations/RBRemoveReturnStatementTransformation.class.st
  src/Refactoring-Transformations/RBRemoveSubtreeTransformation.class.st
  src/Refactoring-Transformations/RBRemoveTemporaryVariableTransformation.class.st
  src/Refactoring-Transformations/RBRemoveVariableTransformation.class.st
  src/Refactoring-Transformations/RBRenameAndDeprecateClassTransformation.class.st
  src/Refactoring-Transformations/RBRenamePackageTransformation.class.st
  src/Refactoring-Transformations/RBRenameTemporaryVariableTransformation.class.st
  src/Refactoring-Transformations/RBRenameVariableTransformation.class.st
  src/Refactoring-Transformations/RBReplaceSubtreeTransformation.class.st
  src/Refactoring-Transformations/RBSplitClassTransformation.class.st
  src/Refactoring-Transformations/RBTemporaryToInstanceVariableTransformation.class.st
  src/Refactoring-Transformations/ReAddSuperSendAsFirstStatementTransformation.class.st
  src/Refactoring-Transformations/ReCompositeExtractMethodRefactoring.class.st
  src/Refactoring-UI-Tests/ReDuplicateClassDriverTest.class.st
  src/Refactoring-UI-Tests/StRefactoringPreviewPresenterMock.class.st
  src/Refactoring-UI/ReInteractionDriver.class.st
  src/Refactoring-UI/StRefactoringPreviewPresenter.class.st
Labels: Status: Tests passed please review!

#17709 Bring back 'Fit all' menu item
  src/Morphic-Base/WorldState.extension.st
Labels: Status: Tests passed please review!

#17700 Cleanup refactorings
  src/Refactoring-Core/RePullUpInstanceVariableRefactoring.class.st
  src/Refactoring-Core/ReRemoveMethodsInHierarchyRefactoring.class.st
  src/Refactoring-Core/ReVariableNameCondition.class.st
  src/Refactoring-UI/ReRemoveInstanceVariablesDriver.class.st
Labels: Status: Tests passed please review!

#17705 Depends on Roassal branch Pharo13
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: Status: Tests passed please review!

#17676 Branch: RedoingClosePresenter, Deleted everything so SpClosedWindowListPresenter can be independant
  src/Morphic-Base/WorldState.extension.st
  src/Morphic-Widgets-Windows/SystemWindow.class.st
  src/Polymorph-Widgets/UITheme.class.st
Labels: Status: Need more work

#17718 Introduced customization of closing window
  src/Morphic-Widgets-Windows/SystemWindow.class.st
  src/Polymorph-Widgets/UITheme.class.st
  src/Rubric-SpecFindReplaceDialog/SpRubFindReplaceDialog.class.st
Labels: more-information-needed
