Repository pharo-project/pharo, pull requests merged in 2025-08, with the labels that each got.

#18458 Replaces initializePackages command with bootstrap fixMethods clap command
  bootstrap/scripts/4-build.sh
  bootstrap/scripts/runKernelTests.sh
  src/Clap-CommandLine/ClapPharoBootstrapCommand.class.st
  src/Clap-Commands-Pharo/ClapPharoVersion.class.st
  src/Clap-Core/ClapContext.class.st
  src/Clap-Tests/ClapPharoFixMethodsCommandTest.class.st
  src/InitializePackagesCommandLineHandler/ClapPharoFixMethodsCommand.class.st
  src/InitializePackagesCommandLineHandler/InitializePackagesCommandLineHandler.class.st
  src/Kernel-CodeModel/CompiledMethod.class.st
  src/System-BasicCommandLineHandler/BasicCommandLineHandler.class.st
Labels: Status: Tests passed please review!

#18462 fix errors in CI due to incomplete regex for stamps (could have 5 or 6 digits at the end)
  src/Monticello-Tests/MCStWriterTest.class.st
Labels: more-information-needed

#18452 Improve Iceberg opening management
  src/Calypso-SystemPlugins-Monticello-Browser/ClyCommitPackageCommand.class.st
  src/Tool-Registry/PharoCommonTools.class.st
Labels: Status: Tests passed please review!

#18373 Enh/generic workspace heuristic
  src/HeuristicCompletion-Model/CoGenericWorkspaceHeuristic.class.st
Labels: backport

#18504 Fixes #18482 Cannot push up a class var.
  src/Refactoring-Core/RBChildrenToSiblingsRefactoring.class.st
  src/Refactoring-Core/ReDefinesInstanceVariableCondition.class.st
  src/Refactoring-Core/ReDirectlyDefinesInstanceVariableCondition.class.st
  src/Refactoring-Core/ReDirectlyDefinesSharedVariableCondition.class.st
  src/Refactoring-Core/ReHierarchyDefinesInstanceVariableCondition.class.st
  src/Refactoring-Core/ReHierarchyDefinesSharedVariableCondition.class.st
  src/Refactoring-Core/RePullUpMethodRefactoring.class.st
  src/Refactoring-Core/RePullUpSharedVariableRefactoring.class.st
  src/Refactoring-Transformations-Tests/RBPullUpClassVariableParametrizedTest.class.st
  src/Refactoring-UI/RePushUpVariableDriver.class.st
  src/SystemCommands-VariableCommands/RePullUpInstanceVariableRefactoring.extension.st
  src/SystemCommands-VariableCommands/SycPushUpVariableCommand.class.st
Labels: Status: Tests passed please review!
