Repository pharo-project/pharo, pull requests merged in 2025-07, with the labels that each got.

#18359 Refactor: migrating and cleaning Inline Method refactoring
  src/Refactoring-Core/RBInlineMethodFromComponentRefactoring.class.st
  src/Refactoring-Core/RBInlineMethodRefactoring.class.st
  src/Refactoring-Core/RBRemoveSenderRefactoring.class.st
  src/Refactoring-Core/ReRenameClassRefactoring.class.st
Labels: Status: Tests passed please review!

#18348 fix: up/down cursor motion didn't move directly up/down in the presence of tab characters
  src/Rubric-Tests/RubTextEditorTest.class.st
  src/Rubric/RubTextEditor.class.st
  src/System-Dependencies-Tests/SystemDependenciesTest.class.st
Labels: Status: Need more work

#17583 [PortToP11] 17029-Image-crash-or-errors-when-openning-another-developper-Pharo-11-image
  src/ThreadedFFI-UFFI-Tests/TFUFFIConcurrencyTest.class.st
  src/UnifiedFFI/FFICalloutAPI.class.st
Labels: more-information-needed

#18365 Fix inline variable shadowing
  src/OpalCompiler-Core/OCASTTranslator.class.st
  src/OpalCompiler-Core/OCAbstractMethodScope.class.st
  src/OpalCompiler-Tests/OCClosureCompilerTest.class.st
  src/ReleaseTests/ReleaseTest.class.st
Labels: Status: Tests passed please review!

#18437 Fix auto refactoring
  src/AST-Core/String.extension.st
Labels: Company: Thales
