Repository pharo-project/pharo, pull requests merged in 2025-02, with the labels that each got.

#17735 Branch: 17675-Opal-Extension-symbolic-to-Debugging-Core
  src/Debugging-Core/CompiledCode.extension.st
Labels: more-information-needed

#17743 Skipping two tests to get the green bar for now.
  src/DrTests-Tests/DrTestsUITest.class.st
Labels: more-information-needed

#17769 Fix testMethodsOfTheClassShouldNotBeRepeatedInItsSuperclasses
  src/OpalCompiler-Core/CompiledMethod.extension.st
Labels: Status: Tests passed please review!

#17763 Fix opening of the Dependency analyzer
  src/Calypso-SystemPlugins-Critic-Browser/ClyShowDependencyCritiqueCommand.class.st
Labels: Status: Tests passed please review!

#17764 Fix browsing of methods in Epicea
  src/EpiceaBrowsers/EpBrowseVisitor.class.st
Labels: Status: Tests passed please review!

#17707 Move System-SourcesCondenser later in the loading order
  bootstrap/scripts/4-build.sh
  src/BaselineOfMisc/BaselineOfMisc.class.st
  src/BaselineOfPharoBootstrap/BaselineOfPharoBootstrap.class.st
  src/System-SourcesCondenser/ManifestSystemSourcesCondenser.class.st
  src/System-SourcesCondenser/PharoChangesCondenser.class.st
Labels: Status: Tests passed please review!

#17773 Fix and improve WindowAnnouncementTest
  src/Morphic-Tests/WindowAnnouncementTest.class.st
Labels: Status: Tests passed please review!

#17775 [Backport] Fix cursor navigation
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion-Tests/CompletionEngineTest.class.st
  src/Rubric-Tests/RubTextEditorTest.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Rubric/RubTextEditor.class.st
  src/SUnit-Core-Traits/TAssertable.trait.st
  src/SUnit-Core/TestAsserter.class.st
Labels: Status: Need more work

#17791 Clean tool registry2
  src/MenuRegistration/MenuRegistrationExample.class.st
  src/Morphic-Base/PluggableMenuSpec.extension.st
  src/Morphic-Core/Morph.class.st
  src/Network-Kernel/Socket.class.st
  src/Network-Protocols/ProtocolClient.class.st
  src/Polymorph-Widgets/MorphicUIManager.class.st
  src/Tool-Base/ToolShortcutsCategory.class.st
  src/Tool-ProcessBrowser/ProcessBrowser.class.st
  src/Tool-Registry/PharoCommonTools.class.st
  src/Tool-Registry/ToolRegistry.class.st
  src/Tools-Tests/InspectTest.class.st
  src/Tools-Tests/OpenToolTest.class.st
  src/Tools/Object.extension.st
  src/Transcript-Tool/ThreadSafeTranscript.extension.st
Labels: more-information-needed

#17794 EnhancingMockInCoCompletionTests
  src/HeuristicCompletion-Tests/CoCompletionEngineTest.class.st
  src/HeuristicCompletion-Tests/CoMockClass.class.st
  src/HeuristicCompletion-Tests/CoMockMethod.class.st
  src/HeuristicCompletion-Tests/CoMockPackage.class.st
Labels: more-information-needed

#17797 2025 02 06 remove recent tools
  src/Calypso-SystemTools-QueryBrowser/ClyBrowserMorph.extension.st
  src/DebugPoints/DebugPointInstanceVariableTarget.class.st
  src/Deprecated13/ToolShortcutsCategory.extension.st
  src/DrTests-TestsRunner/TestCase.extension.st
  src/DrTests/ClassDescription.extension.st
  src/DrTests/CompiledMethod.extension.st
  src/EpiceaBrowsers/EpBrowseVisitor.class.st
  src/MenuRegistration/MenuRegistrationExample.class.st
  src/MonticelloGUI/PSMCMergePatchMorph.class.st
  src/Morphic-Base/FallbackMenu.class.st
  src/Morphic-Core/Morph.class.st
  src/Morphic-Examples/ClassListNodeExample.class.st
  src/Morphic-Examples/ClassTreeNodeExample.class.st
  src/Morphic-Examples/PackageClassNodeExample.class.st
  src/Morphic-Examples/PackageMethodNodeExample.class.st
  src/Morphic-Widgets-Basic/PluggableButtonMorph.class.st
  src/NECompletion/NECSelectorEntry.class.st
  src/NECompletion/NECSymbolEntry.class.st
  src/NECompletion/NECVariableEntry.class.st
  src/PharoDocComment-Tests/CommentTestCase.class.st
  src/Reflectivity-Tools/WatchesWindowPresenter.class.st
  src/Reflectivity/Breakpoint.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/SUnit-Support-UITesting-Tests/SimulateKeystrokesTest.class.st
  src/SUnit-Support-UITesting-Tests/SimulateMouseTest.class.st
  src/System-Settings-Browser/SettingNode.class.st
  src/SystemCommands-MessageCommands/SycShowLocalSendersCommand.class.st
  src/SystemCommands-MessageCommands/SycSuperclassImplementorsCommand.class.st
  src/SystemCommands-MethodCommands/SycShowMethodVersionCommand.class.st
  src/Tool-Base/Package.extension.st
  src/Tool-Base/RGBehaviorDefinition.extension.st
  src/Tool-Base/RGElementDefinition.extension.st
  src/Tool-Base/RGMethodDefinition.extension.st
  src/Tool-Base/SystemNavigation.extension.st
  src/Tool-Base/ToolShortcutsCategory.class.st
  src/Tool-DependencyAnalyser-UI/DANode.class.st
  src/Tool-DependencyAnalyser-UI/DAPackageTreePresenter.class.st
  src/Tool-ProcessBrowser/CPUWatcher.class.st
  src/Tool-ProcessBrowser/ProcessBrowser.class.st
  src/Tool-Profilers/SmalltalkImage.extension.st
  src/Tool-Profilers/TimeProfilerNode.class.st
  src/Tool-Registry/PharoCommonTools.class.st
  src/Tool-Registry/ToolRegistry.class.st
  src/Tools/Behavior.extension.st
  src/Tools/CompiledBlock.extension.st
  src/Tools/Object.extension.st
  src/Tools/PackageTag.extension.st
Labels: more-information-needed

#17798 Last old methods of PharoCommonTools
  src/Tool-Registry/PharoCommonTools.class.st
  src/Tool-Registry/ToolRegistry.class.st
Labels: more-information-needed

#17805 Fix duplicate package when no starting acronym
  src/Refactoring-Core/RBRegexRefactoring.class.st
  src/Refactoring-Transformations-Tests/RBRegexTest.class.st
Labels: more-information-needed

#17817 Remove a usage of an old icon name
  src/Morphic-Widgets-Windows/SystemWindow.class.st
Labels: Easy, Status: Tests passed please review!

#17840 Fix dependency test
  src/Graphics-Display Objects/Form.class.st
  src/Text-Core/Form.extension.st
  src/Text-Core/TextAnchor.class.st
Labels: Status: Tests passed please review!

#17842 Remove a few methods with equivalent in superclass
  src/General-Rules/ReThemeAccessRule.class.st
  src/ReleaseTests/ReleaseTest.class.st
  src/Ring-Core/RGObject.class.st
  src/Ring-Definitions-Core/RGDefinition.class.st
Labels: Status: Tests passed please review!

#17841 Fix setting breakpoints
  src/Reflectivity/MetaLink.class.st
Labels: Status: Tests passed please review!

#17843 Fix Message not understood when opening Full Environment on Calypso
  src/Refactoring-Environment/RBBrowserEnvironment.class.st
Labels: Status: Tests passed please review!

#17867 Trying to change the default of DependencyAnalyser and loading it
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/BaselineOfIDE/BaselineOfIDE.class.st
  src/BaselineOfPharo/BaselineOfPharo.class.st
Labels: more-information-needed

#17759 P12 fix windows tab shortcut
  src/Morphic-Base/Morph.extension.st
  src/Morphic-Core/Morph.class.st
  src/Morphic-Core/WorldMorph.class.st
  src/Morphic-Widgets-Taskbar-Tests/TaskListMorphTest.class.st
  src/Morphic-Widgets-Taskbar-Tests/TaskMorphTest.class.st
  src/Morphic-Widgets-Taskbar-Tests/TaskbarMorphTest.class.st
  src/Morphic-Widgets-Taskbar/TaskListMorph.class.st
  src/Morphic-Widgets-Taskbar/UITheme.extension.st
  src/Polymorph-Widgets/UITheme.class.st
Labels: Status: Tests passed please review!

#17864 Improve error on File deletion failure
  src/Files/File.class.st
Labels: Status: Tests passed please review!

#17668 Removing the fact that ### equals #
  src/AST-Core-Tests/OCScannerTest.class.st
  src/AST-Core/OCScanner.class.st
Labels: more-information-needed

#17896 17895-Better-hook-for-completion-engine-in-RubSmalltalkTextEditor
  src/Rubric-Tests/RubSmalltalkEditorTest.class.st
  src/Rubric/RubSmalltalkEditor.class.st
Labels: more-information-needed

#17863 Push up #classInstaller
  src/Kernel-CodeModel/Class.class.st
  src/Kernel-CodeModel/ClassDescription.class.st
Labels: Status: Tests passed please review!

#17795 Improve FLBasicSerializationTest>>#testWideStringClassName
  src/Fuel-Core-Tests/FLBasicSerializationTest.class.st
Labels: Status: Tests passed please review!

#17247 Cleanup Shout
  src/Shout/SHRBTextStyler.class.st
Labels: Status: Need more work

#17900 Cleaning opal
  src/AST-Core-Tests/OCMethodNodeTest.class.st
  src/AST-Core-Tests/OCParseTreeTest.class.st
  src/AST-Core-Tests/OCProgramNodeTest.class.st
  src/AST-Core-Tests/OCSimpleFormatterTest.class.st
  src/AST-Core/OCMessageNode.class.st
  src/AST-Core/OCMethodNode.class.st
  src/AST-Core/OCSequenceNode.class.st
  src/CodeImport/OldClassDefinitionBuilder.class.st
  src/OpalCompiler-Tests/MethodPragmaTest.class.st
  src/OpalCompiler-Tests/OCArrayLiteralTest.class.st
  src/OpalCompiler-Tests/OCIRBuilderTest.class.st
  src/OpalCompiler-Tests/OCSourceCode2BytecodeTest.class.st
  src/OpalCompiler-Tests/OCStaticASTCompilerPluginTest.class.st
  src/OpalCompiler-ToolFeatures-Tests/OCReturnNodeAdderVisitorTest.class.st
  src/Refactoring-Core-Tests/OCIsEssentialTest.class.st
  src/Refactoring-Core/OCMethodNode.extension.st
  src/Refactoring-Transformations/OCSequenceNode.extension.st
  src/Ring-ChunkImporter/RGChunkImporter.class.st
  src/Rubric-SpecFindReplaceDialog/SpRubFindReplaceDialog.class.st
  src/SystemCommands-MessageCommands/SycMessageDescription.class.st
Labels: Status: Tests passed please review!

#17907 Removing misplaced browing methods, Fixes # 17396
  src/DebugPoints/DebugPoint.class.st
  src/DebugPoints/DebugPointInstanceVariableTarget.class.st
  src/DebugPoints/DebugPointNodeTarget.class.st
  src/DebugPoints/DebugPointObjectTarget.class.st
  src/DebugPoints/DebugPointTarget.class.st
Labels: Status: Tests passed please review!
