Repository pharo-project/pharo, pull requests merged in 2025-03, with the labels that each got.

#17909 Fix: OpalCompilerTest and others should not hard code Smalltalk compiler
  src/OpalCompiler-Tests/OpalCompilerTest.class.st
Labels: Status: Tests passed please review!

#17901 Branch: adding-isValid-for-SDLWindows
  src/OSWindow-SDL2/OSSDL2BackendWindow.class.st
  src/OSWindow-SDL2/SDL2Handle.class.st
Labels: Status: Tests passed please review!

#17917 17916-Adding-deprecated-binding-to-IR
  src/AST-Core-Tests/OCMethodNodeTest.class.st
  src/BaselineOfBasicTools/BaselineOfBasicTools.class.st
  src/OpalCompiler-Core/IRBuilder.class.st
Labels: Status: Tests passed please review!

#17910 Branch: Fix-Baseline-CoStaticBenchmarks, Adding the `HeuristicComple…
  src/BaselineOfHeuristicCompletion/BaselineOfHeuristicCompletion.class.st
  src/HeuristicCompletion-Benchmarks/CoStaticBenchmarksMessage.class.st
  src/HeuristicCompletion-Benchmarks/CoStaticBenchmarksVariables.class.st
Labels: Status: Tests passed please review!

#17914 Completion improvements: do not skip closing characters
  src/NECompletion-Morphic/CompletionEngine.class.st
  src/NECompletion-Tests/CompletionEngineTest.class.st
  src/Rubric/RubSmalltalkEditor.class.st
  src/Rubric/RubTextEditor.class.st
Labels: Status: Tests passed please review!

#17933 Improve ReRefersToClassRule name
  src/General-Rules/ReRefersToClassRule.class.st
Labels: Status: Tests passed please review!

#17913 Fix issue 17908 - Rename argument
  src/Refactoring-Core/ReRenameMethodRefactoring.class.st
  src/Refactoring-UI/ReRenameMethodDriver.class.st
  src/Refactoring-UI/StMethodNameEditorPresenter.class.st
Labels: Status: Tests passed please review!

#17925 Push up #removeFromTree from MessageNode to ProgramNode
  src/AST-Core/OCMessageNode.class.st
  src/AST-Core/OCProgramNode.class.st
Labels: Status: Tests passed please review!

#17950 Fixing dependency analyser opening
  src/Calypso-SystemPlugins-DependencyAnalyser-Browser/ClyOpenDependencyBrowserCommand.class.st
Labels: more-information-needed

#17943 Use ShellExecuteW instead of ShellExecuteA for NativeBrowserOpenVisitor
  src/Native-Browser/NativeBrowserOpenVisitor.class.st
Labels: Status: Tests passed please review!

#18009 fix undeclared
  src/Calypso-SystemPlugins-Critic-Browser/ClyShowDependencyCritiqueCommand.class.st
Labels: more-information-needed

#18019 17861 transcript open via the menu is broken
  src/MenuRegistration/MenuRegistrationExample.class.st
  src/Polymorph-Widgets/MorphicUIManager.class.st
  src/Rubric-SpecFindReplaceDialog/SpRubFindReplaceDialog.class.st
  src/Tool-Registry/ToolRegistry.class.st
  src/Transcript-Core/ThreadSafeTranscript.class.st
  src/Transcript-Tool/ThreadSafeTranscript.extension.st
Labels: more-information-needed

#18041 Protecting tests so that their execution is independant
  src/Debugging-Utils-Tests/HaltTest.class.st
  src/Debugging-Utils/Halt.class.st
Labels: more-information-needed

#18032 Improved ReSearchingLiteralRule by giving an example in description & added automatic transformation
  src/General-Rules/ReSearchingLiteralRule.class.st
Labels: Status: Need more work

#18042 Introduce Morphic-Deprecated
  src/BaselineOfPharo/BaselineOfPharo.class.st
  src/Morphic-Deprecated/ManifestMorphicDeprecated.class.st
  src/Morphic-Deprecated/TEasilyThemed.extension.st
  src/Morphic-Deprecated/UITheme.extension.st
  src/Morphic-Deprecated/package.st
  src/Morphic-Examples/WidgetExample.class.st
  src/Polymorph-Widgets/TEasilyThemed.trait.st
  src/Polymorph-Widgets/UITheme.class.st
Labels: Status: Tests passed please review!

#17979 Move HashTesterTest to SUnit-Tests
  src/SUnit-Tests/HashTesterTest.class.st
Labels: Status: Tests passed please review!

#17931 [Backport #17928] Fix bug with obsolete classes and extension methods
  src/Kernel-CodeModel-Tests/PackageTest.class.st
  src/Kernel-CodeModel/ClassDescription.class.st
Labels: Status: Tests passed please review!

#18053 17641-DemoCoveragePresenter-open DNU fix
  src/Reflectivity-Examples/ReflectivityCodeMorph.class.st
Labels: Status: Tests passed please review!
