Repository pharo-project/pharo, pull requests merged in 2025-06, with the labels that each got.

#18143 Remove dead code un UIManager
  src/Debugger-Oups-Tests/OupsDummyDebuggerSystem.class.st
  src/Debugger-Oups/OupsDebuggerSystem.class.st
  src/Files-Prompt/DummyUIManager.extension.st
  src/Files-Prompt/UIManager.extension.st
  src/Polymorph-Widgets/MorphicUIManager.class.st
  src/UIManager/CommandLineUIManager.class.st
  src/UIManager/DummyUIManager.class.st
  src/UIManager/NonInteractiveUIManager.class.st
  src/UIManager/UIManager.class.st
Labels: Status: Tests passed please review!

#18233 Fix some release tests
  src/SUnit-MockObjects/MockUnorderedObject.class.st
Labels: Status: Tests passed please review!

#18243 [Pharo13] Adding validation of the hierarchy for all the slots
  src/Shift-ClassBuilder-Tests/ManifestShiftClassBuilderTests.class.st
  src/Shift-ClassBuilder-Tests/ShCBAClasWithAnSlot.class.st
  src/Shift-ClassBuilder-Tests/ShCBAClasWithAnotherSlot.class.st
  src/Shift-ClassBuilder-Tests/ShCBClassWithSubclass.class.st
  src/Shift-ClassBuilder-Tests/ShCBSubClassWithInstanceVariable.class.st
  src/Shift-ClassBuilder-Tests/ShCBSubSubClassWithInstanceVariable.class.st
  src/Shift-ClassBuilder-Tests/ShModifyClassTest.class.st
  src/Shift-ClassBuilder/ShLayoutDefinition.class.st
Labels: Version: Pharo 13

#18257 Add comment to Class>>#rename:
  src/Kernel-CodeModel/Class.class.st
Labels: Status: Tests passed please review!

#18268 Improve assertions of MCStWriterTest>>#testClassMethodDefinition
  src/Monticello-Tests/MCStWriterTest.class.st
Labels: Status: Tests passed please review!

#18278 Fix MessagTally>>exampleSpyForSeconds
  src/Tool-Profilers-Tests/MessageTallyTest.class.st
  src/Tool-Profilers/MessageTally.class.st
Labels: Status: Tests passed please review!

#18109 Cut cyclic dependency in Zinc
  src/System-Dependencies-Tests/SystemDependenciesTest.class.st
  src/Zinc-Resource-Meta-Core/ZnConstants.class.st
  src/Zinc-Resource-Meta-Core/ZnCurrentOptions.class.st
  src/Zinc-Resource-Meta-Core/ZnOptions.class.st
  src/Zinc-Resource-Meta-Tests/ZnOptionsTest.class.st
Labels: Status: Tests passed please review!

#18290 Backport #18289 to P13: Fix Duplicate class refactoring
  src/Refactoring-UI-Tests/StClassAndMethodsSelectionPresenterTest.class.st
  src/Refactoring-UI-Tests/StRefactoringAddClassPresenterTest.class.st
  src/Refactoring-UI-Tests/StRequestClassPresenterTest.class.st
  src/Refactoring-UI/StRefactoringAddClassPresenter.class.st
  src/Refactoring-UI/StRequestClassPresenter.class.st
Labels: Status: Tests passed please review!

#18306 Improve Epicea search
  src/Epicea/EpCodeChange.class.st
  src/EpiceaBrowsers/EpLogBrowserPresenter.class.st
Labels: Status: Tests passed please review!

#18309 Adding trim* API to Text to be polymorphic to String.
  src/Text-Core/Text.class.st
  src/Text-Tests/TextTest.class.st
Labels: more-information-needed

#18141 Simplify Stream API
  src/Collections-Streams/Stream.class.st
  src/Deprecated14/Stream.extension.st
  src/Kernel/Character.class.st
  src/System-CommandLine/VTermOutputDriver.class.st
Labels: Status: Tests passed please review!

#18352 Add comment and executable comments to String>>copyUpToSubstring:
  src/Collections-Strings/String.class.st
Labels: more-information-needed
